In [1]:
import pandas as pd

In [2]:
pos = pd.read_excel(r'c:\Users\User\Documents\NIR3\files\Модели Сообщения (2).xlsx', sheet_name='ИД', skiprows=1)
pos = pos[(pos['ИС'] == 'ПОС')]
pos = pos.dropna(subset=['Текст'])
pos = pos.dropna(subset=['Локация (район)'])
pos = pos.rename(columns={'Дата создания': 'date', 'Текст': 'text', 'Блок по распределению': 'label_cat', 'Локация (район)': 'loc_dist', 'Адрес объекта - Не править!': 'loc_for_geocoding'})
pos['label_cat'] = pos['label_cat'].replace({'ТКО':'Отходы', 'БОС': 'Безопасность'})
pos['source'] = 'ПОС'
pos['source_cf'] = 1
pos = pos[(pos['label_cat'] != 'Не ЦУР')]
pos['loc_dist'] = pos['loc_dist'].str.replace(r' район$', '', regex=True).str.capitalize()
pos = pos[['date', 'text', 'label_cat','loc_dist', 'loc_for_geocoding', 'source', 'source_cf']]
pos

,date,text,label_cat,loc_dist,loc_for_geocoding,source,source_cf
19,2022-02-23,Бульвар-Новаторов дома 26/2 и 24/2 не убирают ...,Дороги,Кировский,Новаторов б-р 26к2,ПОС,1
20,2022-02-23,Страшно ездить во дворе. Ещё пару дней и можно...,Дороги,Пушкинский,Колпинское ш 28к1,ПОС,1
21,2022-02-23,В этом году ни разу не проводилась Уборка терр...,Дороги,Красногвардейский,6-я Жерновская ул 9к1,ПОС,1
22,2022-02-23,"Не числятся проезды вдоль дома, нет посылки. З...",Транспорт,Красносельский,Красное Село,ПОС,1
23,2022-02-23,"Здравствуйте, дороги скользкие, невозможно дой...",Дороги,Невский,Ольминского ул,ПОС,1
...,...,...,...,...,...,...,...
69401,2022-06-20,Объявления на знаках,Транспорт,Невский,Дыбенко ул,ПОС,1
69402,2022-06-20,Рисунки на асфальте,Дороги,Невский,Дыбенко ул,ПОС,1
69403,2022-06-20,Объявления на опоре освещения,Транспорт,Невский,Дыбенко ул,ПОС,1
69404,2022-06-20,Объявления на светофоре,Транспорт,Невский,Дыбенко ул,ПОС,1
69405,2022-06-20,Весь внутридворовый проезд от ул. Софьи Ковале...,Благоустройство,Калининский,NaN,ПОС,1

In [3]:
pos.to_csv(r'c:\Users\User\Documents\NIR3\files\ПОС_сообщения.csv', sep=';')

In [1]:
import pandas as pd
from geopy.geocoders import Nominatim
from geopy.extra.rate_limiter import RateLimiter
from tqdm import tqdm
import time

In [2]:
df = pd.read_csv(r'c:\Users\User\Documents\NIR3\files\ПОС_сообщения.csv', sep=';')
df

,Unnamed: 0,date,text,label_cat,loc_dist,loc_for_geocoding,source,source_cf
0,19,2022-02-23,Бульвар-Новаторов дома 26/2 и 24/2 не убирают ...,Дороги,Кировский,Новаторов б-р 26к2,ПОС,1
1,20,2022-02-23,Страшно ездить во дворе. Ещё пару дней и можно...,Дороги,Пушкинский,Колпинское ш 28к1,ПОС,1
2,21,2022-02-23,В этом году ни разу не проводилась Уборка терр...,Дороги,Красногвардейский,6-я Жерновская ул 9к1,ПОС,1
3,22,2022-02-23,"Не числятся проезды вдоль дома, нет посылки. З...",Транспорт,Красносельский,Красное Село,ПОС,1
4,23,2022-02-23,"Здравствуйте, дороги скользкие, невозможно дой...",Дороги,Невский,Ольминского ул,ПОС,1
...,...,...,...,...,...,...,...,...
21615,69401,2022-06-20,Объявления на знаках,Транспорт,Невский,Дыбенко ул,ПОС,1
21616,69402,2022-06-20,Рисунки на асфальте,Дороги,Невский,Дыбенко ул,ПОС,1
21617,69403,2022-06-20,Объявления на опоре освещения,Транспорт,Невский,Дыбенко ул,ПОС,1
21618,69404,2022-06-20,Объявления на светофоре,Транспорт,Невский,Дыбенко ул,ПОС,1
21619,69405,2022-06-20,Весь внутридворовый проезд от ул. Софьи Ковале...,Благоустройство,Калининский,NaN,ПОС,1

In [3]:
df['loc_for_geocoding'] = df['loc_for_geocoding'] + ", Санкт-Петербург"
df = df.drop_duplicates(subset=['text'])
df

,Unnamed: 0,date,text,label_cat,loc_dist,loc_for_geocoding,source,source_cf
0,19,2022-02-23,Бульвар-Новаторов дома 26/2 и 24/2 не убирают ...,Дороги,Кировский,"Новаторов б-р 26к2, Санкт-Петербург",ПОС,1
1,20,2022-02-23,Страшно ездить во дворе. Ещё пару дней и можно...,Дороги,Пушкинский,"Колпинское ш 28к1, Санкт-Петербург",ПОС,1
2,21,2022-02-23,В этом году ни разу не проводилась Уборка терр...,Дороги,Красногвардейский,"6-я Жерновская ул 9к1, Санкт-Петербург",ПОС,1
3,22,2022-02-23,"Не числятся проезды вдоль дома, нет посылки. З...",Транспорт,Красносельский,"Красное Село, Санкт-Петербург",ПОС,1
4,23,2022-02-23,"Здравствуйте, дороги скользкие, невозможно дой...",Дороги,Невский,"Ольминского ул, Санкт-Петербург",ПОС,1
...,...,...,...,...,...,...,...,...
21601,69385,2022-06-20,87 квартира делает ремонт. Вывозят мусор. От н...,ЖКХ,Центральный,"Конная ул 5/3, Санкт-Петербург",ПОС,1
21603,69388,2022-06-20,Добрый день. В мае неожиданно узнал о якобы на...,ЖКХ,Кировский,"Корнеева ул 6, Санкт-Петербург",ПОС,1
21610,69396,2022-06-20,Объявления на знаках прошу очистить,Транспорт,Невский,"Искровский пр-т, Санкт-Петербург",ПОС,1
21611,69397,2022-06-20,Объявления на мачте,Транспорт,Невский,"Искровский пр-т, Санкт-Петербург",ПОС,1
21619,69405,2022-06-20,Весь внутридворовый проезд от ул. Софьи Ковале...,Благоустройство,Калининский,NaN,ПОС,1

In [2]:
df = pd.read_csv(r'c:\Users\User\Documents\NIR3\files\ПОС_сообщения_geocoded_2.csv', sep=';')

In [2]:
input_path = r'c:\Users\User\Documents\NIR3\files\ПОС_сообщения_geocoded_2.csv'

# Загружаем CSV и проверяем, есть ли нужные столбцы
df = pd.read_csv(input_path, sep=';')
if 'latitude' not in df.columns:
    df['latitude'] = None
if 'longitude' not in df.columns:
    df['longitude'] = None

geolocator = Nominatim(user_agent="my_geocoder")
geocode = RateLimiter(geolocator.geocode, min_delay_seconds=0.5)

save_every = 30

for i in tqdm(range(len(df)), desc="Геокодирование"):
    row = df.iloc[i]
    if pd.isnull(row['latitude']) or pd.isnull(row['longitude']):
        try:
            print(f"[{i}] Геокодируем адрес: {row['loc_for_geocoding']}")
            location = geocode(row['loc_for_geocoding'])
            if location:
                df.at[i, 'latitude'] = location.latitude
                df.at[i, 'longitude'] = location.longitude
        except Exception as e:
            print(f"Ошибка на строке {i}: {e}")
        time.sleep(0.5)
    if i % save_every == 0 and i > 0:
        df.to_csv(input_path, index=False, sep=';')
        print(f"Автосохранение после {i} строк...")

df.to_csv(input_path, index=False, sep=';')
print("Геокодирование завершено, результат сохранён.")

Геокодирование:   0%|          | 0/19990 [00:00<?, ?it/s]

[0] Геокодируем адрес: Новаторов б-р 26к2, Санкт-Петербург

Геокодирование:   0%|          | 1/19990 [00:00<4:10:16,  1.33it/s]

[6] Геокодируем адрес: Ветеранов пр-т 114, Санкт-Петербург

Геокодирование:   0%|          | 7/19990 [00:01<1:26:25,  3.85it/s]

[7] Геокодируем адрес: Непокоренных пр-т 74, Санкт-Петербург

Геокодирование:   0%|          | 31/19990 [00:02<19:59, 16.64it/s]

Автосохранение после 30 строк...
[33] Геокодируем адрес: Российский пр-т 14, Санкт-Петербург

Геокодирование:   0%|          | 37/19990 [00:03<28:11, 11.79it/s]

[48] Геокодируем адрес: Песочный Пионерская ул, Санкт-Петербург

Геокодирование:   0%|          | 49/19990 [00:04<25:00, 13.29it/s]

[51] Геокодируем адрес: Комендантский пр-т 9, Санкт-Петербург

Геокодирование:   0%|          | 53/19990 [00:05<36:47,  9.03it/s]

[54] Геокодируем адрес: Лиговский пр-т 114Г, Санкт-Петербург

Геокодирование:   0%|          | 56/19990 [00:06<47:04,  7.06it/s]

[59] Геокодируем адрес: Обуховской Обороны пр-т 243, Санкт-Петербург

Геокодирование:   0%|          | 62/19990 [00:08<52:41,  6.30it/s]

Автосохранение после 60 строк...
[69] Геокодируем адрес: Тихорецкий пр-т 31к2, Санкт-Петербург

Геокодирование:   0%|          | 70/19990 [00:08<40:37,  8.17it/s]

[77] Геокодируем адрес: Песочный Садовая ул 81стр1, Санкт-Петербург

Геокодирование:   0%|          | 78/19990 [00:09<40:10,  8.26it/s]

[79] Геокодируем адрес: Колпино Павловская ул 17, Санкт-Петербург

Геокодирование:   0%|          | 80/19990 [00:10<59:17,  5.60it/s]

[81] Геокодируем адрес: Светлановский пр-т 54Г, Санкт-Петербург

Геокодирование:   0%|          | 82/19990 [00:11<1:14:06,  4.48it/s]

[82] Геокодируем адрес: Луначарского пр-т 84к4, Санкт-Петербург

Геокодирование:   0%|          | 83/19990 [00:12<1:36:19,  3.44it/s]

[83] Геокодируем адрес: Петергоф Санкт-Петербургское ш 121к2, Санкт-Петербург

Геокодирование:   0%|          | 84/19990 [00:13<2:04:31,  2.66it/s]

[87] Геокодируем адрес: ЖК Северная Долина Федора Абрамова ул, Санкт-Петербург

Геокодирование:   1%|          | 121/19990 [00:15<17:00, 19.47it/s]

Автосохранение после 90 строк...
Автосохранение после 120 строк...
[133] Геокодируем адрес: Славы пр-т 24, Санкт-Петербург

Геокодирование:   1%|          | 134/19990 [00:16<18:31, 17.86it/s]

[136] Геокодируем адрес: Ленинский пр-т 111, Санкт-Петербург

Геокодирование:   1%|          | 139/19990 [00:17<27:11, 12.17it/s]

[139] Геокодируем адрес: Большевиков пр-т 38к2, Санкт-Петербург

Геокодирование:   1%|          | 181/19990 [00:18<12:25, 26.56it/s]

Автосохранение после 150 строк...
Автосохранение после 180 строк...
[181] Геокодируем адрес: Энгельса пр-т 111к1, Санкт-Петербург
[183] Геокодируем адрес: Энгельса пр-т 150к1, Санкт-Петербург

Геокодирование:   1%|          | 190/19990 [00:20<22:43, 14.52it/s]

[205] Геокодируем адрес: Большой Сампсониевский пр-т 96, Санкт-Петербург

Геокодирование:   1%|          | 206/19990 [00:21<23:44, 13.89it/s]

[208] Геокодируем адрес: Пушкин Магазейная ул 36, Санкт-Петербург

Геокодирование:   1%|          | 211/19990 [00:22<29:00, 11.36it/s]

Автосохранение после 210 строк...
[222] Геокодируем адрес: Энгельса пр-т 107, Санкт-Петербург

Геокодирование:   1%|          | 241/19990 [00:23<18:47, 17.52it/s]

Автосохранение после 240 строк...
[259] Геокодируем адрес: Зеленогорск Тихий пер, Санкт-Петербург

Геокодирование:   1%|▏         | 260/19990 [00:24<15:40, 20.97it/s]

[262] Геокодируем адрес: Маршала Блюхера пр-т 12АИ, Санкт-Петербург

Геокодирование:   2%|▏         | 301/19990 [00:25<09:23, 34.95it/s]

Автосохранение после 270 строк...
Автосохранение после 300 строк...

Геокодирование:   2%|▏         | 361/19990 [00:26<04:14, 77.03it/s]

Автосохранение после 330 строк...
Автосохранение после 360 строк...
[366] Геокодируем адрес: Большевиков пр-т 9к1Т, Санкт-Петербург
[368] Геокодируем адрес: Дальневосточный пр-т 12к2, Санкт-Петербург
[369] Геокодируем адрес: Маршала Блюхера пр-т 14, Санкт-Петербург

Геокодирование:   2%|▏         | 376/19990 [00:28<17:01, 19.21it/s]

[389] Геокодируем адрес: Малый Васильевского острова пр-т 30-32Б, Санкт-Петербург

Геокодирование:   2%|▏         | 390/19990 [00:30<19:07, 17.08it/s]

Автосохранение после 390 строк...
[394] Геокодируем адрес: 15-я линия ВО 66, Санкт-Петербург

Геокодирование:   2%|▏         | 421/19990 [00:31<16:48, 19.40it/s]

Автосохранение после 420 строк...
[436] Геокодируем адрес: Парголово Северный пр-т, Санкт-Петербург

Геокодирование:   2%|▏         | 451/19990 [00:32<12:49, 25.40it/s]

Автосохранение после 450 строк...
[473] Геокодируем адрес: Художников пр-т 26, Санкт-Петербург

Геокодирование:   2%|▏         | 481/19990 [00:33<12:06, 26.87it/s]

Автосохранение после 480 строк...
[487] Геокодируем адрес: Культуры пр-т, Санкт-Петербург

Геокодирование:   2%|▏         | 488/19990 [00:34<16:17, 19.94it/s]

[491] Геокодируем адрес: Художников пр-т 33к1, Санкт-Петербург
[492] Геокодируем адрес: Художников пр-т 33к1, Санкт-Петербург

Геокодирование:   3%|▎         | 541/19990 [00:36<10:41, 30.31it/s]

Автосохранение после 510 строк...
Автосохранение после 540 строк...

Геокодирование:   3%|▎         | 571/19990 [00:37<06:55, 46.74it/s]

Автосохранение после 570 строк...
[586] Геокодируем адрес: Удариников пр-т 27к1, Санкт-Петербург

Геокодирование:   3%|▎         | 631/19990 [00:37<04:40, 69.11it/s]

Автосохранение после 600 строк...
Автосохранение после 630 строк...
[647] Геокодируем адрес: Индустриальный пр-т 27, Санкт-Петербург

Геокодирование:   3%|▎         | 661/19990 [00:39<07:19, 43.94it/s]

Автосохранение после 660 строк...
[681] Геокодируем адрес: Загребский б-р 9, Санкт-Петербург

Геокодирование:   4%|▎         | 721/19990 [00:40<05:11, 61.86it/s]

Автосохранение после 690 строк...
Автосохранение после 720 строк...
[721] Геокодируем адрес: Авиаконструкторов ул 24, Санкт-Петербург

Геокодирование:   4%|▎         | 732/19990 [00:40<07:53, 40.66it/s]

[741] Геокодируем адрес: Светлановский пр-т 101, Санкт-Петербург

Геокодирование:   4%|▍         | 751/19990 [00:42<12:06, 26.48it/s]

Автосохранение после 750 строк...
[757] Геокодируем адрес: Кондратьевский пр-т 75к2, Санкт-Петербург

Геокодирование:   4%|▍         | 758/19990 [00:42<15:09, 21.15it/s]

[758] Геокодируем адрес: Кондратьевский пр-т 75к2, Санкт-Петербург

Геокодирование:   4%|▍         | 763/19990 [00:43<22:59, 13.94it/s]

[766] Геокодируем адрес: Художников пр-т 5к1, Санкт-Петербург

Геокодирование:   4%|▍         | 781/19990 [00:44<20:07, 15.90it/s]

Автосохранение после 780 строк...
[795] Геокодируем адрес: Муринская дор, Санкт-Петербург

Геокодирование:   4%|▍         | 796/19990 [00:45<18:20, 17.43it/s]

[801] Геокодируем адрес: Большевиков пр-т 37к1, Санкт-Петербург

Геокодирование:   4%|▍         | 811/19990 [00:46<20:02, 15.95it/s]

Автосохранение после 810 строк...
[823] Геокодируем адрес: Комендантский пр-т 13к1, Санкт-Петербург

Геокодирование:   4%|▍         | 824/19990 [00:47<20:07, 15.88it/s]

[832] Геокодируем адрес: Обуховской обороны пр-т 289к1, Санкт-Петербург

Геокодирование:   4%|▍         | 841/19990 [00:48<19:17, 16.55it/s]

Автосохранение после 840 строк...
[844] Геокодируем адрес: Луначарского пр-т 56к1, Санкт-Петербург

Геокодирование:   4%|▍         | 845/19990 [00:49<26:26, 12.06it/s]

[851] Геокодируем адрес: Мечникова пр-т 5к2, Санкт-Петербург

Геокодирование:   4%|▍         | 852/19990 [00:50<32:37,  9.78it/s]

[854] Геокодируем адрес: Загородный пр-т 17, Санкт-Петербург

Геокодирование:   4%|▍         | 871/19990 [00:52<22:49, 13.96it/s]

Автосохранение после 870 строк...
[874] Геокодируем адрес: Героев пр-т 31, Санкт-Петербург

Геокодирование:   4%|▍         | 875/19990 [00:52<30:35, 10.42it/s]

[892] Геокодируем адрес: Славы пр-т 23к1, Санкт-Петербург

Геокодирование:   4%|▍         | 893/19990 [00:53<23:00, 13.83it/s]

[899] Геокодируем адрес: Энергетиков пр-т 11к5, Санкт-Петербург

Геокодирование:   5%|▍         | 900/19990 [00:54<27:16, 11.67it/s]

[900] Геокодируем адрес: Энергетиков пр-т 9к6, Санкт-Петербург
Автосохранение после 900 строк...
[901] Геокодируем адрес: Энергетиков пр-т 11к2, Санкт-Петербург

Геокодирование:   5%|▍         | 903/19990 [00:56<50:33,  6.29it/s]

[905] Геокодируем адрес: Большевиков пр-т 39к1, Санкт-Петербург

Геокодирование:   5%|▍         | 931/19990 [00:57<21:58, 14.46it/s]

Автосохранение после 930 строк...
[931] Геокодируем адрес: Комендантский пр-т 50к1, Санкт-Петербург

Геокодирование:   5%|▍         | 937/19990 [00:58<25:46, 12.32it/s]

[947] Геокодируем адрес: Просвещения пр-т 33к2, Санкт-Петербург

Геокодирование:   5%|▍         | 991/19990 [01:00<09:35, 33.01it/s]

Автосохранение после 960 строк...
Автосохранение после 990 строк...

Геокодирование:   5%|▌         | 1051/19990 [01:00<04:23, 71.90it/s]

Автосохранение после 1020 строк...
Автосохранение после 1050 строк...
[1067] Геокодируем адрес: Стачек пр-т 73, Санкт-Петербург

Геокодирование:   5%|▌         | 1081/19990 [01:01<06:20, 49.73it/s]

Автосохранение после 1080 строк...
[1090] Геокодируем адрес: Космонавтов пр-т 30к4, Санкт-Петербург

Геокодирование:   6%|▌         | 1111/19990 [01:02<09:49, 32.00it/s]

Автосохранение после 1110 строк...
[1115] Геокодируем адрес: Энгельса пр-т 22, Санкт-Петербург

Геокодирование:   6%|▌         | 1120/19990 [01:03<13:42, 22.93it/s]

[1131] Геокодируем адрес: Красное Село Бронетанковая ул 11к1, Санкт-Петербург

Геокодирование:   6%|▌         | 1141/19990 [01:05<14:32, 21.59it/s]

Автосохранение после 1140 строк...
[1145] Геокодируем адрес: Пушкин Железнодорожная ул 76, Санкт-Петербург

Геокодирование:   6%|▌         | 1147/19990 [01:05<18:26, 17.04it/s]

[1156] Геокодируем адрес: Энгельса пр-т 22, Санкт-Петербург

Геокодирование:   6%|▌         | 1157/19990 [01:06<23:44, 13.22it/s]

[1157] Геокодируем адрес: Индустриальный пр-т 17к2, Санкт-Петербург

Геокодирование:   6%|▌         | 1160/19990 [01:08<41:28,  7.57it/s]

[1163] Геокодируем адрес: Обуховской Обороны пр-т 35Б, Санкт-Петербург

Геокодирование:   6%|▌         | 1171/19990 [01:09<36:41,  8.55it/s]

Автосохранение после 1170 строк...
[1178] Геокодируем адрес: Советский пр-т 2к1, Санкт-Петербург

Геокодирование:   6%|▌         | 1179/19990 [01:10<35:37,  8.80it/s]

[1182] Геокодируем адрес: Комендантский пр-т 4к2, Санкт-Петербург

Геокодирование:   6%|▌         | 1201/19990 [01:11<20:38, 15.18it/s]

Автосохранение после 1200 строк...
[1224] Геокодируем адрес: Елизарова пр-т 12, Санкт-Петербург

Геокодирование:   6%|▌         | 1231/19990 [01:12<14:51, 21.04it/s]

Автосохранение после 1230 строк...
[1235] Геокодируем адрес: Энгельса пр-т 22, Санкт-Петербург

Геокодирование:   6%|▌         | 1236/19990 [01:13<21:28, 14.56it/s]

[1257] Геокодируем адрес: Парголово Заречная ул 42к2, Санкт-Петербург

Геокодирование:   6%|▋         | 1261/19990 [01:14<16:59, 18.37it/s]

Автосохранение после 1260 строк...
[1273] Геокодируем адрес: Комендантский пр-т 57к1, Санкт-Петербург

Геокодирование:   6%|▋         | 1291/19990 [01:15<11:49, 26.36it/s]

Автосохранение после 1290 строк...
[1316] Геокодируем адрес: Авиаконструкторов пр-т 18к1, Санкт-Петербург

Геокодирование:   7%|▋         | 1322/19990 [01:16<10:40, 29.13it/s]

Автосохранение после 1320 строк...
[1325] Геокодируем адрес: Энгельса пр-т 131к2, Санкт-Петербург

Геокодирование:   7%|▋         | 1351/19990 [01:17<09:31, 32.59it/s]

Автосохранение после 1350 строк...
[1355] Геокодируем адрес: Катлинская дор, Санкт-Петербург

Геокодирование:   7%|▋         | 1358/19990 [01:18<13:30, 22.98it/s]

[1366] Геокодируем адрес: Ломоносов Жоры Антоненко ул 8, Санкт-Петербург

Геокодирование:   7%|▋         | 1367/19990 [01:19<19:27, 15.95it/s]

[1369] Геокодируем адрес: Ленинский пр-т 92к3, Санкт-Петербург

Геокодирование:   7%|▋         | 1411/19990 [01:21<09:29, 32.63it/s]

Автосохранение после 1380 строк...
Автосохранение после 1410 строк...
[1415] Геокодируем адрес: Тореза пр-т 102к3, Санкт-Петербург

Геокодирование:   7%|▋         | 1471/19990 [01:22<05:16, 58.50it/s]

Автосохранение после 1440 строк...
Автосохранение после 1470 строк...

Геокодирование:   8%|▊         | 1501/19990 [01:22<03:46, 81.58it/s]

Автосохранение после 1500 строк...
[1524] Геокодируем адрес: Культуры пр-т 17, Санкт-Петербург

Геокодирование:   8%|▊         | 1537/19990 [01:23<05:25, 56.61it/s]

Автосохранение после 1530 строк...
[1542] Геокодируем адрес: Ленина ул 33, Санкт-Петербург
[1545] Геокодируем адрес: Фурштадтская ул, Санкт-Петербург

Геокодирование:   8%|▊         | 1561/19990 [01:24<10:37, 28.90it/s]

Автосохранение после 1560 строк...
[1585] Геокодируем адрес: Железнодорожный пр-т 14к3стр1, Санкт-Петербург

Геокодирование:   8%|▊         | 1586/19990 [01:25<10:36, 28.93it/s]

[1589] Геокодируем адрес: Новгородский пр-т 9к2, Санкт-Петербург

Геокодирование:   8%|▊         | 1621/19990 [01:27<09:58, 30.69it/s]

Автосохранение после 1590 строк...
Автосохранение после 1620 строк...

Геокодирование:   8%|▊         | 1651/19990 [01:27<06:31, 46.80it/s]

Автосохранение после 1650 строк...
[1680] Геокодируем адрес: Парголово Михаила Дудина ул, Санкт-Петербург

Геокодирование:   8%|▊         | 1681/19990 [01:28<06:59, 43.67it/s]

Автосохранение после 1680 строк...
[1703] Геокодируем адрес: Культуры пр-т, Санкт-Петербург

Геокодирование:   9%|▊         | 1712/19990 [01:29<08:17, 36.76it/s]

Автосохранение после 1710 строк...
[1735] Геокодируем адрес: Ветеранов пр-т 173к7, Санкт-Петербург

Геокодирование:   9%|▊         | 1742/19990 [01:29<08:16, 36.74it/s]

Автосохранение после 1740 строк...
[1746] Геокодируем адрес: Петергоф Бобыльская дор 61, Санкт-Петербург

Геокодирование:   9%|▉         | 1771/19990 [01:31<08:52, 34.23it/s]

Автосохранение после 1770 строк...
[1784] Геокодируем адрес: Энгельса пр-т 145к3, Санкт-Петербург

Геокодирование:   9%|▉         | 1785/19990 [01:31<11:12, 27.07it/s]

[1797] Геокодируем адрес: Ульяны Громовой наб 8Б, Санкт-Петербург

Геокодирование:   9%|▉         | 1798/19990 [01:33<14:47, 20.50it/s]

Автосохранение после 1800 строк...
[1801] Геокодируем адрес: Энтузиастов пр-т 40к2, Санкт-Петербург

Геокодирование:   9%|▉         | 1803/19990 [01:33<20:06, 15.07it/s]

[1804] Геокодируем адрес: Авиаконструкторов пр-т 4к1, Санкт-Петербург

Геокодирование:   9%|▉         | 1831/19990 [01:35<14:13, 21.28it/s]

Автосохранение после 1830 строк...
[1855] Геокодируем адрес: Кронверская ул, Санкт-Петербург

Геокодирование:   9%|▉         | 1862/19990 [01:35<11:08, 27.13it/s]

Автосохранение после 1860 строк...
[1863] Геокодируем адрес: Муринская дор 10к1, Санкт-Петербург

Геокодирование:   9%|▉         | 1868/19990 [01:36<17:03, 17.71it/s]

[1886] Геокодируем адрес: Географическая ул 75к2, Санкт-Петербург

Геокодирование:   9%|▉         | 1891/19990 [01:38<15:34, 19.37it/s]

Автосохранение после 1890 строк...
[1892] Геокодируем адрес: Шушары Ростовская ул 13-15, Санкт-Петербург

Геокодирование:   9%|▉         | 1895/19990 [01:39<24:06, 12.51it/s]

[1911] Геокодируем адрес: Кондратьевский пр-т 70к1, Санкт-Петербург

Геокодирование:  10%|▉         | 1921/19990 [01:40<16:04, 18.74it/s]

Автосохранение после 1920 строк...
[1923] Геокодируем адрес: Стрельна Нижняя Колония ул 49Б, Санкт-Петербург

Геокодирование:  10%|▉         | 1925/19990 [01:41<23:45, 12.67it/s]

[1944] Геокодируем адрес: Индустриальный пр-т 14к2, Санкт-Петербург

Геокодирование:  10%|▉         | 1951/19990 [01:42<16:47, 17.91it/s]

Автосохранение после 1950 строк...
[1955] Геокодируем адрес: Оптиков пр-т 37, Санкт-Петербург

Геокодирование:  10%|█         | 2011/19990 [01:43<06:39, 45.00it/s]

Автосохранение после 1980 строк...
Автосохранение после 2010 строк...
[2013] Геокодируем адрес: Понтонный Александра Товпеко ул 17, Санкт-Петербург
[2014] Геокодируем адрес: Энгельса пр-т 16к2, Санкт-Петербург

Геокодирование:  10%|█         | 2022/19990 [01:45<14:42, 20.36it/s]

[2029] Геокодируем адрес: Петергоф Эрлеровский б-р 10, Санкт-Петербург

Геокодирование:  10%|█         | 2041/19990 [01:46<15:24, 19.42it/s]

Автосохранение после 2040 строк...
[2066] Геокодируем адрес: Красных Зорь б-р 16к2, Санкт-Петербург

Геокодирование:  10%|█         | 2073/19990 [01:47<11:26, 26.09it/s]

Автосохранение после 2070 строк...
[2076] Геокодируем адрес: Суворовский пр-т 62, Санкт-Петербург

Геокодирование:  10%|█         | 2078/19990 [01:48<17:44, 16.83it/s]

[2081] Геокодируем адрес: Богатырский пр-т 55к5, Санкт-Петербург

Геокодирование:  10%|█         | 2082/19990 [01:48<23:56, 12.47it/s]

[2092] Геокодируем адрес: Ветеранов пр-т 32, Санкт-Петербург

Геокодирование:  11%|█         | 2131/19990 [01:50<09:45, 30.51it/s]

Автосохранение после 2100 строк...
Автосохранение после 2130 строк...
[2135] Геокодируем адрес: Авиаконструкторов пр-т 4к1, Санкт-Петербург

Геокодирование:  11%|█         | 2140/19990 [01:52<19:50, 14.99it/s]

[2150] Геокодируем адрес: Мартышкино, Ломонов Немкова ул, Санкт-Петербург

Геокодирование:  11%|█         | 2191/19990 [01:53<08:38, 34.35it/s]

Автосохранение после 2160 строк...
Автосохранение после 2190 строк...
[2191] Геокодируем адрес: Дальневосточный пр-т 63, Санкт-Петербург

Геокодирование:  11%|█▏        | 2251/19990 [01:54<05:44, 51.49it/s]

Автосохранение после 2220 строк...
Автосохранение после 2250 строк...
[2251] Геокодируем адрес: Сиреневый б-р, Санкт-Петербург

Геокодирование:  11%|█▏        | 2264/19990 [01:55<07:57, 37.13it/s]

[2265] Геокодируем адрес: Новочеркасский пр-т 12к1, Санкт-Петербург

Геокодирование:  11%|█▏        | 2281/19990 [01:56<11:28, 25.72it/s]

Автосохранение после 2280 строк...
[2281] Геокодируем адрес: Одоедовского ул, Санкт-Петербург

Геокодирование:  12%|█▏        | 2311/19990 [01:57<08:33, 34.44it/s]

Автосохранение после 2310 строк...
[2324] Геокодируем адрес: Чкаловский пр-т 38, Санкт-Петербург

Геокодирование:  12%|█▏        | 2325/19990 [01:58<12:43, 23.12it/s]

[2330] Геокодируем адрес: Московский пр-т 130С, Санкт-Петербург

Геокодирование:  12%|█▏        | 2341/19990 [01:59<14:49, 19.85it/s]

Автосохранение после 2340 строк...
[2343] Геокодируем адрес: Крыленко ул 21к1С, Санкт-Петербург

Геокодирование:  12%|█▏        | 2371/19990 [02:00<09:16, 31.65it/s]

Автосохранение после 2370 строк...
[2374] Геокодируем адрес: Королева пр-т 45к1, Санкт-Петербург
[2376] Геокодируем адрес: Авиаконструкторов пр-т 14к3, Санкт-Петербург
[2378] Геокодируем адрес: Шушары Школьная ул 6, Санкт-Петербург

Геокодирование:  12%|█▏        | 2431/19990 [02:03<09:58, 29.33it/s]

Автосохранение после 2400 строк...
Автосохранение после 2430 строк...
[2451] Геокодируем адрес: Обуховской Обороны пр-т 93Р, Санкт-Петербург

Геокодирование:  12%|█▏        | 2461/19990 [02:04<09:38, 30.29it/s]

Автосохранение после 2460 строк...
[2489] Геокодируем адрес: Лиговский пр-т 96, Санкт-Петербург

Геокодирование:  12%|█▏        | 2497/19990 [02:05<08:44, 33.36it/s]

Автосохранение после 2490 строк...
[2508] Геокодируем адрес: Лиговский пр-т 107, Санкт-Петербург

Геокодирование:  13%|█▎        | 2509/19990 [02:06<11:33, 25.19it/s]

[2509] Геокодируем адрес: Лиговский пр-т 107, Санкт-Петербург

Геокодирование:  13%|█▎        | 2521/19990 [02:07<15:41, 18.56it/s]

Автосохранение после 2520 строк...
[2524] Геокодируем адрес: Финляндский пр-т 1, Санкт-Петербург

Геокодирование:  13%|█▎        | 2525/19990 [02:08<21:00, 13.85it/s]

[2527] Геокодируем адрес: Сестрорецк Воскова ул 11, Санкт-Петербург

Геокодирование:  13%|█▎        | 2581/19990 [02:09<07:12, 40.23it/s]

Автосохранение после 2550 строк...
Автосохранение после 2580 строк...
[2592] Геокодируем адрес: Загородный пр-т 17, Санкт-Петербург

Геокодирование:  13%|█▎        | 2611/19990 [02:10<07:21, 39.39it/s]

Автосохранение после 2610 строк...
[2611] Геокодируем адрес: 2-й Муринский пр-т, Санкт-Петербург

Геокодирование:  13%|█▎        | 2620/19990 [02:11<13:14, 21.87it/s]

[2627] Геокодируем адрес: Маршала Блюхера пр-т 65, Санкт-Петербург

Геокодирование:  13%|█▎        | 2628/19990 [02:12<16:56, 17.09it/s]

[2635] Геокодируем адрес: Шушары Московское ш 244к1, Санкт-Петербург

Геокодирование:  13%|█▎        | 2641/19990 [02:13<17:13, 16.78it/s]

Автосохранение после 2640 строк...
[2641] Геокодируем адрес: Большой пр-т 69, Санкт-Петербург
[2643] Геокодируем адрес: Чкаловский пр-т 28, Санкт-Петербург

Геокодирование:  14%|█▎        | 2701/19990 [02:16<08:58, 32.12it/s]

Автосохранение после 2670 строк...
Автосохранение после 2700 строк...

Геокодирование:  14%|█▎        | 2731/19990 [02:16<05:51, 49.12it/s]

Автосохранение после 2730 строк...
[2751] Геокодируем адрес: Лиговский пр-т 91, Санкт-Петербург

Геокодирование:  14%|█▍        | 2791/19990 [02:17<04:34, 62.60it/s]

Автосохранение после 2760 строк...
Автосохранение после 2790 строк...
[2802] Геокодируем адрес: Парголово Первого Мая ул 107к4, Санкт-Петербург

Геокодирование:  14%|█▍        | 2804/19990 [02:17<06:45, 42.43it/s]

[2814] Геокодируем адрес: Муринская дор, Санкт-Петербург

Геокодирование:  14%|█▍        | 2822/19990 [02:19<09:40, 29.57it/s]

Автосохранение после 2820 строк...
[2823] Геокодируем адрес: Металлострой Садовая ул 8, Санкт-Петербург

Геокодирование:  14%|█▍        | 2851/19990 [02:20<08:51, 32.28it/s]

Автосохранение после 2850 строк...
[2857] Геокодируем адрес: Сизова ул, Санкт-Петербург

Геокодирование:  14%|█▍        | 2859/19990 [02:20<12:37, 22.61it/s]

[2877] Геокодируем адрес: Басков наб 10Б, Санкт-Петербург

Геокодирование:  14%|█▍        | 2883/19990 [02:22<13:17, 21.45it/s]

Автосохранение после 2880 строк...
[2885] Геокодируем адрес: Волковский пр-т 144, Санкт-Петербург
[2887] Геокодируем адрес: Волковский пр-т 144, Санкт-Петербург

Геокодирование:  14%|█▍        | 2888/19990 [02:24<28:22, 10.05it/s]

[2888] Геокодируем адрес: Ленинский пр-т 138/5, Санкт-Петербург

Геокодирование:  14%|█▍        | 2891/19990 [02:25<37:48,  7.54it/s]

[2902] Геокодируем адрес: Энгельса пр-т 96, Санкт-Петербург

Геокодирование:  15%|█▍        | 2911/19990 [02:26<24:10, 11.78it/s]

Автосохранение после 2910 строк...
[2925] Геокодируем адрес: Новаторов б-р 84, Санкт-Петербург

Геокодирование:  15%|█▍        | 2926/19990 [02:27<20:05, 14.16it/s]

[2933] Геокодируем адрес: Тореза пр-т 102к3, Санкт-Петербург

Геокодирование:  15%|█▍        | 2971/19990 [02:28<08:26, 33.59it/s]

Автосохранение после 2940 строк...
Автосохранение после 2970 строк...

Геокодирование:  15%|█▌        | 3031/19990 [02:28<03:46, 74.92it/s]

Автосохранение после 3000 строк...
Автосохранение после 3030 строк...
[3036] Геокодируем адрес: Петергоф Аврова ул 20, Санкт-Петербург

Геокодирование:  15%|█▌        | 3045/19990 [02:29<05:52, 48.03it/s]

[3055] Геокодируем адрес: Шушары Первомайская ул 20, Санкт-Петербург

Геокодирование:  15%|█▌        | 3091/19990 [02:30<05:42, 49.37it/s]

Автосохранение после 3060 строк...
Автосохранение после 3090 строк...
[3097] Геокодируем адрес: Сиреневый б-р 4к2, Санкт-Петербург

Геокодирование:  16%|█▌        | 3102/19990 [02:31<08:27, 33.26it/s]

[3103] Геокодируем адрес: Сиреневый б-р 4к2, Санкт-Петербург

Геокодирование:  16%|█▌        | 3151/19990 [02:32<05:57, 47.17it/s]

Автосохранение после 3120 строк...
Автосохранение после 3150 строк...
[3153] Геокодируем адрес: Ветеранов пр-т 160, Санкт-Петербург

Геокодирование:  16%|█▌        | 3162/19990 [02:33<09:02, 31.05it/s]

[3166] Геокодируем адрес: Серебристый б-р, Санкт-Петербург

Геокодирование:  16%|█▌        | 3181/19990 [02:34<10:20, 27.08it/s]

Автосохранение после 3180 строк...
[3196] Геокодируем адрес: культуры пр-т 11к3, Санкт-Петербург

Геокодирование:  16%|█▌        | 3211/19990 [02:35<09:05, 30.78it/s]

Автосохранение после 3210 строк...
[3232] Геокодируем адрес: Луначарского пр-т 112/2, Санкт-Петербург

Геокодирование:  16%|█▌        | 3233/19990 [02:36<11:14, 24.86it/s]

[3233] Геокодируем адрес: Обуховской Обороны пр-т 221, Санкт-Петербург

Геокодирование:  16%|█▌        | 3242/19990 [02:37<15:21, 18.18it/s]

Автосохранение после 3240 строк...
[3253] Геокодируем адрес: Королева пр-т 47к1, Санкт-Петербург

Геокодирование:  16%|█▋        | 3254/19990 [02:38<15:09, 18.39it/s]

[3264] Геокодируем адрес: Стойкости ул 4литА, Санкт-Петербург

Геокодирование:  16%|█▋        | 3265/19990 [02:39<17:38, 15.80it/s]

[3265] Геокодируем адрес: Ветеранов пр-т 105, Санкт-Петербург

Геокодирование:  16%|█▋        | 3271/19990 [02:40<27:07, 10.27it/s]

Автосохранение после 3270 строк...
[3285] Геокодируем адрес: Стачек пр-т 84к1, Санкт-Петербург

Геокодирование:  17%|█▋        | 3301/19990 [02:41<12:41, 21.90it/s]

Автосохранение после 3300 строк...
[3325] Геокодируем адрес: Петро-Славянка Клубная ул 1к2, Санкт-Петербург

Геокодирование:  17%|█▋        | 3326/19990 [02:42<11:54, 23.32it/s]

[3329] Геокодируем адрес: Старорусский пр-т 13к1, Санкт-Петербург

Геокодирование:  17%|█▋        | 3361/19990 [02:43<08:10, 33.90it/s]

Автосохранение после 3330 строк...
Автосохранение после 3360 строк...
[3380] Геокодируем адрес: Большой Сампсониевский пр-т, Санкт-Петербург

Геокодирование:  17%|█▋        | 3381/19990 [02:44<09:24, 29.43it/s]

[3383] Геокодируем адрес: Кронштадт Посадская ул 5, Санкт-Петербург

Геокодирование:  17%|█▋        | 3388/19990 [02:45<13:06, 21.12it/s]

Автосохранение после 3390 строк...
[3392] Геокодируем адрес: Трамвайный пр-т 13к4, Санкт-Петербург

Геокодирование:  17%|█▋        | 3393/19990 [02:46<18:23, 15.05it/s]

[3396] Геокодируем адрес: Космонавтов пр-т 65к2, Санкт-Петербург

Геокодирование:  17%|█▋        | 3451/19990 [02:47<07:14, 38.04it/s]

Автосохранение после 3420 строк...
Автосохранение после 3450 строк...
[3456] Геокодируем адрес: Вишерская Окуловская ул, Санкт-Петербург

Геокодирование:  17%|█▋        | 3462/19990 [02:48<08:59, 30.64it/s]

[3473] Геокодируем адрес: Пушкин Малиновская ул 11, Санкт-Петербург

Геокодирование:  18%|█▊        | 3511/19990 [02:49<06:30, 42.24it/s]

Автосохранение после 3480 строк...
Автосохранение после 3510 строк...
[3516] Геокодируем адрес: Дачный пр-т 36к1, Санкт-Петербург

Геокодирование:  18%|█▊        | 3541/19990 [02:50<06:48, 40.25it/s]

Автосохранение после 3540 строк...
[3569] Геокодируем адрес: Сиреневый б-р, Санкт-Петербург

Геокодирование:  18%|█▊        | 3570/19990 [02:51<07:01, 38.99it/s]

Автосохранение после 3570 строк...
[3573] Геокодируем адрес: Ударников пр-т 56к1, Санкт-Петербург

Геокодирование:  18%|█▊        | 3601/19990 [02:52<07:13, 37.77it/s]

Автосохранение после 3600 строк...
[3626] Геокодируем адрес: Шушары Школьная ул 17, Санкт-Петербург

Геокодирование:  18%|█▊        | 3634/19990 [02:54<11:18, 24.12it/s]

Автосохранение после 3630 строк...
[3645] Геокодируем адрес: Обуховской Обороны пр-т 33к2, Санкт-Петербург

Геокодирование:  18%|█▊        | 3661/19990 [02:55<09:53, 27.53it/s]

Автосохранение после 3660 строк...
[3665] Геокодируем адрес: Индустриальный пр-т 35к3, Санкт-Петербург

Геокодирование:  18%|█▊        | 3691/19990 [02:56<08:24, 32.33it/s]

Автосохранение после 3690 строк...
[3708] Геокодируем адрес: Стачек пр-т 1-5, Санкт-Петербург

Геокодирование:  19%|█▊        | 3721/19990 [02:57<09:01, 30.04it/s]

Автосохранение после 3720 строк...
[3726] Геокодируем адрес: Шушары Валдайская ул 11, Санкт-Петербург

Геокодирование:  19%|█▊        | 3728/19990 [02:58<11:47, 22.97it/s]

[3736] Геокодируем адрес: Стачек пр-т 105, Санкт-Петербург

Геокодирование:  19%|█▊        | 3737/19990 [02:59<17:18, 15.66it/s]

[3747] Геокодируем адрес: Загребский б-р 33к2, Санкт-Петербург

Геокодирование:  19%|█▉        | 3751/19990 [03:00<17:58, 15.06it/s]

Автосохранение после 3750 строк...
[3773] Геокодируем адрес: Сиреневый б-р 4к2, Санкт-Петербург

Геокодирование:  19%|█▉        | 3781/19990 [03:01<12:32, 21.55it/s]

Автосохранение после 3780 строк...
[3792] Геокодируем адрес: Сиреневый б-р 4к2, Санкт-Петербург

Геокодирование:  19%|█▉        | 3793/19990 [03:02<14:40, 18.39it/s]

[3800] Геокодируем адрес: Большевиков пр-т 31, Санкт-Петербург

Геокодирование:  19%|█▉        | 3811/19990 [03:03<15:04, 17.90it/s]

Автосохранение после 3810 строк...
[3828] Геокодируем адрес: Колпино Ленина пр-т 15/9, Санкт-Петербург

Геокодирование:  19%|█▉        | 3829/19990 [03:04<14:10, 19.00it/s]

[3830] Геокодируем адрес: Парголово Шишкина ул 309к1, Санкт-Петербург

Геокодирование:  19%|█▉        | 3841/19990 [03:05<15:20, 17.54it/s]

Автосохранение после 3840 строк...
[3854] Геокодируем адрес: Ленинский пр-т 95к2, Санкт-Петербург

Геокодирование:  19%|█▉        | 3855/19990 [03:06<15:53, 16.92it/s]

[3859] Геокодируем адрес: Кондратьевский пр-т 64к2, Санкт-Петербург

Геокодирование:  19%|█▉        | 3871/19990 [03:07<15:44, 17.06it/s]

Автосохранение после 3870 строк...
[3891] Геокодируем адрес: Шушары Валдайская ул, Санкт-Петербург

Геокодирование:  20%|█▉        | 3901/19990 [03:08<11:18, 23.72it/s]

Автосохранение после 3900 строк...
[3906] Геокодируем адрес: Большой Сампсониевский пр-т, Санкт-Петербург

Геокодирование:  20%|█▉        | 3907/19990 [03:09<17:22, 15.43it/s]

[3915] Геокодируем адрес: Орлово-Денисовский пр-т 19к1, Санкт-Петербург

Геокодирование:  20%|█▉        | 3916/19990 [03:10<20:22, 13.15it/s]

[3926] Геокодируем адрес: Шушары Вилеровский пер 6, Санкт-Петербург

Геокодирование:  20%|█▉        | 3927/19990 [03:11<21:05, 12.69it/s]

[3928] Геокодируем адрес: Лиговский пр-т 107, Санкт-Петербург

Геокодирование:  20%|█▉        | 3931/19990 [03:12<29:51,  8.96it/s]

Автосохранение после 3930 строк...
[3937] Геокодируем адрес: 6-я линия ВО 60, Санкт-Петербург

Геокодирование:  20%|█▉        | 3938/19990 [03:16<1:05:59,  4.05it/s]

[3954] Геокодируем адрес: Пушкин Широкая ул 1/36, Санкт-Петербург

Геокодирование:  20%|█▉        | 3955/19990 [03:16<37:52,  7.06it/s]

[3960] Геокодируем адрес: Комендантский пр-т 35к1, Санкт-Петербург

Геокодирование:  20%|█▉        | 3961/19990 [03:17<38:51,  6.87it/s]

Автосохранение после 3960 строк...
[3970] Геокодируем адрес: Ветеранов пр-т 196, Санкт-Петербург

Геокодирование:  20%|█▉        | 3971/19990 [03:19<36:21,  7.34it/s]

[3984] Геокодируем адрес: Металлострой Полевая ул 5, Санкт-Петербург

Геокодирование:  20%|█▉        | 3985/19990 [03:19<27:03,  9.86it/s]

[3987] Геокодируем адрес: Пулковский Мередиан, Санкт-Петербург

Геокодирование:  20%|██        | 4021/19990 [03:21<11:10, 23.81it/s]

Автосохранение после 3990 строк...
Автосохранение после 4020 строк...

Геокодирование:  20%|██        | 4051/19990 [03:21<06:29, 40.94it/s]

Автосохранение после 4050 строк...
[4063] Геокодируем адрес: Авиаконструкторов пр-т 20к1, Санкт-Петербург

Геокодирование:  20%|██        | 4064/19990 [03:21<07:53, 33.64it/s]

[4074] Геокодируем адрес: Обуховской Обороны пр-т 33к2, Санкт-Петербург

Геокодирование:  21%|██        | 4111/19990 [03:23<06:01, 43.87it/s]

Автосохранение после 4080 строк...
Автосохранение после 4110 строк...
[4113] Геокодируем адрес: 16-я линия ВО, Санкт-Петербург
[4114] Геокодируем адрес: Большевиков пр-т 31, Санкт-Петербург
[4117] Геокодируем адрес: Новоколомяжский пр-т 11, Санкт-Петербург

Геокодирование:  21%|██        | 4122/19990 [03:26<20:55, 12.64it/s]

[4138] Геокодируем адрес: Авиаконструкторов пр-т 20к1, Санкт-Петербург

Геокодирование:  21%|██        | 4171/19990 [03:27<09:48, 26.86it/s]

Автосохранение после 4140 строк...
Автосохранение после 4170 строк...

Геокодирование:  21%|██        | 4201/19990 [03:27<06:05, 43.18it/s]

Автосохранение после 4200 строк...
[4205] Геокодируем адрес: Славы пр-т 30к6, Санкт-Петербург

Геокодирование:  21%|██        | 4214/19990 [03:28<07:32, 34.84it/s]

[4218] Геокодируем адрес: Салтыковская дор, Санкт-Петербург

Геокодирование:  21%|██▏       | 4261/19990 [03:29<05:41, 46.12it/s]

Автосохранение после 4230 строк...
Автосохранение после 4260 строк...
[4282] Геокодируем адрес: Московский пр-т 86Т, Санкт-Петербург

Геокодирование:  21%|██▏       | 4283/19990 [03:30<07:35, 34.47it/s]

[4287] Геокодируем адрес: Приморский пр-т 137к1, Санкт-Петербург

Геокодирование:  21%|██▏       | 4292/19990 [03:31<11:02, 23.69it/s]

Автосохранение после 4290 строк...
[4294] Геокодируем адрес: Парголово Заречная ул 33, Санкт-Петербург

Геокодирование:  22%|██▏       | 4299/19990 [03:32<14:20, 18.24it/s]

[4315] Геокодируем адрес: Авиаконструкторов пр-т 35к3, Санкт-Петербург

Геокодирование:  22%|██▏       | 4321/19990 [03:33<13:29, 19.35it/s]

Автосохранение после 4320 строк...
[4327] Геокодируем адрес: Мечникова пр-т 5к2, Санкт-Петербург

Геокодирование:  22%|██▏       | 4328/19990 [03:34<17:57, 14.53it/s]

[4346] Геокодируем адрес: Богатырский пр-т 51к1, Санкт-Петербург

Геокодирование:  22%|██▏       | 4351/19990 [03:35<15:17, 17.05it/s]

Автосохранение после 4350 строк...
[4369] Геокодируем адрес: Юрия Гагарина ул 45, Санкт-Петербург

Геокодирование:  22%|██▏       | 4370/19990 [03:37<19:46, 13.16it/s]

[4372] Геокодируем адрес: Среднеохтинский пр-т 40, Санкт-Петербург

Геокодирование:  22%|██▏       | 4373/19990 [03:38<26:26,  9.85it/s]

[4377] Геокодируем адрес: Шушары Вилеровский пер 6, Санкт-Петербург

Геокодирование:  22%|██▏       | 4381/19990 [03:39<27:36,  9.42it/s]

Автосохранение после 4380 строк...
[4404] Геокодируем адрес: Маршала Жукова пр-т 18, Санкт-Петербург

Геокодирование:  22%|██▏       | 4411/19990 [03:40<16:20, 15.89it/s]

Автосохранение после 4410 строк...
[4412] Геокодируем адрес: Пушкин Средняя ул 44/18, Санкт-Петербург
[4413] Геокодируем адрес: Лисий Нос Песочная ул 3к1, Санкт-Петербург

Геокодирование:  22%|██▏       | 4414/19990 [03:42<30:42,  8.45it/s]

[4423] Геокодируем адрес: Елизарова пр-т 12, Санкт-Петербург

Геокодирование:  22%|██▏       | 4424/19990 [03:43<30:15,  8.58it/s]

[4429] Геокодируем адрес: Металлострой Садовая ул 8, Санкт-Петербург

Геокодирование:  22%|██▏       | 4441/19990 [03:44<21:18, 12.16it/s]

Автосохранение после 4440 строк...
[4456] Геокодируем адрес: Авиаконструкторов пр-т 38, Санкт-Петербург

Геокодирование:  22%|██▏       | 4457/19990 [03:45<18:51, 13.73it/s]

[4469] Геокодируем адрес: Большеохтинский пр-т 16к1, Санкт-Петербург

Геокодирование:  22%|██▏       | 4470/19990 [03:46<18:33, 13.94it/s]

[4470] Геокодируем адрес: Наличная ул 36к3Б, Санкт-Петербург

Геокодирование:  23%|██▎       | 4501/19990 [03:47<11:38, 22.18it/s]

Автосохранение после 4470 строк...
Автосохранение после 4500 строк...

Геокодирование:  23%|██▎       | 4531/19990 [03:47<06:48, 37.86it/s]

Автосохранение после 4530 строк...
[4531] Геокодируем адрес: Шушары Вилеровский пер 8, Санкт-Петербург
[4532] Геокодируем адрес: Шушары Вишерская ул 1к1, Санкт-Петербург

Геокодирование:  23%|██▎       | 4542/19990 [03:49<13:25, 19.18it/s]

[4547] Геокодируем адрес: Ударников пр-т 41к1, Санкт-Петербург

Геокодирование:  23%|██▎       | 4561/19990 [03:50<12:58, 19.81it/s]

Автосохранение после 4560 строк...
[4575] Геокодируем адрес: Славы пр-т 51, Санкт-Петербург

Геокодирование:  23%|██▎       | 4576/19990 [03:51<14:21, 17.89it/s]

[4589] Геокодируем адрес: Энгельса пр-т 16к2, Санкт-Петербург

Геокодирование:  23%|██▎       | 4621/19990 [03:52<07:32, 34.00it/s]

Автосохранение после 4590 строк...
Автосохранение после 4620 строк...

Геокодирование:  23%|██▎       | 4651/19990 [03:52<04:45, 53.67it/s]

Автосохранение после 4650 строк...
[4659] Геокодируем адрес: Стачек пр-т 27к4, Санкт-Петербург

Геокодирование:  24%|██▎       | 4711/19990 [03:53<03:31, 72.35it/s]

Автосохранение после 4680 строк...
Автосохранение после 4710 строк...

Геокодирование:  24%|██▍       | 4771/19990 [03:54<02:12, 114.96it/s]

Автосохранение после 4740 строк...
Автосохранение после 4770 строк...
[4793] Геокодируем адрес: Светлановский пр-т 47, Санкт-Петербург

Геокодирование:  24%|██▍       | 4794/19990 [03:54<03:57, 63.99it/s]

Автосохранение после 4800 строк...
[4801] Геокодируем адрес: Авиаконструкторов пр-т 4к1, Санкт-Петербург

Геокодирование:  24%|██▍       | 4807/19990 [03:55<06:36, 38.27it/s]

[4825] Геокодируем адрес: Богатырский пр-т 57к2, Санкт-Петербург

Геокодирование:  24%|██▍       | 4833/19990 [03:56<07:47, 32.39it/s]

Автосохранение после 4830 строк...
[4856] Геокодируем адрес: Фарфороровская 20, Санкт-Петербург

Геокодирование:  24%|██▍       | 4863/19990 [03:57<07:39, 32.92it/s]

Автосохранение после 4860 строк...
[4869] Геокодируем адрес: Товарищеский пр-т 2к1, Санкт-Петербург

Геокодирование:  24%|██▍       | 4891/19990 [03:58<08:01, 31.37it/s]

Автосохранение после 4890 строк...
[4900] Геокодируем адрес: Энгельса пр-т 10, Санкт-Петербург

Геокодирование:  25%|██▍       | 4921/19990 [04:00<08:05, 31.01it/s]

Автосохранение после 4920 строк...
[4934] Геокодируем адрес: Шушары Школьная ул 17, Санкт-Петербург

Геокодирование:  25%|██▍       | 4981/19990 [04:01<04:31, 55.25it/s]

Автосохранение после 4950 строк...
Автосохранение после 4980 строк...

Геокодирование:  25%|██▌       | 5011/19990 [04:01<03:17, 75.79it/s]

Автосохранение после 5010 строк...
[5012] Геокодируем адрес: Кронштадт Кронштадтская ул 13к2, Санкт-Петербург

Геокодирование:  25%|██▌       | 5024/19990 [04:01<04:58, 50.13it/s]

[5024] Геокодируем адрес: Кузнецова пр-т 10к1, Санкт-Петербург
[5025] Геокодируем адрес: Новаторов б-р 68, Санкт-Петербург
[5028] Геокодируем адрес: Кузнецова пр-т 10к2, Санкт-Петербург
[5030] Геокодируем адрес: Кузнецова пр-т 10к2, Санкт-Петербург
[5031] Геокодируем адрес: Кондратьевский пр-т 25, Санкт-Петербург

Геокодирование:  25%|██▌       | 5034/19990 [04:07<27:02,  9.22it/s]

[5034] Геокодируем адрес: Энергетиков пр-т 9К6, Санкт-Петербург

Геокодирование:  25%|██▌       | 5041/19990 [04:08<29:04,  8.57it/s]

Автосохранение после 5040 строк...
Автосохранение после 5070 строк...

Геокодирование:  25%|██▌       | 5071/19990 [04:08<15:47, 15.75it/s]

[5097] Геокодируем адрес: Петергоф Жертв Революции пл 6А, Санкт-Петербург

Геокодирование:  26%|██▌       | 5106/19990 [04:09<11:12, 22.14it/s]

Автосохранение после 5100 строк...
[5112] Геокодируем адрес: Авиаконструкторов пр-т 2, Санкт-Петербург

Геокодирование:  26%|██▌       | 5113/19990 [04:10<14:04, 17.62it/s]

[5123] Геокодируем адрес: Просвещения пр-т 39к1, Санкт-Петербург

Геокодирование:  26%|██▌       | 5131/19990 [04:11<13:56, 17.76it/s]

Автосохранение после 5130 строк...
[5143] Геокодируем адрес: Галицкой ул 19к3, Санкт-Петербург

Геокодирование:  26%|██▌       | 5161/19990 [04:12<09:53, 25.00it/s]

Автосохранение после 5160 строк...
[5161] Геокодируем адрес: Стачек пр-т 107к3Б, Санкт-Петербург

Геокодирование:  26%|██▌       | 5166/19990 [04:13<13:41, 18.04it/s]

[5190] Геокодируем адрес: Пушкин Чистякова ул 4, Санкт-Петербург

Геокодирование:  26%|██▌       | 5191/19990 [04:14<13:17, 18.56it/s]

Автосохранение после 5190 строк...
[5197] Геокодируем адрес: Суворовский пр-т 61, Санкт-Петербург

Геокодирование:  26%|██▌       | 5221/19990 [04:15<09:59, 24.62it/s]

Автосохранение после 5220 строк...
Автосохранение после 5250 строк...

Геокодирование:  26%|██▋       | 5281/19990 [04:15<04:16, 57.42it/s]

Автосохранение после 5280 строк...
[5301] Геокодируем адрес: Фарфороровская ул 24литН, Санкт-Петербург

Геокодирование:  27%|██▋       | 5312/19990 [04:16<04:46, 51.31it/s]

Автосохранение после 5310 строк...
[5328] Геокодируем адрес: Стачек пр-т 105к2Г, Санкт-Петербург

Геокодирование:  27%|██▋       | 5371/19990 [04:17<03:59, 61.07it/s]

Автосохранение после 5340 строк...
Автосохранение после 5370 строк...
[5376] Геокодируем адрес: Суздальский пр-т 20, Санкт-Петербург

Геокодирование:  27%|██▋       | 5381/19990 [04:18<07:12, 33.81it/s]

[5387] Геокодируем адрес: Косыгина ул 27к1, Санкт-Петербург

Геокодирование:  27%|██▋       | 5431/19990 [04:19<05:03, 47.97it/s]

Автосохранение после 5400 строк...
Автосохранение после 5430 строк...
[5444] Геокодируем адрес: Авиаконструкторов пр-т 4к1, Санкт-Петербург

Геокодирование:  27%|██▋       | 5445/19990 [04:20<07:01, 34.47it/s]

[5457] Геокодируем адрес: Шушары Старорусский пр-т, Санкт-Петербург

Геокодирование:  27%|██▋       | 5464/19990 [04:21<09:14, 26.19it/s]

Автосохранение после 5460 строк...
[5486] Геокодируем адрес: Новочеркасский пр-т 45к1, Санкт-Петербург

Геокодирование:  27%|██▋       | 5492/19990 [04:22<08:29, 28.47it/s]

Автосохранение после 5490 строк...
[5498] Геокодируем адрес: Дальневосточный пр-т 10, Санкт-Петербург

Геокодирование:  28%|██▊       | 5551/19990 [04:24<04:55, 48.94it/s]

Автосохранение после 5520 строк...
Автосохранение после 5550 строк...
[5559] Геокодируем адрес: Петергоф Никольская ул 10, Санкт-Петербург
[5560] Геокодируем адрес: Петергоф Ораниенбаумская ул, Санкт-Петербург

Геокодирование:  28%|██▊       | 5562/19990 [04:25<11:04, 21.71it/s]

[5564] Геокодируем адрес: Петергоф Никольская ул 10, Санкт-Петербург

Геокодирование:  28%|██▊       | 5581/19990 [04:26<11:59, 20.03it/s]

Автосохранение после 5580 строк...
[5592] Геокодируем адрес: Славы пр-т 8, Санкт-Петербург

Геокодирование:  28%|██▊       | 5611/19990 [04:27<09:18, 25.73it/s]

Автосохранение после 5610 строк...
[5637] Геокодируем адрес: Александровской Фермы пр-т 13, Санкт-Петербург

Геокодирование:  28%|██▊       | 5638/19990 [04:28<08:30, 28.09it/s]

[5640] Геокодируем адрес: 17-я линия ВО 12В, Санкт-Петербург
Автосохранение после 5640 строк...
[5641] Геокодируем адрес: Шушары Сарицкая ул, Санкт-Петербург

Геокодирование:  28%|██▊       | 5644/19990 [04:30<17:40, 13.53it/s]

[5670] Геокодируем адрес: Московский пр-т 83Ю, Санкт-Петербург

Геокодирование:  28%|██▊       | 5671/19990 [04:32<15:14, 15.65it/s]

Автосохранение после 5670 строк...
[5683] Геокодируем адрес: Кондратьевский пр-т 62к6, Санкт-Петербург

Геокодирование:  28%|██▊       | 5684/19990 [04:32<14:21, 16.60it/s]

[5687] Геокодируем адрес: Маршака пр-т 28к1, Санкт-Петербург

Геокодирование:  29%|██▊       | 5731/19990 [04:34<07:38, 31.09it/s]

Автосохранение после 5700 строк...
Автосохранение после 5730 строк...
[5731] Геокодируем адрес: Маршала Блюхера пр-т, Санкт-Петербург

Геокодирование:  29%|██▊       | 5741/19990 [04:35<09:51, 24.11it/s]

[5757] Геокодируем адрес: Херсонская ул 5-7С, Санкт-Петербург

Геокодирование:  29%|██▉       | 5764/19990 [04:36<10:22, 22.84it/s]

Автосохранение после 5760 строк...
[5781] Геокодируем адрес: Обуховской Обороны пр-т 219А, Санкт-Петербург

Геокодирование:  29%|██▉       | 5791/19990 [04:37<09:11, 25.76it/s]

Автосохранение после 5790 строк...
[5818] Геокодируем адрес: Культуры пр-т 12к1, Санкт-Петербург

Геокодирование:  29%|██▉       | 5851/19990 [04:38<05:02, 46.69it/s]

Автосохранение после 5820 строк...
Автосохранение после 5850 строк...
[5871] Геокодируем адрес: Маршала Блюхера пр-т 7к2, Санкт-Петербург

Геокодирование:  29%|██▉       | 5872/19990 [04:39<06:47, 34.65it/s]

[5872] Геокодируем адрес: Парголово Валерия Гаврилина ул 15, Санкт-Петербург

Геокодирование:  29%|██▉       | 5884/19990 [04:40<09:19, 25.19it/s]

Автосохранение после 5880 строк...
[5888] Геокодируем адрес: Петергоф Санкт-Петербургское ш 115К, Санкт-Петербург

Геокодирование:  29%|██▉       | 5889/19990 [04:41<13:44, 17.11it/s]

[5899] Геокодируем адрес: Большевиков пр-т 13к2, Санкт-Петербург

Геокодирование:  30%|██▉       | 5911/19990 [04:42<11:50, 19.82it/s]

Автосохранение после 5910 строк...
[5916] Геокодируем адрес: Петергоф Ропшинское ш, Санкт-Петербург

Геокодирование:  30%|██▉       | 5917/19990 [04:43<16:03, 14.60it/s]

[5930] Геокодируем адрес: Петергоф Ропшинское ш, Санкт-Петербург

Геокодирование:  30%|██▉       | 5931/19990 [04:44<16:31, 14.18it/s]

[5940] Геокодируем адрес: Петергоф Ропшинское ш, Санкт-Петербург

Геокодирование:  30%|██▉       | 5971/19990 [04:45<09:16, 25.20it/s]

Автосохранение после 5940 строк...
Автосохранение после 5970 строк...

Геокодирование:  30%|███       | 6001/19990 [04:45<05:39, 41.21it/s]

Автосохранение после 6000 строк...
[6013] Геокодируем адрес: Новаторов б-р, Санкт-Петербург

Геокодирование:  30%|███       | 6031/19990 [04:46<05:44, 40.52it/s]

Автосохранение после 6030 строк...
[6039] Геокодируем адрес: 3-я линия ВО, Санкт-Петербург

Геокодирование:  30%|███       | 6061/19990 [04:47<07:11, 32.26it/s]

Автосохранение после 6060 строк...
[6069] Геокодируем адрес: Колпино Адмиралтейская ул 19, Санкт-Петербург

Геокодирование:  31%|███       | 6121/19990 [04:48<03:58, 58.22it/s]

Автосохранение после 6090 строк...
Автосохранение после 6120 строк...
[6123] Геокодируем адрес: Металлострой Садовая ул 8, Санкт-Петербург

Геокодирование:  31%|███       | 6151/19990 [04:49<04:40, 49.35it/s]

Автосохранение после 6150 строк...
[6158] Геокодируем адрес: Науки пр-т 24к1, Санкт-Петербург

Геокодирование:  31%|███       | 6162/19990 [04:50<07:43, 29.86it/s]

[6162] Геокодируем адрес: Металлострой Школьная ул 7, Санкт-Петербург

Геокодирование:  31%|███       | 6170/19990 [04:51<11:19, 20.33it/s]

[6176] Геокодируем адрес: Испытателей пр-т 20, Санкт-Петербург

Геокодирование:  31%|███       | 6177/19990 [04:52<15:47, 14.57it/s]

[6178] Геокодируем адрес: Российский пр-т 14, Санкт-Петербург
[6179] Геокодируем адрес: Шушары Первомайская ул 16, Санкт-Петербург

Геокодирование:  31%|███       | 6182/19990 [04:54<28:14,  8.15it/s]

Автосохранение после 6180 строк...
[6193] Геокодируем адрес: Королева пр-т 39к2, Санкт-Петербург

Геокодирование:  31%|███       | 6211/19990 [04:55<14:41, 15.64it/s]

Автосохранение после 6210 строк...
[6229] Геокодируем адрес: Среднеохтинский пр-т 3к1, Санкт-Петербург

Геокодирование:  31%|███       | 6230/19990 [04:56<13:08, 17.46it/s]

[6230] Геокодируем адрес: Пушкин Петербургское ш 9, Санкт-Петербург

Геокодирование:  31%|███       | 6241/19990 [04:57<15:38, 14.65it/s]

Автосохранение после 6240 строк...
[6243] Геокодируем адрес: Маршака пр-т 28к1, Санкт-Петербург

Геокодирование:  31%|███       | 6245/19990 [04:58<19:42, 11.62it/s]

[6266] Геокодируем адрес: Литейный пр-т 60, Санкт-Петербург

Геокодирование:  31%|███▏      | 6267/19990 [04:59<15:31, 14.73it/s]

[6267] Геокодируем адрес: Лесной пр-т 32, Санкт-Петербург

Геокодирование:  31%|███▏      | 6272/19990 [05:00<22:03, 10.37it/s]

Автосохранение после 6270 строк...
[6286] Геокодируем адрес: Лиговский пр-т 117, Санкт-Петербург

Геокодирование:  31%|███▏      | 6287/19990 [05:02<25:43,  8.88it/s]

[6287] Геокодируем адрес: Лиговский пр-т 117, Санкт-Петербург

Геокодирование:  31%|███▏      | 6289/19990 [05:03<33:22,  6.84it/s]

[6291] Геокодируем адрес: Лиговский пр-т 117, Санкт-Петербург

Геокодирование:  32%|███▏      | 6301/19990 [05:05<25:40,  8.89it/s]

Автосохранение после 6300 строк...
[6326] Геокодируем адрес: Добролюбова пр-т 19, Санкт-Петербург

Геокодирование:  32%|███▏      | 6331/19990 [05:06<13:40, 16.64it/s]

Автосохранение после 6330 строк...
[6346] Геокодируем адрес: Маршала Блюхера пр-т 69А, Санкт-Петербург

Геокодирование:  32%|███▏      | 6361/19990 [05:07<09:27, 24.01it/s]

Автосохранение после 6360 строк...
[6386] Геокодируем адрес: Пушкин Алексея Толстого б-р 9, Санкт-Петербург

Геокодирование:  32%|███▏      | 6421/19990 [05:08<04:41, 48.25it/s]

Автосохранение после 6390 строк...
Автосохранение после 6420 строк...
[6426] Геокодируем адрес: Петергоф Ропшинское ш 10, Санкт-Петербург

Геокодирование:  32%|███▏      | 6430/19990 [05:09<11:47, 19.16it/s]

[6439] Геокодируем адрес: Славы пр-т 41, Санкт-Петербург

Геокодирование:  32%|███▏      | 6451/19990 [05:11<11:41, 19.31it/s]

Автосохранение после 6450 строк...
[6471] Геокодируем адрес: Левашово Карпова пр-т, Санкт-Петербург

Геокодирование:  32%|███▏      | 6472/19990 [05:11<10:01, 22.47it/s]

[6474] Геокодируем адрес: 7-я линия ВО, Санкт-Петербург

Геокодирование:  32%|███▏      | 6481/19990 [05:13<15:35, 14.44it/s]

Автосохранение после 6480 строк...
[6500] Геокодируем адрес: Малоохтинский пр-т 86к1, Санкт-Петербург

Геокодирование:  33%|███▎      | 6501/19990 [05:15<17:38, 12.74it/s]

[6502] Геокодируем адрес: Пушкин Церковная 6А, Санкт-Петербург

Геокодирование:  33%|███▎      | 6504/19990 [05:16<22:57,  9.79it/s]

[6509] Геокодируем адрес: Петергоф Ропшинское ш 10, Санкт-Петербург

Геокодирование:  33%|███▎      | 6541/19990 [05:17<09:25, 23.77it/s]

Автосохранение после 6510 строк...
Автосохранение после 6540 строк...
[6561] Геокодируем адрес: Комендантский пр-т 66/1 56/1, Санкт-Петербург

Геокодирование:  33%|███▎      | 6571/19990 [05:18<08:08, 27.49it/s]

Автосохранение после 6570 строк...
[6576] Геокодируем адрес: Космонавтов пр-т 29к8, Санкт-Петербург

Геокодирование:  33%|███▎      | 6577/19990 [05:19<10:59, 20.33it/s]

[6583] Геокодируем адрес: Трамвайный пр-т 13к1, Санкт-Петербург

Геокодирование:  33%|███▎      | 6631/19990 [05:20<05:25, 41.07it/s]

Автосохранение после 6600 строк...
Автосохранение после 6630 строк...

Геокодирование:  33%|███▎      | 6661/19990 [05:20<03:36, 61.63it/s]

Автосохранение после 6660 строк...
[6684] Геокодируем адрес: Поварской наб 13, Санкт-Петербург

Геокодирование:  33%|███▎      | 6696/19990 [05:21<04:08, 53.57it/s]

Автосохранение после 6690 строк...
[6705] Геокодируем адрес: Дунайский пр-т 14к1, Санкт-Петербург

Геокодирование:  34%|███▎      | 6721/19990 [05:22<05:38, 39.16it/s]

Автосохранение после 6720 строк...
[6735] Геокодируем адрес: Реки Оккервиль наб, Санкт-Петербург

Геокодирование:  34%|███▎      | 6736/19990 [05:23<07:30, 29.42it/s]

[6736] Геокодируем адрес: Поэтический б-р, Санкт-Петербург

Геокодирование:  34%|███▍      | 6751/19990 [05:24<09:56, 22.19it/s]

Автосохранение после 6750 строк...
[6772] Геокодируем адрес: Красное Село Гатчинское ш 6к2, Санкт-Петербург

Геокодирование:  34%|███▍      | 6773/19990 [05:25<10:13, 21.54it/s]

[6773] Геокодируем адрес: Обводного канала наб 118АЖ, Санкт-Петербург

Геокодирование:  34%|███▍      | 6777/19990 [05:26<13:02, 16.88it/s]

[6777] Геокодируем адрес: Муринский пр-т 3, Санкт-Петербург

Геокодирование:  34%|███▍      | 6783/19990 [05:27<19:01, 11.57it/s]

Автосохранение после 6780 строк...
[6783] Геокодируем адрес: Славы пр-т 17, Санкт-Петербург

Геокодирование:  34%|███▍      | 6841/19990 [05:28<05:22, 40.81it/s]

Автосохранение после 6810 строк...
Автосохранение после 6840 строк...

Геокодирование:  34%|███▍      | 6871/19990 [05:28<03:29, 62.60it/s]

Автосохранение после 6870 строк...
[6873] Геокодируем адрес: Петрегоф Луизино ул, Санкт-Петербург

Геокодирование:  34%|███▍      | 6886/19990 [05:29<04:34, 47.71it/s]

[6896] Геокодируем адрес: Металлострой Садовая ул 8, Санкт-Петербург

Геокодирование:  35%|███▍      | 6931/19990 [05:30<04:33, 47.78it/s]

Автосохранение после 6900 строк...
Автосохранение после 6930 строк...
[6945] Геокодируем адрес: Литейный пр-т 60, Санкт-Петербург

Геокодирование:  35%|███▍      | 6946/19990 [05:31<06:20, 34.31it/s]

[6957] Геокодируем адрес: Шушары Старорусский пр-т 6, Санкт-Петербург

Геокодирование:  35%|███▍      | 6991/19990 [05:33<05:07, 42.23it/s]

Автосохранение после 6960 строк...
Автосохранение после 6990 строк...

Геокодирование:  35%|███▌      | 7021/19990 [05:33<03:21, 64.39it/s]

Автосохранение после 7020 строк...
[7041] Геокодируем адрес: 21-я линия ВО 16к5, Санкт-Петербург

Геокодирование:  35%|███▌      | 7052/19990 [05:34<04:33, 47.29it/s]

Автосохранение после 7050 строк...
[7076] Геокодируем адрес: Культуры пр-т 29к4, Санкт-Петербург

Геокодирование:  35%|███▌      | 7085/19990 [05:35<05:08, 41.88it/s]

Автосохранение после 7080 строк...
[7107] Геокодируем адрес: Парголово Михаила Дудина ул, Санкт-Петербург

Геокодирование:  36%|███▌      | 7108/19990 [05:35<05:48, 36.94it/s]

Автосохранение после 7110 строк...
[7111] Геокодируем адрес: Шушары Новгородский пр-т 10, Санкт-Петербург
[7112] Геокодируем адрес: Лиговский пр-т 185, Санкт-Петербург

Геокодирование:  36%|███▌      | 7114/19990 [05:37<14:31, 14.78it/s]

[7134] Геокодируем адрес: Институтский пр-т 3к1, Санкт-Петербург

Геокодирование:  36%|███▌      | 7135/19990 [05:38<12:37, 16.97it/s]

[7138] Геокодируем адрес: Космонавтов пр-т 30к4, Санкт-Петербург

Геокодирование:  36%|███▌      | 7142/19990 [05:39<15:48, 13.55it/s]

Автосохранение после 7140 строк...
[7146] Геокодируем адрес: Товарищеский пр-т 2к1, Санкт-Петербург

Геокодирование:  36%|███▌      | 7147/19990 [05:40<19:43, 10.85it/s]

[7167] Геокодируем адрес: Народного ополчения пр-т 43, Санкт-Петербург

Геокодирование:  36%|███▌      | 7171/19990 [05:42<14:34, 14.66it/s]

Автосохранение после 7170 строк...
[7173] Геокодируем адрес: Ленинский пр-т 134к3, Санкт-Петербург

Геокодирование:  36%|███▌      | 7174/19990 [05:43<27:38,  7.73it/s]

[7196] Геокодируем адрес: Большевиков пр-т 3к1Д, Санкт-Петербург

Геокодирование:  36%|███▌      | 7231/19990 [05:45<07:22, 28.82it/s]

Автосохранение после 7200 строк...
Автосохранение после 7230 строк...
[7235] Геокодируем адрес: Заневский пр-т 71к2, Санкт-Петербург

Геокодирование:  36%|███▌      | 7239/19990 [05:45<09:38, 22.04it/s]

[7254] Геокодируем адрес: Ветеранов пр-т 109к4, Санкт-Петербург

Геокодирование:  36%|███▋      | 7261/19990 [05:46<10:08, 20.94it/s]

Автосохранение после 7260 строк...
[7261] Геокодируем адрес: Парголово Ольгинская ул, Санкт-Петербург

Геокодирование:  36%|███▋      | 7291/19990 [05:47<07:17, 29.00it/s]

Автосохранение после 7290 строк...
[7294] Геокодируем адрес: Каховский пер 2Т, Санкт-Петербург

Геокодирование:  37%|███▋      | 7299/19990 [05:48<10:39, 19.84it/s]

[7301] Геокодируем адрес: Торфяная дор, Санкт-Петербург
[7302] Геокодируем адрес: Муринская дор, Санкт-Петербург
[7304] Геокодируем адрес: Обуховской Обороны пр-т 35Б, Санкт-Петербург

Геокодирование:  37%|███▋      | 7305/19990 [05:51<27:14,  7.76it/s]

[7305] Геокодируем адрес: Стрельна Связи ул, Санкт-Петербург
[7308] Геокодируем адрес: Ветеранов пр-т 114к1, Санкт-Петербург

Геокодирование:  37%|███▋      | 7309/19990 [05:53<37:19,  5.66it/s]

[7312] Геокодируем адрес: Обуховской Обороны пр-т 35, Санкт-Петербург

Геокодирование:  37%|███▋      | 7313/19990 [05:54<40:55,  5.16it/s]

[7313] Геокодируем адрес: Обуховской Обороны пр-т 39, Санкт-Петербург

Геокодирование:  37%|███▋      | 7321/19990 [05:56<34:27,  6.13it/s]

Автосохранение после 7320 строк...
[7342] Геокодируем адрес: Светлановский пр-т 38, Санкт-Петербург

Геокодирование:  37%|███▋      | 7343/19990 [05:56<17:54, 11.77it/s]

[7345] Геокодируем адрес: Колпино Заводской пр-т 34, Санкт-Петербург

Геокодирование:  37%|███▋      | 7346/19990 [05:57<23:37,  8.92it/s]

[7347] Геокодируем адрес: Юнтоловский ул 53к1, Санкт-Петербург

Геокодирование:  37%|███▋      | 7351/19990 [05:58<26:39,  7.90it/s]

Автосохранение после 7350 строк...
[7353] Геокодируем адрес: Большой Петроградской стороны пр-т, Санкт-Петербург

Геокодирование:  37%|███▋      | 7354/19990 [05:59<35:15,  5.97it/s]

[7359] Геокодируем адрес: Обуховской Обороны пр-т 35Б, Санкт-Петербург

Геокодирование:  37%|███▋      | 7360/19990 [06:00<35:08,  5.99it/s]

[7365] Геокодируем адрес: Обуховской Обороны пр-т 33к2, Санкт-Петербург

Геокодирование:  37%|███▋      | 7366/19990 [06:01<33:56,  6.20it/s]

[7377] Геокодируем адрес: Комендантский пр-т 36к2, Санкт-Петербург

Геокодирование:  37%|███▋      | 7381/19990 [06:02<23:26,  8.97it/s]

Автосохранение после 7380 строк...
[7383] Геокодируем адрес: Комендантский пр-т 53к4, Санкт-Петербург

Геокодирование:  37%|███▋      | 7384/19990 [06:03<29:35,  7.10it/s]

[7392] Геокодируем адрес: Стачек пр-т 138, Санкт-Петербург

Геокодирование:  37%|███▋      | 7393/19990 [06:04<27:55,  7.52it/s]

[7394] Геокодируем адрес: Народного Ополчения пр-т 113В, Санкт-Петербург

Геокодирование:  37%|███▋      | 7395/19990 [06:05<35:49,  5.86it/s]

[7398] Геокодируем адрес: Ленинский пр-т 134к2, Санкт-Петербург

Геокодирование:  37%|███▋      | 7399/19990 [06:06<40:24,  5.19it/s]

[7401] Геокодируем адрес: Культуры пр-т 11а, Санкт-Петербург

Геокодирование:  37%|███▋      | 7402/19990 [06:08<50:06,  4.19it/s]

[7403] Геокодируем адрес: Пискаревский пр-т 37, Санкт-Петербург

Геокодирование:  37%|███▋      | 7404/19990 [06:08<56:40,  3.70it/s]

[7405] Геокодируем адрес: Ветеранов пр-т 189, Санкт-Петербург

Геокодирование:  37%|███▋      | 7406/19990 [06:10<1:10:44,  2.97it/s]

[7408] Геокодируем адрес: Культуры пр-т 11а, Санкт-Петербург

Геокодирование:  37%|███▋      | 7411/19990 [06:11<57:36,  3.64it/s]

Автосохранение после 7410 строк...
[7411] Геокодируем адрес: Вилькицкий б-р, Санкт-Петербург

Геокодирование:  37%|███▋      | 7412/19990 [06:11<1:07:52,  3.09it/s]

[7419] Геокодируем адрес: Лиговский пр-т 89/20, Санкт-Петербург

Геокодирование:  37%|███▋      | 7420/19990 [06:12<44:02,  4.76it/s]

[7422] Геокодируем адрес: Лиговский пр-т 89/20, Санкт-Петербург

Геокодирование:  37%|███▋      | 7441/19990 [06:14<17:48, 11.74it/s]

Автосохранение после 7440 строк...
[7443] Геокодируем адрес: Маршала Жукова пр-т 18, Санкт-Петербург
[7444] Геокодируем адрес: Ветеранов пр-т 88, Санкт-Петербург

Геокодирование:  37%|███▋      | 7445/19990 [06:16<41:01,  5.10it/s]

[7450] Геокодируем адрес: Пушкин Ахматовкая ул 5, Санкт-Петербург

Геокодирование:  37%|███▋      | 7451/19990 [06:17<37:29,  5.57it/s]

[7451] Геокодируем адрес: Металлистов пр-т 21к3, Санкт-Петербург

Геокодирование:  37%|███▋      | 7454/19990 [06:18<44:32,  4.69it/s]

[7460] Геокодируем адрес: Красное Село Гатчинское ш 4к3, Санкт-Петербург

Геокодирование:  37%|███▋      | 7461/19990 [06:20<40:41,  5.13it/s]

[7461] Геокодируем адрес: Маршала Жукова ул 30к2, Санкт-Петербург

Геокодирование:  37%|███▋      | 7463/19990 [06:20<46:48,  4.46it/s]

[7463] Геокодируем адрес: Новоизмайловский пр-т 16к3, Санкт-Петербург

Геокодирование:  37%|███▋      | 7464/19990 [06:21<58:35,  3.56it/s]

[7468] Геокодируем адрес: Витебский пр-т 55, Санкт-Петербург

Геокодирование:  37%|███▋      | 7469/19990 [06:23<55:20,  3.77it/s]

[7470] Геокодируем адрес: Елизарова ул 10, Санкт-Петербург

Геокодирование:  37%|███▋      | 7471/19990 [06:24<1:03:37,  3.28it/s]

Автосохранение после 7470 строк...
[7479] Геокодируем адрес: Петергоф Демьяна Бедного ул, Санкт-Петербург

Геокодирование:  37%|███▋      | 7480/19990 [06:24<40:10,  5.19it/s]

[7480] Геокодируем адрес: Петергоф Воровского ул, Санкт-Петербург

Геокодирование:  37%|███▋      | 7481/19990 [06:25<53:02,  3.93it/s]

[7483] Геокодируем адрес: Лесной пр-т 39к3, Санкт-Петербург

Геокодирование:  37%|███▋      | 7484/19990 [06:26<58:21,  3.57it/s]

[7497] Геокодируем адрес: Ульяны Громовой ул 8Б, Санкт-Петербург

Геокодирование:  38%|███▊      | 7501/19990 [06:28<28:28,  7.31it/s]

Автосохранение после 7500 строк...
[7502] Геокодируем адрес: Петергоф Воровского ул, Санкт-Петербург

Геокодирование:  38%|███▊      | 7503/19990 [06:28<34:25,  6.05it/s]

[7508] Геокодируем адрес: Косыгина пр-т 28к1, Санкт-Петербург

Геокодирование:  38%|███▊      | 7509/19990 [06:30<36:34,  5.69it/s]

[7514] Геокодируем адрес: Петергоф Демьяна Бедного ул, Санкт-Петербург

Геокодирование:  38%|███▊      | 7515/19990 [06:30<34:10,  6.08it/s]

[7515] Геокодируем адрес: Петергоф Урицкого ул, Санкт-Петербург

Геокодирование:  38%|███▊      | 7516/19990 [06:31<47:19,  4.39it/s]

[7518] Геокодируем адрес: Петергоф Урицкого ул, Санкт-Петербург

Геокодирование:  38%|███▊      | 7519/19990 [06:32<52:29,  3.96it/s]

[7519] Геокодируем адрес: Петергоф Демьяна Бедного ул, Санкт-Петербург

Геокодирование:  38%|███▊      | 7520/19990 [06:34<1:30:25,  2.30it/s]

[7520] Геокодируем адрес: Петергоф Демьяна Бедного ул, Санкт-Петербург

Геокодирование:  38%|███▊      | 7521/19990 [06:35<1:45:09,  1.98it/s]

[7523] Геокодируем адрес: Петергоф Демьяна Бедного ул 10А, Санкт-Петербург

Геокодирование:  38%|███▊      | 7524/19990 [06:37<1:36:10,  2.16it/s]

[7525] Геокодируем адрес: Обуховской Обороны пр-т 33к2, Санкт-Петербург

Геокодирование:  38%|███▊      | 7526/19990 [06:37<1:34:29,  2.20it/s]

[7529] Геокодируем адрес: Петергоф Демьяна Бедного ул 10А, Санкт-Петербург

Геокодирование:  38%|███▊      | 7531/19990 [06:39<1:12:41,  2.86it/s]

Автосохранение после 7530 строк...
[7533] Геокодируем адрес: Ветеранов пр-т 151, Санкт-Петербург

Геокодирование:  38%|███▊      | 7534/19990 [06:41<1:36:45,  2.15it/s]

[7536] Геокодируем адрес: Новаторов б-р 80к3, Санкт-Петербург

Геокодирование:  38%|███▊      | 7537/19990 [06:41<1:20:57,  2.56it/s]

[7547] Геокодируем адрес: Петергоф Демьяна Бедного ул, Санкт-Петербург

Геокодирование:  38%|███▊      | 7548/19990 [06:42<41:50,  4.96it/s]

[7548] Геокодируем адрес: Обуховской Обороны пр-т 227к1Б, Санкт-Петербург

Геокодирование:  38%|███▊      | 7549/19990 [06:43<52:44,  3.93it/s]

[7553] Геокодируем адрес: Петергоф Ропшинское ш, Санкт-Петербург

Геокодирование:  38%|███▊      | 7554/19990 [06:44<50:14,  4.12it/s]

[7555] Геокодируем адрес: Петергоф Демьяна Бедного ул, Санкт-Петербург

Геокодирование:  38%|███▊      | 7561/19990 [06:46<39:03,  5.30it/s]

Автосохранение после 7560 строк...
[7562] Геокодируем адрес: Петергоф Ропшинское ш, Санкт-Петербург

Геокодирование:  38%|███▊      | 7563/19990 [06:46<47:23,  4.37it/s]

[7563] Геокодируем адрес: Петергоф Ропшинское ш, Санкт-Петербург

Геокодирование:  38%|███▊      | 7564/19990 [06:47<1:05:30,  3.16it/s]

[7564] Геокодируем адрес: Петергоф Ропшинское ш, Санкт-Петербург

Геокодирование:  38%|███▊      | 7565/19990 [06:48<1:25:43,  2.42it/s]

[7565] Геокодируем адрес: Просвещения пр-т 14к4Ж, Санкт-Петербург

Геокодирование:  38%|███▊      | 7566/19990 [06:49<1:42:17,  2.02it/s]

[7575] Геокодируем адрес: Культуры пр-т, Санкт-Петербург

Геокодирование:  38%|███▊      | 7576/19990 [06:50<46:49,  4.42it/s]

[7577] Геокодируем адрес: Обуховской Обороны пр-т 33А, Санкт-Петербург

Геокодирование:  38%|███▊      | 7591/19990 [06:52<24:14,  8.52it/s]

Автосохранение после 7590 строк...
[7603] Геокодируем адрес: Авиаконструкторов пр-т 16к1, Санкт-Петербург

Геокодирование:  38%|███▊      | 7604/19990 [06:52<18:27, 11.18it/s]

[7605] Геокодируем адрес: Московский пр-т 105, Санкт-Петербург

Геокодирование:  38%|███▊      | 7607/19990 [06:54<27:06,  7.61it/s]

[7614] Геокодируем адрес: Большой Васильевский остров пр-т, Санкт-Петербург

Геокодирование:  38%|███▊      | 7615/19990 [06:55<25:33,  8.07it/s]

[7615] Геокодируем адрес: Без названия пр-д, Санкт-Петербург

Геокодирование:  38%|███▊      | 7617/19990 [06:55<32:54,  6.27it/s]

[7620] Геокодируем адрес: Ветеранов пр-т 102, Санкт-Петербург

Геокодирование:  38%|███▊      | 7621/19990 [06:57<40:33,  5.08it/s]

Автосохранение после 7620 строк...
[7636] Геокодируем адрес: Маршала Жукова пр-т 62к2, Санкт-Петербург

Геокодирование:  38%|███▊      | 7637/19990 [06:57<22:40,  9.08it/s]

[7637] Геокодируем адрес: Маршала Блюхера пр-т 29, Санкт-Петербург

Геокодирование:  38%|███▊      | 7639/19990 [06:59<31:21,  6.56it/s]

[7639] Геокодируем адрес: Славы пр-т 2к4, Санкт-Петербург

Геокодирование:  38%|███▊      | 7651/19990 [07:00<21:50,  9.42it/s]

Автосохранение после 7650 строк...
[7660] Геокодируем адрес: Октябрьский б-р 22А, Санкт-Петербург

Геокодирование:  38%|███▊      | 7661/19990 [07:01<21:14,  9.67it/s]

[7661] Геокодируем адрес: Новоизмайловский пр-т 67к2, Санкт-Петербург

Геокодирование:  38%|███▊      | 7664/19990 [07:01<25:51,  7.94it/s]

[7668] Геокодируем адрес: Искровский пр-т 3к2, Санкт-Петербург

Геокодирование:  38%|███▊      | 7681/19990 [07:03<17:46, 11.54it/s]

Автосохранение после 7680 строк...
[7705] Геокодируем адрес: Просвещения пр-т 21/139, Санкт-Петербург

Геокодирование:  39%|███▊      | 7706/19990 [07:04<11:44, 17.44it/s]

[7706] Геокодируем адрес: Энергетиков пр-т 9к6, Санкт-Петербург
[7707] Геокодируем адрес: Дачный пр-т 16к1, Санкт-Петербург

Геокодирование:  39%|███▊      | 7713/19990 [07:06<20:49,  9.82it/s]

Автосохранение после 7710 строк...
[7713] Геокодируем адрес: Парголово Заречная ул 17к1, Санкт-Петербург
[7715] Геокодируем адрес: Малый васильевский остров пр-т, Санкт-Петербург

Геокодирование:  39%|███▊      | 7716/19990 [07:08<35:28,  5.77it/s]

[7717] Геокодируем адрес: Обуховской Обороны пр-т 33к2, Санкт-Петербург

Геокодирование:  39%|███▊      | 7718/19990 [07:08<42:06,  4.86it/s]

[7719] Геокодируем адрес: Балтийский б-р, Санкт-Петербург

Геокодирование:  39%|███▊      | 7720/19990 [07:09<50:44,  4.03it/s]

[7720] Геокодируем адрес: Павловск Надгорная ул, Санкт-Петербург

Геокодирование:  39%|███▊      | 7721/19990 [07:10<1:03:35,  3.22it/s]

[7723] Геокодируем адрес: Ветеранов пр-т 149, Санкт-Петербург

Геокодирование:  39%|███▊      | 7724/19990 [07:12<1:10:03,  2.92it/s]

[7728] Геокодируем адрес: Кондратьевский пр-т 85, Санкт-Петербург

Геокодирование:  39%|███▊      | 7729/19990 [07:12<55:48,  3.66it/s]

[7729] Геокодируем адрес: Стачек пр-т 95к1, Санкт-Петербург

Геокодирование:  39%|███▊      | 7730/19990 [07:13<1:08:45,  2.97it/s]

[7730] Геокодируем адрес: Дальневосточный пр-т 38, Санкт-Петербург

Геокодирование:  39%|███▉      | 7771/19990 [07:15<09:48, 20.78it/s]

Автосохранение после 7740 строк...
Автосохранение после 7770 строк...
[7777] Геокодируем адрес: Кронверкский пр-т 69Б, Санкт-Петербург

Геокодирование:  39%|███▉      | 7779/19990 [07:16<11:19, 17.96it/s]

[7782] Геокодируем адрес: Комендантский пр-т 13к1, Санкт-Петербург

Геокодирование:  39%|███▉      | 7801/19990 [07:17<10:01, 20.26it/s]

Автосохранение после 7800 строк...
[7806] Геокодируем адрес: Маршала Жукова пр-т 30к2, Санкт-Петербург

Геокодирование:  39%|███▉      | 7808/19990 [07:18<12:52, 15.76it/s]

[7815] Геокодируем адрес: Сизова пр-т 14, Санкт-Петербург

Геокодирование:  39%|███▉      | 7816/19990 [07:19<16:18, 12.44it/s]

[7825] Геокодируем адрес: Ветеранов пр-т 67к1, Санкт-Петербург

Геокодирование:  39%|███▉      | 7831/19990 [07:20<15:06, 13.41it/s]

Автосохранение после 7830 строк...
[7832] Геокодируем адрес: Парголово Межозерная ул, Санкт-Петербург

Геокодирование:  39%|███▉      | 7834/19990 [07:21<20:32,  9.86it/s]

[7836] Геокодируем адрес: Песочный Садовая ул 44А, Санкт-Петербург

Геокодирование:  39%|███▉      | 7837/19990 [07:22<28:54,  7.01it/s]

[7837] Геокодируем адрес: Ветеранов пр-т 122, Санкт-Петербург

Геокодирование:  39%|███▉      | 7839/19990 [07:23<40:02,  5.06it/s]

[7843] Геокодируем адрес: Поэтический б-р 11к1, Санкт-Петербург

Геокодирование:  39%|███▉      | 7844/19990 [07:24<38:17,  5.29it/s]

[7846] Геокодируем адрес: Красных Зорь б-р 20, Санкт-Петербург

Геокодирование:  39%|███▉      | 7847/19990 [07:25<47:15,  4.28it/s]

[7848] Геокодируем адрес: Пушкин Анциферовская ул 12, Санкт-Петербург

Геокодирование:  39%|███▉      | 7849/19990 [07:26<53:53,  3.76it/s]

[7850] Геокодируем адрес: Пушкин Анциферовская ул 12, Санкт-Петербург

Геокодирование:  39%|███▉      | 7851/19990 [07:27<1:03:24,  3.19it/s]

[7857] Геокодируем адрес: Александровской Фермы пр-т 13, Санкт-Петербург

Геокодирование:  39%|███▉      | 7858/19990 [07:28<47:35,  4.25it/s]

[7858] Геокодируем адрес: Колпино Тверская ул 44, Санкт-Петербург

Геокодирование:  39%|███▉      | 7859/19990 [07:29<59:47,  3.38it/s]

[7860] Геокодируем адрес: Шлиссельбургский пр-т 12к1, Санкт-Петербург

Геокодирование:  39%|███▉      | 7861/19990 [07:30<1:12:19,  2.79it/s]

Автосохранение после 7860 строк...
[7861] Геокодируем адрес: Непокоренных пр-т 9к2, Санкт-Петербург

Геокодирование:  39%|███▉      | 7862/19990 [07:31<1:22:28,  2.45it/s]

[7863] Геокодируем адрес: Колпино Тверская ул 44, Санкт-Петербург

Геокодирование:  39%|███▉      | 7864/19990 [07:32<1:29:20,  2.26it/s]

[7868] Геокодируем адрес: Суворовский пр-т 62, Санкт-Петербург

Геокодирование:  39%|███▉      | 7869/19990 [07:33<1:06:34,  3.03it/s]

[7873] Геокодируем адрес: Большой Васильевский остров пр-т, Санкт-Петербург

Геокодирование:  39%|███▉      | 7874/19990 [07:34<56:08,  3.60it/s]

[7877] Геокодируем адрес: Непокоренных пр-т 9к2, Санкт-Петербург

Геокодирование:  39%|███▉      | 7878/19990 [07:35<52:23,  3.85it/s]

[7878] Геокодируем адрес: Непокоренных пр-т 9к1, Санкт-Петербург

Геокодирование:  39%|███▉      | 7879/19990 [07:36<1:07:40,  2.98it/s]

[7880] Геокодируем адрес: Славы пр-т 29, Санкт-Петербург

Геокодирование:  39%|███▉      | 7891/19990 [07:37<31:56,  6.31it/s]

Автосохранение после 7890 строк...
[7892] Геокодируем адрес: Маршала Блюхера пр-т, Санкт-Петербург

Геокодирование:  39%|███▉      | 7894/19990 [07:38<36:11,  5.57it/s]

[7894] Геокодируем адрес: Зеленогорск Театральная ул, Санкт-Петербург
[7895] Геокодируем адрес: Пархоменко пр-т 47, Санкт-Петербург

Геокодирование:  39%|███▉      | 7896/19990 [07:40<1:03:17,  3.19it/s]

[7896] Геокодируем адрес: Санкт-Петербургский пр-т 31, Санкт-Петербург

Геокодирование:  40%|███▉      | 7898/19990 [07:41<1:11:32,  2.82it/s]

[7898] Геокодируем адрес: Кондратьевский пр-т 62к1, Санкт-Петербург

Геокодирование:  40%|███▉      | 7899/19990 [07:42<1:23:19,  2.42it/s]

[7904] Геокодируем адрес: Петровский пр-т 20к6, Санкт-Петербург

Геокодирование:  40%|███▉      | 7905/19990 [07:43<58:43,  3.43it/s]

[7911] Геокодируем адрес: Красное Село Нарвская ул 8к1, Санкт-Петербург

Геокодирование:  40%|███▉      | 7921/19990 [07:44<27:28,  7.32it/s]

Автосохранение после 7920 строк...
[7923] Геокодируем адрес: Лиговский пр-т 89/20, Санкт-Петербург

Геокодирование:  40%|███▉      | 7924/19990 [07:45<31:53,  6.31it/s]

[7927] Геокодируем адрес: Тихорецкий пр-т 25к1, Санкт-Петербург

Геокодирование:  40%|███▉      | 7928/19990 [07:46<35:30,  5.66it/s]

[7930] Геокодируем адрес: Невский пр-т 95, Санкт-Петербург

Геокодирование:  40%|███▉      | 7931/19990 [07:47<43:10,  4.65it/s]

[7932] Геокодируем адрес: Красное Село Ленина пр-т 75, Санкт-Петербург

Геокодирование:  40%|███▉      | 7933/19990 [07:48<56:04,  3.58it/s]

[7936] Геокодируем адрес: Просвещения пр-т 33к1, Санкт-Петербург

Геокодирование:  40%|███▉      | 7951/19990 [07:49<20:25,  9.82it/s]

Автосохранение после 7950 строк...
[7954] Геокодируем адрес: Культуры пр-т, Санкт-Петербург

Геокодирование:  40%|███▉      | 7955/19990 [07:50<24:31,  8.18it/s]

[7961] Геокодируем адрес: Горелово 5-й пр-д, Санкт-Петербург

Геокодирование:  40%|███▉      | 7962/19990 [07:51<26:02,  7.70it/s]

[7966] Геокодируем адрес: Парголово Голицынская ул, Санкт-Петербург

Геокодирование:  40%|███▉      | 7967/19990 [07:52<28:50,  6.95it/s]

[7967] Геокодируем адрес: Большевиков пр-т 30к1, Санкт-Петербург

Геокодирование:  40%|███▉      | 7969/19990 [07:53<39:19,  5.09it/s]

[7971] Геокодируем адрес: Лиговский пр-т 40, Санкт-Петербург

Геокодирование:  40%|███▉      | 7972/19990 [07:54<45:58,  4.36it/s]

[7977] Геокодируем адрес: Колпино Веры Слуцкой ул 38, Санкт-Петербург

Геокодирование:  40%|███▉      | 7978/19990 [07:55<40:24,  4.96it/s]

[7978] Геокодируем адрес: Колпино Веры Слуцкой ул 32, Санкт-Петербург

Геокодирование:  40%|███▉      | 7981/19990 [07:56<46:18,  4.32it/s]

Автосохранение после 7980 строк...
[7981] Геокодируем адрес: Пушкин Рехколовское ш, Санкт-Петербург

Геокодирование:  40%|███▉      | 7982/19990 [07:57<59:20,  3.37it/s]

[7991] Геокодируем адрес: Юнтоловский пр-т 48к1, Санкт-Петербург

Геокодирование:  40%|███▉      | 7992/19990 [07:58<34:13,  5.84it/s]

[7992] Геокодируем адрес: Пушкин Гусарская ул 6к2, Санкт-Петербург

Геокодирование:  40%|███▉      | 7993/19990 [07:59<49:03,  4.08it/s]

[7994] Геокодируем адрес: Петергоф Демьяна Бедного ул, Санкт-Петербург

Геокодирование:  40%|████      | 8011/19990 [08:00<19:13, 10.39it/s]

Автосохранение после 8010 строк...
[8015] Геокодируем адрес: Шушары Торопецкая ул, Санкт-Петербург

Геокодирование:  40%|████      | 8016/19990 [08:01<22:41,  8.79it/s]

[8017] Геокодируем адрес: Красное Село Ленина пр-т 92к1, Санкт-Петербург
[8018] Геокодируем адрес: Индустриальный пр-т 35к3, Санкт-Петербург

Геокодирование:  40%|████      | 8019/19990 [08:03<41:38,  4.79it/s]

[8021] Геокодируем адрес: Металлострой Садовая ул 8, Санкт-Петербург

Геокодирование:  40%|████      | 8022/19990 [08:04<46:21,  4.30it/s]

[8022] Геокодируем адрес: Металлострой Садовая ул 8, Санкт-Петербург

Геокодирование:  40%|████      | 8024/19990 [08:05<54:24,  3.67it/s]

[8028] Геокодируем адрес: Металлострой Садовая ул 8, Санкт-Петербург

Геокодирование:  40%|████      | 8029/19990 [08:06<49:34,  4.02it/s]

[8030] Геокодируем адрес: Металлострой Садовая ул 8, Санкт-Петербург

Геокодирование:  40%|████      | 8031/19990 [08:07<57:51,  3.45it/s]

[8031] Геокодируем адрес: Пушкин Генерала Хазова ул 2, Санкт-Петербург

Геокодирование:  40%|████      | 8032/19990 [08:08<1:14:08,  2.69it/s]

[8033] Геокодируем адрес: Лиговский пр-т 91, Санкт-Петербург

Геокодирование:  40%|████      | 8034/19990 [08:09<1:22:18,  2.42it/s]

[8034] Геокодируем адрес: Новоизмайловский пр-т 30, Санкт-Петербург

Геокодирование:  40%|████      | 8035/19990 [08:10<1:36:34,  2.06it/s]

[8037] Геокодируем адрес: пос. Металлострой Садовая ул, Санкт-Петербург

Геокодирование:  40%|████      | 8038/19990 [08:11<1:24:44,  2.35it/s]

[8038] Геокодируем адрес: пос. Металлострой Садовая ул, Санкт-Петербург

Геокодирование:  40%|████      | 8041/19990 [08:12<1:15:54,  2.62it/s]

Автосохранение после 8040 строк...
[8046] Геокодируем адрес: Энгельса пр-т 21, Санкт-Петербург

Геокодирование:  40%|████      | 8047/19990 [08:13<51:03,  3.90it/s]

[8051] Геокодируем адрес: Славы пр-т 25, Санкт-Петербург

Геокодирование:  40%|████      | 8052/19990 [08:14<47:12,  4.21it/s]

[8054] Геокодируем адрес: Пушкин Рехколовское ш, Санкт-Петербург

Геокодирование:  40%|████      | 8055/19990 [08:15<48:34,  4.10it/s]

[8055] Геокодируем адрес: 21-я линия ВО, Санкт-Петербург

Геокодирование:  40%|████      | 8056/19990 [08:17<1:38:21,  2.02it/s]

[8061] Геокодируем адрес: Дальневосточный пр-т 58, Санкт-Петербург

Геокодирование:  40%|████      | 8062/19990 [08:18<1:03:28,  3.13it/s]

[8066] Геокодируем адрес: Кузнецова пр-т 23к1, Санкт-Петербург

Геокодирование:  40%|████      | 8067/19990 [08:19<53:40,  3.70it/s]

[8068] Геокодируем адрес: Малая Митрофаньевская ул 5к1стр1, Санкт-Петербург

Геокодирование:  40%|████      | 8069/19990 [08:20<58:57,  3.37it/s]

[8070] Геокодируем адрес: Обуховской Обороны пр-т 93Р, Санкт-Петербург

Геокодирование:  40%|████      | 8071/19990 [08:21<1:12:46,  2.73it/s]

Автосохранение после 8070 строк...
[8073] Геокодируем адрес: Наставников пр-т 27, Санкт-Петербург

Геокодирование:  40%|████      | 8074/19990 [08:22<1:08:17,  2.91it/s]

[8074] Геокодируем адрес: Московский пр-т, Санкт-Петербург

Геокодирование:  40%|████      | 8075/19990 [08:23<1:23:12,  2.39it/s]

[8078] Геокодируем адрес: Богатырский пр-т 51к1, Санкт-Петербург

Геокодирование:  40%|████      | 8079/19990 [08:24<1:09:44,  2.85it/s]

[8080] Геокодируем адрес: Лиговский пр-т 81, Санкт-Петербург

Геокодирование:  40%|████      | 8081/19990 [08:25<1:18:15,  2.54it/s]

[8084] Геокодируем адрес: Колпино Культуры ул 3, Санкт-Петербург

Геокодирование:  40%|████      | 8085/19990 [08:26<1:04:43,  3.07it/s]

[8085] Геокодируем адрес: Тихорецкий пр-т 24к1, Санкт-Петербург

Геокодирование:  40%|████      | 8086/19990 [08:27<1:21:02,  2.45it/s]

[8094] Геокодируем адрес: Шушарская ул, Санкт-Петербург

Геокодирование:  41%|████      | 8101/19990 [08:28<29:49,  6.64it/s]

Автосохранение после 8100 строк...
[8102] Геокодируем адрес: Парголово Шишкина ул 301стр1, Санкт-Петербург

Геокодирование:  41%|████      | 8103/19990 [08:29<37:04,  5.34it/s]

[8103] Геокодируем адрес: Искровский пр-т 32к1, Санкт-Петербург

Геокодирование:  41%|████      | 8105/19990 [08:30<50:29,  3.92it/s]

[8105] Геокодируем адрес: Сиреневый б-р 4к2, Санкт-Петербург

Геокодирование:  41%|████      | 8106/19990 [08:31<1:06:23,  2.98it/s]

[8116] Геокодируем адрес: Полюстровский пр-т 5, Санкт-Петербург

Геокодирование:  41%|████      | 8117/19990 [08:32<36:03,  5.49it/s]

[8124] Геокодируем адрес: Парголово Федора Абрамова ул 21к3, Санкт-Петербург

Геокодирование:  41%|████      | 8125/19990 [08:33<30:42,  6.44it/s]

[8127] Геокодируем адрес: Пушкин Конюшенная ул 38/37, Санкт-Петербург

Геокодирование:  41%|████      | 8131/19990 [08:34<32:41,  6.05it/s]

Автосохранение после 8130 строк...
[8134] Геокодируем адрес: Московский пр-т 165к2, Санкт-Петербург

Геокодирование:  41%|████      | 8135/19990 [08:35<33:12,  5.95it/s]

[8146] Геокодируем адрес: Ветеранов пр-т 160, Санкт-Петербург

Геокодирование:  41%|████      | 8147/19990 [08:36<25:37,  7.70it/s]

[8148] Геокодируем адрес: Лесной пр-т 39к3, Санкт-Петербург

Геокодирование:  41%|████      | 8149/19990 [08:37<32:22,  6.10it/s]

[8152] Геокодируем адрес: Павловск Правды ул, Санкт-Петербург

Геокодирование:  41%|████      | 8153/19990 [08:38<35:46,  5.51it/s]

[8155] Геокодируем адрес: Обуховской Обороны пр-т 89Б, Санкт-Петербург

Геокодирование:  41%|████      | 8161/19990 [08:39<30:28,  6.47it/s]

Автосохранение после 8160 строк...
[8162] Геокодируем адрес: Петергоф Демьяна Бедного ул, Санкт-Петербург

Геокодирование:  41%|████      | 8191/19990 [08:40<09:55, 19.81it/s]

Автосохранение после 8190 строк...
[8192] Геокодируем адрес: Дачный пр-т 7к1, Санкт-Петербург
[8197] Геокодируем адрес: Сиреневый б-р, Санкт-Петербург

Геокодирование:  41%|████      | 8198/19990 [08:42<19:14, 10.21it/s]

[8200] Геокодируем адрес: 25-я линия ВО, Санкт-Петербург

Геокодирование:  41%|████      | 8203/19990 [08:43<26:22,  7.45it/s]

[8204] Геокодируем адрес: Маршала Блюхера пр-т 44, Санкт-Петербург
[8206] Геокодируем адрес: Шушары Пушкинская ул, Санкт-Петербург

Геокодирование:  41%|████      | 8207/19990 [08:45<35:18,  5.56it/s]

[8207] Геокодируем адрес: Шушары Пушкинская ул, Санкт-Петербург
[8208] Геокодируем адрес: Шушары Пушкинская ул, Санкт-Петербург

Геокодирование:  41%|████      | 8210/19990 [08:47<50:05,  3.92it/s]

[8210] Геокодируем адрес: Павловск Васенко ул, Санкт-Петербург
[8211] Геокодируем адрес: Павловск Васенко ул, Санкт-Петербург

Геокодирование:  41%|████      | 8212/19990 [08:49<1:08:57,  2.85it/s]

[8215] Геокодируем адрес: Просвещения пр-т 27к3, Санкт-Петербург

Геокодирование:  41%|████      | 8221/19990 [08:50<44:47,  4.38it/s]

Автосохранение после 8220 строк...
[8226] Геокодируем адрес: Шушары Дальневосточный пр-т, Санкт-Петербург

Геокодирование:  41%|████      | 8227/19990 [08:51<38:53,  5.04it/s]

[8230] Геокодируем адрес: Просвещения пр-т 27к3, Санкт-Петербург

Геокодирование:  41%|████      | 8231/19990 [08:52<41:18,  4.74it/s]

[8235] Геокодируем адрес: 1й Предпортовый пр-д, Санкт-Петербург

Геокодирование:  41%|████      | 8236/19990 [08:53<41:40,  4.70it/s]

[8238] Геокодируем адрес: Богатырский пр-т 35к2, Санкт-Петербург

Геокодирование:  41%|████      | 8239/19990 [08:54<45:23,  4.31it/s]

[8240] Геокодируем адрес: Богатырский пр-т 53к3, Санкт-Петербург

Геокодирование:  41%|████      | 8241/19990 [08:55<54:16,  3.61it/s]

[8244] Геокодируем адрес: Юнтоловский пр-т 53/3, Санкт-Петербург

Геокодирование:  41%|████      | 8245/19990 [08:56<54:37,  3.58it/s]

[8250] Геокодируем адрес: Товарищеский пр-т 2к1, Санкт-Петербург

Геокодирование:  41%|████▏     | 8251/19990 [08:57<46:44,  4.19it/s]

Автосохранение после 8250 строк...
[8257] Геокодируем адрес: Московский пр-т 167, Санкт-Петербург

Геокодирование:  41%|████▏     | 8258/19990 [08:58<39:30,  4.95it/s]

[8266] Геокодируем адрес: Шушары Новгородский пр-т 10, Санкт-Петербург

Геокодирование:  41%|████▏     | 8267/19990 [08:59<30:32,  6.40it/s]

[8274] Геокодируем адрес: Стрельна Грибоедова ул 7, Санкт-Петербург

Геокодирование:  41%|████▏     | 8281/19990 [09:00<21:32,  9.06it/s]

Автосохранение после 8280 строк...
[8295] Геокодируем адрес: Маршала Блюхера пр-т 40, Санкт-Петербург

Геокодирование:  42%|████▏     | 8296/19990 [09:01<17:26, 11.17it/s]

[8303] Геокодируем адрес: Балтийский б-р, Санкт-Петербург

Геокодирование:  42%|████▏     | 8311/19990 [09:02<14:38, 13.30it/s]

Автосохранение после 8310 строк...
[8312] Геокодируем адрес: Каменноостровский пр-т 64Ф, Санкт-Петербург

Геокодирование:  42%|████▏     | 8314/19990 [09:03<20:24,  9.53it/s]

[8314] Геокодируем адрес: Пинский наб 4, Санкт-Петербург
[8315] Геокодируем адрес: Пинский наб 4, Санкт-Петербург

Геокодирование:  42%|████▏     | 8316/19990 [09:05<39:52,  4.88it/s]

[8317] Геокодируем адрес: Колпино Коммуны ул 3, Санкт-Петербург

Геокодирование:  42%|████▏     | 8318/19990 [09:06<48:04,  4.05it/s]

[8327] Геокодируем адрес: Мечникова пр-т 9, Санкт-Петербург

Геокодирование:  42%|████▏     | 8328/19990 [09:07<34:54,  5.57it/s]

[8329] Геокодируем адрес: Шлиссельбургский пр-т 17к2, Санкт-Петербург

Геокодирование:  42%|████▏     | 8330/19990 [09:08<40:14,  4.83it/s]

[8333] Геокодируем адрес: п.Александровская Соболевская дор 8, Санкт-Петербург

Геокодирование:  42%|████▏     | 8334/19990 [09:09<44:19,  4.38it/s]

[8334] Геокодируем адрес: Балтийский б-р, Санкт-Петербург

Геокодирование:  42%|████▏     | 8335/19990 [09:10<56:04,  3.46it/s]

[8335] Геокодируем адрес: Шушары Новгородский пр-т 4, Санкт-Петербург

Геокодирование:  42%|████▏     | 8341/19990 [09:11<43:09,  4.50it/s]

Автосохранение после 8340 строк...
[8346] Геокодируем адрес: Литейный пр-т 60, Санкт-Петербург

Геокодирование:  42%|████▏     | 8347/19990 [09:12<36:16,  5.35it/s]

[8356] Геокодируем адрес: Невский пр-т 32-34, Санкт-Петербург

Геокодирование:  42%|████▏     | 8357/19990 [09:14<37:44,  5.14it/s]

[8364] Геокодируем адрес: Товарищеский пр-т 32к2, Санкт-Петербург

Геокодирование:  42%|████▏     | 8365/19990 [09:15<33:05,  5.85it/s]

[8365] Геокодируем адрес: Энгельса пр-т 13/2, Санкт-Петербург

Геокодирование:  42%|████▏     | 8366/19990 [09:16<44:41,  4.33it/s]

[8366] Геокодируем адрес: Сиреневый б-р, Санкт-Петербург

Геокодирование:  42%|████▏     | 8371/19990 [09:17<38:45,  5.00it/s]

Автосохранение после 8370 строк...
[8373] Геокодируем адрес: Трамвайный пр-т 27к1, Санкт-Петербург

Геокодирование:  42%|████▏     | 8374/19990 [09:18<42:36,  4.54it/s]

[8374] Геокодируем адрес: Маршала Жукова пр-т 18, Санкт-Петербург

Геокодирование:  42%|████▏     | 8375/19990 [09:19<1:02:21,  3.10it/s]

[8377] Геокодируем адрес: Славы пр-т 7к1, Санкт-Петербург

Геокодирование:  42%|████▏     | 8378/19990 [09:20<59:39,  3.24it/s]

[8378] Геокодируем адрес: Металлострой Пионерская ул 7, Санкт-Петербург

Геокодирование:  42%|████▏     | 8379/19990 [09:21<1:16:01,  2.55it/s]

[8390] Геокодируем адрес: Вилькицкий б-р 7, Санкт-Петербург

Геокодирование:  42%|████▏     | 8391/19990 [09:22<35:10,  5.50it/s]

[8391] Геокодируем адрес: 3-я линия ВО, Санкт-Петербург

Геокодирование:  42%|████▏     | 8392/19990 [09:24<1:06:23,  2.91it/s]

[8395] Геокодируем адрес: Комендантский пр-т 18, Санкт-Петербург

Геокодирование:  42%|████▏     | 8396/19990 [09:25<56:44,  3.41it/s]

[8396] Геокодируем адрес: 20-я линия ВО 19А, Санкт-Петербург

Геокодирование:  42%|████▏     | 8397/19990 [09:26<1:18:14,  2.47it/s]

[8397] Геокодируем адрес: Петергоф Ропшинское ш, Санкт-Петербург

Геокодирование:  42%|████▏     | 8398/19990 [09:27<1:23:42,  2.31it/s]

[8398] Геокодируем адрес: Просвещения пр-т 33к1, Санкт-Петербург

Геокодирование:  42%|████▏     | 8399/19990 [09:28<1:41:58,  1.89it/s]

[8399] Геокодируем адрес: Петергоф Ропшинское ш, Санкт-Петербург

Геокодирование:  42%|████▏     | 8400/19990 [09:29<1:55:51,  1.67it/s]

[8400] Геокодируем адрес: Петергоф Ропшинское ш, Санкт-Петербург

Геокодирование:  42%|████▏     | 8401/19990 [09:30<2:17:49,  1.40it/s]

Автосохранение после 8400 строк...
[8405] Геокодируем адрес: Октябрьский б-р, Санкт-Петербург

Геокодирование:  42%|████▏     | 8406/19990 [09:31<1:18:11,  2.47it/s]

[8417] Геокодируем адрес: Шушары Школьная ул 17, Санкт-Петербург

Геокодирование:  42%|████▏     | 8418/19990 [09:32<35:49,  5.38it/s]

[8418] Геокодируем адрес: Шушары Центральная ул 14к4, Санкт-Петербург

Геокодирование:  42%|████▏     | 8419/19990 [09:33<46:15,  4.17it/s]

[8419] Геокодируем адрес: Шушары Ростовская ул 4к6, Санкт-Петербург

Геокодирование:  42%|████▏     | 8420/19990 [09:34<1:01:25,  3.14it/s]

[8420] Геокодируем адрес: Шушары Школьная ул 17, Санкт-Петербург

Геокодирование:  42%|████▏     | 8421/19990 [09:35<1:17:13,  2.50it/s]

[8421] Геокодируем адрес: Пушкин Октябрьский б-р 22, Санкт-Петербург

Геокодирование:  42%|████▏     | 8422/19990 [09:36<1:39:51,  1.93it/s]

[8423] Геокодируем адрес: Шушары Школьная ул 17, Санкт-Петербург

Геокодирование:  42%|████▏     | 8424/19990 [09:37<1:34:05,  2.05it/s]

[8429] Геокодируем адрес: Витебский пр-т 19к2, Санкт-Петербург

Геокодирование:  42%|████▏     | 8431/19990 [09:38<56:59,  3.38it/s]

Автосохранение после 8430 строк...
[8432] Геокодируем адрес: Маршала Жукова пр-т 30к2Б, Санкт-Петербург

Геокодирование:  42%|████▏     | 8433/19990 [09:39<58:17,  3.30it/s]

[8435] Геокодируем адрес: Маршала Жукова пр-т 30к2Б, Санкт-Петербург

Геокодирование:  42%|████▏     | 8436/19990 [09:40<1:00:05,  3.20it/s]

[8439] Геокодируем адрес: Дачный пр-т 7к2, Санкт-Петербург

Геокодирование:  42%|████▏     | 8440/19990 [09:41<59:08,  3.26it/s]

[8444] Геокодируем адрес: Сиреневый б-р 22/26, Санкт-Петербург

Геокодирование:  42%|████▏     | 8445/19990 [09:42<52:32,  3.66it/s]

[8456] Геокодируем адрес: Шушары Школьная ул 17, Санкт-Петербург

Геокодирование:  42%|████▏     | 8457/19990 [09:43<29:13,  6.58it/s]

[8458] Геокодируем адрес: Шушары Школьная ул 17, Санкт-Петербург

Геокодирование:  42%|████▏     | 8461/19990 [09:45<37:20,  5.15it/s]

Автосохранение после 8460 строк...
[8462] Геокодируем адрес: Дунайский ул 7к3, Санкт-Петербург

Геокодирование:  42%|████▏     | 8463/19990 [09:45<41:55,  4.58it/s]

[8468] Геокодируем адрес: Просвещения пр-т 41, Санкт-Петербург

Геокодирование:  42%|████▏     | 8469/19990 [09:46<38:33,  4.98it/s]

[8470] Геокодируем адрес: Просвещения пр-т 21/139, Санкт-Петербург

Геокодирование:  42%|████▏     | 8471/19990 [09:47<49:50,  3.85it/s]

[8472] Геокодируем адрес: Серебристый б-р, Санкт-Петербург

Геокодирование:  42%|████▏     | 8473/19990 [09:48<56:34,  3.39it/s]

[8477] Геокодируем адрес: Невский пр-т 67, Санкт-Петербург

Геокодирование:  42%|████▏     | 8478/19990 [09:49<50:26,  3.80it/s]

[8482] Геокодируем адрес: Красное Село Стрельнинское ш 4к2, Санкт-Петербург

Геокодирование:  42%|████▏     | 8483/19990 [09:51<48:42,  3.94it/s]

[8483] Геокодируем адрес: Джамбула ул 19, Санкт-Петербург

Геокодирование:  42%|████▏     | 8484/19990 [09:51<56:35,  3.39it/s]

[8487] Геокодируем адрес: Ветеранов пр-т 169к1, Санкт-Петербург

Геокодирование:  42%|████▏     | 8491/19990 [09:52<41:13,  4.65it/s]

Автосохранение после 8490 строк...
[8500] Геокодируем адрес: Шушары Школьная ул 17, Санкт-Петербург

Геокодирование:  43%|████▎     | 8501/19990 [09:53<27:33,  6.95it/s]

[8507] Геокодируем адрес: Обуховской Обороны пр-т 33А, Санкт-Петербург

Геокодирование:  43%|████▎     | 8508/19990 [09:54<28:26,  6.73it/s]

[8512] Геокодируем адрес: Пушкин Школьная ул 23, Санкт-Петербург

Геокодирование:  43%|████▎     | 8513/19990 [09:55<30:26,  6.28it/s]

[8520] Геокодируем адрес: Просвещения пр-т 27к3, Санкт-Петербург

Геокодирование:  43%|████▎     | 8521/19990 [09:56<28:42,  6.66it/s]

Автосохранение после 8520 строк...
[8524] Геокодируем адрес: Шанцевский пер, Санкт-Петербург

Геокодирование:  43%|████▎     | 8525/19990 [09:57<30:17,  6.31it/s]

[8530] Геокодируем адрес: Индустриальный пр-т 7, Санкт-Петербург

Геокодирование:  43%|████▎     | 8531/19990 [09:58<32:57,  5.80it/s]

[8531] Геокодируем адрес: Наставников пр-т 8к1, Санкт-Петербург

Геокодирование:  43%|████▎     | 8532/19990 [09:59<42:33,  4.49it/s]

[8533] Геокодируем адрес: Шушары Вишерская ул 1к1, Санкт-Петербург

Геокодирование:  43%|████▎     | 8534/19990 [10:00<51:05,  3.74it/s]

[8536] Геокодируем адрес: Дачный пр-т 36к5, Санкт-Петербург

Геокодирование:  43%|████▎     | 8551/19990 [10:01<21:07,  9.03it/s]

Автосохранение после 8550 строк...
[8554] Геокодируем адрес: Шушары Витебский пр-т, Санкт-Петербург

Геокодирование:  43%|████▎     | 8555/19990 [10:02<24:49,  7.68it/s]

[8558] Геокодируем адрес: Королёва пр-т 61, Санкт-Петербург

Геокодирование:  43%|████▎     | 8559/19990 [10:03<31:37,  6.02it/s]

[8564] Геокодируем адрес: Кораблестроитестроителей ул 35к1, Санкт-Петербург

Геокодирование:  43%|████▎     | 8565/19990 [10:04<29:15,  6.51it/s]

[8567] Геокодируем адрес: 24-я линия ВО, Санкт-Петербург

Геокодирование:  43%|████▎     | 8568/19990 [10:07<55:56,  3.40it/s]

[8575] Геокодируем адрес: Литейный пр-т 53, Санкт-Петербург

Геокодирование:  43%|████▎     | 8576/19990 [10:08<47:25,  4.01it/s]

[8576] Геокодируем адрес: Луначарского пр-т 54, Санкт-Петербург

Геокодирование:  43%|████▎     | 8581/19990 [10:09<41:26,  4.59it/s]

Автосохранение после 8580 строк...
[8589] Геокодируем адрес: Авиаконструкторов пр-т 3к2, Санкт-Петербург

Геокодирование:  43%|████▎     | 8590/19990 [10:10<28:27,  6.68it/s]

[8590] Геокодируем адрес: Пушкин Школьная ул 15, Санкт-Петербург

Геокодирование:  43%|████▎     | 8592/19990 [10:11<37:34,  5.06it/s]

[8592] Геокодируем адрес: Ленинский пр-т 96к3, Санкт-Петербург

Геокодирование:  43%|████▎     | 8593/19990 [10:12<49:44,  3.82it/s]

[8604] Геокодируем адрес: Шушары Пушкинская ул, Санкт-Петербург

Геокодирование:  43%|████▎     | 8605/19990 [10:13<29:28,  6.44it/s]

[8605] Геокодируем адрес: Светлановский пр-т 48/19, Санкт-Петербург

Геокодирование:  43%|████▎     | 8611/19990 [10:14<30:18,  6.26it/s]

Автосохранение после 8610 строк...
[8612] Геокодируем адрес: Большой Сампсониевский пр-т 62, Санкт-Петербург

Геокодирование:  43%|████▎     | 8613/19990 [10:15<39:07,  4.85it/s]

[8616] Геокодируем адрес: Пушкин Пушкинская ул 8, Санкт-Петербург

Геокодирование:  43%|████▎     | 8617/19990 [10:16<39:38,  4.78it/s]

[8622] Геокодируем адрес: Шушары Школьная ул 15, Санкт-Петербург

Геокодирование:  43%|████▎     | 8623/19990 [10:17<36:10,  5.24it/s]

[8624] Геокодируем адрес: Народного Ополчения пр-т 93, Санкт-Петербург

Геокодирование:  43%|████▎     | 8625/19990 [10:18<47:04,  4.02it/s]

[8625] Геокодируем адрес: Народного Ополчения пр-т 97, Санкт-Петербург

Геокодирование:  43%|████▎     | 8626/19990 [10:19<1:01:30,  3.08it/s]

[8629] Геокодируем адрес: Народного Ополчения пр-т 97, Санкт-Петербург

Геокодирование:  43%|████▎     | 8630/19990 [10:20<57:04,  3.32it/s]

[8640] Геокодируем адрес: Суворовский пр-т 62, Санкт-Петербург

Геокодирование:  43%|████▎     | 8641/19990 [10:21<35:02,  5.40it/s]

Автосохранение после 8640 строк...
[8642] Геокодируем адрес: Суворовский пр-т 62, Санкт-Петербург

Геокодирование:  43%|████▎     | 8643/19990 [10:22<40:03,  4.72it/s]

[8650] Геокодируем адрес: Ярославский пр-т 66к1, Санкт-Петербург

Геокодирование:  43%|████▎     | 8651/19990 [10:23<31:29,  6.00it/s]

[8654] Геокодируем адрес: Ветеранов пр-т 112, Санкт-Петербург

Геокодирование:  43%|████▎     | 8655/19990 [10:24<37:56,  4.98it/s]

[8655] Геокодируем адрес: Гаражный пр-д 1Г3, Санкт-Петербург

Геокодирование:  43%|████▎     | 8656/19990 [10:25<47:54,  3.94it/s]

[8660] Геокодируем адрес: Лиговский пр-т 16, Санкт-Петербург

Геокодирование:  43%|████▎     | 8661/19990 [10:26<44:41,  4.23it/s]

[8662] Геокодируем адрес: Юрия Гагарина пр-т 28к4, Санкт-Петербург

Геокодирование:  43%|████▎     | 8663/19990 [10:27<51:28,  3.67it/s]

[8666] Геокодируем адрес: Шушары Школьная ул 15, Санкт-Петербург

Геокодирование:  43%|████▎     | 8667/19990 [10:28<50:10,  3.76it/s]

[8667] Геокодируем адрес: Наставников пр-т 6, Санкт-Петербург

Геокодирование:  43%|████▎     | 8668/19990 [10:29<1:05:36,  2.88it/s]

[8669] Геокодируем адрес: Новочеркасский пр-т 56к2, Санкт-Петербург

Геокодирование:  43%|████▎     | 8671/19990 [10:30<1:04:22,  2.93it/s]

Автосохранение после 8670 строк...
[8672] Геокодируем адрес: Стачек пр-т 82, Санкт-Петербург

Геокодирование:  43%|████▎     | 8673/19990 [10:31<1:11:33,  2.64it/s]

[8673] Геокодируем адрес: Шушары Школьная ул 15, Санкт-Петербург

Геокодирование:  43%|████▎     | 8674/19990 [10:32<1:29:29,  2.11it/s]

[8674] Геокодируем адрес: Металлострой Садовая ул 8, Санкт-Петербург

Геокодирование:  43%|████▎     | 8675/19990 [10:33<1:48:49,  1.73it/s]

[8675] Геокодируем адрес: Металлострой Богайчука ул 3, Санкт-Петербург

Геокодирование:  43%|████▎     | 8676/19990 [10:34<2:07:10,  1.48it/s]

[8699] Геокодируем адрес: Петергоф Ропшинское ш, Санкт-Петербург

Геокодирование:  44%|████▎     | 8701/19990 [10:35<21:54,  8.59it/s]

Автосохранение после 8700 строк...
[8704] Геокодируем адрес: Маршала Блюхера пр-т, Санкт-Петербург

Геокодирование:  44%|████▎     | 8705/19990 [10:36<26:44,  7.03it/s]

[8712] Геокодируем адрес: Лиговский пр-т 75-77, Санкт-Петербург

Геокодирование:  44%|████▎     | 8713/19990 [10:37<25:54,  7.25it/s]

[8724] Геокодируем адрес: Комендантский пр-т 66к5, Санкт-Петербург

Геокодирование:  44%|████▎     | 8725/19990 [10:38<20:15,  9.27it/s]

[8725] Геокодируем адрес: Новочеркасский пр-т 56к2, Санкт-Петербург

Геокодирование:  44%|████▎     | 8731/19990 [10:39<22:29,  8.35it/s]

Автосохранение после 8730 строк...
[8733] Геокодируем адрес: Ленинский пр-т 117к1, Санкт-Петербург

Геокодирование:  44%|████▎     | 8734/19990 [10:40<28:51,  6.50it/s]

[8736] Геокодируем адрес: Елизарова пр-т 3, Санкт-Петербург

Геокодирование:  44%|████▎     | 8737/19990 [10:41<36:38,  5.12it/s]

[8744] Геокодируем адрес: Петергоф Ропшинское ш, Санкт-Петербург

Геокодирование:  44%|████▎     | 8745/19990 [10:42<29:55,  6.26it/s]

[8751] Геокодируем адрес: Комендантский пр-т 64к1, Санкт-Петербург

Геокодирование:  44%|████▍     | 8752/19990 [10:43<28:45,  6.51it/s]

[8755] Геокодируем адрес: Одоевская ул 31, Санкт-Петербург

Геокодирование:  44%|████▍     | 8756/19990 [10:44<32:51,  5.70it/s]

[8756] Геокодируем адрес: Одоевская ул 31, Санкт-Петербург

Геокодирование:  44%|████▍     | 8757/19990 [10:45<44:18,  4.23it/s]

[8757] Геокодируем адрес: Одоевская ул 31, Санкт-Петербург

Геокодирование:  44%|████▍     | 8761/19990 [10:46<44:07,  4.24it/s]

Автосохранение после 8760 строк...
[8773] Геокодируем адрес: Шушары Окуловская ул, Санкт-Петербург

Геокодирование:  44%|████▍     | 8774/19990 [10:47<23:11,  8.06it/s]

[8775] Геокодируем адрес: Авиаконструкторов пр-т 6А, Санкт-Петербург

Геокодирование:  44%|████▍     | 8776/19990 [10:48<33:04,  5.65it/s]

[8778] Геокодируем адрес: Комендантский пр-т 64к1, Санкт-Петербург

Геокодирование:  44%|████▍     | 8779/19990 [10:49<37:57,  4.92it/s]

[8779] Геокодируем адрес: Комендантский пр-т 64к1, Санкт-Петербург

Геокодирование:  44%|████▍     | 8780/19990 [10:51<1:08:01,  2.75it/s]

[8780] Геокодируем адрес: Комендантский пр-т 64к1, Санкт-Петербург

Геокодирование:  44%|████▍     | 8781/19990 [10:52<1:22:02,  2.28it/s]

[8783] Геокодируем адрес: Просвещения пр-т 19, Санкт-Петербург

Геокодирование:  44%|████▍     | 8784/19990 [10:53<1:18:38,  2.37it/s]

[8787] Геокодируем адрес: Космонавтов пр-т 61к1, Санкт-Петербург

Геокодирование:  44%|████▍     | 8788/19990 [10:54<1:04:03,  2.91it/s]

[8789] Геокодируем адрес: Дунайский пр-т 34/16, Санкт-Петербург

Геокодирование:  44%|████▍     | 8791/19990 [10:55<1:06:35,  2.80it/s]

Автосохранение после 8790 строк...
[8795] Геокодируем адрес: Энгельса пр-т 22, Санкт-Петербург

Геокодирование:  44%|████▍     | 8796/19990 [10:56<50:58,  3.66it/s]

[8806] Геокодируем адрес: Финляндский пр-т 1, Санкт-Петербург

Геокодирование:  44%|████▍     | 8807/19990 [10:57<29:30,  6.32it/s]

[8811] Геокодируем адрес: Художников пр-т 33к1, Санкт-Петербург

Геокодирование:  44%|████▍     | 8812/19990 [10:58<31:03,  6.00it/s]

[8813] Геокодируем адрес: Энгельса пр-т 22, Санкт-Петербург

Геокодирование:  44%|████▍     | 8814/19990 [10:59<41:40,  4.47it/s]

[8820] Геокодируем адрес: Пятилеток пр-т 14к2, Санкт-Петербург

Геокодирование:  44%|████▍     | 8821/19990 [11:00<34:42,  5.36it/s]

Автосохранение после 8820 строк...
[8822] Геокодируем адрес: Невский пр-т 102С, Санкт-Петербург

Геокодирование:  44%|████▍     | 8823/19990 [11:01<42:20,  4.40it/s]

[8825] Геокодируем адрес: Лиговский пр-т 78, Санкт-Петербург

Геокодирование:  44%|████▍     | 8826/19990 [11:02<46:51,  3.97it/s]

[8826] Геокодируем адрес: Непокорённых пр-т 9к1, Санкт-Петербург

Геокодирование:  44%|████▍     | 8827/19990 [11:03<58:46,  3.17it/s]

[8828] Геокодируем адрес: Энгельса пр-т 22, Санкт-Петербург

Геокодирование:  44%|████▍     | 8829/19990 [11:04<1:11:12,  2.61it/s]

[8834] Геокодируем адрес: Энгельса пр-т 129к1, Санкт-Петербург

Геокодирование:  44%|████▍     | 8835/19990 [11:05<48:38,  3.82it/s]

[8839] Геокодируем адрес: Светлановский пр-т 46к2, Санкт-Петербург

Геокодирование:  44%|████▍     | 8840/19990 [11:06<43:56,  4.23it/s]

[8842] Геокодируем адрес: Колпино Трудящихся пр-т, Санкт-Петербург

Геокодирование:  44%|████▍     | 8843/19990 [11:07<49:26,  3.76it/s]

[8843] Геокодируем адрес: Дачный пр-т 36, Санкт-Петербург

Геокодирование:  44%|████▍     | 8844/19990 [11:08<1:05:57,  2.82it/s]

[8847] Геокодируем адрес: Новаторов б-р 96, Санкт-Петербург

Геокодирование:  44%|████▍     | 8848/19990 [11:09<58:10,  3.19it/s]

[8850] Геокодируем адрес: Богатырский пр-т 49к1, Санкт-Петербург

Геокодирование:  44%|████▍     | 8851/19990 [11:10<58:51,  3.15it/s]

Автосохранение после 8850 строк...
[8854] Геокодируем адрес: Новаторов б-р 92к2, Санкт-Петербург

Геокодирование:  44%|████▍     | 8855/19990 [11:11<51:56,  3.57it/s]

[8855] Геокодируем адрес: Солидарности пр-т 5, Санкт-Петербург

Геокодирование:  44%|████▍     | 8856/19990 [11:12<1:11:15,  2.60it/s]

[8856] Геокодируем адрес: Новаторов б-р 88, Санкт-Петербург

Геокодирование:  44%|████▍     | 8857/19990 [11:13<1:25:21,  2.17it/s]

[8859] Геокодируем адрес: Новаторов б-р, Санкт-Петербург

Геокодирование:  44%|████▍     | 8860/19990 [11:14<1:13:54,  2.51it/s]

[8861] Геокодируем адрес: Мира ул 38, Санкт-Петербург

Геокодирование:  44%|████▍     | 8862/19990 [11:15<1:20:53,  2.29it/s]

[8862] Геокодируем адрес: Малый пр-т 54/4, Санкт-Петербург

Геокодирование:  44%|████▍     | 8863/19990 [11:16<1:41:37,  1.82it/s]

[8863] Геокодируем адрес: Новаторов б-р, Санкт-Петербург

Геокодирование:  44%|████▍     | 8864/19990 [11:17<1:48:53,  1.70it/s]

[8864] Геокодируем адрес: Тореза пр-т 38, Санкт-Петербург

Геокодирование:  44%|████▍     | 8865/19990 [11:18<2:08:00,  1.45it/s]

[8868] Геокодируем адрес: Боровая 23/21Л, Санкт-Петербург

Геокодирование:  44%|████▍     | 8869/19990 [11:19<1:21:57,  2.26it/s]

[8869] Геокодируем адрес: Тореза пр-т 38, Санкт-Петербург

Геокодирование:  44%|████▍     | 8870/19990 [11:20<1:40:58,  1.84it/s]

[8878] Геокодируем адрес: Пушкин Новодеревенская ул 3, Санкт-Петербург

Геокодирование:  44%|████▍     | 8881/19990 [11:21<40:27,  4.58it/s]

Автосохранение после 8880 строк...
[8881] Геокодируем адрес: Светлановский пр-т 48/19, Санкт-Петербург

Геокодирование:  44%|████▍     | 8882/19990 [11:22<54:17,  3.41it/s]

[8883] Геокодируем адрес: Энгельса пр-т 36, Санкт-Петербург

Геокодирование:  44%|████▍     | 8884/19990 [11:23<1:06:12,  2.80it/s]

[8888] Геокодируем адрес: Энгельса пр-т 22, Санкт-Петербург

Геокодирование:  44%|████▍     | 8889/19990 [11:24<51:44,  3.58it/s]

[8890] Геокодируем адрес: Елизарова пр-т 25, Санкт-Петербург

Геокодирование:  44%|████▍     | 8891/19990 [11:25<58:57,  3.14it/s]

[8891] Геокодируем адрес: Энгельса пр-т 136к1, Санкт-Петербург

Геокодирование:  44%|████▍     | 8892/19990 [11:26<1:13:14,  2.53it/s]

[8895] Геокодируем адрес: 3-я линия 2-й половины ул, Санкт-Петербург

Геокодирование:  45%|████▍     | 8896/19990 [11:27<1:10:40,  2.62it/s]

[8896] Геокодируем адрес: Шушары Ростовская ул 4к3, Санкт-Петербург

Геокодирование:  45%|████▍     | 8897/19990 [11:28<1:17:51,  2.37it/s]

[8905] Геокодируем адрес: Петергоф Дашкевича ул 6, Санкт-Петербург

Геокодирование:  45%|████▍     | 8906/19990 [11:29<41:42,  4.43it/s]

[8907] Геокодируем адрес: Петергоф Дашкевича ул 6, Санкт-Петербург

Геокодирование:  45%|████▍     | 8911/19990 [11:30<39:11,  4.71it/s]

Автосохранение после 8910 строк...
[8919] Геокодируем адрес: 20-я линия ВО 11Б, Санкт-Петербург

Геокодирование:  45%|████▍     | 8920/19990 [11:33<44:53,  4.11it/s]

[8925] Геокодируем адрес: 20 линия ВО 19а, Санкт-Петербург

Геокодирование:  45%|████▍     | 8926/19990 [11:34<38:49,  4.75it/s]

[8934] Геокодируем адрес: Энгельса пр-т 140, Санкт-Петербург

Геокодирование:  45%|████▍     | 8935/19990 [11:34<30:59,  5.94it/s]

[8936] Геокодируем адрес: Петергоф Ропшинское ш, Санкт-Петербург

Геокодирование:  45%|████▍     | 8941/19990 [11:36<29:17,  6.29it/s]

Автосохранение после 8940 строк...
[8964] Геокодируем адрес: Петергоф Ропшинское ш 10, Санкт-Петербург

Геокодирование:  45%|████▍     | 8965/19990 [11:36<13:35, 13.52it/s]

[8966] Геокодируем адрес: Лесной пр-т 39к3, Санкт-Петербург

Геокодирование:  45%|████▍     | 8967/19990 [11:37<19:06,  9.61it/s]

[8968] Геокодируем адрес: Металлострой Садовая ул 8, Санкт-Петербург

Геокодирование:  45%|████▍     | 8969/19990 [11:38<26:14,  7.00it/s]

[8970] Геокодируем адрес: Сампсоньевский сад, Санкт-Петербург

Геокодирование:  45%|████▍     | 8971/19990 [11:39<34:39,  5.30it/s]

Автосохранение после 8970 строк...
[8974] Геокодируем адрес: Новознаменка сад, Санкт-Петербург

Геокодирование:  45%|████▍     | 8975/19990 [11:40<36:29,  5.03it/s]

[8976] Геокодируем адрес: Металлострой Пушкинская ул 4, Санкт-Петербург

Геокодирование:  45%|████▍     | 8977/19990 [11:41<45:56,  4.00it/s]

[8984] Геокодируем адрес: Санкт-Петербургский пр-т 37, Санкт-Петербург

Геокодирование:  45%|████▍     | 8985/19990 [11:42<35:54,  5.11it/s]

[8991] Геокодируем адрес: Металлострой Садовая ул 8, Санкт-Петербург

Геокодирование:  45%|████▍     | 8992/19990 [11:43<31:22,  5.84it/s]

[8994] Геокодируем адрес: Металлострой Садовая ул 8, Санкт-Петербург

Геокодирование:  45%|████▍     | 8995/19990 [11:44<37:01,  4.95it/s]

[8995] Геокодируем адрес: Богатырский пр-т 10, Санкт-Петербург

Геокодирование:  45%|████▌     | 8996/19990 [11:45<49:35,  3.70it/s]

[8997] Геокодируем адрес: Ветеранов пр-т 175, Санкт-Петербург

Геокодирование:  45%|████▌     | 9001/19990 [11:47<45:03,  4.07it/s]

Автосохранение после 9000 строк...
[9006] Геокодируем адрес: Большой пр-т 101, Санкт-Петербург

Геокодирование:  45%|████▌     | 9007/19990 [11:48<39:15,  4.66it/s]

[9009] Геокодируем адрес: Московский пр-т 149Г, Санкт-Петербург

Геокодирование:  45%|████▌     | 9010/19990 [11:48<41:05,  4.45it/s]

[9026] Геокодируем адрес: Петергоф Ропшинское ш 8Ч, Санкт-Петербург

Геокодирование:  45%|████▌     | 9027/19990 [11:49<20:41,  8.83it/s]

[9028] Геокодируем адрес: Шлиссельбургский пр-т 45, Санкт-Петербург

Геокодирование:  45%|████▌     | 9029/19990 [11:50<28:10,  6.48it/s]

[9029] Геокодируем адрес: Космонавтов пр-т 29к7, Санкт-Петербург

Геокодирование:  45%|████▌     | 9031/19990 [11:51<36:07,  5.05it/s]

Автосохранение после 9030 строк...
[9032] Геокодируем адрес: Большивиков пр-т, Санкт-Петербург

Геокодирование:  45%|████▌     | 9033/19990 [11:52<42:43,  4.27it/s]

[9035] Геокодируем адрес: рки Фонтанки наб, Санкт-Петербург

Геокодирование:  45%|████▌     | 9036/19990 [11:53<49:15,  3.71it/s]

[9038] Геокодируем адрес: Энгельса пр-т 128, Санкт-Петербург

Геокодирование:  45%|████▌     | 9039/19990 [11:55<57:01,  3.20it/s]

[9049] Геокодируем адрес: Торфяная дор, Санкт-Петербург

Геокодирование:  45%|████▌     | 9050/19990 [11:55<29:45,  6.13it/s]

[9051] Геокодируем адрес: Комендантский пр-т 62, Санкт-Петербург

Геокодирование:  45%|████▌     | 9052/19990 [11:57<51:37,  3.53it/s]

[9056] Геокодируем адрес: Стачек пр-т 87, Санкт-Петербург

Геокодирование:  45%|████▌     | 9061/19990 [11:59<36:28,  4.99it/s]

Автосохранение после 9060 строк...
[9061] Геокодируем адрес: Обуховской Обороны пр-т 107Б, Санкт-Петербург
[9062] Геокодируем адрес: Обуховской Обороны пр-т 107Б, Санкт-Петербург

Геокодирование:  45%|████▌     | 9063/19990 [12:00<57:28,  3.17it/s]

[9063] Геокодируем адрес: Обуховской Обороны пр-т 93Р, Санкт-Петербург

Геокодирование:  45%|████▌     | 9064/19990 [12:01<1:09:45,  2.61it/s]

[9066] Геокодируем адрес: Большой Смоленский пр-т 24, Санкт-Петербург

Геокодирование:  45%|████▌     | 9067/19990 [12:03<1:09:35,  2.62it/s]

[9076] Геокодируем адрес: Комендантский пр-т 32к1, Санкт-Петербург

Геокодирование:  45%|████▌     | 9077/19990 [12:03<37:38,  4.83it/s]

[9078] Геокодируем адрес: Шушары Ростовская ул 4к3, Санкт-Петербург

Геокодирование:  45%|████▌     | 9079/19990 [12:04<44:45,  4.06it/s]

[9079] Геокодируем адрес: Шушары Ростовская ул 4к3, Санкт-Петербург

Геокодирование:  45%|████▌     | 9080/19990 [12:05<57:46,  3.15it/s]

[9085] Геокодируем адрес: Петровский пр-т 5стр1, Санкт-Петербург

Геокодирование:  45%|████▌     | 9086/19990 [12:06<44:58,  4.04it/s]

[9088] Геокодируем адрес: Красное Село Спирина ул 18, Санкт-Петербург

Геокодирование:  45%|████▌     | 9091/19990 [12:08<45:07,  4.03it/s]

Автосохранение после 9090 строк...
[9092] Геокодируем адрес: Комендантский пр-т 67, Санкт-Петербург

Геокодирование:  45%|████▌     | 9093/19990 [12:09<51:16,  3.54it/s]

[9097] Геокодируем адрес: Науки пр-т 1, Санкт-Петербург

Геокодирование:  46%|████▌     | 9098/19990 [12:09<44:01,  4.12it/s]

[9099] Геокодируем адрес: 2-я линия ВО, Санкт-Петербург

Геокодирование:  46%|████▌     | 9100/19990 [12:11<58:02,  3.13it/s]

[9106] Геокодируем адрес: Культуры пр-т, Санкт-Петербург

Геокодирование:  46%|████▌     | 9107/19990 [12:11<37:49,  4.79it/s]

[9109] Геокодируем адрес: Энгельса пр-т 22Б, Санкт-Петербург

Геокодирование:  46%|████▌     | 9121/19990 [12:13<21:46,  8.32it/s]

Автосохранение после 9120 строк...
[9132] Геокодируем адрес: Павловск Оборонная ул, Санкт-Петербург

Геокодирование:  46%|████▌     | 9133/19990 [12:13<16:04, 11.25it/s]

[9135] Геокодируем адрес: Славы пр-т 26к1, Санкт-Петербург

Геокодирование:  46%|████▌     | 9136/19990 [12:14<23:08,  7.82it/s]

[9138] Геокодируем адрес: Ветеранов пр-т 171к2, Санкт-Петербург

Геокодирование:  46%|████▌     | 9139/19990 [12:15<28:40,  6.31it/s]

[9141] Геокодируем адрес: Тихорецкий пр-т 27Б, Санкт-Петербург

Геокодирование:  46%|████▌     | 9142/19990 [12:16<35:38,  5.07it/s]

[9142] Геокодируем адрес: Кронштадт Гражданская ул 7/11, Санкт-Петербург

Геокодирование:  46%|████▌     | 9143/19990 [12:18<48:57,  3.69it/s]

[9144] Геокодируем адрес: Петергоф Эрлеровский б-р 24, Санкт-Петербург

Геокодирование:  46%|████▌     | 9145/19990 [12:19<57:11,  3.16it/s]

[9149] Геокодируем адрес: Маршала Жукова пр-т 30к2Е, Санкт-Петербург

Геокодирование:  46%|████▌     | 9150/19990 [12:19<45:12,  4.00it/s]

[9150] Геокодируем адрес: Парголово Архитектора Белова ул, Санкт-Петербург

Геокодирование:  46%|████▌     | 9151/19990 [12:21<1:03:39,  2.84it/s]

Автосохранение после 9150 строк...
[9151] Геокодируем адрес: Ленина пр-т, Санкт-Петербург

Геокодирование:  46%|████▌     | 9152/19990 [12:21<1:16:13,  2.37it/s]

[9152] Геокодируем адрес: Петергоф Демьяна Бедного ул, Санкт-Петербург

Геокодирование:  46%|████▌     | 9153/19990 [12:22<1:31:17,  1.98it/s]

[9156] Геокодируем адрес: Художников пр-т 18к1, Санкт-Петербург

Геокодирование:  46%|████▌     | 9157/19990 [12:23<1:09:37,  2.59it/s]

[9160] Геокодируем адрес: Энергетиков пр-т 60/1, Санкт-Петербург

Геокодирование:  46%|████▌     | 9161/19990 [12:25<1:04:24,  2.80it/s]

[9162] Геокодируем адрес: Стачек пр-т 75, Санкт-Петербург

Геокодирование:  46%|████▌     | 9163/19990 [12:26<1:08:01,  2.65it/s]

[9165] Геокодируем адрес: Средний пр-т 99/18В, Санкт-Петербург

Геокодирование:  46%|████▌     | 9181/19990 [12:27<21:08,  8.52it/s]

Автосохранение после 9180 строк...
[9185] Геокодируем адрес: Антонова-Овсеенкой ул, Санкт-Петербург

Геокодирование:  46%|████▌     | 9186/19990 [12:27<21:15,  8.47it/s]

[9189] Геокодируем адрес: Культуры пр-т, Санкт-Петербург

Геокодирование:  46%|████▌     | 9190/19990 [12:28<28:05,  6.41it/s]

[9193] Геокодируем адрес: Художников пр-т 18к1, Санкт-Петербург

Геокодирование:  46%|████▌     | 9194/19990 [12:29<31:18,  5.75it/s]

[9196] Геокодируем адрес: Богатрырский пр-т 53к3, Санкт-Петербург

Геокодирование:  46%|████▌     | 9197/19990 [12:30<36:16,  4.96it/s]

[9198] Геокодируем адрес: Юнтоловский пр-т 49к1, Санкт-Петербург

Геокодирование:  46%|████▌     | 9199/19990 [12:31<45:51,  3.92it/s]

[9199] Геокодируем адрес: 15-я линия ВО 66, Санкт-Петербург

Геокодирование:  46%|████▌     | 9211/19990 [12:34<35:37,  5.04it/s]

Автосохранение после 9210 строк...
[9211] Геокодируем адрес: Энгельса пр-т 151к2, Санкт-Петербург

Геокодирование:  46%|████▌     | 9214/19990 [12:35<36:18,  4.95it/s]

[9215] Геокодируем адрес: Большеохтинский пр-т 22к1, Санкт-Петербург

Геокодирование:  46%|████▌     | 9216/19990 [12:36<44:01,  4.08it/s]

[9216] Геокодируем адрес: Большеохтинский пр-т 22к1, Санкт-Петербург

Геокодирование:  46%|████▌     | 9218/19990 [12:37<52:58,  3.39it/s]

[9219] Геокодируем адрес: Парголово Архитектора Белова ул, Санкт-Петербург

Геокодирование:  46%|████▌     | 9220/19990 [12:38<59:49,  3.00it/s]

[9221] Геокодируем адрес: Богатырский пр-т 53к3, Санкт-Петербург

Геокодирование:  46%|████▌     | 9222/19990 [12:39<1:07:02,  2.68it/s]

[9224] Геокодируем адрес: Шушары Первомайская ул 8, Санкт-Петербург

Геокодирование:  46%|████▌     | 9225/19990 [12:40<1:06:29,  2.70it/s]

[9225] Геокодируем адрес: Светлановский пр-т 97, Санкт-Петербург

Геокодирование:  46%|████▌     | 9226/19990 [12:41<1:23:35,  2.15it/s]

[9227] Геокодируем адрес: Художников пр-т 18к1, Санкт-Петербург

Геокодирование:  46%|████▌     | 9228/19990 [12:42<1:20:58,  2.21it/s]

[9230] Геокодируем адрес: Советский пр-т 39, Санкт-Петербург

Геокодирование:  46%|████▌     | 9231/19990 [12:43<1:16:47,  2.33it/s]

[9232] Геокодируем адрес: Московский пр-т 175, Санкт-Петербург

Геокодирование:  46%|████▌     | 9233/19990 [12:44<1:23:04,  2.16it/s]

[9234] Геокодируем адрес: Шушары Первомайская ул 8, Санкт-Петербург

Геокодирование:  46%|████▌     | 9235/19990 [12:45<1:18:59,  2.27it/s]

[9236] Геокодируем адрес: Стачек пр-т 101к1, Санкт-Петербург

Геокодирование:  46%|████▌     | 9241/19990 [12:46<47:49,  3.75it/s]

Автосохранение после 9240 строк...
[9245] Геокодируем адрес: Юрия Гагарина пр-т 22к2, Санкт-Петербург

Геокодирование:  46%|████▋     | 9246/19990 [12:47<40:43,  4.40it/s]

[9246] Геокодируем адрес: Юрия Гагарина пр-т 22к2, Санкт-Петербург

Геокодирование:  46%|████▋     | 9247/19990 [12:48<56:16,  3.18it/s]

[9263] Геокодируем адрес: Комендантский пр-т 55к1, Санкт-Петербург

Геокодирование:  46%|████▋     | 9264/19990 [12:49<22:19,  8.01it/s]

[9264] Геокодируем адрес: Туристскя ул, Санкт-Петербург

Геокодирование:  46%|████▋     | 9271/19990 [12:50<22:41,  7.88it/s]

Автосохранение после 9270 строк...
[9282] Геокодируем адрес: 24-я линия ВО, Санкт-Петербург

Геокодирование:  46%|████▋     | 9283/19990 [12:51<21:15,  8.39it/s]

[9287] Геокодируем адрес: Песочный Октябрьская ул, Санкт-Петербург

Геокодирование:  46%|████▋     | 9288/19990 [12:52<21:29,  8.30it/s]

[9290] Геокодируем адрес: Петергоф Демьяна Бедного ул, Санкт-Петербург

Геокодирование:  46%|████▋     | 9291/19990 [12:53<27:34,  6.47it/s]

[9291] Геокодируем адрес: Петергоф Аврова ул, Санкт-Петербург

Геокодирование:  46%|████▋     | 9292/19990 [12:54<38:07,  4.68it/s]

[9292] Геокодируем адрес: Петергоф Аврова ул, Санкт-Петербург

Геокодирование:  47%|████▋     | 9301/19990 [12:55<26:47,  6.65it/s]

Автосохранение после 9300 строк...
[9304] Геокодируем адрес: Пархоменко пр-т 19, Санкт-Петербург

Геокодирование:  47%|████▋     | 9305/19990 [12:56<31:37,  5.63it/s]

[9308] Геокодируем адрес: Стачек пр-т 24, Санкт-Петербург

Геокодирование:  47%|████▋     | 9309/19990 [12:57<34:15,  5.20it/s]

[9316] Геокодируем адрес: Петергоф Ропшинское ш, Санкт-Петербург

Геокодирование:  47%|████▋     | 9331/19990 [12:58<14:28, 12.28it/s]

Автосохранение после 9330 строк...
[9337] Геокодируем адрес: Челиева ул, Санкт-Петербург

Геокодирование:  47%|████▋     | 9338/19990 [12:59<15:57, 11.13it/s]

[9349] Геокодируем адрес: Петергоф Ропшинское ш 10, Санкт-Петербург

Геокодирование:  47%|████▋     | 9350/19990 [13:00<16:08, 10.98it/s]

[9350] Геокодируем адрес: Энергетиков пр-т 66к1, Санкт-Петербург
[9352] Геокодируем адрес: Петергоф Ропшинское ш 10, Санкт-Петербург

Геокодирование:  47%|████▋     | 9353/19990 [13:02<28:42,  6.18it/s]

[9353] Геокодируем адрес: Пархоменко ул 8литАН, Санкт-Петербург

Геокодирование:  47%|████▋     | 9361/19990 [13:03<24:47,  7.15it/s]

Автосохранение после 9360 строк...
[9367] Геокодируем адрес: Художников пр-т 10к1, Санкт-Петербург

Геокодирование:  47%|████▋     | 9368/19990 [13:04<24:48,  7.14it/s]

[9370] Геокодируем адрес: Обуховской Обороны пр-т 39, Санкт-Петербург

Геокодирование:  47%|████▋     | 9371/19990 [13:05<31:20,  5.65it/s]

[9378] Геокодируем адрес: Санкт-Петербургский пр-т 8/9, Санкт-Петербург

Геокодирование:  47%|████▋     | 9379/19990 [13:06<28:17,  6.25it/s]

[9385] Геокодируем адрес: Большевиков пр-т 7к1, Санкт-Петербург

Геокодирование:  47%|████▋     | 9386/19990 [13:07<25:49,  6.84it/s]

[9387] Геокодируем адрес: Солидарности пр-т 1к4, Санкт-Петербург

Геокодирование:  47%|████▋     | 9388/19990 [13:08<33:44,  5.24it/s]

[9390] Геокодируем адрес: Парголово Меркурьева ул, Санкт-Петербург

Геокодирование:  47%|████▋     | 9391/19990 [13:09<39:51,  4.43it/s]

Автосохранение после 9390 строк...
[9392] Геокодируем адрес: Каменноостровский пр-т 64С, Санкт-Петербург

Геокодирование:  47%|████▋     | 9393/19990 [13:10<46:11,  3.82it/s]

[9398] Геокодируем адрес: Московский пр-т 115, Санкт-Петербург

Геокодирование:  47%|████▋     | 9399/19990 [13:11<42:42,  4.13it/s]

[9399] Геокодируем адрес: Лермонтовский пр-т 8, Санкт-Петербург

Геокодирование:  47%|████▋     | 9400/19990 [13:12<52:32,  3.36it/s]

[9404] Геокодируем адрес: Петергоф Ропшинское ш 10, Санкт-Петербург

Геокодирование:  47%|████▋     | 9405/19990 [13:13<43:37,  4.04it/s]

[9406] Геокодируем адрес: Петергоф Ропшинское ш 10, Санкт-Петербург

Геокодирование:  47%|████▋     | 9407/19990 [13:14<52:52,  3.34it/s]

[9407] Геокодируем адрес: Петергоф Бобыльская дор 63, Санкт-Петербург

Геокодирование:  47%|████▋     | 9408/19990 [13:15<1:06:14,  2.66it/s]

[9408] Геокодируем адрес: Большевиков пр-т 9к3, Санкт-Петербург

Геокодирование:  47%|████▋     | 9409/19990 [13:16<1:20:20,  2.19it/s]

[9412] Геокодируем адрес: Зеленогорск Лиственная ул, Санкт-Петербург

Геокодирование:  47%|████▋     | 9413/19990 [13:17<1:03:36,  2.77it/s]

[9416] Геокодируем адрес: Петергоф Зверинская ул 6В, Санкт-Петербург

Геокодирование:  47%|████▋     | 9417/19990 [13:18<56:37,  3.11it/s]

[9417] Геокодируем адрес: Петергоф Аврова ул 11, Санкт-Петербург

Геокодирование:  47%|████▋     | 9418/19990 [13:19<1:12:01,  2.45it/s]

[9418] Геокодируем адрес: Петергоф Аврова ул 11, Санкт-Петербург

Геокодирование:  47%|████▋     | 9419/19990 [13:20<1:26:05,  2.05it/s]

[9419] Геокодируем адрес: Петергоф Аврова ул 14А, Санкт-Петербург

Геокодирование:  47%|████▋     | 9421/19990 [13:21<1:29:26,  1.97it/s]

Автосохранение после 9420 строк...
[9421] Геокодируем адрес: Малоохтинский пр-т 88, Санкт-Петербург

Геокодирование:  47%|████▋     | 9422/19990 [13:22<1:41:36,  1.73it/s]

[9422] Геокодируем адрес: Пархоменко пр-т 26, Санкт-Петербург

Геокодирование:  47%|████▋     | 9423/19990 [13:25<3:25:50,  1.17s/it]

[9423] Геокодируем адрес: Петергоф Ропшинское ш 10, Санкт-Петербург

Геокодирование:  47%|████▋     | 9424/19990 [13:26<3:16:28,  1.12s/it]

[9424] Геокодируем адрес: Петергоф Ропшинское ш 10, Санкт-Петербург

Геокодирование:  47%|████▋     | 9425/19990 [13:27<3:10:49,  1.08s/it]

[9425] Геокодируем адрес: Петергоф Ропшинское ш 10, Санкт-Петербург

Геокодирование:  47%|████▋     | 9426/19990 [13:28<3:05:35,  1.05s/it]

[9426] Геокодируем адрес: Петергоф Ропшинское ш 10, Санкт-Петербург

Геокодирование:  47%|████▋     | 9427/19990 [13:29<3:05:54,  1.06s/it]

[9427] Геокодируем адрес: Петергоф Ропшинское ш 10, Санкт-Петербург

Геокодирование:  47%|████▋     | 9428/19990 [13:30<3:01:46,  1.03s/it]

[9428] Геокодируем адрес: Петергоф Ропшинское ш 10, Санкт-Петербург

Геокодирование:  47%|████▋     | 9429/19990 [13:31<2:59:33,  1.02s/it]

[9429] Геокодируем адрес: Петергоф Ропшинское ш 10, Санкт-Петербург

Геокодирование:  47%|████▋     | 9430/19990 [13:32<2:58:10,  1.01s/it]

[9430] Геокодируем адрес: Петергоф Ропшинское ш 10, Санкт-Петербург

Геокодирование:  47%|████▋     | 9431/19990 [13:33<2:55:25,  1.00it/s]

[9431] Геокодируем адрес: Петергоф Ропшинское ш 10, Санкт-Петербург

Геокодирование:  47%|████▋     | 9432/19990 [13:34<2:57:47,  1.01s/it]

[9432] Геокодируем адрес: Петергоф Ропшинское ш 10, Санкт-Петербург

Геокодирование:  47%|████▋     | 9433/19990 [13:35<2:57:20,  1.01s/it]

[9433] Геокодируем адрес: Петергоф Ропшинское ш 10, Санкт-Петербург

Геокодирование:  47%|████▋     | 9434/19990 [13:36<2:55:50,  1.00it/s]

[9434] Геокодируем адрес: Петергоф Ропшинское ш 4, Санкт-Петербург

Геокодирование:  47%|████▋     | 9435/19990 [13:37<2:58:39,  1.02s/it]

[9435] Геокодируем адрес: Петергоф Ропшинское ш 4, Санкт-Петербург

Геокодирование:  47%|████▋     | 9436/19990 [13:38<2:54:25,  1.01it/s]

[9437] Геокодируем адрес: Петергоф Ропшинское ш 10, Санкт-Петербург

Геокодирование:  47%|████▋     | 9438/19990 [13:39<2:14:32,  1.31it/s]

[9438] Геокодируем адрес: Петергоф Ропшинское ш 4, Санкт-Петербург

Геокодирование:  47%|████▋     | 9439/19990 [13:40<2:25:41,  1.21it/s]

[9439] Геокодируем адрес: Кораблестроителей пр-т 36к1, Санкт-Петербург

Геокодирование:  47%|████▋     | 9440/19990 [13:41<2:36:34,  1.12it/s]

[9441] Геокодируем адрес: Королева пр-т 21к1, Санкт-Петербург

Геокодирование:  47%|████▋     | 9442/19990 [13:42<2:06:25,  1.39it/s]

[9442] Геокодируем адрес: Комендантский пр-т 64к1, Санкт-Петербург

Геокодирование:  47%|████▋     | 9451/19990 [13:43<38:32,  4.56it/s]

Автосохранение после 9450 строк...
[9454] Геокодируем адрес: Культуры пр-т 24к1, Санкт-Петербург

Геокодирование:  47%|████▋     | 9455/19990 [13:44<39:37,  4.43it/s]

[9456] Геокодируем адрес: Трудящихся б-р 35к2, Санкт-Петербург

Геокодирование:  47%|████▋     | 9457/19990 [13:45<47:34,  3.69it/s]

[9459] Геокодируем адрес: Петергоф Аврова ул, Санкт-Петербург

Геокодирование:  47%|████▋     | 9460/19990 [13:46<50:20,  3.49it/s]

[9460] Геокодируем адрес: Пятилеток пр-т 15к8, Санкт-Петербург

Геокодирование:  47%|████▋     | 9461/19990 [13:47<1:06:07,  2.65it/s]

[9463] Геокодируем адрес: Лермонтовский пр-т 8/10, Санкт-Петербург

Геокодирование:  47%|████▋     | 9464/19990 [13:48<1:06:25,  2.64it/s]

[9476] Геокодируем адрес: Лиговский пр-т 271, Санкт-Петербург

Геокодирование:  47%|████▋     | 9481/19990 [13:49<24:56,  7.02it/s]

Автосохранение после 9480 строк...
[9482] Геокодируем адрес: Петергоф Ораниенбаумское ш, Санкт-Петербург

Геокодирование:  47%|████▋     | 9483/19990 [13:50<30:08,  5.81it/s]

[9487] Геокодируем адрес: Кронштадт Ленина пр-т 13, Санкт-Петербург

Геокодирование:  47%|████▋     | 9488/19990 [13:51<33:03,  5.30it/s]

[9494] Геокодируем адрес: Кондратьевский пр-т 68к4, Санкт-Петербург

Геокодирование:  47%|████▋     | 9495/19990 [13:52<28:35,  6.12it/s]

[9499] Геокодируем адрес: Просвещения пр-т 31, Санкт-Петербург

Геокодирование:  48%|████▊     | 9500/19990 [13:53<31:47,  5.50it/s]

[9500] Геокодируем адрес: Просвещения пр-т 33к1, Санкт-Петербург

Геокодирование:  48%|████▊     | 9511/19990 [13:54<21:39,  8.06it/s]

Автосохранение после 9510 строк...
[9515] Геокодируем адрес: Энгельса пр-т 111к1, Санкт-Петербург

Геокодирование:  48%|████▊     | 9516/19990 [13:55<23:40,  7.37it/s]

[9531] Геокодируем адрес: Поэтический б-р, Санкт-Петербург

Геокодирование:  48%|████▊     | 9532/19990 [13:56<16:10, 10.78it/s]

[9535] Геокодируем адрес: Медиков пр-т 8к1, Санкт-Петербург

Геокодирование:  48%|████▊     | 9536/19990 [13:57<20:37,  8.45it/s]

[9536] Геокодируем адрес: Медиков пр-т 8к1, Санкт-Петербург
[9537] Геокодируем адрес: Медиков пр-т 8к1, Санкт-Петербург

Геокодирование:  48%|████▊     | 9538/19990 [13:59<37:04,  4.70it/s]

[9538] Геокодируем адрес: Космонавтов пр-т 29к2, Санкт-Петербург

Геокодирование:  48%|████▊     | 9541/19990 [14:00<43:08,  4.04it/s]

Автосохранение после 9540 строк...
[9546] Геокодируем адрес: Октябрьская наб 118к1Б, Санкт-Петербург

Геокодирование:  48%|████▊     | 9547/19990 [14:01<32:45,  5.31it/s]

[9566] Геокодируем адрес: Красное Село Пушкинское ш, Санкт-Петербург

Геокодирование:  48%|████▊     | 9571/19990 [14:02<16:20, 10.62it/s]

Автосохранение после 9570 строк...
[9581] Геокодируем адрес: Шушары Окуловская ул, Санкт-Петербург

Геокодирование:  48%|████▊     | 9582/19990 [14:03<13:46, 12.59it/s]

[9582] Геокодируем адрес: Петергоф Александрийское ш, Санкт-Петербург

Геокодирование:  48%|████▊     | 9584/19990 [14:04<20:45,  8.36it/s]

[9584] Геокодируем адрес: Петергоф Александрийское ш, Санкт-Петербург

Геокодирование:  48%|████▊     | 9586/19990 [14:05<28:41,  6.04it/s]

[9589] Геокодируем адрес: Российский пр-т 14, Санкт-Петербург

Геокодирование:  48%|████▊     | 9590/19990 [14:06<33:09,  5.23it/s]

[9591] Геокодируем адрес: Комендантский пр-т 64к1, Санкт-Петербург

Геокодирование:  48%|████▊     | 9592/19990 [14:07<39:25,  4.40it/s]

[9592] Геокодируем адрес: Шлиссельбургский пр-т 17к2, Санкт-Петербург

Геокодирование:  48%|████▊     | 9601/19990 [14:08<26:39,  6.50it/s]

Автосохранение после 9600 строк...
[9604] Геокодируем адрес: Героев пр-т 33, Санкт-Петербург

Геокодирование:  48%|████▊     | 9605/19990 [14:09<31:25,  5.51it/s]

[9607] Геокодируем адрес: Ленинский пр-т 43, Санкт-Петербург

Геокодирование:  48%|████▊     | 9608/19990 [14:10<37:36,  4.60it/s]

[9608] Геокодируем адрес: Зеленогорск Кавалерийская ул, Санкт-Петербург

Геокодирование:  48%|████▊     | 9610/19990 [14:11<43:00,  4.02it/s]

[9610] Геокодируем адрес: Петергоф Юты Бондаровской ул, Санкт-Петербург

Геокодирование:  48%|████▊     | 9631/19990 [14:12<14:57, 11.54it/s]

Автосохранение после 9630 строк...
[9639] Геокодируем адрес: Петергоф Аврова ул, Санкт-Петербург

Геокодирование:  48%|████▊     | 9640/19990 [14:13<15:06, 11.41it/s]

[9650] Геокодируем адрес: Ленинский пр-т 66, Санкт-Петербург

Геокодирование:  48%|████▊     | 9651/19990 [14:14<16:28, 10.46it/s]

[9651] Геокодируем адрес: Петергоф Аврова ул 14Б, Санкт-Петербург

Геокодирование:  48%|████▊     | 9661/19990 [14:15<15:36, 11.03it/s]

Автосохранение после 9660 строк...
[9668] Геокодируем адрес: Невский пр-т 23, Санкт-Петербург

Геокодирование:  48%|████▊     | 9669/19990 [14:16<16:50, 10.22it/s]

[9669] Геокодируем адрес: Космонавтов пр-т 29к1Т, Санкт-Петербург
[9670] Геокодируем адрес: Юрия Гагарина пр-т 14к6, Санкт-Петербург

Геокодирование:  48%|████▊     | 9672/19990 [14:18<30:35,  5.62it/s]

[9673] Геокодируем адрес: Петергоф Зверинская ул, Санкт-Петербург

Геокодирование:  48%|████▊     | 9674/19990 [14:19<36:45,  4.68it/s]

[9678] Геокодируем адрес: Дудергофского канала пр-д 4к1, Санкт-Петербург

Геокодирование:  48%|████▊     | 9679/19990 [14:20<36:37,  4.69it/s]

[9681] Геокодируем адрес: Славы пр-т 2к2, Санкт-Петербург

Геокодирование:  48%|████▊     | 9682/19990 [14:21<41:38,  4.13it/s]

[9686] Геокодируем адрес: Графский пер 10/11Ж, Санкт-Петербург

Геокодирование:  48%|████▊     | 9687/19990 [14:22<39:35,  4.34it/s]

[9688] Геокодируем адрес: Просвещения пр-т 32к1, Санкт-Петербург

Геокодирование:  48%|████▊     | 9689/19990 [14:23<46:15,  3.71it/s]

[9690] Геокодируем адрес: Просвещения пр-т 32, Санкт-Петербург

Геокодирование:  48%|████▊     | 9691/19990 [14:24<56:32,  3.04it/s]

Автосохранение после 9690 строк...
[9694] Геокодируем адрес: Сестрорецк Советский пр-т, Санкт-Петербург

Геокодирование:  48%|████▊     | 9695/19990 [14:25<48:26,  3.54it/s]

[9701] Геокодируем адрес: Ветеранов пр-т 171к4, Санкт-Петербург

Геокодирование:  49%|████▊     | 9702/19990 [14:26<37:05,  4.62it/s]

[9705] Геокодируем адрес: Просвещения пр-т 87к1, Санкт-Петербург

Геокодирование:  49%|████▊     | 9706/19990 [14:27<38:43,  4.43it/s]

[9712] Геокодируем адрес: Энгельса пр-т 133к1Ж, Санкт-Петербург

Геокодирование:  49%|████▊     | 9713/19990 [14:28<31:59,  5.36it/s]

[9714] Геокодируем адрес: Обуховской Обороны пр-т 124, Санкт-Петербург

Геокодирование:  49%|████▊     | 9715/19990 [14:29<41:49,  4.09it/s]

[9720] Геокодируем адрес: Большевиков пр-т 17, Санкт-Петербург

Геокодирование:  49%|████▊     | 9721/19990 [14:30<38:28,  4.45it/s]

Автосохранение после 9720 строк...
[9721] Геокодируем адрес: Большевиков пр-т 17, Санкт-Петербург

Геокодирование:  49%|████▊     | 9722/19990 [14:31<47:26,  3.61it/s]

[9722] Геокодируем адрес: Королёва пр-т 71к2, Санкт-Петербург

Геокодирование:  49%|████▊     | 9723/19990 [14:32<58:22,  2.93it/s]

[9735] Геокодируем адрес: Колпино Заводской пр-т 58, Санкт-Петербург

Геокодирование:  49%|████▊     | 9736/19990 [14:33<29:08,  5.87it/s]

[9736] Геокодируем адрес: Кондратьевский пр-т 62к6, Санкт-Петербург

Геокодирование:  49%|████▊     | 9737/19990 [14:34<37:27,  4.56it/s]

[9739] Геокодируем адрес: Лиговский пр-т 78, Санкт-Петербург

Геокодирование:  49%|████▊     | 9740/19990 [14:35<42:57,  3.98it/s]

[9747] Геокодируем адрес: Загородный пр-т 17, Санкт-Петербург

Геокодирование:  49%|████▉     | 9748/19990 [14:36<33:35,  5.08it/s]

[9748] Геокодируем адрес: Загородный пр-т 21-23, Санкт-Петербург

Геокодирование:  49%|████▉     | 9749/19990 [14:37<45:20,  3.76it/s]

[9749] Геокодируем адрес: Загородный пр-т 17, Санкт-Петербург

Геокодирование:  49%|████▉     | 9751/19990 [14:38<52:54,  3.22it/s]

Автосохранение после 9750 строк...
[9751] Геокодируем адрес: Парголово Брюлловская ул, Санкт-Петербург

Геокодирование:  49%|████▉     | 9752/19990 [14:39<1:01:41,  2.77it/s]

[9755] Геокодируем адрес: Шушары Старорусский пр-т 6, Санкт-Петербург

Геокодирование:  49%|████▉     | 9756/19990 [14:40<56:20,  3.03it/s]

[9774] Геокодируем адрес: Шушары Школьная ул 15, Санкт-Петербург

Геокодирование:  49%|████▉     | 9775/19990 [14:41<19:45,  8.62it/s]

[9780] Геокодируем адрес: Ветеранов пр-т 144, Санкт-Петербург

Геокодирование:  49%|████▉     | 9781/19990 [14:42<24:19,  6.99it/s]

Автосохранение после 9780 строк...
[9788] Геокодируем адрес: 9 линия ВО 2к2а, Санкт-Петербург

Геокодирование:  49%|████▉     | 9789/19990 [14:43<20:43,  8.20it/s]

[9802] Геокодируем адрес: культуры пр-т 7к1, Санкт-Петербург

Геокодирование:  49%|████▉     | 9803/19990 [14:44<17:07,  9.91it/s]

[9805] Геокодируем адрес: Ораниенбаумский пр-т 39к1, Санкт-Петербург

Геокодирование:  49%|████▉     | 9806/19990 [14:45<21:35,  7.86it/s]

[9806] Геокодируем адрес: Петергоф Бобыльская ул, Санкт-Петербург

Геокодирование:  49%|████▉     | 9811/19990 [14:46<24:04,  7.05it/s]

Автосохранение после 9810 строк...
[9815] Геокодируем адрес: Ломоносов Победы ул 36к2, Санкт-Петербург

Геокодирование:  49%|████▉     | 9816/19990 [14:47<25:27,  6.66it/s]

[9817] Геокодируем адрес: Ломоносов Полигонный пер, Санкт-Петербург

Геокодирование:  49%|████▉     | 9818/19990 [14:48<34:08,  4.97it/s]

[9819] Геокодируем адрес: Ломоносов Полигонный пер, Санкт-Петербург

Геокодирование:  49%|████▉     | 9820/19990 [14:49<42:35,  3.98it/s]

[9840] Геокодируем адрес: Дунайский пр-т 55к1, Санкт-Петербург

Геокодирование:  49%|████▉     | 9841/19990 [14:50<18:35,  9.10it/s]

Автосохранение после 9840 строк...
[9848] Геокодируем адрес: 24-я линия ВО, Санкт-Петербург

Геокодирование:  49%|████▉     | 9849/19990 [14:51<21:32,  7.85it/s]

[9852] Геокодируем адрес: Парголово Парнасная ул 5к2, Санкт-Петербург

Геокодирование:  49%|████▉     | 9853/19990 [14:52<22:32,  7.50it/s]

[9855] Геокодируем адрес: Культуры пр-т 22, Санкт-Петербург

Геокодирование:  49%|████▉     | 9856/19990 [14:53<29:03,  5.81it/s]

[9858] Геокодируем адрес: Комендантский пр-т 61, Санкт-Петербург

Геокодирование:  49%|████▉     | 9859/19990 [14:54<33:12,  5.08it/s]

[9861] Геокодируем адрес: Маршала Блюхер пр-т 7к2, Санкт-Петербург

Геокодирование:  49%|████▉     | 9862/19990 [14:55<38:56,  4.33it/s]

[9870] Геокодируем адрес: Крестовский пр-т 18, Санкт-Петербург

Геокодирование:  49%|████▉     | 9871/19990 [14:56<30:02,  5.61it/s]

Автосохранение после 9870 строк...
[9872] Геокодируем адрес: пискаревский пр-т 159к6, Санкт-Петербург

Геокодирование:  49%|████▉     | 9873/19990 [14:57<34:00,  4.96it/s]

[9896] Геокодируем адрес: Белоостров Приморское ш, Санкт-Петербург

Геокодирование:  50%|████▉     | 9901/19990 [14:58<14:22, 11.70it/s]

Автосохранение после 9900 строк...
[9903] Геокодируем адрес: Бобыльская дор 61, Санкт-Петербург

Геокодирование:  50%|████▉     | 9904/19990 [14:59<18:24,  9.13it/s]

[9904] Геокодируем адрес: Петергоф Бобыльская дор 61, Санкт-Петербург

Геокодирование:  50%|████▉     | 9906/19990 [15:00<26:17,  6.39it/s]

[9910] Геокодируем адрес: Кузнечный наб 22, Санкт-Петербург

Геокодирование:  50%|████▉     | 9911/19990 [15:01<27:45,  6.05it/s]

[9920] Геокодируем адрес: Поэтический б-р 20, Санкт-Петербург

Геокодирование:  50%|████▉     | 9931/19990 [15:02<15:23, 10.89it/s]

Автосохранение после 9930 строк...
[9932] Геокодируем адрес: Большой Сампсониевский пр-т, Санкт-Петербург
[9933] Геокодируем адрес: Большой Сампсониевский пр-т 108, Санкт-Петербург

Геокодирование:  50%|████▉     | 9934/19990 [15:04<30:09,  5.56it/s]

[9935] Геокодируем адрес: Пискаревский пр-т 159/6, Санкт-Петербург

Геокодирование:  50%|████▉     | 9936/19990 [15:05<34:11,  4.90it/s]

[9940] Геокодируем адрес: Косыгина пр-т 22, Санкт-Петербург

Геокодирование:  50%|████▉     | 9941/19990 [15:06<33:48,  4.95it/s]

[9942] Геокодируем адрес: Королёва пр-т 19, Санкт-Петербург

Геокодирование:  50%|████▉     | 9943/19990 [15:07<42:18,  3.96it/s]

[9943] Геокодируем адрес: Комендантский пр-т 61, Санкт-Петербург

Геокодирование:  50%|████▉     | 9944/19990 [15:08<52:41,  3.18it/s]

[9952] Геокодируем адрес: Ленинский пр-т 148к2, Санкт-Петербург

Геокодирование:  50%|████▉     | 9953/19990 [15:09<32:54,  5.08it/s]

[9953] Геокодируем адрес: Металлистов пр-т 28с1, Санкт-Петербург

Геокодирование:  50%|████▉     | 9954/19990 [15:10<43:28,  3.85it/s]

[9955] Геокодируем адрес: Ленинский пр-т 148к2, Санкт-Петербург

Геокодирование:  50%|████▉     | 9956/19990 [15:11<51:20,  3.26it/s]

[9958] Геокодируем адрес: Большевиков пр-т 13к3, Санкт-Петербург

Геокодирование:  50%|████▉     | 9959/19990 [15:12<52:09,  3.21it/s]

[9959] Геокодируем адрес: Среднеохтинский пр-т 15, Санкт-Петербург

Геокодирование:  50%|████▉     | 9961/19990 [15:13<1:02:00,  2.70it/s]

Автосохранение после 9960 строк...
[9968] Геокодируем адрес: 1-й Муринский пр-т, Санкт-Петербург

Геокодирование:  50%|████▉     | 9969/19990 [15:14<38:31,  4.34it/s]

[9977] Геокодируем адрес: Лиговский пр-т 107, Санкт-Петербург

Геокодирование:  50%|████▉     | 9978/19990 [15:15<26:21,  6.33it/s]

[9986] Геокодируем адрес: 2-й Муринский пр-т 26, Санкт-Петербург

Геокодирование:  50%|████▉     | 9991/19990 [15:19<36:01,  4.63it/s]

Автосохранение после 9990 строк...
[9997] Геокодируем адрес: Сиреневый б-р 7к2, Санкт-Петербург

Геокодирование:  50%|█████     | 9998/19990 [15:20<29:19,  5.68it/s]

[9998] Геокодируем адрес: Энгельса пр-т 98, Санкт-Петербург
[9999] Геокодируем адрес: Парголово Заречная ул 38к2, Санкт-Петербург

Геокодирование:  50%|█████     | 10000/19990 [15:22<45:16,  3.68it/s]

[10013] Геокодируем адрес: Средний ВО пр-т, Санкт-Петербург

Геокодирование:  50%|█████     | 10014/19990 [15:23<27:08,  6.13it/s]

[10017] Геокодируем адрес: Средний ВО пр-т, Санкт-Петербург

Геокодирование:  50%|█████     | 10018/19990 [15:24<29:44,  5.59it/s]

[10020] Геокодируем адрес: Литейном пр-т 56, Санкт-Петербург

Геокодирование:  50%|█████     | 10021/19990 [15:25<35:40,  4.66it/s]

Автосохранение после 10020 строк...
[10021] Геокодируем адрес: Литейном пр-т 56, Санкт-Петербург

Геокодирование:  50%|█████     | 10022/19990 [15:26<43:54,  3.78it/s]

[10028] Геокодируем адрес: Петергоф Ропшинское ш, Санкт-Петербург

Геокодирование:  50%|█████     | 10029/19990 [15:27<34:37,  4.79it/s]

[10029] Геокодируем адрес: Новаторов б-р 112, Санкт-Петербург

Геокодирование:  50%|█████     | 10030/19990 [15:29<59:53,  2.77it/s]

[10031] Геокодируем адрес: Новаторов б-р 112, Санкт-Петербург

Геокодирование:  50%|█████     | 10032/19990 [15:30<1:04:00,  2.59it/s]

[10033] Геокодируем адрес: Петергоф Ропшинское ш, Санкт-Петербург

Геокодирование:  50%|█████     | 10034/19990 [15:31<1:05:08,  2.55it/s]

[10035] Геокодируем адрес: Петергоф Ропшинское ш, Санкт-Петербург

Геокодирование:  50%|█████     | 10036/19990 [15:32<1:09:55,  2.37it/s]

[10038] Геокодируем адрес: Петергоф Ропшинское ш 8литАН, Санкт-Петербург

Геокодирование:  50%|█████     | 10039/19990 [15:33<1:03:16,  2.62it/s]

[10039] Геокодируем адрес: Петергоф Ропшинское ш 8литАН, Санкт-Петербург

Геокодирование:  50%|█████     | 10040/19990 [15:34<1:17:08,  2.15it/s]

[10040] Геокодируем адрес: Петергоф Ропшинское ш 8литАН, Санкт-Петербург

Геокодирование:  50%|█████     | 10041/19990 [15:35<1:31:42,  1.81it/s]

[10041] Геокодируем адрес: Петергоф Ропшинское ш 8литАН, Санкт-Петербург

Геокодирование:  50%|█████     | 10042/19990 [15:36<1:45:43,  1.57it/s]

[10043] Геокодируем адрес: Петергоф Ропшинское ш 8литАН, Санкт-Петербург

Геокодирование:  50%|█████     | 10044/19990 [15:37<1:37:25,  1.70it/s]

[10044] Геокодируем адрес: Петергоф Ропшинское ш 8литАН, Санкт-Петербург

Геокодирование:  50%|█████     | 10051/19990 [15:38<43:40,  3.79it/s]

Автосохранение после 10050 строк...
[10064] Геокодируем адрес: Комендантский пр-т 19к3, Санкт-Петербург

Геокодирование:  50%|█████     | 10065/19990 [15:39<21:16,  7.78it/s]

[10071] Геокодируем адрес: Зеленогорский Ленина пр-т, Санкт-Петербург

Геокодирование:  50%|█████     | 10072/19990 [15:40<22:07,  7.47it/s]

[10077] Геокодируем адрес: Большой Сампсониевский пр-т, Санкт-Петербург

Геокодирование:  50%|█████     | 10078/19990 [15:41<24:33,  6.73it/s]

[10078] Геокодируем адрес: Левашово Горское ш, Санкт-Петербург

Геокодирование:  50%|█████     | 10079/19990 [15:42<32:49,  5.03it/s]

[10079] Геокодируем адрес: Цитатдельская дор, Санкт-Петербург

Геокодирование:  50%|█████     | 10081/19990 [15:43<40:16,  4.10it/s]

Автосохранение после 10080 строк...
[10085] Геокодируем адрес: Шушары Витебский пр-т, Санкт-Петербург

Геокодирование:  50%|█████     | 10086/19990 [15:44<36:41,  4.50it/s]

[10086] Геокодируем адрес: Славы пр-т 43/49, Санкт-Петербург

Геокодирование:  50%|█████     | 10087/19990 [15:45<54:01,  3.06it/s]

[10094] Геокодируем адрес: Стачек пр-т 95, Санкт-Петербург

Геокодирование:  51%|█████     | 10095/19990 [15:46<33:59,  4.85it/s]

[10109] Геокодируем адрес: Маршака пр-т 16к3, Санкт-Петербург

Геокодирование:  51%|█████     | 10111/19990 [15:47<19:47,  8.32it/s]

Автосохранение после 10110 строк...
[10112] Геокодируем адрес: Стачек пр-т 95к1, Санкт-Петербург

Геокодирование:  51%|█████     | 10113/19990 [15:48<26:21,  6.25it/s]

[10114] Геокодируем адрес: Парголово Шишкина ул 291к1, Санкт-Петербург

Геокодирование:  51%|█████     | 10115/19990 [15:49<35:21,  4.66it/s]

[10115] Геокодируем адрес: Кронштадт Красная ул 8к1, Санкт-Петербург

Геокодирование:  51%|█████     | 10116/19990 [15:50<49:03,  3.35it/s]

[10118] Геокодируем адрес: 25-я линия ВО, Санкт-Петербург

Геокодирование:  51%|█████     | 10119/19990 [15:52<1:15:10,  2.19it/s]

[10119] Геокодируем адрес: Елагинский пр-т 42, Санкт-Петербург

Геокодирование:  51%|█████     | 10120/19990 [15:53<1:20:46,  2.04it/s]

[10124] Геокодируем адрес: Марата ул 2/73-75, Санкт-Петербург

Геокодирование:  51%|█████     | 10125/19990 [15:54<1:01:36,  2.67it/s]

[10125] Геокодируем адрес: Петергоф Ропшинское ш 4, Санкт-Петербург

Геокодирование:  51%|█████     | 10126/19990 [15:55<1:08:42,  2.39it/s]

[10126] Геокодируем адрес: Петергоф Ропшинское ш 10, Санкт-Петербург

Геокодирование:  51%|█████     | 10127/19990 [15:56<1:22:33,  1.99it/s]

[10127] Геокодируем адрес: Новаторов б-р 78, Санкт-Петербург

Геокодирование:  51%|█████     | 10128/19990 [15:57<1:38:06,  1.68it/s]

[10129] Геокодируем адрес: Лиговский пр-т 114Г, Санкт-Петербург

Геокодирование:  51%|█████     | 10130/19990 [15:58<1:31:22,  1.80it/s]

[10134] Геокодируем адрес: Просвещения пр-т 21/139, Санкт-Петербург

Геокодирование:  51%|█████     | 10135/19990 [15:59<1:01:13,  2.68it/s]

[10135] Геокодируем адрес: Энгельса пр-т 22, Санкт-Петербург

Геокодирование:  51%|█████     | 10136/19990 [16:00<1:15:58,  2.16it/s]

[10136] Геокодируем адрес: Петергоф Ропшинское ш 4, Санкт-Петербург

Геокодирование:  51%|█████     | 10137/19990 [16:01<1:27:39,  1.87it/s]

[10138] Геокодируем адрес: Обуховской Обороны пр-т 33, Санкт-Петербург

Геокодирование:  51%|█████     | 10139/19990 [16:02<1:25:47,  1.91it/s]

[10139] Геокодируем адрес: Ленина пр-т, Санкт-Петербург

Геокодирование:  51%|█████     | 10141/19990 [16:03<1:23:48,  1.96it/s]

Автосохранение после 10140 строк...
[10144] Геокодируем адрес: Народного Ополчения пр-т 47, Санкт-Петербург

Геокодирование:  51%|█████     | 10145/19990 [16:04<59:30,  2.76it/s]

[10145] Геокодируем адрес: Новаторов б-р 78, Санкт-Петербург

Геокодирование:  51%|█████     | 10146/19990 [16:05<1:15:44,  2.17it/s]

[10146] Геокодируем адрес: Трамвайный пр-т 17, Санкт-Петербург

Геокодирование:  51%|█████     | 10147/19990 [16:06<1:31:11,  1.80it/s]

[10150] Геокодируем адрес: Красное село Нарвская ул 6, Санкт-Петербург

Геокодирование:  51%|█████     | 10151/19990 [16:07<1:07:32,  2.43it/s]

[10154] Геокодируем адрес: Зеленогорск Ленина пр-т, Санкт-Петербург

Геокодирование:  51%|█████     | 10155/19990 [16:08<52:56,  3.10it/s]

[10155] Геокодируем адрес: Науки пр-т 71к3, Санкт-Петербург

Геокодирование:  51%|█████     | 10156/19990 [16:09<1:07:24,  2.43it/s]

[10156] Геокодируем адрес: Наставников пр-т 36к2, Санкт-Петербург

Геокодирование:  51%|█████     | 10157/19990 [16:10<1:21:51,  2.00it/s]

[10161] Геокодируем адрес: Металлострой Северный пр-д, Санкт-Петербург

Геокодирование:  51%|█████     | 10162/19990 [16:11<56:38,  2.89it/s]

[10162] Геокодируем адрес: Испытателей пр-т 20к2, Санкт-Петербург

Геокодирование:  51%|█████     | 10163/19990 [16:12<1:11:05,  2.30it/s]

[10164] Геокодируем адрес: Светлановский пр-т 43, Санкт-Петербург

Геокодирование:  51%|█████     | 10171/19990 [16:13<36:57,  4.43it/s]

Автосохранение после 10170 строк...
[10174] Геокодируем адрес: Усть-Славянка Советский пр-т, Санкт-Петербург

Геокодирование:  51%|█████     | 10175/19990 [16:14<35:42,  4.58it/s]

[10176] Геокодируем адрес: Петергоф Ропшинское ш, Санкт-Петербург

Геокодирование:  51%|█████     | 10177/19990 [16:15<43:44,  3.74it/s]

[10177] Геокодируем адрес: Металлострой дор, Санкт-Петербург

Геокодирование:  51%|█████     | 10178/19990 [16:16<57:31,  2.84it/s]

[10178] Геокодируем адрес: Петергоф Ропшинское ш, Санкт-Петербург

Геокодирование:  51%|█████     | 10179/19990 [16:17<1:14:35,  2.19it/s]

[10184] Геокодируем адрес: Наставников пр-т 45к1, Санкт-Петербург

Геокодирование:  51%|█████     | 10185/19990 [16:18<47:19,  3.45it/s]

[10187] Геокодируем адрес: Пушкин Малиновская ул 11Б, Санкт-Петербург

Геокодирование:  51%|█████     | 10188/19990 [16:19<51:14,  3.19it/s]

[10189] Геокодируем адрес: Пушкин Малиновская ул 11Б, Санкт-Петербург

Геокодирование:  51%|█████     | 10190/19990 [16:20<58:18,  2.80it/s]

[10191] Геокодируем адрес: Политехническая ул 1литО, Санкт-Петербург

Геокодирование:  51%|█████     | 10201/19990 [16:21<25:36,  6.37it/s]

Автосохранение после 10200 строк...
[10204] Геокодируем адрес: Петергоф Ропшинское ш 4, Санкт-Петербург

Геокодирование:  51%|█████     | 10205/19990 [16:22<29:53,  5.46it/s]

[10205] Геокодируем адрес: Испытателей пр-т 33, Санкт-Петербург
[10206] Геокодируем адрес: Петергоф Ропшинское ш 4, Санкт-Петербург

Геокодирование:  51%|█████     | 10207/19990 [16:24<51:16,  3.18it/s]

[10208] Геокодируем адрес: Петергоф Ропшинское ш 4, Санкт-Петербург

Геокодирование:  51%|█████     | 10209/19990 [16:25<57:19,  2.84it/s]

[10209] Геокодируем адрес: Петергоф Ропшинское ш 4, Санкт-Петербург

Геокодирование:  51%|█████     | 10210/19990 [16:26<1:09:31,  2.34it/s]

[10210] Геокодируем адрес: Петергоф Ропшинское ш 4, Санкт-Петербург

Геокодирование:  51%|█████     | 10211/19990 [16:27<1:24:11,  1.94it/s]

[10213] Геокодируем адрес: Каменноостровский пр-т 33, Санкт-Петербург

Геокодирование:  51%|█████     | 10214/19990 [16:28<1:13:23,  2.22it/s]

[10216] Геокодируем адрес: Таврическая ул 5литА, Санкт-Петербург

Геокодирование:  51%|█████     | 10217/19990 [16:29<1:02:41,  2.60it/s]

[10218] Геокодируем адрес: Шушары Школьная ул 12, Санкт-Петербург

Геокодирование:  51%|█████     | 10219/19990 [16:30<1:09:36,  2.34it/s]

[10219] Геокодируем адрес: Шушары Школьная ул 12, Санкт-Петербург

Геокодирование:  51%|█████     | 10220/19990 [16:31<1:23:59,  1.94it/s]

[10224] Геокодируем адрес: Культуры пр-т 26к5, Санкт-Петербург

Геокодирование:  51%|█████     | 10225/19990 [16:32<56:08,  2.90it/s]

[10228] Геокодируем адрес: Богатырский пр-т 2, Санкт-Петербург

Геокодирование:  51%|█████     | 10231/19990 [16:33<44:23,  3.66it/s]

Автосохранение после 10230 строк...
[10233] Геокодируем адрес: Пушкин Петербургское ш 10, Санкт-Петербург

Геокодирование:  51%|█████     | 10234/19990 [16:34<43:23,  3.75it/s]

[10234] Геокодируем адрес: 21-я линия ВО 16к6, Санкт-Петербург

Геокодирование:  51%|█████     | 10235/19990 [16:35<1:01:26,  2.65it/s]

[10242] Геокодируем адрес: Шушары Витебский пр-т, Санкт-Петербург

Геокодирование:  51%|█████     | 10243/19990 [16:36<34:49,  4.66it/s]

[10246] Геокодируем адрес: Богатырский пр-т 12, Санкт-Петербург

Геокодирование:  51%|█████▏    | 10247/19990 [16:37<37:11,  4.37it/s]

[10248] Геокодируем адрес: Петергоф Ропшинское ш 4, Санкт-Петербург

Геокодирование:  51%|█████▏    | 10249/19990 [16:38<44:29,  3.65it/s]

[10251] Геокодируем адрес: канал Грибоедова наб, Санкт-Петербург

Геокодирование:  51%|█████▏    | 10252/19990 [16:39<47:17,  3.43it/s]

[10253] Геокодируем адрес: Королева пр-т 62А, Санкт-Петербург

Геокодирование:  51%|█████▏    | 10254/19990 [16:40<55:23,  2.93it/s]

[10254] Геокодируем адрес: Чернышевского пр-т 14, Санкт-Петербург

Геокодирование:  51%|█████▏    | 10255/19990 [16:41<1:09:47,  2.32it/s]

[10255] Геокодируем адрес: Испытателей пр-т 35, Санкт-Петербург

Геокодирование:  51%|█████▏    | 10256/19990 [16:42<1:23:42,  1.94it/s]

[10256] Геокодируем адрес: Приморский пр-т 161, Санкт-Петербург

Геокодирование:  51%|█████▏    | 10257/19990 [16:43<1:41:30,  1.60it/s]

[10258] Геокодируем адрес: Южная дор, Санкт-Петербург

Геокодирование:  51%|█████▏    | 10261/19990 [16:44<1:03:11,  2.57it/s]

Автосохранение после 10260 строк...
[10262] Геокодируем адрес: Новоизмайловский пр-т 20к2, Санкт-Петербург

Геокодирование:  51%|█████▏    | 10263/19990 [16:45<1:05:40,  2.47it/s]

[10264] Геокодируем адрес: Парголово Федора Абрамова ул 21к3, Санкт-Петербург

Геокодирование:  51%|█████▏    | 10265/19990 [16:46<1:10:54,  2.29it/s]

[10265] Геокодируем адрес: Лиговский пр-т 47, Санкт-Петербург

Геокодирование:  51%|█████▏    | 10266/19990 [16:47<1:28:41,  1.83it/s]

[10268] Геокодируем адрес: Новаторов б-р 78, Санкт-Петербург

Геокодирование:  51%|█████▏    | 10269/19990 [16:48<1:13:24,  2.21it/s]

[10271] Геокодируем адрес: КИМа пр-т 13, Санкт-Петербург

Геокодирование:  51%|█████▏    | 10272/19990 [16:49<1:05:35,  2.47it/s]

[10275] Геокодируем адрес: Лиговский пр-т 117, Санкт-Петербург

Геокодирование:  51%|█████▏    | 10276/19990 [16:50<56:09,  2.88it/s]

[10278] Геокодируем адрес: Парголово Некрасова ул 37, Санкт-Петербург

Геокодирование:  51%|█████▏    | 10279/19990 [16:51<53:28,  3.03it/s]

[10281] Геокодируем адрес: Народного Ополчения пр-т 149, Санкт-Петербург

Геокодирование:  51%|█████▏    | 10282/19990 [16:52<56:06,  2.88it/s]

[10286] Геокодируем адрес: Металлострой Садовая ул 8литА, Санкт-Петербург

Геокодирование:  51%|█████▏    | 10287/19990 [16:53<42:51,  3.77it/s]

[10288] Геокодируем адрес: Богатырский пр-т 51к1, Санкт-Петербург

Геокодирование:  51%|█████▏    | 10289/19990 [16:54<51:35,  3.13it/s]

[10289] Геокодируем адрес: Зеленогорск Пухтоловская дор, Санкт-Петербург

Геокодирование:  51%|█████▏    | 10290/19990 [16:55<1:04:00,  2.53it/s]

[10290] Геокодируем адрес: Искровский пр-т 32к1, Санкт-Петербург

Геокодирование:  51%|█████▏    | 10291/19990 [16:57<1:46:43,  1.51it/s]

Автосохранение после 10290 строк...
[10291] Геокодируем адрес: Новгородский пр-т 10, Санкт-Петербург

Геокодирование:  51%|█████▏    | 10292/19990 [16:58<1:54:36,  1.41it/s]

[10294] Геокодируем адрес: Лиговский пр-т 47, Санкт-Петербург

Геокодирование:  52%|█████▏    | 10295/19990 [16:59<1:28:16,  1.83it/s]

[10296] Геокодируем адрес: Лиговский пр-т 47, Санкт-Петербург

Геокодирование:  52%|█████▏    | 10297/19990 [17:00<1:26:26,  1.87it/s]

[10297] Геокодируем адрес: Маршала Захарова пр-т 14к2, Санкт-Петербург

Геокодирование:  52%|█████▏    | 10298/19990 [17:01<1:37:41,  1.65it/s]

[10314] Геокодируем адрес: Вознесенский пр-т 29, Санкт-Петербург

Геокодирование:  52%|█████▏    | 10321/19990 [17:02<20:48,  7.74it/s]

Автосохранение после 10320 строк...
[10332] Геокодируем адрес: Ленинский пр-т 151, Санкт-Петербург

Геокодирование:  52%|█████▏    | 10333/19990 [17:04<23:22,  6.89it/s]

[10347] Геокодируем адрес: Лиговский пр-т 81, Санкт-Петербург

Геокодирование:  52%|█████▏    | 10351/19990 [17:05<16:01, 10.03it/s]

Автосохранение после 10350 строк...
[10351] Геокодируем адрес: Тореза ул 38, Санкт-Петербург

Геокодирование:  52%|█████▏    | 10353/19990 [17:06<20:23,  7.88it/s]

[10359] Геокодируем адрес: Ветеранов пр-т 140Г, Санкт-Петербург

Геокодирование:  52%|█████▏    | 10360/19990 [17:07<21:37,  7.42it/s]

[10360] Геокодируем адрес: Сестрорецк Токарева ул 10, Санкт-Петербург

Геокодирование:  52%|█████▏    | 10362/19990 [17:08<28:15,  5.68it/s]

[10369] Геокодируем адрес: Маршала Жукова ул 30к2, Санкт-Петербург

Геокодирование:  52%|█████▏    | 10370/19990 [17:09<25:04,  6.39it/s]

[10371] Геокодируем адрес: Медиков пр-т 10к1, Санкт-Петербург

Геокодирование:  52%|█████▏    | 10372/19990 [17:10<33:00,  4.86it/s]

[10372] Геокодируем адрес: Медиков пр-т 10к5, Санкт-Петербург

Геокодирование:  52%|█████▏    | 10373/19990 [17:11<41:01,  3.91it/s]

[10378] Геокодируем адрес: Лиговский пр-т 63, Санкт-Петербург

Геокодирование:  52%|█████▏    | 10381/19990 [17:12<32:16,  4.96it/s]

Автосохранение после 10380 строк...
[10382] Геокодируем адрес: Ветеранов пр-т 155, Санкт-Петербург

Геокодирование:  52%|█████▏    | 10383/19990 [17:13<40:51,  3.92it/s]

[10387] Геокодируем адрес: Бакунина пр-т 19-25, Санкт-Петербург

Геокодирование:  52%|█████▏    | 10388/19990 [17:14<37:13,  4.30it/s]

[10396] Геокодируем адрес: Меншиковский пр-т 15к1, Санкт-Петербург

Геокодирование:  52%|█████▏    | 10397/19990 [17:16<34:58,  4.57it/s]

[10398] Геокодируем адрес: Школьная ул 7, Санкт-Петербург

Геокодирование:  52%|█████▏    | 10399/19990 [17:17<43:10,  3.70it/s]

[10405] Геокодируем адрес: Славы пр-т 40, Санкт-Петербург

Геокодирование:  52%|█████▏    | 10406/19990 [17:18<34:05,  4.69it/s]

[10408] Геокодируем адрес: Славы пр-т 2к2, Санкт-Петербург

Геокодирование:  52%|█████▏    | 10409/19990 [17:19<37:05,  4.30it/s]

[10409] Геокодируем адрес: Ириновский пр-т 25Б, Санкт-Петербург

Геокодирование:  52%|█████▏    | 10411/19990 [17:20<44:57,  3.55it/s]

Автосохранение после 10410 строк...
[10414] Геокодируем адрес: Богатырский пр-т 10, Санкт-Петербург

Геокодирование:  52%|█████▏    | 10415/19990 [17:21<41:23,  3.86it/s]

[10418] Геокодируем адрес: Энгельса пр-т 22, Санкт-Петербург

Геокодирование:  52%|█████▏    | 10419/19990 [17:22<42:29,  3.75it/s]

[10419] Геокодируем адрес: Парголово Первого Мая ул 107к4, Санкт-Петербург

Геокодирование:  52%|█████▏    | 10420/19990 [17:23<52:31,  3.04it/s]

[10422] Геокодируем адрес: Красное Село Гатчинское ш 12к1, Санкт-Петербург

Геокодирование:  52%|█████▏    | 10423/19990 [17:24<56:31,  2.82it/s]

[10428] Геокодируем адрес: Обуховской Обороны пр-т 229/7, Санкт-Петербург

Геокодирование:  52%|█████▏    | 10441/19990 [17:25<18:19,  8.68it/s]

Автосохранение после 10440 строк...
[10444] Геокодируем адрес: Лубьи наб, Санкт-Петербург

Геокодирование:  52%|█████▏    | 10445/19990 [17:26<19:59,  7.96it/s]

[10454] Геокодируем адрес: Обуховской Обороны пр-т 269, Санкт-Петербург

Геокодирование:  52%|█████▏    | 10455/19990 [17:27<19:21,  8.21it/s]

[10459] Геокодируем адрес: Художников пр-т 9к2, Санкт-Петербург

Геокодирование:  52%|█████▏    | 10460/19990 [17:28<21:07,  7.52it/s]

[10461] Геокодируем адрес: Петергоф Ропшинское ш 4, Санкт-Петербург

Геокодирование:  52%|█████▏    | 10462/19990 [17:29<28:56,  5.49it/s]

[10464] Геокодируем адрес: Мориса Тореза пр-т 44Б, Санкт-Петербург

Геокодирование:  52%|█████▏    | 10471/19990 [17:30<23:06,  6.86it/s]

Автосохранение после 10470 строк...
[10477] Геокодируем адрес: Ленинский пр-т 110к1, Санкт-Петербург

Геокодирование:  52%|█████▏    | 10478/19990 [17:31<20:45,  7.63it/s]

[10478] Геокодируем адрес: Грнчарная ул, Санкт-Петербург

Геокодирование:  52%|█████▏    | 10480/19990 [17:32<27:46,  5.71it/s]

[10482] Геокодируем адрес: Маршала Жукова пр-т 54к6, Санкт-Петербург

Геокодирование:  52%|█████▏    | 10483/19990 [17:33<34:58,  4.53it/s]

[10486] Геокодируем адрес: Металлострой Центральный пр-д, Санкт-Петербург

Геокодирование:  52%|█████▏    | 10487/19990 [17:34<35:36,  4.45it/s]

[10489] Геокодируем адрес: Комендантский пр-т 18, Санкт-Петербург

Геокодирование:  52%|█████▏    | 10490/19990 [17:35<40:56,  3.87it/s]

[10498] Геокодируем адрес: Дунайский пр-т 7, Санкт-Петербург

Геокодирование:  53%|█████▎    | 10499/19990 [17:36<28:53,  5.48it/s]

[10499] Геокодируем адрес: Греческий пр-т 23А, Санкт-Петербург

Геокодирование:  53%|█████▎    | 10501/19990 [17:37<37:30,  4.22it/s]

Автосохранение после 10500 строк...
[10501] Геокодируем адрес: Ветеранов пр-т 3к3, Санкт-Петербург

Геокодирование:  53%|█████▎    | 10502/19990 [17:38<48:34,  3.26it/s]

[10502] Геокодируем адрес: Невский пр-т 95, Санкт-Петербург

Геокодирование:  53%|█████▎    | 10503/19990 [17:39<1:05:56,  2.40it/s]

[10504] Геокодируем адрес: Кондратьевский пр-т 55, Санкт-Петербург

Геокодирование:  53%|█████▎    | 10505/19990 [17:40<1:08:13,  2.32it/s]

[10509] Геокодируем адрес: Большой В.О. пр-т 78-80, Санкт-Петербург

Геокодирование:  53%|█████▎    | 10510/19990 [17:41<54:27,  2.90it/s]

[10510] Геокодируем адрес: Солидарности пр-т 13к2, Санкт-Петербург

Геокодирование:  53%|█████▎    | 10511/19990 [17:42<1:00:04,  2.63it/s]

[10514] Геокодируем адрес: Маршала Блюхера пр-т, Санкт-Петербург

Геокодирование:  53%|█████▎    | 10515/19990 [17:43<52:55,  2.98it/s]

[10521] Геокодируем адрес: Шушары Новгородский пр-т 10, Санкт-Петербург

Геокодирование:  53%|█████▎    | 10522/19990 [17:44<37:52,  4.17it/s]

[10522] Геокодируем адрес: Шушары Новгородский пр-т 10, Санкт-Петербург

Геокодирование:  53%|█████▎    | 10523/19990 [17:45<49:05,  3.21it/s]

[10527] Геокодируем адрес: Светлановский пр-т 115к2, Санкт-Петербург

Геокодирование:  53%|█████▎    | 10531/19990 [17:46<32:55,  4.79it/s]

Автосохранение после 10530 строк...
[10532] Геокодируем адрес: Стачек пр-т 59/3, Санкт-Петербург

Геокодирование:  53%|█████▎    | 10533/19990 [17:47<40:19,  3.91it/s]

[10533] Геокодируем адрес: Муринская дор, Санкт-Петербург

Геокодирование:  53%|█████▎    | 10534/19990 [17:48<51:40,  3.05it/s]

[10534] Геокодируем адрес: Кондратьевский пр-т 55, Санкт-Петербург

Геокодирование:  53%|█████▎    | 10535/19990 [17:49<1:09:59,  2.25it/s]

[10535] Геокодируем адрес: Луначарского пр-т 70, Санкт-Петербург

Геокодирование:  53%|█████▎    | 10536/19990 [17:50<1:26:38,  1.82it/s]

[10538] Геокодируем адрес: Кондратьевский пр-т 55, Санкт-Петербург

Геокодирование:  53%|█████▎    | 10539/19990 [17:51<1:11:36,  2.20it/s]

[10539] Геокодируем адрес: канала Грибоедова наб 18-20 лит.З, Санкт-Петербург

Геокодирование:  53%|█████▎    | 10540/19990 [17:52<1:28:07,  1.79it/s]

[10550] Геокодируем адрес: Среднеохтинский пр-т 1к2, Санкт-Петербург

Геокодирование:  53%|█████▎    | 10551/19990 [17:53<33:06,  4.75it/s]

[10557] Геокодируем адрес: Тореза пр-т 38, Санкт-Петербург

Геокодирование:  53%|█████▎    | 10558/19990 [17:54<29:12,  5.38it/s]

[10559] Геокодируем адрес: Маршала Жукова пр-т 66к1, Санкт-Петербург

Геокодирование:  53%|█████▎    | 10561/19990 [17:55<34:45,  4.52it/s]

Автосохранение после 10560 строк...
[10561] Геокодируем адрес: Шушары Новгородский пр-т 10, Санкт-Петербург

Геокодирование:  53%|█████▎    | 10562/19990 [17:56<47:01,  3.34it/s]

[10564] Геокодируем адрес: Испытателей пр-т 12, Санкт-Петербург

Геокодирование:  53%|█████▎    | 10565/19990 [17:57<47:28,  3.31it/s]

[10569] Геокодируем адрес: Юнтоловский пр-т 53к3, Санкт-Петербург

Геокодирование:  53%|█████▎    | 10570/19990 [17:58<39:18,  3.99it/s]

[10575] Геокодируем адрес: Красное Село Освобождения ул 23к1, Санкт-Петербург

Геокодирование:  53%|█████▎    | 10576/19990 [17:59<35:48,  4.38it/s]

[10578] Геокодируем адрес: Шушары Пушкинская ул 3, Санкт-Петербург

Геокодирование:  53%|█████▎    | 10579/19990 [18:00<38:25,  4.08it/s]

[10580] Геокодируем адрес: Пушкин Чистякова ул 4, Санкт-Петербург

Геокодирование:  53%|█████▎    | 10581/19990 [18:01<45:27,  3.45it/s]

[10586] Геокодируем адрес: Зеленогорск Овражная ул 29, Санкт-Петербург

Геокодирование:  53%|█████▎    | 10587/19990 [18:02<36:51,  4.25it/s]

[10587] Геокодируем адрес: Левашово Горское ш, Санкт-Петербург

Геокодирование:  53%|█████▎    | 10588/19990 [18:03<47:32,  3.30it/s]

[10589] Геокодируем адрес: Культуры пр-т, Санкт-Петербург

Геокодирование:  53%|█████▎    | 10591/19990 [18:04<51:30,  3.04it/s]

Автосохранение после 10590 строк...
[10596] Геокодируем адрес: Ломоносов Ораниенбаумский пр-т 33к3, Санкт-Петербург

Геокодирование:  53%|█████▎    | 10597/19990 [18:05<34:25,  4.55it/s]

[10599] Геокодируем адрес: Лиговский пр-т 114Г, Санкт-Петербург

Геокодирование:  53%|█████▎    | 10600/19990 [18:06<39:52,  3.92it/s]

[10602] Геокодируем адрес: Культуры пр-т 8, Санкт-Петербург

Геокодирование:  53%|█████▎    | 10603/19990 [18:07<45:42,  3.42it/s]

[10603] Геокодируем адрес: Ветеранов пр-т 88, Санкт-Петербург

Геокодирование:  53%|█████▎    | 10604/19990 [18:08<58:56,  2.65it/s]

[10604] Геокодируем адрес: Дачный пр-т 8к1, Санкт-Петербург

Геокодирование:  53%|█████▎    | 10605/19990 [18:09<1:10:08,  2.23it/s]

[10616] Геокодируем адрес: Ветеранов пр-т 30, Санкт-Петербург

Геокодирование:  53%|█████▎    | 10621/19990 [18:10<24:11,  6.45it/s]

Автосохранение после 10620 строк...
[10628] Геокодируем адрес: Культуры пр-т 21к1, Санкт-Петербург

Геокодирование:  53%|█████▎    | 10629/19990 [18:11<19:50,  7.86it/s]

[10638] Геокодируем адрес: Молодежное Солнечная ул 5, Санкт-Петербург

Геокодирование:  53%|█████▎    | 10639/19990 [18:12<17:51,  8.73it/s]

[10640] Геокодируем адрес: Ветеранов пр-т 88, Санкт-Петербург

Геокодирование:  53%|█████▎    | 10641/19990 [18:13<25:24,  6.13it/s]

[10644] Геокодируем адрес: Маршала Блюхера пр-т, Санкт-Петербург

Геокодирование:  53%|█████▎    | 10645/19990 [18:14<27:56,  5.58it/s]

[10646] Геокодируем адрес: Шушары Редкое Кузьмино ул, Санкт-Петербург

Геокодирование:  53%|█████▎    | 10647/19990 [18:15<34:07,  4.56it/s]

[10648] Геокодируем адрес: Молодёжное Солнечная ул 5, Санкт-Петербург

Геокодирование:  53%|█████▎    | 10649/19990 [18:16<42:44,  3.64it/s]

[10649] Геокодируем адрес: Парголово Федора Абрамова ул 8, Санкт-Петербург

Геокодирование:  53%|█████▎    | 10651/19990 [18:17<51:19,  3.03it/s]

Автосохранение после 10650 строк...
[10658] Геокодируем адрес: Комендантский пр-т 31к3, Санкт-Петербург

Геокодирование:  53%|█████▎    | 10659/19990 [18:18<28:47,  5.40it/s]

[10679] Геокодируем адрес: Греческий пр-т 9, Санкт-Петербург

Геокодирование:  53%|█████▎    | 10681/19990 [18:19<15:11, 10.21it/s]

Автосохранение после 10680 строк...
[10690] Геокодируем адрес: Пискаревский пр-т 159к7, Санкт-Петербург

Геокодирование:  53%|█████▎    | 10691/19990 [18:20<13:27, 11.51it/s]

[10696] Геокодируем адрес: Шушары Новгородский пр-т 10, Санкт-Петербург

Геокодирование:  54%|█████▎    | 10697/19990 [18:21<17:17,  8.96it/s]

[10698] Геокодируем адрес: КИМа пр-т 30А, Санкт-Петербург

Геокодирование:  54%|█████▎    | 10711/19990 [18:22<13:07, 11.78it/s]

Автосохранение после 10710 строк...
[10718] Геокодируем адрес: Петергоф Ропшинское ш 3к6, Санкт-Петербург

Геокодирование:  54%|█████▎    | 10719/19990 [18:23<14:02, 11.01it/s]

[10719] Геокодируем адрес: Петергоф Ропшинское ш 3к3, Санкт-Петербург
[10720] Геокодируем адрес: Петергоф Парковая ул 14к2, Санкт-Петербург
[10721] Геокодируем адрес: Металлистов пр-т 72, Санкт-Петербург

Геокодирование:  54%|█████▎    | 10722/19990 [18:26<34:49,  4.44it/s]

[10732] Геокодируем адрес: Шушары Новгородский пр-т, Санкт-Петербург

Геокодирование:  54%|█████▎    | 10733/19990 [18:27<24:59,  6.17it/s]

[10735] Геокодируем адрес: Кронштадт Пролетарская ул, Санкт-Петербург

Геокодирование:  54%|█████▎    | 10736/19990 [18:28<28:41,  5.37it/s]

[10737] Геокодируем адрес: Петергоф Ропшинское ш, Санкт-Петербург

Геокодирование:  54%|█████▎    | 10738/19990 [18:29<34:47,  4.43it/s]

[10738] Геокодируем адрес: Лиговский пр-т 145/2, Санкт-Петербург

Геокодирование:  54%|█████▎    | 10741/19990 [18:30<39:32,  3.90it/s]

Автосохранение после 10740 строк...
[10744] Геокодируем адрес: Суздальский пр-т 26, Санкт-Петербург

Геокодирование:  54%|█████▍    | 10745/19990 [18:31<36:29,  4.22it/s]

[10748] Геокодируем адрес: Металлострой Богайчука ул, Санкт-Петербург

Геокодирование:  54%|█████▍    | 10749/19990 [18:32<35:31,  4.34it/s]

[10755] Геокодируем адрес: канал Грибоедова наб 18-20Е, Санкт-Петербург

Геокодирование:  54%|█████▍    | 10756/19990 [18:33<31:27,  4.89it/s]

[10759] Геокодируем адрес: Заневский пр-т 45, Санкт-Петербург

Геокодирование:  54%|█████▍    | 10760/19990 [18:34<32:43,  4.70it/s]

[10767] Геокодируем адрес: Московский пр-т 157, Санкт-Петербург

Геокодирование:  54%|█████▍    | 10771/19990 [18:35<24:09,  6.36it/s]

Автосохранение после 10770 строк...
[10776] Геокодируем адрес: Обуховской Обороны пр-т 33к2, Санкт-Петербург

Геокодирование:  54%|█████▍    | 10777/19990 [18:36<21:27,  7.16it/s]

[10778] Геокодируем адрес: Старо-Петергофский пр-т 21к1, Санкт-Петербург

Геокодирование:  54%|█████▍    | 10779/19990 [18:37<29:48,  5.15it/s]

[10781] Геокодируем адрес: Лиговский пр-т 215, Санкт-Петербург

Геокодирование:  54%|█████▍    | 10782/19990 [18:38<35:57,  4.27it/s]

[10784] Геокодируем адрес: 5-я линия ВО, Санкт-Петербург

Геокодирование:  54%|█████▍    | 10785/19990 [18:39<42:51,  3.58it/s]

[10787] Геокодируем адрес: канал Грибоедова наб, Санкт-Петербург

Геокодирование:  54%|█████▍    | 10788/19990 [18:40<40:14,  3.81it/s]

[10793] Геокодируем адрес: Гуммолосары Садовая ул, Санкт-Петербург

Геокодирование:  54%|█████▍    | 10794/19990 [18:41<33:38,  4.56it/s]

[10795] Геокодируем адрес: Ветеранов пр-т 171, Санкт-Петербург

Геокодирование:  54%|█████▍    | 10796/19990 [18:42<44:01,  3.48it/s]

[10797] Геокодируем адрес: Обуховской Обороны пр-т 33А, Санкт-Петербург

Геокодирование:  54%|█████▍    | 10798/19990 [18:43<48:58,  3.13it/s]

[10798] Геокодируем адрес: Космонавтов пр-т 65к2, Санкт-Петербург

Геокодирование:  54%|█████▍    | 10801/19990 [18:44<47:02,  3.26it/s]

Автосохранение после 10800 строк...
[10806] Геокодируем адрес: Парголово Валерия Гаврилина ул, Санкт-Петербург

Геокодирование:  54%|█████▍    | 10807/19990 [18:45<33:13,  4.61it/s]

[10810] Геокодируем адрес: Космонавтов пр-т 27к5, Санкт-Петербург

Геокодирование:  54%|█████▍    | 10811/19990 [18:46<35:21,  4.33it/s]

[10811] Геокодируем адрес: Муринская дор 51к1, Санкт-Петербург

Геокодирование:  54%|█████▍    | 10812/19990 [18:47<47:53,  3.19it/s]

[10812] Геокодируем адрес: Энергетиков пр-т 9к3, Санкт-Петербург

Геокодирование:  54%|█████▍    | 10813/19990 [18:48<1:01:24,  2.49it/s]

[10814] Геокодируем адрес: Ленинский пр-т 116, Санкт-Петербург

Геокодирование:  54%|█████▍    | 10815/19990 [18:49<1:10:52,  2.16it/s]

[10827] Геокодируем адрес: Колпино Раумская ул 15, Санкт-Петербург

Геокодирование:  54%|█████▍    | 10828/19990 [18:50<26:33,  5.75it/s]

[10830] Геокодируем адрес: Ленинский пр-т 96к3, Санкт-Петербург

Геокодирование:  54%|█████▍    | 10831/19990 [18:51<32:19,  4.72it/s]

Автосохранение после 10830 строк...
[10832] Геокодируем адрес: Мечникова пр-т 5к2, Санкт-Петербург

Геокодирование:  54%|█████▍    | 10833/19990 [18:52<37:53,  4.03it/s]

[10834] Геокодируем адрес: Колпино Красных Партизан ул 4, Санкт-Петербург

Геокодирование:  54%|█████▍    | 10835/19990 [18:53<44:41,  3.41it/s]

[10835] Геокодируем адрес: Московский пр-т 208, Санкт-Петербург

Геокодирование:  54%|█████▍    | 10836/19990 [18:54<59:24,  2.57it/s]

[10846] Геокодируем адрес: Петергоф Ропшинское ш 3к8, Санкт-Петербург

Геокодирование:  54%|█████▍    | 10847/19990 [18:55<28:50,  5.28it/s]

[10849] Геокодируем адрес: Петергоф Ропшинское ш 4, Санкт-Петербург

Геокодирование:  54%|█████▍    | 10850/19990 [18:56<33:36,  4.53it/s]

[10858] Геокодируем адрес: Чкаловский пр-т 18, Санкт-Петербург

Геокодирование:  54%|█████▍    | 10861/19990 [18:57<24:57,  6.10it/s]

Автосохранение после 10860 строк...
[10873] Геокодируем адрес: Королева пр-т 62, Санкт-Петербург

Геокодирование:  54%|█████▍    | 10874/19990 [18:58<16:39,  9.12it/s]

[10874] Геокодируем адрес: Кубинская ул 36литА, Санкт-Петербург

Геокодирование:  54%|█████▍    | 10876/19990 [18:59<20:53,  7.27it/s]

[10878] Геокодируем адрес: Маршала Казакова ул 1к2Д, Санкт-Петербург

Геокодирование:  54%|█████▍    | 10891/19990 [19:00<13:53, 10.92it/s]

Автосохранение после 10890 строк...
[10892] Геокодируем адрес: Красное Село Стрельнинское ш, Санкт-Петербург

Геокодирование:  54%|█████▍    | 10894/19990 [19:01<19:37,  7.72it/s]

[10894] Геокодируем адрес: Поэтический б-р, Санкт-Петербург

Геокодирование:  55%|█████▍    | 10896/19990 [19:02<26:06,  5.81it/s]

[10898] Геокодируем адрес: Художников пр-т 23к1, Санкт-Петербург

Геокодирование:  55%|█████▍    | 10899/19990 [19:03<31:37,  4.79it/s]

[10905] Геокодируем адрес: Лесной пр-т 8, Санкт-Петербург

Геокодирование:  55%|█████▍    | 10906/19990 [19:04<28:46,  5.26it/s]

[10911] Геокодируем адрес: Юрия Гагарина пр-т 53, Санкт-Петербург

Геокодирование:  55%|█████▍    | 10912/19990 [19:05<28:09,  5.37it/s]

[10918] Геокодируем адрес: Обуховской Обороны пр-т 243, Санкт-Петербург

Геокодирование:  55%|█████▍    | 10919/19990 [19:06<24:53,  6.07it/s]

[10919] Геокодируем адрес: Маршала Казакова пр-т, Санкт-Петербург

Геокодирование:  55%|█████▍    | 10921/19990 [19:07<32:06,  4.71it/s]

Автосохранение после 10920 строк...
[10922] Геокодируем адрес: Колпино Московская ул 11, Санкт-Петербург

Геокодирование:  55%|█████▍    | 10923/19990 [19:08<38:05,  3.97it/s]

[10925] Геокодируем адрес: Маршала Жукова пр-т 74к1, Санкт-Петербург

Геокодирование:  55%|█████▍    | 10926/19990 [19:09<41:56,  3.60it/s]

[10926] Геокодируем адрес: Маршала Жукова пр-т 74к1, Санкт-Петербург

Геокодирование:  55%|█████▍    | 10927/19990 [19:10<54:59,  2.75it/s]

[10932] Геокодируем адрес: Парголово Николая Рубцова ул 3, Санкт-Петербург

Геокодирование:  55%|█████▍    | 10933/19990 [19:11<39:36,  3.81it/s]

[10933] Геокодируем адрес: Горелово Красносельское ш 36, Санкт-Петербург

Геокодирование:  55%|█████▍    | 10934/19990 [19:12<52:42,  2.86it/s]

[10941] Геокодируем адрес: 11-я линия ВО 58, Санкт-Петербург

Геокодирование:  55%|█████▍    | 10942/19990 [19:15<49:34,  3.04it/s]

[10942] Геокодируем адрес: Стачек пр-т 87, Санкт-Петербург

Геокодирование:  55%|█████▍    | 10951/19990 [19:15<28:38,  5.26it/s]

Автосохранение после 10950 строк...
[10952] Геокодируем адрес: Приморский пр-т 137к1, Санкт-Петербург

Геокодирование:  55%|█████▍    | 10953/19990 [19:16<32:25,  4.65it/s]

[10967] Геокодируем адрес: Елизарова пр-т 8к2Е, Санкт-Петербург

Геокодирование:  55%|█████▍    | 10968/19990 [19:17<18:07,  8.30it/s]

[10971] Геокодируем адрес: Кораблестроителей пр-т 40к2, Санкт-Петербург

Геокодирование:  55%|█████▍    | 10972/19990 [19:18<22:17,  6.74it/s]

[10972] Геокодируем адрес: Ленина пл 88, Санкт-Петербург

Геокодирование:  55%|█████▍    | 10974/19990 [19:19<29:25,  5.11it/s]

[10975] Геокодируем адрес: энгельса пр-т 7б, Санкт-Петербург

Геокодирование:  55%|█████▍    | 10981/19990 [19:21<26:02,  5.76it/s]

Автосохранение после 10980 строк...
[10982] Геокодируем адрес: Космонавтов пр-т 37, Санкт-Петербург

Геокодирование:  55%|█████▍    | 10983/19990 [19:21<32:19,  4.65it/s]

[10984] Геокодируем адрес: Дунайский пр-т 53к2, Санкт-Петербург

Геокодирование:  55%|█████▍    | 10985/19990 [19:22<37:26,  4.01it/s]

[10997] Геокодируем адрес: Лиговский пр-т 99, Санкт-Петербург

Геокодирование:  55%|█████▌    | 10998/19990 [19:23<21:45,  6.89it/s]

[11000] Геокодируем адрес: Александровский б-р, Санкт-Петербург

Геокодирование:  55%|█████▌    | 11001/19990 [19:24<26:18,  5.69it/s]

[11003] Геокодируем адрес: Петергоф Ораниенбаумское ш 4А, Санкт-Петербург

Геокодирование:  55%|█████▌    | 11004/19990 [19:25<31:25,  4.77it/s]

[11004] Геокодируем адрес: Петергоф Ораниенбаумское ш 4А, Санкт-Петербург

Геокодирование:  55%|█████▌    | 11005/19990 [19:26<41:09,  3.64it/s]

[11005] Геокодируем адрес: Петергоф Ораниенбаумское ш 4А, Санкт-Петербург

Геокодирование:  55%|█████▌    | 11006/19990 [19:27<53:19,  2.81it/s]

[11006] Геокодируем адрес: Петергоф Ораниенбаумское ш 4А, Санкт-Петербург

Геокодирование:  55%|█████▌    | 11007/19990 [19:28<1:06:51,  2.24it/s]

[11009] Геокодируем адрес: Пятилеток пр-т 10к2, Санкт-Петербург

Геокодирование:  55%|█████▌    | 11011/19990 [19:29<53:20,  2.81it/s]

Автосохранение после 11010 строк...
[11025] Геокодируем адрес: Литейный пр-т 54, Санкт-Петербург

Геокодирование:  55%|█████▌    | 11026/19990 [19:30<20:45,  7.20it/s]

[11028] Геокодируем адрес: Пушкин Пушкинская ул 8, Санкт-Петербург

Геокодирование:  55%|█████▌    | 11029/19990 [19:31<25:21,  5.89it/s]

[11033] Геокодируем адрес: Колпино Павловская ул 8, Санкт-Петербург

Геокодирование:  55%|█████▌    | 11041/19990 [19:32<17:45,  8.40it/s]

Автосохранение после 11040 строк...
[11045] Геокодируем адрес: Комендантский пр-т 13к1, Санкт-Петербург

Геокодирование:  55%|█████▌    | 11046/19990 [19:33<19:19,  7.71it/s]

[11047] Геокодируем адрес: Комендантский пр-т 13к1, Санкт-Петербург

Геокодирование:  55%|█████▌    | 11048/19990 [19:34<27:00,  5.52it/s]

[11048] Геокодируем адрес: Пушкин Церковная ул 17/7, Санкт-Петербург

Геокодирование:  55%|█████▌    | 11050/19990 [19:35<36:32,  4.08it/s]

[11050] Геокодируем адрес: Российский пр-т 14, Санкт-Петербург

Геокодирование:  55%|█████▌    | 11051/19990 [19:36<47:24,  3.14it/s]

[11053] Геокодируем адрес: Культуры пр-т 21к1, Санкт-Петербург

Геокодирование:  55%|█████▌    | 11054/19990 [19:37<47:01,  3.17it/s]

[11054] Геокодируем адрес: Колпино Оборонный мост, Санкт-Петербург

Геокодирование:  55%|█████▌    | 11055/19990 [19:38<58:04,  2.56it/s]

[11056] Геокодируем адрес: Большой Сампсониевский пр-т 18, Санкт-Петербург

Геокодирование:  55%|█████▌    | 11057/19990 [19:39<1:06:38,  2.23it/s]

[11061] Геокодируем адрес: Бабушкина ул 17к3Б, Санкт-Петербург

Геокодирование:  55%|█████▌    | 11071/19990 [19:40<21:09,  7.02it/s]

Автосохранение после 11070 строк...
[11080] Геокодируем адрес: Славы пр-т 2к2, Санкт-Петербург

Геокодирование:  55%|█████▌    | 11081/19990 [19:41<18:16,  8.12it/s]

[11086] Геокодируем адрес: Шушары Школьная ул 26, Санкт-Петербург

Геокодирование:  55%|█████▌    | 11087/19990 [19:42<19:44,  7.52it/s]

[11091] Геокодируем адрес: Песочный Садовая ул 8, Санкт-Петербург

Геокодирование:  55%|█████▌    | 11092/19990 [19:43<22:17,  6.65it/s]

[11092] Геокодируем адрес: Турухтанные Острова дор, Санкт-Петербург

Геокодирование:  55%|█████▌    | 11094/19990 [19:44<28:41,  5.17it/s]

[11098] Геокодируем адрес: Парголово Архитектора Белова ул, Санкт-Петербург

Геокодирование:  56%|█████▌    | 11101/19990 [19:45<26:05,  5.68it/s]

Автосохранение после 11100 строк...
[11110] Геокодируем адрес: Петергоф Ораниенбаумское ш, Санкт-Петербург

Геокодирование:  56%|█████▌    | 11111/19990 [19:46<19:22,  7.64it/s]

[11111] Геокодируем адрес: Петергоф Ораниенбаумское ш, Санкт-Петербург

Геокодирование:  56%|█████▌    | 11112/19990 [19:47<27:52,  5.31it/s]

[11112] Геокодируем адрес: Петергоф Ораниенбаумское ш, Санкт-Петербург

Геокодирование:  56%|█████▌    | 11113/19990 [19:48<38:38,  3.83it/s]

[11113] Геокодируем адрес: Петергоф Сергиевка сквер, Санкт-Петербург

Геокодирование:  56%|█████▌    | 11114/19990 [19:49<50:42,  2.92it/s]

[11118] Геокодируем адрес: Петергоф Ораниенбаумское ш 4А, Санкт-Петербург

Геокодирование:  56%|█████▌    | 11119/19990 [19:50<42:35,  3.47it/s]

[11120] Геокодируем адрес: Луначарского пр-т 88к1, Санкт-Петербург

Геокодирование:  56%|█████▌    | 11121/19990 [19:51<47:39,  3.10it/s]

[11122] Геокодируем адрес: Колпино Культуры ул 9, Санкт-Петербург

Геокодирование:  56%|█████▌    | 11123/19990 [19:52<54:42,  2.70it/s]

[11124] Геокодируем адрес: Кронштадт Зосимова ул, Санкт-Петербург

Геокодирование:  56%|█████▌    | 11131/19990 [19:53<30:03,  4.91it/s]

Автосохранение после 11130 строк...
[11134] Геокодируем адрес: Литейный пр-т 17-19, Санкт-Петербург

Геокодирование:  56%|█████▌    | 11135/19990 [19:54<32:50,  4.49it/s]

[11142] Геокодируем адрес: Просвещения пр-т 74, Санкт-Петербург

Геокодирование:  56%|█████▌    | 11143/19990 [19:55<25:31,  5.78it/s]

[11144] Геокодируем адрес: Большеохтинский пр-т 33/3, Санкт-Петербург

Геокодирование:  56%|█████▌    | 11145/19990 [19:56<32:57,  4.47it/s]

[11155] Геокодируем адрес: Большевиков пр-т 9к2, Санкт-Петербург

Геокодирование:  56%|█████▌    | 11161/19990 [19:57<16:57,  8.68it/s]

Автосохранение после 11160 строк...
[11164] Геокодируем адрес: Королева пр-т 42к2, Санкт-Петербург

Геокодирование:  56%|█████▌    | 11165/19990 [19:58<21:29,  6.84it/s]

[11167] Геокодируем адрес: Шушары Старорусский пр-т 13к1, Санкт-Петербург

Геокодирование:  56%|█████▌    | 11168/19990 [19:59<26:00,  5.65it/s]

[11169] Геокодируем адрес: Петергоф Ропшинское ш 10, Санкт-Петербург

Геокодирование:  56%|█████▌    | 11170/19990 [20:00<33:32,  4.38it/s]

[11173] Геокодируем адрес: Петергоф Ораниенбаумское ш 4А, Санкт-Петербург

Геокодирование:  56%|█████▌    | 11174/19990 [20:02<45:42,  3.21it/s]

[11174] Геокодируем адрес: Ломоносов Цветочная ул, Санкт-Петербург

Геокодирование:  56%|█████▌    | 11175/19990 [20:03<54:58,  2.67it/s]

[11175] Геокодируем адрес: Петергоф Ораниенбаумское ш 4А, Санкт-Петербург

Геокодирование:  56%|█████▌    | 11176/19990 [20:04<1:08:11,  2.15it/s]

[11176] Геокодируем адрес: Ломоносов Цветочная ул, Санкт-Петербург

Геокодирование:  56%|█████▌    | 11177/19990 [20:05<1:18:51,  1.86it/s]

[11177] Геокодируем адрес: Ломоносов Цветочная ул, Санкт-Петербург

Геокодирование:  56%|█████▌    | 11178/19990 [20:06<1:30:03,  1.63it/s]

[11181] Геокодируем адрес: Петергоф Ораниенбаумское ш 4А, Санкт-Петербург

Геокодирование:  56%|█████▌    | 11191/19990 [20:07<26:27,  5.54it/s]

Автосохранение после 11190 строк...
[11194] Геокодируем адрес: Дачный пр-т 36к5, Санкт-Петербург

Геокодирование:  56%|█████▌    | 11195/19990 [20:08<26:53,  5.45it/s]

[11204] Геокодируем адрес: Большевиков пр-т 61к1, Санкт-Петербург

Геокодирование:  56%|█████▌    | 11221/19990 [20:09<10:11, 14.33it/s]

Автосохранение после 11220 строк...
[11230] Геокодируем адрес: Искровский пр-т 25, Санкт-Петербург

Геокодирование:  56%|█████▌    | 11231/19990 [20:10<11:23, 12.82it/s]

[11232] Геокодируем адрес: Народного Ополчения пр-т 47, Санкт-Петербург

Геокодирование:  56%|█████▌    | 11235/19990 [20:11<16:08,  9.04it/s]

[11235] Геокодируем адрес: Дачный пр-т 36к5, Санкт-Петербург
[11236] Геокодируем адрес: Пушкин Генерала Хазова ул 43, Санкт-Петербург

Геокодирование:  56%|█████▌    | 11238/19990 [20:13<26:34,  5.49it/s]

[11239] Геокодируем адрес: Коннолахтинская дор, Санкт-Петербург

Геокодирование:  56%|█████▌    | 11240/19990 [20:14<31:09,  4.68it/s]

[11242] Геокодируем адрес: Дунайский пр-т 56/124, Санкт-Петербург

Геокодирование:  56%|█████▌    | 11243/19990 [20:15<36:17,  4.02it/s]

[11243] Геокодируем адрес: Культуры пр-т, Санкт-Петербург

Геокодирование:  56%|█████▋    | 11251/19990 [20:16<25:18,  5.76it/s]

Автосохранение после 11250 строк...
[11255] Геокодируем адрес: Московский пр-т 192-194, Санкт-Петербург

Геокодирование:  56%|█████▋    | 11256/19990 [20:18<27:53,  5.22it/s]

[11260] Геокодируем адрес: Новаторов б-р 78, Санкт-Петербург

Геокодирование:  56%|█████▋    | 11261/19990 [20:18<26:10,  5.56it/s]

[11269] Геокодируем адрес: Новаторов б-р 72, Санкт-Петербург

Геокодирование:  56%|█████▋    | 11270/19990 [20:19<22:06,  6.58it/s]

[11270] Геокодируем адрес: Новаторов б-р 68, Санкт-Петербург

Геокодирование:  56%|█████▋    | 11272/19990 [20:20<27:37,  5.26it/s]

[11275] Геокодируем адрес: Пушкин Петербургское ш 13/1, Санкт-Петербург

Геокодирование:  56%|█████▋    | 11276/19990 [20:21<31:39,  4.59it/s]

[11276] Геокодируем адрес: Новаторов ул 84, Санкт-Петербург

Геокодирование:  56%|█████▋    | 11281/19990 [20:22<27:35,  5.26it/s]

Автосохранение после 11280 строк...
[11281] Геокодируем адрес: Сиреневый б-р 8к1, Санкт-Петербург

Геокодирование:  56%|█████▋    | 11283/19990 [20:23<35:52,  4.05it/s]

[11283] Геокодируем адрес: Индустриальный пр-т 10к1, Санкт-Петербург

Геокодирование:  56%|█████▋    | 11284/19990 [20:24<49:01,  2.96it/s]

[11284] Геокодируем адрес: Шушары Валдайская ул 1, Санкт-Петербург

Геокодирование:  56%|█████▋    | 11285/19990 [20:25<1:00:02,  2.42it/s]

[11289] Геокодируем адрес: Средний ВО пр-т, Санкт-Петербург

Геокодирование:  56%|█████▋    | 11290/19990 [20:26<45:03,  3.22it/s]

[11296] Геокодируем адрес: Авиаконструкторов пр-т 3к1, Санкт-Петербург

Геокодирование:  57%|█████▋    | 11297/19990 [20:27<32:52,  4.41it/s]

[11300] Геокодируем адрес: Каменноостровский пр-т 59, Санкт-Петербург

Геокодирование:  57%|█████▋    | 11301/19990 [20:28<33:39,  4.30it/s]

[11302] Геокодируем адрес: Стачек пр-т 105, Санкт-Петербург

Геокодирование:  57%|█████▋    | 11311/19990 [20:29<22:00,  6.57it/s]

Автосохранение после 11310 строк...
[11311] Геокодируем адрес: Парголово Заречная ул, Санкт-Петербург

Геокодирование:  57%|█████▋    | 11313/19990 [20:30<26:25,  5.47it/s]

[11322] Геокодируем адрес: Кронштадт Тулонская ул, Санкт-Петербург

Геокодирование:  57%|█████▋    | 11323/19990 [20:31<20:13,  7.14it/s]

[11330] Геокодируем адрес: 3-я линия ВО 61к3, Санкт-Петербург

Геокодирование:  57%|█████▋    | 11331/19990 [20:32<20:34,  7.01it/s]

[11331] Геокодируем адрес: Кронштадт Гусева ул 11, Санкт-Петербург

Геокодирование:  57%|█████▋    | 11333/19990 [20:33<25:29,  5.66it/s]

[11336] Геокодируем адрес: Солидарности пр-т 4, Санкт-Петербург

Геокодирование:  57%|█████▋    | 11341/19990 [20:34<22:45,  6.33it/s]

Автосохранение после 11340 строк...
[11343] Геокодируем адрес: Михаила Защенко ул, Санкт-Петербург

Геокодирование:  57%|█████▋    | 11344/19990 [20:35<24:33,  5.87it/s]

[11345] Геокодируем адрес: Сестрорецк Ново-Гагаринская ул, Санкт-Петербург

Геокодирование:  57%|█████▋    | 11346/19990 [20:36<33:33,  4.29it/s]

[11347] Геокодируем адрес: Лиговский пр-т 81, Санкт-Петербург

Геокодирование:  57%|█████▋    | 11348/19990 [20:37<42:20,  3.40it/s]

[11350] Геокодируем адрес: Шушары Старорусский пр-т 13к1, Санкт-Петербург

Геокодирование:  57%|█████▋    | 11351/19990 [20:39<56:10,  2.56it/s]

[11354] Геокодируем адрес: Невский пр-т 28, Санкт-Петербург

Геокодирование:  57%|█████▋    | 11355/19990 [20:40<51:12,  2.81it/s]

[11361] Геокодируем адрес: Песочный Пограничная ул 108, Санкт-Петербург

Геокодирование:  57%|█████▋    | 11362/19990 [20:41<35:33,  4.04it/s]

[11362] Геокодируем адрес: Сестрорецк Левашовское ш, Санкт-Петербург

Геокодирование:  57%|█████▋    | 11363/19990 [20:42<43:13,  3.33it/s]

[11364] Геокодируем адрес: Витебский пр-т 55, Санкт-Петербург

Геокодирование:  57%|█████▋    | 11365/19990 [20:43<51:34,  2.79it/s]

[11368] Геокодируем адрес: Суздальский пр-т 93к1, Санкт-Петербург

Геокодирование:  57%|█████▋    | 11369/19990 [20:44<44:24,  3.24it/s]

[11369] Геокодируем адрес: Ветеранов пр-т 105, Санкт-Петербург

Геокодирование:  57%|█████▋    | 11370/19990 [20:45<59:00,  2.43it/s]

[11370] Геокодируем адрес: Луначарского пр-т 7к2, Санкт-Петербург

Геокодирование:  57%|█████▋    | 11371/19990 [20:46<1:10:43,  2.03it/s]

Автосохранение после 11370 строк...
[11376] Геокодируем адрес: Ириновский пр-т 43, Санкт-Петербург

Геокодирование:  57%|█████▋    | 11377/19990 [20:47<44:39,  3.21it/s]

[11389] Геокодируем адрес: Парголово Валерия Гаврилина ул 3к1, Санкт-Петербург

Геокодирование:  57%|█████▋    | 11390/19990 [20:48<22:20,  6.42it/s]

[11393] Геокодируем адрес: Ленинский пр-т 129к3, Санкт-Петербург

Геокодирование:  57%|█████▋    | 11394/19990 [20:49<25:05,  5.71it/s]

[11397] Геокодируем адрес: Пятилеток пр-т 3, Санкт-Петербург

Геокодирование:  57%|█████▋    | 11398/19990 [20:50<29:20,  4.88it/s]

[11399] Геокодируем адрес: Суворовский пр-т 62, Санкт-Петербург

Геокодирование:  57%|█████▋    | 11401/19990 [20:52<37:38,  3.80it/s]

Автосохранение после 11400 строк...
[11401] Геокодируем адрес: Шушары Валдайская ул 6к2, Санкт-Петербург

Геокодирование:  57%|█████▋    | 11402/19990 [20:55<1:34:06,  1.52it/s]

[11402] Геокодируем адрес: Тореза пр-т 104к3, Санкт-Петербург

Геокодирование:  57%|█████▋    | 11403/19990 [20:56<1:42:33,  1.40it/s]

[11410] Геокодируем адрес: 2-ой Муринский пр-т 15, Санкт-Петербург

Геокодирование:  57%|█████▋    | 11411/19990 [21:00<1:19:26,  1.80it/s]

[11427] Геокодируем адрес: Синопская ул 32/35, Санкт-Петербург

Геокодирование:  57%|█████▋    | 11428/19990 [21:01<34:20,  4.16it/s]

[11429] Геокодируем адрес: Витебский пр-т 53/1, Санкт-Петербург

RateLimiter caught an error, retrying (0/2 tries). Called with (*('Витебский пр-т 53/1, Санкт-Петербург',), **{}).
Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connection.py", line 516, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1374, in getresponse
    response.begin()
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1278, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1134, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 367, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=%D0%92%D0%B8%D1%82%D0%B5%D0%B1%D1%81%D0%BA%D0%B8%D0%B9+%D0%BF%D1%80-%D1%82+53%2F1%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 482, in _request
    resp = self.session.get(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=%D0%92%D0%B8%D1%82%D0%B5%D0%B1%D1%81%D0%BA%D0%B8%D0%B9+%D0%BF%D1%80-%D1%82+53%2F1%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\extra\rate_limiter.py", line 136, in _retries_gen
    yield i  # Run the function.
    ^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\extra\rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\geocoders\nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\geocoders\base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 472, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 494, in _request
    raise GeocoderUnavailable(message)
geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=%D0%92%D0%B8%D1%82%D0%B5%D0%B1%D1%81%D0%BA%D0%B8%D0%B9+%D0%BF%D1%80-%D1%82+53%2F1%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))
RateLimiter caught an error, retrying (1/2 tries). Called with (*('Витебский пр-т 53/1, Санкт-Петербург',), **{}).
Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connection.py", line 516, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1374, in getresponse
    response.begin()
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1278, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1134, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 367, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=%D0%92%D0%B8%D1%82%D0%B5%D0%B1%D1%81%D0%BA%D0%B8%D0%B9+%D0%BF%D1%80-%D1%82+53%2F1%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 482, in _request
    resp = self.session.get(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=%D0%92%D0%B8%D1%82%D0%B5%D0%B1%D1%81%D0%BA%D0%B8%D0%B9+%D0%BF%D1%80-%D1%82+53%2F1%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\extra\rate_limiter.py", line 136, in _retries_gen
    yield i  # Run the function.
    ^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\extra\rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\geocoders\nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\geocoders\base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 472, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 494, in _request
    raise GeocoderUnavailable(message)
geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=%D0%92%D0%B8%D1%82%D0%B5%D0%B1%D1%81%D0%BA%D0%B8%D0%B9+%D0%BF%D1%80-%D1%82+53%2F1%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))
Геокодирование:  57%|█████▋    | 11431/19990 [21:19<2:28:00,  1.04s/it]

Автосохранение после 11430 строк...
[11431] Геокодируем адрес: Ленина пр-т, Санкт-Петербург

Геокодирование:  57%|█████▋    | 11432/19990 [21:20<2:24:49,  1.02s/it]

[11440] Геокодируем адрес: Космонавтов пр-т 28к2, Санкт-Петербург

Геокодирование:  57%|█████▋    | 11441/19990 [21:21<1:16:33,  1.86it/s]

[11450] Геокодируем адрес: Луначарского пр-т 7к2, Санкт-Петербург

Геокодирование:  57%|█████▋    | 11451/19990 [21:22<48:46,  2.92it/s]

[11456] Геокодируем адрес: Витебский пр-т 97к1, Санкт-Петербург

Геокодирование:  57%|█████▋    | 11457/19990 [21:23<40:38,  3.50it/s]

[11458] Геокодируем адрес: Энтузиастов пр-т 28к1, Санкт-Петербург

Геокодирование:  57%|█████▋    | 11461/19990 [21:25<41:32,  3.42it/s]

Автосохранение после 11460 строк...
[11462] Геокодируем адрес: Новочеркасский пр-т 13, Санкт-Петербург

Геокодирование:  57%|█████▋    | 11463/19990 [21:25<45:31,  3.12it/s]

[11465] Геокодируем адрес: 2-ой Муринский пр-т 19, Санкт-Петербург

Геокодирование:  57%|█████▋    | 11466/19990 [21:27<47:48,  2.97it/s]

[11467] Геокодируем адрес: Энгельса пр-т 117, Санкт-Петербург

RateLimiter caught an error, retrying (0/2 tries). Called with (*('Энгельса пр-т 117, Санкт-Петербург',), **{}).
Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connection.py", line 516, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1374, in getresponse
    response.begin()
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1278, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1134, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 367, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=%D0%AD%D0%BD%D0%B3%D0%B5%D0%BB%D1%8C%D1%81%D0%B0+%D0%BF%D1%80-%D1%82+117%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 482, in _request
    resp = self.session.get(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=%D0%AD%D0%BD%D0%B3%D0%B5%D0%BB%D1%8C%D1%81%D0%B0+%D0%BF%D1%80-%D1%82+117%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\extra\rate_limiter.py", line 136, in _retries_gen
    yield i  # Run the function.
    ^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\extra\rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\geocoders\nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\geocoders\base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 472, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 494, in _request
    raise GeocoderUnavailable(message)
geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=%D0%AD%D0%BD%D0%B3%D0%B5%D0%BB%D1%8C%D1%81%D0%B0+%D0%BF%D1%80-%D1%82+117%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))
Геокодирование:  57%|█████▋    | 11468/19990 [21:36<2:58:14,  1.25s/it]

[11468] Геокодируем адрес: Богатырский пр-т 37к 2, Санкт-Петербург

Геокодирование:  57%|█████▋    | 11469/19990 [21:38<2:59:51,  1.27s/it]

[11469] Геокодируем адрес: Авиаконструкторов пр-т 49, Санкт-Петербург

Геокодирование:  57%|█████▋    | 11470/19990 [21:39<2:54:56,  1.23s/it]

[11477] Геокодируем адрес: Ленинский пр-т 121, Санкт-Петербург

Геокодирование:  57%|█████▋    | 11478/19990 [21:40<1:16:52,  1.85it/s]

[11478] Геокодируем адрес: Стачек пр-т 198, Санкт-Петербург

RateLimiter caught an error, retrying (0/2 tries). Called with (*('Стачек пр-т 198, Санкт-Петербург',), **{}).
Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connection.py", line 516, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1374, in getresponse
    response.begin()
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1278, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1134, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 367, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=%D0%A1%D1%82%D0%B0%D1%87%D0%B5%D0%BA+%D0%BF%D1%80-%D1%82+198%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 482, in _request
    resp = self.session.get(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=%D0%A1%D1%82%D0%B0%D1%87%D0%B5%D0%BA+%D0%BF%D1%80-%D1%82+198%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\extra\rate_limiter.py", line 136, in _retries_gen
    yield i  # Run the function.
    ^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\extra\rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\geocoders\nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\geocoders\base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 472, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 494, in _request
    raise GeocoderUnavailable(message)
geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=%D0%A1%D1%82%D0%B0%D1%87%D0%B5%D0%BA+%D0%BF%D1%80-%D1%82+198%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))
Геокодирование:  57%|█████▋    | 11479/19990 [21:51<3:56:35,  1.67s/it]

[11480] Геокодируем адрес: Шушары Витебский пр-т, Санкт-Петербург

Геокодирование:  57%|█████▋    | 11481/19990 [21:52<3:16:24,  1.38s/it]

[11486] Геокодируем адрес: Шушары Витебский пр-т, Санкт-Петербург

Геокодирование:  57%|█████▋    | 11487/19990 [21:54<1:54:27,  1.24it/s]

[11488] Геокодируем адрес: Науки пр-т 17, Санкт-Петербург

Геокодирование:  57%|█████▋    | 11491/19990 [21:55<1:25:01,  1.67it/s]

Автосохранение после 11490 строк...
[11495] Геокодируем адрес: Серебристый б-р 17к1, Санкт-Петербург

Геокодирование:  58%|█████▊    | 11496/19990 [21:55<57:59,  2.44it/s]

[11504] Геокодируем адрес: Большой Петроградской стороны пр-т 106, Санкт-Петербург

Геокодирование:  58%|█████▊    | 11505/19990 [21:57<38:33,  3.67it/s]

[11506] Геокодируем адрес: Шушары Старорусский пр-т 13к1, Санкт-Петербург

Геокодирование:  58%|█████▊    | 11521/19990 [21:58<17:56,  7.87it/s]

Автосохранение после 11520 строк...
[11526] Геокодируем адрес: Пушкин Октябрьский б-р, Санкт-Петербург

Геокодирование:  58%|█████▊    | 11527/19990 [21:59<18:08,  7.78it/s]

[11538] Геокодируем адрес: Лесной пр-т 39к3, Санкт-Петербург

Геокодирование:  58%|█████▊    | 11539/19990 [21:59<14:56,  9.43it/s]

[11539] Геокодируем адрес: Кондратьевский пр-т 62к6, Санкт-Петербург
[11541] Геокодируем адрес: Конногвардейский б-р, Санкт-Петербург

Геокодирование:  58%|█████▊    | 11542/19990 [22:02<32:07,  4.38it/s]

[11545] Геокодируем адрес: Большой Сампсониевский пр-т 18, Санкт-Петербург

Геокодирование:  58%|█████▊    | 11546/19990 [22:04<35:24,  3.98it/s]

[11546] Геокодируем адрес: Большой Сампсониевский пр-т 20, Санкт-Петербург

Геокодирование:  58%|█████▊    | 11548/19990 [22:05<43:02,  3.27it/s]

[11549] Геокодируем адрес: Пушкин Малиновская ул 11, Санкт-Петербург

Геокодирование:  58%|█████▊    | 11550/19990 [22:06<48:27,  2.90it/s]

[11550] Геокодируем адрес: Пушкин Малиновская ул 11, Санкт-Петербург

Геокодирование:  58%|█████▊    | 11551/19990 [22:09<1:19:28,  1.77it/s]

Автосохранение после 11550 строк...
[11551] Геокодируем адрес: Пушкин Малиновская ул 11, Санкт-Петербург

Геокодирование:  58%|█████▊    | 11552/19990 [22:10<1:33:39,  1.50it/s]

[11555] Геокодируем адрес: Суворовский пр-т 2, Санкт-Петербург

Геокодирование:  58%|█████▊    | 11556/19990 [22:13<1:31:35,  1.53it/s]

[11557] Геокодируем адрес: Металлистов пр-т 98, Санкт-Петербург

Геокодирование:  58%|█████▊    | 11558/19990 [22:16<2:08:24,  1.09it/s]

[11558] Геокодируем адрес: Петергоф Юты Бондаровской ул, Санкт-Петербург

Геокодирование:  58%|█████▊    | 11559/19990 [22:17<2:05:56,  1.12it/s]

[11565] Геокодируем адрес: Большой Сампсониевский пр-т 20, Санкт-Петербург

Геокодирование:  58%|█████▊    | 11566/19990 [22:20<1:22:44,  1.70it/s]

[11570] Геокодируем адрес: Торики Ленинградская ул, Санкт-Петербург

Геокодирование:  58%|█████▊    | 11571/19990 [22:21<1:00:41,  2.31it/s]

[11572] Геокодируем адрес: Большой Сампсониевский пр-т 18, Санкт-Петербург

Геокодирование:  58%|█████▊    | 11573/19990 [22:24<1:33:13,  1.50it/s]

[11577] Геокодируем адрес: Солидарности пр-т 7к1, Санкт-Петербург

Геокодирование:  58%|█████▊    | 11578/19990 [22:28<1:35:39,  1.47it/s]

[11580] Геокодируем адрес: Кронштадт Широкая ул 8, Санкт-Петербург

Геокодирование:  58%|█████▊    | 11581/19990 [22:29<1:30:31,  1.55it/s]

Автосохранение после 11580 строк...
[11584] Геокодируем адрес: Адмирала Трибуца мост, Санкт-Петербург

Геокодирование:  58%|█████▊    | 11585/19990 [22:31<1:17:30,  1.81it/s]

[11585] Геокодируем адрес: Луначарского пр-т 5, Санкт-Петербург

Геокодирование:  58%|█████▊    | 11586/19990 [22:33<1:43:01,  1.36it/s]

[11588] Геокодируем адрес: Петергоф Юты Бондаровской ул, Санкт-Петербург

Геокодирование:  58%|█████▊    | 11589/19990 [22:35<1:40:47,  1.39it/s]

[11589] Геокодируем адрес: Петергоф Юты Бондаровской ул, Санкт-Петербург

Геокодирование:  58%|█████▊    | 11590/19990 [22:37<2:02:07,  1.15it/s]

[11596] Геокодируем адрес: Петергоф Ораниенбаумское ш, Санкт-Петербург

Геокодирование:  58%|█████▊    | 11597/19990 [22:38<1:06:04,  2.12it/s]

[11598] Геокодируем адрес: Лиговский пр-т 75, Санкт-Петербург

Геокодирование:  58%|█████▊    | 11599/19990 [22:39<1:06:17,  2.11it/s]

[11601] Геокодируем адрес: Колпино Заводской пр-т, Санкт-Петербург

Геокодирование:  58%|█████▊    | 11602/19990 [22:40<58:49,  2.38it/s]

[11603] Геокодируем адрес: Шушары Петербургское ш, Санкт-Петербург

Геокодирование:  58%|█████▊    | 11604/19990 [22:41<1:01:41,  2.27it/s]

[11607] Геокодируем адрес: Невский пр-т 38к4, Санкт-Петербург

Геокодирование:  58%|█████▊    | 11611/19990 [22:42<38:12,  3.66it/s]

Автосохранение после 11610 строк...
[11623] Геокодируем адрес: Большевиков пр-т 37к1, Санкт-Петербург

Геокодирование:  58%|█████▊    | 11624/19990 [22:43<19:28,  7.16it/s]

[11626] Геокодируем адрес: Стрельна Коммуны ул, Санкт-Петербург

Геокодирование:  58%|█████▊    | 11627/19990 [22:44<24:35,  5.67it/s]

[11637] Геокодируем адрес: Рижский пр-т 4-6, Санкт-Петербург

Геокодирование:  58%|█████▊    | 11641/19990 [22:47<24:35,  5.66it/s]

Автосохранение после 11640 строк...
[11642] Геокодируем адрес: Маршала Блюхера пр-т 52, Санкт-Петербург

Геокодирование:  58%|█████▊    | 11643/19990 [22:48<32:50,  4.24it/s]

[11654] Геокодируем адрес: Шушары Московское ш 258к2, Санкт-Петербург

Геокодирование:  58%|█████▊    | 11655/19990 [22:49<19:31,  7.11it/s]

[11658] Геокодируем адрес: Богатырский пр-т 10, Санкт-Петербург

Геокодирование:  58%|█████▊    | 11659/19990 [22:51<32:53,  4.22it/s]

[11666] Геокодируем адрес: Пушкин Алексея Толстого б-р 16, Санкт-Петербург

Геокодирование:  58%|█████▊    | 11667/19990 [22:52<27:46,  4.99it/s]

[11668] Геокодируем адрес: Славы пр-т 25, Санкт-Петербург

Геокодирование:  58%|█████▊    | 11671/19990 [22:55<39:51,  3.48it/s]

Автосохранение после 11670 строк...
[11677] Геокодируем адрес: Медиков пр-т 10к5, Санкт-Петербург

Геокодирование:  58%|█████▊    | 11678/19990 [22:56<29:28,  4.70it/s]

[11678] Геокодируем адрес: Кавалергардская ул 22литБ, Санкт-Петербург

Геокодирование:  58%|█████▊    | 11679/19990 [22:56<36:07,  3.83it/s]

[11688] Геокодируем адрес: Медиков пр-т 10к1, Санкт-Петербург

RateLimiter caught an error, retrying (0/2 tries). Called with (*('Медиков пр-т 10к1, Санкт-Петербург',), **{}).
Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connection.py", line 516, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1374, in getresponse
    response.begin()
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1278, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1134, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 367, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=%D0%9C%D0%B5%D0%B4%D0%B8%D0%BA%D0%BE%D0%B2+%D0%BF%D1%80-%D1%82+10%D0%BA1%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 482, in _request
    resp = self.session.get(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=%D0%9C%D0%B5%D0%B4%D0%B8%D0%BA%D0%BE%D0%B2+%D0%BF%D1%80-%D1%82+10%D0%BA1%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\extra\rate_limiter.py", line 136, in _retries_gen
    yield i  # Run the function.
    ^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\extra\rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\geocoders\nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\geocoders\base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 472, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 494, in _request
    raise GeocoderUnavailable(message)
geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=%D0%9C%D0%B5%D0%B4%D0%B8%D0%BA%D0%BE%D0%B2+%D0%BF%D1%80-%D1%82+10%D0%BA1%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))
Геокодирование:  58%|█████▊    | 11689/19990 [23:06<1:27:36,  1.58it/s]

[11689] Геокодируем адрес: Дунайский пр-т 7/7, Санкт-Петербург

RateLimiter caught an error, retrying (0/2 tries). Called with (*('Дунайский пр-т 7/7, Санкт-Петербург',), **{}).
Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connection.py", line 516, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1374, in getresponse
    response.begin()
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1278, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1134, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 367, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=%D0%94%D1%83%D0%BD%D0%B0%D0%B9%D1%81%D0%BA%D0%B8%D0%B9+%D0%BF%D1%80-%D1%82+7%2F7%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 482, in _request
    resp = self.session.get(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=%D0%94%D1%83%D0%BD%D0%B0%D0%B9%D1%81%D0%BA%D0%B8%D0%B9+%D0%BF%D1%80-%D1%82+7%2F7%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\extra\rate_limiter.py", line 136, in _retries_gen
    yield i  # Run the function.
    ^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\extra\rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\geocoders\nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\geocoders\base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 472, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 494, in _request
    raise GeocoderUnavailable(message)
geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=%D0%94%D1%83%D0%BD%D0%B0%D0%B9%D1%81%D0%BA%D0%B8%D0%B9+%D0%BF%D1%80-%D1%82+7%2F7%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))
RateLimiter caught an error, retrying (1/2 tries). Called with (*('Дунайский пр-т 7/7, Санкт-Петербург',), **{}).
Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connection.py", line 516, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1374, in getresponse
    response.begin()
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1278, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1134, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 367, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=%D0%94%D1%83%D0%BD%D0%B0%D0%B9%D1%81%D0%BA%D0%B8%D0%B9+%D0%BF%D1%80-%D1%82+7%2F7%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 482, in _request
    resp = self.session.get(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=%D0%94%D1%83%D0%BD%D0%B0%D0%B9%D1%81%D0%BA%D0%B8%D0%B9+%D0%BF%D1%80-%D1%82+7%2F7%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\extra\rate_limiter.py", line 136, in _retries_gen
    yield i  # Run the function.
    ^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\extra\rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\geocoders\nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\geocoders\base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 472, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 494, in _request
    raise GeocoderUnavailable(message)
geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=%D0%94%D1%83%D0%BD%D0%B0%D0%B9%D1%81%D0%BA%D0%B8%D0%B9+%D0%BF%D1%80-%D1%82+7%2F7%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))
Геокодирование:  58%|█████▊    | 11690/19990 [23:24<4:13:24,  1.83s/it]

[11692] Геокодируем адрес: Красных Зорь б-р 10литЗ, Санкт-Петербург

Геокодирование:  58%|█████▊    | 11693/19990 [23:24<3:21:44,  1.46s/it]

[11693] Геокодируем адрес: Науки пр-т 79к3, Санкт-Петербург

Геокодирование:  58%|█████▊    | 11694/19990 [23:26<3:15:36,  1.41s/it]

[11698] Геокодируем адрес: Энгельса пр-т 139, Санкт-Петербург

Геокодирование:  59%|█████▊    | 11701/19990 [23:27<1:47:55,  1.28it/s]

Автосохранение после 11700 строк...
[11703] Геокодируем адрес: Ветеранов пр-т 122, Санкт-Петербург

Геокодирование:  59%|█████▊    | 11704/19990 [23:28<1:28:43,  1.56it/s]

[11707] Геокодируем адрес: Парфёновская ул 7к1стр1, Санкт-Петербург

Геокодирование:  59%|█████▊    | 11708/19990 [23:29<1:04:59,  2.12it/s]

[11713] Геокодируем адрес: Парголово Валерия Гаврилина ул 15, Санкт-Петербург

Геокодирование:  59%|█████▊    | 11714/19990 [23:30<49:00,  2.81it/s]

[11726] Геокодируем адрес: Энгельса пр-т 44, Санкт-Петербург

Геокодирование:  59%|█████▊    | 11727/19990 [23:31<29:45,  4.63it/s]

[11727] Геокодируем адрес: Светлановский пр-т 101, Санкт-Петербург

Геокодирование:  59%|█████▊    | 11728/19990 [23:32<36:41,  3.75it/s]

[11729] Геокодируем адрес: Кронштадт Посадская ул 17/14, Санкт-Петербург

Геокодирование:  59%|█████▊    | 11731/19990 [23:34<39:14,  3.51it/s]

Автосохранение после 11730 строк...
[11731] Геокодируем адрес: Культуры пр-т, Санкт-Петербург

Геокодирование:  59%|█████▊    | 11732/19990 [23:34<48:09,  2.86it/s]

[11733] Геокодируем адрес: Пятилеток пр-т 15к3, Санкт-Петербург

Геокодирование:  59%|█████▊    | 11734/19990 [23:35<54:35,  2.52it/s]

[11734] Геокодируем адрес: Пятилеток пр-т 15к3, Санкт-Петербург

Геокодирование:  59%|█████▊    | 11735/19990 [23:36<1:08:23,  2.01it/s]

[11744] Геокодируем адрес: Суздальский пр-т 6, Санкт-Петербург

Геокодирование:  59%|█████▉    | 11745/19990 [23:38<32:57,  4.17it/s]

[11748] Геокодируем адрес: Новочеркасский пр-т 57к1, Санкт-Петербург

Геокодирование:  59%|█████▉    | 11749/19990 [23:38<30:00,  4.58it/s]

[11749] Геокодируем адрес: Невский пр-т 156Б, Санкт-Петербург

Геокодирование:  59%|█████▉    | 11750/19990 [23:40<42:36,  3.22it/s]

[11751] Геокодируем адрес: Науки пр-т 14к1, Санкт-Петербург

Геокодирование:  59%|█████▉    | 11752/19990 [23:41<54:00,  2.54it/s]

[11752] Геокодируем адрес: Королева пр-т 46к3, Санкт-Петербург

Геокодирование:  59%|█████▉    | 11761/19990 [23:42<25:58,  5.28it/s]

Автосохранение после 11760 строк...
[11762] Геокодируем адрес: Ленина ул 51, Санкт-Петербург

Геокодирование:  59%|█████▉    | 11763/19990 [23:43<33:39,  4.07it/s]

[11763] Геокодируем адрес: Витебский пр-т 47к5, Санкт-Петербург

Геокодирование:  59%|█████▉    | 11765/19990 [23:44<38:31,  3.56it/s]

[11784] Геокодируем адрес: Петергоф Петергофская ул, Санкт-Петербург

Геокодирование:  59%|█████▉    | 11791/19990 [23:45<12:13, 11.18it/s]

Автосохранение после 11790 строк...
[11793] Геокодируем адрес: Мира ул, Санкт-Петербург

Геокодирование:  59%|█████▉    | 11794/19990 [23:46<16:32,  8.26it/s]

[11800] Геокодируем адрес: Космонавтов пр-т 35, Санкт-Петербург

Геокодирование:  59%|█████▉    | 11801/19990 [23:47<20:33,  6.64it/s]

[11806] Геокодируем адрес: Большевиков пр-т 2М, Санкт-Петербург

Геокодирование:  59%|█████▉    | 11807/19990 [23:50<31:02,  4.39it/s]

[11817] Геокодируем адрес: Пушкин Сапёрная ул 53, Санкт-Петербург

Геокодирование:  59%|█████▉    | 11818/19990 [23:51<23:11,  5.87it/s]

[11818] Геокодируем адрес: Шушары Московское ш 258к2, Санкт-Петербург

Геокодирование:  59%|█████▉    | 11819/19990 [23:52<30:03,  4.53it/s]

[11819] Геокодируем адрес: Петергоф Демьяна Бедного ул, Санкт-Петербург

Геокодирование:  59%|█████▉    | 11820/19990 [23:54<47:54,  2.84it/s]

[11820] Геокодируем адрес: Лиговский пр-т 271, Санкт-Петербург

Геокодирование:  59%|█████▉    | 11821/19990 [23:56<1:01:28,  2.21it/s]

Автосохранение после 11820 строк...
[11822] Геокодируем адрес: Лиговский пр-т 107, Санкт-Петербург

Геокодирование:  59%|█████▉    | 11823/19990 [23:57<1:06:27,  2.05it/s]

[11827] Геокодируем адрес: Дачный пр-т 7к2, Санкт-Петербург

Геокодирование:  59%|█████▉    | 11828/19990 [23:58<51:00,  2.67it/s]

[11832] Геокодируем адрес: Шушары Московское ш 258к2, Санкт-Петербург

Геокодирование:  59%|█████▉    | 11833/19990 [23:59<38:46,  3.51it/s]

[11833] Геокодируем адрес: Шушары Московское ш 258к2, Санкт-Петербург

Геокодирование:  59%|█████▉    | 11834/19990 [24:00<47:55,  2.84it/s]

[11835] Геокодируем адрес: Ветеранов пр-т 122, Санкт-Петербург

Геокодирование:  59%|█████▉    | 11836/19990 [24:02<1:11:13,  1.91it/s]

[11843] Геокодируем адрес: Московский пр-т 15, Санкт-Петербург

Геокодирование:  59%|█████▉    | 11851/19990 [24:03<26:39,  5.09it/s]

Автосохранение после 11850 строк...
[11851] Геокодируем адрес: 2-ой Муринский пр-т, Санкт-Петербург

RateLimiter caught an error, retrying (0/2 tries). Called with (*('2-ой Муринский пр-т, Санкт-Петербург',), **{}).
Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connection.py", line 516, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1374, in getresponse
    response.begin()
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1278, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1134, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 367, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=2-%D0%BE%D0%B9+%D0%9C%D1%83%D1%80%D0%B8%D0%BD%D1%81%D0%BA%D0%B8%D0%B9+%D0%BF%D1%80-%D1%82%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 482, in _request
    resp = self.session.get(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=2-%D0%BE%D0%B9+%D0%9C%D1%83%D1%80%D0%B8%D0%BD%D1%81%D0%BA%D0%B8%D0%B9+%D0%BF%D1%80-%D1%82%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\extra\rate_limiter.py", line 136, in _retries_gen
    yield i  # Run the function.
    ^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\extra\rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\geocoders\nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\geocoders\base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 472, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 494, in _request
    raise GeocoderUnavailable(message)
geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=2-%D0%BE%D0%B9+%D0%9C%D1%83%D1%80%D0%B8%D0%BD%D1%81%D0%BA%D0%B8%D0%B9+%D0%BF%D1%80-%D1%82%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))
RateLimiter caught an error, retrying (1/2 tries). Called with (*('2-ой Муринский пр-т, Санкт-Петербург',), **{}).
Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connection.py", line 516, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1374, in getresponse
    response.begin()
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1278, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1134, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 367, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=2-%D0%BE%D0%B9+%D0%9C%D1%83%D1%80%D0%B8%D0%BD%D1%81%D0%BA%D0%B8%D0%B9+%D0%BF%D1%80-%D1%82%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 482, in _request
    resp = self.session.get(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=2-%D0%BE%D0%B9+%D0%9C%D1%83%D1%80%D0%B8%D0%BD%D1%81%D0%BA%D0%B8%D0%B9+%D0%BF%D1%80-%D1%82%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\extra\rate_limiter.py", line 136, in _retries_gen
    yield i  # Run the function.
    ^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\extra\rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\geocoders\nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\geocoders\base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 472, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 494, in _request
    raise GeocoderUnavailable(message)
geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=2-%D0%BE%D0%B9+%D0%9C%D1%83%D1%80%D0%B8%D0%BD%D1%81%D0%BA%D0%B8%D0%B9+%D0%BF%D1%80-%D1%82%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))
Геокодирование:  59%|█████▉    | 11852/19990 [24:21<3:32:15,  1.56s/it]

[11852] Геокодируем адрес: 2-ой Муринский пр-т, Санкт-Петербург

RateLimiter caught an error, retrying (0/2 tries). Called with (*('2-ой Муринский пр-т, Санкт-Петербург',), **{}).
Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connection.py", line 516, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1374, in getresponse
    response.begin()
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1278, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1134, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 367, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=2-%D0%BE%D0%B9+%D0%9C%D1%83%D1%80%D0%B8%D0%BD%D1%81%D0%BA%D0%B8%D0%B9+%D0%BF%D1%80-%D1%82%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 482, in _request
    resp = self.session.get(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=2-%D0%BE%D0%B9+%D0%9C%D1%83%D1%80%D0%B8%D0%BD%D1%81%D0%BA%D0%B8%D0%B9+%D0%BF%D1%80-%D1%82%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\extra\rate_limiter.py", line 136, in _retries_gen
    yield i  # Run the function.
    ^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\extra\rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\geocoders\nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\geocoders\base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 472, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 494, in _request
    raise GeocoderUnavailable(message)
geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=2-%D0%BE%D0%B9+%D0%9C%D1%83%D1%80%D0%B8%D0%BD%D1%81%D0%BA%D0%B8%D0%B9+%D0%BF%D1%80-%D1%82%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))
RateLimiter caught an error, retrying (1/2 tries). Called with (*('2-ой Муринский пр-т, Санкт-Петербург',), **{}).
Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connection.py", line 516, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1374, in getresponse
    response.begin()
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1278, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1134, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 367, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=2-%D0%BE%D0%B9+%D0%9C%D1%83%D1%80%D0%B8%D0%BD%D1%81%D0%BA%D0%B8%D0%B9+%D0%BF%D1%80-%D1%82%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 482, in _request
    resp = self.session.get(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=2-%D0%BE%D0%B9+%D0%9C%D1%83%D1%80%D0%B8%D0%BD%D1%81%D0%BA%D0%B8%D0%B9+%D0%BF%D1%80-%D1%82%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\extra\rate_limiter.py", line 136, in _retries_gen
    yield i  # Run the function.
    ^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\extra\rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\geocoders\nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\geocoders\base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 472, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 494, in _request
    raise GeocoderUnavailable(message)
geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=2-%D0%BE%D0%B9+%D0%9C%D1%83%D1%80%D0%B8%D0%BD%D1%81%D0%BA%D0%B8%D0%B9+%D0%BF%D1%80-%D1%82%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))
Геокодирование:  59%|█████▉    | 11853/19990 [24:39<7:09:58,  3.17s/it]

[11854] Геокодируем адрес: Петергоф Ропшинское ш, Санкт-Петербург

Геокодирование:  59%|█████▉    | 11855/19990 [24:40<5:56:56,  2.63s/it]

[11855] Геокодируем адрес: Сестрорецк Коннолахтинская дор, Санкт-Петербург

Геокодирование:  59%|█████▉    | 11857/19990 [24:41<4:48:04,  2.13s/it]

[11858] Геокодируем адрес: Ветеранов пр-т 122, Санкт-Петербург

RateLimiter caught an error, retrying (0/2 tries). Called with (*('Ветеранов пр-т 122, Санкт-Петербург',), **{}).
Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connection.py", line 516, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1374, in getresponse
    response.begin()
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1278, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1134, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 367, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=%D0%92%D0%B5%D1%82%D0%B5%D1%80%D0%B0%D0%BD%D0%BE%D0%B2+%D0%BF%D1%80-%D1%82+122%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 482, in _request
    resp = self.session.get(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=%D0%92%D0%B5%D1%82%D0%B5%D1%80%D0%B0%D0%BD%D0%BE%D0%B2+%D0%BF%D1%80-%D1%82+122%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\extra\rate_limiter.py", line 136, in _retries_gen
    yield i  # Run the function.
    ^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\extra\rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\geocoders\nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\geocoders\base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 472, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 494, in _request
    raise GeocoderUnavailable(message)
geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=%D0%92%D0%B5%D1%82%D0%B5%D1%80%D0%B0%D0%BD%D0%BE%D0%B2+%D0%BF%D1%80-%D1%82+122%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))
RateLimiter caught an error, retrying (1/2 tries). Called with (*('Ветеранов пр-т 122, Санкт-Петербург',), **{}).
Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connection.py", line 516, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1374, in getresponse
    response.begin()
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1278, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1134, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 367, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=%D0%92%D0%B5%D1%82%D0%B5%D1%80%D0%B0%D0%BD%D0%BE%D0%B2+%D0%BF%D1%80-%D1%82+122%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 482, in _request
    resp = self.session.get(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=%D0%92%D0%B5%D1%82%D0%B5%D1%80%D0%B0%D0%BD%D0%BE%D0%B2+%D0%BF%D1%80-%D1%82+122%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\extra\rate_limiter.py", line 136, in _retries_gen
    yield i  # Run the function.
    ^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\extra\rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\geocoders\nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\geocoders\base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 472, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 494, in _request
    raise GeocoderUnavailable(message)
geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=%D0%92%D0%B5%D1%82%D0%B5%D1%80%D0%B0%D0%BD%D0%BE%D0%B2+%D0%BF%D1%80-%D1%82+122%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))
RateLimiter swallowed an error after 2 retries. Called with (*('Ветеранов пр-т 122, Санкт-Петербург',), **{}).
Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connection.py", line 516, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1374, in getresponse
    response.begin()
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1278, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1134, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 367, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

[11867] Геокодируем адрес: Ветеранов пр-т 122, Санкт-Петербург

RateLimiter caught an error, retrying (0/2 tries). Called with (*('Ветеранов пр-т 122, Санкт-Петербург',), **{}).
Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connection.py", line 516, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1374, in getresponse
    response.begin()
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1278, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1134, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 367, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=%D0%92%D0%B5%D1%82%D0%B5%D1%80%D0%B0%D0%BD%D0%BE%D0%B2+%D0%BF%D1%80-%D1%82+122%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 482, in _request
    resp = self.session.get(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=%D0%92%D0%B5%D1%82%D0%B5%D1%80%D0%B0%D0%BD%D0%BE%D0%B2+%D0%BF%D1%80-%D1%82+122%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\extra\rate_limiter.py", line 136, in _retries_gen
    yield i  # Run the function.
    ^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\extra\rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\geocoders\nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\geocoders\base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 472, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 494, in _request
    raise GeocoderUnavailable(message)
geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=%D0%92%D0%B5%D1%82%D0%B5%D1%80%D0%B0%D0%BD%D0%BE%D0%B2+%D0%BF%D1%80-%D1%82+122%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))
RateLimiter caught an error, retrying (1/2 tries). Called with (*('Ветеранов пр-т 122, Санкт-Петербург',), **{}).
Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connection.py", line 516, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1374, in getresponse
    response.begin()
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1278, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1134, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 367, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=%D0%92%D0%B5%D1%82%D0%B5%D1%80%D0%B0%D0%BD%D0%BE%D0%B2+%D0%BF%D1%80-%D1%82+122%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 482, in _request
    resp = self.session.get(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=%D0%92%D0%B5%D1%82%D0%B5%D1%80%D0%B0%D0%BD%D0%BE%D0%B2+%D0%BF%D1%80-%D1%82+122%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\extra\rate_limiter.py", line 136, in _retries_gen
    yield i  # Run the function.
    ^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\extra\rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\geocoders\nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\geocoders\base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 472, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 494, in _request
    raise GeocoderUnavailable(message)
geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=%D0%92%D0%B5%D1%82%D0%B5%D1%80%D0%B0%D0%BD%D0%BE%D0%B2+%D0%BF%D1%80-%D1%82+122%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))
Геокодирование:  59%|█████▉    | 11868/19990 [25:20<6:28:44,  2.87s/it]

[11873] Геокодируем адрес: Энгельса пр-т 100/2, Санкт-Петербург

Геокодирование:  59%|█████▉    | 11874/19990 [25:22<4:20:43,  1.93s/it]

[11875] Геокодируем адрес: Приморский пр-т 51/2, Санкт-Петербург

Геокодирование:  59%|█████▉    | 11876/19990 [25:23<3:51:14,  1.71s/it]

[11878] Геокодируем адрес: Шушары Петербургское ш, Санкт-Петербург

Геокодирование:  59%|█████▉    | 11881/19990 [25:24<2:31:38,  1.12s/it]

Автосохранение после 11880 строк...
[11881] Геокодируем адрес: Александровская Кузьминское ш, Санкт-Петербург

Геокодирование:  59%|█████▉    | 11882/19990 [25:25<2:26:53,  1.09s/it]

[11883] Геокодируем адрес: Казанской ул 46, Санкт-Петербург

Геокодирование:  59%|█████▉    | 11884/19990 [25:26<2:06:50,  1.07it/s]

[11884] Геокодируем адрес: Кронштадт Посадская ул 17/14, Санкт-Петербург

Геокодирование:  59%|█████▉    | 11885/19990 [25:27<2:09:45,  1.04it/s]

[11887] Геокодируем адрес: Петергоф Демьяна Бедного ул, Санкт-Петербург

Геокодирование:  59%|█████▉    | 11888/19990 [25:28<1:33:56,  1.44it/s]

[11888] Геокодируем адрес: Институтский пр-т 3к3, Санкт-Петербург

Геокодирование:  59%|█████▉    | 11889/19990 [25:29<1:41:47,  1.33it/s]

[11890] Геокодируем адрес: Петергоф Никольская ул 10, Санкт-Петербург

Геокодирование:  59%|█████▉    | 11891/19990 [25:30<1:31:40,  1.47it/s]

[11907] Геокодируем адрес: Пушкин Гумилёвская ул 13к1, Санкт-Петербург

Геокодирование:  60%|█████▉    | 11911/19990 [25:31<21:51,  6.16it/s]

Автосохранение после 11910 строк...
[11919] Геокодируем адрес: Бакунина ул 19-25, Санкт-Петербург

Геокодирование:  60%|█████▉    | 11920/19990 [25:32<18:29,  7.27it/s]

[11924] Геокодируем адрес: Кубинская ул 75к2Б, Санкт-Петербург

Геокодирование:  60%|█████▉    | 11925/19990 [25:33<19:26,  6.91it/s]

[11925] Геокодируем адрес: Заневский пр-т 42, Санкт-Петербург

Геокодирование:  60%|█████▉    | 11926/19990 [25:34<28:33,  4.71it/s]

[11929] Геокодируем адрес: Ушаково, Санкт-Петербург

Геокодирование:  60%|█████▉    | 11930/19990 [25:35<28:43,  4.68it/s]

[11932] Геокодируем адрес: Ленинский пр-т 123/2, Санкт-Петербург

Геокодирование:  60%|█████▉    | 11933/19990 [25:36<35:24,  3.79it/s]

[11933] Геокодируем адрес: Пушкин Красносельское ш 15А, Санкт-Петербург

Геокодирование:  60%|█████▉    | 11941/19990 [25:37<23:32,  5.70it/s]

Автосохранение после 11940 строк...
[11942] Геокодируем адрес: Светлановский пр-т 47, Санкт-Петербург

Геокодирование:  60%|█████▉    | 11943/19990 [25:38<28:23,  4.72it/s]

[11951] Геокодируем адрес: Авиаконструкторов пр-т 4к1, Санкт-Петербург

Геокодирование:  60%|█████▉    | 11952/19990 [25:39<21:17,  6.29it/s]

[11954] Геокодируем адрес: Авиаконструкторов пр-т 4к1, Санкт-Петербург

Геокодирование:  60%|█████▉    | 11955/19990 [25:40<25:52,  5.18it/s]

[11955] Геокодируем адрес: Колпино Тверская ул 54, Санкт-Петербург

Геокодирование:  60%|█████▉    | 11956/19990 [25:41<34:27,  3.89it/s]

[11959] Геокодируем адрес: Меншиковский пр-т 13, Санкт-Петербург

Геокодирование:  60%|█████▉    | 11960/19990 [25:42<35:06,  3.81it/s]

[11962] Геокодируем адрес: Красное Село Спирина ул 14к1, Санкт-Петербург

Геокодирование:  60%|█████▉    | 11963/19990 [25:43<39:13,  3.41it/s]

[11967] Геокодируем адрес: Шушары Школьная ул 15, Санкт-Петербург

Геокодирование:  60%|█████▉    | 11971/19990 [25:44<26:09,  5.11it/s]

Автосохранение после 11970 строк...
[11973] Геокодируем адрес: Парголово Тихоокеанская ул 14к2, Санкт-Петербург

Геокодирование:  60%|█████▉    | 11974/19990 [25:45<28:01,  4.77it/s]

[11980] Геокодируем адрес: Дачный пр-т 31к2, Санкт-Петербург

Геокодирование:  60%|█████▉    | 11981/19990 [25:46<24:00,  5.56it/s]

[11987] Геокодируем адрес: Кондратьевский пр-т 70к1, Санкт-Петербург

Геокодирование:  60%|█████▉    | 11988/19990 [25:47<21:55,  6.08it/s]

[11988] Геокодируем адрес: Светлановский пр-т 101, Санкт-Петербург

Геокодирование:  60%|█████▉    | 11989/19990 [25:48<32:02,  4.16it/s]

[11989] Геокодируем адрес: Ветеранов пр-т 143к1, Санкт-Петербург

Геокодирование:  60%|█████▉    | 11990/19990 [25:49<40:14,  3.31it/s]

[11992] Геокодируем адрес: Кронштадт Посадская ул 17/14, Санкт-Петербург

Геокодирование:  60%|█████▉    | 11993/19990 [25:50<42:20,  3.15it/s]

[11998] Геокодируем адрес: Шушары Новгородский пр-т 6к2, Санкт-Петербург

Геокодирование:  60%|██████    | 11999/19990 [25:51<33:05,  4.03it/s]

[11999] Геокодируем адрес: Комендантский пр-т 12к1, Санкт-Петербург

Геокодирование:  60%|██████    | 12001/19990 [25:52<39:24,  3.38it/s]

Автосохранение после 12000 строк...
[12003] Геокодируем адрес: Парголово Приозерское ш 16к1, Санкт-Петербург

Геокодирование:  60%|██████    | 12004/19990 [25:53<39:25,  3.38it/s]

[12006] Геокодируем адрес: Парголово Тихоокеанская ул, Санкт-Петербург

Геокодирование:  60%|██████    | 12007/19990 [25:54<39:41,  3.35it/s]

[12015] Геокодируем адрес: Товарищеский пр-т 4к3, Санкт-Петербург

Геокодирование:  60%|██████    | 12016/19990 [25:55<25:53,  5.13it/s]

[12019] Геокодируем адрес: Петергоф Ропшинское ш, Санкт-Петербург

Геокодирование:  60%|██████    | 12020/19990 [25:57<36:31,  3.64it/s]

[12022] Геокодируем адрес: Металлострой Богайчука ул, Санкт-Петербург

Геокодирование:  60%|██████    | 12023/19990 [25:58<37:42,  3.52it/s]

[12026] Геокодируем адрес: Малый Васильевского острова пр-т, Санкт-Петербург

Геокодирование:  60%|██████    | 12027/19990 [25:59<37:43,  3.52it/s]

[12029] Геокодируем адрес: Парголово Юкковское ш, Санкт-Петербург

Геокодирование:  60%|██████    | 12031/19990 [26:00<36:17,  3.66it/s]

Автосохранение после 12030 строк...
[12040] Геокодируем адрес: Энгельса пр-т 139/21, Санкт-Петербург

Геокодирование:  60%|██████    | 12041/19990 [26:01<23:32,  5.63it/s]

[12050] Геокодируем адрес: Народного Ополчения пр-т 175, Санкт-Петербург

Геокодирование:  60%|██████    | 12051/19990 [26:02<17:55,  7.38it/s]

[12051] Геокодируем адрес: Невский пр-т 39, Санкт-Петербург

Геокодирование:  60%|██████    | 12061/19990 [26:03<14:55,  8.85it/s]

Автосохранение после 12060 строк...
[12069] Геокодируем адрес: Колпино Вокзальная ул 14, Санкт-Петербург

Геокодирование:  60%|██████    | 12070/19990 [26:04<13:26,  9.82it/s]

[12078] Геокодируем адрес: Петергоф Демьяна Бедного ул, Санкт-Петербург

Геокодирование:  60%|██████    | 12079/19990 [26:05<13:19,  9.89it/s]

[12081] Геокодируем адрес: Петергоф Демьяна Бедного ул, Санкт-Петербург

Геокодирование:  60%|██████    | 12082/19990 [26:06<17:58,  7.33it/s]

[12084] Геокодируем адрес: Петергоф Демьяна Бедного ул, Санкт-Петербург

Геокодирование:  60%|██████    | 12085/19990 [26:07<22:15,  5.92it/s]

[12085] Геокодируем адрес: Павловск Мичурина пер, Санкт-Петербург

Геокодирование:  60%|██████    | 12086/19990 [26:08<30:41,  4.29it/s]

[12086] Геокодируем адрес: Луначарского пр-т 100, Санкт-Петербург

Геокодирование:  60%|██████    | 12087/19990 [26:09<42:52,  3.07it/s]

[12090] Геокодируем адрес: Шушары Школьная ул 17, Санкт-Петербург

Геокодирование:  60%|██████    | 12091/19990 [26:10<39:43,  3.31it/s]

Автосохранение после 12090 строк...
[12092] Геокодируем адрес: Греческий пр-т 27/2, Санкт-Петербург

Геокодирование:  60%|██████    | 12093/19990 [26:11<44:20,  2.97it/s]

[12093] Геокодируем адрес: Греческий пр-т 27/2, Санкт-Петербург

Геокодирование:  61%|██████    | 12094/19990 [26:12<54:32,  2.41it/s]

[12096] Геокодируем адрес: Морская наб 17литГ, Санкт-Петербург

Геокодирование:  61%|██████    | 12097/19990 [26:13<48:01,  2.74it/s]

[12099] Геокодируем адрес: Маршала Блюхера пр-т 57к2, Санкт-Петербург

Геокодирование:  61%|██████    | 12100/19990 [26:14<48:14,  2.73it/s]

[12107] Геокодируем адрес: Шушары Школьная ул 22, Санкт-Петербург

Геокодирование:  61%|██████    | 12108/19990 [26:15<30:52,  4.26it/s]

[12111] Геокодируем адрес: Среднеохтинский пр-т 27/16, Санкт-Петербург

Геокодирование:  61%|██████    | 12112/19990 [26:16<31:54,  4.11it/s]

[12113] Геокодируем адрес: Петергоф Санкт-Петербургский пр-т, Санкт-Петербург

Геокодирование:  61%|██████    | 12121/19990 [26:17<20:55,  6.27it/s]

Автосохранение после 12120 строк...
[12123] Геокодируем адрес: Суворовский пр-т 62, Санкт-Петербург

Геокодирование:  61%|██████    | 12124/19990 [26:19<35:06,  3.73it/s]

[12129] Геокодируем адрес: Литейный пр-т 54, Санкт-Петербург

Геокодирование:  61%|██████    | 12130/19990 [26:20<29:42,  4.41it/s]

[12134] Геокодируем адрес: Красное Село Юных Пионеров ул 15, Санкт-Петербург

Геокодирование:  61%|██████    | 12135/19990 [26:21<29:38,  4.42it/s]

[12140] Геокодируем адрес: Юрия Гагарина  пр-т 21, Санкт-Петербург

Геокодирование:  61%|██████    | 12141/19990 [26:22<27:12,  4.81it/s]

[12141] Геокодируем адрес: Юрия Гагарина  пр-т 27, Санкт-Петербург

Геокодирование:  61%|██████    | 12142/19990 [26:23<35:15,  3.71it/s]

[12142] Геокодируем адрес: Просвещения пр-т 21/139, Санкт-Петербург

Геокодирование:  61%|██████    | 12143/19990 [26:24<43:54,  2.98it/s]

[12144] Геокодируем адрес: Юрия Гагарина  пр-т 27, Санкт-Петербург

Геокодирование:  61%|██████    | 12145/19990 [26:25<49:01,  2.67it/s]

[12150] Геокодируем адрес: Новочеркасский пр-т 57к1, Санкт-Петербург

Геокодирование:  61%|██████    | 12151/19990 [26:26<34:28,  3.79it/s]

Автосохранение после 12150 строк...
[12154] Геокодируем адрес: Меншиковский пр-т 15к2, Санкт-Петербург

Геокодирование:  61%|██████    | 12155/19990 [26:27<32:18,  4.04it/s]

[12157] Геокодируем адрес: Сиреневый б-р 23к1, Санкт-Петербург

Геокодирование:  61%|██████    | 12158/19990 [26:28<36:06,  3.61it/s]

[12162] Геокодируем адрес: Маршала Блюхера ул 57к2, Санкт-Петербург

Геокодирование:  61%|██████    | 12163/19990 [26:29<32:13,  4.05it/s]

[12164] Геокодируем адрес: Среднеохтинский пр-т 23, Санкт-Петербург

Геокодирование:  61%|██████    | 12165/19990 [26:30<38:41,  3.37it/s]

[12166] Геокодируем адрес: Олеко Дундича ул 36к1Б, Санкт-Петербург

Геокодирование:  61%|██████    | 12167/19990 [26:31<41:36,  3.13it/s]

[12169] Геокодируем адрес: Дальневосточный пр-т 10, Санкт-Петербург

Геокодирование:  61%|██████    | 12170/19990 [26:32<45:06,  2.89it/s]

[12170] Геокодируем адрес: Маршала Жукова пр-т 30к2, Санкт-Петербург

Геокодирование:  61%|██████    | 12171/19990 [26:33<53:55,  2.42it/s]

[12171] Геокодируем адрес: Большевиков пр-т 9к3, Санкт-Петербург

Геокодирование:  61%|██████    | 12172/19990 [26:34<1:04:39,  2.02it/s]

[12175] Геокодируем адрес: Среднеохтинский пр-т 23, Санкт-Петербург

Геокодирование:  61%|██████    | 12176/19990 [26:35<51:17,  2.54it/s]

[12176] Геокодируем адрес: Пушкин Сапёрная ул 46, Санкт-Петербург

Геокодирование:  61%|██████    | 12177/19990 [26:36<1:01:56,  2.10it/s]

[12179] Геокодируем адрес: Авиационна ул 40, Санкт-Петербург

Геокодирование:  61%|██████    | 12181/19990 [26:37<48:53,  2.66it/s]

Автосохранение после 12180 строк...
[12185] Геокодируем адрес: Петергоф Демьяна Бедного ул, Санкт-Петербург

Геокодирование:  61%|██████    | 12186/19990 [26:38<34:24,  3.78it/s]

[12187] Геокодируем адрес: Петергоф Демьяна Бедного ул, Санкт-Петербург

Геокодирование:  61%|██████    | 12188/19990 [26:39<41:20,  3.14it/s]

[12188] Геокодируем адрес: Большой Смоленский пр-т 15, Санкт-Петербург

Геокодирование:  61%|██████    | 12189/19990 [26:40<58:33,  2.22it/s]

[12190] Геокодируем адрес: Большой Смоленский пр-т 15к2, Санкт-Петербург

Геокодирование:  61%|██████    | 12191/19990 [26:41<56:41,  2.29it/s]

[12207] Геокодируем адрес: Шушары Вишерская ул 24, Санкт-Петербург

Геокодирование:  61%|██████    | 12241/19990 [26:43<05:22, 24.00it/s]

Автосохранение после 12210 строк...
Автосохранение после 12240 строк...
[12242] Геокодируем адрес: Дачный пр-т 36к5, Санкт-Петербург

Геокодирование:  61%|██████▏   | 12249/19990 [26:43<06:24, 20.13it/s]

[12254] Геокодируем адрес: Пятилеток пр-т 14/1, Санкт-Петербург

Геокодирование:  61%|██████▏   | 12255/19990 [26:44<09:43, 13.26it/s]

[12258] Геокодируем адрес: Брюсова ул 8, Санкт-Петербург

Геокодирование:  61%|██████▏   | 12259/19990 [26:45<12:45, 10.09it/s]

[12264] Геокодируем адрес: Пятилеток пр-т 14/1, Санкт-Петербург

Геокодирование:  61%|██████▏   | 12265/19990 [26:46<15:25,  8.34it/s]

[12267] Геокодируем адрес: Большевиков пр-т 9/1, Санкт-Петербург

Геокодирование:  61%|██████▏   | 12271/19990 [26:47<17:11,  7.49it/s]

Автосохранение после 12270 строк...
[12272] Геокодируем адрес: Цымбалина ул 52, Санкт-Петербург

Геокодирование:  61%|██████▏   | 12273/19990 [26:48<20:24,  6.30it/s]

[12279] Геокодируем адрес: Маршала Блюхера ул 7/2, Санкт-Петербург

Геокодирование:  61%|██████▏   | 12280/19990 [26:49<21:49,  5.89it/s]

[12297] Геокодируем адрес: Волковский пр-т 116, Санкт-Петербург

Геокодирование:  62%|██████▏   | 12301/19990 [26:51<11:56, 10.73it/s]

Автосохранение после 12300 строк...
[12309] Геокодируем адрес: Морская наб 17литГ, Санкт-Петербург

Геокодирование:  62%|██████▏   | 12310/19990 [26:51<10:44, 11.92it/s]

[12312] Геокодируем адрес: Шушары Школьная ул 15, Санкт-Петербург

Геокодирование:  62%|██████▏   | 12313/19990 [26:52<16:11,  7.90it/s]

[12323] Геокодируем адрес: Королева пр-т 30к1, Санкт-Петербург

Геокодирование:  62%|██████▏   | 12324/19990 [26:53<14:33,  8.77it/s]

[12329] Геокодируем адрес: Новаторов б-р, Санкт-Петербург

Геокодирование:  62%|██████▏   | 12331/19990 [26:54<16:00,  7.97it/s]

Автосохранение после 12330 строк...
[12331] Геокодируем адрес: Нижняя дор, Санкт-Петербург

Геокодирование:  62%|██████▏   | 12332/19990 [26:55<22:19,  5.72it/s]

[12332] Геокодируем адрес: Энергетиков пр-т 32к2, Санкт-Петербург

Геокодирование:  62%|██████▏   | 12333/19990 [26:56<34:03,  3.75it/s]

[12338] Геокодируем адрес: Петергоф Нижняя дор 13А, Санкт-Петербург

Геокодирование:  62%|██████▏   | 12339/19990 [26:57<27:31,  4.63it/s]

[12342] Геокодируем адрес: Петергоф Нижняя дор 13А, Санкт-Петербург

Геокодирование:  62%|██████▏   | 12343/19990 [26:58<28:52,  4.41it/s]

[12345] Геокодируем адрес: Петергоф Нижняя дор 13А, Санкт-Петербург

Геокодирование:  62%|██████▏   | 12346/19990 [26:59<32:06,  3.97it/s]

[12346] Геокодируем адрес: Средний ВО пр-т 39, Санкт-Петербург

Геокодирование:  62%|██████▏   | 12347/19990 [27:00<43:49,  2.91it/s]

[12347] Геокодируем адрес: Науки пр-т 17Б, Санкт-Петербург

Геокодирование:  62%|██████▏   | 12348/19990 [27:01<53:12,  2.39it/s]

[12349] Геокодируем адрес: Богатырский пр-т 51к1, Санкт-Петербург

Геокодирование:  62%|██████▏   | 12350/19990 [27:02<55:11,  2.31it/s]

[12353] Геокодируем адрес: Богатырский пр-т 30к1, Санкт-Петербург

Геокодирование:  62%|██████▏   | 12354/19990 [27:03<44:33,  2.86it/s]

[12354] Геокодируем адрес: Серебристый б-р 5к1, Санкт-Петербург

Геокодирование:  62%|██████▏   | 12361/19990 [27:04<27:38,  4.60it/s]

Автосохранение после 12360 строк...
[12362] Геокодируем адрес: Колпино Машиностроителей ул, Санкт-Петербург

Геокодирование:  62%|██████▏   | 12363/19990 [27:05<32:14,  3.94it/s]

[12364] Геокодируем адрес: Дачный пр-т 83к3, Санкт-Петербург

Геокодирование:  62%|██████▏   | 12365/19990 [27:06<39:51,  3.19it/s]

[12371] Геокодируем адрес: Ветеранов пр-т 11, Санкт-Петербург

Геокодирование:  62%|██████▏   | 12372/19990 [27:08<38:59,  3.26it/s]

[12375] Геокодируем адрес: Шушары Школьная ул 15, Санкт-Петербург

Геокодирование:  62%|██████▏   | 12376/19990 [27:09<35:52,  3.54it/s]

[12382] Геокодируем адрес: Вознесенский пр-т 27, Санкт-Петербург

Геокодирование:  62%|██████▏   | 12383/19990 [27:10<29:21,  4.32it/s]

[12383] Геокодируем адрес: Петергоф Царицынская ул 1, Санкт-Петербург

Геокодирование:  62%|██████▏   | 12384/19990 [27:11<35:50,  3.54it/s]

[12385] Геокодируем адрес: Петергоф Царицынская ул 1, Санкт-Петербург

Геокодирование:  62%|██████▏   | 12391/19990 [27:13<28:40,  4.42it/s]

Автосохранение после 12390 строк...
[12395] Геокодируем адрес: Петергоф, Царицынская ул 1, Санкт-Петербург

Геокодирование:  62%|██████▏   | 12396/19990 [27:13<24:10,  5.24it/s]

[12400] Геокодируем адрес: Пушкин Пушкинская ул 8, Санкт-Петербург

Геокодирование:  62%|██████▏   | 12401/19990 [27:14<25:05,  5.04it/s]

[12407] Геокодируем адрес: Средний ВО пр-т 85, Санкт-Петербург

Геокодирование:  62%|██████▏   | 12408/19990 [27:16<23:09,  5.46it/s]

[12410] Геокодируем адрес: Мечникова пр-т 3, Санкт-Петербург

Геокодирование:  62%|██████▏   | 12411/19990 [27:16<26:19,  4.80it/s]

[12420] Геокодируем адрес: Петергоф Ропшинское ш, Санкт-Петербург

Геокодирование:  62%|██████▏   | 12421/19990 [27:18<19:56,  6.32it/s]

Автосохранение после 12420 строк...
[12421] Геокодируем адрес: Петергоф Ропшинское ш, Санкт-Петербург

Геокодирование:  62%|██████▏   | 12422/19990 [27:19<33:26,  3.77it/s]

[12422] Геокодируем адрес: Коломяги Берёзовая ул, Санкт-Петербург

Геокодирование:  62%|██████▏   | 12423/19990 [27:20<41:25,  3.04it/s]

[12424] Геокодируем адрес: Ломоносов Победы ул, Санкт-Петербург

Геокодирование:  62%|██████▏   | 12425/19990 [27:21<45:31,  2.77it/s]

[12428] Геокодируем адрес: Комендантский пр-т 4, Санкт-Петербург

Геокодирование:  62%|██████▏   | 12429/19990 [27:22<41:30,  3.04it/s]

[12430] Геокодируем адрес: 12 линия ВО, Санкт-Петербург

Геокодирование:  62%|██████▏   | 12431/19990 [27:23<45:16,  2.78it/s]

[12432] Геокодируем адрес: З-я Жерновская ул 3, Санкт-Петербург

Геокодирование:  62%|██████▏   | 12433/19990 [27:25<53:46,  2.34it/s]

[12434] Геокодируем адрес: Ленинский пр-т 53/4, Санкт-Петербург

Геокодирование:  62%|██████▏   | 12435/19990 [27:26<55:13,  2.28it/s]

[12439] Геокодируем адрес: Орлово-Денисовский пр-т, Санкт-Петербург

Геокодирование:  62%|██████▏   | 12440/19990 [27:26<38:05,  3.30it/s]

[12442] Геокодируем адрес: Александрино сад, Санкт-Петербург

Геокодирование:  62%|██████▏   | 12443/19990 [27:27<38:34,  3.26it/s]

[12443] Геокодируем адрес: Богатырский пр-т 51к1, Санкт-Петербург

Геокодирование:  62%|██████▏   | 12444/19990 [27:28<50:11,  2.51it/s]

[12444] Геокодируем адрес: Московский пр-т 57, Санкт-Петербург

Геокодирование:  62%|██████▏   | 12445/19990 [27:30<1:03:14,  1.99it/s]

[12446] Геокодируем адрес: Комендантский пр-т 53к3, Санкт-Петербург

Геокодирование:  62%|██████▏   | 12451/19990 [27:31<34:34,  3.63it/s]

Автосохранение после 12450 строк...
[12455] Геокодируем адрес: Энергетиков пр-т 9к1стр1, Санкт-Петербург

Геокодирование:  62%|██████▏   | 12456/19990 [27:31<27:59,  4.49it/s]

[12470] Геокодируем адрес: Московский пр-т 193, Санкт-Петербург

Геокодирование:  62%|██████▏   | 12471/19990 [27:33<16:47,  7.46it/s]

[12472] Геокодируем адрес: Энтузиастов пр-т 54к3, Санкт-Петербург

Геокодирование:  62%|██████▏   | 12473/19990 [27:33<20:18,  6.17it/s]

[12476] Геокодируем адрес: Королева пр-т 66к1, Санкт-Петербург

Геокодирование:  62%|██████▏   | 12477/19990 [27:34<22:46,  5.50it/s]

[12478] Геокодируем адрес: Королева пр-т 66к1, Санкт-Петербург

Геокодирование:  62%|██████▏   | 12481/19990 [27:36<25:18,  4.95it/s]

Автосохранение после 12480 строк...
[12487] Геокодируем адрес: Суздальский пр-т 107, Санкт-Петербург

Геокодирование:  62%|██████▏   | 12488/19990 [27:37<21:48,  5.73it/s]

[12490] Геокодируем адрес: Богатырский пр-т 51к1, Санкт-Петербург

Геокодирование:  62%|██████▏   | 12491/19990 [27:37<25:29,  4.90it/s]

[12497] Геокодируем адрес: Лесной пр-т 37к4литераД, Санкт-Петербург

Геокодирование:  63%|██████▎   | 12498/19990 [27:38<21:06,  5.92it/s]

[12502] Геокодируем адрес: Маршала Жукова пр-т 45, Санкт-Петербург

Геокодирование:  63%|██████▎   | 12503/19990 [27:40<24:21,  5.12it/s]

[12505] Геокодируем адрес: Лиговский пр-т 47, Санкт-Петербург

Геокодирование:  63%|██████▎   | 12506/19990 [27:40<26:54,  4.64it/s]

[12506] Геокодируем адрес: Авангардная ул 3, Санкт-Петербург

Геокодирование:  63%|██████▎   | 12507/19990 [27:41<34:56,  3.57it/s]

[12508] Геокодируем адрес: nan

Геокодирование:  63%|██████▎   | 12509/19990 [27:42<39:55,  3.12it/s]

[12509] Геокодируем адрес: Лыжный пер 4к3, Санкт-Петербург

Геокодирование:  63%|██████▎   | 12511/19990 [27:44<46:43,  2.67it/s]

Автосохранение после 12510 строк...
[12511] Геокодируем адрес: Просвещения пр-т 53к1, Санкт-Петербург

Геокодирование:  63%|██████▎   | 12512/19990 [27:44<56:03,  2.22it/s]

[12516] Геокодируем адрес: Просвещения пр-т 104, Санкт-Петербург

Геокодирование:  63%|██████▎   | 12517/19990 [27:46<40:35,  3.07it/s]

[12522] Геокодируем адрес: Петергоф Ольгина пруда наб, Санкт-Петербург

Геокодирование:  63%|██████▎   | 12523/19990 [27:46<29:10,  4.26it/s]

[12531] Геокодируем адрес: Большой пр-т 101, Санкт-Петербург

Геокодирование:  63%|██████▎   | 12532/19990 [27:48<24:22,  5.10it/s]

[12533] Геокодируем адрес: nan

Геокодирование:  63%|██████▎   | 12534/19990 [27:48<26:04,  4.77it/s]

[12534] Геокодируем адрес: Цимбалина ул, Санкт-Петербург

Геокодирование:  63%|██████▎   | 12541/19990 [27:50<21:09,  5.87it/s]

Автосохранение после 12540 строк...
[12553] Геокодируем адрес: Большевиков пр-т 3к1, Санкт-Петербург

Геокодирование:  63%|██████▎   | 12554/19990 [27:50<14:13,  8.71it/s]

[12567] Геокодируем адрес: Комендантский пр-т 32к1, Санкт-Петербург

Геокодирование:  63%|██████▎   | 12571/19990 [27:52<10:44, 11.51it/s]

Автосохранение после 12570 строк...
[12571] Геокодируем адрес: Комендантский пр-т 34к1, Санкт-Петербург

Геокодирование:  63%|██████▎   | 12573/19990 [27:52<15:29,  7.98it/s]

[12576] Геокодируем адрес: Шушарская дор, Санкт-Петербург

Геокодирование:  63%|██████▎   | 12577/19990 [27:53<18:29,  6.68it/s]

[12582] Геокодируем адрес: Большой Сампсониевский пр-т 32, Санкт-Петербург

Геокодирование:  63%|██████▎   | 12583/19990 [27:55<21:05,  5.85it/s]

[12597] Геокодируем адрес: Невский пр-т 45к2, Санкт-Петербург

Геокодирование:  63%|██████▎   | 12601/19990 [27:56<11:59, 10.27it/s]

Автосохранение после 12600 строк...
[12603] Геокодируем адрес: Русановская ул 18к3стр1, Санкт-Петербург

Геокодирование:  63%|██████▎   | 12604/19990 [27:56<15:17,  8.05it/s]

[12605] Геокодируем адрес: Ленинский пр-т 72к3, Санкт-Петербург

Геокодирование:  63%|██████▎   | 12606/19990 [27:57<22:02,  5.58it/s]

[12607] Геокодируем адрес: Кондратьевский пр-т 64, Санкт-Петербург

Геокодирование:  63%|██████▎   | 12608/19990 [27:58<28:55,  4.25it/s]

[12610] Геокодируем адрес: Старорусский пр-т 13к1, Санкт-Петербург

Геокодирование:  63%|██████▎   | 12611/19990 [27:59<32:06,  3.83it/s]

[12611] Геокодируем адрес: Юрия Гагарина  пр-т 38к1, Санкт-Петербург

Геокодирование:  63%|██████▎   | 12612/19990 [28:00<41:15,  2.98it/s]

[12613] Геокодируем адрес: Парголово Санаторный пер 7, Санкт-Петербург

Геокодирование:  63%|██████▎   | 12614/19990 [28:01<46:03,  2.67it/s]

[12615] Геокодируем адрес: пискаревский пр-т 117, Санкт-Петербург

Геокодирование:  63%|██████▎   | 12616/19990 [28:03<52:01,  2.36it/s]

[12620] Геокодируем адрес: Шушары Чудновская ул, Санкт-Петербург

Геокодирование:  63%|██████▎   | 12621/19990 [28:03<37:11,  3.30it/s]

[12622] Геокодируем адрес: Петергоф Эрлеровский б-р 10, Санкт-Петербург

Геокодирование:  63%|██████▎   | 12631/19990 [28:05<21:09,  5.79it/s]

Автосохранение после 12630 строк...
[12641] Геокодируем адрес: Петергоф Ропшинское ш, Санкт-Петербург

Геокодирование:  63%|██████▎   | 12642/19990 [28:05<14:15,  8.59it/s]

[12646] Геокодируем адрес: Владимирский пр-т 1/47, Санкт-Петербург

Геокодирование:  63%|██████▎   | 12647/19990 [28:07<17:36,  6.95it/s]

[12647] Геокодируем адрес: Лиговский пр-т 99, Санкт-Петербург

Геокодирование:  63%|██████▎   | 12649/19990 [28:08<22:47,  5.37it/s]

[12652] Геокодируем адрес: Московский пр-т 73к5, Санкт-Петербург

Геокодирование:  63%|██████▎   | 12653/19990 [28:08<24:13,  5.05it/s]

[12653] Геокодируем адрес: Светлановский пр-т 113к2, Санкт-Петербург

Геокодирование:  63%|██████▎   | 12654/19990 [28:09<32:11,  3.80it/s]

[12656] Геокодируем адрес: Комендантский пр-т 32к1, Санкт-Петербург

Геокодирование:  63%|██████▎   | 12657/19990 [28:11<35:50,  3.41it/s]

[12657] Геокодируем адрес: Народного Ополчения пр-т 173, Санкт-Петербург

Геокодирование:  63%|██████▎   | 12658/19990 [28:12<47:37,  2.57it/s]

[12658] Геокодируем адрес: Шушары Ростовская ул 13-15, Санкт-Петербург

Геокодирование:  63%|██████▎   | 12659/19990 [28:13<56:25,  2.17it/s]

[12659] Геокодируем адрес: Загородный пр-т 18, Санкт-Петербург

Геокодирование:  63%|██████▎   | 12661/19990 [28:15<1:14:39,  1.64it/s]

Автосохранение после 12660 строк...
[12663] Геокодируем адрес: Большевиков пр-т 25, Санкт-Петербург

Геокодирование:  63%|██████▎   | 12664/19990 [28:15<54:54,  2.22it/s]

[12664] Геокодируем адрес: Лиговский пр-т 89/20, Санкт-Петербург

Геокодирование:  63%|██████▎   | 12665/19990 [28:17<1:08:12,  1.79it/s]

[12682] Геокодируем адрес: Шушары Московское ш 29, Санкт-Петербург

Геокодирование:  63%|██████▎   | 12683/19990 [28:17<17:27,  6.98it/s]

[12683] Геокодируем адрес: Маршала Жукова пр-т 60к2, Санкт-Петербург

Геокодирование:  63%|██████▎   | 12691/19990 [28:19<15:43,  7.74it/s]

Автосохранение после 12690 строк...
[12691] Геокодируем адрес: Парголово Федора Абрамова ул 23, Санкт-Петербург

Геокодирование:  63%|██████▎   | 12693/19990 [28:19<20:17,  5.99it/s]

[12693] Геокодируем адрес: Маршала Жукова пр-т 60к2, Санкт-Петербург
[12694] Геокодируем адрес: Маршала Жукова пр-т 60к2, Санкт-Петербург

Геокодирование:  64%|██████▎   | 12695/19990 [28:21<36:45,  3.31it/s]

[12697] Геокодируем адрес: Металлистов пр-т 90, Санкт-Петербург

Геокодирование:  64%|██████▎   | 12698/19990 [28:23<38:16,  3.18it/s]

[12704] Геокодируем адрес: Шушары Валдайская ул 11, Санкт-Петербург

Геокодирование:  64%|██████▎   | 12705/19990 [28:23<27:49,  4.36it/s]

[12705] Геокодируем адрес: Ветеранов пр-т 34, Санкт-Петербург

Геокодирование:  64%|██████▎   | 12706/19990 [28:25<37:22,  3.25it/s]

[12706] Геокодируем адрес: Ленинский пр-т 137к4, Санкт-Петербург

Геокодирование:  64%|██████▎   | 12707/19990 [28:25<44:53,  2.70it/s]

[12707] Геокодируем адрес: Королева пр-т 3, Санкт-Петербург

Геокодирование:  64%|██████▎   | 12708/19990 [28:27<57:30,  2.11it/s]

[12714] Геокодируем адрес: Непокорённых пр-т 74, Санкт-Петербург

Геокодирование:  64%|██████▎   | 12715/19990 [28:28<33:52,  3.58it/s]

[12716] Геокодируем адрес: Шушары Центральная ул 14к4, Санкт-Петербург

Геокодирование:  64%|██████▎   | 12721/19990 [28:29<25:49,  4.69it/s]

Автосохранение после 12720 строк...
[12729] Геокодируем адрес: Суворовский пр-т 25/16, Санкт-Петербург

Геокодирование:  64%|██████▎   | 12730/19990 [28:30<19:26,  6.23it/s]

[12733] Геокодируем адрес: Светлановский пр-т 77, Санкт-Петербург

Геокодирование:  64%|██████▎   | 12734/19990 [28:31<21:44,  5.56it/s]

[12735] Геокодируем адрес: Петергоф Ропшинское ш, Санкт-Петербург

Геокодирование:  64%|██████▎   | 12736/19990 [28:31<27:00,  4.48it/s]

[12737] Геокодируем адрес: Пятилеток пр-т 2к2, Санкт-Петербург

Геокодирование:  64%|██████▎   | 12738/19990 [28:32<33:20,  3.62it/s]

[12743] Геокодируем адрес: Петергоф Ропшинское ш, Санкт-Петербург

Геокодирование:  64%|██████▍   | 12744/19990 [28:33<27:10,  4.44it/s]

[12746] Геокодируем адрес: Лиговский пр-т 16, Санкт-Петербург

Геокодирование:  64%|██████▍   | 12751/19990 [28:35<23:10,  5.20it/s]

Автосохранение после 12750 строк...
[12752] Геокодируем адрес: Евгения Шварца ул 7, Санкт-Петербург

Геокодирование:  64%|██████▍   | 12753/19990 [28:35<27:27,  4.39it/s]

[12765] Геокодируем адрес: 23-я линия ВО, Санкт-Петербург

Геокодирование:  64%|██████▍   | 12766/19990 [28:37<18:33,  6.49it/s]

[12767] Геокодируем адрес: Российский б-р, Санкт-Петербург

Геокодирование:  64%|██████▍   | 12768/19990 [28:38<21:33,  5.58it/s]

[12773] Геокодируем адрес: Авиаконструкторов пр-т 32, Санкт-Петербург

Геокодирование:  64%|██████▍   | 12781/19990 [28:39<14:18,  8.40it/s]

Автосохранение после 12780 строк...
[12786] Геокодируем адрес: Петергоф Санкт-Петербургский пр-т, Санкт-Петербург

Геокодирование:  64%|██████▍   | 12787/19990 [28:40<14:48,  8.10it/s]

[12787] Геокодируем адрес: Светлановский пр-т 117, Санкт-Петербург
[12788] Геокодируем адрес: Славы пр-т 38, Санкт-Петербург

Геокодирование:  64%|██████▍   | 12789/19990 [28:42<29:12,  4.11it/s]

[12793] Геокодируем адрес: Культуры пр-т 15к1, Санкт-Петербург

Геокодирование:  64%|██████▍   | 12794/19990 [28:43<27:00,  4.44it/s]

[12795] Геокодируем адрес: Юрия Гагарина пр-т 14к1, Санкт-Петербург

Геокодирование:  64%|██████▍   | 12796/19990 [28:44<32:37,  3.67it/s]

[12796] Геокодируем адрес: Юрия Гагарина ул 17, Санкт-Петербург

Геокодирование:  64%|██████▍   | 12797/19990 [28:45<40:40,  2.95it/s]

[12798] Геокодируем адрес: Оптиков пр-т 51к1, Санкт-Петербург

Геокодирование:  64%|██████▍   | 12799/19990 [28:47<57:09,  2.10it/s]

[12800] Геокодируем адрес: Культуры пр-т 11/1, Санкт-Петербург

Геокодирование:  64%|██████▍   | 12801/19990 [28:48<59:52,  2.00it/s]

[12803] Геокодируем адрес: Просвещения пр-т 54, Санкт-Петербург

Геокодирование:  64%|██████▍   | 12811/19990 [28:49<26:01,  4.60it/s]

Автосохранение после 12810 строк...
[12812] Геокодируем адрес: Маршала Блюхера ул 7к2, Санкт-Петербург

Геокодирование:  64%|██████▍   | 12813/19990 [28:50<29:51,  4.01it/s]

[12814] Геокодируем адрес: Маршала Блюхера пр-т 7к2, Санкт-Петербург

Геокодирование:  64%|██████▍   | 12815/19990 [28:51<35:47,  3.34it/s]

[12817] Геокодируем адрес: Торики Песочная ул 1, Санкт-Петербург

Геокодирование:  64%|██████▍   | 12818/19990 [28:52<36:27,  3.28it/s]

[12822] Геокодируем адрес: Литейный пр-т 59, Санкт-Петербург

Геокодирование:  64%|██████▍   | 12823/19990 [28:53<31:57,  3.74it/s]

[12823] Геокодируем адрес: Солидарности пр-т 8Бк1, Санкт-Петербург

Геокодирование:  64%|██████▍   | 12824/19990 [28:53<38:51,  3.07it/s]

[12832] Геокодируем адрес: Литейный пр-т 59, Санкт-Петербург

Геокодирование:  64%|██████▍   | 12833/19990 [28:55<25:52,  4.61it/s]

[12833] Геокодируем адрес: Пушкин Алексея Толстого б-р 19, Санкт-Петербург

Геокодирование:  64%|██████▍   | 12834/19990 [28:56<34:05,  3.50it/s]

[12839] Геокодируем адрес: Медиков пр-т 10к1, Санкт-Петербург

Геокодирование:  64%|██████▍   | 12841/19990 [28:57<26:05,  4.57it/s]

Автосохранение после 12840 строк...
[12841] Геокодируем адрес: Парголово Николая Рубцова ул, Санкт-Петербург

Геокодирование:  64%|██████▍   | 12842/19990 [28:58<33:38,  3.54it/s]

[12843] Геокодируем адрес: Муринская дор, Санкт-Петербург

Геокодирование:  64%|██████▍   | 12844/19990 [28:59<39:50,  2.99it/s]

[12845] Геокодируем адрес: Петергоф Юты Бондаровской ул, Санкт-Петербург

Геокодирование:  64%|██████▍   | 12846/19990 [29:00<45:04,  2.64it/s]

[12850] Геокодируем адрес: Лиговский пр-т 89/20, Санкт-Петербург

Геокодирование:  64%|██████▍   | 12851/19990 [29:01<36:57,  3.22it/s]

[12859] Геокодируем адрес: Новгородский пр-т 7, Санкт-Петербург

Геокодирование:  64%|██████▍   | 12860/19990 [29:02<23:40,  5.02it/s]

[12860] Геокодируем адрес: Комендантский пр-т 32к1, Санкт-Петербург

Геокодирование:  64%|██████▍   | 12861/19990 [29:03<30:23,  3.91it/s]

[12864] Геокодируем адрес: Шлиссельбургский пр-т 20к2, Санкт-Петербург

Геокодирование:  64%|██████▍   | 12865/19990 [29:04<30:12,  3.93it/s]

[12865] Геокодируем адрес: Космонавтов пр-т 61к1, Санкт-Петербург

Геокодирование:  64%|██████▍   | 12866/19990 [29:05<38:51,  3.06it/s]

[12868] Геокодируем адрес: Комендантский пр-т 4, Санкт-Петербург

Геокодирование:  64%|██████▍   | 12871/19990 [29:06<33:11,  3.57it/s]

Автосохранение после 12870 строк...
[12873] Геокодируем адрес: Петергоф Ропшинское ш, Санкт-Петербург

Геокодирование:  64%|██████▍   | 12874/19990 [29:07<31:53,  3.72it/s]

[12875] Геокодируем адрес: Петергоф Ропшинское ш, Санкт-Петербург

Геокодирование:  64%|██████▍   | 12876/19990 [29:08<38:26,  3.08it/s]

[12885] Геокодируем адрес: Шушары Вишерская ул 24, Санкт-Петербург

Геокодирование:  64%|██████▍   | 12886/19990 [29:09<22:12,  5.33it/s]

[12892] Геокодируем адрес: Октябрьский б-р 22А, Санкт-Петербург

Геокодирование:  64%|██████▍   | 12893/19990 [29:10<20:52,  5.67it/s]

[12893] Геокодируем адрес: Металлострой Железнодорожная ул 17, Санкт-Петербург

Геокодирование:  65%|██████▍   | 12894/19990 [29:11<26:32,  4.46it/s]

[12898] Геокодируем адрес: Богатырский пр-т 51к1, Санкт-Петербург

Геокодирование:  65%|██████▍   | 12901/19990 [29:12<23:08,  5.10it/s]

Автосохранение после 12900 строк...
[12901] Геокодируем адрес: Павловск Александрова Дача сад, Санкт-Петербург

Геокодирование:  65%|██████▍   | 12902/19990 [29:13<30:38,  3.86it/s]

[12902] Геокодируем адрес: Космонавтов пр-т 65к2, Санкт-Петербург

Геокодирование:  65%|██████▍   | 12903/19990 [29:14<42:01,  2.81it/s]

[12903] Геокодируем адрес: Сестрорецк Пушкинская ул, Санкт-Петербург

Геокодирование:  65%|██████▍   | 12904/19990 [29:15<53:05,  2.22it/s]

[12906] Геокодируем адрес: 12-я линия пер 37А, Санкт-Петербург

Геокодирование:  65%|██████▍   | 12907/19990 [29:16<54:26,  2.17it/s]

[12909] Геокодируем адрес: Обуховской Обороны пр-т 39, Санкт-Петербург

Геокодирование:  65%|██████▍   | 12910/19990 [29:17<46:27,  2.54it/s]

[12915] Геокодируем адрес: Решетова ул 13к2, Санкт-Петербург

Геокодирование:  65%|██████▍   | 12916/19990 [29:18<30:44,  3.83it/s]

[12917] Геокодируем адрес: Художников пр-т 18к1, Санкт-Петербург

Геокодирование:  65%|██████▍   | 12918/19990 [29:19<36:25,  3.24it/s]

[12919] Геокодируем адрес: Пушкин Артиллерийская ул 6, Санкт-Петербург

Геокодирование:  65%|██████▍   | 12920/19990 [29:20<42:04,  2.80it/s]

[12920] Геокодируем адрес: Луначарского пр-т 70к2, Санкт-Петербург

Геокодирование:  65%|██████▍   | 12921/19990 [29:21<51:16,  2.30it/s]

[12921] Геокодируем адрес: Дунайский пр-т 7/7, Санкт-Петербург

Геокодирование:  65%|██████▍   | 12922/19990 [29:22<1:05:20,  1.80it/s]

[12924] Геокодируем адрес: 2-й Муринский пр-т 7, Санкт-Петербург

Геокодирование:  65%|██████▍   | 12925/19990 [29:24<1:14:38,  1.58it/s]

[12925] Геокодируем адрес: Дачный пр-т 29к3, Санкт-Петербург

Геокодирование:  65%|██████▍   | 12926/19990 [29:25<1:17:18,  1.52it/s]

[12927] Геокодируем адрес: Дачный пр-т 29к3, Санкт-Петербург

Геокодирование:  65%|██████▍   | 12931/19990 [29:26<44:19,  2.65it/s]

Автосохранение после 12930 строк...
[12941] Геокодируем адрес: Комендантский пр-т 53к3, Санкт-Петербург

Геокодирование:  65%|██████▍   | 12942/19990 [29:27<19:30,  6.02it/s]

[12944] Геокодируем адрес: Дунайский пр-т 7/7, Санкт-Петербург

Геокодирование:  65%|██████▍   | 12945/19990 [29:28<25:29,  4.61it/s]

[12945] Геокодируем адрес: Просвещения пр-т 34, Санкт-Петербург

Геокодирование:  65%|██████▍   | 12946/19990 [29:29<33:05,  3.55it/s]

[12949] Геокодируем адрес: Брестский б-р, Санкт-Петербург

Геокодирование:  65%|██████▍   | 12950/19990 [29:30<30:44,  3.82it/s]

[12950] Геокодируем адрес: Комендантский пр-т 59к1, Санкт-Петербург

Геокодирование:  65%|██████▍   | 12951/19990 [29:31<39:28,  2.97it/s]

[12952] Геокодируем адрес: Комендантский пр-т 59к1, Санкт-Петербург

Геокодирование:  65%|██████▍   | 12953/19990 [29:32<44:04,  2.66it/s]

[12954] Геокодируем адрес: Дунайский пр-т 7/7, Санкт-Петербург

Геокодирование:  65%|██████▍   | 12961/19990 [29:33<25:45,  4.55it/s]

Автосохранение после 12960 строк...
[12967] Геокодируем адрес: 3Советская ул 12, Санкт-Петербург

Геокодирование:  65%|██████▍   | 12968/19990 [29:34<18:33,  6.31it/s]

[12976] Геокодируем адрес: Солидарности пр-т 27к1, Санкт-Петербург

Геокодирование:  65%|██████▍   | 12977/19990 [29:36<22:44,  5.14it/s]

[12980] Геокодируем адрес: Большевиков пр-т 45, Санкт-Петербург

Геокодирование:  65%|██████▍   | 12991/19990 [29:37<14:29,  8.05it/s]

Автосохранение после 12990 строк...
[12998] Геокодируем адрес: Парголово Заречная ул, Санкт-Петербург

Геокодирование:  65%|██████▌   | 12999/19990 [29:38<12:58,  8.98it/s]

[13004] Геокодируем адрес: Петергоф Демьяна Бедного ул, Санкт-Петербург

Геокодирование:  65%|██████▌   | 13005/19990 [29:39<14:35,  7.98it/s]

[13005] Геокодируем адрес: Московский пр-т, Санкт-Петербург

Геокодирование:  65%|██████▌   | 13007/19990 [29:40<20:00,  5.82it/s]

[13009] Геокодируем адрес: Зеленогорск Мира ул, Санкт-Петербург

Геокодирование:  65%|██████▌   | 13010/19990 [29:41<23:11,  5.02it/s]

[13012] Геокодируем адрес: Дыбенко ул 8к1, Санкт-Петербург

Геокодирование:  65%|██████▌   | 13021/19990 [29:42<15:50,  7.34it/s]

Автосохранение после 13020 строк...
[13024] Геокодируем адрес: Обуховской Обороны пр-т 35, Санкт-Петербург

Геокодирование:  65%|██████▌   | 13025/19990 [29:43<18:50,  6.16it/s]

[13036] Геокодируем адрес: Московский пр-т, Санкт-Петербург

Геокодирование:  65%|██████▌   | 13037/19990 [29:44<13:27,  8.61it/s]

[13040] Геокодируем адрес: Дачный пр-т 29к3, Санкт-Петербург

Геокодирование:  65%|██████▌   | 13051/19990 [29:45<10:44, 10.77it/s]

Автосохранение после 13050 строк...
[13058] Геокодируем адрес: Наставников пр-т 25к3, Санкт-Петербург

Геокодирование:  65%|██████▌   | 13059/19990 [29:46<10:39, 10.84it/s]

[13059] Геокодируем адрес: Комендантский пр-т 55к1, Санкт-Петербург
[13060] Геокодируем адрес: Комендантский пр-т 55к1, Санкт-Петербург

Геокодирование:  65%|██████▌   | 13062/19990 [29:48<20:17,  5.69it/s]

[13066] Геокодируем адрес: Петергоф Озерковая ул, Санкт-Петербург

Геокодирование:  65%|██████▌   | 13067/19990 [29:49<20:43,  5.57it/s]

[13068] Геокодируем адрес: Просвещения пр-т 72, Санкт-Петербург

Геокодирование:  65%|██████▌   | 13069/19990 [29:50<26:34,  4.34it/s]

[13069] Геокодируем адрес: Петергоф Блан-Менильская ул, Санкт-Петербург

Геокодирование:  65%|██████▌   | 13081/19990 [29:51<14:59,  7.68it/s]

Автосохранение после 13080 строк...
[13082] Геокодируем адрес: Комендантский пр-т 61, Санкт-Петербург

Геокодирование:  65%|██████▌   | 13084/19990 [29:52<19:18,  5.96it/s]

[13085] Геокодируем адрес: Большая Конюшенная ул 4-6-8Б, Санкт-Петербург
[13086] Геокодируем адрес: Рижский пр-т 50Б, Санкт-Петербург

Геокодирование:  65%|██████▌   | 13087/19990 [29:54<30:19,  3.79it/s]

[13092] Геокодируем адрес: Комендантский пр-т 34к1, Санкт-Петербург

Геокодирование:  65%|██████▌   | 13093/19990 [29:55<26:17,  4.37it/s]

[13097] Геокодируем адрес: Маршала Блюхера пр-т 8к1, Санкт-Петербург

Геокодирование:  66%|██████▌   | 13098/19990 [29:56<25:44,  4.46it/s]

[13099] Геокодируем адрес: Лиговский пр-т 47, Санкт-Петербург

Геокодирование:  66%|██████▌   | 13100/19990 [29:57<30:21,  3.78it/s]

[13100] Геокодируем адрес: Тореза пр-т 33, Санкт-Петербург

Геокодирование:  66%|██████▌   | 13101/19990 [29:58<38:24,  2.99it/s]

[13103] Геокодируем адрес: Разведчика б-р 12к1, Санкт-Петербург

Геокодирование:  66%|██████▌   | 13104/19990 [29:59<37:31,  3.06it/s]

[13107] Геокодируем адрес: Дачный пр-т 38к3, Санкт-Петербург

Геокодирование:  66%|██████▌   | 13108/19990 [30:00<34:00,  3.37it/s]

[13109] Геокодируем адрес: Непокоренных пр-т 49к2, Санкт-Петербург

Геокодирование:  66%|██████▌   | 13110/19990 [30:01<38:13,  3.00it/s]

[13110] Геокодируем адрес: Просвещения пр-т 14к2, Санкт-Петербург

Геокодирование:  66%|██████▌   | 13111/19990 [30:02<50:29,  2.27it/s]

Автосохранение после 13110 строк...
[13112] Геокодируем адрес: Лиговский пр-т 228, Санкт-Петербург

Геокодирование:  66%|██████▌   | 13113/19990 [30:03<52:31,  2.18it/s]

[13115] Геокодируем адрес: Лиговский пр-т 47, Санкт-Петербург

Геокодирование:  66%|██████▌   | 13116/19990 [30:04<46:15,  2.48it/s]

[13120] Геокодируем адрес: Народного Ополчения пр-т 31, Санкт-Петербург

Геокодирование:  66%|██████▌   | 13121/19990 [30:05<36:01,  3.18it/s]

[13121] Геокодируем адрес: Витебский пр-т 85к3, Санкт-Петербург

Геокодирование:  66%|██████▌   | 13122/19990 [30:06<43:10,  2.65it/s]

[13122] Геокодируем адрес: Красное село Огородная ул, Санкт-Петербург

Геокодирование:  66%|██████▌   | 13123/19990 [30:07<56:09,  2.04it/s]

[13130] Геокодируем адрес: Павловск Садовая ул 5, Санкт-Петербург

Геокодирование:  66%|██████▌   | 13131/19990 [30:08<29:25,  3.89it/s]

[13133] Геокодируем адрес: Обуховской Обороны пр-т 110к1, Санкт-Петербург

Геокодирование:  66%|██████▌   | 13134/19990 [30:09<30:55,  3.69it/s]

[13137] Геокодируем адрес: Комендантский пр-т 66к3, Санкт-Петербург

Геокодирование:  66%|██████▌   | 13138/19990 [30:10<30:13,  3.78it/s]

[13139] Геокодируем адрес: Костромской пр-т 10, Санкт-Петербург

Геокодирование:  66%|██████▌   | 13141/19990 [30:11<34:22,  3.32it/s]

Автосохранение после 13140 строк...
[13142] Геокодируем адрес: Старо-Петергофский пр-т 37, Санкт-Петербург

Геокодирование:  66%|██████▌   | 13143/19990 [30:12<37:52,  3.01it/s]

[13149] Геокодируем адрес: Космонавтов пр-т 52, Санкт-Петербург

Геокодирование:  66%|██████▌   | 13150/19990 [30:13<26:15,  4.34it/s]

[13152] Геокодируем адрес: Загребский б-р 35/28 литера А, Санкт-Петербург

Геокодирование:  66%|██████▌   | 13153/19990 [30:14<29:05,  3.92it/s]

[13155] Геокодируем адрес: Лиговский пр-т 47, Санкт-Петербург

Геокодирование:  66%|██████▌   | 13156/19990 [30:15<30:45,  3.70it/s]

[13160] Геокодируем адрес: 2 Муринский пр-т 37, Санкт-Петербург

Геокодирование:  66%|██████▌   | 13161/19990 [30:16<27:58,  4.07it/s]

[13161] Геокодируем адрес: Комендантский пр-т 55к1, Санкт-Петербург

Геокодирование:  66%|██████▌   | 13162/19990 [30:17<34:44,  3.28it/s]

[13163] Геокодируем адрес: Заневский пр-т 47, Санкт-Петербург

Геокодирование:  66%|██████▌   | 13171/19990 [30:18<20:58,  5.42it/s]

Автосохранение после 13170 строк...
[13174] Геокодируем адрес: Петергоф Ропшинское ш 8АН, Санкт-Петербург

Геокодирование:  66%|██████▌   | 13175/19990 [30:19<20:51,  5.45it/s]

[13176] Геокодируем адрес: Петергоф Ропшинское ш 8АН, Санкт-Петербург

Геокодирование:  66%|██████▌   | 13177/19990 [30:20<27:13,  4.17it/s]

[13182] Геокодируем адрес: Петергоф Ропшинское ш 8, Санкт-Петербург

Геокодирование:  66%|██████▌   | 13183/19990 [30:21<24:03,  4.71it/s]

[13183] Геокодируем адрес: Петергоф Ропшинское ш, Санкт-Петербург

Геокодирование:  66%|██████▌   | 13184/19990 [30:22<31:51,  3.56it/s]

[13187] Геокодируем адрес: Суворовский пр-т 56, Санкт-Петербург

Геокодирование:  66%|██████▌   | 13188/19990 [30:23<33:08,  3.42it/s]

[13193] Геокодируем адрес: Петергоф Ропшинское ш 8АН, Санкт-Петербург

Геокодирование:  66%|██████▌   | 13201/19990 [30:24<16:02,  7.05it/s]

Автосохранение после 13200 строк...
[13201] Геокодируем адрес: Жерновская ул 17, 19, 6, Санкт-Петербург

Геокодирование:  66%|██████▌   | 13203/19990 [30:25<20:08,  5.62it/s]

[13203] Геокодируем адрес: Энергетиков пр-т 66к1, Санкт-Петербург

Геокодирование:  66%|██████▌   | 13205/19990 [30:26<26:12,  4.32it/s]

[13208] Геокодируем адрес: Новоизмайловский пр-т 53, Санкт-Петербург

Геокодирование:  66%|██████▌   | 13209/19990 [30:27<27:27,  4.11it/s]

[13212] Геокодируем адрес: Обуховской Обороны пр-т 110к1, Санкт-Петербург

Геокодирование:  66%|██████▌   | 13231/19990 [30:28<09:28, 11.90it/s]

Автосохранение после 13230 строк...
[13236] Геокодируем адрес: Энгельса пр-т 138к2, Санкт-Петербург

Геокодирование:  66%|██████▌   | 13237/19990 [30:29<10:59, 10.23it/s]

[13238] Геокодируем адрес: Кондратьевский пр-т 40к14, Санкт-Петербург

Геокодирование:  66%|██████▌   | 13240/19990 [30:30<14:47,  7.61it/s]

[13245] Геокодируем адрес: Сестрорецк Воскова ул 1, Санкт-Петербург

Геокодирование:  66%|██████▋   | 13246/19990 [30:31<16:17,  6.90it/s]

[13248] Геокодируем адрес: Муринская дор, Санкт-Петербург

Геокодирование:  66%|██████▋   | 13249/19990 [30:32<19:33,  5.74it/s]

[13250] Геокодируем адрес: Культуры пр-т 15к7, Санкт-Петербург

Геокодирование:  66%|██████▋   | 13251/19990 [30:33<25:02,  4.49it/s]

[13257] Геокодируем адрес: Стачек пр-т 14/2, Санкт-Петербург

Геокодирование:  66%|██████▋   | 13258/19990 [30:34<22:01,  5.09it/s]

[13258] Геокодируем адрес: 17-я пер 60, Санкт-Петербург

Геокодирование:  66%|██████▋   | 13259/19990 [30:36<42:04,  2.67it/s]

[13260] Геокодируем адрес: Солидарности пр-т 21к3, Санкт-Петербург

Геокодирование:  66%|██████▋   | 13261/19990 [30:37<42:46,  2.62it/s]

Автосохранение после 13260 строк...
[13262] Геокодируем адрес: Полевая Сабировская ул 45к1стр1, Санкт-Петербург

Геокодирование:  66%|██████▋   | 13263/19990 [30:38<42:36,  2.63it/s]

[13268] Геокодируем адрес: Мориса Тореза пр-т 35к1, Санкт-Петербург

Геокодирование:  66%|██████▋   | 13269/19990 [30:39<32:42,  3.43it/s]

[13272] Геокодируем адрес: Кондратьевский пр-т 83к1, Санкт-Петербург

Геокодирование:  66%|██████▋   | 13273/19990 [30:40<30:22,  3.68it/s]

[13279] Геокодируем адрес: Тореза пр-т 28, Санкт-Петербург

Геокодирование:  66%|██████▋   | 13280/19990 [30:41<24:57,  4.48it/s]

[13280] Геокодируем адрес: Рижский пр-т 72, Санкт-Петербург

Геокодирование:  66%|██████▋   | 13281/19990 [30:42<32:12,  3.47it/s]

[13281] Геокодируем адрес: Зеленогорск Курортная ул 29В, Санкт-Петербург

Геокодирование:  66%|██████▋   | 13291/19990 [30:43<18:17,  6.11it/s]

Автосохранение после 13290 строк...
[13311] Геокодируем адрес: Маршала Блюхера пр-т 9к1, Санкт-Петербург

Геокодирование:  67%|██████▋   | 13312/19990 [30:44<08:55, 12.46it/s]

[13315] Геокодируем адрес: Шушарская дор, Санкт-Петербург

Геокодирование:  67%|██████▋   | 13316/19990 [30:45<11:28,  9.69it/s]

[13318] Геокодируем адрес: Косая линия ВО, Санкт-Петербург

Геокодирование:  67%|██████▋   | 13319/19990 [30:46<15:05,  7.37it/s]

[13319] Геокодируем адрес: Славы пр-т 8, Санкт-Петербург
[13320] Геокодируем адрес: Славы пр-т 2к1, Санкт-Петербург

Геокодирование:  67%|██████▋   | 13321/19990 [30:48<28:19,  3.92it/s]

Автосохранение после 13320 строк...
[13328] Геокодируем адрес: Шушары Школьная ул 8, Санкт-Петербург

Геокодирование:  67%|██████▋   | 13329/19990 [30:49<21:00,  5.28it/s]

[13329] Геокодируем адрес: Шушары Вишерская ул 22, Санкт-Петербург

Геокодирование:  67%|██████▋   | 13330/19990 [30:50<27:04,  4.10it/s]

[13331] Геокодируем адрес: Маршала Жукова пр-т 30к2, Санкт-Петербург

Геокодирование:  67%|██████▋   | 13332/19990 [30:51<31:48,  3.49it/s]

[13336] Геокодируем адрес: Науки пр-т 17к6, Санкт-Петербург

Геокодирование:  67%|██████▋   | 13337/19990 [30:52<28:00,  3.96it/s]

[13344] Геокодируем адрес: Колпино Вознесенское ш 55, Санкт-Петербург

Геокодирование:  67%|██████▋   | 13345/19990 [30:53<22:00,  5.03it/s]

[13345] Геокодируем адрес: Стачек пр-т 90, Санкт-Петербург

Геокодирование:  67%|██████▋   | 13351/19990 [30:54<19:59,  5.53it/s]

Автосохранение после 13350 строк...
[13352] Геокодируем адрес: Испытателей пр-т 6/3, Санкт-Петербург

Геокодирование:  67%|██████▋   | 13353/19990 [30:55<24:42,  4.48it/s]

[13353] Геокодируем адрес: реки Охты наб, Санкт-Петербург

Геокодирование:  67%|██████▋   | 13354/19990 [30:56<31:24,  3.52it/s]

[13356] Геокодируем адрес: Шушары Школьная ул 18, Санкт-Петербург

Геокодирование:  67%|██████▋   | 13357/19990 [30:57<34:28,  3.21it/s]

[13357] Геокодируем адрес: Шушары Школьная ул 18, Санкт-Петербург

Геокодирование:  67%|██████▋   | 13358/19990 [30:58<44:32,  2.48it/s]

[13361] Геокодируем адрес: Славы пр-т 18, Санкт-Петербург

Геокодирование:  67%|██████▋   | 13362/19990 [30:59<38:19,  2.88it/s]

[13367] Геокодируем адрес: Композиторов ул 13, 17к1, Санкт-Петербург

Геокодирование:  67%|██████▋   | 13368/19990 [31:00<27:45,  3.98it/s]

[13374] Геокодируем адрес: Спирина ул 18литА, Санкт-Петербург

Геокодирование:  67%|██████▋   | 13375/19990 [31:01<21:41,  5.08it/s]

[13376] Геокодируем адрес: Советский пр-т 39к1, Санкт-Петербург

Геокодирование:  67%|██████▋   | 13377/19990 [31:02<27:27,  4.01it/s]

[13379] Геокодируем адрес: Раевского пр-т 18, Санкт-Петербург

Геокодирование:  67%|██████▋   | 13381/19990 [31:03<29:11,  3.77it/s]

Автосохранение после 13380 строк...
[13382] Геокодируем адрес: Пушкин Пушкинская ул 8, Санкт-Петербург

Геокодирование:  67%|██████▋   | 13383/19990 [31:04<33:03,  3.33it/s]

[13383] Геокодируем адрес: Пролетарский пр-т 20, Санкт-Петербург

Геокодирование:  67%|██████▋   | 13384/19990 [31:05<44:52,  2.45it/s]

[13391] Геокодируем адрес: Спирина ул 18литА, Санкт-Петербург

Геокодирование:  67%|██████▋   | 13392/19990 [31:06<23:43,  4.64it/s]

[13392] Геокодируем адрес: Спирина ул 18литА, Санкт-Петербург

Геокодирование:  67%|██████▋   | 13393/19990 [31:07<32:18,  3.40it/s]

[13393] Геокодируем адрес: Обуховской Обороны пр-т 33к2, Санкт-Петербург

Геокодирование:  67%|██████▋   | 13394/19990 [31:08<42:59,  2.56it/s]

[13394] Геокодируем адрес: Обуховской Обороны пр-т 33к2, Санкт-Петербург

Геокодирование:  67%|██████▋   | 13395/19990 [31:09<53:42,  2.05it/s]

[13400] Геокодируем адрес: Шушары Ростовская ул 5к3, Санкт-Петербург

Геокодирование:  67%|██████▋   | 13411/19990 [31:10<15:23,  7.12it/s]

Автосохранение после 13410 строк...
[13411] Геокодируем адрес: Бакунина пр-т 7, Санкт-Петербург

Геокодирование:  67%|██████▋   | 13414/19990 [31:11<18:42,  5.86it/s]

[13423] Геокодируем адрес: Приморский пр-т 137/1, Санкт-Петербург

Геокодирование:  67%|██████▋   | 13424/19990 [31:12<15:34,  7.03it/s]

[13432] Геокодируем адрес: Александровская Редкое Кузьмино ул, Санкт-Петербург

Геокодирование:  67%|██████▋   | 13433/19990 [31:13<13:15,  8.24it/s]

[13433] Геокодируем адрес: Энгельса пр-т 139/21А, Санкт-Петербург
[13434] Геокодируем адрес: Московский пр-т 192-194, Санкт-Петербург

Геокодирование:  67%|██████▋   | 13435/19990 [31:15<25:26,  4.29it/s]

[13436] Геокодируем адрес: Кронштадт Ленина пр-т, Санкт-Петербург

Геокодирование:  67%|██████▋   | 13437/19990 [31:16<27:21,  3.99it/s]

[13437] Геокодируем адрес: Александровская Соболевская ул, Санкт-Петербург

Геокодирование:  67%|██████▋   | 13441/19990 [31:17<26:18,  4.15it/s]

Автосохранение после 13440 строк...
[13441] Геокодируем адрес: Науки пр-т 79к2Б, Санкт-Петербург

Геокодирование:  67%|██████▋   | 13442/19990 [31:18<34:17,  3.18it/s]

[13455] Геокодируем адрес: Юрия Гагарина пр-т 17, Санкт-Петербург

Геокодирование:  67%|██████▋   | 13456/19990 [31:19<17:21,  6.28it/s]

[13464] Геокодируем адрес: Шушары Школьная ул 15стр1, Санкт-Петербург

Геокодирование:  67%|██████▋   | 13465/19990 [31:20<13:57,  7.80it/s]

[13465] Геокодируем адрес: Шушары Школьная ул 15стр1, Санкт-Петербург

Геокодирование:  67%|██████▋   | 13466/19990 [31:21<19:15,  5.65it/s]

[13466] Геокодируем адрес: Шушары Школьная ул 15стр1, Санкт-Петербург

Геокодирование:  67%|██████▋   | 13467/19990 [31:22<26:13,  4.15it/s]

[13468] Геокодируем адрес: Лиговский пр-т 117, Санкт-Петербург

Геокодирование:  67%|██████▋   | 13469/19990 [31:23<33:04,  3.29it/s]

[13469] Геокодируем адрес: Просвещения пр-т 21/139, Санкт-Петербург

Геокодирование:  67%|██████▋   | 13471/19990 [31:24<38:03,  2.86it/s]

Автосохранение после 13470 строк...
[13475] Геокодируем адрес: Коломяги Новоколомяжский пр-т 16/8, Санкт-Петербург

Геокодирование:  67%|██████▋   | 13476/19990 [31:25<27:31,  3.94it/s]

[13476] Геокодируем адрес: Парголово Валерия Гаврилина ул, Санкт-Петербург

Геокодирование:  67%|██████▋   | 13477/19990 [31:26<36:04,  3.01it/s]

[13477] Геокодируем адрес: Коломяги Новоколомяжский пр-т, Санкт-Петербург

Геокодирование:  67%|██████▋   | 13478/19990 [31:28<1:04:06,  1.69it/s]

[13478] Геокодируем адрес: Искровский пр-т 35/38, Санкт-Петербург

Геокодирование:  67%|██████▋   | 13479/19990 [31:29<1:15:02,  1.45it/s]

[13483] Геокодируем адрес: Культуры пр-т 29к1, Санкт-Петербург

Геокодирование:  67%|██████▋   | 13484/19990 [31:30<44:06,  2.46it/s]

[13486] Геокодируем адрес: Дальневосточный пр-т 60, Санкт-Петербург

Геокодирование:  67%|██████▋   | 13487/19990 [31:31<42:48,  2.53it/s]

[13487] Геокодируем адрес: Дальневосточный пр-т 10к1, Санкт-Петербург

Геокодирование:  67%|██████▋   | 13488/19990 [31:32<49:08,  2.20it/s]

[13490] Геокодируем адрес: Загородный пр-т 6, Санкт-Петербург

Геокодирование:  67%|██████▋   | 13491/19990 [31:33<45:14,  2.39it/s]

[13491] Геокодируем адрес: Приморский пр-т 25, Санкт-Петербург

Геокодирование:  67%|██████▋   | 13492/19990 [31:34<55:01,  1.97it/s]

[13494] Геокодируем адрес: Луначарского пр-т 27к1, Санкт-Петербург

Геокодирование:  68%|██████▊   | 13495/19990 [31:35<47:13,  2.29it/s]

[13498] Геокодируем адрес: Загородный пр-т 6, Санкт-Петербург

Геокодирование:  68%|██████▊   | 13499/19990 [31:36<39:56,  2.71it/s]

[13500] Геокодируем адрес: Индустриальный пр-т 40, Санкт-Петербург

Геокодирование:  68%|██████▊   | 13501/19990 [31:37<44:39,  2.42it/s]

Автосохранение после 13500 строк...
[13511] Геокодируем адрес: Комендантский пр-т 25к1, Санкт-Петербург

Геокодирование:  68%|██████▊   | 13512/19990 [31:38<20:14,  5.33it/s]

[13514] Геокодируем адрес: Центральный парк культуры и отдыха сад, Санкт-Петербург

Геокодирование:  68%|██████▊   | 13515/19990 [31:39<24:28,  4.41it/s]

[13516] Геокодируем адрес: Солидарности пр-т 13к2, Санкт-Петербург

Геокодирование:  68%|██████▊   | 13517/19990 [31:40<27:23,  3.94it/s]

[13520] Геокодируем адрес: Сосновка сад, Санкт-Петербург

Геокодирование:  68%|██████▊   | 13521/19990 [31:41<27:22,  3.94it/s]

[13524] Геокодируем адрес: Финляндский пр-т 1, Санкт-Петербург

Геокодирование:  68%|██████▊   | 13525/19990 [31:42<28:05,  3.84it/s]

[13526] Геокодируем адрес: Товарищеский пр-т 28/1, Санкт-Петербург

Геокодирование:  68%|██████▊   | 13527/19990 [31:43<32:48,  3.28it/s]

[13530] Геокодируем адрес: Греческий пр-т 12, Санкт-Петербург

Геокодирование:  68%|██████▊   | 13531/19990 [31:44<32:02,  3.36it/s]

Автосохранение после 13530 строк...
[13532] Геокодируем адрес: Металлистов пр-т 21к1, Санкт-Петербург

Геокодирование:  68%|██████▊   | 13533/19990 [31:45<34:32,  3.12it/s]

[13533] Геокодируем адрес: Культуры пр-т, Санкт-Петербург

Геокодирование:  68%|██████▊   | 13534/19990 [31:46<43:13,  2.49it/s]

[13534] Геокодируем адрес: Культуры пр-т, Санкт-Петербург

Геокодирование:  68%|██████▊   | 13535/19990 [31:47<53:05,  2.03it/s]

[13536] Геокодируем адрес: Славы пр-т 40к1, Санкт-Петербург

Геокодирование:  68%|██████▊   | 13537/19990 [31:48<52:01,  2.07it/s]

[13543] Геокодируем адрес: Юнтоловский пр-т 49к4, Санкт-Петербург

Геокодирование:  68%|██████▊   | 13544/19990 [31:49<30:03,  3.57it/s]

[13547] Геокодируем адрес: Суворовский пр-т 62, Санкт-Петербург

Геокодирование:  68%|██████▊   | 13548/19990 [31:50<30:02,  3.57it/s]

[13554] Геокодируем адрес: Сизова пр-т 25, Санкт-Петербург

Геокодирование:  68%|██████▊   | 13555/19990 [31:51<23:17,  4.60it/s]

[13555] Геокодируем адрес: Загребский б-р 37/27, Санкт-Петербург

Геокодирование:  68%|██████▊   | 13556/19990 [31:52<30:45,  3.49it/s]

[13558] Геокодируем адрес: Обуховской Обороны пр-т 9, Санкт-Петербург

Геокодирование:  68%|██████▊   | 13559/19990 [31:53<32:15,  3.32it/s]

[13559] Геокодируем адрес: Металлострой Богайчука ул, Санкт-Петербург

Геокодирование:  68%|██████▊   | 13561/19990 [31:54<35:34,  3.01it/s]

Автосохранение после 13560 строк...
[13561] Геокодируем адрес: Металлострой Железнодорожная ул, Санкт-Петербург

Геокодирование:  68%|██████▊   | 13562/19990 [31:55<44:43,  2.40it/s]

[13563] Геокодируем адрес: Обуховской Обороны пр-т 33, Санкт-Петербург

Геокодирование:  68%|██████▊   | 13564/19990 [31:56<49:50,  2.15it/s]

[13567] Геокодируем адрес: Маршала Блюхера пр-т 21к2, Санкт-Петербург

Геокодирование:  68%|██████▊   | 13568/19990 [31:57<38:50,  2.76it/s]

[13568] Геокодируем адрес: Пушкин Московская ул, Санкт-Петербург

Геокодирование:  68%|██████▊   | 13569/19990 [31:58<47:04,  2.27it/s]

[13569] Геокодируем адрес: Металлистов пр-т 23к2, Санкт-Петербург

Геокодирование:  68%|██████▊   | 13570/19990 [31:59<56:36,  1.89it/s]

[13570] Геокодируем адрес: Непокоренных пр-т 9к1, Санкт-Петербург

Геокодирование:  68%|██████▊   | 13571/19990 [32:00<1:06:51,  1.60it/s]

[13571] Геокодируем адрес: Металлистов пр-т 25к1, Санкт-Петербург

Геокодирование:  68%|██████▊   | 13572/19990 [32:01<1:17:41,  1.38it/s]

[13573] Геокодируем адрес: Металлистов пр-т 25к1, Санкт-Петербург

Геокодирование:  68%|██████▊   | 13574/19990 [32:02<1:07:49,  1.58it/s]

[13575] Геокодируем адрес: Металлистов пр-т 21к3, Санкт-Петербург

Геокодирование:  68%|██████▊   | 13576/19990 [32:03<1:02:39,  1.71it/s]

[13578] Геокодируем адрес: Стрельна Санкт-Петербургское ш 96, Санкт-Петербург

Геокодирование:  68%|██████▊   | 13579/19990 [32:04<50:51,  2.10it/s]

[13586] Геокодируем адрес: Ленинский пр-т 95к2, Санкт-Петербург

Геокодирование:  68%|██████▊   | 13587/19990 [32:05<27:07,  3.93it/s]

[13587] Геокодируем адрес: Олеко Дундича ул 20к1Б, Санкт-Петербург

Геокодирование:  68%|██████▊   | 13591/19990 [32:06<25:30,  4.18it/s]

Автосохранение после 13590 строк...
[13602] Геокодируем адрес: Пушкин Саперная ул 10, Санкт-Петербург

Геокодирование:  68%|██████▊   | 13603/19990 [32:07<14:57,  7.11it/s]

[13619] Геокодируем адрес: Энтузиастов пр-т 28к3, Санкт-Петербург

Геокодирование:  68%|██████▊   | 13622/19990 [32:08<09:50, 10.79it/s]

Автосохранение после 13620 строк...
[13625] Геокодируем адрес: Поэтический б-р, Санкт-Петербург

Геокодирование:  68%|██████▊   | 13626/19990 [32:09<12:21,  8.58it/s]

[13640] Геокодируем адрес: Шушары Старорусский пр-т 13к1, Санкт-Петербург

Геокодирование:  68%|██████▊   | 13641/19990 [32:10<09:31, 11.11it/s]

[13642] Геокодируем адрес: Металлистов пр-т 25к1, Санкт-Петербург

Геокодирование:  68%|██████▊   | 13643/19990 [32:11<13:31,  7.82it/s]

[13645] Геокодируем адрес: Металлистов пр-т 23к2, Санкт-Петербург

Геокодирование:  68%|██████▊   | 13646/19990 [32:12<16:39,  6.35it/s]

[13646] Геокодируем адрес: Металлистов пр-т 23к2, Санкт-Петербург

Геокодирование:  68%|██████▊   | 13647/19990 [32:13<22:57,  4.61it/s]

[13647] Геокодируем адрес: Металлистов пр-т 23к2, Санкт-Петербург

Геокодирование:  68%|██████▊   | 13648/19990 [32:14<30:18,  3.49it/s]

[13650] Геокодируем адрес: Пушкин Московская ул, Санкт-Петербург

Геокодирование:  68%|██████▊   | 13651/19990 [32:15<33:25,  3.16it/s]

Автосохранение после 13650 строк...
[13651] Геокодируем адрес: Пушкин Московская ул 33, Санкт-Петербург

Геокодирование:  68%|██████▊   | 13652/19990 [32:16<41:29,  2.55it/s]

[13653] Геокодируем адрес: Ленинский пр-т 78к1, Санкт-Петербург

Геокодирование:  68%|██████▊   | 13654/19990 [32:17<43:08,  2.45it/s]

[13656] Геокодируем адрес: Юрия Гагарина пр-т 27, Санкт-Петербург

Геокодирование:  68%|██████▊   | 13657/19990 [32:18<42:21,  2.49it/s]

[13663] Геокодируем адрес: Лиговский пр-т 81, Санкт-Петербург

Геокодирование:  68%|██████▊   | 13664/19990 [32:19<26:48,  3.93it/s]

[13666] Геокодируем адрес: Парголово Тихоокеанская ул 14к1, Санкт-Петербург

Геокодирование:  68%|██████▊   | 13667/19990 [32:20<28:25,  3.71it/s]

[13668] Геокодируем адрес: Парголово Тихоокеанская ул 12к2, Санкт-Петербург

Геокодирование:  68%|██████▊   | 13669/19990 [32:21<32:49,  3.21it/s]

[13671] Геокодируем адрес: Евгения Шварца ул 11к1, Санкт-Петербург

Геокодирование:  68%|██████▊   | 13672/19990 [32:22<34:17,  3.07it/s]

[13672] Геокодируем адрес: Евгения Шварца ул 11к1, Санкт-Петербург

Геокодирование:  68%|██████▊   | 13673/19990 [32:23<42:29,  2.48it/s]

[13673] Геокодируем адрес: Металлострой Богайчука ул, Санкт-Петербург

Геокодирование:  68%|██████▊   | 13674/19990 [32:24<50:21,  2.09it/s]

[13674] Геокодируем адрес: Металлострой Богайчука ул, Санкт-Петербург

Геокодирование:  68%|██████▊   | 13675/19990 [32:25<59:59,  1.75it/s]

[13676] Геокодируем адрес: Металлострой Железнодорожная ул 13, Санкт-Петербург

Геокодирование:  68%|██████▊   | 13677/19990 [32:26<58:48,  1.79it/s]

[13677] Геокодируем адрес: Металлострой Железнодорожная ул 13, Санкт-Петербург

Геокодирование:  68%|██████▊   | 13678/19990 [32:27<1:07:42,  1.55it/s]

[13678] Геокодируем адрес: Витебский пр-т 63, Санкт-Петербург

Геокодирование:  68%|██████▊   | 13679/19990 [32:28<1:19:05,  1.33it/s]

[13680] Геокодируем адрес: Парголово Тихоокеанская ул 12к2, Санкт-Петербург

Геокодирование:  68%|██████▊   | 13681/19990 [32:29<1:07:33,  1.56it/s]

Автосохранение после 13680 строк...
[13681] Геокодируем адрес: Дальневосточный пр-т 25, Санкт-Петербург

Геокодирование:  68%|██████▊   | 13682/19990 [32:30<1:16:33,  1.37it/s]

[13682] Геокодируем адрес: Металлострой Железнодорожная ул 13, Санкт-Петербург

Геокодирование:  68%|██████▊   | 13683/19990 [32:31<1:20:04,  1.31it/s]

[13683] Геокодируем адрес: Пушкин Октябрьский б-р 3, Санкт-Петербург

Геокодирование:  68%|██████▊   | 13684/19990 [32:32<1:32:01,  1.14it/s]

[13687] Геокодируем адрес: Светлановский пр-т 117, Санкт-Петербург

Геокодирование:  68%|██████▊   | 13688/19990 [32:33<52:09,  2.01it/s]

[13688] Геокодируем адрес: Измайловский пр-т 7литЗ, Санкт-Петербург

Геокодирование:  68%|██████▊   | 13689/19990 [32:34<57:54,  1.81it/s]

[13690] Геокодируем адрес: Измайловский пр-т 7, Санкт-Петербург

Геокодирование:  68%|██████▊   | 13691/19990 [32:35<57:37,  1.82it/s]

[13701] Геокодируем адрес: Лиговский пр-т 211, Санкт-Петербург

Геокодирование:  69%|██████▊   | 13711/19990 [32:36<13:40,  7.65it/s]

Автосохранение после 13710 строк...
[13711] Геокодируем адрес: Добролюбова пр-т 8, Санкт-Петербург

Геокодирование:  69%|██████▊   | 13714/19990 [32:37<15:56,  6.56it/s]

[13715] Геокодируем адрес: Маршала Казакова пр-т 40к1, Санкт-Петербург

Геокодирование:  69%|██████▊   | 13716/19990 [32:38<20:40,  5.06it/s]

[13720] Геокодируем адрес: Колпино Трудящихся б-р 33, Санкт-Петербург

Геокодирование:  69%|██████▊   | 13721/19990 [32:39<21:10,  4.93it/s]

[13721] Геокодируем адрес: Славы ул 18, Санкт-Петербург

Геокодирование:  69%|██████▊   | 13722/19990 [32:41<37:20,  2.80it/s]

[13723] Геокодируем адрес: реки Оккервиль наб 4, Санкт-Петербург

Геокодирование:  69%|██████▊   | 13724/19990 [32:42<41:01,  2.55it/s]

[13726] Геокодируем адрес: Петергоф Озерковая ул, Санкт-Петербург

Геокодирование:  69%|██████▊   | 13727/19990 [32:43<37:36,  2.78it/s]

[13729] Геокодируем адрес: художников пр-т 33к1, Санкт-Петербург

Геокодирование:  69%|██████▊   | 13730/19990 [32:44<37:43,  2.77it/s]

[13730] Геокодируем адрес: Шушары пушкинская ул 2, Санкт-Петербург

Геокодирование:  69%|██████▊   | 13731/19990 [32:45<46:11,  2.26it/s]

[13732] Геокодируем адрес: Витебский пр-т 31к4, Санкт-Петербург

Геокодирование:  69%|██████▊   | 13733/19990 [32:46<46:37,  2.24it/s]

[13735] Геокодируем адрес: Торфяная дор, Санкт-Петербург

Геокодирование:  69%|██████▊   | 13736/19990 [32:47<42:10,  2.47it/s]

[13736] Геокодируем адрес: Шушары Чудовская ул, Санкт-Петербург

Геокодирование:  69%|██████▊   | 13737/19990 [32:48<51:20,  2.03it/s]

[13737] Геокодируем адрес: Медиков пр-т 10к1, Санкт-Петербург

Геокодирование:  69%|██████▊   | 13741/19990 [32:49<37:51,  2.75it/s]

Автосохранение после 13740 строк...
[13742] Геокодируем адрес: Шушары Школьная ул 17, Санкт-Петербург

Геокодирование:  69%|██████▊   | 13743/19990 [32:50<39:22,  2.64it/s]

[13743] Геокодируем адрес: Светлановский пр-т 95, Санкт-Петербург

Геокодирование:  69%|██████▉   | 13744/19990 [32:51<52:32,  1.98it/s]

[13744] Геокодируем адрес: Стачек пр-т 101к1Б, Санкт-Петербург

Геокодирование:  69%|██████▉   | 13745/19990 [32:52<57:49,  1.80it/s]

[13745] Геокодируем адрес: Менделеевская линия линия ВО, Санкт-Петербург

Геокодирование:  69%|██████▉   | 13746/19990 [32:53<1:09:50,  1.49it/s]

[13754] Геокодируем адрес: Павловск Толмачева ул 15/2, Санкт-Петербург

Геокодирование:  69%|██████▉   | 13755/19990 [32:54<28:06,  3.70it/s]

[13755] Геокодируем адрес: Шушары Школьная ул 15, Санкт-Петербург

Геокодирование:  69%|██████▉   | 13756/19990 [32:55<34:54,  2.98it/s]

[13760] Геокодируем адрес: Народного Ополчения пр-т 149, Санкт-Петербург

Геокодирование:  69%|██████▉   | 13761/19990 [32:56<29:35,  3.51it/s]

[13761] Геокодируем адрес: Обуховской Обороны пр-т 33А, Санкт-Петербург

Геокодирование:  69%|██████▉   | 13762/19990 [32:57<37:32,  2.76it/s]

[13768] Геокодируем адрес: Шушары Валдайская ул, Санкт-Петербург

Геокодирование:  69%|██████▉   | 13771/19990 [32:58<21:36,  4.80it/s]

Автосохранение после 13770 строк...
[13776] Геокодируем адрес: Маршала Жукова пр-т 66к1, Санкт-Петербург

Геокодирование:  69%|██████▉   | 13777/19990 [32:59<19:06,  5.42it/s]

[13784] Геокодируем адрес: Витебский пр-т 91к3, Санкт-Петербург

Геокодирование:  69%|██████▉   | 13785/19990 [33:00<16:37,  6.22it/s]

[13787] Геокодируем адрес: Славы пр-т 10к3, Санкт-Петербург

Геокодирование:  69%|██████▉   | 13788/19990 [33:01<19:20,  5.34it/s]

[13788] Геокодируем адрес: Ломоносов Скуридина ул 6, Санкт-Петербург

Геокодирование:  69%|██████▉   | 13789/19990 [33:02<26:45,  3.86it/s]

[13789] Геокодируем адрес: Шушары Новгородский ул 10, Санкт-Петербург

Геокодирование:  69%|██████▉   | 13790/19990 [33:03<35:18,  2.93it/s]

[13790] Геокодируем адрес: Энергетиков пр-т 8к1, Санкт-Петербург

Геокодирование:  69%|██████▉   | 13791/19990 [33:04<45:09,  2.29it/s]

[13792] Геокодируем адрес: Героев пр-т 32, Санкт-Петербург

Геокодирование:  69%|██████▉   | 13793/19990 [33:05<48:32,  2.13it/s]

[13794] Геокодируем адрес: Павловск Детскосельская ул, Санкт-Петербург

Геокодирование:  69%|██████▉   | 13795/19990 [33:06<45:40,  2.26it/s]

[13795] Геокодируем адрес: Сестрорецк Мосина ул, Санкт-Петербург

Геокодирование:  69%|██████▉   | 13796/19990 [33:07<55:25,  1.86it/s]

[13799] Геокодируем адрес: Дачный пр-т 15, Санкт-Петербург

Геокодирование:  69%|██████▉   | 13801/19990 [33:08<39:31,  2.61it/s]

Автосохранение после 13800 строк...
[13801] Геокодируем адрес: Шушары Витебский пр-т, Санкт-Петербург

Геокодирование:  69%|██████▉   | 13802/19990 [33:09<44:38,  2.31it/s]

[13802] Геокодируем адрес: Кронштадт, Советская ул, Санкт-Петербург

Геокодирование:  69%|██████▉   | 13803/19990 [33:10<55:14,  1.87it/s]

[13803] Геокодируем адрес: Петергоф Чичерниская ул 2, Санкт-Петербург

Геокодирование:  69%|██████▉   | 13804/19990 [33:11<1:05:08,  1.58it/s]

[13806] Геокодируем адрес: Стачек пр-т 59, Санкт-Петербург

Геокодирование:  69%|██████▉   | 13807/19990 [33:12<52:38,  1.96it/s]

[13807] Геокодируем адрес: Стачек пр-т 67к3, Санкт-Петербург

Геокодирование:  69%|██████▉   | 13808/19990 [33:13<1:00:16,  1.71it/s]

[13809] Геокодируем адрес: Петергоф Чичерниская ул, Санкт-Петербург

Геокодирование:  69%|██████▉   | 13810/19990 [33:14<56:07,  1.83it/s]

[13812] Геокодируем адрес: Александровская Редкое Кузьмино ул, Санкт-Петербург

Геокодирование:  69%|██████▉   | 13813/19990 [33:15<47:49,  2.15it/s]

[13813] Геокодируем адрес: Александровская Редкое Кузьмино ул, Санкт-Петербург

Геокодирование:  69%|██████▉   | 13814/19990 [33:16<57:44,  1.78it/s]

[13817] Геокодируем адрес: Петергоф Озерковая ул, Санкт-Петербург

Геокодирование:  69%|██████▉   | 13818/19990 [33:17<41:09,  2.50it/s]

[13824] Геокодируем адрес: Заневский пр-т 14, Санкт-Петербург

Геокодирование:  69%|██████▉   | 13825/19990 [33:18<28:01,  3.67it/s]

[13825] Геокодируем адрес: Металлострой Садовая ул 21к1, Санкт-Петербург

Геокодирование:  69%|██████▉   | 13826/19990 [33:19<34:16,  3.00it/s]

[13826] Геокодируем адрес: Кронштадт Советская ул 11А, Санкт-Петербург

Геокодирование:  69%|██████▉   | 13827/19990 [33:20<43:59,  2.33it/s]

[13830] Геокодируем адрес: на Турухтанные Острова дор, Санкт-Петербург

Геокодирование:  69%|██████▉   | 13831/19990 [33:21<37:44,  2.72it/s]

Автосохранение после 13830 строк...
[13833] Геокодируем адрес: Науки пр-т 17/6, Санкт-Петербург

Геокодирование:  69%|██████▉   | 13834/19990 [33:22<36:24,  2.82it/s]

[13841] Геокодируем адрес: Литейный пр-т 11, Санкт-Петербург

Геокодирование:  69%|██████▉   | 13842/19990 [33:23<22:46,  4.50it/s]

[13849] Геокодируем адрес: маршала блюхера пр-т 7, Санкт-Петербург

Геокодирование:  69%|██████▉   | 13850/19990 [33:24<19:08,  5.34it/s]

[13856] Геокодируем адрес: Юнтоловский пр-т 53к3, Санкт-Петербург

Геокодирование:  69%|██████▉   | 13857/19990 [33:25<16:10,  6.32it/s]

[13858] Геокодируем адрес: Красного Текстильщика пр-т 9/11, Санкт-Петербург

Геокодирование:  69%|██████▉   | 13861/19990 [33:26<19:41,  5.19it/s]

Автосохранение после 13860 строк...
[13868] Геокодируем адрес: юрия гагарина пр-т 36, Санкт-Петербург

Геокодирование:  69%|██████▉   | 13869/19990 [33:27<15:56,  6.40it/s]

[13869] Геокодируем адрес: Новочеркасский пр-т 28/19, Санкт-Петербург

Геокодирование:  69%|██████▉   | 13870/19990 [33:28<21:48,  4.68it/s]

[13871] Геокодируем адрес: Космонавтов пр-т 61к1, Санкт-Петербург

Геокодирование:  69%|██████▉   | 13872/19990 [33:29<26:24,  3.86it/s]

[13888] Геокодируем адрес: Парголово Заречная ул 42к2, Санкт-Петербург

Геокодирование:  69%|██████▉   | 13889/19990 [33:30<12:14,  8.31it/s]

[13889] Геокодируем адрес: Большой Сампсониевский пр-т 80, Санкт-Петербург

Геокодирование:  69%|██████▉   | 13891/19990 [33:31<17:53,  5.68it/s]

Автосохранение после 13890 строк...
[13907] Геокодируем адрес: Юрия Гагарина пр-т 24к1, Санкт-Петербург

Геокодирование:  70%|██████▉   | 13908/19990 [33:32<09:42, 10.45it/s]

[13908] Геокодируем адрес: Сестрорецк Гагаринская ул 77к1стр1, Санкт-Петербург

Геокодирование:  70%|██████▉   | 13910/19990 [33:33<12:17,  8.25it/s]

[13911] Геокодируем адрес: Петергоф Чичерниская ул 2, Санкт-Петербург

Геокодирование:  70%|██████▉   | 13912/19990 [33:34<16:55,  5.99it/s]

[13912] Геокодируем адрес: Ленинский пр-т 98, Санкт-Петербург

Геокодирование:  70%|██████▉   | 13913/19990 [33:35<26:05,  3.88it/s]

[13916] Геокодируем адрес: Художников пр-т 26к2, Санкт-Петербург

Геокодирование:  70%|██████▉   | 13917/19990 [33:36<24:23,  4.15it/s]

[13919] Геокодируем адрес: Дунайский пр-т 53к2, Санкт-Петербург

Геокодирование:  70%|██████▉   | 13921/19990 [33:37<25:13,  4.01it/s]

Автосохранение после 13920 строк...
[13922] Геокодируем адрес: Малоохтинский пр-т 10, Санкт-Петербург

Геокодирование:  70%|██████▉   | 13923/19990 [33:38<30:15,  3.34it/s]

[13923] Геокодируем адрес: Загородный пр-т 22, Санкт-Петербург

Геокодирование:  70%|██████▉   | 13924/19990 [33:39<41:29,  2.44it/s]

[13924] Геокодируем адрес: Комендантский пр-т 69, Санкт-Петербург

Геокодирование:  70%|██████▉   | 13925/19990 [33:40<51:23,  1.97it/s]

[13932] Геокодируем адрес: Энгельса пр-т 143к3, Санкт-Петербург

Геокодирование:  70%|██████▉   | 13933/19990 [33:41<24:43,  4.08it/s]

[13940] Геокодируем адрес: Красное Село Гатчинское ш, Санкт-Петербург

Геокодирование:  70%|██████▉   | 13951/19990 [33:42<11:05,  9.08it/s]

Автосохранение после 13950 строк...
[13952] Геокодируем адрес: Шушары Переведенская ул, Санкт-Петербург
[13953] Геокодируем адрес: Заневский пр-т 42, Санкт-Петербург

Геокодирование:  70%|██████▉   | 13954/19990 [33:44<19:22,  5.19it/s]

[13957] Геокодируем адрес: Петергоф Озерковая ул, Санкт-Петербург

Геокодирование:  70%|██████▉   | 13958/19990 [33:45<20:03,  5.01it/s]

[13958] Геокодируем адрес: Петергоф Озерковая ул, Санкт-Петербург
[13959] Геокодируем адрес: Петергоф Озерковая ул 21, Санкт-Петербург

Геокодирование:  70%|██████▉   | 13960/19990 [33:47<32:31,  3.09it/s]

[13960] Геокодируем адрес: Народного Ополчения пр-т 167/21, Санкт-Петербург

Геокодирование:  70%|██████▉   | 13961/19990 [33:48<39:21,  2.55it/s]

[13962] Геокодируем адрес: Большой Сампсониевский пр-т 57, Санкт-Петербург

Геокодирование:  70%|██████▉   | 13963/19990 [33:49<42:34,  2.36it/s]

[13963] Геокодируем адрес: Валерия Гаврилина ул 3к1литераА, Санкт-Петербург

Геокодирование:  70%|██████▉   | 13964/19990 [33:50<46:29,  2.16it/s]

[13964] Геокодируем адрес: Валерия Гаврилина ул 3к1литераА, Санкт-Петербург

Геокодирование:  70%|██████▉   | 13965/19990 [33:51<55:14,  1.82it/s]

[13968] Геокодируем адрес: Придоррожная ал 21, Санкт-Петербург

Геокодирование:  70%|██████▉   | 13969/19990 [33:52<40:54,  2.45it/s]

[13970] Геокодируем адрес: Шушары Школьная ул 15, Санкт-Петербург

Геокодирование:  70%|██████▉   | 13971/19990 [33:53<44:45,  2.24it/s]

[13971] Геокодируем адрес: Шушары Школьная ул 15, Санкт-Петербург

Геокодирование:  70%|██████▉   | 13972/19990 [33:54<53:09,  1.89it/s]

[13973] Геокодируем адрес: реки Оккервиль наб 4, Санкт-Петербург

Геокодирование:  70%|██████▉   | 13981/19990 [33:55<22:33,  4.44it/s]

Автосохранение после 13980 строк...
[13985] Геокодируем адрес: Солидарности пр-т 1к3, Санкт-Петербург

Геокодирование:  70%|██████▉   | 13986/19990 [33:56<19:39,  5.09it/s]

[13990] Геокодируем адрес: Испытателей пр-т 16, Санкт-Петербург

Геокодирование:  70%|██████▉   | 13991/19990 [33:57<19:50,  5.04it/s]

[13993] Геокодируем адрес: Королева ул 7, Санкт-Петербург

Геокодирование:  70%|███████   | 13994/19990 [33:58<23:20,  4.28it/s]

[14002] Геокодируем адрес: Петергоф Озерковая ул, Санкт-Петербург

Геокодирование:  70%|███████   | 14011/19990 [33:59<10:56,  9.10it/s]

Автосохранение после 14010 строк...
[14015] Геокодируем адрес: 23-я линия ВО, Санкт-Петербург

Геокодирование:  70%|███████   | 14016/19990 [34:00<15:08,  6.58it/s]

[14016] Геокодируем адрес: Парголово Заречная ул, Санкт-Петербург
[14017] Геокодируем адрес: Парголово Заречная ул, Санкт-Петербург

Геокодирование:  70%|███████   | 14018/19990 [34:02<23:36,  4.22it/s]

[14020] Геокодируем адрес: Культуры пр-т 29, Санкт-Петербург

Геокодирование:  70%|███████   | 14021/19990 [34:03<26:56,  3.69it/s]

[14026] Геокодируем адрес: Муринская дор 10к1, Санкт-Петербург

Геокодирование:  70%|███████   | 14027/19990 [34:04<21:57,  4.53it/s]

[14032] Геокодируем адрес: Новочеркасский пр-т 14, Санкт-Петербург

Геокодирование:  70%|███████   | 14033/19990 [34:05<20:59,  4.73it/s]

[14035] Геокодируем адрес: Красное Село Спирина ул 12, Санкт-Петербург

Геокодирование:  70%|███████   | 14036/19990 [34:06<23:19,  4.25it/s]

[14040] Геокодируем адрес: Тореза пр-т 102к3, Санкт-Петербург

Геокодирование:  70%|███████   | 14041/19990 [34:07<22:05,  4.49it/s]

Автосохранение после 14040 строк...
[14041] Геокодируем адрес: Петергоф Солнечная ул, Санкт-Петербург

Геокодирование:  70%|███████   | 14042/19990 [34:08<27:06,  3.66it/s]

[14043] Геокодируем адрес: Народного Ополчения пр-т 149, Санкт-Петербург

Геокодирование:  70%|███████   | 14044/19990 [34:11<52:34,  1.88it/s]

[14051] Геокодируем адрес: 14-я линия ВО, Санкт-Петербург

Геокодирование:  70%|███████   | 14052/19990 [34:13<33:59,  2.91it/s]

[14055] Геокодируем адрес: приморский пр-т 52к1, Санкт-Петербург

Геокодирование:  70%|███████   | 14056/19990 [34:13<29:01,  3.41it/s]

[14056] Геокодируем адрес: Шушары Полоцкая ул 15к3, Санкт-Петербург

Геокодирование:  70%|███████   | 14057/19990 [34:14<34:57,  2.83it/s]

[14059] Геокодируем адрес: Ломоносов Пригородная ул 1а, Санкт-Петербург

Геокодирование:  70%|███████   | 14060/19990 [34:15<34:54,  2.83it/s]

[14060] Геокодируем адрес: Зеленогорск Курортная ул 33, Санкт-Петербург

Геокодирование:  70%|███████   | 14061/19990 [34:16<42:58,  2.30it/s]

[14070] Геокодируем адрес: Дачный пр-т 15, Санкт-Петербург

Геокодирование:  70%|███████   | 14071/19990 [34:18<23:22,  4.22it/s]

Автосохранение после 14070 строк...
[14071] Геокодируем адрес: мориса тореза пр-т 28, Санкт-Петербург

Геокодирование:  70%|███████   | 14072/19990 [34:19<36:49,  2.68it/s]

[14073] Геокодируем адрес: Лиговский пр-т 87В, Санкт-Петербург

Геокодирование:  70%|███████   | 14074/19990 [34:20<37:23,  2.64it/s]

[14074] Геокодируем адрес: Лиговский пр-т 87В, Санкт-Петербург

Геокодирование:  70%|███████   | 14075/19990 [34:21<44:42,  2.20it/s]

[14076] Геокодируем адрес: Литейный пр-т 11, Санкт-Петербург

Геокодирование:  70%|███████   | 14077/19990 [34:22<47:56,  2.06it/s]

[14083] Геокодируем адрес: Ветеранов пр-т 71, Санкт-Петербург

Геокодирование:  70%|███████   | 14084/19990 [34:23<28:54,  3.41it/s]

[14085] Геокодируем адрес: Петергоф Братьев Горкушенко ул, Санкт-Петербург

Геокодирование:  70%|███████   | 14086/19990 [34:24<31:30,  3.12it/s]

[14088] Геокодируем адрес: Искровский пр-т 9, Санкт-Петербург

Геокодирование:  70%|███████   | 14089/19990 [34:25<32:22,  3.04it/s]

[14089] Геокодируем адрес: реки Оккервиль наб 4, Санкт-Петербург

Геокодирование:  70%|███████   | 14090/19990 [34:26<40:24,  2.43it/s]

[14093] Геокодируем адрес: Кронштадт Посадская ул 17/14, Санкт-Петербург

Геокодирование:  71%|███████   | 14101/19990 [34:28<18:10,  5.40it/s]

Автосохранение после 14100 строк...
[14105] Геокодируем адрес: Ленинский пр-т 132, Санкт-Петербург

Геокодирование:  71%|███████   | 14106/19990 [34:29<19:00,  5.16it/s]

[14114] Геокодируем адрес: Петергоф Чичерниская ул 2, Санкт-Петербург

Геокодирование:  71%|███████   | 14115/19990 [34:29<13:09,  7.45it/s]

[14128] Геокодируем адрес: Энгельса пр-т 100/2, Санкт-Петербург

Геокодирование:  71%|███████   | 14131/19990 [34:31<10:46,  9.06it/s]

Автосохранение после 14130 строк...
[14132] Геокодируем адрес: Московский пр-т 220, Санкт-Петербург

Геокодирование:  71%|███████   | 14133/19990 [34:31<14:10,  6.88it/s]

[14133] Геокодируем адрес: Юрия Гагарина пр-т 35, Санкт-Петербург

Геокодирование:  71%|███████   | 14134/19990 [34:34<28:49,  3.39it/s]

[14136] Геокодируем адрес: Бобыльская дор 61А, Санкт-Петербург

Геокодирование:  71%|███████   | 14137/19990 [34:34<27:59,  3.49it/s]

[14157] Геокодируем адрес: Искровский пр-т 35/38, Санкт-Петербург

Геокодирование:  71%|███████   | 14158/19990 [34:36<11:57,  8.13it/s]

[14160] Геокодируем адрес: Нефтяная дор, Санкт-Петербург

Геокодирование:  71%|███████   | 14161/19990 [34:36<14:07,  6.88it/s]

Автосохранение после 14160 строк...
[14162] Геокодируем адрес: Бокситогороская ул 27, Санкт-Петербург

Геокодирование:  71%|███████   | 14163/19990 [34:37<16:43,  5.81it/s]

[14169] Геокодируем адрес: Ветеранов пр-т 114/1, Санкт-Петербург

Геокодирование:  71%|███████   | 14170/19990 [34:39<17:06,  5.67it/s]

[14171] Геокодируем адрес: Пушкин Церковная ул 50/18, Санкт-Петербург

Геокодирование:  71%|███████   | 14172/19990 [34:39<20:52,  4.64it/s]

[14173] Геокодируем адрес: Охты наб, Санкт-Петербург

Геокодирование:  71%|███████   | 14174/19990 [34:40<23:07,  4.19it/s]

[14175] Геокодируем адрес: Каменноостровский пр-т 34, Санкт-Петербург

Геокодирование:  71%|███████   | 14176/19990 [34:41<29:16,  3.31it/s]

[14177] Геокодируем адрес: Энергетиков пр-т 9к3, Санкт-Петербург

Геокодирование:  71%|███████   | 14191/19990 [34:43<11:59,  8.06it/s]

Автосохранение после 14190 строк...
[14192] Геокодируем адрес: Шушары Витебский пр-т, Санкт-Петербург

Геокодирование:  71%|███████   | 14194/19990 [34:43<14:33,  6.64it/s]

[14205] Геокодируем адрес: Мориса Тореза пр-т 28, Санкт-Петербург

Геокодирование:  71%|███████   | 14206/19990 [34:44<11:34,  8.32it/s]

[14209] Геокодируем адрес: Петергоф Александрийский сад, Санкт-Петербург

Геокодирование:  71%|███████   | 14210/19990 [34:45<13:37,  7.07it/s]

[14218] Геокодируем адрес: Красное Село Пушкинское ш, Санкт-Петербург

Геокодирование:  71%|███████   | 14219/19990 [34:47<13:13,  7.27it/s]

[14219] Геокодируем адрес: Коннолахтинская дор, Санкт-Петербург

Геокодирование:  71%|███████   | 14221/19990 [34:47<16:37,  5.79it/s]

Автосохранение после 14220 строк...
[14224] Геокодируем адрес: Маршала Жукова пр-т 70к1, Санкт-Петербург

Геокодирование:  71%|███████   | 14225/19990 [34:48<17:59,  5.34it/s]

[14225] Геокодируем адрес: Космонавтов пр-т 61, Санкт-Петербург

Геокодирование:  71%|███████   | 14226/19990 [34:50<25:04,  3.83it/s]

[14226] Геокодируем адрес: Колпино Красных Партизан ул 3, Санкт-Петербург

Геокодирование:  71%|███████   | 14227/19990 [34:50<30:52,  3.11it/s]

[14230] Геокодируем адрес: Комендантский пр-т 17к1, Санкт-Петербург

Геокодирование:  71%|███████   | 14231/19990 [34:51<28:26,  3.38it/s]

[14234] Геокодируем адрес: Парголово Валерия Гаврилина ул 3, Санкт-Петербург

Геокодирование:  71%|███████   | 14235/19990 [34:52<26:38,  3.60it/s]

[14235] Геокодируем адрес: Парголово Заречная ул, Санкт-Петербург

Геокодирование:  71%|███████   | 14236/19990 [34:53<33:38,  2.85it/s]

[14243] Геокодируем адрес: Луначарского пр-т 5, Санкт-Петербург

Геокодирование:  71%|███████▏  | 14244/19990 [34:55<23:06,  4.14it/s]

[14244] Геокодируем адрес: Петергоф Знаменская ул 29, Санкт-Петербург

Геокодирование:  71%|███████▏  | 14245/19990 [34:55<27:58,  3.42it/s]

[14250] Геокодируем адрес: Лиговский пр-т 81, Санкт-Петербург

Геокодирование:  71%|███████▏  | 14251/19990 [34:57<24:55,  3.84it/s]

Автосохранение после 14250 строк...
[14254] Геокодируем адрес: Новоизмайловский пр-т 39/53, Санкт-Петербург

Геокодирование:  71%|███████▏  | 14255/19990 [34:57<23:16,  4.11it/s]

[14256] Геокодируем адрес: Пушкин Генерала Хазова ул 5, Санкт-Петербург

Геокодирование:  71%|███████▏  | 14257/19990 [34:58<27:07,  3.52it/s]

[14258] Геокодируем адрес: Шушары Пушкинская ул, Санкт-Петербург

Геокодирование:  71%|███████▏  | 14259/19990 [34:59<30:10,  3.17it/s]

[14259] Геокодируем адрес: Петергоф Ропшинское ш 3к7, Санкт-Петербург

Геокодирование:  71%|███████▏  | 14260/19990 [35:00<39:22,  2.43it/s]

[14262] Геокодируем адрес: Парголово Приозерское ш 12, Санкт-Петербург

Геокодирование:  71%|███████▏  | 14263/19990 [35:01<37:00,  2.58it/s]

[14265] Геокодируем адрес: Петергоф Привокзальная пл 2А, Санкт-Петербург

Геокодирование:  71%|███████▏  | 14266/19990 [35:03<44:49,  2.13it/s]

[14272] Геокодируем адрес: Петергоф Ропшинское ш 3к6, Санкт-Петербург

Геокодирование:  71%|███████▏  | 14273/19990 [35:04<28:50,  3.30it/s]

[14277] Геокодируем адрес: Кима пр-т 3, Санкт-Петербург

Геокодирование:  71%|███████▏  | 14278/19990 [35:05<26:01,  3.66it/s]

[14280] Геокодируем адрес: Петергоф Привокзальная пл 2А, Санкт-Петербург

Геокодирование:  71%|███████▏  | 14281/19990 [35:07<27:33,  3.45it/s]

Автосохранение после 14280 строк...
[14281] Геокодируем адрес: Петергоф Привокзальная пл 2А, Санкт-Петербург

Геокодирование:  71%|███████▏  | 14282/19990 [35:07<33:05,  2.87it/s]

[14282] Геокодируем адрес: Петергоф Привокзальная пл 2А, Санкт-Петербург

Геокодирование:  71%|███████▏  | 14283/19990 [35:08<40:44,  2.33it/s]

[14283] Геокодируем адрес: Петергоф Привокзальная пл 2А, Санкт-Петербург

Геокодирование:  71%|███████▏  | 14284/19990 [35:09<49:10,  1.93it/s]

[14289] Геокодируем адрес: Обуховской Обороны ул 39, Санкт-Петербург

Геокодирование:  71%|███████▏  | 14290/19990 [35:10<30:00,  3.17it/s]

[14297] Геокодируем адрес: Косыгина ул 27к1, Санкт-Петербург

Геокодирование:  72%|███████▏  | 14298/19990 [35:11<20:48,  4.56it/s]

[14298] Геокодируем адрес: Ленинский пр-т 72к3, Санкт-Петербург

Геокодирование:  72%|███████▏  | 14299/19990 [35:12<26:38,  3.56it/s]

[14309] Геокодируем адрес: Торфяная дор 4, Санкт-Петербург

Геокодирование:  72%|███████▏  | 14311/19990 [35:13<16:11,  5.85it/s]

Автосохранение после 14310 строк...
[14312] Геокодируем адрес: Наставников пр-т 11к2, Санкт-Петербург

Геокодирование:  72%|███████▏  | 14313/19990 [35:14<20:28,  4.62it/s]

[14318] Геокодируем адрес: Загребский б-р 33к2, Санкт-Петербург

Геокодирование:  72%|███████▏  | 14319/19990 [35:15<17:51,  5.29it/s]

[14319] Геокодируем адрес: Российский пр-т 14, Санкт-Петербург

Геокодирование:  72%|███████▏  | 14320/19990 [35:16<26:08,  3.61it/s]

[14323] Геокодируем адрес: Пискаревский пр-т 145к2, Санкт-Петербург

Геокодирование:  72%|███████▏  | 14324/19990 [35:17<24:00,  3.93it/s]

[14324] Геокодируем адрес: Шушары Школьная ул 20, Санкт-Петербург

Геокодирование:  72%|███████▏  | 14325/19990 [35:18<31:53,  2.96it/s]

[14326] Геокодируем адрес: Пушкин Пушкинская ул 8, Санкт-Петербург

Геокодирование:  72%|███████▏  | 14341/19990 [35:20<11:24,  8.26it/s]

Автосохранение после 14340 строк...
[14344] Геокодируем адрес: Сизова ул 25, Санкт-Петербург

Геокодирование:  72%|███████▏  | 14345/19990 [35:20<12:56,  7.27it/s]

[14346] Геокодируем адрес: Тореза пр-т 40к6, Санкт-Петербург

Геокодирование:  72%|███████▏  | 14348/19990 [35:21<16:30,  5.70it/s]

[14348] Геокодируем адрес: Культуры пр-т 19, Санкт-Петербург

Геокодирование:  72%|███████▏  | 14350/19990 [35:23<22:44,  4.13it/s]

[14365] Геокодируем адрес: Культуры пр-т, Санкт-Петербург

Геокодирование:  72%|███████▏  | 14371/19990 [35:24<09:26,  9.92it/s]

Автосохранение после 14370 строк...
[14373] Геокодируем адрес: Перекупной пер 7литГ, Санкт-Петербург

Геокодирование:  72%|███████▏  | 14374/19990 [35:24<11:40,  8.02it/s]

[14374] Геокодируем адрес: Петергоф Чичеринская ул 2, Санкт-Петербург

Геокодирование:  72%|███████▏  | 14376/19990 [35:25<17:00,  5.50it/s]

[14380] Геокодируем адрес: Раевского пр-т 14к2, Санкт-Петербург

Геокодирование:  72%|███████▏  | 14381/19990 [35:26<17:03,  5.48it/s]

[14381] Геокодируем адрес: Петровский пр-т 5, Санкт-Петербург

Геокодирование:  72%|███████▏  | 14382/19990 [35:27<24:48,  3.77it/s]

[14382] Геокодируем адрес: Петровский пр-т 5, Санкт-Петербург

Геокодирование:  72%|███████▏  | 14383/19990 [35:29<32:45,  2.85it/s]

[14383] Геокодируем адрес: Петровский пр-т 5, Санкт-Петербург

Геокодирование:  72%|███████▏  | 14384/19990 [35:29<40:26,  2.31it/s]

[14384] Геокодируем адрес: Петровский пр-т 5, Санкт-Петербург

Геокодирование:  72%|███████▏  | 14385/19990 [35:30<48:38,  1.92it/s]

[14387] Геокодируем адрес: Парголово Михаила Дудина ул 25к2, Санкт-Петербург

Геокодирование:  72%|███████▏  | 14388/19990 [35:31<39:38,  2.36it/s]

[14388] Геокодируем адрес: Ветеранов пр-т 88, Санкт-Петербург

Геокодирование:  72%|███████▏  | 14389/19990 [35:32<50:49,  1.84it/s]

[14393] Геокодируем адрес: Просвещения пр-т 84к3, Санкт-Петербург

Геокодирование:  72%|███████▏  | 14401/19990 [35:33<16:22,  5.69it/s]

Автосохранение после 14400 строк...
[14402] Геокодируем адрес: Петровский пр-т 5, Санкт-Петербург

Геокодирование:  72%|███████▏  | 14403/19990 [35:35<22:12,  4.19it/s]

[14412] Геокодируем адрес: Петергоф Ропшинское ш 3к2, Санкт-Петербург

Геокодирование:  72%|███████▏  | 14413/19990 [35:35<14:32,  6.40it/s]

[14413] Геокодируем адрес: Петергоф Ропшинское ш 3к2, Санкт-Петербург
[14414] Геокодируем адрес: Петергоф Санкт-Петербургский пр-т 4А, Санкт-Петербург

Геокодирование:  72%|███████▏  | 14415/19990 [35:37<25:22,  3.66it/s]

[14415] Геокодируем адрес: Петергоф Санкт-Петербургский пр-т 4А, Санкт-Петербург

Геокодирование:  72%|███████▏  | 14416/19990 [35:38<30:51,  3.01it/s]

[14416] Геокодируем адрес: Петергоф Озерковая ул, Санкт-Петербург

Геокодирование:  72%|███████▏  | 14417/19990 [35:39<36:57,  2.51it/s]

[14417] Геокодируем адрес: Петергоф Озерковая ул, Санкт-Петербург

Геокодирование:  72%|███████▏  | 14418/19990 [35:40<44:19,  2.09it/s]

[14418] Геокодируем адрес: Петергоф Озерковая ул, Санкт-Петербург

Геокодирование:  72%|███████▏  | 14419/19990 [35:41<52:28,  1.77it/s]

[14420] Геокодируем адрес: Красное Село Освобождения ул 33к2, Санкт-Петербург

Геокодирование:  72%|███████▏  | 14421/19990 [35:42<51:53,  1.79it/s]

[14421] Геокодируем адрес: Ломоносов Краснопрудская ул, Санкт-Петербург

Геокодирование:  72%|███████▏  | 14431/19990 [35:43<18:04,  5.12it/s]

Автосохранение после 14430 строк...
[14452] Геокодируем адрес: Славы пр-т 37, Санкт-Петербург

Геокодирование:  72%|███████▏  | 14453/19990 [35:44<08:10, 11.28it/s]

[14455] Геокодируем адрес: Шушары Кокколевская ул, Санкт-Петербург

Геокодирование:  72%|███████▏  | 14456/19990 [35:45<10:22,  8.89it/s]

[14457] Геокодируем адрес: Шушары Ростовская ул 22, Санкт-Петербург

Геокодирование:  72%|███████▏  | 14461/19990 [35:46<12:35,  7.32it/s]

Автосохранение после 14460 строк...
[14467] Геокодируем адрес: Старо-Петергофский пр-т 3, Санкт-Петербург

Геокодирование:  72%|███████▏  | 14468/19990 [35:47<12:38,  7.28it/s]

[14468] Геокодируем адрес: Просвещения пр-т 20к1, Санкт-Петербург

Геокодирование:  72%|███████▏  | 14470/19990 [35:48<16:28,  5.58it/s]

[14475] Геокодируем адрес: Ленина ул 14, Санкт-Петербург

Геокодирование:  72%|███████▏  | 14476/19990 [35:49<16:13,  5.66it/s]

[14479] Геокодируем адрес: Загородный пр-т 17, Санкт-Петербург

Геокодирование:  72%|███████▏  | 14480/19990 [35:50<18:10,  5.05it/s]

[14480] Геокодируем адрес: Петергоф Самсониевская ул 3, Санкт-Петербург

Геокодирование:  72%|███████▏  | 14481/19990 [35:51<23:54,  3.84it/s]

[14483] Геокодируем адрес: Пушкин Набережная ул 1, Санкт-Петербург

Геокодирование:  72%|███████▏  | 14484/19990 [35:52<25:51,  3.55it/s]

[14489] Геокодируем адрес: Розенштейна ул 8-12В, Санкт-Петербург

Геокодирование:  72%|███████▏  | 14491/19990 [35:53<20:11,  4.54it/s]

Автосохранение после 14490 строк...
[14494] Геокодируем адрес: Большой Сампсониевский пр-т 96, Санкт-Петербург

Геокодирование:  73%|███████▎  | 14495/19990 [35:55<21:16,  4.31it/s]

[14497] Геокодируем адрес: Лиговский пр-т 162, Санкт-Петербург

Геокодирование:  73%|███████▎  | 14498/19990 [35:55<23:08,  3.95it/s]

[14498] Геокодируем адрес: Шушары Школьная ул 15, Санкт-Петербург

Геокодирование:  73%|███████▎  | 14499/19990 [35:56<29:53,  3.06it/s]

[14500] Геокодируем адрес: Сиреневый б-р 22/26, Санкт-Петербург

Геокодирование:  73%|███████▎  | 14501/19990 [35:58<36:14,  2.52it/s]

[14501] Геокодируем адрес: Литейный пр-т 59, Санкт-Петербург

Геокодирование:  73%|███████▎  | 14502/19990 [35:58<43:48,  2.09it/s]

[14510] Геокодируем адрес: Науки пр-т 45к2, Санкт-Петербург

Геокодирование:  73%|███████▎  | 14511/19990 [35:59<20:27,  4.46it/s]

[14511] Геокодируем адрес: Торфяная дор, Санкт-Петербург

Геокодирование:  73%|███████▎  | 14512/19990 [36:00<26:52,  3.40it/s]

[14513] Геокодируем адрес: Ветеранов пр-т 51, Санкт-Петербург

Геокодирование:  73%|███████▎  | 14514/19990 [36:01<32:16,  2.83it/s]

[14519] Геокодируем адрес: Кузнецова пр-т 29к1, Санкт-Петербург

Геокодирование:  73%|███████▎  | 14521/19990 [36:03<22:45,  4.00it/s]

Автосохранение после 14520 строк...
[14521] Геокодируем адрес: Культуры пр-т 22к2, Санкт-Петербург

Геокодирование:  73%|███████▎  | 14522/19990 [36:03<28:38,  3.18it/s]

[14522] Геокодируем адрес: Меньшиковский пр-т 19, Санкт-Петербург

Геокодирование:  73%|███████▎  | 14523/19990 [36:04<39:42,  2.29it/s]

[14528] Геокодируем адрес: 21-я линия ВО, Санкт-Петербург

Геокодирование:  73%|███████▎  | 14529/19990 [36:06<29:50,  3.05it/s]

[14529] Геокодируем адрес: Большой Сампсониевский пр-т, Санкт-Петербург

Геокодирование:  73%|███████▎  | 14530/19990 [36:07<34:07,  2.67it/s]

[14535] Геокодируем адрес: Загородный пр-т 22Б, Санкт-Петербург

Геокодирование:  73%|███████▎  | 14536/19990 [36:08<24:55,  3.65it/s]

[14536] Геокодируем адрес: Красных Зорь б-р 14Ж, Санкт-Петербург

Геокодирование:  73%|███████▎  | 14537/19990 [36:09<32:16,  2.82it/s]

[14541] Геокодируем адрес: Культуры пр-т 17, Санкт-Петербург

Геокодирование:  73%|███████▎  | 14542/19990 [36:10<26:00,  3.49it/s]

[14546] Геокодируем адрес: Энгельса пр-т 143к3, Санкт-Петербург

Геокодирование:  73%|███████▎  | 14547/19990 [36:11<22:14,  4.08it/s]

[14547] Геокодируем адрес: Кадетский б-р 14/13, Санкт-Петербург

Геокодирование:  73%|███████▎  | 14548/19990 [36:12<29:39,  3.06it/s]

[14550] Геокодируем адрес: Пушкин Ленинградская ул 87, Санкт-Петербург

Геокодирование:  73%|███████▎  | 14551/19990 [36:13<30:41,  2.95it/s]

Автосохранение после 14550 строк...
[14558] Геокодируем адрес: Шушары Новгородский пр-т 2к3, Санкт-Петербург

Геокодирование:  73%|███████▎  | 14559/19990 [36:14<19:21,  4.67it/s]

[14565] Геокодируем адрес: Суворовский пр-т 13, Санкт-Петербург

Геокодирование:  73%|███████▎  | 14566/19990 [36:15<17:22,  5.20it/s]

[14566] Геокодируем адрес: ленинский пр-т 131, Санкт-Петербург

Геокодирование:  73%|███████▎  | 14567/19990 [36:16<23:17,  3.88it/s]

[14567] Геокодируем адрес: ленинский пр-т 131, Санкт-Петербург

Геокодирование:  73%|███████▎  | 14568/19990 [36:17<30:13,  2.99it/s]

[14575] Геокодируем адрес: Загородный пр-т 22, Санкт-Петербург

Геокодирование:  73%|███████▎  | 14576/19990 [36:18<19:25,  4.64it/s]

[14577] Геокодируем адрес: Шушары Изборская ул 1к1, Санкт-Петербург

Геокодирование:  73%|███████▎  | 14578/19990 [36:19<23:00,  3.92it/s]

[14580] Геокодируем адрес: Приморский пр-т 137к1, Санкт-Петербург

Геокодирование:  73%|███████▎  | 14581/19990 [36:20<25:22,  3.55it/s]

Автосохранение после 14580 строк...
[14582] Геокодируем адрес: Репино Восточный пер, Санкт-Петербург

Геокодирование:  73%|███████▎  | 14583/19990 [36:21<27:53,  3.23it/s]

[14585] Геокодируем адрес: 21-я линия ВО, Санкт-Петербург

RateLimiter caught an error, retrying (0/2 tries). Called with (*('21-я линия ВО, Санкт-Петербург',), **{}).
Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connection.py", line 516, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1374, in getresponse
    response.begin()
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1278, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1134, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 367, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=21-%D1%8F+%D0%BB%D0%B8%D0%BD%D0%B8%D1%8F+%D0%92%D0%9E%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 482, in _request
    resp = self.session.get(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=21-%D1%8F+%D0%BB%D0%B8%D0%BD%D0%B8%D1%8F+%D0%92%D0%9E%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\extra\rate_limiter.py", line 136, in _retries_gen
    yield i  # Run the function.
    ^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\extra\rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\geocoders\nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\geocoders\base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 472, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 494, in _request
    raise GeocoderUnavailable(message)
geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=21-%D1%8F+%D0%BB%D0%B8%D0%BD%D0%B8%D1%8F+%D0%92%D0%9E%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))
RateLimiter caught an error, retrying (1/2 tries). Called with (*('21-я линия ВО, Санкт-Петербург',), **{}).
Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connection.py", line 516, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1374, in getresponse
    response.begin()
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1278, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1134, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 367, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=21-%D1%8F+%D0%BB%D0%B8%D0%BD%D0%B8%D1%8F+%D0%92%D0%9E%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 482, in _request
    resp = self.session.get(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=21-%D1%8F+%D0%BB%D0%B8%D0%BD%D0%B8%D1%8F+%D0%92%D0%9E%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\extra\rate_limiter.py", line 136, in _retries_gen
    yield i  # Run the function.
    ^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\extra\rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\geocoders\nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\geocoders\base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 472, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 494, in _request
    raise GeocoderUnavailable(message)
geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=21-%D1%8F+%D0%BB%D0%B8%D0%BD%D0%B8%D1%8F+%D0%92%D0%9E%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))
RateLimiter swallowed an error after 2 retries. Called with (*('21-я линия ВО, Санкт-Петербург',), **{}).
Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connection.py", line 516, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1374, in getresponse
    response.begin()
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1278, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1134, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 367, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

[14586] Геокодируем адрес: Просвещения пр-т 69, Санкт-Петербург

Геокодирование:  73%|███████▎  | 14587/19990 [36:43<3:19:12,  2.21s/it]

[14587] Геокодируем адрес: Парголово Заречная ул, Санкт-Петербург

Геокодирование:  73%|███████▎  | 14588/19990 [36:44<2:58:10,  1.98s/it]

[14594] Геокодируем адрес: Народного Ополчения пр-т 93, Санкт-Петербург

Геокодирование:  73%|███████▎  | 14595/19990 [36:46<1:29:27,  1.01it/s]

[14595] Геокодируем адрес: Павловск Горная ул 10, Санкт-Петербург

Геокодирование:  73%|███████▎  | 14596/19990 [36:47<1:27:18,  1.03it/s]

[14597] Геокодируем адрес: Английский пр-т 45, Санкт-Петербург

Геокодирование:  73%|███████▎  | 14598/19990 [36:48<1:20:48,  1.11it/s]

[14606] Геокодируем адрес: Тореза пр-т 102к2, Санкт-Петербург

Геокодирование:  73%|███████▎  | 14611/19990 [36:49<26:50,  3.34it/s]

Автосохранение после 14610 строк...
[14621] Геокодируем адрес: Левашово Парковая ул, Санкт-Петербург

Геокодирование:  73%|███████▎  | 14641/19990 [36:50<07:41, 11.59it/s]

Автосохранение после 14640 строк...
[14647] Геокодируем адрес: Парголово Приозерское ш, Санкт-Петербург

Геокодирование:  73%|███████▎  | 14648/19990 [36:51<08:36, 10.34it/s]

[14658] Геокодируем адрес: Солидарности пр-т 8к1, Санкт-Петербург

Геокодирование:  73%|███████▎  | 14659/19990 [36:52<08:18, 10.69it/s]

[14668] Геокодируем адрес: Павловск Правды ул, Санкт-Петербург

Геокодирование:  73%|███████▎  | 14669/19990 [36:53<08:12, 10.81it/s]

[14669] Геокодируем адрес: Славянка Ростовская ул 14-16, Санкт-Петербург
[14670] Геокодируем адрес: Павловск Правды ул, Санкт-Петербург
Автосохранение после 14670 строк...
[14671] Геокодируем адрес: Пушкин Пушкинская ул 8, Санкт-Петербург

Геокодирование:  73%|███████▎  | 14672/19990 [36:56<18:18,  4.84it/s]

[14684] Геокодируем адрес: Шушары Витебский пр-т, Санкт-Петербург

Геокодирование:  73%|███████▎  | 14685/19990 [36:57<13:17,  6.65it/s]

[14685] Геокодируем адрес: Шушары Витебский пр-т, Санкт-Петербург

Геокодирование:  73%|███████▎  | 14687/19990 [36:58<15:54,  5.56it/s]

[14690] Геокодируем адрес: Металлострой Садовая ул 8, Санкт-Петербург

Геокодирование:  73%|███████▎  | 14691/19990 [36:59<17:17,  5.11it/s]

[14691] Геокодируем адрес: Колпино Ленина пр-т 53, Санкт-Петербург

Геокодирование:  73%|███████▎  | 14692/19990 [37:00<23:06,  3.82it/s]

[14692] Геокодируем адрес: Муринская дор, Санкт-Петербург

Геокодирование:  74%|███████▎  | 14693/19990 [37:01<26:36,  3.32it/s]

[14695] Геокодируем адрес: Колпино Танкистов ул 32, Санкт-Петербург

Геокодирование:  74%|███████▎  | 14696/19990 [37:02<27:58,  3.15it/s]

[14697] Геокодируем адрес: Петергоф Самсониевская ул 3, Санкт-Петербург

Геокодирование:  74%|███████▎  | 14698/19990 [37:03<30:49,  2.86it/s]

[14700] Геокодируем адрес: Парголово Заречная ул 40к2, Санкт-Петербург

Геокодирование:  74%|███████▎  | 14701/19990 [37:04<32:11,  2.74it/s]

Автосохранение после 14700 строк...
[14710] Геокодируем адрес: Красное Село Двадцать Пятого Октября пр-т, Санкт-Петербург

Геокодирование:  74%|███████▎  | 14711/19990 [37:06<20:30,  4.29it/s]

[14721] Геокодируем адрес: Литейный пр-т 10, Санкт-Петербург

Геокодирование:  74%|███████▎  | 14722/19990 [37:07<14:51,  5.91it/s]

[14728] Геокодируем адрес: Ветеранов пр-т 140, Санкт-Петербург

Геокодирование:  74%|███████▎  | 14729/19990 [37:08<15:20,  5.72it/s]

[14729] Геокодируем адрес: Ленинский пр-т 129к3, Санкт-Петербург

Геокодирование:  74%|███████▎  | 14731/19990 [37:09<17:56,  4.88it/s]

Автосохранение после 14730 строк...
[14731] Геокодируем адрес: Пархоменко пр-т 5, Санкт-Петербург

Геокодирование:  74%|███████▎  | 14732/19990 [37:10<26:09,  3.35it/s]

[14732] Геокодируем адрес: Культуры пр-т 17, Санкт-Петербург

Геокодирование:  74%|███████▎  | 14733/19990 [37:11<32:30,  2.70it/s]

[14734] Геокодируем адрес: Славы пр-т 43/49, Санкт-Петербург

Геокодирование:  74%|███████▎  | 14735/19990 [37:12<36:56,  2.37it/s]

[14746] Геокодируем адрес: Обуховской Обороны пр-т 140, Санкт-Петербург

Геокодирование:  74%|███████▍  | 14747/19990 [37:13<16:00,  5.46it/s]

[14756] Геокодируем адрес: Парголово Заречная ул 40, Санкт-Петербург

Геокодирование:  74%|███████▍  | 14757/19990 [37:14<12:05,  7.21it/s]

[14760] Геокодируем адрес: Шушары Ростовская ул 26к2, Санкт-Петербург

Геокодирование:  74%|███████▍  | 14761/19990 [37:15<14:34,  5.98it/s]

Автосохранение после 14760 строк...
[14761] Геокодируем адрес: Шушары Вишерская ул 2, Санкт-Петербург

Геокодирование:  74%|███████▍  | 14762/19990 [37:16<18:36,  4.68it/s]

[14765] Геокодируем адрес: Шушары Первомайская ул 8, Санкт-Петербург

Геокодирование:  74%|███████▍  | 14766/19990 [37:19<31:57,  2.72it/s]

[14770] Геокодируем адрес: Парголово Заречная ул 13к3, Санкт-Петербург

Геокодирование:  74%|███████▍  | 14771/19990 [37:20<26:32,  3.28it/s]

[14773] Геокодируем адрес: Новоизмайловский пр-т 25, Санкт-Петербург

Геокодирование:  74%|███████▍  | 14774/19990 [37:21<28:04,  3.10it/s]

[14778] Геокодируем адрес: Витебский пр-т 81к1, Санкт-Петербург

Геокодирование:  74%|███████▍  | 14779/19990 [37:22<23:28,  3.70it/s]

[14780] Геокодируем адрес: Шушары Вишерская ул 22, Санкт-Петербург

Геокодирование:  74%|███████▍  | 14781/19990 [37:23<27:19,  3.18it/s]

[14784] Геокодируем адрес: Пушкин Саперная ул 36/2, Санкт-Петербург

Геокодирование:  74%|███████▍  | 14785/19990 [37:24<26:47,  3.24it/s]

[14786] Геокодируем адрес: Головнина б-р, Санкт-Петербург

Геокодирование:  74%|███████▍  | 14787/19990 [37:25<27:44,  3.13it/s]

[14787] Геокодируем адрес: Пушкин Гренадерская ул 28к5, Санкт-Петербург

Геокодирование:  74%|███████▍  | 14788/19990 [37:26<34:39,  2.50it/s]

[14789] Геокодируем адрес: Пушкин Александровский б-р, Санкт-Петербург

Геокодирование:  74%|███████▍  | 14790/19990 [37:27<37:20,  2.32it/s]

[14790] Геокодируем адрес: Невский пр-т 61, Санкт-Петербург

Геокодирование:  74%|███████▍  | 14791/19990 [37:28<48:21,  1.79it/s]

Автосохранение после 14790 строк...
[14793] Геокодируем адрес: Маршала Мерецкого ул, Санкт-Петербург

Геокодирование:  74%|███████▍  | 14794/19990 [37:29<38:09,  2.27it/s]

[14795] Геокодируем адрес: Парголово Заречная ул 42к2, Санкт-Петербург

Геокодирование:  74%|███████▍  | 14796/19990 [37:30<38:57,  2.22it/s]

[14798] Геокодируем адрес: Шушары Первомайская ул 26, Санкт-Петербург

Геокодирование:  74%|███████▍  | 14799/19990 [37:31<35:13,  2.46it/s]

[14805] Геокодируем адрес: Белоостров Танкистов ул, Санкт-Петербург

Геокодирование:  74%|███████▍  | 14806/19990 [37:32<22:00,  3.92it/s]

[14810] Геокодируем адрес: Петергоф Аврова ул 32, Санкт-Петербург

Геокодирование:  74%|███████▍  | 14811/19990 [37:33<21:12,  4.07it/s]

[14815] Геокодируем адрес: Товарищеский пр-т 28к1, Санкт-Петербург

Геокодирование:  74%|███████▍  | 14821/19990 [37:34<14:11,  6.07it/s]

Автосохранение после 14820 строк...
[14830] Геокодируем адрес: Тореза пр-т 40к1, Санкт-Петербург

Геокодирование:  74%|███████▍  | 14831/19990 [37:35<10:16,  8.37it/s]

[14832] Геокодируем адрес: Павловск Елизаветинская ул, Санкт-Петербург

Геокодирование:  74%|███████▍  | 14833/19990 [37:36<14:18,  6.01it/s]

[14837] Геокодируем адрес: Ветеранов пр-т 67/1, Санкт-Петербург

Геокодирование:  74%|███████▍  | 14838/19990 [37:38<21:44,  3.95it/s]

[14838] Геокодируем адрес: Шушары Первомайская ул 7А, Санкт-Петербург

Геокодирование:  74%|███████▍  | 14839/19990 [37:39<26:02,  3.30it/s]

[14841] Геокодируем адрес: Шушары Пушкинская ул 38В, Санкт-Петербург

Геокодирование:  74%|███████▍  | 14842/19990 [37:40<25:56,  3.31it/s]

[14849] Геокодируем адрес: Ломоносов Жоры Антоненко ул, Санкт-Петербург

Геокодирование:  74%|███████▍  | 14850/19990 [37:41<18:25,  4.65it/s]

[14850] Геокодируем адрес: Сестрорецк Дубковское ш, Санкт-Петербург

Геокодирование:  74%|███████▍  | 14851/19990 [37:42<26:09,  3.27it/s]

Автосохранение после 14850 строк...
[14851] Геокодируем адрес: Пушкин Саперная ул, Санкт-Петербург

Геокодирование:  74%|███████▍  | 14852/19990 [37:43<30:32,  2.80it/s]

[14857] Геокодируем адрес: Шушары Школьная ул 17, Санкт-Петербург

Геокодирование:  74%|███████▍  | 14858/19990 [37:44<22:43,  3.76it/s]

[14860] Геокодируем адрес: Искровский пр-т 15к1, Санкт-Петербург

Геокодирование:  74%|███████▍  | 14861/19990 [37:45<24:01,  3.56it/s]

[14865] Геокодируем адрес: Московский пр-т 73к5, Санкт-Петербург

Геокодирование:  74%|███████▍  | 14866/19990 [37:46<21:06,  4.05it/s]

[14867] Геокодируем адрес: Тореза пр-т 40к1, Санкт-Петербург

Геокодирование:  74%|███████▍  | 14868/19990 [37:47<24:25,  3.49it/s]

[14870] Геокодируем адрес: Петергоф Самсониевская ул 3, Санкт-Петербург

Геокодирование:  74%|███████▍  | 14871/19990 [37:48<26:41,  3.20it/s]

[14871] Геокодируем адрес: леснозоводская ул 1, Санкт-Петербург

Геокодирование:  74%|███████▍  | 14872/19990 [37:49<31:02,  2.75it/s]

[14872] Геокодируем адрес: Петергоф Аврова ул 32, Санкт-Петербург

Геокодирование:  74%|███████▍  | 14873/19990 [37:50<42:13,  2.02it/s]

[14878] Геокодируем адрес: Тореза пр-т 102к4, Санкт-Петербург

Геокодирование:  74%|███████▍  | 14879/19990 [37:51<25:32,  3.34it/s]

[14880] Геокодируем адрес: Тореза пр-т 102к4, Санкт-Петербург

Геокодирование:  74%|███████▍  | 14881/19990 [37:52<30:35,  2.78it/s]

Автосохранение после 14880 строк...
[14887] Геокодируем адрес: Шушары Первомайская ул 8, Санкт-Петербург

Геокодирование:  74%|███████▍  | 14888/19990 [37:53<20:44,  4.10it/s]

[14888] Геокодируем адрес: Ленинский пр-т 78к1, Санкт-Петербург

Геокодирование:  74%|███████▍  | 14889/19990 [37:54<25:50,  3.29it/s]

[14890] Геокодируем адрес: Петергоф Аврова ул 32, Санкт-Петербург

Геокодирование:  74%|███████▍  | 14891/19990 [37:55<29:41,  2.86it/s]

[14893] Геокодируем адрес: Сестрорецк Мосина ул, Санкт-Петербург

Геокодирование:  75%|███████▍  | 14894/19990 [37:56<28:53,  2.94it/s]

[14897] Геокодируем адрес: Новоизмайловский пр-т 85, Санкт-Петербург

Геокодирование:  75%|███████▍  | 14898/19990 [37:57<28:28,  2.98it/s]

[14899] Геокодируем адрес: Варшавская ул 39/2/50, Санкт-Петербург

Геокодирование:  75%|███████▍  | 14900/19990 [37:58<31:45,  2.67it/s]

[14907] Геокодируем адрес: Большой Сампсониевский пр-т 83, Санкт-Петербург

Геокодирование:  75%|███████▍  | 14911/19990 [38:01<23:36,  3.58it/s]

Автосохранение после 14910 строк...
[14911] Геокодируем адрес: Большевиков пр-т 21, Санкт-Петербург

Геокодирование:  75%|███████▍  | 14912/19990 [38:02<30:03,  2.82it/s]

[14918] Геокодируем адрес: Загородный пр-т 21-23, Санкт-Петербург

Геокодирование:  75%|███████▍  | 14919/19990 [38:03<21:19,  3.96it/s]

[14919] Геокодируем адрес: Петергоф Ропшинское ш 10, Санкт-Петербург

Геокодирование:  75%|███████▍  | 14920/19990 [38:04<25:37,  3.30it/s]

[14920] Геокодируем адрес: Петергоф Ропшинское ш 10, Санкт-Петербург

Геокодирование:  75%|███████▍  | 14921/19990 [38:05<33:38,  2.51it/s]

[14921] Геокодируем адрес: Петергоф Ропшинское ш 10, Санкт-Петербург

Геокодирование:  75%|███████▍  | 14922/19990 [38:06<39:27,  2.14it/s]

[14925] Геокодируем адрес: Петергоф Санкт-Петербургский пр-т 4А, Санкт-Петербург

Геокодирование:  75%|███████▍  | 14926/19990 [38:07<33:03,  2.55it/s]

[14928] Геокодируем адрес: Художников пр-т 34, Санкт-Петербург

Геокодирование:  75%|███████▍  | 14929/19990 [38:08<31:32,  2.67it/s]

[14931] Геокодируем адрес: Дачный пр-т 36к5, Санкт-Петербург

Геокодирование:  75%|███████▍  | 14932/19990 [38:09<28:04,  3.00it/s]

[14932] Геокодируем адрес: 5-я линия ВО 46, Санкт-Петербург

RateLimiter caught an error, retrying (0/2 tries). Called with (*('5-я линия ВО 46, Санкт-Петербург',), **{}).
Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connection.py", line 516, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1374, in getresponse
    response.begin()
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1278, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1134, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 367, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=5-%D1%8F+%D0%BB%D0%B8%D0%BD%D0%B8%D1%8F+%D0%92%D0%9E+46%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 482, in _request
    resp = self.session.get(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=5-%D1%8F+%D0%BB%D0%B8%D0%BD%D0%B8%D1%8F+%D0%92%D0%9E+46%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\extra\rate_limiter.py", line 136, in _retries_gen
    yield i  # Run the function.
    ^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\extra\rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\geocoders\nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\geocoders\base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 472, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 494, in _request
    raise GeocoderUnavailable(message)
geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=5-%D1%8F+%D0%BB%D0%B8%D0%BD%D0%B8%D1%8F+%D0%92%D0%9E+46%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))
RateLimiter caught an error, retrying (1/2 tries). Called with (*('5-я линия ВО 46, Санкт-Петербург',), **{}).
Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connection.py", line 516, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1374, in getresponse
    response.begin()
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1278, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1134, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 367, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=5-%D1%8F+%D0%BB%D0%B8%D0%BD%D0%B8%D1%8F+%D0%92%D0%9E+46%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 482, in _request
    resp = self.session.get(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=5-%D1%8F+%D0%BB%D0%B8%D0%BD%D0%B8%D1%8F+%D0%92%D0%9E+46%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\extra\rate_limiter.py", line 136, in _retries_gen
    yield i  # Run the function.
    ^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\extra\rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\geocoders\nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\geocoders\base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 472, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 494, in _request
    raise GeocoderUnavailable(message)
geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=5-%D1%8F+%D0%BB%D0%B8%D0%BD%D0%B8%D1%8F+%D0%92%D0%9E+46%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))
RateLimiter swallowed an error after 2 retries. Called with (*('5-я линия ВО 46, Санкт-Петербург',), **{}).
Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connection.py", line 516, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1374, in getresponse
    response.begin()
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1278, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1134, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 367, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

[14934] Геокодируем адрес: Балтийский б-р, Санкт-Петербург

Геокодирование:  75%|███████▍  | 14935/19990 [38:30<3:10:07,  2.26s/it]

[14937] Геокодируем адрес: Плесецкая ул 14стр1, Санкт-Петербург

Геокодирование:  75%|███████▍  | 14941/19990 [38:31<1:26:24,  1.03s/it]

Автосохранение после 14940 строк...
[14948] Геокодируем адрес: Металлострой Северный пр-д, Санкт-Петербург

Геокодирование:  75%|███████▍  | 14949/19990 [38:32<42:18,  1.99it/s]

[14949] Геокодируем адрес: Красное Село Лермонтова ул 9к2, Санкт-Петербург

Геокодирование:  75%|███████▍  | 14950/19990 [38:33<47:16,  1.78it/s]

[14953] Геокодируем адрес: Парголово Валерия Гаврилина ул 15, Санкт-Петербург

Геокодирование:  75%|███████▍  | 14954/19990 [38:34<38:28,  2.18it/s]

[14954] Геокодируем адрес: Пушкин Саперная ул 36к1, Санкт-Петербург

Геокодирование:  75%|███████▍  | 14955/19990 [38:35<43:52,  1.91it/s]

[14955] Геокодируем адрес: Шушары Чудовская ул 15, Санкт-Петербург

Геокодирование:  75%|███████▍  | 14956/19990 [38:36<47:27,  1.77it/s]

[14957] Геокодируем адрес: Колпино Машиностроителей ул, Санкт-Петербург

Геокодирование:  75%|███████▍  | 14958/19990 [38:37<44:44,  1.87it/s]

[14958] Геокодируем адрес: Петергоф Привокзальная пл 2, Санкт-Петербург

Геокодирование:  75%|███████▍  | 14959/19990 [38:40<1:28:31,  1.06s/it]

[14961] Геокодируем адрес: Кронштадт Зосимова ул 4, Санкт-Петербург

Геокодирование:  75%|███████▍  | 14962/19990 [38:41<1:02:36,  1.34it/s]

[14963] Геокодируем адрес: Ириновский пр-т 34, Санкт-Петербург

Геокодирование:  75%|███████▍  | 14964/19990 [38:43<1:09:28,  1.21it/s]

[14965] Геокодируем адрес: Крестовский пр-т 23, Санкт-Петербург

Геокодирование:  75%|███████▍  | 14971/19990 [38:45<32:56,  2.54it/s]

Автосохранение после 14970 строк...
[14976] Геокодируем адрес: Металлострой Северный пр-д, Санкт-Петербург

Геокодирование:  75%|███████▍  | 14977/19990 [38:46<22:41,  3.68it/s]

[14977] Геокодируем адрес: Металлострой Северный пр-д, Санкт-Петербург

Геокодирование:  75%|███████▍  | 14978/19990 [38:46<27:38,  3.02it/s]

[14978] Геокодируем адрес: Металлострой Северный пр-д, Санкт-Петербург

Геокодирование:  75%|███████▍  | 14979/19990 [38:48<35:33,  2.35it/s]

[14986] Геокодируем адрес: Стачек пр-т 105к1, Санкт-Петербург

Геокодирование:  75%|███████▍  | 14987/19990 [38:49<22:18,  3.74it/s]

[14992] Геокодируем адрес: Юрия Гагарина пр-т 14к1, Санкт-Петербург

Геокодирование:  75%|███████▌  | 14993/19990 [38:50<19:07,  4.35it/s]

[14993] Геокодируем адрес: Шушары Витебский пр-т, Санкт-Петербург

Геокодирование:  75%|███████▌  | 14994/19990 [38:51<22:34,  3.69it/s]

[14998] Геокодируем адрес: Шушары Вишерская ул 10, Санкт-Петербург

Геокодирование:  75%|███████▌  | 14999/19990 [38:52<21:58,  3.79it/s]

[15000] Геокодируем адрес: Колпино Финляндская ул 38, Санкт-Петербург

Геокодирование:  75%|███████▌  | 15001/19990 [38:53<25:24,  3.27it/s]

Автосохранение после 15000 строк...
[15006] Геокодируем адрес: энгельса пр-т 126, Санкт-Петербург

Геокодирование:  75%|███████▌  | 15007/19990 [38:54<21:39,  3.83it/s]

[15015] Геокодируем адрес: Энгельса пр-т 132к1, Санкт-Петербург

Геокодирование:  75%|███████▌  | 15031/19990 [38:55<07:15, 11.38it/s]

Автосохранение после 15030 строк...
[15032] Геокодируем адрес: Торфяная дор 17к1, Санкт-Петербург

Геокодирование:  75%|███████▌  | 15035/19990 [38:56<08:43,  9.46it/s]

[15039] Геокодируем адрес: Загребский б-р 9, Санкт-Петербург

Геокодирование:  75%|███████▌  | 15040/19990 [38:58<14:54,  5.53it/s]

[15043] Геокодируем адрес: Светлановский пр-т 109к3, Санкт-Петербург

Геокодирование:  75%|███████▌  | 15044/19990 [38:59<15:43,  5.24it/s]

[15045] Геокодируем адрес: Пархоменко ул 5, Санкт-Петербург

Геокодирование:  75%|███████▌  | 15046/19990 [39:00<19:26,  4.24it/s]

[15046] Геокодируем адрес: Комендантский пр-т 28к1, Санкт-Петербург

Геокодирование:  75%|███████▌  | 15048/19990 [39:01<24:16,  3.39it/s]

[15053] Геокодируем адрес: Пушкин Кедринская ул 8, Санкт-Петербург

Геокодирование:  75%|███████▌  | 15054/19990 [39:02<19:03,  4.32it/s]

[15056] Геокодируем адрес: Петергоф Привокзальная пл 2А, Санкт-Петербург

Геокодирование:  75%|███████▌  | 15057/19990 [39:03<21:27,  3.83it/s]

[15057] Геокодируем адрес: Петергоф Привокзальная пл 2А, Санкт-Петербург

Геокодирование:  75%|███████▌  | 15058/19990 [39:04<26:18,  3.12it/s]

[15059] Геокодируем адрес: Петергоф Привокзальная пл 2А, Санкт-Петербург

Геокодирование:  75%|███████▌  | 15060/19990 [39:05<30:36,  2.69it/s]

[15060] Геокодируем адрес: Энергетиков пр-т 72, Санкт-Петербург

Геокодирование:  75%|███████▌  | 15061/19990 [39:07<44:07,  1.86it/s]

Автосохранение после 15060 строк...
[15061] Геокодируем адрес: Петергоф Привокзальная пл 2А, Санкт-Петербург

Геокодирование:  75%|███████▌  | 15062/19990 [39:08<55:39,  1.48it/s]

[15064] Геокодируем адрес: Металлострой Садовая ул, Санкт-Петербург

Геокодирование:  75%|███████▌  | 15065/19990 [39:09<44:09,  1.86it/s]

[15066] Геокодируем адрес: Металлострой Садовая ул, Санкт-Петербург

Геокодирование:  75%|███████▌  | 15067/19990 [39:11<58:44,  1.40it/s]

[15067] Геокодируем адрес: Петровский пр-т 24к3, Санкт-Петербург

Геокодирование:  75%|███████▌  | 15068/19990 [39:14<1:18:40,  1.04it/s]

[15068] Геокодируем адрес: Металлострой Садовая ул, Санкт-Петербург

Геокодирование:  75%|███████▌  | 15069/19990 [39:15<1:19:53,  1.03it/s]

[15071] Геокодируем адрес: Металлострой Садовая ул, Санкт-Петербург

Геокодирование:  75%|███████▌  | 15072/19990 [39:16<55:20,  1.48it/s]

[15072] Геокодируем адрес: Металлострой Северный пр-д, Санкт-Петербург

Геокодирование:  75%|███████▌  | 15073/19990 [39:17<1:03:19,  1.29it/s]

[15073] Геокодируем адрес: Металлострой Северный пр-д, Санкт-Петербург

Геокодирование:  75%|███████▌  | 15074/19990 [39:18<1:08:36,  1.19it/s]

[15074] Геокодируем адрес: Металлострой Северный пр-д, Санкт-Петербург

Геокодирование:  75%|███████▌  | 15075/19990 [39:19<1:16:37,  1.07it/s]

[15075] Геокодируем адрес: Металлострой Северный пр-д, Санкт-Петербург

Геокодирование:  75%|███████▌  | 15076/19990 [39:20<1:18:32,  1.04it/s]

[15076] Геокодируем адрес: Металлострой Железнодорожная ул, Санкт-Петербург

Геокодирование:  75%|███████▌  | 15091/19990 [39:21<13:29,  6.05it/s]

Автосохранение после 15090 строк...
[15098] Геокодируем адрес: Комендантский пр-т 33к1Б, Санкт-Петербург

Геокодирование:  76%|███████▌  | 15099/19990 [39:22<10:34,  7.71it/s]

[15099] Геокодируем адрес: Народного Ополчения пр-т 133, Санкт-Петербург

RateLimiter caught an error, retrying (0/2 tries). Called with (*('Народного Ополчения пр-т 133, Санкт-Петербург',), **{}).
Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connection.py", line 516, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1374, in getresponse
    response.begin()
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1278, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1134, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 367, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=%D0%9D%D0%B0%D1%80%D0%BE%D0%B4%D0%BD%D0%BE%D0%B3%D0%BE+%D0%9E%D0%BF%D0%BE%D0%BB%D1%87%D0%B5%D0%BD%D0%B8%D1%8F+%D0%BF%D1%80-%D1%82+133%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 482, in _request
    resp = self.session.get(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=%D0%9D%D0%B0%D1%80%D0%BE%D0%B4%D0%BD%D0%BE%D0%B3%D0%BE+%D0%9E%D0%BF%D0%BE%D0%BB%D1%87%D0%B5%D0%BD%D0%B8%D1%8F+%D0%BF%D1%80-%D1%82+133%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\extra\rate_limiter.py", line 136, in _retries_gen
    yield i  # Run the function.
    ^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\extra\rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\geocoders\nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\geocoders\base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 472, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 494, in _request
    raise GeocoderUnavailable(message)
geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=%D0%9D%D0%B0%D1%80%D0%BE%D0%B4%D0%BD%D0%BE%D0%B3%D0%BE+%D0%9E%D0%BF%D0%BE%D0%BB%D1%87%D0%B5%D0%BD%D0%B8%D1%8F+%D0%BF%D1%80-%D1%82+133%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))
RateLimiter caught an error, retrying (1/2 tries). Called with (*('Народного Ополчения пр-т 133, Санкт-Петербург',), **{}).
Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connection.py", line 516, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1374, in getresponse
    response.begin()
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1278, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1134, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 367, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=%D0%9D%D0%B0%D1%80%D0%BE%D0%B4%D0%BD%D0%BE%D0%B3%D0%BE+%D0%9E%D0%BF%D0%BE%D0%BB%D1%87%D0%B5%D0%BD%D0%B8%D1%8F+%D0%BF%D1%80-%D1%82+133%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 482, in _request
    resp = self.session.get(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=%D0%9D%D0%B0%D1%80%D0%BE%D0%B4%D0%BD%D0%BE%D0%B3%D0%BE+%D0%9E%D0%BF%D0%BE%D0%BB%D1%87%D0%B5%D0%BD%D0%B8%D1%8F+%D0%BF%D1%80-%D1%82+133%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\extra\rate_limiter.py", line 136, in _retries_gen
    yield i  # Run the function.
    ^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\extra\rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\geocoders\nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\geocoders\base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 472, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 494, in _request
    raise GeocoderUnavailable(message)
geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=%D0%9D%D0%B0%D1%80%D0%BE%D0%B4%D0%BD%D0%BE%D0%B3%D0%BE+%D0%9E%D0%BF%D0%BE%D0%BB%D1%87%D0%B5%D0%BD%D0%B8%D1%8F+%D0%BF%D1%80-%D1%82+133%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))
Геокодирование:  76%|███████▌  | 15099/19990 [39:41<10:34,  7.71it/s]RateLimiter swallowed an error after 2 retries. Called with (*('Народного Ополчения пр-т 133, Санкт-Петербург',), **{}).
Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connection.py", line 516, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1374, in getresponse
    response.begin()
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1278, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1134, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 367, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 841, in urlopen
    retries = retries.increment(

[15101] Геокодируем адрес: Колпино Вознесенское ш 55, Санкт-Петербург

RateLimiter caught an error, retrying (0/2 tries). Called with (*('Колпино Вознесенское ш 55, Санкт-Петербург',), **{}).
Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connection.py", line 516, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1374, in getresponse
    response.begin()
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1278, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1134, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 367, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=%D0%9A%D0%BE%D0%BB%D0%BF%D0%B8%D0%BD%D0%BE+%D0%92%D0%BE%D0%B7%D0%BD%D0%B5%D1%81%D0%B5%D0%BD%D1%81%D0%BA%D0%BE%D0%B5+%D1%88+55%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 482, in _request
    resp = self.session.get(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=%D0%9A%D0%BE%D0%BB%D0%BF%D0%B8%D0%BD%D0%BE+%D0%92%D0%BE%D0%B7%D0%BD%D0%B5%D1%81%D0%B5%D0%BD%D1%81%D0%BA%D0%BE%D0%B5+%D1%88+55%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\extra\rate_limiter.py", line 136, in _retries_gen
    yield i  # Run the function.
    ^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\extra\rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\geocoders\nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\geocoders\base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 472, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 494, in _request
    raise GeocoderUnavailable(message)
geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=%D0%9A%D0%BE%D0%BB%D0%BF%D0%B8%D0%BD%D0%BE+%D0%92%D0%BE%D0%B7%D0%BD%D0%B5%D1%81%D0%B5%D0%BD%D1%81%D0%BA%D0%BE%D0%B5+%D1%88+55%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))
RateLimiter caught an error, retrying (1/2 tries). Called with (*('Колпино Вознесенское ш 55, Санкт-Петербург',), **{}).
Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connection.py", line 516, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1374, in getresponse
    response.begin()
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1278, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1134, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 367, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=%D0%9A%D0%BE%D0%BB%D0%BF%D0%B8%D0%BD%D0%BE+%D0%92%D0%BE%D0%B7%D0%BD%D0%B5%D1%81%D0%B5%D0%BD%D1%81%D0%BA%D0%BE%D0%B5+%D1%88+55%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 482, in _request
    resp = self.session.get(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=%D0%9A%D0%BE%D0%BB%D0%BF%D0%B8%D0%BD%D0%BE+%D0%92%D0%BE%D0%B7%D0%BD%D0%B5%D1%81%D0%B5%D0%BD%D1%81%D0%BA%D0%BE%D0%B5+%D1%88+55%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\extra\rate_limiter.py", line 136, in _retries_gen
    yield i  # Run the function.
    ^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\extra\rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\geocoders\nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\geocoders\base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 472, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 494, in _request
    raise GeocoderUnavailable(message)
geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=%D0%9A%D0%BE%D0%BB%D0%BF%D0%B8%D0%BD%D0%BE+%D0%92%D0%BE%D0%B7%D0%BD%D0%B5%D1%81%D0%B5%D0%BD%D1%81%D0%BA%D0%BE%D0%B5+%D1%88+55%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))
RateLimiter swallowed an error after 2 retries. Called with (*('Колпино Вознесенское ш 55, Санкт-Петербург',), **{}).
Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connection.py", line 516, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1374, in getresponse
    response.begin()
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1278, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1134, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 367, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^

[15106] Геокодируем адрес: Суворовский пр-т 62, Санкт-Петербург

RateLimiter caught an error, retrying (0/2 tries). Called with (*('Суворовский пр-т 62, Санкт-Петербург',), **{}).
Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connection.py", line 516, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1374, in getresponse
    response.begin()
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1278, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1134, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 367, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=%D0%A1%D1%83%D0%B2%D0%BE%D1%80%D0%BE%D0%B2%D1%81%D0%BA%D0%B8%D0%B9+%D0%BF%D1%80-%D1%82+62%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 482, in _request
    resp = self.session.get(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=%D0%A1%D1%83%D0%B2%D0%BE%D1%80%D0%BE%D0%B2%D1%81%D0%BA%D0%B8%D0%B9+%D0%BF%D1%80-%D1%82+62%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\extra\rate_limiter.py", line 136, in _retries_gen
    yield i  # Run the function.
    ^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\extra\rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\geocoders\nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\geocoders\base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 472, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 494, in _request
    raise GeocoderUnavailable(message)
geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=%D0%A1%D1%83%D0%B2%D0%BE%D1%80%D0%BE%D0%B2%D1%81%D0%BA%D0%B8%D0%B9+%D0%BF%D1%80-%D1%82+62%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))
RateLimiter caught an error, retrying (1/2 tries). Called with (*('Суворовский пр-т 62, Санкт-Петербург',), **{}).
Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connection.py", line 516, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1374, in getresponse
    response.begin()
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1278, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1134, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 367, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=%D0%A1%D1%83%D0%B2%D0%BE%D1%80%D0%BE%D0%B2%D1%81%D0%BA%D0%B8%D0%B9+%D0%BF%D1%80-%D1%82+62%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 482, in _request
    resp = self.session.get(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=%D0%A1%D1%83%D0%B2%D0%BE%D1%80%D0%BE%D0%B2%D1%81%D0%BA%D0%B8%D0%B9+%D0%BF%D1%80-%D1%82+62%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\extra\rate_limiter.py", line 136, in _retries_gen
    yield i  # Run the function.
    ^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\extra\rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\geocoders\nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\geocoders\base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 472, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 494, in _request
    raise GeocoderUnavailable(message)
geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=%D0%A1%D1%83%D0%B2%D0%BE%D1%80%D0%BE%D0%B2%D1%81%D0%BA%D0%B8%D0%B9+%D0%BF%D1%80-%D1%82+62%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))
RateLimiter swallowed an error after 2 retries. Called with (*('Суворовский пр-т 62, Санкт-Петербург',), **{}).
Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connection.py", line 516, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1374, in getresponse
    response.begin()
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1278, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1134, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 367, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

[15109] Геокодируем адрес: Екатерининский пр-т 2, Санкт-Петербург

RateLimiter caught an error, retrying (0/2 tries). Called with (*('Екатерининский пр-т 2, Санкт-Петербург',), **{}).
Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connection.py", line 516, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1374, in getresponse
    response.begin()
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1278, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1134, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 367, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=%D0%95%D0%BA%D0%B0%D1%82%D0%B5%D1%80%D0%B8%D0%BD%D0%B8%D0%BD%D1%81%D0%BA%D0%B8%D0%B9+%D0%BF%D1%80-%D1%82+2%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 482, in _request
    resp = self.session.get(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=%D0%95%D0%BA%D0%B0%D1%82%D0%B5%D1%80%D0%B8%D0%BD%D0%B8%D0%BD%D1%81%D0%BA%D0%B8%D0%B9+%D0%BF%D1%80-%D1%82+2%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\extra\rate_limiter.py", line 136, in _retries_gen
    yield i  # Run the function.
    ^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\extra\rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\geocoders\nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\geocoders\base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 472, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 494, in _request
    raise GeocoderUnavailable(message)
geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=%D0%95%D0%BA%D0%B0%D1%82%D0%B5%D1%80%D0%B8%D0%BD%D0%B8%D0%BD%D1%81%D0%BA%D0%B8%D0%B9+%D0%BF%D1%80-%D1%82+2%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))
RateLimiter caught an error, retrying (1/2 tries). Called with (*('Екатерининский пр-т 2, Санкт-Петербург',), **{}).
Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connection.py", line 516, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1374, in getresponse
    response.begin()
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1278, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1134, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 367, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=%D0%95%D0%BA%D0%B0%D1%82%D0%B5%D1%80%D0%B8%D0%BD%D0%B8%D0%BD%D1%81%D0%BA%D0%B8%D0%B9+%D0%BF%D1%80-%D1%82+2%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 482, in _request
    resp = self.session.get(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=%D0%95%D0%BA%D0%B0%D1%82%D0%B5%D1%80%D0%B8%D0%BD%D0%B8%D0%BD%D1%81%D0%BA%D0%B8%D0%B9+%D0%BF%D1%80-%D1%82+2%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\extra\rate_limiter.py", line 136, in _retries_gen
    yield i  # Run the function.
    ^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\extra\rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\geocoders\nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\geocoders\base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 472, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 494, in _request
    raise GeocoderUnavailable(message)
geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=%D0%95%D0%BA%D0%B0%D1%82%D0%B5%D1%80%D0%B8%D0%BD%D0%B8%D0%BD%D1%81%D0%BA%D0%B8%D0%B9+%D0%BF%D1%80-%D1%82+2%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))
Геокодирование:  76%|███████▌  | 15110/19990 [40:43<5:33:58,  4.11s/it]

[15112] Геокодируем адрес: Маршала Блюхера пр-т, Санкт-Петербург

Геокодирование:  76%|███████▌  | 15113/19990 [40:44<4:15:19,  3.14s/it]

[15116] Геокодируем адрес: Парголово Федора Абрамова ул 21к3, Санкт-Петербург

Геокодирование:  76%|███████▌  | 15117/19990 [40:45<2:58:18,  2.20s/it]

[15120] Геокодируем адрес: Юнтоловский пр-т 49к4, Санкт-Петербург

Геокодирование:  76%|███████▌  | 15121/19990 [40:46<2:08:31,  1.58s/it]

Автосохранение после 15120 строк...
[15123] Геокодируем адрес: Ленинский пр-т 78к1, Санкт-Петербург

Геокодирование:  76%|███████▌  | 15124/19990 [40:47<1:41:38,  1.25s/it]

[15131] Геокодируем адрес: Ленинский пр-т 77к1, Санкт-Петербург

Геокодирование:  76%|███████▌  | 15132/19990 [40:48<56:47,  1.43it/s]

[15139] Геокодируем адрес: Литейный пр-т 59, Санкт-Петербург

Геокодирование:  76%|███████▌  | 15151/19990 [40:49<21:22,  3.77it/s]

Автосохранение после 15150 строк...
[15156] Геокодируем адрес: Красное Село Лермонтова ул 10, Санкт-Петербург

Геокодирование:  76%|███████▌  | 15157/19990 [40:50<19:09,  4.20it/s]

[15157] Геокодируем адрес: Красное Село Лермонтова ул 11к1В, Санкт-Петербург

Геокодирование:  76%|███████▌  | 15160/19990 [40:51<18:51,  4.27it/s]

[15162] Геокодируем адрес: Парголово Парашютная ул, Санкт-Петербург

Геокодирование:  76%|███████▌  | 15163/19990 [40:52<20:41,  3.89it/s]

[15169] Геокодируем адрес: Ветеранов пр-т 131, Санкт-Петербург

Геокодирование:  76%|███████▌  | 15170/19990 [40:53<18:15,  4.40it/s]

[15173] Геокодируем адрес: Петергоф Ропшинское ш 3к9, Санкт-Петербург

Геокодирование:  76%|███████▌  | 15174/19990 [40:54<17:51,  4.50it/s]

[15174] Геокодируем адрес: Петергоф Ропшинское ш 3к9, Санкт-Петербург

Геокодирование:  76%|███████▌  | 15175/19990 [40:55<22:41,  3.54it/s]

[15175] Геокодируем адрес: Петергоф Ропшинское ш 3к9, Санкт-Петербург

Геокодирование:  76%|███████▌  | 15176/19990 [40:56<28:01,  2.86it/s]

[15177] Геокодируем адрес: Петергоф Ропшинское ш 3к9, Санкт-Петербург

Геокодирование:  76%|███████▌  | 15178/19990 [40:57<30:57,  2.59it/s]

[15178] Геокодируем адрес: Петергоф Ропшинское ш 3к9, Санкт-Петербург

Геокодирование:  76%|███████▌  | 15179/19990 [40:58<37:09,  2.16it/s]

[15180] Геокодируем адрес: Славы пр-т 2к1, Санкт-Петербург

Геокодирование:  76%|███████▌  | 15181/19990 [40:59<41:12,  1.94it/s]

Автосохранение после 15180 строк...
[15182] Геокодируем адрес: Тореза пр-т 40к1, Санкт-Петербург

Геокодирование:  76%|███████▌  | 15183/19990 [41:00<37:40,  2.13it/s]

[15189] Геокодируем адрес: Парголово Меркурьева ул, Санкт-Петербург

Геокодирование:  76%|███████▌  | 15190/19990 [41:01<21:55,  3.65it/s]

[15190] Геокодируем адрес: Парголово Михаила Дудина ул, Санкт-Петербург

Геокодирование:  76%|███████▌  | 15191/19990 [41:02<28:13,  2.83it/s]

[15193] Геокодируем адрес: Стачек пр-т 105к2, Санкт-Петербург

Геокодирование:  76%|███████▌  | 15194/19990 [41:03<27:43,  2.88it/s]

[15198] Геокодируем адрес: Медиков пр-т 10к1, Санкт-Петербург

Геокодирование:  76%|███████▌  | 15199/19990 [41:04<23:15,  3.43it/s]

[15201] Геокодируем адрес: Большевиков пр-т 61, Санкт-Петербург

Геокодирование:  76%|███████▌  | 15202/19990 [41:05<24:25,  3.27it/s]

[15202] Геокодируем адрес: Большевиков пр-т 65к4, Санкт-Петербург

Геокодирование:  76%|███████▌  | 15211/19990 [41:06<13:46,  5.78it/s]

Автосохранение после 15210 строк...
[15212] Геокодируем адрес: Колпино Трудящихся б-р 12, Санкт-Петербург

Геокодирование:  76%|███████▌  | 15213/19990 [41:07<18:13,  4.37it/s]

[15218] Геокодируем адрес: Авиаконструкторов пр-т 4к1, Санкт-Петербург

Геокодирование:  76%|███████▌  | 15219/19990 [41:08<15:50,  5.02it/s]

[15222] Геокодируем адрес: Авиаконструкторов пр-т 4к1, Санкт-Петербург

Геокодирование:  76%|███████▌  | 15223/19990 [41:09<16:43,  4.75it/s]

[15233] Геокодируем адрес: Маршала Блюхера пр-т 12зд160, Санкт-Петербург

Геокодирование:  76%|███████▌  | 15234/19990 [41:10<11:09,  7.10it/s]

[15234] Геокодируем адрес: Мечникова пр-т 8/1, Санкт-Петербург

Геокодирование:  76%|███████▌  | 15241/19990 [41:11<11:40,  6.78it/s]

Автосохранение после 15240 строк...
[15244] Геокодируем адрес: Пушкин Гусарская ул 4к13, Санкт-Петербург

Геокодирование:  76%|███████▋  | 15245/19990 [41:12<11:53,  6.65it/s]

[15246] Геокодируем адрес: Пискаревский пр-т 145к6, Санкт-Петербург

Геокодирование:  76%|███████▋  | 15247/19990 [41:13<16:06,  4.91it/s]

[15248] Геокодируем адрес: Петергоф Ропшинское ш 3к9, Санкт-Петербург

Геокодирование:  76%|███████▋  | 15249/19990 [41:14<20:35,  3.84it/s]

[15250] Геокодируем адрес: Юнтоловский пр-т 49к4, Санкт-Петербург

Геокодирование:  76%|███████▋  | 15251/19990 [41:15<23:56,  3.30it/s]

[15251] Геокодируем адрес: Юнтоловский пр-т 49к4, Санкт-Петербург

Геокодирование:  76%|███████▋  | 15252/19990 [41:16<31:01,  2.55it/s]

[15252] Геокодируем адрес: Юнтоловский пр-т 49к4, Санкт-Петербург

Геокодирование:  76%|███████▋  | 15253/19990 [41:17<38:19,  2.06it/s]

[15253] Геокодируем адрес: Юнтоловский пр-т 49к4, Санкт-Петербург

Геокодирование:  76%|███████▋  | 15254/19990 [41:18<45:42,  1.73it/s]

[15254] Геокодируем адрес: Юнтоловский пр-т 49к4, Санкт-Петербург

Геокодирование:  76%|███████▋  | 15255/19990 [41:19<55:00,  1.43it/s]

[15255] Геокодируем адрес: Юнтоловский пр-т 49к4, Санкт-Петербург

Геокодирование:  76%|███████▋  | 15256/19990 [41:20<57:10,  1.38it/s]

[15258] Геокодируем адрес: Юнтоловский пр-т 49к4, Санкт-Петербург

Геокодирование:  76%|███████▋  | 15259/19990 [41:21<42:16,  1.87it/s]

[15260] Геокодируем адрес: Юнтоловский пр-т 49к4, Санкт-Петербург

Геокодирование:  76%|███████▋  | 15261/19990 [41:22<41:15,  1.91it/s]

[15262] Геокодируем адрес: Юнтоловский пр-т 49к4, Санкт-Петербург

Геокодирование:  76%|███████▋  | 15263/19990 [41:23<40:54,  1.93it/s]

[15263] Геокодируем адрес: Юнтоловский пр-т 49к4, Санкт-Петербург

Геокодирование:  76%|███████▋  | 15264/19990 [41:24<47:34,  1.66it/s]

[15265] Геокодируем адрес: Искровский пр-т 32к1, Санкт-Петербург

Геокодирование:  76%|███████▋  | 15266/19990 [41:25<45:42,  1.72it/s]

[15270] Геокодируем адрес: Дачный пр-т 25к4, Санкт-Петербург

Геокодирование:  76%|███████▋  | 15271/19990 [41:26<29:59,  2.62it/s]

Автосохранение после 15270 строк...
[15275] Геокодируем адрес: кондратьевский пр-т 62к2, Санкт-Петербург

Геокодирование:  76%|███████▋  | 15276/19990 [41:27<27:06,  2.90it/s]

[15280] Геокодируем адрес: Королева пр-т 73, Санкт-Петербург

Геокодирование:  76%|███████▋  | 15281/19990 [41:28<21:52,  3.59it/s]

[15286] Геокодируем адрес: Маршала Блюхера пр-т 21, Санкт-Петербург

Геокодирование:  76%|███████▋  | 15287/19990 [41:29<18:37,  4.21it/s]

[15290] Геокодируем адрес: Юнтоловский пр-т 49, Санкт-Петербург

Геокодирование:  76%|███████▋  | 15291/19990 [41:30<17:52,  4.38it/s]

[15291] Геокодируем адрес: Кондратьевский пр-т 68к4, Санкт-Петербург

Геокодирование:  76%|███████▋  | 15292/19990 [41:31<22:21,  3.50it/s]

[15294] Геокодируем адрес: Петергоф Ропшинское ш 3к9, Санкт-Петербург

Геокодирование:  77%|███████▋  | 15301/19990 [41:33<18:25,  4.24it/s]

Автосохранение после 15300 строк...
[15305] Геокодируем адрес: Торфяная дор 17к2, Санкт-Петербург

Геокодирование:  77%|███████▋  | 15306/19990 [41:34<15:58,  4.89it/s]

[15306] Геокодируем адрес: Дальневосточный пр-д, Санкт-Петербург

Геокодирование:  77%|███████▋  | 15308/19990 [41:35<20:17,  3.85it/s]

[15316] Геокодируем адрес: Ленинский пр-т 151, Санкт-Петербург

Геокодирование:  77%|███████▋  | 15317/19990 [41:36<15:23,  5.06it/s]

[15319] Геокодируем адрес: Ленинский пр-т 147, Санкт-Петербург

Геокодирование:  77%|███████▋  | 15320/19990 [41:37<17:54,  4.35it/s]

[15324] Геокодируем адрес: Обуховской Обороны пр-т 291, Санкт-Петербург

Геокодирование:  77%|███████▋  | 15325/19990 [41:38<16:06,  4.83it/s]

[15327] Геокодируем адрес: Большевиков пр-т 25, Санкт-Петербург

Геокодирование:  77%|███████▋  | 15328/19990 [41:39<18:09,  4.28it/s]

[15330] Геокодируем адрес: Загородный пр-т 40, Санкт-Петербург

Геокодирование:  77%|███████▋  | 15331/19990 [41:40<21:00,  3.70it/s]

Автосохранение после 15330 строк...
[15332] Геокодируем адрес: Ветеранов пр-т 88, Санкт-Петербург

Геокодирование:  77%|███████▋  | 15333/19990 [41:42<30:31,  2.54it/s]

[15355] Геокодируем адрес: Солидарности ул 21, Санкт-Петербург

Геокодирование:  77%|███████▋  | 15361/19990 [41:43<08:28,  9.11it/s]

Автосохранение после 15360 строк...
[15363] Геокодируем адрес: Ветеранов пр-т 122, Санкт-Петербург

Геокодирование:  77%|███████▋  | 15364/19990 [41:44<10:48,  7.13it/s]

[15370] Геокодируем адрес: Ленинский пр-т 118, Санкт-Петербург

Геокодирование:  77%|███████▋  | 15371/19990 [41:45<11:04,  6.95it/s]

[15371] Геокодируем адрес: Ленинский пр-т 130к6, Санкт-Петербург
[15372] Геокодируем адрес: Колпино Софийская ул, Санкт-Петербург

Геокодирование:  77%|███████▋  | 15373/19990 [41:47<17:32,  4.39it/s]

[15384] Геокодируем адрес: Петергоф Демьяна Бедного ул, Санкт-Петербург

Геокодирование:  77%|███████▋  | 15385/19990 [41:48<11:55,  6.44it/s]

[15390] Геокодируем адрес: Дунайский пр-т 7к7, Санкт-Петербург

Геокодирование:  77%|███████▋  | 15391/19990 [41:49<12:58,  5.91it/s]

Автосохранение после 15390 строк...
[15392] Геокодируем адрес: Петергоф Царицынская ул 1, Санкт-Петербург

Геокодирование:  77%|███████▋  | 15393/19990 [41:50<14:57,  5.12it/s]

[15393] Геокодируем адрес: Петергоф Царицынская ул 1, Санкт-Петербург

Геокодирование:  77%|███████▋  | 15394/19990 [41:51<19:26,  3.94it/s]

[15394] Геокодируем адрес: Петергоф Царицынская ул 1, Санкт-Петербург

Геокодирование:  77%|███████▋  | 15395/19990 [41:52<24:52,  3.08it/s]

[15395] Геокодируем адрес: Петергоф Царицынская ул 1, Санкт-Петербург

Геокодирование:  77%|███████▋  | 15396/19990 [41:53<31:06,  2.46it/s]

[15396] Геокодируем адрес: Петергоф Царицынская ул 1, Санкт-Петербург

Геокодирование:  77%|███████▋  | 15397/19990 [41:54<37:37,  2.03it/s]

[15397] Геокодируем адрес: Петергоф Царицынская ул, Санкт-Петербург

Геокодирование:  77%|███████▋  | 15398/19990 [41:55<43:24,  1.76it/s]

[15398] Геокодируем адрес: Петергоф Царицынская ул, Санкт-Петербург

Геокодирование:  77%|███████▋  | 15399/19990 [41:56<50:29,  1.52it/s]

[15399] Геокодируем адрес: Петергоф Царицынская ул 1, Санкт-Петербург

Геокодирование:  77%|███████▋  | 15400/19990 [41:57<56:29,  1.35it/s]

[15415] Геокодируем адрес: Красное Село Лермонтова ул 11к2, Санкт-Петербург

Геокодирование:  77%|███████▋  | 15416/19990 [41:58<14:28,  5.27it/s]

[15416] Геокодируем адрес: Пискаревский пр-т 35, Санкт-Петербург

Геокодирование:  77%|███████▋  | 15417/19990 [41:59<17:53,  4.26it/s]

[15418] Геокодируем адрес: Заневский пр-т 18, Санкт-Петербург

Геокодирование:  77%|███████▋  | 15419/19990 [42:00<20:58,  3.63it/s]

[15420] Геокодируем адрес: Просвещения пр-т 32к1, Санкт-Петербург

Геокодирование:  77%|███████▋  | 15421/19990 [42:01<25:08,  3.03it/s]

Автосохранение после 15420 строк...
[15423] Геокодируем адрес: Петергоф Демьяна Бедного ул, Санкт-Петербург

Геокодирование:  77%|███████▋  | 15424/19990 [42:02<23:14,  3.27it/s]

[15425] Геокодируем адрес: Загородный пр-т 21-23, Санкт-Петербург

Геокодирование:  77%|███████▋  | 15426/19990 [42:04<36:30,  2.08it/s]

[15426] Геокодируем адрес: Загородный пр-т 21-23, Санкт-Петербург

Геокодирование:  77%|███████▋  | 15427/19990 [42:05<41:49,  1.82it/s]

[15428] Геокодируем адрес: Поварской пер 14литА, Санкт-Петербург

Геокодирование:  77%|███████▋  | 15429/19990 [42:06<37:41,  2.02it/s]

[15430] Геокодируем адрес: Чернышевского пр-т 17, Санкт-Петербург

Геокодирование:  77%|███████▋  | 15431/19990 [42:07<40:57,  1.86it/s]

[15431] Геокодируем адрес: Чернышевского пр-т 17, Санкт-Петербург

Геокодирование:  77%|███████▋  | 15451/19990 [42:08<08:58,  8.43it/s]

Автосохранение после 15450 строк...
[15458] Геокодируем адрес: Ветеранов пр-т 1к1, Санкт-Петербург

Геокодирование:  77%|███████▋  | 15459/19990 [42:09<08:18,  9.08it/s]

[15460] Геокодируем адрес: Юнтоловский пр-т 49к44, Санкт-Петербург
[15461] Геокодируем адрес: Юнтоловский пр-т 49к44, Санкт-Петербург

Геокодирование:  77%|███████▋  | 15462/19990 [42:11<13:56,  5.41it/s]

[15462] Геокодируем адрес: Космонавтов пр-т 15, Санкт-Петербург

Геокодирование:  77%|███████▋  | 15465/19990 [42:12<17:14,  4.38it/s]

[15468] Геокодируем адрес: Шушары Пушкинская ул, Санкт-Петербург

Геокодирование:  77%|███████▋  | 15469/19990 [42:13<16:33,  4.55it/s]

[15470] Геокодируем адрес: Парголово Толубеевский пр-д, Санкт-Петербург

Геокодирование:  77%|███████▋  | 15471/19990 [42:14<20:17,  3.71it/s]

[15471] Геокодируем адрес: Большевиков пр-т 22к2, Санкт-Петербург

Геокодирование:  77%|███████▋  | 15472/19990 [42:15<25:02,  3.01it/s]

[15472] Геокодируем адрес: Большевиков пр-т 30к4, Санкт-Петербург

Геокодирование:  77%|███████▋  | 15473/19990 [42:16<31:14,  2.41it/s]

[15476] Геокодируем адрес: Металлистов пр-т 89, Санкт-Петербург

Геокодирование:  77%|███████▋  | 15477/19990 [42:17<27:22,  2.75it/s]

[15477] Геокодируем адрес: Ленинский пр-т 118к1, Санкт-Петербург

Геокодирование:  77%|███████▋  | 15478/19990 [42:18<31:57,  2.35it/s]

[15479] Геокодируем адрес: Английский пр-т 25, Санкт-Петербург

Геокодирование:  77%|███████▋  | 15481/19990 [42:19<31:10,  2.41it/s]

Автосохранение после 15480 строк...
[15486] Геокодируем адрес: Парголово Федора Абрамова ул 21к3, Санкт-Петербург

Геокодирование:  77%|███████▋  | 15487/19990 [42:20<18:23,  4.08it/s]

[15488] Геокодируем адрес: Суворовский пр-т 1/8, Санкт-Петербург

Геокодирование:  77%|███████▋  | 15489/19990 [42:21<23:35,  3.18it/s]

[15492] Геокодируем адрес: Загородный пр-т 40, Санкт-Петербург

Геокодирование:  78%|███████▊  | 15493/19990 [42:22<21:31,  3.48it/s]

[15493] Геокодируем адрес: Павловск Елизаветинская ул, Санкт-Петербург

Геокодирование:  78%|███████▊  | 15494/19990 [42:23<26:27,  2.83it/s]

[15495] Геокодируем адрес: Стачек пр-т 101к1, Санкт-Петербург

Геокодирование:  78%|███████▊  | 15496/19990 [42:24<29:19,  2.55it/s]

[15498] Геокодируем адрес: Стачек пр-т 95к1, Санкт-Петербург

Геокодирование:  78%|███████▊  | 15499/19990 [42:25<27:35,  2.71it/s]

[15503] Геокодируем адрес: Металлострой Садовая ул 8, Санкт-Петербург

Геокодирование:  78%|███████▊  | 15504/19990 [42:26<22:22,  3.34it/s]

[15508] Геокодируем адрес: Культуры пр-т, Санкт-Петербург

Геокодирование:  78%|███████▊  | 15509/19990 [42:27<19:23,  3.85it/s]

[15510] Геокодируем адрес: Энергетиков пр-т 48, Санкт-Петербург

Геокодирование:  78%|███████▊  | 15511/19990 [42:28<24:38,  3.03it/s]

Автосохранение после 15510 строк...
[15513] Геокодируем адрес: Челиева ул 18, Санкт-Петербург

Геокодирование:  78%|███████▊  | 15514/19990 [42:29<22:44,  3.28it/s]

[15514] Геокодируем адрес: Солидарности пр-т 3к3, Санкт-Петербург

Геокодирование:  78%|███████▊  | 15515/19990 [42:30<29:16,  2.55it/s]

[15515] Геокодируем адрес: Рижский пр-т 23, Санкт-Петербург

Геокодирование:  78%|███████▊  | 15516/19990 [42:31<36:06,  2.07it/s]

[15516] Геокодируем адрес: Просвещения пр-т 82к1, Санкт-Петербург

Геокодирование:  78%|███████▊  | 15517/19990 [42:32<41:22,  1.80it/s]

[15517] Геокодируем адрес: Колпино Фидерная ул, Санкт-Петербург

Геокодирование:  78%|███████▊  | 15518/19990 [42:33<47:31,  1.57it/s]

[15522] Геокодируем адрес: Петергоф Чебышёвская ул 9, Санкт-Петербург

Геокодирование:  78%|███████▊  | 15523/19990 [42:34<28:55,  2.57it/s]

[15527] Геокодируем адрес: Невский пр-т 61Б, Санкт-Петербург

Геокодирование:  78%|███████▊  | 15528/19990 [42:35<23:44,  3.13it/s]

[15528] Геокодируем адрес: Южно-Приморский сад, Санкт-Петербург

Геокодирование:  78%|███████▊  | 15541/19990 [42:36<09:57,  7.45it/s]

Автосохранение после 15540 строк...
[15544] Геокодируем адрес: Сестрорецк Инструментальщиков ул 15, Санкт-Петербург

Геокодирование:  78%|███████▊  | 15545/19990 [42:37<11:37,  6.38it/s]

[15545] Геокодируем адрес: Ленинский пр-т 118, Санкт-Петербург
[15546] Геокодируем адрес: Маршала Жукова пр-т 18, Санкт-Петербург

Геокодирование:  78%|███████▊  | 15547/19990 [42:39<22:12,  3.34it/s]

[15548] Геокодируем адрес: Королева пр-т 19, Санкт-Петербург

Геокодирование:  78%|███████▊  | 15549/19990 [42:40<23:55,  3.09it/s]

[15549] Геокодируем адрес: Королева пр-т 19, Санкт-Петербург

Геокодирование:  78%|███████▊  | 15550/19990 [42:41<29:38,  2.50it/s]

[15550] Геокодируем адрес: Королёва пр-т 19, Санкт-Петербург

Геокодирование:  78%|███████▊  | 15551/19990 [42:42<34:51,  2.12it/s]

[15551] Геокодируем адрес: Пушкин Пушкинская ул 8, Санкт-Петербург

Геокодирование:  78%|███████▊  | 15552/19990 [42:43<40:22,  1.83it/s]

[15552] Геокодируем адрес: Кронштадт Флотская ул, Санкт-Петербург

Геокодирование:  78%|███████▊  | 15553/19990 [42:44<45:04,  1.64it/s]

[15553] Геокодируем адрес: Пушкин Ленинградская ул 47, Санкт-Петербург

Геокодирование:  78%|███████▊  | 15554/19990 [42:45<53:04,  1.39it/s]

[15554] Геокодируем адрес: Павловск Мариенталь сад, Санкт-Петербург

Геокодирование:  78%|███████▊  | 15555/19990 [42:46<56:14,  1.31it/s]

[15558] Геокодируем адрес: Пушкин Оранжерейная ул 57, Санкт-Петербург

Геокодирование:  78%|███████▊  | 15559/19990 [42:47<35:21,  2.09it/s]

[15559] Геокодируем адрес: Ветеранов пр-т 122, Санкт-Петербург

Геокодирование:  78%|███████▊  | 15560/19990 [42:48<46:01,  1.60it/s]

[15566] Геокодируем адрес: Петергоф Новые Заводы ул, Санкт-Петербург

Геокодирование:  78%|███████▊  | 15567/19990 [42:49<21:10,  3.48it/s]

[15568] Геокодируем адрес: Петергоф Новые Заводы ул, Санкт-Петербург

Геокодирование:  78%|███████▊  | 15571/19990 [42:50<20:24,  3.61it/s]

Автосохранение после 15570 строк...
[15577] Геокодируем адрес: Большеохтинский пр-т 15к2, Санкт-Петербург

Геокодирование:  78%|███████▊  | 15578/19990 [42:51<14:02,  5.23it/s]

[15588] Геокодируем адрес: Ленинский пр-т 55, Санкт-Петербург

Геокодирование:  78%|███████▊  | 15589/19990 [42:52<11:04,  6.62it/s]

[15589] Геокодируем адрес: Ленинский пр-т 55, Санкт-Петербург

Геокодирование:  78%|███████▊  | 15590/19990 [42:54<20:04,  3.65it/s]

[15590] Геокодируем адрес: 1-й Муринский пр-т, Санкт-Петербург

Геокодирование:  78%|███████▊  | 15591/19990 [42:56<26:25,  2.77it/s]

[15599] Геокодируем адрес: Шушары новгородский пр-т, Санкт-Петербург

Геокодирование:  78%|███████▊  | 15601/19990 [42:56<15:18,  4.78it/s]

Автосохранение после 15600 строк...
[15615] Геокодируем адрес: Лиговский пр-т 117, Санкт-Петербург

Геокодирование:  78%|███████▊  | 15616/19990 [42:57<08:32,  8.54it/s]

[15616] Геокодируем адрес: Шушары Московское ш 258к2, Санкт-Петербург

Геокодирование:  78%|███████▊  | 15617/19990 [42:58<11:18,  6.45it/s]

[15622] Геокодируем адрес: Советский пр-т 12, Санкт-Петербург

Геокодирование:  78%|███████▊  | 15623/19990 [43:00<12:57,  5.62it/s]

[15623] Геокодируем адрес: Советский пр-т 12, Санкт-Петербург

Геокодирование:  78%|███████▊  | 15624/19990 [43:00<16:34,  4.39it/s]

[15624] Геокодируем адрес: Комендантский пр-т 50к1, Санкт-Петербург

Геокодирование:  78%|███████▊  | 15625/19990 [43:01<20:20,  3.58it/s]

[15626] Геокодируем адрес: Советский пр-т 39к1, Санкт-Петербург

Геокодирование:  78%|███████▊  | 15631/19990 [43:02<16:22,  4.44it/s]

Автосохранение после 15630 строк...
[15631] Геокодируем адрес: Троицкий пр-т 16, Санкт-Петербург

Геокодирование:  78%|███████▊  | 15632/19990 [43:03<22:04,  3.29it/s]

[15633] Геокодируем адрес: Московский пр-т 7, Санкт-Петербург

Геокодирование:  78%|███████▊  | 15634/19990 [43:04<26:47,  2.71it/s]

[15639] Геокодируем адрес: Металлистов пр-т 23, Санкт-Петербург

Геокодирование:  78%|███████▊  | 15640/19990 [43:05<18:25,  3.93it/s]

[15640] Геокодируем адрес: Малый пр-т 58, Санкт-Петербург

Геокодирование:  78%|███████▊  | 15641/19990 [43:07<26:16,  2.76it/s]

[15641] Геокодируем адрес: Торфяная дор 17к2, Санкт-Петербург

Геокодирование:  78%|███████▊  | 15642/19990 [43:07<28:40,  2.53it/s]

[15643] Геокодируем адрес: Лиговский пр-т 82а, Санкт-Петербург

Геокодирование:  78%|███████▊  | 15644/19990 [43:08<32:01,  2.26it/s]

[15649] Геокодируем адрес: Сизова пр-т 20к1, Санкт-Петербург

Геокодирование:  78%|███████▊  | 15650/19990 [43:09<20:33,  3.52it/s]

[15657] Геокодируем адрес: Нефтяная дор, Санкт-Петербург

Геокодирование:  78%|███████▊  | 15661/19990 [43:10<12:17,  5.87it/s]

Автосохранение после 15660 строк...
[15670] Геокодируем адрес: Лиговский пр-т 89/20, Санкт-Петербург

Геокодирование:  78%|███████▊  | 15671/19990 [43:11<09:55,  7.25it/s]

[15672] Геокодируем адрес: Пискаревский пр-т 145к4, Санкт-Петербург

Геокодирование:  78%|███████▊  | 15673/19990 [43:12<12:03,  5.96it/s]

[15679] Геокодируем адрес: Королева ул 44к1, Санкт-Петербург

Геокодирование:  78%|███████▊  | 15680/19990 [43:13<11:35,  6.19it/s]

[15686] Геокодируем адрес: Маршала Жукова пр-т 26/16Д, Санкт-Петербург

Геокодирование:  78%|███████▊  | 15687/19990 [43:15<12:18,  5.83it/s]

[15689] Геокодируем адрес: Ленинский пр-т 53к1, Санкт-Петербург

Геокодирование:  78%|███████▊  | 15690/19990 [43:15<13:05,  5.47it/s]

[15690] Геокодируем адрес: Загородный пр-т 26, Санкт-Петербург

Геокодирование:  78%|███████▊  | 15691/19990 [43:17<19:15,  3.72it/s]

Автосохранение после 15690 строк...
[15691] Геокодируем адрес: Авиаконструкторов пр-т 2, Санкт-Петербург

Геокодирование:  78%|███████▊  | 15692/19990 [43:17<22:38,  3.16it/s]

[15693] Геокодируем адрес: Ленская ул 10к1Б, Санкт-Петербург

Геокодирование:  79%|███████▊  | 15694/19990 [43:18<24:18,  2.95it/s]

[15699] Геокодируем адрес: Советский пр-т 39к1, Санкт-Петербург

Геокодирование:  79%|███████▊  | 15700/19990 [43:19<19:06,  3.74it/s]

[15702] Геокодируем адрес: Космонавтов пр-т 30к1, Санкт-Петербург

Геокодирование:  79%|███████▊  | 15703/19990 [43:20<20:41,  3.45it/s]

[15705] Геокодируем адрес: медиков пр-т 10к1, Санкт-Петербург

Геокодирование:  79%|███████▊  | 15706/19990 [43:21<21:46,  3.28it/s]

[15706] Геокодируем адрес: ленинский пр-т 147к3, Санкт-Петербург

Геокодирование:  79%|███████▊  | 15707/19990 [43:22<26:04,  2.74it/s]

[15709] Геокодируем адрес: Советский пр-т 14стр1, Санкт-Петербург

Геокодирование:  79%|███████▊  | 15710/19990 [43:23<24:47,  2.88it/s]

[15710] Геокодируем адрес: маршала жукова пр-т 18, Санкт-Петербург

Геокодирование:  79%|███████▊  | 15711/19990 [43:25<35:23,  2.01it/s]

[15715] Геокодируем адрес: Сизова пр-т 14, Санкт-Петербург

Геокодирование:  79%|███████▊  | 15721/19990 [43:26<14:32,  4.89it/s]

Автосохранение после 15720 строк...
[15725] Геокодируем адрес: Обуховской Обороны пр-т 145, Санкт-Петербург

Геокодирование:  79%|███████▊  | 15726/19990 [43:26<14:09,  5.02it/s]

[15727] Геокодируем адрес: Колпино Тверская ул 38, Санкт-Петербург

Геокодирование:  79%|███████▊  | 15728/19990 [43:27<17:02,  4.17it/s]

[15733] Геокодируем адрес: Товарищеский пр-т 9, Санкт-Петербург

Геокодирование:  79%|███████▊  | 15734/19990 [43:28<15:18,  4.63it/s]

[15736] Геокодируем адрес: Культуры пр-т 19, Санкт-Петербург

Геокодирование:  79%|███████▊  | 15737/19990 [43:29<17:18,  4.09it/s]

[15746] Геокодируем адрес: Шушары Школьная ул 15стр1, Санкт-Петербург

Геокодирование:  79%|███████▉  | 15751/19990 [43:30<09:12,  7.67it/s]

Автосохранение после 15750 строк...
[15770] Геокодируем адрес: Комендантский пр-т 53к4, Санкт-Петербург

Геокодирование:  79%|███████▉  | 15771/19990 [43:31<05:17, 13.29it/s]

[15774] Геокодируем адрес: Красное Село Двадцать Пятого Октября пр-т, Санкт-Петербург

Геокодирование:  79%|███████▉  | 15775/19990 [43:33<07:47,  9.03it/s]

[15777] Геокодируем адрес: Пушкин Пушкинская ул, Санкт-Петербург

Геокодирование:  79%|███████▉  | 15781/19990 [43:33<08:14,  8.51it/s]

Автосохранение после 15780 строк...
[15790] Геокодируем адрес: Ленинский пр-т 111к2, Санкт-Петербург

Геокодирование:  79%|███████▉  | 15791/19990 [43:34<07:16,  9.61it/s]

[15799] Геокодируем адрес: Зеленогорск Ленина пр-т, Санкт-Петербург

Геокодирование:  79%|███████▉  | 15800/19990 [43:35<07:27,  9.36it/s]

[15800] Геокодируем адрес: Шушары Школьная ул 15, Санкт-Петербург

Геокодирование:  79%|███████▉  | 15802/19990 [43:36<10:27,  6.67it/s]

[15803] Геокодируем адрес: Шушары Школьная ул 15, Санкт-Петербург

Геокодирование:  79%|███████▉  | 15804/19990 [43:37<13:39,  5.11it/s]

[15804] Геокодируем адрес: Авиаконструкторов пр-т 38к1, Санкт-Петербург

Геокодирование:  79%|███████▉  | 15811/19990 [43:38<11:04,  6.29it/s]

Автосохранение после 15810 строк...
[15811] Геокодируем адрес: Ветеранов пр-т 122, Санкт-Петербург

Геокодирование:  79%|███████▉  | 15813/19990 [43:40<15:34,  4.47it/s]

[15817] Геокодируем адрес: Муринская дор, Санкт-Петербург

Геокодирование:  79%|███████▉  | 15818/19990 [43:40<13:31,  5.14it/s]

[15818] Геокодируем адрес: Шушары Чудовская ул, Санкт-Петербург

Геокодирование:  79%|███████▉  | 15819/19990 [43:41<18:58,  3.66it/s]

[15821] Геокодируем адрес: Шушары Леонтьевская ул, Санкт-Петербург

Геокодирование:  79%|███████▉  | 15822/19990 [43:42<20:14,  3.43it/s]

[15824] Геокодируем адрес: Шушары Софийская ул, Санкт-Петербург

Геокодирование:  79%|███████▉  | 15825/19990 [43:43<21:11,  3.27it/s]

[15830] Геокодируем адрес: Юрия Гагарина пр-т 16, Санкт-Петербург

Геокодирование:  79%|███████▉  | 15831/19990 [43:45<18:04,  3.84it/s]

[15834] Геокодируем адрес: Науки пр-т 24к1, Санкт-Петербург

Геокодирование:  79%|███████▉  | 15835/19990 [43:45<17:01,  4.07it/s]

[15835] Геокодируем адрес: Новочеркасский пр-т 49/20, Санкт-Петербург

Геокодирование:  79%|███████▉  | 15836/19990 [43:47<23:01,  3.01it/s]

[15836] Геокодируем адрес: Петергоф Новые Заводы ул, Санкт-Петербург

Геокодирование:  79%|███████▉  | 15837/19990 [43:47<27:06,  2.55it/s]

[15840] Геокодируем адрес: Сиреневый б-р 4к2, Санкт-Петербург

Геокодирование:  79%|███████▉  | 15841/19990 [43:48<24:10,  2.86it/s]

Автосохранение после 15840 строк...
[15842] Геокодируем адрес: Сиреневый б-р 4к2, Санкт-Петербург

Геокодирование:  79%|███████▉  | 15843/19990 [43:49<25:37,  2.70it/s]

[15849] Геокодируем адрес: Ленина ул 5, Санкт-Петербург

Геокодирование:  79%|███████▉  | 15850/19990 [43:50<17:14,  4.00it/s]

[15852] Геокодируем адрес: Серебристый б-р 24к2, Санкт-Петербург

Геокодирование:  79%|███████▉  | 15853/19990 [43:51<18:04,  3.82it/s]

[15854] Геокодируем адрес: Пушкин Фермский сад, Санкт-Петербург

Геокодирование:  79%|███████▉  | 15855/19990 [43:52<21:41,  3.18it/s]

[15865] Геокодируем адрес: Луначарского пр-т 76, Санкт-Петербург

Геокодирование:  79%|███████▉  | 15866/19990 [43:54<13:22,  5.14it/s]

[15867] Геокодируем адрес: Горелово Максима Горького ул 20, Санкт-Петербург

Геокодирование:  79%|███████▉  | 15871/19990 [43:54<12:20,  5.56it/s]

Автосохранение после 15870 строк...
[15884] Геокодируем адрес: 5-й Предпортовый пр-д 4к1, Санкт-Петербург

Геокодирование:  79%|███████▉  | 15885/19990 [43:55<07:49,  8.74it/s]

[15895] Геокодируем адрес: Горелово Максима Горького ул 20, Санкт-Петербург

Геокодирование:  80%|███████▉  | 15896/19990 [43:56<06:49, 10.00it/s]

[15900] Геокодируем адрес: Ветеранов пр-т 13, Санкт-Петербург

Геокодирование:  80%|███████▉  | 15901/19990 [43:59<11:58,  5.69it/s]

Автосохранение после 15900 строк...
[15903] Геокодируем адрес: Шлиссербургский пр-т 34, Санкт-Петербург

Геокодирование:  80%|███████▉  | 15904/19990 [43:59<12:05,  5.63it/s]

[15905] Геокодируем адрес: 6-я линия линия ВО, Санкт-Петербург

RateLimiter caught an error, retrying (0/2 tries). Called with (*('6-я линия линия ВО, Санкт-Петербург',), **{}).
Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connection.py", line 516, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1374, in getresponse
    response.begin()
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1278, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1134, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 367, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=6-%D1%8F+%D0%BB%D0%B8%D0%BD%D0%B8%D1%8F+%D0%BB%D0%B8%D0%BD%D0%B8%D1%8F+%D0%92%D0%9E%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 482, in _request
    resp = self.session.get(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=6-%D1%8F+%D0%BB%D0%B8%D0%BD%D0%B8%D1%8F+%D0%BB%D0%B8%D0%BD%D0%B8%D1%8F+%D0%92%D0%9E%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\extra\rate_limiter.py", line 136, in _retries_gen
    yield i  # Run the function.
    ^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\extra\rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\geocoders\nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\geocoders\base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 472, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 494, in _request
    raise GeocoderUnavailable(message)
geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=6-%D1%8F+%D0%BB%D0%B8%D0%BD%D0%B8%D1%8F+%D0%BB%D0%B8%D0%BD%D0%B8%D1%8F+%D0%92%D0%9E%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))
Геокодирование:  80%|███████▉  | 15906/19990 [44:10<56:40,  1.20it/s]

[15907] Геокодируем адрес: Королева ул 63, Санкт-Петербург

Геокодирование:  80%|███████▉  | 15908/19990 [44:11<51:56,  1.31it/s]

[15911] Геокодируем адрес: Авиаконструкторов пр-т 4к1, Санкт-Петербург

Геокодирование:  80%|███████▉  | 15912/19990 [44:12<41:06,  1.65it/s]

[15912] Геокодируем адрес: Дачный пр-т 5/7, Санкт-Петербург

Геокодирование:  80%|███████▉  | 15913/19990 [44:13<44:53,  1.51it/s]

[15913] Геокодируем адрес: Авиаконструкторов пр-т 4к1, Санкт-Петербург

Геокодирование:  80%|███████▉  | 15914/19990 [44:14<46:24,  1.46it/s]

[15914] Геокодируем адрес: Шушары Старорусский пр-т 13к1, Санкт-Петербург

Геокодирование:  80%|███████▉  | 15915/19990 [44:15<49:27,  1.37it/s]

[15916] Геокодируем адрес: Шушары Старорусский пр-т 13к1, Санкт-Петербург

Геокодирование:  80%|███████▉  | 15917/19990 [44:16<44:34,  1.52it/s]

[15918] Геокодируем адрес: Кронштадт Лебедева ул 5, Санкт-Петербург

Геокодирование:  80%|███████▉  | 15919/19990 [44:17<41:14,  1.65it/s]

[15919] Геокодируем адрес: Авиаконструкторов пр-т 4к1, Санкт-Петербург

Геокодирование:  80%|███████▉  | 15920/19990 [44:18<45:58,  1.48it/s]

[15921] Геокодируем адрес: Большевиков пр-т 6-4, Санкт-Петербург

Геокодирование:  80%|███████▉  | 15922/19990 [44:19<43:42,  1.55it/s]

[15926] Геокодируем адрес: Шушары Старорусский пр-т 13к1, Санкт-Петербург

Геокодирование:  80%|███████▉  | 15927/19990 [44:20<26:06,  2.59it/s]

[15928] Геокодируем адрес: Авиаконструкторов пр-т 4к1, Санкт-Петербург

Геокодирование:  80%|███████▉  | 15931/19990 [44:21<22:24,  3.02it/s]

Автосохранение после 15930 строк...
[15931] Геокодируем адрес: Шушары Старорусский пр-т 13к1, Санкт-Петербург

Геокодирование:  80%|███████▉  | 15932/19990 [44:22<27:31,  2.46it/s]

[15933] Геокодируем адрес: Красное Село Лермонтова ул 7, Санкт-Петербург

Геокодирование:  80%|███████▉  | 15934/19990 [44:23<31:50,  2.12it/s]

[15934] Геокодируем адрес: Шушары Школьная ул 15, Санкт-Петербург

Геокодирование:  80%|███████▉  | 15935/19990 [44:24<35:44,  1.89it/s]

[15938] Геокодируем адрес: Авиаконструкторов пр-т 4к1, Санкт-Петербург

Геокодирование:  80%|███████▉  | 15939/19990 [44:25<25:51,  2.61it/s]

[15940] Геокодируем адрес: Авиаконструкторов пр-т 4к1, Санкт-Петербург

Геокодирование:  80%|███████▉  | 15941/19990 [44:26<28:41,  2.35it/s]

[15942] Геокодируем адрес: Шушары Школьная ул 15, Санкт-Петербург

Геокодирование:  80%|███████▉  | 15943/19990 [44:27<29:21,  2.30it/s]

[15943] Геокодируем адрес: Шушары Школьная ул 15, Санкт-Петербург

Геокодирование:  80%|███████▉  | 15944/19990 [44:28<35:29,  1.90it/s]

[15948] Геокодируем адрес: Шушары Школьная ул 15, Санкт-Петербург

Геокодирование:  80%|███████▉  | 15949/19990 [44:29<24:10,  2.79it/s]

[15957] Геокодируем адрес: Серебристый б-р 12к1, Санкт-Петербург

Геокодирование:  80%|███████▉  | 15958/19990 [44:30<14:22,  4.68it/s]

[15960] Геокодируем адрес: Суворовский пр-т 62, Санкт-Петербург

Геокодирование:  80%|███████▉  | 15961/19990 [44:31<17:00,  3.95it/s]

Автосохранение после 15960 строк...
[15963] Геокодируем адрес: Энгельса пр-т 33, Санкт-Петербург

Геокодирование:  80%|███████▉  | 15964/19990 [44:33<23:42,  2.83it/s]

[15964] Геокодируем адрес: Ветеранов пр-т 122, Санкт-Петербург

Геокодирование:  80%|███████▉  | 15965/19990 [44:34<27:35,  2.43it/s]

[15965] Геокодируем адрес: Московский пр-т, Санкт-Петербург

Геокодирование:  80%|███████▉  | 15966/19990 [44:35<31:10,  2.15it/s]

[15973] Геокодируем адрес: Королева пр-т 73, Санкт-Петербург

Геокодирование:  80%|███████▉  | 15974/19990 [44:36<18:31,  3.61it/s]

[15982] Геокодируем адрес: Петергоф Новые Заводы ул, Санкт-Петербург

Геокодирование:  80%|███████▉  | 15983/19990 [44:37<12:10,  5.48it/s]

[15983] Геокодируем адрес: Петергоф Новые Заводы ул, Санкт-Петербург

Геокодирование:  80%|███████▉  | 15984/19990 [44:38<16:08,  4.14it/s]

[15984] Геокодируем адрес: Павловск Горная ул 4, Санкт-Петербург

Геокодирование:  80%|███████▉  | 15985/19990 [44:39<21:18,  3.13it/s]

[15985] Геокодируем адрес: Шушары Московское ш 258к2, Санкт-Петербург

Геокодирование:  80%|███████▉  | 15986/19990 [44:40<25:49,  2.58it/s]

[15988] Геокодируем адрес: Советский пр-т 12, Санкт-Петербург

Геокодирование:  80%|███████▉  | 15991/19990 [44:42<27:34,  2.42it/s]

Автосохранение после 15990 строк...
[15993] Геокодируем адрес: павловская пр-т 76, Санкт-Петербург

Геокодирование:  80%|████████  | 15994/19990 [44:43<24:05,  2.76it/s]

[16004] Геокодируем адрес: Обуховской Обороны пр-т 89Б, Санкт-Петербург

Геокодирование:  80%|████████  | 16005/19990 [44:44<12:25,  5.34it/s]

[16007] Геокодируем адрес: Обуховской Обороны пр-т 89Б, Санкт-Петербург

Геокодирование:  80%|████████  | 16008/19990 [44:45<14:16,  4.65it/s]

[16009] Геокодируем адрес: новоколомяжский пр-т 11, Санкт-Петербург

Геокодирование:  80%|████████  | 16010/19990 [44:46<17:21,  3.82it/s]

[16010] Геокодируем адрес: Авиаконструкторов пр-т 4к1, Санкт-Петербург

Геокодирование:  80%|████████  | 16011/19990 [44:47<21:40,  3.06it/s]

[16011] Геокодируем адрес: Авиаконструкторов пр-т 4к1, Санкт-Петербург

Геокодирование:  80%|████████  | 16012/19990 [44:48<27:40,  2.40it/s]

[16012] Геокодируем адрес: Приморский пр-т 58к2, Санкт-Петербург

Геокодирование:  80%|████████  | 16013/19990 [44:49<33:24,  1.98it/s]

[16015] Геокодируем адрес: Серебристый б-р 22к3, Санкт-Петербург

Геокодирование:  80%|████████  | 16021/19990 [44:50<15:46,  4.19it/s]

Автосохранение после 16020 строк...
[16037] Геокодируем адрес: Обуховской Обороны пр-т 245к2, Санкт-Петербург

Геокодирование:  80%|████████  | 16038/19990 [44:51<06:54,  9.53it/s]

[16039] Геокодируем адрес: Парголово Валерия Гаврилина ул 3к1, Санкт-Петербург

Геокодирование:  80%|████████  | 16040/19990 [44:52<09:41,  6.79it/s]

[16040] Геокодируем адрес: Петергоф Новые Заводы ул, Санкт-Петербург
[16041] Геокодируем адрес: Петергоф Новые Заводы ул, Санкт-Петербург

Геокодирование:  80%|████████  | 16042/19990 [44:54<16:54,  3.89it/s]

[16044] Геокодируем адрес: Петергоф Новые Заводы ул, Санкт-Петербург

Геокодирование:  80%|████████  | 16045/19990 [44:55<18:01,  3.65it/s]

[16045] Геокодируем адрес: Петергоф Новые Заводы ул, Санкт-Петербург

Геокодирование:  80%|████████  | 16046/19990 [44:56<22:32,  2.92it/s]

[16047] Геокодируем адрес: Парголово Толубеевский пр-д, Санкт-Петербург

Геокодирование:  80%|████████  | 16048/19990 [44:57<25:06,  2.62it/s]

[16048] Геокодируем адрес: Шушары Старорусский пр-т 13, Санкт-Петербург

Геокодирование:  80%|████████  | 16049/19990 [44:58<31:21,  2.09it/s]

[16050] Геокодируем адрес: Петергоф Новые Заводы ул, Санкт-Петербург

Геокодирование:  80%|████████  | 16051/19990 [44:59<31:39,  2.07it/s]

Автосохранение после 16050 строк...
[16052] Геокодируем адрес: Шушары Старорусский пр-т, Санкт-Петербург

Геокодирование:  80%|████████  | 16053/19990 [45:00<30:58,  2.12it/s]

[16053] Геокодируем адрес: Шушары Старорусский пр-т, Санкт-Петербург

Геокодирование:  80%|████████  | 16054/19990 [45:01<36:43,  1.79it/s]

[16054] Геокодируем адрес: Шушары Старорусский пр-т, Санкт-Петербург

Геокодирование:  80%|████████  | 16055/19990 [45:02<42:14,  1.55it/s]

[16055] Геокодируем адрес: Александровской Фермы пр-т, Санкт-Петербург

Геокодирование:  80%|████████  | 16056/19990 [45:03<48:14,  1.36it/s]

[16056] Геокодируем адрес: Маршала Казакова пр-т, Санкт-Петербург

Геокодирование:  80%|████████  | 16057/19990 [45:04<52:18,  1.25it/s]

[16057] Геокодируем адрес: Шушары Старорусский пр-т, Санкт-Петербург

Геокодирование:  80%|████████  | 16058/19990 [45:05<54:26,  1.20it/s]

[16059] Геокодируем адрес: Петергоф Ропшинское ш, Санкт-Петербург

Геокодирование:  80%|████████  | 16060/19990 [45:06<45:08,  1.45it/s]

[16060] Геокодируем адрес: Петергоф Ропшинское ш, Санкт-Петербург

Геокодирование:  80%|████████  | 16061/19990 [45:07<49:59,  1.31it/s]

[16064] Геокодируем адрес: Муринская дор, Санкт-Петербург

Геокодирование:  80%|████████  | 16065/19990 [45:08<30:28,  2.15it/s]

[16066] Геокодируем адрес: Муринская дор, Санкт-Петербург

Геокодирование:  80%|████████  | 16067/19990 [45:09<30:58,  2.11it/s]

[16071] Геокодируем адрес: Петергоф Ропшинское ш, Санкт-Петербург

Геокодирование:  80%|████████  | 16072/19990 [45:10<22:18,  2.93it/s]

[16077] Геокодируем адрес: Шушары Старорусский пр-т, Санкт-Петербург

Геокодирование:  80%|████████  | 16081/19990 [45:12<17:30,  3.72it/s]

Автосохранение после 16080 строк...
[16082] Геокодируем адрес: Греческий пр-т 21, Санкт-Петербург

Геокодирование:  80%|████████  | 16083/19990 [45:13<19:52,  3.28it/s]

[16083] Геокодируем адрес: Греческий пр-т 23, Санкт-Петербург

Геокодирование:  80%|████████  | 16084/19990 [45:14<25:18,  2.57it/s]

[16086] Геокодируем адрес: Петергоф Ропшинское ш 3к7, Санкт-Петербург

Геокодирование:  80%|████████  | 16087/19990 [45:15<23:33,  2.76it/s]

[16087] Геокодируем адрес: Народного Ополчения пр-т 83, Санкт-Петербург

Геокодирование:  80%|████████  | 16088/19990 [45:16<30:44,  2.12it/s]

[16088] Геокодируем адрес: Ленинский пр-т 78/1, Санкт-Петербург

Геокодирование:  80%|████████  | 16089/19990 [45:17<37:47,  1.72it/s]

[16091] Геокодируем адрес: Шушары Переведенская ул 4к1, Санкт-Петербург

Геокодирование:  81%|████████  | 16092/19990 [45:18<28:14,  2.30it/s]

[16092] Геокодируем адрес: Шушары Школьная ул 15стр1, Санкт-Петербург

Геокодирование:  81%|████████  | 16093/19990 [45:19<33:40,  1.93it/s]

[16093] Геокодируем адрес: Петергоф Ропшинское ш 2, Санкт-Петербург

Геокодирование:  81%|████████  | 16094/19990 [45:20<42:08,  1.54it/s]

[16094] Геокодируем адрес: Петергоф Новые Заводы ул, Санкт-Петербург

Геокодирование:  81%|████████  | 16095/19990 [45:21<44:07,  1.47it/s]

[16096] Геокодируем адрес: кузнецова ул 29/3, Санкт-Петербург

Геокодирование:  81%|████████  | 16097/19990 [45:22<42:33,  1.52it/s]

[16101] Геокодируем адрес: ленина пл 3, Санкт-Петербург

Геокодирование:  81%|████████  | 16102/19990 [45:23<25:04,  2.58it/s]

[16104] Геокодируем адрес: Народного Ополчения пр-т 141, Санкт-Петербург

Геокодирование:  81%|████████  | 16105/19990 [45:24<24:26,  2.65it/s]

[16110] Геокодируем адрес: Комендантский пр-т 51к1, Санкт-Петербург

Геокодирование:  81%|████████  | 16111/19990 [45:25<17:40,  3.66it/s]

Автосохранение после 16110 строк...
[16117] Геокодируем адрес: Фарфоровский пост ул, Санкт-Петербург

Геокодирование:  81%|████████  | 16118/19990 [45:26<13:07,  4.92it/s]

[16118] Геокодируем адрес: Комендантский пр-т 3к1, Санкт-Петербург

Геокодирование:  81%|████████  | 16119/19990 [45:27<17:35,  3.67it/s]

[16120] Геокодируем адрес: Шушары Валдайская ул 6к2, Санкт-Петербург

Геокодирование:  81%|████████  | 16121/19990 [45:28<20:27,  3.15it/s]

[16126] Геокодируем адрес: Советский пр-т 14, Санкт-Петербург

Геокодирование:  81%|████████  | 16127/19990 [45:29<17:07,  3.76it/s]

[16128] Геокодируем адрес: Лесной пр-т 37к5, Санкт-Петербург

Геокодирование:  81%|████████  | 16129/19990 [45:30<18:27,  3.49it/s]

[16140] Геокодируем адрес: Авиаконструкторов пр-т 4к1, Санкт-Петербург

Геокодирование:  81%|████████  | 16141/19990 [45:31<11:11,  5.73it/s]

Автосохранение после 16140 строк...
[16141] Геокодируем адрес: Красное Село Гатчинское ш 5к2, Санкт-Петербург

Геокодирование:  81%|████████  | 16142/19990 [45:32<15:08,  4.24it/s]

[16152] Геокодируем адрес: Комендантский пр-т 53к1, Санкт-Петербург

Геокодирование:  81%|████████  | 16153/19990 [45:33<09:18,  6.87it/s]

[16160] Геокодируем адрес: Институтский пр-т 4к1, Санкт-Петербург

Геокодирование:  81%|████████  | 16171/19990 [45:34<05:55, 10.75it/s]

Автосохранение после 16170 строк...
[16174] Геокодируем адрес: Московский пр-т 48, Санкт-Петербург

Геокодирование:  81%|████████  | 16175/19990 [45:35<07:35,  8.37it/s]

[16176] Геокодируем адрес: Малый пр-т 74, Санкт-Петербург

Геокодирование:  81%|████████  | 16177/19990 [45:36<10:45,  5.91it/s]

[16179] Геокодируем адрес: Усть-Славянка Советский пр-т 16, Санкт-Петербург

Геокодирование:  81%|████████  | 16180/19990 [45:37<12:35,  5.04it/s]

[16187] Геокодируем адрес: Пушкин Октябрьский б-р 24, Санкт-Петербург

Геокодирование:  81%|████████  | 16188/19990 [45:38<10:52,  5.83it/s]

[16188] Геокодируем адрес: Пушкин Оранжерейная ул 60, Санкт-Петербург

Геокодирование:  81%|████████  | 16189/19990 [45:39<13:23,  4.73it/s]

[16190] Геокодируем адрес: Шушары Переведенская ул 4к1, Санкт-Петербург

Геокодирование:  81%|████████  | 16191/19990 [45:40<16:19,  3.88it/s]

[16191] Геокодируем адрес: Кадетский б-р 23, Санкт-Петербург

Геокодирование:  81%|████████  | 16192/19990 [45:41<21:52,  2.89it/s]

[16197] Геокодируем адрес: Тореза пр-т 26, Санкт-Петербург

Геокодирование:  81%|████████  | 16198/19990 [45:42<16:25,  3.85it/s]

[16200] Геокодируем адрес: Народного Ополчения пр-т 141, Санкт-Петербург

Геокодирование:  81%|████████  | 16201/19990 [45:43<19:11,  3.29it/s]

Автосохранение после 16200 строк...
[16201] Геокодируем адрес: Колпино Братьев Радченко ул 19, Санкт-Петербург

Геокодирование:  81%|████████  | 16202/19990 [45:44<21:59,  2.87it/s]

[16207] Геокодируем адрес: 26-я линия ВО, Санкт-Петербург

Геокодирование:  81%|████████  | 16208/19990 [45:47<28:47,  2.19it/s]

[16210] Геокодируем адрес: Лиговский пр-т 154, Санкт-Петербург

Геокодирование:  81%|████████  | 16211/19990 [45:48<25:29,  2.47it/s]

[16212] Геокодируем адрес: Пушкин Генерала Хазова ул 20, Санкт-Петербург

Геокодирование:  81%|████████  | 16213/19990 [45:49<26:19,  2.39it/s]

[16222] Геокодируем адрес: Косая линия ВО, Санкт-Петербург

Геокодирование:  81%|████████  | 16223/19990 [45:50<14:14,  4.41it/s]

[16223] Геокодируем адрес: Сестрорецк Володарского ул 36, Санкт-Петербург

Геокодирование:  81%|████████  | 16231/19990 [45:51<10:52,  5.76it/s]

Автосохранение после 16230 строк...
[16232] Геокодируем адрес: Ветеранов пр-т 13, Санкт-Петербург

Геокодирование:  81%|████████  | 16233/19990 [45:52<13:43,  4.56it/s]

[16243] Геокодируем адрес: Суворовский пр-т 39, Санкт-Петербург

Геокодирование:  81%|████████▏ | 16244/19990 [45:53<09:24,  6.63it/s]

[16244] Геокодируем адрес: Суворовский пр-т 39, Санкт-Петербург
[16245] Геокодируем адрес: Суворовский пр-т 39, Санкт-Петербург

Геокодирование:  81%|████████▏ | 16246/19990 [45:55<15:52,  3.93it/s]

[16250] Геокодируем адрес: Авиаконструкторов пр-т 4к1, Санкт-Петербург

Геокодирование:  81%|████████▏ | 16251/19990 [45:56<14:26,  4.31it/s]

[16251] Геокодируем адрес: Бобыльская дор, Санкт-Петербург

Геокодирование:  81%|████████▏ | 16261/19990 [45:57<09:21,  6.64it/s]

Автосохранение после 16260 строк...
[16261] Геокодируем адрес: Горелово Красносельское ш 13, Санкт-Петербург

Геокодирование:  81%|████████▏ | 16264/19990 [45:58<11:21,  5.47it/s]

[16266] Геокодируем адрес: Шушары Старорусский пр-т 13к1, Санкт-Петербург

Геокодирование:  81%|████████▏ | 16267/19990 [45:59<13:19,  4.66it/s]

[16270] Геокодируем адрес: Колпино Красных Партизан ул, Санкт-Петербург

Геокодирование:  81%|████████▏ | 16271/19990 [46:00<13:48,  4.49it/s]

[16271] Геокодируем адрес: Колпино Павловская ул 92, Санкт-Петербург

Геокодирование:  81%|████████▏ | 16272/19990 [46:01<18:29,  3.35it/s]

[16276] Геокодируем адрес: Новочеркасский пр-т 39к2, Санкт-Петербург

Геокодирование:  81%|████████▏ | 16277/19990 [46:02<15:47,  3.92it/s]

[16281] Геокодируем адрес: Бобыльская дор 61, Санкт-Петербург

Геокодирование:  81%|████████▏ | 16282/19990 [46:03<14:33,  4.25it/s]

[16282] Геокодируем адрес: Металлистов пр-т 82, Санкт-Петербург

Геокодирование:  81%|████████▏ | 16283/19990 [46:04<19:27,  3.18it/s]

[16284] Геокодируем адрес: Шушары Старорусский пр-т 13к1, Санкт-Петербург

Геокодирование:  81%|████████▏ | 16285/19990 [46:05<21:46,  2.84it/s]

[16287] Геокодируем адрес: Каменноостровский пр-т 69, Санкт-Петербург

Геокодирование:  81%|████████▏ | 16288/19990 [46:06<21:26,  2.88it/s]

[16288] Геокодируем адрес: Шушары Школьная ул 15, Санкт-Петербург

Геокодирование:  81%|████████▏ | 16291/19990 [46:07<20:18,  3.04it/s]

Автосохранение после 16290 строк...
[16297] Геокодируем адрес: Малодетскосельский пр-т 36, Санкт-Петербург

Геокодирование:  82%|████████▏ | 16298/19990 [46:08<13:09,  4.68it/s]

[16301] Геокодируем адрес: Светлановский пр-т 109к1, Санкт-Петербург

Геокодирование:  82%|████████▏ | 16302/19990 [46:09<13:31,  4.54it/s]

[16302] Геокодируем адрес: Петергоф Ропшинское ш, Санкт-Петербург

Геокодирование:  82%|████████▏ | 16303/19990 [46:10<18:32,  3.32it/s]

[16306] Геокодируем адрес: Космонавтов пр-т 106, Санкт-Петербург

Геокодирование:  82%|████████▏ | 16307/19990 [46:11<18:48,  3.26it/s]

[16310] Геокодируем адрес: Большой Сампсониевский пр-т 80, Санкт-Петербург

Геокодирование:  82%|████████▏ | 16321/19990 [46:12<08:15,  7.41it/s]

Автосохранение после 16320 строк...
[16333] Геокодируем адрес: 26-я линия ВО, Санкт-Петербург

Геокодирование:  82%|████████▏ | 16334/19990 [46:14<06:46,  9.00it/s]

[16338] Геокодируем адрес: Медиков пр-т 10к1, Санкт-Петербург

Геокодирование:  82%|████████▏ | 16339/19990 [46:14<07:09,  8.50it/s]

[16340] Геокодируем адрес: Трудящихся б-р, Санкт-Петербург

Геокодирование:  82%|████████▏ | 16351/19990 [46:15<05:51, 10.35it/s]

Автосохранение после 16350 строк...
[16351] Геокодируем адрес: Ленинский пр-т 119к5, Санкт-Петербург
[16353] Геокодируем адрес: Заневский пр-т 59, Санкт-Петербург

Геокодирование:  82%|████████▏ | 16354/19990 [46:17<10:53,  5.57it/s]

[16361] Геокодируем адрес: Муринский пр-т 8к1, Санкт-Петербург

Геокодирование:  82%|████████▏ | 16362/19990 [46:18<09:28,  6.38it/s]

[16373] Геокодируем адрес: Шушары Староорловская ул, Санкт-Петербург

Геокодирование:  82%|████████▏ | 16374/19990 [46:19<07:21,  8.20it/s]

[16375] Геокодируем адрес: ленина пр-т 32, Санкт-Петербург

Геокодирование:  82%|████████▏ | 16381/19990 [46:21<08:08,  7.39it/s]

Автосохранение после 16380 строк...
[16381] Геокодируем адрес: Павловск Елизаветинская ул, Санкт-Петербург
[16382] Геокодируем адрес: Пушкин Парковая ул, Санкт-Петербург

Геокодирование:  82%|████████▏ | 16383/19990 [46:22<13:24,  4.48it/s]

[16384] Геокодируем адрес: Колпино Красных Партизан ул 16, Санкт-Петербург

Геокодирование:  82%|████████▏ | 16385/19990 [46:23<15:58,  3.76it/s]

[16388] Геокодируем адрес: Пушкин Гусарская ул, Санкт-Петербург

Геокодирование:  82%|████████▏ | 16389/19990 [46:24<15:37,  3.84it/s]

[16389] Геокодируем адрес: Пушкин Гусарская ул, Санкт-Петербург

Геокодирование:  82%|████████▏ | 16390/19990 [46:25<19:51,  3.02it/s]

[16391] Геокодируем адрес: просвещения пр-т 82, Санкт-Петербург

Геокодирование:  82%|████████▏ | 16392/19990 [46:26<23:03,  2.60it/s]

[16393] Геокодируем адрес: Шушары Витебский пр-т, Санкт-Петербург

Геокодирование:  82%|████████▏ | 16394/19990 [46:27<23:49,  2.51it/s]

[16396] Геокодируем адрес: Пушкин Гвардейский б-р, Санкт-Петербург

Геокодирование:  82%|████████▏ | 16397/19990 [46:28<22:47,  2.63it/s]

[16399] Геокодируем адрес: Пушкин Подбельского ш, Санкт-Петербург

Геокодирование:  82%|████████▏ | 16400/19990 [46:29<21:41,  2.76it/s]

[16403] Геокодируем адрес: Красное Село Двадцать Пятого Октября ул, Санкт-Петербург

Геокодирование:  82%|████████▏ | 16404/19990 [46:31<25:09,  2.38it/s]

[16406] Геокодируем адрес: Дачный пр-т 29к3, Санкт-Петербург

Геокодирование:  82%|████████▏ | 16407/19990 [46:32<23:34,  2.53it/s]

[16408] Геокодируем адрес: Металлистов пр-т 23к4, Санкт-Петербург

Геокодирование:  82%|████████▏ | 16409/19990 [46:33<24:18,  2.46it/s]

[16409] Геокодируем адрес: Пушкин Кузьминского ш, Санкт-Петербург

Геокодирование:  82%|████████▏ | 16411/19990 [46:34<26:14,  2.27it/s]

Автосохранение после 16410 строк...
[16417] Геокодируем адрес: Металлистов пр-т 21к1, Санкт-Петербург

Геокодирование:  82%|████████▏ | 16418/19990 [46:35<14:43,  4.04it/s]

[16429] Геокодируем адрес: Космонавтов пр-т 15, Санкт-Петербург

Геокодирование:  82%|████████▏ | 16430/19990 [46:36<09:11,  6.45it/s]

[16432] Геокодируем адрес: Луначарского пр-т 78к1, Санкт-Петербург

Геокодирование:  82%|████████▏ | 16433/19990 [46:37<10:17,  5.76it/s]

[16437] Геокодируем адрес: Вадим Шефнер ул 10к1, Санкт-Петербург

Геокодирование:  82%|████████▏ | 16438/19990 [46:38<10:47,  5.48it/s]

[16438] Геокодируем адрес: Песочный садовая ул 83стр1, Санкт-Петербург

Геокодирование:  82%|████████▏ | 16441/19990 [46:39<12:20,  4.79it/s]

Автосохранение после 16440 строк...
[16442] Геокодируем адрес: Хазова ул 26,24,11,30, Санкт-Петербург

Геокодирование:  82%|████████▏ | 16443/19990 [46:40<15:56,  3.71it/s]

[16448] Геокодируем адрес: Авиаконструкторов пр-т 31, Санкт-Петербург

Геокодирование:  82%|████████▏ | 16449/19990 [46:41<13:01,  4.53it/s]

[16463] Геокодируем адрес: Челиева ул, Санкт-Петербург

Геокодирование:  82%|████████▏ | 16464/19990 [46:42<07:04,  8.31it/s]

[16465] Геокодируем адрес: Торфяная дор 17к2, Санкт-Петербург

Геокодирование:  82%|████████▏ | 16466/19990 [46:43<09:25,  6.24it/s]

[16466] Геокодируем адрес: московский пр-т 130ж, Санкт-Петербург

Геокодирование:  82%|████████▏ | 16467/19990 [46:44<13:35,  4.32it/s]

[16468] Геокодируем адрес: московский пр-т 130ж, Санкт-Петербург

Геокодирование:  82%|████████▏ | 16471/19990 [46:45<13:59,  4.19it/s]

Автосохранение после 16470 строк...
[16483] Геокодируем адрес: медиков пр-т 10, Санкт-Петербург

Геокодирование:  82%|████████▏ | 16484/19990 [46:46<07:16,  8.03it/s]

[16484] Геокодируем адрес: усть-славянка советский пр-т 41к1, Санкт-Петербург

Геокодирование:  82%|████████▏ | 16485/19990 [46:47<10:26,  5.59it/s]

[16485] Геокодируем адрес: 22-я линия ВО 3к7, Санкт-Петербург

Геокодирование:  82%|████████▏ | 16486/19990 [46:49<16:09,  3.61it/s]

[16487] Геокодируем адрес: Шушары Старорусский ул, Санкт-Петербург

Геокодирование:  82%|████████▏ | 16488/19990 [46:49<16:32,  3.53it/s]

[16488] Геокодируем адрес: Шушары Окуловская ул, Санкт-Петербург

Геокодирование:  82%|████████▏ | 16489/19990 [46:50<21:37,  2.70it/s]

[16489] Геокодируем адрес: Шушары Окуловская ул, Санкт-Петербург

Геокодирование:  82%|████████▏ | 16490/19990 [46:51<27:11,  2.14it/s]

[16497] Геокодируем адрес: Металлистов пр-т 61к2, Санкт-Петербург

Геокодирование:  83%|████████▎ | 16498/19990 [46:52<14:39,  3.97it/s]

[16500] Геокодируем адрес: Славы пр-т 4, Санкт-Петербург

Геокодирование:  83%|████████▎ | 16501/19990 [46:53<17:22,  3.35it/s]

Автосохранение после 16500 строк...
[16508] Геокодируем адрес: Дачный пр-т 16к4, Санкт-Петербург

Геокодирование:  83%|████████▎ | 16509/19990 [46:54<11:17,  5.14it/s]

[16518] Геокодируем адрес: Энергетиков пр-т 30к2, Санкт-Петербург

Геокодирование:  83%|████████▎ | 16531/19990 [46:55<05:09, 11.19it/s]

Автосохранение после 16530 строк...
[16531] Геокодируем адрес: Саперный Дорожная ул 13к2, Санкт-Петербург

Геокодирование:  83%|████████▎ | 16534/19990 [46:56<06:35,  8.73it/s]

[16535] Геокодируем адрес: Веденнева ул, Санкт-Петербург
[16536] Геокодируем адрес: Спирина ул 18литА, Санкт-Петербург

Геокодирование:  83%|████████▎ | 16537/19990 [46:58<11:38,  4.95it/s]

[16543] Геокодируем адрес: Патриотов пр-т 34, Санкт-Петербург

Геокодирование:  83%|████████▎ | 16544/19990 [46:59<10:52,  5.28it/s]

[16544] Геокодируем адрес: Витебский пр-т КБ, Санкт-Петербург

Геокодирование:  83%|████████▎ | 16546/19990 [47:00<12:54,  4.45it/s]

[16547] Геокодируем адрес: Шлиссербургский пр-т, Санкт-Петербург

Геокодирование:  83%|████████▎ | 16548/19990 [47:01<14:51,  3.86it/s]

[16559] Геокодируем адрес: Петергоф Парковая ул 16, Санкт-Петербург

Геокодирование:  83%|████████▎ | 16561/19990 [47:02<09:28,  6.03it/s]

Автосохранение после 16560 строк...
[16584] Геокодируем адрес: сестрорецк мосина ул 148, Санкт-Петербург

Геокодирование:  83%|████████▎ | 16585/19990 [47:03<04:16, 13.27it/s]

[16586] Геокодируем адрес: Лесной пр-т 59к5, Санкт-Петербург

Геокодирование:  83%|████████▎ | 16591/19990 [47:04<05:23, 10.52it/s]

Автосохранение после 16590 строк...
[16592] Геокодируем адрес: Лесной пр-т 59к5, Санкт-Петербург

Геокодирование:  83%|████████▎ | 16593/19990 [47:05<07:35,  7.46it/s]

[16596] Геокодируем адрес: Стачек пр-т 148, Санкт-Петербург

Геокодирование:  83%|████████▎ | 16597/19990 [47:06<09:25,  6.00it/s]

[16597] Геокодируем адрес: Большой Сампсониевский пр-т, Санкт-Петербург

Геокодирование:  83%|████████▎ | 16598/19990 [47:07<13:13,  4.28it/s]

[16599] Геокодируем адрес: 1-й Муринский пр-т, Санкт-Петербург

Геокодирование:  83%|████████▎ | 16600/19990 [47:09<17:09,  3.29it/s]

[16602] Геокодируем адрес: Колпино Заводской пр-т 4, Санкт-Петербург

Геокодирование:  83%|████████▎ | 16603/19990 [47:09<16:05,  3.51it/s]

[16603] Геокодируем адрес: 19-я линия ВО 34к1Б, Санкт-Петербург

Геокодирование:  83%|████████▎ | 16604/19990 [47:10<19:55,  2.83it/s]

[16607] Геокодируем адрес: Ветеранов пр-т 122, Санкт-Петербург

Геокодирование:  83%|████████▎ | 16608/19990 [47:11<18:58,  2.97it/s]

[16609] Геокодируем адрес: Советский пр-т 12, Санкт-Петербург

Геокодирование:  83%|████████▎ | 16610/19990 [47:12<21:09,  2.66it/s]

[16613] Геокодируем адрес: 9-го Января пр-т, Санкт-Петербург

Геокодирование:  83%|████████▎ | 16614/19990 [47:13<18:15,  3.08it/s]

[16614] Геокодируем адрес: Пушкин Кедринская ул, Санкт-Петербург

Геокодирование:  83%|████████▎ | 16621/19990 [47:14<11:15,  4.99it/s]

Автосохранение после 16620 строк...
[16627] Геокодируем адрес: КРонштадт Карла Либкнехта ул 17, Санкт-Петербург

Геокодирование:  83%|████████▎ | 16628/19990 [47:15<09:26,  5.93it/s]

[16629] Геокодируем адрес: Ленинский пр-т 90, Санкт-Петербург

Геокодирование:  83%|████████▎ | 16630/19990 [47:16<13:05,  4.28it/s]

[16632] Геокодируем адрес: 2-ой Луч ул, Санкт-Петербург

Геокодирование:  83%|████████▎ | 16633/19990 [47:17<13:34,  4.12it/s]

[16638] Геокодируем адрес: Советский пр-т 41к1, Санкт-Петербург

Геокодирование:  83%|████████▎ | 16639/19990 [47:18<11:42,  4.77it/s]

[16639] Геокодируем адрес: Еремеева ул 3,5,7, Санкт-Петербург

Геокодирование:  83%|████████▎ | 16640/19990 [47:19<15:55,  3.51it/s]

[16644] Геокодируем адрес: Юрия Гагарина пр-т 36, Санкт-Петербург

Геокодирование:  83%|████████▎ | 16651/19990 [47:21<09:31,  5.84it/s]

Автосохранение после 16650 строк...
[16662] Геокодируем адрес: Лиговский пр-т 78, Санкт-Петербург

Геокодирование:  83%|████████▎ | 16663/19990 [47:22<06:34,  8.44it/s]

[16664] Геокодируем адрес: Лиговский пр-т 78, Санкт-Петербург

Геокодирование:  83%|████████▎ | 16665/19990 [47:22<08:23,  6.60it/s]

[16665] Геокодируем адрес: Энтузиастов пр-т 54к3, Санкт-Петербург

Геокодирование:  83%|████████▎ | 16667/19990 [47:23<10:52,  5.10it/s]

[16668] Геокодируем адрес: Народного Ополчения пр-т 221, Санкт-Петербург

Геокодирование:  83%|████████▎ | 16669/19990 [47:24<14:19,  3.86it/s]

[16669] Геокодируем адрес: Шушары Московское ш 258к2, Санкт-Петербург

Геокодирование:  83%|████████▎ | 16670/19990 [47:25<17:39,  3.13it/s]

[16670] Геокодируем адрес: Колпино Пролетарская ул 97, Санкт-Петербург

Геокодирование:  83%|████████▎ | 16671/19990 [47:26<23:07,  2.39it/s]

[16676] Геокодируем адрес: Народного Ополчения пр-т 219, Санкт-Петербург

Геокодирование:  83%|████████▎ | 16681/19990 [47:28<11:38,  4.74it/s]

Автосохранение после 16680 строк...
[16681] Геокодируем адрес: Пушкин Ленинградская ул 67, Санкт-Петербург

Геокодирование:  83%|████████▎ | 16683/19990 [47:28<13:15,  4.16it/s]

[16692] Геокодируем адрес: Народного Ополчения пр-т 141, Санкт-Петербург

Геокодирование:  84%|████████▎ | 16693/19990 [47:29<09:03,  6.07it/s]

[16703] Геокодируем адрес: Шушары Московское ш 250к2, Санкт-Петербург

Геокодирование:  84%|████████▎ | 16704/19990 [47:30<06:36,  8.28it/s]

[16704] Геокодируем адрес: Шушары Школьная ул 17, Санкт-Петербург

Геокодирование:  84%|████████▎ | 16711/19990 [47:32<07:07,  7.67it/s]

Автосохранение после 16710 строк...
[16715] Геокодируем адрес: Мечникова пр-т 14, Санкт-Петербург

Геокодирование:  84%|████████▎ | 16716/19990 [47:32<07:43,  7.07it/s]

[16717] Геокодируем адрес: Обуховской Обороны пр-т 78, Санкт-Петербург

Геокодирование:  84%|████████▎ | 16718/19990 [47:33<10:30,  5.19it/s]

[16720] Геокодируем адрес: Новаторов б-р, Санкт-Петербург

Геокодирование:  84%|████████▎ | 16721/19990 [47:34<12:00,  4.53it/s]

[16722] Геокодируем адрес: 16-я линия ВО, Санкт-Петербург

Геокодирование:  84%|████████▎ | 16723/19990 [47:37<21:47,  2.50it/s]

[16727] Геокодируем адрес: Светлановский пр-т 60к1, Санкт-Петербург

Геокодирование:  84%|████████▍ | 16771/19990 [47:38<02:27, 21.85it/s]

Автосохранение после 16740 строк...
Автосохранение после 16770 строк...
[16776] Геокодируем адрес: Серебристый б-р, Санкт-Петербург

Геокодирование:  84%|████████▍ | 16780/19990 [47:38<02:54, 18.37it/s]

[16783] Геокодируем адрес: Ветеранов пр-т 175, Санкт-Петербург

Геокодирование:  84%|████████▍ | 16787/19990 [47:40<04:03, 13.14it/s]

[16787] Геокодируем адрес: 6-я линия ВО, Санкт-Петербург
[16788] Геокодируем адрес: Парголово Заречная ул 33, Санкт-Петербург
[16789] Геокодируем адрес: Лиговский пр-т 107, Санкт-Петербург
[16791] Геокодируем адрес: Товарищеский пер 32к2, Санкт-Петербург

Геокодирование:  84%|████████▍ | 16792/19990 [47:44<10:24,  5.12it/s]

[16792] Геокодируем адрес: Народного Ополчения пр-т 33, Санкт-Петербург
[16794] Геокодируем адрес: Парголово Заречная ул 13к4, Санкт-Петербург

Геокодирование:  84%|████████▍ | 16796/19990 [47:45<12:54,  4.12it/s]

[16796] Геокодируем адрес: Энергетиков пр-т 30к5, Санкт-Петербург
[16797] Геокодируем адрес: Ломоносов Победы ул 23, Санкт-Петербург

Геокодирование:  84%|████████▍ | 16801/19990 [47:48<14:56,  3.56it/s]

Автосохранение после 16800 строк...
[16801] Геокодируем адрес: nan
[16802] Геокодируем адрес: Люблинский пер 4, Санкт-Петербург

Геокодирование:  84%|████████▍ | 16803/19990 [47:49<19:37,  2.71it/s]

[16803] Геокодируем адрес: Школьная ул 11, Санкт-Петербург
[16804] Геокодируем адрес: nan

Геокодирование:  84%|████████▍ | 16805/19990 [47:51<25:22,  2.09it/s]

[16805] Геокодируем адрес: nan

Геокодирование:  84%|████████▍ | 16806/19990 [47:52<28:32,  1.86it/s]

[16806] Геокодируем адрес: nan

Геокодирование:  84%|████████▍ | 16807/19990 [47:53<31:44,  1.67it/s]

[16807] Геокодируем адрес: nan

Геокодирование:  84%|████████▍ | 16808/19990 [47:54<35:15,  1.50it/s]

[16808] Геокодируем адрес: Лесной пр-т 39, Санкт-Петербург

Геокодирование:  84%|████████▍ | 16809/19990 [47:56<41:45,  1.27it/s]

[16809] Геокодируем адрес: Алексея Толстого б-р 20, Санкт-Петербург

Геокодирование:  84%|████████▍ | 16810/19990 [47:57<43:34,  1.22it/s]

[16810] Геокодируем адрес: 4-я Советская ул 29, Санкт-Петербург

Геокодирование:  84%|████████▍ | 16811/19990 [47:58<44:45,  1.18it/s]

[16811] Геокодируем адрес: Вячеслава Шишкова ул 32А, Санкт-Петербург

Геокодирование:  84%|████████▍ | 16812/19990 [47:59<45:31,  1.16it/s]

[16812] Геокодируем адрес: Марата ул 16, Санкт-Петербург

Геокодирование:  84%|████████▍ | 16813/19990 [48:00<48:25,  1.09it/s]

[16813] Геокодируем адрес: nan

Геокодирование:  84%|████████▍ | 16814/19990 [48:00<47:30,  1.11it/s]

[16814] Геокодируем адрес: Большой Сампсониевский пр-т 80, Санкт-Петербург

Геокодирование:  84%|████████▍ | 16815/19990 [48:02<52:58,  1.00s/it]

[16815] Геокодируем адрес: Павловская ул 90, Санкт-Петербург

Геокодирование:  84%|████████▍ | 16816/19990 [48:03<49:23,  1.07it/s]

[16816] Геокодируем адрес: Дыбенко ул, Санкт-Петербург

Геокодирование:  84%|████████▍ | 16817/19990 [48:04<50:23,  1.05it/s]

[16817] Геокодируем адрес: Обводного канала наб 36, Санкт-Петербург

Геокодирование:  84%|████████▍ | 16818/19990 [48:05<52:47,  1.00it/s]

[16818] Геокодируем адрес: Дыбенко ул, Санкт-Петербург

Геокодирование:  84%|████████▍ | 16819/19990 [48:07<1:06:40,  1.26s/it]

[16819] Геокодируем адрес: Ириновский пр-т 41к2, Санкт-Петербург

Геокодирование:  84%|████████▍ | 16820/19990 [48:08<1:02:28,  1.18s/it]

[16820] Геокодируем адрес: Народного Ополчения пр-т 37, Санкт-Петербург

Геокодирование:  84%|████████▍ | 16821/19990 [48:09<1:02:31,  1.18s/it]

[16821] Геокодируем адрес: nan

Геокодирование:  84%|████████▍ | 16822/19990 [48:09<56:13,  1.07s/it]

[16822] Геокодируем адрес: Ленинский пр-т 97, Санкт-Петербург

Геокодирование:  84%|████████▍ | 16823/19990 [48:11<59:29,  1.13s/it]

[16823] Геокодируем адрес: Байконурская ул 4, Санкт-Петербург

Геокодирование:  84%|████████▍ | 16824/19990 [48:12<54:05,  1.03s/it]

[16824] Геокодируем адрес: Орджоникидзе ул 32, Санкт-Петербург

Геокодирование:  84%|████████▍ | 16825/19990 [48:13<55:23,  1.05s/it]

[16825] Геокодируем адрес: Шушары Старорусский пр-т, Санкт-Петербург

Геокодирование:  84%|████████▍ | 16826/19990 [48:14<53:03,  1.01s/it]

[16826] Геокодируем адрес: Счастливая ул, Санкт-Петербург

Геокодирование:  84%|████████▍ | 16827/19990 [48:14<52:06,  1.01it/s]

[16827] Геокодируем адрес: Гаккелевская ул, Санкт-Петербург

Геокодирование:  84%|████████▍ | 16828/19990 [48:15<52:12,  1.01it/s]

[16828] Геокодируем адрес: Солдата Корзуна ул 58к2, Санкт-Петербург

Геокодирование:  84%|████████▍ | 16829/19990 [48:17<52:41,  1.00s/it]

[16829] Геокодируем адрес: Ленсовета ул 63, Санкт-Петербург

Геокодирование:  84%|████████▍ | 16830/19990 [48:18<53:14,  1.01s/it]

[16830] Геокодируем адрес: Сестрорецк Володарского ул 6, Санкт-Петербург

Геокодирование:  84%|████████▍ | 16831/19990 [48:19<56:15,  1.07s/it]

Автосохранение после 16830 строк...
[16831] Геокодируем адрес: Пироговская наб, Санкт-Петербург

Геокодирование:  84%|████████▍ | 16832/19990 [48:20<51:34,  1.02it/s]

[16832] Геокодируем адрес: бухарестская ул 66к3, Санкт-Петербург

Геокодирование:  84%|████████▍ | 16833/19990 [48:21<52:53,  1.01s/it]

[16833] Геокодируем адрес: Александра Невского пл, Санкт-Петербург

Геокодирование:  84%|████████▍ | 16834/19990 [48:22<52:32,  1.00it/s]

[16834] Геокодируем адрес: Невский пр-т 81, Санкт-Петербург

Геокодирование:  84%|████████▍ | 16835/19990 [48:23<53:46,  1.02s/it]

[16835] Геокодируем адрес: Союза печатников ул 14, Санкт-Петербург

Геокодирование:  84%|████████▍ | 16836/19990 [48:24<51:50,  1.01it/s]

[16836] Геокодируем адрес: nan

Геокодирование:  84%|████████▍ | 16837/19990 [48:24<50:48,  1.03it/s]

[16837] Геокодируем адрес: Виленский пер 7, Санкт-Петербург

Геокодирование:  84%|████████▍ | 16838/19990 [48:26<52:00,  1.01it/s]

[16838] Геокодируем адрес: Седова ул 130, Санкт-Петербург

Геокодирование:  84%|████████▍ | 16839/19990 [48:27<54:43,  1.04s/it]

[16839] Геокодируем адрес: nan

Геокодирование:  84%|████████▍ | 16840/19990 [48:27<50:48,  1.03it/s]

[16840] Геокодируем адрес: Гаврилина ул 15, Санкт-Петербург

Геокодирование:  84%|████████▍ | 16841/19990 [48:29<53:28,  1.02s/it]

[16841] Геокодируем адрес: nan

Геокодирование:  84%|████████▍ | 16842/19990 [48:29<50:54,  1.03it/s]

[16842] Геокодируем адрес: Полевая Сабировская ул 47к1, Санкт-Петербург

Геокодирование:  84%|████████▍ | 16843/19990 [48:31<52:07,  1.01it/s]

[16843] Геокодируем адрес: Народная ул 16, Санкт-Петербург

Геокодирование:  84%|████████▍ | 16844/19990 [48:32<52:40,  1.00s/it]

[16844] Геокодируем адрес: nan

Геокодирование:  84%|████████▍ | 16845/19990 [48:32<51:19,  1.02it/s]

[16845] Геокодируем адрес: Стрельбищенская ул 26, Санкт-Петербург

Геокодирование:  84%|████████▍ | 16846/19990 [48:34<52:22,  1.00it/s]

[16846] Геокодируем адрес: nan

Геокодирование:  84%|████████▍ | 16847/19990 [48:34<51:41,  1.01it/s]

[16847] Геокодируем адрес: Народного Ополчения пр-т 41, Санкт-Петербург

Геокодирование:  84%|████████▍ | 16848/19990 [48:36<55:32,  1.06s/it]

[16848] Геокодируем адрес: Новоизмайловский пр-т 45, Санкт-Петербург

Геокодирование:  84%|████████▍ | 16849/19990 [48:37<53:32,  1.02s/it]

[16849] Геокодируем адрес: Фурштатская ул 44, Санкт-Петербург

Геокодирование:  84%|████████▍ | 16850/19990 [48:38<51:12,  1.02it/s]

[16850] Геокодируем адрес: Пушкин, Санкт-Петербург

Геокодирование:  84%|████████▍ | 16851/19990 [48:38<51:17,  1.02it/s]

[16851] Геокодируем адрес: nan

Геокодирование:  84%|████████▍ | 16852/19990 [48:39<51:08,  1.02it/s]

[16852] Геокодируем адрес: Люблинский пер 4, Санкт-Петербург

Геокодирование:  84%|████████▍ | 16853/19990 [48:41<52:00,  1.01it/s]

[16853] Геокодируем адрес: nan

Геокодирование:  84%|████████▍ | 16854/19990 [48:41<51:33,  1.01it/s]

[16854] Геокодируем адрес: Шушары Школьная ул 17, Санкт-Петербург

Геокодирование:  84%|████████▍ | 16855/19990 [48:43<53:09,  1.02s/it]

[16855] Геокодируем адрес: Трефолева ул 35, Санкт-Петербург

Геокодирование:  84%|████████▍ | 16856/19990 [48:44<52:55,  1.01s/it]

[16856] Геокодируем адрес: 11-я Красноармейская ул 10, Санкт-Петербург

Геокодирование:  84%|████████▍ | 16857/19990 [48:45<53:09,  1.02s/it]

[16857] Геокодируем адрес: Металлострой Садовая ул 8, Санкт-Петербург

Геокодирование:  84%|████████▍ | 16858/19990 [48:46<52:32,  1.01s/it]

[16858] Геокодируем адрес: Шушары Старорусский ул 13к1, Санкт-Петербург

Геокодирование:  84%|████████▍ | 16859/19990 [48:47<51:44,  1.01it/s]

[16859] Геокодируем адрес: Карла Либкнехта ул 15, Санкт-Петербург

Геокодирование:  84%|████████▍ | 16860/19990 [48:48<54:00,  1.04s/it]

[16860] Геокодируем адрес: Победы ул 21, Санкт-Петербург

Геокодирование:  84%|████████▍ | 16861/19990 [48:49<57:16,  1.10s/it]

Автосохранение после 16860 строк...
[16861] Геокодируем адрес: nan

Геокодирование:  84%|████████▍ | 16862/19990 [48:49<49:11,  1.06it/s]

[16862] Геокодируем адрес: Ветеранов пр-т 171к1, Санкт-Петербург

Геокодирование:  84%|████████▍ | 16863/19990 [48:51<51:13,  1.02it/s]

[16863] Геокодируем адрес: nan

Геокодирование:  84%|████████▍ | 16864/19990 [48:51<50:22,  1.03it/s]

[16864] Геокодируем адрес: nan

Геокодирование:  84%|████████▍ | 16865/19990 [48:52<50:43,  1.03it/s]

[16865] Геокодируем адрес: Петергоф, Санкт-Петербург

Геокодирование:  84%|████████▍ | 16866/19990 [48:54<51:47,  1.01it/s]

[16866] Геокодируем адрес: Шушары Московское ш, Санкт-Петербург

Геокодирование:  84%|████████▍ | 16867/19990 [48:55<51:36,  1.01it/s]

[16867] Геокодируем адрес: Саперный Дорожная ул 13к2, Санкт-Петербург

Геокодирование:  84%|████████▍ | 16868/19990 [48:56<52:10,  1.00s/it]

[16868] Геокодируем адрес: nan

Геокодирование:  84%|████████▍ | 16869/19990 [48:57<51:34,  1.01it/s]

[16869] Геокодируем адрес: nan

Геокодирование:  84%|████████▍ | 16870/19990 [48:57<51:20,  1.01it/s]

[16870] Геокодируем адрес: Муринская дор, Санкт-Петербург

Геокодирование:  84%|████████▍ | 16871/19990 [48:59<51:59,  1.00s/it]

[16871] Геокодируем адрес: Шаумяна пр-т, Санкт-Петербург

Геокодирование:  84%|████████▍ | 16872/19990 [49:00<53:11,  1.02s/it]

[16872] Геокодируем адрес: nan

Геокодирование:  84%|████████▍ | 16873/19990 [49:00<51:09,  1.02it/s]

[16873] Геокодируем адрес: Двинская ул 8к1, Санкт-Петербург

Геокодирование:  84%|████████▍ | 16874/19990 [49:03<1:07:55,  1.31s/it]

[16874] Геокодируем адрес: Московская ул, Санкт-Петербург

Геокодирование:  84%|████████▍ | 16875/19990 [49:04<1:03:05,  1.22s/it]

[16875] Геокодируем адрес: nan

Геокодирование:  84%|████████▍ | 16876/19990 [49:05<59:06,  1.14s/it]

[16876] Геокодируем адрес: шлиссельбургский пр-т 24к1, Санкт-Петербург

Геокодирование:  84%|████████▍ | 16877/19990 [49:06<58:28,  1.13s/it]

[16877] Геокодируем адрес: nan

Геокодирование:  84%|████████▍ | 16878/19990 [49:06<54:32,  1.05s/it]

[16878] Геокодируем адрес: Яхтенная ул 1к1, Санкт-Петербург

Геокодирование:  84%|████████▍ | 16879/19990 [49:08<55:32,  1.07s/it]

[16879] Геокодируем адрес: Кузнецовская ул 10к3, Санкт-Петербург

Геокодирование:  84%|████████▍ | 16880/19990 [49:09<53:27,  1.03s/it]

[16880] Геокодируем адрес: Энгельса пр-т 129к1, Санкт-Петербург

Геокодирование:  84%|████████▍ | 16881/19990 [49:10<53:24,  1.03s/it]

[16881] Геокодируем адрес: Веры Слуцкой ул 89, Санкт-Петербург

Геокодирование:  84%|████████▍ | 16882/19990 [49:11<53:25,  1.03s/it]

[16882] Геокодируем адрес: Кушелевская дор 5/8, Санкт-Петербург

Геокодирование:  84%|████████▍ | 16883/19990 [49:12<52:43,  1.02s/it]

[16883] Геокодируем адрес: Наличная ул 25/84, Санкт-Петербург

Геокодирование:  84%|████████▍ | 16884/19990 [49:13<51:56,  1.00s/it]

[16884] Геокодируем адрес: Стремянная ул, Санкт-Петербург

Геокодирование:  84%|████████▍ | 16885/19990 [49:14<51:29,  1.00it/s]

[16885] Геокодируем адрес: Асафьева ул 12к2, Санкт-Петербург

Геокодирование:  84%|████████▍ | 16886/19990 [49:15<51:28,  1.01it/s]

[16886] Геокодируем адрес: Большевиков пр-т, Санкт-Петербург

Геокодирование:  84%|████████▍ | 16887/19990 [49:16<52:16,  1.01s/it]

[16887] Геокодируем адрес: Ленская ул 3к1, Санкт-Петербург

Геокодирование:  84%|████████▍ | 16888/19990 [49:17<51:46,  1.00s/it]

[16888] Геокодируем адрес: Ленская ул 3к1, Санкт-Петербург

Геокодирование:  84%|████████▍ | 16889/19990 [49:18<51:48,  1.00s/it]

[16889] Геокодируем адрес: Мечникова пр-т, Санкт-Петербург

Геокодирование:  84%|████████▍ | 16890/19990 [49:19<51:53,  1.00s/it]

[16890] Геокодируем адрес: Лиственная ул 22А, Санкт-Петербург

Геокодирование:  84%|████████▍ | 16891/19990 [49:20<55:11,  1.07s/it]

Автосохранение после 16890 строк...
[16891] Геокодируем адрес: nan

Геокодирование:  85%|████████▍ | 16892/19990 [49:21<49:49,  1.04it/s]

[16892] Геокодируем адрес: Петергофское ш 15к2, Санкт-Петербург

Геокодирование:  85%|████████▍ | 16893/19990 [49:22<51:14,  1.01it/s]

[16893] Геокодируем адрес: Большая Зеленина ул 26, Санкт-Петербург

Геокодирование:  85%|████████▍ | 16894/19990 [49:23<50:48,  1.02it/s]

[16894] Геокодируем адрес: Большая Зеленина ул 20, Санкт-Петербург

Геокодирование:  85%|████████▍ | 16895/19990 [49:24<51:17,  1.01it/s]

[16895] Геокодируем адрес: nan

Геокодирование:  85%|████████▍ | 16896/19990 [49:24<50:17,  1.03it/s]

[16896] Геокодируем адрес: nan

Геокодирование:  85%|████████▍ | 16897/19990 [49:26<50:57,  1.01it/s]

[16897] Геокодируем адрес: Кавалергардская ул 8-10, Санкт-Петербург

Геокодирование:  85%|████████▍ | 16898/19990 [49:27<53:02,  1.03s/it]

[16898] Геокодируем адрес: 11-я линия ВО 66-68, Санкт-Петербург

Геокодирование:  85%|████████▍ | 16899/19990 [49:29<1:12:49,  1.41s/it]

[16899] Геокодируем адрес: Народного Ополчения пр-т, Санкт-Петербург

Геокодирование:  85%|████████▍ | 16900/19990 [49:30<1:01:55,  1.20s/it]

[16900] Геокодируем адрес: Невский пр-т 134, Санкт-Петербург

Геокодирование:  85%|████████▍ | 16901/19990 [49:31<59:29,  1.16s/it]

[16901] Геокодируем адрес: Комендантский пр-т 13к1, Санкт-Петербург

Геокодирование:  85%|████████▍ | 16902/19990 [49:32<55:35,  1.08s/it]

[16902] Геокодируем адрес: Ломоносов Жоры Антоненко ул 16, Санкт-Петербург

Геокодирование:  85%|████████▍ | 16903/19990 [49:33<54:14,  1.05s/it]

[16903] Геокодируем адрес: Ломоносов Жоры Антоненко ул 16, Санкт-Петербург

Геокодирование:  85%|████████▍ | 16904/19990 [49:34<53:54,  1.05s/it]

[16904] Геокодируем адрес: Ломоносов Жоры Антоненко ул 16, Санкт-Петербург

Геокодирование:  85%|████████▍ | 16905/19990 [49:35<52:48,  1.03s/it]

[16905] Геокодируем адрес: Бабушкина ул 52, Санкт-Петербург

Геокодирование:  85%|████████▍ | 16906/19990 [49:36<53:06,  1.03s/it]

[16906] Геокодируем адрес: Бабушкина ул 10, Санкт-Петербург

Геокодирование:  85%|████████▍ | 16907/19990 [49:37<53:39,  1.04s/it]

[16907] Геокодируем адрес: Петергоф Санкт-Петербургский пр-т, Санкт-Петербург

Геокодирование:  85%|████████▍ | 16908/19990 [49:38<51:22,  1.00s/it]

[16908] Геокодируем адрес: Петергоф Ропшинское ш 10, Санкт-Петербург

Геокодирование:  85%|████████▍ | 16909/19990 [49:39<52:15,  1.02s/it]

[16909] Геокодируем адрес: Петергоф Ропшинское ш 10, Санкт-Петербург

Геокодирование:  85%|████████▍ | 16910/19990 [49:40<52:02,  1.01s/it]

[16910] Геокодируем адрес: Зеленогорск Комсомольская ул 10, Санкт-Петербург

Геокодирование:  85%|████████▍ | 16911/19990 [49:41<50:50,  1.01it/s]

[16911] Геокодируем адрес: Потапова ул, Санкт-Петербург

Геокодирование:  85%|████████▍ | 16912/19990 [49:42<49:58,  1.03it/s]

[16912] Геокодируем адрес: Петергоф Ропшинское ш 10, Санкт-Петербург

Геокодирование:  85%|████████▍ | 16913/19990 [49:43<51:23,  1.00s/it]

[16913] Геокодируем адрес: Петергоф, Санкт-Петербург

Геокодирование:  85%|████████▍ | 16914/19990 [49:44<50:14,  1.02it/s]

[16914] Геокодируем адрес: nan

Геокодирование:  85%|████████▍ | 16915/19990 [49:45<50:15,  1.02it/s]

[16915] Геокодируем адрес: nan

Геокодирование:  85%|████████▍ | 16916/19990 [49:46<50:17,  1.02it/s]

[16916] Геокодируем адрес: nan

Геокодирование:  85%|████████▍ | 16917/19990 [49:47<50:32,  1.01it/s]

[16917] Геокодируем адрес: Варшавская ул 73, Санкт-Петербург

Геокодирование:  85%|████████▍ | 16918/19990 [49:48<51:40,  1.01s/it]

[16918] Геокодируем адрес: Варшавская ул 39/2, Санкт-Петербург

Геокодирование:  85%|████████▍ | 16919/19990 [49:49<52:55,  1.03s/it]

[16919] Геокодируем адрес: Костюшко ул 72, Санкт-Петербург

Геокодирование:  85%|████████▍ | 16920/19990 [49:50<51:24,  1.00s/it]

[16920] Геокодируем адрес: Костюшко ул 72, Санкт-Петербург

Геокодирование:  85%|████████▍ | 16921/19990 [49:51<53:48,  1.05s/it]

Автосохранение после 16920 строк...
[16921] Геокодируем адрес: Костюшко ул 66, Санкт-Петербург

Геокодирование:  85%|████████▍ | 16922/19990 [49:52<50:16,  1.02it/s]

[16922] Геокодируем адрес: Беринга ул 26к3Е, Санкт-Петербург

Геокодирование:  85%|████████▍ | 16923/19990 [49:52<49:05,  1.04it/s]

[16923] Геокодируем адрес: Институтский пер 5к6, Санкт-Петербург

Геокодирование:  85%|████████▍ | 16924/19990 [49:54<50:33,  1.01it/s]

[16924] Геокодируем адрес: nan

Геокодирование:  85%|████████▍ | 16925/19990 [49:55<50:03,  1.02it/s]

[16925] Геокодируем адрес: Тельмана ул, Санкт-Петербург

Геокодирование:  85%|████████▍ | 16926/19990 [49:56<51:27,  1.01s/it]

[16926] Геокодируем адрес: Патриотов пр-т, Санкт-Петербург

Геокодирование:  85%|████████▍ | 16927/19990 [49:57<51:43,  1.01s/it]

[16927] Геокодируем адрес: Тельмана ул, Санкт-Петербург

Геокодирование:  85%|████████▍ | 16928/19990 [49:58<50:57,  1.00it/s]

[16928] Геокодируем адрес: Петергоф Мельничная ул, Санкт-Петербург

Геокодирование:  85%|████████▍ | 16929/19990 [49:59<50:28,  1.01it/s]

[16929] Геокодируем адрес: nan

Геокодирование:  85%|████████▍ | 16930/19990 [50:00<50:16,  1.01it/s]

[16930] Геокодируем адрес: Рыбацкий пр-т 43к1, Санкт-Петербург

Геокодирование:  85%|████████▍ | 16931/19990 [50:01<52:01,  1.02s/it]

[16931] Геокодируем адрес: nan

Геокодирование:  85%|████████▍ | 16932/19990 [50:02<49:57,  1.02it/s]

[16932] Геокодируем адрес: nan

Геокодирование:  85%|████████▍ | 16933/19990 [50:03<50:24,  1.01it/s]

[16933] Геокодируем адрес: Тельмана ул 14, Санкт-Петербург

Геокодирование:  85%|████████▍ | 16934/19990 [50:04<52:59,  1.04s/it]

[16934] Геокодируем адрес: nan

Геокодирование:  85%|████████▍ | 16935/19990 [50:05<49:52,  1.02it/s]

[16935] Геокодируем адрес: nan

Геокодирование:  85%|████████▍ | 16936/19990 [50:06<50:11,  1.01it/s]

[16936] Геокодируем адрес: Тельмана ул 40, Санкт-Петербург

Геокодирование:  85%|████████▍ | 16937/19990 [50:07<53:00,  1.04s/it]

[16937] Геокодируем адрес: русановская ул, Санкт-Петербург

Геокодирование:  85%|████████▍ | 16938/19990 [50:08<50:10,  1.01it/s]

[16938] Геокодируем адрес: Фарфоровская ул 24, Санкт-Петербург

Геокодирование:  85%|████████▍ | 16939/19990 [50:09<51:18,  1.01s/it]

[16939] Геокодируем адрес: Тельмана ул 22, Санкт-Петербург

Геокодирование:  85%|████████▍ | 16940/19990 [50:10<52:02,  1.02s/it]

[16940] Геокодируем адрес: nan

Геокодирование:  85%|████████▍ | 16941/19990 [50:11<49:28,  1.03it/s]

[16941] Геокодируем адрес: Тельмана ул 16, Санкт-Петербург

Геокодирование:  85%|████████▍ | 16942/19990 [50:12<51:31,  1.01s/it]

[16942] Геокодируем адрес: Шаумяна пр-т 34, Санкт-Петербург

Геокодирование:  85%|████████▍ | 16943/19990 [50:13<51:33,  1.02s/it]

[16943] Геокодируем адрес: Рябовское ш 57, Санкт-Петербург

Геокодирование:  85%|████████▍ | 16944/19990 [50:14<50:17,  1.01it/s]

[16944] Геокодируем адрес: nan

Геокодирование:  85%|████████▍ | 16945/19990 [50:15<49:20,  1.03it/s]

[16945] Геокодируем адрес: nan

Геокодирование:  85%|████████▍ | 16946/19990 [50:16<49:44,  1.02it/s]

[16946] Геокодируем адрес: Авиаконструкторов пр-т 19, Санкт-Петербург

Геокодирование:  85%|████████▍ | 16947/19990 [50:17<52:41,  1.04s/it]

[16947] Геокодируем адрес: щербакова ул 5, Санкт-Петербург

Геокодирование:  85%|████████▍ | 16948/19990 [50:18<51:16,  1.01s/it]

[16948] Геокодируем адрес: nan

Геокодирование:  85%|████████▍ | 16949/19990 [50:19<49:15,  1.03it/s]

[16949] Геокодируем адрес: nan

Геокодирование:  85%|████████▍ | 16950/19990 [50:20<49:49,  1.02it/s]

[16950] Геокодируем адрес: nan

Геокодирование:  85%|████████▍ | 16951/19990 [50:21<52:17,  1.03s/it]

Автосохранение после 16950 строк...
[16951] Геокодируем адрес: Первомайская ул 15, Санкт-Петербург

Геокодирование:  85%|████████▍ | 16952/19990 [50:22<52:11,  1.03s/it]

[16952] Геокодируем адрес: Московское ш, Санкт-Петербург

Геокодирование:  85%|████████▍ | 16953/19990 [50:23<49:43,  1.02it/s]

[16953] Геокодируем адрес: Пушкинская ул 8А, Санкт-Петербург

Геокодирование:  85%|████████▍ | 16954/19990 [50:24<53:02,  1.05s/it]

[16954] Геокодируем адрес: nan

Геокодирование:  85%|████████▍ | 16955/19990 [50:25<48:24,  1.04it/s]

[16955] Геокодируем адрес: Марата ул 70, Санкт-Петербург

Геокодирование:  85%|████████▍ | 16956/19990 [50:26<51:01,  1.01s/it]

[16956] Геокодируем адрес: Крименчугская ул 11к1, Санкт-Петербург

Геокодирование:  85%|████████▍ | 16957/19990 [50:27<48:45,  1.04it/s]

[16957] Геокодируем адрес: Пушкинская ул 5, Санкт-Петербург

Геокодирование:  85%|████████▍ | 16958/19990 [50:28<50:37,  1.00s/it]

[16958] Геокодируем адрес: Кавалергардская ул 21, Санкт-Петербург

Геокодирование:  85%|████████▍ | 16959/19990 [50:29<50:05,  1.01it/s]

[16959] Геокодируем адрес: 6-я Красноармейская ул 22, Санкт-Петербург

Геокодирование:  85%|████████▍ | 16960/19990 [50:30<51:55,  1.03s/it]

[16960] Геокодируем адрес: Московское ш 244, Санкт-Петербург

Геокодирование:  85%|████████▍ | 16961/19990 [50:31<52:46,  1.05s/it]

[16961] Геокодируем адрес: Пестеля ул 11, Санкт-Петербург

Геокодирование:  85%|████████▍ | 16962/19990 [50:32<49:46,  1.01it/s]

[16962] Геокодируем адрес: nan

Геокодирование:  85%|████████▍ | 16963/19990 [50:33<48:41,  1.04it/s]

[16963] Геокодируем адрес: nan

Геокодирование:  85%|████████▍ | 16964/19990 [50:34<49:00,  1.03it/s]

[16964] Геокодируем адрес: Патриотов пр-т, Санкт-Петербург

Геокодирование:  85%|████████▍ | 16965/19990 [50:35<50:41,  1.01s/it]

[16965] Геокодируем адрес: Рыбацкий пр-т, Санкт-Петербург

Геокодирование:  85%|████████▍ | 16966/19990 [50:37<1:05:15,  1.29s/it]

[16966] Геокодируем адрес: nan

Геокодирование:  85%|████████▍ | 16967/19990 [50:38<1:00:03,  1.19s/it]

[16967] Геокодируем адрес: Карпинского ул 24, Санкт-Петербург

Геокодирование:  85%|████████▍ | 16968/19990 [50:39<58:50,  1.17s/it]

[16968] Геокодируем адрес: Автовская ул 18, Санкт-Петербург

Геокодирование:  85%|████████▍ | 16969/19990 [50:40<55:12,  1.10s/it]

[16969] Геокодируем адрес: nan

Геокодирование:  85%|████████▍ | 16970/19990 [50:41<52:58,  1.05s/it]

[16970] Геокодируем адрес: nan

Геокодирование:  85%|████████▍ | 16971/19990 [50:42<52:12,  1.04s/it]

[16971] Геокодируем адрес: nan

Геокодирование:  85%|████████▍ | 16972/19990 [50:43<51:50,  1.03s/it]

[16972] Геокодируем адрес: nan

Геокодирование:  85%|████████▍ | 16973/19990 [50:44<51:07,  1.02s/it]

[16973] Геокодируем адрес: nan

Геокодирование:  85%|████████▍ | 16974/19990 [50:45<50:53,  1.01s/it]

[16974] Геокодируем адрес: патриотов пр-т, Санкт-Петербург

Геокодирование:  85%|████████▍ | 16975/19990 [50:46<51:36,  1.03s/it]

[16975] Геокодируем адрес: nan

Геокодирование:  85%|████████▍ | 16976/19990 [50:47<50:14,  1.00s/it]

[16976] Геокодируем адрес: Бертовский пер, Санкт-Петербург

Геокодирование:  85%|████████▍ | 16977/19990 [50:48<50:34,  1.01s/it]

[16977] Геокодируем адрес: Дмитрия Устинова ул, Санкт-Петербург

Геокодирование:  85%|████████▍ | 16978/19990 [50:49<50:40,  1.01s/it]

[16978] Геокодируем адрес: Двадцать Пятого Октября пр-т, Санкт-Петербург

Геокодирование:  85%|████████▍ | 16979/19990 [50:50<51:36,  1.03s/it]

[16979] Геокодируем адрес: Миллионная ул, Санкт-Петербург

Геокодирование:  85%|████████▍ | 16980/19990 [50:51<49:59,  1.00it/s]

[16980] Геокодируем адрес: Киевская ул, Санкт-Петербург

Геокодирование:  85%|████████▍ | 16981/19990 [50:52<52:44,  1.05s/it]

Автосохранение после 16980 строк...
[16981] Геокодируем адрес: реки Смоленки наб, Санкт-Петербург

Геокодирование:  85%|████████▍ | 16982/19990 [50:53<49:32,  1.01it/s]

[16982] Геокодируем адрес: Арсенальная ул, Санкт-Петербург

Геокодирование:  85%|████████▍ | 16983/19990 [50:54<49:29,  1.01it/s]

[16983] Геокодируем адрес: Смольная наб, Санкт-Петербург

Геокодирование:  85%|████████▍ | 16984/19990 [50:55<49:17,  1.02it/s]

[16984] Геокодируем адрес: Славы пр-т, Санкт-Петербург

Геокодирование:  85%|████████▍ | 16985/19990 [50:56<50:53,  1.02s/it]

[16985] Геокодируем адрес: Ушинского ул, Санкт-Петербург

Геокодирование:  85%|████████▍ | 16986/19990 [50:57<49:45,  1.01it/s]

[16986] Геокодируем адрес: Шушары Вишерская ул 2, Санкт-Петербург

Геокодирование:  85%|████████▍ | 16987/19990 [50:58<50:14,  1.00s/it]

[16987] Геокодируем адрес: Шушары Школьная ул 17, Санкт-Петербург

Геокодирование:  85%|████████▍ | 16988/19990 [50:59<50:38,  1.01s/it]

[16988] Геокодируем адрес: Московский пр-т 73к5, Санкт-Петербург

Геокодирование:  85%|████████▍ | 16989/19990 [51:00<50:09,  1.00s/it]

[16989] Геокодируем адрес: Костюшко ул 74, Санкт-Петербург

Геокодирование:  85%|████████▍ | 16990/19990 [51:01<50:06,  1.00s/it]

[16990] Геокодируем адрес: Старорусский пр-т 13, Санкт-Петербург

Геокодирование:  85%|████████▍ | 16991/19990 [51:02<52:29,  1.05s/it]

[16991] Геокодируем адрес: nan

Геокодирование:  85%|████████▌ | 16992/19990 [51:03<47:59,  1.04it/s]

[16992] Геокодируем адрес: Красного Курсанта ул, Санкт-Петербург

Геокодирование:  85%|████████▌ | 16993/19990 [51:04<49:00,  1.02it/s]

[16993] Геокодируем адрес: Шушары Первомайская ул, Санкт-Петербург

Геокодирование:  85%|████████▌ | 16994/19990 [51:05<49:27,  1.01it/s]

[16994] Геокодируем адрес: Митрофаньевское ш, Санкт-Петербург

Геокодирование:  85%|████████▌ | 16995/19990 [51:06<49:27,  1.01it/s]

[16995] Геокодируем адрес: nan

Геокодирование:  85%|████████▌ | 16996/19990 [51:07<49:03,  1.02it/s]

[16996] Геокодируем адрес: Новая ул 51к15, Санкт-Петербург

Геокодирование:  85%|████████▌ | 16997/19990 [51:08<52:54,  1.06s/it]

[16997] Геокодируем адрес: Шостаковича ул, Санкт-Петербург

Геокодирование:  85%|████████▌ | 16998/19990 [51:09<48:41,  1.02it/s]

[16998] Геокодируем адрес: 1-й Муринский пр-т 11, Санкт-Петербург

RateLimiter caught an error, retrying (0/2 tries). Called with (*('1-й Муринский пр-т 11, Санкт-Петербург',), **{}).
Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connection.py", line 516, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1374, in getresponse
    response.begin()
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1278, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1134, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 367, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=1-%D0%B9+%D0%9C%D1%83%D1%80%D0%B8%D0%BD%D1%81%D0%BA%D0%B8%D0%B9+%D0%BF%D1%80-%D1%82+11%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 482, in _request
    resp = self.session.get(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=1-%D0%B9+%D0%9C%D1%83%D1%80%D0%B8%D0%BD%D1%81%D0%BA%D0%B8%D0%B9+%D0%BF%D1%80-%D1%82+11%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\extra\rate_limiter.py", line 136, in _retries_gen
    yield i  # Run the function.
    ^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\extra\rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\geocoders\nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\geocoders\base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 472, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 494, in _request
    raise GeocoderUnavailable(message)
geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=1-%D0%B9+%D0%9C%D1%83%D1%80%D0%B8%D0%BD%D1%81%D0%BA%D0%B8%D0%B9+%D0%BF%D1%80-%D1%82+11%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))
Геокодирование:  85%|████████▌ | 16999/19990 [51:18<3:01:54,  3.65s/it]

[16999] Геокодируем адрес: Художников пр-т 41, Санкт-Петербург

Геокодирование:  85%|████████▌ | 17000/19990 [51:20<2:34:52,  3.11s/it]

[17000] Геокодируем адрес: Энгельса пр-т 150к1, Санкт-Петербург

Геокодирование:  85%|████████▌ | 17001/19990 [51:21<2:02:31,  2.46s/it]

[17001] Геокодируем адрес: Дунайский пр-т 35, Санкт-Петербург

Геокодирование:  85%|████████▌ | 17002/19990 [51:22<1:41:41,  2.04s/it]

[17002] Геокодируем адрес: Дунайский пр-т 58к1, Санкт-Петербург

Геокодирование:  85%|████████▌ | 17003/19990 [51:23<1:24:05,  1.69s/it]

[17003] Геокодируем адрес: Фурштатская ул 44, Санкт-Петербург

Геокодирование:  85%|████████▌ | 17004/19990 [51:24<1:13:58,  1.49s/it]

[17004] Геокодируем адрес: Чернышевского ул 17, Санкт-Петербург

Геокодирование:  85%|████████▌ | 17005/19990 [51:25<1:07:43,  1.36s/it]

[17005] Геокодируем адрес: Варшавская ул 73, Санкт-Петербург

Геокодирование:  85%|████████▌ | 17006/19990 [51:26<1:01:29,  1.24s/it]

[17006] Геокодируем адрес: Луначарского пр-т, Санкт-Петербург

Геокодирование:  85%|████████▌ | 17007/19990 [51:27<58:56,  1.19s/it]

[17007] Геокодируем адрес: Культуры пр-т 15к2, Санкт-Петербург

Геокодирование:  85%|████████▌ | 17008/19990 [51:28<54:48,  1.10s/it]

[17008] Геокодируем адрес: Будапештская ул 108к2, Санкт-Петербург

Геокодирование:  85%|████████▌ | 17009/19990 [51:29<53:25,  1.08s/it]

[17009] Геокодируем адрес: Непокоренных пр-т 13к3, Санкт-Петербург

Геокодирование:  85%|████████▌ | 17010/19990 [51:30<52:06,  1.05s/it]

[17010] Геокодируем адрес: Генерала Симоняка ул 25Б, Санкт-Петербург

Геокодирование:  85%|████████▌ | 17011/19990 [51:31<53:54,  1.09s/it]

Автосохранение после 17010 строк...
[17011] Геокодируем адрес: Юнтоловский пр-т 49к3, Санкт-Петербург

Геокодирование:  85%|████████▌ | 17012/19990 [51:32<49:45,  1.00s/it]

[17012] Геокодируем адрес: Благодатная ул 23, Санкт-Петербург

Геокодирование:  85%|████████▌ | 17013/19990 [51:33<50:19,  1.01s/it]

[17013] Геокодируем адрес: Пулковское ш, Санкт-Петербург

Геокодирование:  85%|████████▌ | 17014/19990 [51:34<49:47,  1.00s/it]

[17014] Геокодируем адрес: Нарвская ул 8к2, Санкт-Петербург

Геокодирование:  85%|████████▌ | 17015/19990 [51:35<49:41,  1.00s/it]

[17015] Геокодируем адрес: Школьная ул 2, Санкт-Петербург

Геокодирование:  85%|████████▌ | 17016/19990 [51:36<53:11,  1.07s/it]

[17016] Геокодируем адрес: nan

Геокодирование:  85%|████████▌ | 17017/19990 [51:37<47:56,  1.03it/s]

[17017] Геокодируем адрес: Александровской Фермы пр-т 13, Санкт-Петербург

Геокодирование:  85%|████████▌ | 17018/19990 [51:38<51:54,  1.05s/it]

[17018] Геокодируем адрес: nan

Геокодирование:  85%|████████▌ | 17019/19990 [51:39<47:42,  1.04it/s]

[17019] Геокодируем адрес: Колпинское ш 40к1, Санкт-Петербург

Геокодирование:  85%|████████▌ | 17020/19990 [51:40<49:12,  1.01it/s]

[17020] Геокодируем адрес: Народная ул 16, Санкт-Петербург

Геокодирование:  85%|████████▌ | 17021/19990 [51:41<49:16,  1.00it/s]

[17021] Геокодируем адрес: Будапештская ул 95к1, Санкт-Петербург

Геокодирование:  85%|████████▌ | 17022/19990 [51:42<48:41,  1.02it/s]

[17022] Геокодируем адрес: Седова ул 22, Санкт-Петербург

Геокодирование:  85%|████████▌ | 17023/19990 [51:43<50:18,  1.02s/it]

[17023] Геокодируем адрес: Московское ш, Санкт-Петербург

Геокодирование:  85%|████████▌ | 17024/19990 [51:44<48:48,  1.01it/s]

[17024] Геокодируем адрес: Шушары Колпинское ш 12к2, Санкт-Петербург

Геокодирование:  85%|████████▌ | 17025/19990 [51:45<49:02,  1.01it/s]

[17025] Геокодируем адрес: Боровая ул 14, Санкт-Петербург

Геокодирование:  85%|████████▌ | 17026/19990 [51:46<49:36,  1.00s/it]

[17026] Геокодируем адрес: Софьи Ковалевской ул 15к5, Санкт-Петербург

Геокодирование:  85%|████████▌ | 17027/19990 [51:47<49:39,  1.01s/it]

[17027] Геокодируем адрес: Шушары, Санкт-Петербург

Геокодирование:  85%|████████▌ | 17028/19990 [51:48<49:04,  1.01it/s]

[17028] Геокодируем адрес: Красносельское ш 35, Санкт-Петербург

Геокодирование:  85%|████████▌ | 17029/19990 [51:49<50:16,  1.02s/it]

[17029] Геокодируем адрес: Пушкин Магазейная ул 18, Санкт-Петербург

Геокодирование:  85%|████████▌ | 17030/19990 [51:50<49:33,  1.00s/it]

[17030] Геокодируем адрес: Ланское ш, Санкт-Петербург

Геокодирование:  85%|████████▌ | 17031/19990 [51:51<48:17,  1.02it/s]

[17031] Геокодируем адрес: реки Фонтанки наб 66, Санкт-Петербург

Геокодирование:  85%|████████▌ | 17032/19990 [51:52<50:00,  1.01s/it]

[17032] Геокодируем адрес: Гагаринская ул 28, Санкт-Петербург

Геокодирование:  85%|████████▌ | 17033/19990 [51:53<48:41,  1.01it/s]

[17033] Геокодируем адрес: Стародеревенская ул 24к1, Санкт-Петербург

Геокодирование:  85%|████████▌ | 17034/19990 [51:54<49:07,  1.00it/s]

[17034] Геокодируем адрес: Смоляная ул 1, Санкт-Петербург

Геокодирование:  85%|████████▌ | 17035/19990 [51:55<49:05,  1.00it/s]

[17035] Геокодируем адрес: Шушары, Санкт-Петербург

Геокодирование:  85%|████████▌ | 17036/19990 [51:56<48:35,  1.01it/s]

[17036] Геокодируем адрес: Партизана Германа ул 3, Санкт-Петербург

Геокодирование:  85%|████████▌ | 17037/19990 [51:57<49:46,  1.01s/it]

[17037] Геокодируем адрес: nan

Геокодирование:  85%|████████▌ | 17038/19990 [51:58<48:08,  1.02it/s]

[17038] Геокодируем адрес: Шушары Вишерская ул, Санкт-Петербург

Геокодирование:  85%|████████▌ | 17039/19990 [51:59<48:54,  1.01it/s]

[17039] Геокодируем адрес: nan

Геокодирование:  85%|████████▌ | 17040/19990 [52:00<48:41,  1.01it/s]

[17040] Геокодируем адрес: Комарово Зеленогорское ш, Санкт-Петербург

Геокодирование:  85%|████████▌ | 17041/19990 [52:01<51:05,  1.04s/it]

Автосохранение после 17040 строк...
[17041] Геокодируем адрес: Обуховской Обороны наб, Санкт-Петербург

Геокодирование:  85%|████████▌ | 17042/19990 [52:02<48:54,  1.00it/s]

[17042] Геокодируем адрес: nan

Геокодирование:  85%|████████▌ | 17043/19990 [52:03<48:10,  1.02it/s]

[17043] Геокодируем адрес: Чёрной речки наб 10, Санкт-Петербург

Геокодирование:  85%|████████▌ | 17044/19990 [52:04<50:11,  1.02s/it]

[17044] Геокодируем адрес: 2-я Жерновская ул, Санкт-Петербург

Геокодирование:  85%|████████▌ | 17045/19990 [52:05<48:49,  1.01it/s]

[17045] Геокодируем адрес: nan

Геокодирование:  85%|████████▌ | 17046/19990 [52:06<48:07,  1.02it/s]

[17046] Геокодируем адрес: Первомайская ул, Санкт-Петербург

Геокодирование:  85%|████████▌ | 17047/19990 [52:07<50:28,  1.03s/it]

[17047] Геокодируем адрес: Обводного канала наб 28А, Санкт-Петербург

Геокодирование:  85%|████████▌ | 17048/19990 [52:08<49:36,  1.01s/it]

[17048] Геокодируем адрес: Старорусский пр-т 13к1, Санкт-Петербург

Геокодирование:  85%|████████▌ | 17049/19990 [52:09<48:57,  1.00it/s]

[17049] Геокодируем адрес: nan

Геокодирование:  85%|████████▌ | 17050/19990 [52:10<47:46,  1.03it/s]

[17050] Геокодируем адрес: Исполкомская ул, Санкт-Петербург

Геокодирование:  85%|████████▌ | 17051/19990 [52:11<48:25,  1.01it/s]

[17051] Геокодируем адрес: Генерала Симоняка ул 17, Санкт-Петербург

Геокодирование:  85%|████████▌ | 17052/19990 [52:12<49:04,  1.00s/it]

[17052] Геокодируем адрес: Взлётная ул 13, Санкт-Петербург

Геокодирование:  85%|████████▌ | 17053/19990 [52:13<48:58,  1.00s/it]

[17053] Геокодируем адрес: Окуловская ул 7к2, Санкт-Петербург

Геокодирование:  85%|████████▌ | 17054/19990 [52:14<48:57,  1.00s/it]

[17054] Геокодируем адрес: Чёрной речки наб 53к2, Санкт-Петербург

Геокодирование:  85%|████████▌ | 17055/19990 [52:15<48:47,  1.00it/s]

[17055] Геокодируем адрес: Окуловская ул 8, Санкт-Петербург

Геокодирование:  85%|████████▌ | 17056/19990 [52:16<48:44,  1.00it/s]

[17056] Геокодируем адрес: Чёрной речки наб, Санкт-Петербург

Геокодирование:  85%|████████▌ | 17057/19990 [52:17<48:32,  1.01it/s]

[17057] Геокодируем адрес: Окуловская ул 8, Санкт-Петербург

Геокодирование:  85%|████████▌ | 17058/19990 [52:18<48:52,  1.00s/it]

[17058] Геокодируем адрес: Новое ш, Санкт-Петербург

Геокодирование:  85%|████████▌ | 17059/19990 [52:19<48:55,  1.00s/it]

[17059] Геокодируем адрес: Ольги Берггольц ул 15, Санкт-Петербург

Геокодирование:  85%|████████▌ | 17060/19990 [52:20<49:20,  1.01s/it]

[17060] Геокодируем адрес: Двинская ул 4к1, Санкт-Петербург

Геокодирование:  85%|████████▌ | 17061/19990 [52:21<48:57,  1.00s/it]

[17061] Геокодируем адрес: Стахановцев ул 10, Санкт-Петербург

Геокодирование:  85%|████████▌ | 17062/19990 [52:22<49:23,  1.01s/it]

[17062] Геокодируем адрес: nan

Геокодирование:  85%|████████▌ | 17063/19990 [52:23<47:47,  1.02it/s]

[17063] Геокодируем адрес: Пятилеток пр-т 5, Санкт-Петербург

Геокодирование:  85%|████████▌ | 17064/19990 [52:24<50:10,  1.03s/it]

[17064] Геокодируем адрес: Петровский пр-т 20Р, Санкт-Петербург

Геокодирование:  85%|████████▌ | 17065/19990 [52:25<49:54,  1.02s/it]

[17065] Геокодируем адрес: Торжковская ул 30Ак1, Санкт-Петербург

Геокодирование:  85%|████████▌ | 17066/19990 [52:26<48:08,  1.01it/s]

[17066] Геокодируем адрес: nan

Геокодирование:  85%|████████▌ | 17067/19990 [52:27<47:28,  1.03it/s]

[17067] Геокодируем адрес: Омская ул, Санкт-Петербург

Геокодирование:  85%|████████▌ | 17068/19990 [52:28<48:33,  1.00it/s]

[17068] Геокодируем адрес: Витебский пр-т 41к2, Санкт-Петербург

Геокодирование:  85%|████████▌ | 17069/19990 [52:29<48:30,  1.00it/s]

[17069] Геокодируем адрес: Дальневосточный пр-т, Санкт-Петербург

Геокодирование:  85%|████████▌ | 17070/19990 [52:30<49:51,  1.02s/it]

[17070] Геокодируем адрес: Пролетарская ул 7, Санкт-Петербург

Геокодирование:  85%|████████▌ | 17071/19990 [52:31<51:44,  1.06s/it]

Автосохранение после 17070 строк...
[17071] Геокодируем адрес: Маршала Захарова пр-т 27к1, Санкт-Петербург

Геокодирование:  85%|████████▌ | 17072/19990 [52:32<48:56,  1.01s/it]

[17072] Геокодируем адрес: Пушкин Саперная ул 41/2, Санкт-Петербург

Геокодирование:  85%|████████▌ | 17073/19990 [52:33<49:41,  1.02s/it]

[17073] Геокодируем адрес: nan

Геокодирование:  85%|████████▌ | 17074/19990 [52:34<46:18,  1.05it/s]

[17074] Геокодируем адрес: Сестрорецк, Санкт-Петербург

Геокодирование:  85%|████████▌ | 17075/19990 [52:35<47:24,  1.02it/s]

[17075] Геокодируем адрес: Ветеранов пр-т 45, Санкт-Петербург

Геокодирование:  85%|████████▌ | 17076/19990 [52:36<50:12,  1.03s/it]

[17076] Геокодируем адрес: nan

Геокодирование:  85%|████████▌ | 17077/19990 [52:37<46:37,  1.04it/s]

[17077] Геокодируем адрес: nan

Геокодирование:  85%|████████▌ | 17078/19990 [52:38<47:12,  1.03it/s]

[17078] Геокодируем адрес: Антокольский пер, Санкт-Петербург

Геокодирование:  85%|████████▌ | 17079/19990 [52:39<47:58,  1.01it/s]

[17079] Геокодируем адрес: Благодатная ул 3, Санкт-Петербург

Геокодирование:  85%|████████▌ | 17080/19990 [52:40<48:57,  1.01s/it]

[17080] Геокодируем адрес: Академика Павлова ул 6к1, Санкт-Петербург

Геокодирование:  85%|████████▌ | 17081/19990 [52:41<49:26,  1.02s/it]

[17081] Геокодируем адрес: Лыжный пер 4, Санкт-Петербург

Геокодирование:  85%|████████▌ | 17082/19990 [52:42<49:23,  1.02s/it]

[17082] Геокодируем адрес: nan

Геокодирование:  85%|████████▌ | 17083/19990 [52:43<46:56,  1.03it/s]

[17083] Геокодируем адрес: Октябрьская наб, Санкт-Петербург

Геокодирование:  85%|████████▌ | 17084/19990 [52:44<47:44,  1.01it/s]

[17084] Геокодируем адрес: nan

Геокодирование:  85%|████████▌ | 17085/19990 [52:45<47:36,  1.02it/s]

[17085] Геокодируем адрес: Народная ул 60, Санкт-Петербург

Геокодирование:  85%|████████▌ | 17086/19990 [52:46<49:14,  1.02s/it]

[17086] Геокодируем адрес: Переведенская ул 4к1, Санкт-Петербург

Геокодирование:  85%|████████▌ | 17087/19990 [52:47<49:05,  1.01s/it]

[17087] Геокодируем адрес: Рябовское ш, Санкт-Петербург

Геокодирование:  85%|████████▌ | 17088/19990 [52:48<47:38,  1.02it/s]

[17088] Геокодируем адрес: nan

Геокодирование:  85%|████████▌ | 17089/19990 [52:49<47:27,  1.02it/s]

[17089] Геокодируем адрес: 1-й Муринский пр-т 17, Санкт-Петербург

RateLimiter caught an error, retrying (0/2 tries). Called with (*('1-й Муринский пр-т 17, Санкт-Петербург',), **{}).
Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connection.py", line 516, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1374, in getresponse
    response.begin()
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1278, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1134, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 367, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=1-%D0%B9+%D0%9C%D1%83%D1%80%D0%B8%D0%BD%D1%81%D0%BA%D0%B8%D0%B9+%D0%BF%D1%80-%D1%82+17%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 482, in _request
    resp = self.session.get(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=1-%D0%B9+%D0%9C%D1%83%D1%80%D0%B8%D0%BD%D1%81%D0%BA%D0%B8%D0%B9+%D0%BF%D1%80-%D1%82+17%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\extra\rate_limiter.py", line 136, in _retries_gen
    yield i  # Run the function.
    ^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\extra\rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\geocoders\nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\geocoders\base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 472, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 494, in _request
    raise GeocoderUnavailable(message)
geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=1-%D0%B9+%D0%9C%D1%83%D1%80%D0%B8%D0%BD%D1%81%D0%BA%D0%B8%D0%B9+%D0%BF%D1%80-%D1%82+17%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))
Геокодирование:  85%|████████▌ | 17090/19990 [52:59<2:55:19,  3.63s/it]

[17090] Геокодируем адрес: Реки Мойки наб 81, Санкт-Петербург

Геокодирование:  85%|████████▌ | 17091/19990 [53:00<2:12:57,  2.75s/it]

[17091] Геокодируем адрес: Восстановления ул, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17092/19990 [53:00<1:45:51,  2.19s/it]

[17092] Геокодируем адрес: Чапаева ул, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17093/19990 [53:02<1:29:59,  1.86s/it]

[17093] Геокодируем адрес: Реки Оккервиль наб 4к2Б, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17094/19990 [53:03<1:16:50,  1.59s/it]

[17094] Геокодируем адрес: nan

Геокодирование:  86%|████████▌ | 17095/19990 [53:03<1:07:07,  1.39s/it]

[17095] Геокодируем адрес: Нарвская ул 8к2, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17096/19990 [53:05<1:02:10,  1.29s/it]

[17096] Геокодируем адрес: Обводного канала наб 66, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17097/19990 [53:06<59:48,  1.24s/it]

[17097] Геокодируем адрес: Реки Оккервиль наб 4к2Б, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17098/19990 [53:07<55:10,  1.14s/it]

[17098] Геокодируем адрес: Белышева ул, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17099/19990 [53:08<52:16,  1.09s/it]

[17099] Геокодируем адрес: Пулковское ш 42к6ст1, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17100/19990 [53:08<50:17,  1.04s/it]

[17100] Геокодируем адрес: Народного Ополчения пр-т, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17101/19990 [53:11<1:07:45,  1.41s/it]

Автосохранение после 17100 строк...
[17101] Геокодируем адрес: Солидарности пр-т 13к2, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17102/19990 [53:12<59:06,  1.23s/it]

[17102] Геокодируем адрес: Гончарная ул 11а, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17103/19990 [53:13<56:22,  1.17s/it]

[17103] Геокодируем адрес: Ольги Берггольц ул, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17104/19990 [53:14<53:19,  1.11s/it]

[17104] Геокодируем адрес: Пилотов ул, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17105/19990 [53:15<51:29,  1.07s/it]

[17105] Геокодируем адрес: nan

Геокодирование:  86%|████████▌ | 17106/19990 [53:15<49:53,  1.04s/it]

[17106] Геокодируем адрес: Пражская ул, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17107/19990 [53:17<49:49,  1.04s/it]

[17107] Геокодируем адрес: Синопская наб 32/35, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17108/19990 [53:18<49:59,  1.04s/it]

[17108] Геокодируем адрес: nan

Геокодирование:  86%|████████▌ | 17109/19990 [53:18<48:06,  1.00s/it]

[17109] Геокодируем адрес: Елизарова пр-т 16, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17110/19990 [53:20<50:29,  1.05s/it]

[17110] Геокодируем адрес: Большая Пороховская ул 3б, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17111/19990 [53:21<49:11,  1.03s/it]

[17111] Геокодируем адрес: nan

Геокодирование:  86%|████████▌ | 17112/19990 [53:21<47:03,  1.02it/s]

[17112] Геокодируем адрес: nan

Геокодирование:  86%|████████▌ | 17113/19990 [53:22<47:30,  1.01it/s]

[17113] Геокодируем адрес: nan

Геокодирование:  86%|████████▌ | 17114/19990 [53:23<47:27,  1.01it/s]

[17114] Геокодируем адрес: Дачный пр-т 10/7, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17115/19990 [53:25<50:47,  1.06s/it]

[17115] Геокодируем адрес: Пулковский сад, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17116/19990 [53:26<47:18,  1.01it/s]

[17116] Геокодируем адрес: Брюсовская ул 6к2, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17117/19990 [53:27<47:27,  1.01it/s]

[17117] Геокодируем адрес: Шушары Изборская ул 1, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17118/19990 [53:28<48:03,  1.00s/it]

[17118] Геокодируем адрес: Авангардная ул 20, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17119/19990 [53:29<48:11,  1.01s/it]

[17119] Геокодируем адрес: Латышских стрелков ул 11, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17120/19990 [53:30<48:13,  1.01s/it]

[17120] Геокодируем адрес: Латышских стрелков ул 5, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17121/19990 [53:31<47:35,  1.00it/s]

[17121] Геокодируем адрес: nan

Геокодирование:  86%|████████▌ | 17122/19990 [53:32<46:59,  1.02it/s]

[17122] Геокодируем адрес: 1-й Муринский пр-т 3, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17123/19990 [53:34<1:08:47,  1.44s/it]

[17123] Геокодируем адрес: Ленинградская ул 14, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17124/19990 [53:35<58:09,  1.22s/it]

[17124] Геокодируем адрес: Чапаева ул, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17125/19990 [53:36<54:51,  1.15s/it]

[17125] Геокодируем адрес: Парголово Ленинградская ул 81, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17126/19990 [53:37<53:09,  1.11s/it]

[17126] Геокодируем адрес: Смоленская ул 10, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17127/19990 [53:38<51:45,  1.08s/it]

[17127] Геокодируем адрес: Приморский пр-т 52, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17128/19990 [53:39<51:25,  1.08s/it]

[17128] Геокодируем адрес: Ленинский пр-т 154к2, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17129/19990 [53:40<48:07,  1.01s/it]

[17129] Геокодируем адрес: Народная ул 1б, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17130/19990 [53:41<48:49,  1.02s/it]

[17130] Геокодируем адрес: Народного Ополчения пр-т 37, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17131/19990 [53:42<51:22,  1.08s/it]

Автосохранение после 17130 строк...
[17131] Геокодируем адрес: Народного Ополчения пр-т 35, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17132/19990 [53:43<49:25,  1.04s/it]

[17132] Геокодируем адрес: Народного Ополчения пр-т 37, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17133/19990 [53:45<1:01:16,  1.29s/it]

[17133] Геокодируем адрес: Авангардная ул 20, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17134/19990 [53:46<56:10,  1.18s/it]

[17134] Геокодируем адрес: Искровский пр-т, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17135/19990 [53:47<53:41,  1.13s/it]

[17135] Геокодируем адрес: nan

Геокодирование:  86%|████████▌ | 17136/19990 [53:48<50:44,  1.07s/it]

[17136] Геокодируем адрес: nan

Геокодирование:  86%|████████▌ | 17137/19990 [53:49<49:40,  1.04s/it]

[17137] Геокодируем адрес: Большевиков пр-т 2, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17138/19990 [53:50<52:16,  1.10s/it]

[17138] Геокодируем адрес: Народного Ополчения пр-т 35, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17139/19990 [53:51<50:23,  1.06s/it]

[17139] Геокодируем адрес: nan

Геокодирование:  86%|████████▌ | 17140/19990 [53:52<46:44,  1.02it/s]

[17140] Геокодируем адрес: nan

Геокодирование:  86%|████████▌ | 17141/19990 [53:53<46:54,  1.01it/s]

[17141] Геокодируем адрес: nan

Геокодирование:  86%|████████▌ | 17142/19990 [53:54<47:11,  1.01it/s]

[17142] Геокодируем адрес: Литовская ул 16Д, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17143/19990 [53:55<48:37,  1.02s/it]

[17143] Геокодируем адрес: nan

Геокодирование:  86%|████████▌ | 17144/19990 [53:56<46:44,  1.01it/s]

[17144] Геокодируем адрес: Тамбасова ул 8к1, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17145/19990 [53:57<47:44,  1.01s/it]

[17145] Геокодируем адрес: nan

Геокодирование:  86%|████████▌ | 17146/19990 [53:58<47:04,  1.01it/s]

[17146] Геокодируем адрес: Ириновский пр-т 41к2, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17147/19990 [53:59<47:20,  1.00it/s]

[17147] Геокодируем адрес: nan

Геокодирование:  86%|████████▌ | 17148/19990 [54:00<46:55,  1.01it/s]

[17148] Геокодируем адрес: Измаиловский б-р 4стр1, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17149/19990 [54:01<46:46,  1.01it/s]

[17149] Геокодируем адрес: nan

Геокодирование:  86%|████████▌ | 17150/19990 [54:02<47:15,  1.00it/s]

[17150] Геокодируем адрес: nan

Геокодирование:  86%|████████▌ | 17151/19990 [54:03<47:21,  1.00s/it]

[17151] Геокодируем адрес: nan

Геокодирование:  86%|████████▌ | 17152/19990 [54:04<47:08,  1.00it/s]

[17152] Геокодируем адрес: Наставников пр-т 45к5, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17153/19990 [54:05<47:47,  1.01s/it]

[17153] Геокодируем адрес: nan

Геокодирование:  86%|████████▌ | 17154/19990 [54:06<47:11,  1.00it/s]

[17154] Геокодируем адрес: nan

Геокодирование:  86%|████████▌ | 17155/19990 [54:07<47:03,  1.00it/s]

[17155] Геокодируем адрес: nan

Геокодирование:  86%|████████▌ | 17156/19990 [54:08<47:10,  1.00it/s]

[17156] Геокодируем адрес: nan

Геокодирование:  86%|████████▌ | 17157/19990 [54:09<47:12,  1.00it/s]

[17157] Геокодируем адрес: Маршала Жукова пр-т 34к1Д, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17158/19990 [54:10<46:54,  1.01it/s]

[17158] Геокодируем адрес: Лени Голикова ул 10, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17159/19990 [54:11<49:40,  1.05s/it]

[17159] Геокодируем адрес: Лени Голикова ул 25, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17160/19990 [54:12<47:56,  1.02s/it]

[17160] Геокодируем адрес: Московский пр-т 185, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17161/19990 [54:13<54:14,  1.15s/it]

Автосохранение после 17160 строк...
[17161] Геокодируем адрес: Московский пр-т 208к1, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17162/19990 [54:14<47:11,  1.00s/it]

[17162] Геокодируем адрес: Победы ул 21, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17163/19990 [54:15<50:34,  1.07s/it]

[17163] Геокодируем адрес: Стрельбищенская ул 24, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17164/19990 [54:16<45:33,  1.03it/s]

[17164] Геокодируем адрес: nan

Геокодирование:  86%|████████▌ | 17165/19990 [54:17<45:46,  1.03it/s]

[17165] Геокодируем адрес: Большевиков пр-т 30к1, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17166/19990 [54:18<47:27,  1.01s/it]

[17166] Геокодируем адрес: Бабушкина ул 115к5, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17167/19990 [54:19<46:51,  1.00it/s]

[17167] Геокодируем адрес: Бабушкина ул 115к5, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17168/19990 [54:20<46:49,  1.00it/s]

[17168] Геокодируем адрес: nan

Геокодирование:  86%|████████▌ | 17169/19990 [54:21<45:47,  1.03it/s]

[17169] Геокодируем адрес: Новоалександровская ул 62, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17170/19990 [54:22<46:46,  1.00it/s]

[17170] Геокодируем адрес: Новоалександровская ул 62, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17171/19990 [54:23<46:57,  1.00it/s]

[17171] Геокодируем адрес: nan

Геокодирование:  86%|████████▌ | 17172/19990 [54:24<46:12,  1.02it/s]

[17172] Геокодируем адрес: nan

Геокодирование:  86%|████████▌ | 17173/19990 [54:25<46:25,  1.01it/s]

[17173] Геокодируем адрес: Долгоозерная ул 12, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17174/19990 [54:26<48:00,  1.02s/it]

[17174] Геокодируем адрес: Лидии Зверевой ул 9к2, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17175/19990 [54:27<46:38,  1.01it/s]

[17175] Геокодируем адрес: Авиаконструкторов пр-т, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17176/19990 [54:28<47:44,  1.02s/it]

[17176] Геокодируем адрес: Королева пр-т 8, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17177/19990 [54:29<49:32,  1.06s/it]

[17177] Геокодируем адрес: nan

Геокодирование:  86%|████████▌ | 17178/19990 [54:30<45:09,  1.04it/s]

[17178] Геокодируем адрес: Новгородский пр-т, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17179/19990 [54:31<47:13,  1.01s/it]

[17179] Геокодируем адрес: Окуловская ул, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17180/19990 [54:32<45:46,  1.02it/s]

[17180] Геокодируем адрес: Вишерская ул 1к1, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17181/19990 [54:33<46:57,  1.00s/it]

[17181] Геокодируем адрес: nan

Геокодирование:  86%|████████▌ | 17182/19990 [54:34<45:45,  1.02it/s]

[17182] Геокодируем адрес: nan

Геокодирование:  86%|████████▌ | 17183/19990 [54:35<46:20,  1.01it/s]

[17183] Геокодируем адрес: nan

Геокодирование:  86%|████████▌ | 17184/19990 [54:36<46:09,  1.01it/s]

[17184] Геокодируем адрес: Просвещения пр-т 84к3, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17185/19990 [54:37<46:54,  1.00s/it]

[17185] Геокодируем адрес: Карпинского ул 38к7, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17186/19990 [54:38<47:33,  1.02s/it]

[17186] Геокодируем адрес: Просвещения пр-т 53к3, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17187/19990 [54:39<46:47,  1.00s/it]

[17187] Геокодируем адрес: 3-й Рабфаковский пер 5к1, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17188/19990 [54:40<47:00,  1.01s/it]

[17188] Геокодируем адрес: 1-я Алексеевская ул 27, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17189/19990 [54:41<46:40,  1.00it/s]

[17189] Геокодируем адрес: Сестрорецкая ул 6, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17190/19990 [54:42<46:38,  1.00it/s]

[17190] Геокодируем адрес: nan

Геокодирование:  86%|████████▌ | 17191/19990 [54:43<48:18,  1.04s/it]

Автосохранение после 17190 строк...
[17191] Геокодируем адрес: nan

Геокодирование:  86%|████████▌ | 17192/19990 [54:44<45:29,  1.03it/s]

[17192] Геокодируем адрес: Обуховской Обороны пр-т 19Д, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17193/19990 [54:45<47:33,  1.02s/it]

[17193] Геокодируем адрес: nan

Геокодирование:  86%|████████▌ | 17194/19990 [54:46<45:37,  1.02it/s]

[17194] Геокодируем адрес: nan

Геокодирование:  86%|████████▌ | 17195/19990 [54:47<45:44,  1.02it/s]

[17195] Геокодируем адрес: nan

Геокодирование:  86%|████████▌ | 17196/19990 [54:48<45:53,  1.01it/s]

[17196] Геокодируем адрес: nan

Геокодирование:  86%|████████▌ | 17197/19990 [54:49<46:01,  1.01it/s]

[17197] Геокодируем адрес: nan

Геокодирование:  86%|████████▌ | 17198/19990 [54:50<46:31,  1.00it/s]

[17198] Геокодируем адрес: Парковая ул 20к3, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17199/19990 [54:52<1:02:08,  1.34s/it]

[17199] Геокодируем адрес: Петергоф, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17200/19990 [54:53<56:08,  1.21s/it]

[17200] Геокодируем адрес: nan

Геокодирование:  86%|████████▌ | 17201/19990 [54:54<52:33,  1.13s/it]

[17201] Геокодируем адрес: Петергоф, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17202/19990 [54:55<51:12,  1.10s/it]

[17202] Геокодируем адрес: nan

Геокодирование:  86%|████████▌ | 17203/19990 [54:56<49:18,  1.06s/it]

[17203] Геокодируем адрес: nan

Геокодирование:  86%|████████▌ | 17204/19990 [54:57<48:59,  1.06s/it]

[17204] Геокодируем адрес: Малый пр-т, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17205/19990 [54:58<49:27,  1.07s/it]

[17205] Геокодируем адрес: Обуховской Обороны пр-т 35, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17206/19990 [54:59<48:59,  1.06s/it]

[17206] Геокодируем адрес: Металлострой, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17207/19990 [55:00<46:22,  1.00it/s]

[17207] Геокодируем адрес: Кубинская ул 28кв31, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17208/19990 [55:01<45:37,  1.02it/s]

[17208] Геокодируем адрес: Костюшко ул 88, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17209/19990 [55:02<47:17,  1.02s/it]

[17209] Геокодируем адрес: Старорусский пр-т, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17210/19990 [55:03<46:52,  1.01s/it]

[17210] Геокодируем адрес: nan

Геокодирование:  86%|████████▌ | 17211/19990 [55:04<45:34,  1.02it/s]

[17211] Геокодируем адрес: Шушары, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17212/19990 [55:05<46:32,  1.01s/it]

[17212] Геокодируем адрес: Заречная ул, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17213/19990 [55:06<48:04,  1.04s/it]

[17213] Геокодируем адрес: Старорусский пр-т 13к1, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17214/19990 [55:07<46:32,  1.01s/it]

[17214] Геокодируем адрес: Московское ш 286А, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17215/19990 [55:08<48:00,  1.04s/it]

[17215] Геокодируем адрес: nan

Геокодирование:  86%|████████▌ | 17216/19990 [55:09<44:29,  1.04it/s]

[17216] Геокодируем адрес: Бурцева ул 22, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17217/19990 [55:10<46:12,  1.00it/s]

[17217] Геокодируем адрес: Старорусский пр-т 13к1, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17218/19990 [55:11<46:25,  1.00s/it]

[17218] Геокодируем адрес: Дыбенко ул, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17219/19990 [55:12<45:17,  1.02it/s]

[17219] Геокодируем адрес: реки Мойки наб 48-50-52, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17220/19990 [55:13<47:32,  1.03s/it]

[17220] Геокодируем адрес: реки Мойки наб 1/8, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17221/19990 [55:14<48:51,  1.06s/it]

Автосохранение после 17220 строк...
[17221] Геокодируем адрес: Лени Голикова ул, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17222/19990 [55:15<44:32,  1.04it/s]

[17222] Геокодируем адрес: Лени Голикова ул, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17223/19990 [55:16<44:55,  1.03it/s]

[17223] Геокодируем адрес: Королева пр-т, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17224/19990 [55:17<46:22,  1.01s/it]

[17224] Геокодируем адрес: Большая Озерная ул, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17225/19990 [55:18<45:13,  1.02it/s]

[17225] Геокодируем адрес: Наличная ул, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17226/19990 [55:19<45:12,  1.02it/s]

[17226] Геокодируем адрес: Пестеля ул 2, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17227/19990 [55:20<46:04,  1.00s/it]

[17227] Геокодируем адрес: Седова ул, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17228/19990 [55:21<45:33,  1.01it/s]

[17228] Геокодируем адрес: Марка Галлая ул, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17229/19990 [55:22<46:20,  1.01s/it]

[17229] Геокодируем адрес: nan

Геокодирование:  86%|████████▌ | 17230/19990 [55:23<45:13,  1.02it/s]

[17230] Геокодируем адрес: Седова ул 101, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17231/19990 [55:24<47:53,  1.04s/it]

[17231] Геокодируем адрес: 2-я Жерновская ул, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17232/19990 [55:25<45:07,  1.02it/s]

[17232] Геокодируем адрес: 2-я Жерновская ул, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17233/19990 [55:26<45:35,  1.01it/s]

[17233] Геокодируем адрес: Моисеенко ул, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17234/19990 [55:27<45:27,  1.01it/s]

[17234] Геокодируем адрес: 6-я Жерновская ул, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17235/19990 [55:28<45:26,  1.01it/s]

[17235] Геокодируем адрес: Заусадебная ул, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17236/19990 [55:29<45:54,  1.00s/it]

[17236] Геокодируем адрес: Революции ш, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17237/19990 [55:30<46:49,  1.02s/it]

[17237] Геокодируем адрес: Зверинская ул, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17238/19990 [55:31<45:08,  1.02it/s]

[17238] Геокодируем адрес: Рощинское ш, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17239/19990 [55:32<45:25,  1.01it/s]

[17239] Геокодируем адрес: Оптиков ул, Санкт-Петербург

Геокодирование:  86%|████████▌ | 17240/19990 [55:33<45:35,  1.01it/s]

[17240] Геокодируем адрес: nan

Геокодирование:  86%|████████▌ | 17241/19990 [55:34<45:28,  1.01it/s]

[17241] Геокодируем адрес: nan

Геокодирование:  86%|████████▋ | 17242/19990 [55:35<45:22,  1.01it/s]

[17242] Геокодируем адрес: nan

Геокодирование:  86%|████████▋ | 17243/19990 [55:36<45:50,  1.00s/it]

[17243] Геокодируем адрес: Народного Ополчения пр-т 105, Санкт-Петербург

Геокодирование:  86%|████████▋ | 17244/19990 [55:37<47:58,  1.05s/it]

[17244] Геокодируем адрес: Стачек пр-т 90, Санкт-Петербург

Геокодирование:  86%|████████▋ | 17245/19990 [55:38<47:17,  1.03s/it]

[17245] Геокодируем адрес: nan

Геокодирование:  86%|████████▋ | 17246/19990 [55:39<44:14,  1.03it/s]

[17246] Геокодируем адрес: Есенина ул 36к1, Санкт-Петербург

Геокодирование:  86%|████████▋ | 17247/19990 [55:40<46:42,  1.02s/it]

[17247] Геокодируем адрес: Парголово Фёдора Абрамова ул 21к3, Санкт-Петербург

Геокодирование:  86%|████████▋ | 17248/19990 [55:41<46:08,  1.01s/it]

[17248] Геокодируем адрес: Стрельбищенская ул 10, Санкт-Петербург

Геокодирование:  86%|████████▋ | 17249/19990 [55:42<44:45,  1.02it/s]

[17249] Геокодируем адрес: Отважных ул 2к2, Санкт-Петербург

Геокодирование:  86%|████████▋ | 17250/19990 [55:43<45:21,  1.01it/s]

[17250] Геокодируем адрес: 5-я линия ВО 46, Санкт-Петербург

Геокодирование:  86%|████████▋ | 17251/19990 [55:47<1:23:28,  1.83s/it]

Автосохранение после 17250 строк...
[17251] Геокодируем адрес: Стрельбищенская ул 24, Санкт-Петербург

Геокодирование:  86%|████████▋ | 17252/19990 [55:47<1:07:01,  1.47s/it]

[17252] Геокодируем адрес: Красное Село Гатчинское ш 6к2, Санкт-Петербург

Геокодирование:  86%|████████▋ | 17253/19990 [55:48<1:03:58,  1.40s/it]

[17253] Геокодируем адрес: Новоалександровская ул 62, Санкт-Петербург

Геокодирование:  86%|████████▋ | 17254/19990 [55:49<54:46,  1.20s/it]

[17254] Геокодируем адрес: Авиаконструкторов пр-т, Санкт-Петербург

Геокодирование:  86%|████████▋ | 17255/19990 [55:50<52:50,  1.16s/it]

[17255] Геокодируем адрес: Парковая ул 20к2, Санкт-Петербург

Геокодирование:  86%|████████▋ | 17256/19990 [55:51<52:06,  1.14s/it]

[17256] Геокодируем адрес: Академика Лихачёва пл, Санкт-Петербург

Геокодирование:  86%|████████▋ | 17257/19990 [55:52<48:16,  1.06s/it]

[17257] Геокодируем адрес: Плесецкая ул, Санкт-Петербург

Геокодирование:  86%|████████▋ | 17258/19990 [55:53<46:47,  1.03s/it]

[17258] Геокодируем адрес: Конная ул 20к6, Санкт-Петербург

Геокодирование:  86%|████████▋ | 17259/19990 [55:54<46:44,  1.03s/it]

[17259] Геокодируем адрес: Рылеева ул 11Б, Санкт-Петербург

Геокодирование:  86%|████████▋ | 17260/19990 [55:55<47:32,  1.04s/it]

[17260] Геокодируем адрес: Моисеенко ул 8Б, Санкт-Петербург

Геокодирование:  86%|████████▋ | 17261/19990 [55:56<47:00,  1.03s/it]

[17261] Геокодируем адрес: Латышских Стрелков ул 11к1, Санкт-Петербург

Геокодирование:  86%|████████▋ | 17262/19990 [55:57<45:29,  1.00s/it]

[17262] Геокодируем адрес: nan

Геокодирование:  86%|████████▋ | 17263/19990 [55:58<44:47,  1.01it/s]

[17263] Геокодируем адрес: Энергетиков пр-т 9к3, Санкт-Петербург

Геокодирование:  86%|████████▋ | 17264/19990 [55:59<45:55,  1.01s/it]

[17264] Геокодируем адрес: Боровая ул 57, Санкт-Петербург

Геокодирование:  86%|████████▋ | 17265/19990 [56:00<45:31,  1.00s/it]

[17265] Геокодируем адрес: Решетникова ул 9, Санкт-Петербург

Геокодирование:  86%|████████▋ | 17266/19990 [56:01<45:44,  1.01s/it]

[17266] Геокодируем адрес: Трамвайный пр-т 1, Санкт-Петербург

Геокодирование:  86%|████████▋ | 17267/19990 [56:03<1:00:24,  1.33s/it]

[17267] Геокодируем адрес: Прогонная ул, Санкт-Петербург

Геокодирование:  86%|████████▋ | 17268/19990 [56:04<50:47,  1.12s/it]

[17268] Геокодируем адрес: Скороходовская ул, Санкт-Петербург

Геокодирование:  86%|████████▋ | 17269/19990 [56:05<49:23,  1.09s/it]

[17269] Геокодируем адрес: Красина ул, Санкт-Петербург

Геокодирование:  86%|████████▋ | 17270/19990 [56:06<49:02,  1.08s/it]

[17270] Геокодируем адрес: Сиреневый б-р 4к2, Санкт-Петербург

Геокодирование:  86%|████████▋ | 17271/19990 [56:07<53:13,  1.17s/it]

[17271] Геокодируем адрес: Лени Голикова ул 44, Санкт-Петербург

Геокодирование:  86%|████████▋ | 17272/19990 [56:10<1:08:54,  1.52s/it]

[17272] Геокодируем адрес: Солидарности пр-т 7к1, Санкт-Петербург

Геокодирование:  86%|████████▋ | 17273/19990 [56:13<1:35:23,  2.11s/it]

[17273] Геокодируем адрес: Петергоф Прогонная ул, Санкт-Петербург

Геокодирование:  86%|████████▋ | 17274/19990 [56:14<1:20:32,  1.78s/it]

[17274] Геокодируем адрес: Олеко Дундича ул 25к1, Санкт-Петербург

Геокодирование:  86%|████████▋ | 17275/19990 [56:15<1:10:08,  1.55s/it]

[17275] Геокодируем адрес: Подводника Кузьмина ул 56, Санкт-Петербург

Геокодирование:  86%|████████▋ | 17276/19990 [56:16<1:00:27,  1.34s/it]

[17276] Геокодируем адрес: nan

Геокодирование:  86%|████████▋ | 17277/19990 [56:17<52:25,  1.16s/it]

[17277] Геокодируем адрес: Малая Посадская ул, Санкт-Петербург

Геокодирование:  86%|████████▋ | 17278/19990 [56:19<1:04:53,  1.44s/it]

[17278] Геокодируем адрес: Парголово Николая Рубцова ул 9, Санкт-Петербург

Геокодирование:  86%|████████▋ | 17279/19990 [56:20<1:00:29,  1.34s/it]

[17279] Геокодируем адрес: Поварской пер 13, Санкт-Петербург

Геокодирование:  86%|████████▋ | 17280/19990 [56:21<54:37,  1.21s/it]

[17280] Геокодируем адрес: nan

Геокодирование:  86%|████████▋ | 17281/19990 [56:22<53:07,  1.18s/it]

Автосохранение после 17280 строк...
[17281] Геокодируем адрес: Энтузиастов пр-т 54к3, Санкт-Петербург

Геокодирование:  86%|████████▋ | 17282/19990 [56:23<50:04,  1.11s/it]

[17282] Геокодируем адрес: Энтузиастов пр-т 54к3, Санкт-Петербург

Геокодирование:  86%|████████▋ | 17283/19990 [56:24<47:35,  1.06s/it]

[17283] Геокодируем адрес: Костюшко ул, Санкт-Петербург

Геокодирование:  86%|████████▋ | 17284/19990 [56:25<47:22,  1.05s/it]

[17284] Геокодируем адрес: Комендантский пр-т 30к1, Санкт-Петербург

Геокодирование:  86%|████████▋ | 17285/19990 [56:26<47:55,  1.06s/it]

[17285] Геокодируем адрес: Колпино Ремизова ул, Санкт-Петербург

Геокодирование:  86%|████████▋ | 17286/19990 [56:27<45:28,  1.01s/it]

[17286] Геокодируем адрес: Союза Печатников ул 8, Санкт-Петербург

Геокодирование:  86%|████████▋ | 17287/19990 [56:28<46:20,  1.03s/it]

[17287] Геокодируем адрес: Киришская ул 5, Санкт-Петербург

Геокодирование:  86%|████████▋ | 17288/19990 [56:29<44:51,  1.00it/s]

[17288] Геокодируем адрес: 6-я Советская ул, Санкт-Петербург

Геокодирование:  86%|████████▋ | 17289/19990 [56:30<44:54,  1.00it/s]

[17289] Геокодируем адрес: Кронштадт Андреевкая ул 11, Санкт-Петербург

Геокодирование:  86%|████████▋ | 17290/19990 [56:31<45:26,  1.01s/it]

[17290] Геокодируем адрес: Парголово Заречная ул, Санкт-Петербург

Геокодирование:  86%|████████▋ | 17291/19990 [56:32<43:53,  1.03it/s]

[17291] Геокодируем адрес: Петергоф, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17292/19990 [56:33<44:34,  1.01it/s]

[17292] Геокодируем адрес: Гданьская ул 22, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17293/19990 [56:34<44:41,  1.01it/s]

[17293] Геокодируем адрес: 5-я линия ВО 52, Санкт-Петербург

RateLimiter caught an error, retrying (0/2 tries). Called with (*('5-я линия ВО 52, Санкт-Петербург',), **{}).
Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connection.py", line 516, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1374, in getresponse
    response.begin()
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1278, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1134, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 367, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=5-%D1%8F+%D0%BB%D0%B8%D0%BD%D0%B8%D1%8F+%D0%92%D0%9E+52%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 482, in _request
    resp = self.session.get(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=5-%D1%8F+%D0%BB%D0%B8%D0%BD%D0%B8%D1%8F+%D0%92%D0%9E+52%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\extra\rate_limiter.py", line 136, in _retries_gen
    yield i  # Run the function.
    ^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\extra\rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\geocoders\nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\geocoders\base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 472, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 494, in _request
    raise GeocoderUnavailable(message)
geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=5-%D1%8F+%D0%BB%D0%B8%D0%BD%D0%B8%D1%8F+%D0%92%D0%9E+52%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))
RateLimiter caught an error, retrying (1/2 tries). Called with (*('5-я линия ВО 52, Санкт-Петербург',), **{}).
Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connection.py", line 516, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1374, in getresponse
    response.begin()
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1278, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1134, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 367, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=5-%D1%8F+%D0%BB%D0%B8%D0%BD%D0%B8%D1%8F+%D0%92%D0%9E+52%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 482, in _request
    resp = self.session.get(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=5-%D1%8F+%D0%BB%D0%B8%D0%BD%D0%B8%D1%8F+%D0%92%D0%9E+52%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\extra\rate_limiter.py", line 136, in _retries_gen
    yield i  # Run the function.
    ^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\extra\rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\geocoders\nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\geocoders\base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 472, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 494, in _request
    raise GeocoderUnavailable(message)
geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=5-%D1%8F+%D0%BB%D0%B8%D0%BD%D0%B8%D1%8F+%D0%92%D0%9E+52%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))
RateLimiter swallowed an error after 2 retries. Called with (*('5-я линия ВО 52, Санкт-Петербург',), **{}).
Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connection.py", line 516, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1374, in getresponse
    response.begin()
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1278, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1134, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 367, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

[17294] Геокодируем адрес: Новая ул 51к8, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17295/19990 [56:55<3:49:12,  5.10s/it]

[17295] Геокодируем адрес: Рыбацкий пр-т 18к2, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17296/19990 [56:56<2:49:26,  3.77s/it]

[17296] Геокодируем адрес: Тамбасова ул 8к1, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17297/19990 [56:57<2:12:42,  2.96s/it]

[17297] Геокодируем адрес: Энергетиков пр-т 9к4, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17298/19990 [56:58<1:47:45,  2.40s/it]

[17298] Геокодируем адрес: nan

Геокодирование:  87%|████████▋ | 17299/19990 [56:59<1:25:41,  1.91s/it]

[17299] Геокодируем адрес: Максима Горького ул, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17300/19990 [57:00<1:15:38,  1.69s/it]

[17300] Геокодируем адрес: Рыбацкий пр-т 18к2, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17301/19990 [57:01<1:04:39,  1.44s/it]

[17301] Геокодируем адрес: Парашютная ул 4, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17302/19990 [57:02<1:02:32,  1.40s/it]

[17302] Геокодируем адрес: Исполкомская ул 16, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17303/19990 [57:03<53:56,  1.20s/it]

[17303] Геокодируем адрес: Белоостров Новое ш, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17304/19990 [57:04<51:02,  1.14s/it]

[17304] Геокодируем адрес: Исполкомская ул 16, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17305/19990 [57:06<1:02:49,  1.40s/it]

[17305] Геокодируем адрес: 2-я Советская ул, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17306/19990 [57:07<57:50,  1.29s/it]

[17306] Геокодируем адрес: Летчика Лихолетова ул, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17307/19990 [57:08<52:38,  1.18s/it]

[17307] Геокодируем адрес: nan

Геокодирование:  87%|████████▋ | 17308/19990 [57:09<49:57,  1.12s/it]

[17308] Геокодируем адрес: nan

Геокодирование:  87%|████████▋ | 17309/19990 [57:10<48:34,  1.09s/it]

[17309] Геокодируем адрес: Московский пр-т, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17310/19990 [57:11<49:46,  1.11s/it]

[17310] Геокодируем адрес: Московский пр-т, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17311/19990 [57:12<49:07,  1.10s/it]

Автосохранение после 17310 строк...
[17311] Геокодируем адрес: Сестрорецк Володарского ул 15, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17312/19990 [57:13<46:46,  1.05s/it]

[17312] Геокодируем адрес: Октябрьская наб, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17313/19990 [57:14<44:34,  1.00it/s]

[17313] Геокодируем адрес: Прибрежная ул 18, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17314/19990 [57:15<47:59,  1.08s/it]

[17314] Геокодируем адрес: Будапештская ул 88к3, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17315/19990 [57:17<57:52,  1.30s/it]

[17315] Геокодируем адрес: Пилотов ул 28, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17316/19990 [57:18<54:19,  1.22s/it]

[17316] Геокодируем адрес: Артиллерийская ул 12, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17317/19990 [57:20<1:04:04,  1.44s/it]

[17317] Геокодируем адрес: Пилотов ул 13, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17318/19990 [57:21<59:33,  1.34s/it]

[17318] Геокодируем адрес: Большая Московская ул 7, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17319/19990 [57:23<1:00:32,  1.36s/it]

[17319] Геокодируем адрес: Культуры пр-т 15, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17320/19990 [57:24<56:49,  1.28s/it]

[17320] Геокодируем адрес: Большевиков пр-т 30к1, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17321/19990 [57:25<50:54,  1.14s/it]

[17321] Геокодируем адрес: nan

Геокодирование:  87%|████████▋ | 17322/19990 [57:25<46:25,  1.04s/it]

[17322] Геокодируем адрес: Советский пр-т 39к1, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17323/19990 [57:26<46:15,  1.04s/it]

[17323] Геокодируем адрес: Мытнинская ул 15, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17324/19990 [57:27<45:49,  1.03s/it]

[17324] Геокодируем адрес: Сестрорецк, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17325/19990 [57:28<44:50,  1.01s/it]

[17325] Геокодируем адрес: nan

Геокодирование:  87%|████████▋ | 17326/19990 [57:29<44:04,  1.01it/s]

[17326] Геокодируем адрес: Оборонная ул 17/13, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17327/19990 [57:30<45:06,  1.02s/it]

[17327] Геокодируем адрес: Сестрорецк, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17328/19990 [57:31<44:19,  1.00it/s]

[17328] Геокодируем адрес: Достоевского ул 28В, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17329/19990 [57:32<46:03,  1.04s/it]

[17329] Геокодируем адрес: Маршала Жукова пр-т 66к1, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17330/19990 [57:34<47:32,  1.07s/it]

[17330] Геокодируем адрес: Суздальский пр-т, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17331/19990 [57:35<44:56,  1.01s/it]

[17331] Геокодируем адрес: Черняховского ул 15, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17332/19990 [57:36<46:39,  1.05s/it]

[17332] Геокодируем адрес: Будапештская ул 95к1, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17333/19990 [57:36<43:14,  1.02it/s]

[17333] Геокодируем адрес: Тореза пр-т 9, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17334/19990 [57:38<45:49,  1.04s/it]

[17334] Геокодируем адрес: Пушкин Госпитальный пер, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17335/19990 [57:38<42:12,  1.05it/s]

[17335] Геокодируем адрес: Димитрова ул 29к1, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17336/19990 [57:40<44:50,  1.01s/it]

[17336] Геокодируем адрес: Сиреневый б-р 4к2, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17337/19990 [57:41<44:31,  1.01s/it]

[17337] Геокодируем адрес: nan

Геокодирование:  87%|████████▋ | 17338/19990 [57:41<41:56,  1.05it/s]

[17338] Геокодируем адрес: Пилотов ул 13, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17339/19990 [57:42<44:06,  1.00it/s]

[17339] Геокодируем адрес: Генерала Кравченко ул 3к1, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17340/19990 [57:43<44:27,  1.01s/it]

[17340] Геокодируем адрес: Народная ул 68к1, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17341/19990 [57:45<45:41,  1.03s/it]

Автосохранение после 17340 строк...
[17341] Геокодируем адрес: Горелово Красная ул, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17342/19990 [57:45<42:01,  1.05it/s]

[17342] Геокодируем адрес: Пилотов ул 13, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17343/19990 [57:47<45:22,  1.03s/it]

[17343] Геокодируем адрес: nan

Геокодирование:  87%|████████▋ | 17344/19990 [57:47<41:55,  1.05it/s]

[17344] Геокодируем адрес: Пилотов ул 15к1, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17345/19990 [57:48<44:04,  1.00it/s]

[17345] Геокодируем адрес: Разъезжая ул 42/34, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17346/19990 [57:49<44:18,  1.01s/it]

[17346] Геокодируем адрес: Пилотов ул 21, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17347/19990 [57:50<43:59,  1.00it/s]

[17347] Геокодируем адрес: nan

Геокодирование:  87%|████████▋ | 17348/19990 [57:51<43:05,  1.02it/s]

[17348] Геокодируем адрес: Штурманская ул 28, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17349/19990 [57:52<44:42,  1.02s/it]

[17349] Геокодируем адрес: Штурманская ул 30, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17350/19990 [57:53<44:19,  1.01s/it]

[17350] Геокодируем адрес: Псковская ул 7, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17351/19990 [57:54<44:07,  1.00s/it]

[17351] Геокодируем адрес: nan

Геокодирование:  87%|████████▋ | 17352/19990 [57:55<43:41,  1.01it/s]

[17352] Геокодируем адрес: Энтузиастов пр-т 20к4, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17353/19990 [57:57<45:02,  1.02s/it]

[17353] Геокодируем адрес: Бабушкина ул 96, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17354/19990 [57:58<47:05,  1.07s/it]

[17354] Геокодируем адрес: Зои Космодемьянской ул 13, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17355/19990 [57:59<48:14,  1.10s/it]

[17355] Геокодируем адрес: Московское ш 177, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17356/19990 [58:00<51:54,  1.18s/it]

[17356] Геокодируем адрес: Невский пр-т 135, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17357/19990 [58:01<49:00,  1.12s/it]

[17357] Геокодируем адрес: Бабушкина ул 101к1, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17358/19990 [58:02<44:05,  1.01s/it]

[17358] Геокодируем адрес: 9-я Советская ул 39/24, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17359/19990 [58:03<44:42,  1.02s/it]

[17359] Геокодируем адрес: Белоостров Новое ш 6, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17360/19990 [58:04<46:10,  1.05s/it]

[17360] Геокодируем адрес: nan

Геокодирование:  87%|████████▋ | 17361/19990 [58:05<41:41,  1.05it/s]

[17361] Геокодируем адрес: nan

Геокодирование:  87%|████████▋ | 17362/19990 [58:06<42:07,  1.04it/s]

[17362] Геокодируем адрес: Пилотов ул 15, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17363/19990 [58:07<45:47,  1.05s/it]

[17363] Геокодируем адрес: nan

Геокодирование:  87%|████████▋ | 17364/19990 [58:08<42:11,  1.04it/s]

[17364] Геокодируем адрес: Шереметьевская ул 17, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17365/19990 [58:09<43:45,  1.00s/it]

[17365] Геокодируем адрес: nan

Геокодирование:  87%|████████▋ | 17366/19990 [58:10<42:39,  1.03it/s]

[17366] Геокодируем адрес: Льва Толстого ул 5Б, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17367/19990 [58:11<45:59,  1.05s/it]

[17367] Геокодируем адрес: nan

Геокодирование:  87%|████████▋ | 17368/19990 [58:12<42:28,  1.03it/s]

[17368] Геокодируем адрес: Перекупной пер 7Г, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17369/19990 [58:13<45:16,  1.04s/it]

[17369] Геокодируем адрес: Лесной пр-т 77, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17370/19990 [58:14<49:01,  1.12s/it]

[17370] Геокодируем адрес: Лесной пр-т 77, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17371/19990 [58:15<48:46,  1.12s/it]

Автосохранение после 17370 строк...
[17371] Геокодируем адрес: nan

Геокодирование:  87%|████████▋ | 17372/19990 [58:16<41:54,  1.04it/s]

[17372] Геокодируем адрес: Разъезжая ул 6, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17373/19990 [58:17<45:15,  1.04s/it]

[17373] Геокодируем адрес: Шушары Старорусский пр-т 13к1, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17374/19990 [58:18<45:10,  1.04s/it]

[17374] Геокодируем адрес: Большая Московская ул 7, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17375/19990 [58:19<44:50,  1.03s/it]

[17375] Геокодируем адрес: Ленинский пр-т 79к1, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17376/19990 [58:20<42:56,  1.01it/s]

[17376] Геокодируем адрес: nan

Геокодирование:  87%|████████▋ | 17377/19990 [58:21<41:13,  1.06it/s]

[17377] Геокодируем адрес: nan

Геокодирование:  87%|████████▋ | 17378/19990 [58:22<42:38,  1.02it/s]

[17378] Геокодируем адрес: Большой Васильевского острова пр-т, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17379/19990 [58:24<48:19,  1.11s/it]

[17379] Геокодируем адрес: Шаумяна пр-т, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17380/19990 [58:24<42:55,  1.01it/s]

[17380] Геокодируем адрес: Ленинский пр-т, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17381/19990 [58:25<45:41,  1.05s/it]

[17381] Геокодируем адрес: Маршала Казакова ул, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17382/19990 [58:26<43:19,  1.00it/s]

[17382] Геокодируем адрес: Шушары, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17383/19990 [58:27<41:39,  1.04it/s]

[17383] Геокодируем адрес: Ярослава Гашека ул, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17384/19990 [58:28<42:05,  1.03it/s]

[17384] Геокодируем адрес: Советский пр-т, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17385/19990 [58:29<45:17,  1.04s/it]

[17385] Геокодируем адрес: nan

Геокодирование:  87%|████████▋ | 17386/19990 [58:30<41:17,  1.05it/s]

[17386] Геокодируем адрес: Костюшко ул, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17387/19990 [58:31<43:57,  1.01s/it]

[17387] Геокодируем адрес: Костюшко ул 64, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17388/19990 [58:34<1:01:38,  1.42s/it]

[17388] Геокодируем адрес: Костюшко ул 64, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17389/19990 [58:35<59:09,  1.36s/it]

[17389] Геокодируем адрес: Костюшко ул 64, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17390/19990 [58:36<52:03,  1.20s/it]

[17390] Геокодируем адрес: nan

Геокодирование:  87%|████████▋ | 17391/19990 [58:37<46:42,  1.08s/it]

[17391] Геокодируем адрес: Верхняя ул, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17392/19990 [58:38<49:06,  1.13s/it]

[17392] Геокодируем адрес: nan

Геокодирование:  87%|████████▋ | 17393/19990 [58:39<45:09,  1.04s/it]

[17393] Геокодируем адрес: nan

Геокодирование:  87%|████████▋ | 17394/19990 [58:39<43:16,  1.00s/it]

[17394] Геокодируем адрес: Обуховской Обороны пр-т 35Б, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17395/19990 [58:42<1:02:08,  1.44s/it]

[17395] Геокодируем адрес: Кронштадтская пл, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17396/19990 [58:43<51:34,  1.19s/it]

[17396] Геокодируем адрес: nan

Геокодирование:  87%|████████▋ | 17397/19990 [58:44<48:38,  1.13s/it]

[17397] Геокодируем адрес: Аэродромная ул, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17398/19990 [58:45<47:23,  1.10s/it]

[17398] Геокодируем адрес: Новоколомяжский пр-т 13, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17399/19990 [58:46<49:35,  1.15s/it]

[17399] Геокодируем адрес: nan

Геокодирование:  87%|████████▋ | 17400/19990 [58:47<43:34,  1.01s/it]

[17400] Геокодируем адрес: Петербургское ш, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17401/19990 [58:48<46:35,  1.08s/it]

Автосохранение после 17400 строк...
[17401] Геокодируем адрес: nan

Геокодирование:  87%|████████▋ | 17402/19990 [58:49<42:29,  1.02it/s]

[17402] Геокодируем адрес: Медвежий пер 2/5, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17403/19990 [58:50<43:53,  1.02s/it]

[17403] Геокодируем адрес: nan

Геокодирование:  87%|████████▋ | 17404/19990 [58:51<42:46,  1.01it/s]

[17404] Геокодируем адрес: nan

Геокодирование:  87%|████████▋ | 17405/19990 [58:52<42:20,  1.02it/s]

[17405] Геокодируем адрес: nan

Геокодирование:  87%|████████▋ | 17406/19990 [58:53<42:46,  1.01it/s]

[17406] Геокодируем адрес: Бухарестская ул, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17407/19990 [58:54<43:51,  1.02s/it]

[17407] Геокодируем адрес: Английский пр-т 25, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17408/19990 [58:55<47:01,  1.09s/it]

[17408] Геокодируем адрес: nan

Геокодирование:  87%|████████▋ | 17409/19990 [58:56<41:32,  1.04it/s]

[17409] Геокодируем адрес: Люблинский пер 4, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17410/19990 [58:57<43:10,  1.00s/it]

[17410] Геокодируем адрес: Садовая ул 101, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17411/19990 [58:59<1:03:36,  1.48s/it]

[17411] Геокодируем адрес: Люблинский пер 4, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17412/19990 [59:00<53:36,  1.25s/it]

[17412] Геокодируем адрес: nan

Геокодирование:  87%|████████▋ | 17413/19990 [59:01<49:39,  1.16s/it]

[17413] Геокодируем адрес: nan

Геокодирование:  87%|████████▋ | 17414/19990 [59:02<48:32,  1.13s/it]

[17414] Геокодируем адрес: Ириновский пр-т 25, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17415/19990 [59:03<50:29,  1.18s/it]

[17415] Геокодируем адрес: nan

Геокодирование:  87%|████████▋ | 17416/19990 [59:04<43:29,  1.01s/it]

[17416] Геокодируем адрес: nan

Геокодирование:  87%|████████▋ | 17417/19990 [59:05<42:41,  1.00it/s]

[17417] Геокодируем адрес: Кантемировская ул 10, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17418/19990 [59:06<46:33,  1.09s/it]

[17418] Геокодируем адрес: nan

Геокодирование:  87%|████████▋ | 17419/19990 [59:07<42:59,  1.00s/it]

[17419] Геокодируем адрес: nan

Геокодирование:  87%|████████▋ | 17420/19990 [59:08<43:29,  1.02s/it]

[17420] Геокодируем адрес: реки Мойки наб 81, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17421/19990 [59:12<1:17:11,  1.80s/it]

[17421] Геокодируем адрес: nan

Геокодирование:  87%|████████▋ | 17422/19990 [59:13<1:06:44,  1.56s/it]

[17422] Геокодируем адрес: Ленинский пр-т 132, Санкт-Петербург

RateLimiter caught an error, retrying (0/2 tries). Called with (*('Ленинский пр-т 132, Санкт-Петербург',), **{}).
Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connection.py", line 516, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1374, in getresponse
    response.begin()
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1278, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1134, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 367, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=%D0%9B%D0%B5%D0%BD%D0%B8%D0%BD%D1%81%D0%BA%D0%B8%D0%B9+%D0%BF%D1%80-%D1%82+132%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 482, in _request
    resp = self.session.get(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=%D0%9B%D0%B5%D0%BD%D0%B8%D0%BD%D1%81%D0%BA%D0%B8%D0%B9+%D0%BF%D1%80-%D1%82+132%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\extra\rate_limiter.py", line 136, in _retries_gen
    yield i  # Run the function.
    ^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\extra\rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\geocoders\nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\geocoders\base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 472, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 494, in _request
    raise GeocoderUnavailable(message)
geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=%D0%9B%D0%B5%D0%BD%D0%B8%D0%BD%D1%81%D0%BA%D0%B8%D0%B9+%D0%BF%D1%80-%D1%82+132%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))
Геокодирование:  87%|████████▋ | 17423/19990 [59:22<2:50:28,  3.98s/it]

[17423] Геокодируем адрес: Ленинский пр-т 134, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17424/19990 [59:23<2:13:29,  3.12s/it]

[17424] Геокодируем адрес: Автовская ул 30, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17425/19990 [59:24<1:42:45,  2.40s/it]

[17425] Геокодируем адрес: Васи Алексеева ул 23, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17426/19990 [59:25<1:26:32,  2.03s/it]

[17426] Геокодируем адрес: Колпино Павловская ул, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17427/19990 [59:26<1:10:54,  1.66s/it]

[17427] Геокодируем адрес: Винновская наб, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17428/19990 [59:28<1:15:26,  1.77s/it]

[17428] Геокодируем адрес: Ленинский пр-т 130/6, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17429/19990 [59:30<1:12:07,  1.69s/it]

[17429] Геокодируем адрес: Энтузиастов пр-т, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17430/19990 [59:30<1:01:01,  1.43s/it]

[17430] Геокодируем адрес: Димитрова ул 4-1, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17431/19990 [59:32<1:00:17,  1.41s/it]

Автосохранение после 17430 строк...
[17431] Геокодируем адрес: nan

Геокодирование:  87%|████████▋ | 17432/19990 [59:32<50:09,  1.18s/it]

[17432] Геокодируем адрес: nan

Геокодирование:  87%|████████▋ | 17433/19990 [59:33<47:50,  1.12s/it]

[17433] Геокодируем адрес: Энгельса пр-т, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17434/19990 [59:35<49:37,  1.17s/it]

[17434] Геокодируем адрес: Фурштатская ул 28, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17435/19990 [59:35<44:29,  1.04s/it]

[17435] Геокодируем адрес: Парголово, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17436/19990 [59:36<43:59,  1.03s/it]

[17436] Геокодируем адрес: Красногородская ул 19к3, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17437/19990 [59:37<43:59,  1.03s/it]

[17437] Геокодируем адрес: Кравченко ул 3к1стр1, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17438/19990 [59:38<41:48,  1.02it/s]

[17438] Геокодируем адрес: Лени Голикова ул 6к2, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17439/19990 [59:40<44:25,  1.04s/it]

[17439] Геокодируем адрес: Генерала Кравченко ул 3к1, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17440/19990 [59:41<45:24,  1.07s/it]

[17440] Геокодируем адрес: Маринеско ул 1, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17441/19990 [59:42<42:51,  1.01s/it]

[17441] Геокодируем адрес: Просвещения пр-т, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17442/19990 [59:43<44:33,  1.05s/it]

[17442] Геокодируем адрес: Северный пр-д, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17443/19990 [59:44<48:01,  1.13s/it]

[17443] Геокодируем адрес: Верхняя ул, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17444/19990 [59:45<42:27,  1.00s/it]

[17444] Геокодируем адрес: Колокольная ул, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17445/19990 [59:46<41:52,  1.01it/s]

[17445] Геокодируем адрес: Купчинская ул, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17446/19990 [59:47<42:16,  1.00it/s]

[17446] Геокодируем адрес: Инструментальная ул, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17447/19990 [59:48<42:35,  1.00s/it]

[17447] Геокодируем адрес: nan

Геокодирование:  87%|████████▋ | 17448/19990 [59:49<41:38,  1.02it/s]

[17448] Геокодируем адрес: Северный пр-т 89к4, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17449/19990 [59:50<43:31,  1.03s/it]

[17449] Геокодируем адрес: Фёдора Абрамова ул 8, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17450/19990 [59:51<44:15,  1.05s/it]

[17450] Геокодируем адрес: nan

Геокодирование:  87%|████████▋ | 17451/19990 [59:52<40:32,  1.04it/s]

[17451] Геокодируем адрес: nan

Геокодирование:  87%|████████▋ | 17452/19990 [59:53<40:57,  1.03it/s]

[17452] Геокодируем адрес: nan

Геокодирование:  87%|████████▋ | 17453/19990 [59:54<41:56,  1.01it/s]

[17453] Геокодируем адрес: Каховского пер, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17454/19990 [59:55<43:48,  1.04s/it]

[17454] Геокодируем адрес: Бухарестская ул, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17455/19990 [59:56<41:32,  1.02it/s]

[17455] Геокодируем адрес: Зольная ул, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17456/19990 [59:57<41:40,  1.01it/s]

[17456] Геокодируем адрес: Дунайский пр-т 58, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17457/19990 [59:58<46:24,  1.10s/it]

[17457] Геокодируем адрес: Купчинская ул 11к1, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17458/19990 [59:59<43:15,  1.02s/it]

[17458] Геокодируем адрес: nan

Геокодирование:  87%|████████▋ | 17459/19990 [1:00:00<39:42,  1.06it/s]

[17459] Геокодируем адрес: nan

Геокодирование:  87%|████████▋ | 17460/19990 [1:00:01<40:29,  1.04it/s]

[17460] Геокодируем адрес: nan

Геокодирование:  87%|████████▋ | 17461/19990 [1:00:02<42:55,  1.02s/it]

Автосохранение после 17460 строк...
[17461] Геокодируем адрес: Зайцева ул 29, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17462/19990 [1:00:03<44:39,  1.06s/it]

[17462] Геокодируем адрес: Дачный пр-т 16к3, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17463/19990 [1:00:04<41:19,  1.02it/s]

[17463] Геокодируем адрес: Ветеранов пр-т 1к1, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17464/19990 [1:00:05<43:14,  1.03s/it]

[17464] Геокодируем адрес: Ветеранов пр-т 1к1, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17465/19990 [1:00:06<41:55,  1.00it/s]

[17465] Геокодируем адрес: Малая Балканская ул 14к1Б, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17466/19990 [1:00:07<41:03,  1.02it/s]

[17466] Геокодируем адрес: Славы пр-т 37, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17467/19990 [1:00:08<44:31,  1.06s/it]

[17467] Геокодируем адрес: Большой Сампсониевский пр-т 83, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17468/19990 [1:00:09<43:45,  1.04s/it]

[17468] Геокодируем адрес: Лесной пр-т 32, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17469/19990 [1:00:10<45:57,  1.09s/it]

[17469] Геокодируем адрес: Шостаковича ул 5к1, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17470/19990 [1:00:11<48:23,  1.15s/it]

[17470] Геокодируем адрес: Белы Куна ул 6к1, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17471/19990 [1:00:12<45:51,  1.09s/it]

[17471] Геокодируем адрес: Обуховской обороны пр-т 140, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17472/19990 [1:00:13<45:09,  1.08s/it]

[17472] Геокодируем адрес: Мытнинская ул 9, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17473/19990 [1:00:14<39:58,  1.05it/s]

[17473] Геокодируем адрес: Большая Московская ул 13, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17474/19990 [1:00:15<42:25,  1.01s/it]

[17474] Геокодируем адрес: nan

Геокодирование:  87%|████████▋ | 17475/19990 [1:00:16<39:34,  1.06it/s]

[17475] Геокодируем адрес: Кронштадт Кронштадтская ул 1/66, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17476/19990 [1:00:20<1:11:47,  1.71s/it]

[17476] Геокодируем адрес: Ударников пр-т 22к1, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17477/19990 [1:00:20<58:49,  1.40s/it]

[17477] Геокодируем адрес: Конная ул 5/3, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17478/19990 [1:00:21<53:34,  1.28s/it]

[17478] Геокодируем адрес: 1-й Инженерный мост, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17479/19990 [1:00:22<49:30,  1.18s/it]

[17479] Геокодируем адрес: Советский пр-т, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17480/19990 [1:00:23<50:44,  1.21s/it]

[17480] Геокодируем адрес: Королева пр-т, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17481/19990 [1:00:24<46:56,  1.12s/it]

[17481] Геокодируем адрес: Красное Село 1-го Мая ул, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17482/19990 [1:00:26<48:20,  1.16s/it]

[17482] Геокодируем адрес: Боковая ал, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17483/19990 [1:00:27<51:29,  1.23s/it]

[17483] Геокодируем адрес: Колпино, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17484/19990 [1:00:28<44:05,  1.06s/it]

[17484] Геокодируем адрес: Конная ул 5/3, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17485/19990 [1:00:29<44:06,  1.06s/it]

[17485] Геокодируем адрес: Среднерогатская ул, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17486/19990 [1:00:30<42:11,  1.01s/it]

[17486] Геокодируем адрес: тимуровская ул 15к1, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17487/19990 [1:00:31<43:41,  1.05s/it]

[17487] Геокодируем адрес: nan

Геокодирование:  87%|████████▋ | 17488/19990 [1:00:32<41:04,  1.02it/s]

[17488] Геокодируем адрес: Планерная ул 21к1, Санкт-Петербург

Геокодирование:  87%|████████▋ | 17489/19990 [1:00:33<42:53,  1.03s/it]

[17489] Геокодируем адрес: nan

Геокодирование:  87%|████████▋ | 17490/19990 [1:00:34<41:02,  1.02it/s]

[17490] Геокодируем адрес: nan

Геокодирование:  87%|████████▋ | 17491/19990 [1:00:35<43:31,  1.05s/it]

Автосохранение после 17490 строк...
[17491] Геокодируем адрес: nan

Геокодирование:  88%|████████▊ | 17492/19990 [1:00:36<40:29,  1.03it/s]

[17492] Геокодируем адрес: nan

Геокодирование:  88%|████████▊ | 17493/19990 [1:00:37<41:41,  1.00s/it]

[17493] Геокодируем адрес: Стасовой ул 6, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17494/19990 [1:00:38<42:38,  1.03s/it]

[17494] Геокодируем адрес: Куйбышева ул 8, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17495/19990 [1:00:39<46:14,  1.11s/it]

[17495] Геокодируем адрес: Светлановский пр-т 115к2, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17496/19990 [1:00:40<42:38,  1.03s/it]

[17496] Геокодируем адрес: Турку ул 9к5, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17497/19990 [1:00:41<40:54,  1.02it/s]

[17497] Геокодируем адрес: Школьная ул, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17498/19990 [1:00:42<44:27,  1.07s/it]

[17498] Геокодируем адрес: земледельческая ул 5, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17499/19990 [1:00:43<39:56,  1.04it/s]

[17499] Геокодируем адрес: nan

Геокодирование:  88%|████████▊ | 17500/19990 [1:00:44<39:10,  1.06it/s]

[17500] Геокодируем адрес: Руставели ул, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17501/19990 [1:00:45<41:59,  1.01s/it]

[17501] Геокодируем адрес: Кирочная ул, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17502/19990 [1:00:46<40:02,  1.04it/s]

[17502] Геокодируем адрес: nan

Геокодирование:  88%|████████▊ | 17503/19990 [1:00:47<40:35,  1.02it/s]

[17503] Геокодируем адрес: Славы пр-т, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17504/19990 [1:00:48<43:35,  1.05s/it]

[17504] Геокодируем адрес: Красное Село Первого Мая ул, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17505/19990 [1:00:49<42:07,  1.02s/it]

[17505] Геокодируем адрес: Большевиков пр-т, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17506/19990 [1:00:51<53:58,  1.30s/it]

[17506] Геокодируем адрес: nan

Геокодирование:  88%|████████▊ | 17507/19990 [1:00:52<49:27,  1.20s/it]

[17507] Геокодируем адрес: nan

Геокодирование:  88%|████████▊ | 17508/19990 [1:00:53<46:36,  1.13s/it]

[17508] Геокодируем адрес: nan

Геокодирование:  88%|████████▊ | 17509/19990 [1:00:54<45:14,  1.09s/it]

[17509] Геокодируем адрес: Турку ул, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17510/19990 [1:00:55<44:16,  1.07s/it]

[17510] Геокодируем адрес: Софийская ул, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17511/19990 [1:00:56<44:02,  1.07s/it]

[17511] Геокодируем адрес: Ушинского ул 9к1, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17512/19990 [1:00:57<42:47,  1.04s/it]

[17512] Геокодируем адрес: Партизана Германа ул 22к2, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17513/19990 [1:00:58<42:22,  1.03s/it]

[17513] Геокодируем адрес: Каменноостровский пр-т 2, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17514/19990 [1:00:59<43:37,  1.06s/it]

[17514] Геокодируем адрес: nan

Геокодирование:  88%|████████▊ | 17515/19990 [1:01:00<39:38,  1.04it/s]

[17515] Геокодируем адрес: nan

Геокодирование:  88%|████████▊ | 17516/19990 [1:01:01<40:32,  1.02it/s]

[17516] Геокодируем адрес: реки Мойки наб, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17517/19990 [1:01:02<41:16,  1.00s/it]

[17517] Геокодируем адрес: nan

Геокодирование:  88%|████████▊ | 17518/19990 [1:01:03<40:59,  1.01it/s]

[17518] Геокодируем адрес: nan

Геокодирование:  88%|████████▊ | 17519/19990 [1:01:04<41:05,  1.00it/s]

[17519] Геокодируем адрес: nan

Геокодирование:  88%|████████▊ | 17520/19990 [1:01:05<43:59,  1.07s/it]

[17520] Геокодируем адрес: Королева пр-т 46к2, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17521/19990 [1:01:06<43:30,  1.06s/it]

Автосохранение после 17520 строк...
[17521] Геокодируем адрес: Невский пр-т 154, Санкт-Петербург

RateLimiter caught an error, retrying (0/2 tries). Called with (*('Невский пр-т 154, Санкт-Петербург',), **{}).
Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connection.py", line 516, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1374, in getresponse
    response.begin()
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1278, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1134, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 367, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=%D0%9D%D0%B5%D0%B2%D1%81%D0%BA%D0%B8%D0%B9+%D0%BF%D1%80-%D1%82+154%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 482, in _request
    resp = self.session.get(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=%D0%9D%D0%B5%D0%B2%D1%81%D0%BA%D0%B8%D0%B9+%D0%BF%D1%80-%D1%82+154%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\extra\rate_limiter.py", line 136, in _retries_gen
    yield i  # Run the function.
    ^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\extra\rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\geocoders\nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\geocoders\base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 472, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 494, in _request
    raise GeocoderUnavailable(message)
geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=%D0%9D%D0%B5%D0%B2%D1%81%D0%BA%D0%B8%D0%B9+%D0%BF%D1%80-%D1%82+154%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))
Геокодирование:  88%|████████▊ | 17522/19990 [1:01:15<2:22:25,  3.46s/it]

[17522] Геокодируем адрес: Красных Зорь б-р 24, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17523/19990 [1:01:16<1:50:37,  2.69s/it]

[17523] Геокодируем адрес: Шушары, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17524/19990 [1:01:17<1:29:18,  2.17s/it]

[17524] Геокодируем адрес: Советский пр-т 39к1, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17525/19990 [1:01:18<1:15:31,  1.84s/it]

[17525] Геокодируем адрес: Ординарная ул 5, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17526/19990 [1:01:19<1:04:33,  1.57s/it]

[17526] Геокодируем адрес: марата ул 14, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17527/19990 [1:01:20<58:21,  1.42s/it]

[17527] Геокодируем адрес: марата ул 14, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17528/19990 [1:01:21<53:14,  1.30s/it]

[17528] Геокодируем адрес: марата ул 14, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17529/19990 [1:01:22<50:03,  1.22s/it]

[17529] Геокодируем адрес: сердобольская ул, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17530/19990 [1:01:23<45:16,  1.10s/it]

[17530] Геокодируем адрес: nan

Геокодирование:  88%|████████▊ | 17531/19990 [1:01:24<43:52,  1.07s/it]

[17531] Геокодируем адрес: nan

Геокодирование:  88%|████████▊ | 17532/19990 [1:01:25<43:03,  1.05s/it]

[17532] Геокодируем адрес: Фёдора Абрамова ул 4, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17533/19990 [1:01:26<44:22,  1.08s/it]

[17533] Геокодируем адрес: nan

Геокодирование:  88%|████████▊ | 17534/19990 [1:01:27<41:06,  1.00s/it]

[17534] Геокодируем адрес: nan

Геокодирование:  88%|████████▊ | 17535/19990 [1:01:28<41:07,  1.01s/it]

[17535] Геокодируем адрес: Загородный пр-т 6, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17536/19990 [1:01:29<43:34,  1.07s/it]

[17536] Геокодируем адрес: nan

Геокодирование:  88%|████████▊ | 17537/19990 [1:01:30<41:08,  1.01s/it]

[17537] Геокодируем адрес: nan

Геокодирование:  88%|████████▊ | 17538/19990 [1:01:31<40:06,  1.02it/s]

[17538] Геокодируем адрес: Солдата Корзуна ул 58к2, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17539/19990 [1:01:32<40:41,  1.00it/s]

[17539] Геокодируем адрес: Дачный пр-т 32, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17540/19990 [1:01:33<43:08,  1.06s/it]

[17540] Геокодируем адрес: Народного ополчения пр-т 145, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17541/19990 [1:01:34<42:35,  1.04s/it]

[17541] Геокодируем адрес: Конная ул 5к3, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17542/19990 [1:01:35<40:01,  1.02it/s]

[17542] Геокодируем адрес: Пушкинская ул 8, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17543/19990 [1:01:36<40:15,  1.01it/s]

[17543] Геокодируем адрес: Шушары Вишерская ул 22, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17544/19990 [1:01:37<41:16,  1.01s/it]

[17544] Геокодируем адрес: nan

Геокодирование:  88%|████████▊ | 17545/19990 [1:01:38<39:14,  1.04it/s]

[17545] Геокодируем адрес: nan

Геокодирование:  88%|████████▊ | 17546/19990 [1:01:39<39:46,  1.02it/s]

[17546] Геокодируем адрес: nan

Геокодирование:  88%|████████▊ | 17547/19990 [1:01:40<39:58,  1.02it/s]

[17547] Геокодируем адрес: nan

Геокодирование:  88%|████████▊ | 17548/19990 [1:01:41<40:48,  1.00s/it]

[17548] Геокодируем адрес: nan

Геокодирование:  88%|████████▊ | 17549/19990 [1:01:42<40:12,  1.01it/s]

[17549] Геокодируем адрес: nan

Геокодирование:  88%|████████▊ | 17550/19990 [1:01:43<40:16,  1.01it/s]

[17550] Геокодируем адрес: Понтонный Южная ул 27, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17551/19990 [1:01:44<43:27,  1.07s/it]

Автосохранение после 17550 строк...
[17551] Геокодируем адрес: Стойкости ул 31, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17552/19990 [1:01:45<40:45,  1.00s/it]

[17552] Геокодируем адрес: nan

Геокодирование:  88%|████████▊ | 17553/19990 [1:01:46<39:43,  1.02it/s]

[17553] Геокодируем адрес: Индустриальный пр-т, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17554/19990 [1:01:47<41:51,  1.03s/it]

[17554] Геокодируем адрес: Пушкарский пер 7, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17555/19990 [1:01:48<39:49,  1.02it/s]

[17555] Геокодируем адрес: Советский пр-т 39к1, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17556/19990 [1:01:49<40:43,  1.00s/it]

[17556] Геокодируем адрес: Некрасова ул 40, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17557/19990 [1:01:50<42:55,  1.06s/it]

[17557] Геокодируем адрес: nan

Геокодирование:  88%|████████▊ | 17558/19990 [1:01:51<38:55,  1.04it/s]

[17558] Геокодируем адрес: Пулковская ул 19, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17559/19990 [1:01:52<40:18,  1.00it/s]

[17559] Геокодируем адрес: Школьная ул 15, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17560/19990 [1:01:53<43:55,  1.08s/it]

[17560] Геокодируем адрес: Большевиков пр-т, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17561/19990 [1:01:54<39:37,  1.02it/s]

[17561] Геокодируем адрес: nan

Геокодирование:  88%|████████▊ | 17562/19990 [1:01:55<38:31,  1.05it/s]

[17562] Геокодируем адрес: Полтавская ул 12, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17563/19990 [1:01:56<40:23,  1.00it/s]

[17563] Геокодируем адрес: Конная ул 5к3, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17564/19990 [1:01:57<40:13,  1.01it/s]

[17564] Геокодируем адрес: Возрождения ул 27, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17565/19990 [1:01:58<40:40,  1.01s/it]

[17565] Геокодируем адрес: Красина ул, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17566/19990 [1:01:59<39:32,  1.02it/s]

[17566] Геокодируем адрес: nan

Геокодирование:  88%|████████▊ | 17567/19990 [1:02:00<39:20,  1.03it/s]

[17567] Геокодируем адрес: Подводника Кузьмина ул 14, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17568/19990 [1:02:01<40:19,  1.00it/s]

[17568] Геокодируем адрес: Московский пр-т 73к5, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17569/19990 [1:02:02<41:21,  1.02s/it]

[17569] Геокодируем адрес: Рыбацкий пр-т 29к1, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17570/19990 [1:02:03<39:56,  1.01it/s]

[17570] Геокодируем адрес: Коллонтай ул 21к4, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17571/19990 [1:02:04<40:51,  1.01s/it]

[17571] Геокодируем адрес: Новосмоленская наб 1Е, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17572/19990 [1:02:05<40:00,  1.01it/s]

[17572] Геокодируем адрес: Карельский пер, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17573/19990 [1:02:06<39:27,  1.02it/s]

[17573] Геокодируем адрес: Львовская ул, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17574/19990 [1:02:07<39:40,  1.01it/s]

[17574] Геокодируем адрес: Матисова канала наб, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17575/19990 [1:02:08<40:01,  1.01it/s]

[17575] Геокодируем адрес: nan

Геокодирование:  88%|████████▊ | 17576/19990 [1:02:09<39:43,  1.01it/s]

[17576] Геокодируем адрес: Краснофлотский пер, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17577/19990 [1:02:10<40:15,  1.00s/it]

[17577] Геокодируем адрес: Олеко Дундича ул, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17578/19990 [1:02:11<40:20,  1.00s/it]

[17578] Геокодируем адрес: nan

Геокодирование:  88%|████████▊ | 17579/19990 [1:02:12<39:42,  1.01it/s]

[17579] Геокодируем адрес: Байкова ул, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17580/19990 [1:02:13<40:12,  1.00s/it]

[17580] Геокодируем адрес: Шотмана ул 9к1, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17581/19990 [1:02:14<42:52,  1.07s/it]

Автосохранение после 17580 строк...
[17581] Геокодируем адрес: nan

Геокодирование:  88%|████████▊ | 17582/19990 [1:02:15<38:56,  1.03it/s]

[17582] Геокодируем адрес: nan

Геокодирование:  88%|████████▊ | 17583/19990 [1:02:16<39:40,  1.01it/s]

[17583] Геокодируем адрес: nan

Геокодирование:  88%|████████▊ | 17584/19990 [1:02:17<39:25,  1.02it/s]

[17584] Геокодируем адрес: Рыбинская ул, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17585/19990 [1:02:18<39:55,  1.00it/s]

[17585] Геокодируем адрес: Аптекарский пр-т 18, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17586/19990 [1:02:19<42:21,  1.06s/it]

[17586] Геокодируем адрес: софийская ул 69, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17587/19990 [1:02:20<39:49,  1.01it/s]

[17587] Геокодируем адрес: nan

Геокодирование:  88%|████████▊ | 17588/19990 [1:02:21<39:10,  1.02it/s]

[17588] Геокодируем адрес: nan

Геокодирование:  88%|████████▊ | 17589/19990 [1:02:22<39:11,  1.02it/s]

[17589] Геокодируем адрес: nan

Геокодирование:  88%|████████▊ | 17590/19990 [1:02:23<39:40,  1.01it/s]

[17590] Геокодируем адрес: вербная ул 18/1, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17591/19990 [1:02:24<41:31,  1.04s/it]

[17591] Геокодируем адрес: Маршала Казакова ул, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17592/19990 [1:02:25<40:28,  1.01s/it]

[17592] Геокодируем адрес: Маршала Жукова пр-т, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17593/19990 [1:02:26<41:13,  1.03s/it]

[17593] Геокодируем адрес: nan

Геокодирование:  88%|████████▊ | 17594/19990 [1:02:27<38:38,  1.03it/s]

[17594] Геокодируем адрес: реки Фонтанки наб 103, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17595/19990 [1:02:28<40:48,  1.02s/it]

[17595] Геокодируем адрес: Кадетская линия ВО 5к2Д, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17596/19990 [1:02:29<38:16,  1.04it/s]

[17596] Геокодируем адрес: Разъезжая ул 37, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17597/19990 [1:02:30<39:29,  1.01it/s]

[17597] Геокодируем адрес: 5-я Советская ул 11-13, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17598/19990 [1:02:31<40:35,  1.02s/it]

[17598] Геокодируем адрес: Пестеля ул 19, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17599/19990 [1:02:32<40:10,  1.01s/it]

[17599] Геокодируем адрес: Политехническая ул, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17600/19990 [1:02:33<39:23,  1.01it/s]

[17600] Геокодируем адрес: nan

Геокодирование:  88%|████████▊ | 17601/19990 [1:02:34<38:50,  1.03it/s]

[17601] Геокодируем адрес: Уездный пр-т, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17602/19990 [1:02:35<40:04,  1.01s/it]

[17602] Геокодируем адрес: nan

Геокодирование:  88%|████████▊ | 17603/19990 [1:02:36<39:03,  1.02it/s]

[17603] Геокодируем адрес: nan

Геокодирование:  88%|████████▊ | 17604/19990 [1:02:37<39:34,  1.00it/s]

[17604] Геокодируем адрес: nan

Геокодирование:  88%|████████▊ | 17605/19990 [1:02:38<39:18,  1.01it/s]

[17605] Геокодируем адрес: nan

Геокодирование:  88%|████████▊ | 17606/19990 [1:02:39<39:35,  1.00it/s]

[17606] Геокодируем адрес: Политехническая ул, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17607/19990 [1:02:40<39:55,  1.01s/it]

[17607] Геокодируем адрес: Дыбенко ул, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17608/19990 [1:02:41<39:50,  1.00s/it]

[17608] Геокодируем адрес: Маршала Блюхера пр-т, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17609/19990 [1:02:42<41:32,  1.05s/it]

[17609] Геокодируем адрес: nan

Геокодирование:  88%|████████▊ | 17610/19990 [1:02:43<38:47,  1.02it/s]

[17610] Геокодируем адрес: nan

Геокодирование:  88%|████████▊ | 17611/19990 [1:02:44<40:55,  1.03s/it]

Автосохранение после 17610 строк...
[17611] Геокодируем адрес: Металлистов пр-т 108, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17612/19990 [1:02:45<41:20,  1.04s/it]

[17612] Геокодируем адрес: Шушары, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17613/19990 [1:02:46<38:11,  1.04it/s]

[17613] Геокодируем адрес: Стойкости ул 30к1, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17614/19990 [1:02:47<39:37,  1.00s/it]

[17614] Геокодируем адрес: Лени Голикова ул, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17615/19990 [1:02:48<38:57,  1.02it/s]

[17615] Геокодируем адрес: nan

Геокодирование:  88%|████████▊ | 17616/19990 [1:02:49<38:33,  1.03it/s]

[17616] Геокодируем адрес: Брянцева ул, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17617/19990 [1:02:50<38:59,  1.01it/s]

[17617] Геокодируем адрес: Асафьева ул 9к1, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17618/19990 [1:02:51<40:08,  1.02s/it]

[17618] Геокодируем адрес: Асафьева ул 9к1, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17619/19990 [1:02:52<39:37,  1.00s/it]

[17619] Геокодируем адрес: Шушары, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17620/19990 [1:02:53<39:05,  1.01it/s]

[17620] Геокодируем адрес: кораблестроителей ул, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17621/19990 [1:02:54<39:21,  1.00it/s]

[17621] Геокодируем адрес: nan

Геокодирование:  88%|████████▊ | 17622/19990 [1:02:55<38:49,  1.02it/s]

[17622] Геокодируем адрес: 5-я Советская ул 11-13, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17623/19990 [1:02:56<40:26,  1.03s/it]

[17623] Геокодируем адрес: nan

Геокодирование:  88%|████████▊ | 17624/19990 [1:02:57<38:52,  1.01it/s]

[17624] Геокодируем адрес: nan

Геокодирование:  88%|████████▊ | 17625/19990 [1:02:58<38:58,  1.01it/s]

[17625] Геокодируем адрес: nan

Геокодирование:  88%|████████▊ | 17626/19990 [1:02:59<39:02,  1.01it/s]

[17626] Геокодируем адрес: nan

Геокодирование:  88%|████████▊ | 17627/19990 [1:03:00<39:16,  1.00it/s]

[17627] Геокодируем адрес: nan

Геокодирование:  88%|████████▊ | 17628/19990 [1:03:01<39:13,  1.00it/s]

[17628] Геокодируем адрес: nan

Геокодирование:  88%|████████▊ | 17629/19990 [1:03:02<39:06,  1.01it/s]

[17629] Геокодируем адрес: nan

Геокодирование:  88%|████████▊ | 17630/19990 [1:03:03<39:26,  1.00s/it]

[17630] Геокодируем адрес: Дачный пр-т, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17631/19990 [1:03:04<40:45,  1.04s/it]

[17631] Геокодируем адрес: Генерала Хазова ул, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17632/19990 [1:03:05<39:04,  1.01it/s]

[17632] Геокодируем адрес: nan

Геокодирование:  88%|████████▊ | 17633/19990 [1:03:06<38:48,  1.01it/s]

[17633] Геокодируем адрес: Щорса ул 6, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17634/19990 [1:03:07<41:37,  1.06s/it]

[17634] Геокодируем адрес: Дегтярный пер 6, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17635/19990 [1:03:08<38:57,  1.01it/s]

[17635] Геокодируем адрес: Свердловская наб, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17636/19990 [1:03:09<38:45,  1.01it/s]

[17636] Геокодируем адрес: Свердловская наб, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17637/19990 [1:03:10<38:49,  1.01it/s]

[17637] Геокодируем адрес: Софийская ул, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17638/19990 [1:03:11<39:04,  1.00it/s]

[17638] Геокодируем адрес: nan

Геокодирование:  88%|████████▊ | 17639/19990 [1:03:12<38:37,  1.01it/s]

[17639] Геокодируем адрес: Кронштадт Красная ул 8к1, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17640/19990 [1:03:13<41:00,  1.05s/it]

[17640] Геокодируем адрес: nan

Геокодирование:  88%|████████▊ | 17641/19990 [1:03:14<39:52,  1.02s/it]

Автосохранение после 17640 строк...
[17641] Геокодируем адрес: nan

Геокодирование:  88%|████████▊ | 17642/19990 [1:03:15<37:57,  1.03it/s]

[17642] Геокодируем адрес: nan

Геокодирование:  88%|████████▊ | 17643/19990 [1:03:16<38:13,  1.02it/s]

[17643] Геокодируем адрес: nan

Геокодирование:  88%|████████▊ | 17644/19990 [1:03:17<38:29,  1.02it/s]

[17644] Геокодируем адрес: Восстания ул, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17645/19990 [1:03:18<39:40,  1.02s/it]

[17645] Геокодируем адрес: nan

Геокодирование:  88%|████████▊ | 17646/19990 [1:03:19<38:30,  1.01it/s]

[17646] Геокодируем адрес: nan

Геокодирование:  88%|████████▊ | 17647/19990 [1:03:20<38:46,  1.01it/s]

[17647] Геокодируем адрес: nan

Геокодирование:  88%|████████▊ | 17648/19990 [1:03:21<38:46,  1.01it/s]

[17648] Геокодируем адрес: колпино маштностроителей ул 8, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17649/19990 [1:03:22<38:32,  1.01it/s]

[17649] Геокодируем адрес: nan

Геокодирование:  88%|████████▊ | 17650/19990 [1:03:23<38:58,  1.00it/s]

[17650] Геокодируем адрес: nan

Геокодирование:  88%|████████▊ | 17651/19990 [1:03:24<38:52,  1.00it/s]

[17651] Геокодируем адрес: nan

Геокодирование:  88%|████████▊ | 17652/19990 [1:03:25<38:55,  1.00it/s]

[17652] Геокодируем адрес: nan

Геокодирование:  88%|████████▊ | 17653/19990 [1:03:26<38:58,  1.00s/it]

[17653] Геокодируем адрес: Красногвардейская пл 5, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17654/19990 [1:03:27<39:27,  1.01s/it]

[17654] Геокодируем адрес: Рыбацкий пр-т 43к1, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17655/19990 [1:03:28<39:40,  1.02s/it]

[17655] Геокодируем адрес: nan

Геокодирование:  88%|████████▊ | 17656/19990 [1:03:29<38:28,  1.01it/s]

[17656] Геокодируем адрес: Камышовая ул 48к3, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17657/19990 [1:03:30<39:26,  1.01s/it]

[17657] Геокодируем адрес: Камышовая ул 46к1, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17658/19990 [1:03:31<39:09,  1.01s/it]

[17658] Геокодируем адрес: Энгельса пр-т 21, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17659/19990 [1:03:32<42:04,  1.08s/it]

[17659] Геокодируем адрес: Славы пр-т 43/49, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17660/19990 [1:03:33<40:57,  1.05s/it]

[17660] Геокодируем адрес: nan

Геокодирование:  88%|████████▊ | 17661/19990 [1:03:34<36:40,  1.06it/s]

[17661] Геокодируем адрес: Шушары Валдайская ул 1, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17662/19990 [1:03:35<38:59,  1.01s/it]

[17662] Геокодируем адрес: nan

Геокодирование:  88%|████████▊ | 17663/19990 [1:03:36<37:07,  1.04it/s]

[17663] Геокодируем адрес: Коллонтай ул 21к4, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17664/19990 [1:03:37<39:00,  1.01s/it]

[17664] Геокодируем адрес: nan

Геокодирование:  88%|████████▊ | 17665/19990 [1:03:38<37:33,  1.03it/s]

[17665] Геокодируем адрес: Бестужевская ул, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17666/19990 [1:03:39<38:46,  1.00s/it]

[17666] Геокодируем адрес: nan

Геокодирование:  88%|████████▊ | 17667/19990 [1:03:40<37:47,  1.02it/s]

[17667] Геокодируем адрес: Дачный пр-т 33к1, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17668/19990 [1:03:41<40:50,  1.06s/it]

[17668] Геокодируем адрес: Стойкости ул 41к1Д, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17669/19990 [1:03:42<37:07,  1.04it/s]

[17669] Геокодируем адрес: nan

Геокодирование:  88%|████████▊ | 17670/19990 [1:03:43<37:50,  1.02it/s]

[17670] Геокодируем адрес: nan

Геокодирование:  88%|████████▊ | 17671/19990 [1:03:44<39:50,  1.03s/it]

Автосохранение после 17670 строк...
[17671] Геокодируем адрес: Партизана Германа ул 21, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17672/19990 [1:03:45<39:20,  1.02s/it]

[17672] Геокодируем адрес: Солидарности пр-т 8/1, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17673/19990 [1:03:46<40:21,  1.04s/it]

[17673] Геокодируем адрес: nan

Геокодирование:  88%|████████▊ | 17674/19990 [1:03:47<36:59,  1.04it/s]

[17674] Геокодируем адрес: Верхне-Каменская ул, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17675/19990 [1:03:48<37:45,  1.02it/s]

[17675] Геокодируем адрес: nan

Геокодирование:  88%|████████▊ | 17676/19990 [1:03:49<37:46,  1.02it/s]

[17676] Геокодируем адрес: Парголово, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17677/19990 [1:03:50<38:55,  1.01s/it]

[17677] Геокодируем адрес: Павловск, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17678/19990 [1:03:51<37:59,  1.01it/s]

[17678] Геокодируем адрес: Металлострой Садовая ул 8, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17679/19990 [1:03:52<38:58,  1.01s/it]

[17679] Геокодируем адрес: nan

Геокодирование:  88%|████████▊ | 17680/19990 [1:03:53<38:22,  1.00it/s]

[17680] Геокодируем адрес: nan

Геокодирование:  88%|████████▊ | 17681/19990 [1:03:54<37:44,  1.02it/s]

[17681] Геокодируем адрес: кременчугская ул, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17682/19990 [1:03:55<38:31,  1.00s/it]

[17682] Геокодируем адрес: nan

Геокодирование:  88%|████████▊ | 17683/19990 [1:03:56<38:08,  1.01it/s]

[17683] Геокодируем адрес: кравченко ул 3к1, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17684/19990 [1:03:57<39:50,  1.04s/it]

[17684] Геокодируем адрес: Некрасова ул 6, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17685/19990 [1:03:58<40:55,  1.07s/it]

[17685] Геокодируем адрес: Солидарности пр-т, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17686/19990 [1:03:59<38:18,  1.00it/s]

[17686] Геокодируем адрес: Революции ш, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17687/19990 [1:04:00<37:40,  1.02it/s]

[17687] Геокодируем адрес: Стачек пр-т 140, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17688/19990 [1:04:01<39:36,  1.03s/it]

[17688] Геокодируем адрес: Белградская ул, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17689/19990 [1:04:02<36:59,  1.04it/s]

[17689] Геокодируем адрес: Коллонтай ул, Санкт-Петербург

Геокодирование:  88%|████████▊ | 17690/19990 [1:04:03<37:23,  1.03it/s]

[17690] Геокодируем адрес: nan

Геокодирование:  88%|████████▊ | 17691/19990 [1:04:04<37:25,  1.02it/s]

[17691] Геокодируем адрес: nan

Геокодирование:  89%|████████▊ | 17692/19990 [1:04:05<37:37,  1.02it/s]

[17692] Геокодируем адрес: Петровский пр-т, Санкт-Петербург

Геокодирование:  89%|████████▊ | 17693/19990 [1:04:06<40:18,  1.05s/it]

[17693] Геокодируем адрес: Новаторов б-р, Санкт-Петербург

Геокодирование:  89%|████████▊ | 17694/19990 [1:04:07<38:23,  1.00s/it]

[17694] Геокодируем адрес: Новаторов б-р, Санкт-Петербург

Геокодирование:  89%|████████▊ | 17695/19990 [1:04:08<38:42,  1.01s/it]

[17695] Геокодируем адрес: звездная ул, Санкт-Петербург

Геокодирование:  89%|████████▊ | 17696/19990 [1:04:09<37:36,  1.02it/s]

[17696] Геокодируем адрес: Ленинский пр-т 117к2, Санкт-Петербург

Геокодирование:  89%|████████▊ | 17697/19990 [1:04:10<38:04,  1.00it/s]

[17697] Геокодируем адрес: nan

Геокодирование:  89%|████████▊ | 17698/19990 [1:04:11<37:09,  1.03it/s]

[17698] Геокодируем адрес: nan

Геокодирование:  89%|████████▊ | 17699/19990 [1:04:12<37:28,  1.02it/s]

[17699] Геокодируем адрес: Гатчинская ул 23-25, Санкт-Петербург

Геокодирование:  89%|████████▊ | 17700/19990 [1:04:13<38:22,  1.01s/it]

[17700] Геокодируем адрес: Шушары Колпинское ш 59, Санкт-Петербург

Геокодирование:  89%|████████▊ | 17701/19990 [1:04:14<41:06,  1.08s/it]

Автосохранение после 17700 строк...
[17701] Геокодируем адрес: Шушары, Санкт-Петербург

Геокодирование:  89%|████████▊ | 17702/19990 [1:04:15<36:59,  1.03it/s]

[17702] Геокодируем адрес: Лесной пр-т 32, Санкт-Петербург

Геокодирование:  89%|████████▊ | 17703/19990 [1:04:16<41:14,  1.08s/it]

[17703] Геокодируем адрес: Одесская ул 2, Санкт-Петербург

Геокодирование:  89%|████████▊ | 17704/19990 [1:04:17<37:00,  1.03it/s]

[17704] Геокодируем адрес: Ланское ш, Санкт-Петербург

Геокодирование:  89%|████████▊ | 17705/19990 [1:04:18<36:41,  1.04it/s]

[17705] Геокодируем адрес: Идрицкая ул, Санкт-Петербург

Геокодирование:  89%|████████▊ | 17706/19990 [1:04:19<37:05,  1.03it/s]

[17706] Геокодируем адрес: Кирочная ул, Санкт-Петербург

Геокодирование:  89%|████████▊ | 17707/19990 [1:04:20<37:12,  1.02it/s]

[17707] Геокодируем адрес: беринга ул 4, Санкт-Петербург

Геокодирование:  89%|████████▊ | 17708/19990 [1:04:21<38:52,  1.02s/it]

[17708] Геокодируем адрес: Ветеранов пр-т, Санкт-Петербург

Геокодирование:  89%|████████▊ | 17709/19990 [1:04:22<38:11,  1.00s/it]

[17709] Геокодируем адрес: Боткинская ул 23, Санкт-Петербург

Геокодирование:  89%|████████▊ | 17710/19990 [1:04:23<38:31,  1.01s/it]

[17710] Геокодируем адрес: nan

Геокодирование:  89%|████████▊ | 17711/19990 [1:04:24<36:51,  1.03it/s]

[17711] Геокодируем адрес: Вадима Шефнера ул, Санкт-Петербург

Геокодирование:  89%|████████▊ | 17712/19990 [1:04:25<37:24,  1.01it/s]

[17712] Геокодируем адрес: Фурштатская ул, Санкт-Петербург

Геокодирование:  89%|████████▊ | 17713/19990 [1:04:26<37:27,  1.01it/s]

[17713] Геокодируем адрес: Савушкина ул 109, Санкт-Петербург

Геокодирование:  89%|████████▊ | 17714/19990 [1:04:27<39:09,  1.03s/it]

[17714] Геокодируем адрес: Лиговский пр-т 39, Санкт-Петербург

Геокодирование:  89%|████████▊ | 17715/19990 [1:04:28<39:06,  1.03s/it]

[17715] Геокодируем адрес: Петергофское ш 73, Санкт-Петербург

Геокодирование:  89%|████████▊ | 17716/19990 [1:04:29<37:28,  1.01it/s]

[17716] Геокодируем адрес: nan

Геокодирование:  89%|████████▊ | 17717/19990 [1:04:30<36:55,  1.03it/s]

[17717] Геокодируем адрес: профессора молчанова ул, Санкт-Петербург

Геокодирование:  89%|████████▊ | 17718/19990 [1:04:31<37:16,  1.02it/s]

[17718] Геокодируем адрес: nan

Геокодирование:  89%|████████▊ | 17719/19990 [1:04:32<37:12,  1.02it/s]

[17719] Геокодируем адрес: Вавиловых ул 11к6, Санкт-Петербург

Геокодирование:  89%|████████▊ | 17720/19990 [1:04:33<37:43,  1.00it/s]

[17720] Геокодируем адрес: Вавиловых ул 11к6, Санкт-Петербург

Геокодирование:  89%|████████▊ | 17721/19990 [1:04:34<37:26,  1.01it/s]

[17721] Геокодируем адрес: Малая Бухарестская ул 3, Санкт-Петербург

Геокодирование:  89%|████████▊ | 17722/19990 [1:04:36<51:01,  1.35s/it]

[17722] Геокодируем адрес: альпийский пер, Санкт-Петербург

Геокодирование:  89%|████████▊ | 17723/19990 [1:04:37<44:56,  1.19s/it]

[17723] Геокодируем адрес: Долгоозерная ул 14, Санкт-Петербург

Геокодирование:  89%|████████▊ | 17724/19990 [1:04:38<44:28,  1.18s/it]

[17724] Геокодируем адрес: Константина Заслонова ул 28-30, Санкт-Петербург

Геокодирование:  89%|████████▊ | 17725/19990 [1:04:39<42:35,  1.13s/it]

[17725] Геокодируем адрес: новостроек ул, Санкт-Петербург

Геокодирование:  89%|████████▊ | 17726/19990 [1:04:40<39:11,  1.04s/it]

[17726] Геокодируем адрес: Константина Заслонова ул 26, Санкт-Петербург

Геокодирование:  89%|████████▊ | 17727/19990 [1:04:41<39:58,  1.06s/it]

[17727] Геокодируем адрес: Петергофское ш 73, Санкт-Петербург

Геокодирование:  89%|████████▊ | 17728/19990 [1:04:42<39:07,  1.04s/it]

[17728] Геокодируем адрес: nan

Геокодирование:  89%|████████▊ | 17729/19990 [1:04:43<37:35,  1.00it/s]

[17729] Геокодируем адрес: Невский пр-т 146, Санкт-Петербург

Геокодирование:  89%|████████▊ | 17730/19990 [1:04:44<40:09,  1.07s/it]

[17730] Геокодируем адрес: Альпийский пер 9к2, Санкт-Петербург

Геокодирование:  89%|████████▊ | 17731/19990 [1:04:45<38:56,  1.03s/it]

Автосохранение после 17730 строк...
[17731] Геокодируем адрес: Ломоносов Красного Флота ул, Санкт-Петербург

Геокодирование:  89%|████████▊ | 17732/19990 [1:04:46<37:43,  1.00s/it]

[17732] Геокодируем адрес: Краснопутиловская ул, Санкт-Петербург

Геокодирование:  89%|████████▊ | 17733/19990 [1:04:47<37:00,  1.02it/s]

[17733] Геокодируем адрес: Пушкин Госпитальный пер 19к2, Санкт-Петербург

Геокодирование:  89%|████████▊ | 17734/19990 [1:04:48<37:53,  1.01s/it]

[17734] Геокодируем адрес: Большая Зеленина ул, Санкт-Петербург

Геокодирование:  89%|████████▊ | 17735/19990 [1:04:49<36:58,  1.02it/s]

[17735] Геокодируем адрес: Кирочная ул, Санкт-Петербург

Геокодирование:  89%|████████▊ | 17736/19990 [1:04:50<37:01,  1.01it/s]

[17736] Геокодируем адрес: nan

Геокодирование:  89%|████████▊ | 17737/19990 [1:04:51<36:51,  1.02it/s]

[17737] Геокодируем адрес: Просвещения пр-т, Санкт-Петербург

Геокодирование:  89%|████████▊ | 17738/19990 [1:04:52<37:56,  1.01s/it]

[17738] Геокодируем адрес: Пулковское ш 30к2, Санкт-Петербург

Геокодирование:  89%|████████▊ | 17739/19990 [1:04:53<37:29,  1.00it/s]

[17739] Геокодируем адрес: Маршала Жукова пр-т 28к1, Санкт-Петербург

Геокодирование:  89%|████████▊ | 17740/19990 [1:04:54<39:34,  1.06s/it]

[17740] Геокодируем адрес: Маршала Жукова пр-т 30к2В, Санкт-Петербург

Геокодирование:  89%|████████▊ | 17741/19990 [1:04:55<35:54,  1.04it/s]

[17741] Геокодируем адрес: nan

Геокодирование:  89%|████████▉ | 17742/19990 [1:04:56<36:28,  1.03it/s]

[17742] Геокодируем адрес: Парголово Первого Мая ул 85, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17743/19990 [1:04:57<38:15,  1.02s/it]

[17743] Геокодируем адрес: nan

Геокодирование:  89%|████████▉ | 17744/19990 [1:04:58<36:39,  1.02it/s]

[17744] Геокодируем адрес: маршала казакова ул 24к1, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17745/19990 [1:04:59<38:36,  1.03s/it]

[17745] Геокодируем адрес: Федора Абрамова ул, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17746/19990 [1:05:00<36:52,  1.01it/s]

[17746] Геокодируем адрес: Ленинский пр-т 114, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17747/19990 [1:05:01<41:01,  1.10s/it]

[17747] Геокодируем адрес: Невзоровой ул 9, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17748/19990 [1:05:02<36:34,  1.02it/s]

[17748] Геокодируем адрес: Маршала Казакова ул 50к1, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17749/19990 [1:05:03<37:47,  1.01s/it]

[17749] Геокодируем адрес: nan

Геокодирование:  89%|████████▉ | 17750/19990 [1:05:04<35:25,  1.05it/s]

[17750] Геокодируем адрес: Малая ул 11, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17751/19990 [1:05:05<38:01,  1.02s/it]

[17751] Геокодируем адрес: Петергофское ш, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17752/19990 [1:05:06<36:27,  1.02it/s]

[17752] Геокодируем адрес: Меркурьева ул, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17753/19990 [1:05:07<36:15,  1.03it/s]

[17753] Геокодируем адрес: морской пехоты ул, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17754/19990 [1:05:08<37:00,  1.01it/s]

[17754] Геокодируем адрес: 2-я Советская ул, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17755/19990 [1:05:09<37:45,  1.01s/it]

[17755] Геокодируем адрес: nan

Геокодирование:  89%|████████▉ | 17756/19990 [1:05:10<36:28,  1.02it/s]

[17756] Геокодируем адрес: nan

Геокодирование:  89%|████████▉ | 17757/19990 [1:05:11<36:28,  1.02it/s]

[17757] Геокодируем адрес: Катерников пр-т, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17758/19990 [1:05:12<38:13,  1.03s/it]

[17758] Геокодируем адрес: nan

Геокодирование:  89%|████████▉ | 17759/19990 [1:05:13<36:16,  1.02it/s]

[17759] Геокодируем адрес: Орлово-Денисовский пр-т 19к1, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17760/19990 [1:05:14<38:30,  1.04s/it]

[17760] Геокодируем адрес: Елизарова пр-т, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17761/19990 [1:05:15<39:01,  1.05s/it]

Автосохранение после 17760 строк...
[17761] Геокодируем адрес: Боровая ул 6Д, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17762/19990 [1:05:16<37:00,  1.00it/s]

[17762] Геокодируем адрес: nan

Геокодирование:  89%|████████▉ | 17763/19990 [1:05:17<35:37,  1.04it/s]

[17763] Геокодируем адрес: nan

Геокодирование:  89%|████████▉ | 17764/19990 [1:05:19<47:12,  1.27s/it]

[17764] Геокодируем адрес: Савушкина ул, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17765/19990 [1:05:20<44:30,  1.20s/it]

[17765] Геокодируем адрес: Большевиков пр-т 43к1, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17766/19990 [1:05:21<43:39,  1.18s/it]

[17766] Геокодируем адрес: бухарестская ул 39к3, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17767/19990 [1:05:22<40:15,  1.09s/it]

[17767] Геокодируем адрес: nan

Геокодирование:  89%|████████▉ | 17768/19990 [1:05:23<38:55,  1.05s/it]

[17768] Геокодируем адрес: Караваевская ул 29, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17769/19990 [1:05:24<39:11,  1.06s/it]

[17769] Геокодируем адрес: Светлановский пр-т, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17770/19990 [1:05:25<38:50,  1.05s/it]

[17770] Геокодируем адрес: Костюшко ул 10, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17771/19990 [1:05:26<38:26,  1.04s/it]

[17771] Геокодируем адрес: Новочеркасский пр-т, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17772/19990 [1:05:27<37:25,  1.01s/it]

[17772] Геокодируем адрес: Лиговский пр-т 17, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17773/19990 [1:05:28<38:23,  1.04s/it]

[17773] Геокодируем адрес: nan

Геокодирование:  89%|████████▉ | 17774/19990 [1:05:29<36:33,  1.01it/s]

[17774] Геокодируем адрес: Лиговский пр-т 17, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17775/19990 [1:05:30<39:11,  1.06s/it]

[17775] Геокодируем адрес: nan

Геокодирование:  89%|████████▉ | 17776/19990 [1:05:31<35:26,  1.04it/s]

[17776] Геокодируем адрес: Школьная ул 37к2, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17777/19990 [1:05:32<39:20,  1.07s/it]

[17777] Геокодируем адрес: nan

Геокодирование:  89%|████████▉ | 17778/19990 [1:05:33<35:09,  1.05it/s]

[17778] Геокодируем адрес: Батайский пер, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17779/19990 [1:05:34<35:43,  1.03it/s]

[17779] Геокодируем адрес: nan

Геокодирование:  89%|████████▉ | 17780/19990 [1:05:35<36:31,  1.01it/s]

[17780] Геокодируем адрес: Некрасова ул 41, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17781/19990 [1:05:36<39:23,  1.07s/it]

[17781] Геокодируем адрес: Металлострой Садовая ул 8, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17782/19990 [1:05:37<36:23,  1.01it/s]

[17782] Геокодируем адрес: nan

Геокодирование:  89%|████████▉ | 17783/19990 [1:05:38<35:36,  1.03it/s]

[17783] Геокодируем адрес: nan

Геокодирование:  89%|████████▉ | 17784/19990 [1:05:39<36:02,  1.02it/s]

[17784] Геокодируем адрес: Тимофея Фёдорова ул, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17785/19990 [1:05:40<36:02,  1.02it/s]

[17785] Геокодируем адрес: Лени Голикова ул, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17786/19990 [1:05:41<36:28,  1.01it/s]

[17786] Геокодируем адрес: Королева пр-т 63/2, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17787/19990 [1:05:42<40:38,  1.11s/it]

[17787] Геокодируем адрес: Веденеева ул 4, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17788/19990 [1:05:43<35:42,  1.03it/s]

[17788] Геокодируем адрес: nan

Геокодирование:  89%|████████▉ | 17789/19990 [1:05:44<35:11,  1.04it/s]

[17789] Геокодируем адрес: Планерная ул, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17790/19990 [1:05:45<36:09,  1.01it/s]

[17790] Геокодируем адрес: Шушары Первомайская ул 26, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17791/19990 [1:05:46<39:00,  1.06s/it]

Автосохранение после 17790 строк...
[17791] Геокодируем адрес: nan

Геокодирование:  89%|████████▉ | 17792/19990 [1:05:47<35:03,  1.05it/s]

[17792] Геокодируем адрес: Ленинский пр-т, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17793/19990 [1:05:48<37:35,  1.03s/it]

[17793] Геокодируем адрес: Подвойского ул 24к2, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17794/19990 [1:05:49<36:01,  1.02it/s]

[17794] Геокодируем адрес: Крупской с-д, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17795/19990 [1:05:50<37:14,  1.02s/it]

[17795] Геокодируем адрес: nan

Геокодирование:  89%|████████▉ | 17796/19990 [1:05:51<35:15,  1.04it/s]

[17796] Геокодируем адрес: Шушары, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17797/19990 [1:05:52<35:46,  1.02it/s]

[17797] Геокодируем адрес: Шушары Хазова ул 5, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17798/19990 [1:05:53<36:51,  1.01s/it]

[17798] Геокодируем адрес: Генерала Кравченко ул 3к1, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17799/19990 [1:05:54<36:21,  1.00it/s]

[17799] Геокодируем адрес: Энгельса пр-т, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17800/19990 [1:05:55<37:19,  1.02s/it]

[17800] Геокодируем адрес: Художников пр-т, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17801/19990 [1:05:56<36:14,  1.01it/s]

[17801] Геокодируем адрес: Художников пр-т, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17802/19990 [1:05:57<36:32,  1.00s/it]

[17802] Геокодируем адрес: nan

Геокодирование:  89%|████████▉ | 17803/19990 [1:05:58<35:44,  1.02it/s]

[17803] Геокодируем адрес: Шушары Окуловская ул 8, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17804/19990 [1:05:59<36:35,  1.00s/it]

[17804] Геокодируем адрес: Советский пр-т 39к1, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17805/19990 [1:06:00<36:24,  1.00it/s]

[17805] Геокодируем адрес: Генерала Кравченко ул 3к1, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17806/19990 [1:06:01<36:18,  1.00it/s]

[17806] Геокодируем адрес: Невский пр-т 128, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17807/19990 [1:06:02<38:00,  1.04s/it]

[17807] Геокодируем адрес: 2-й Предпортовый пр-д, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17808/19990 [1:06:03<35:33,  1.02it/s]

[17808] Геокодируем адрес: бухарестская ул, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17809/19990 [1:06:04<35:51,  1.01it/s]

[17809] Геокодируем адрес: Ленинский пр-т, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17810/19990 [1:06:05<37:28,  1.03s/it]

[17810] Геокодируем адрес: Сестрорецк Северный пер, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17811/19990 [1:06:06<35:38,  1.02it/s]

[17811] Геокодируем адрес: Муринская дор, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17812/19990 [1:06:07<35:39,  1.02it/s]

[17812] Геокодируем адрес: Гагаринская ул, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17813/19990 [1:06:08<35:36,  1.02it/s]

[17813] Геокодируем адрес: Зайцева ул 39В, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17814/19990 [1:06:09<36:44,  1.01s/it]

[17814] Геокодируем адрес: nan

Геокодирование:  89%|████████▉ | 17815/19990 [1:06:10<35:22,  1.02it/s]

[17815] Геокодируем адрес: бухарестская ул 33к1, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17816/19990 [1:06:11<37:15,  1.03s/it]

[17816] Геокодируем адрес: Вербная ул 20/2Б, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17817/19990 [1:06:12<36:45,  1.02s/it]

[17817] Геокодируем адрес: Партизана Германа ул 5/14, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17818/19990 [1:06:13<36:19,  1.00s/it]

[17818] Геокодируем адрес: Ветеранов пр-т 151к2, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17819/19990 [1:06:14<36:42,  1.01s/it]

[17819] Геокодируем адрес: nan

Геокодирование:  89%|████████▉ | 17820/19990 [1:06:15<35:02,  1.03it/s]

[17820] Геокодируем адрес: nan

Геокодирование:  89%|████████▉ | 17821/19990 [1:06:16<36:45,  1.02s/it]

Автосохранение после 17820 строк...
[17821] Геокодируем адрес: nan

Геокодирование:  89%|████████▉ | 17822/19990 [1:06:17<35:07,  1.03it/s]

[17822] Геокодируем адрес: Витебский пр-т 53к1, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17823/19990 [1:06:18<35:46,  1.01it/s]

[17823] Геокодируем адрес: Академика Глушко ал, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17824/19990 [1:06:19<36:21,  1.01s/it]

[17824] Геокодируем адрес: Ольховая ул 2, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17825/19990 [1:06:20<36:18,  1.01s/it]

[17825] Геокодируем адрес: Подвойского ул 24к2, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17826/19990 [1:06:21<36:01,  1.00it/s]

[17826] Геокодируем адрес: Зины Портновой ул, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17827/19990 [1:06:22<35:32,  1.01it/s]

[17827] Геокодируем адрес: Ждановская наб, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17828/19990 [1:06:23<35:28,  1.02it/s]

[17828] Геокодируем адрес: Белы Куна ул, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17829/19990 [1:06:24<35:57,  1.00it/s]

[17829] Геокодируем адрес: Обводного канала наб, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17830/19990 [1:06:25<36:29,  1.01s/it]

[17830] Геокодируем адрес: Кузнечный пер, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17831/19990 [1:06:26<35:51,  1.00it/s]

[17831] Геокодируем адрес: nan

Геокодирование:  89%|████████▉ | 17832/19990 [1:06:27<35:20,  1.02it/s]

[17832] Геокодируем адрес: Маршала Захарова ул, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17833/19990 [1:06:28<36:58,  1.03s/it]

[17833] Геокодируем адрес: Балтийская ул, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17834/19990 [1:06:29<35:55,  1.00it/s]

[17834] Геокодируем адрес: nan

Геокодирование:  89%|████████▉ | 17835/19990 [1:06:30<35:07,  1.02it/s]

[17835] Геокодируем адрес: 1-й предпортовый пр-д 15, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17836/19990 [1:06:31<36:23,  1.01s/it]

[17836] Геокодируем адрес: Санкт-Петербургское ш 108, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17837/19990 [1:06:32<36:02,  1.00s/it]

[17837] Геокодируем адрес: nan

Геокодирование:  89%|████████▉ | 17838/19990 [1:06:33<35:17,  1.02it/s]

[17838] Геокодируем адрес: Красина ул, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17839/19990 [1:06:34<36:05,  1.01s/it]

[17839] Геокодируем адрес: Ленинский пр-т 67.1, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17840/19990 [1:06:35<39:42,  1.11s/it]

[17840] Геокодируем адрес: Васи Алексеева ул 23, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17841/19990 [1:06:36<36:01,  1.01s/it]

[17841] Геокодируем адрес: nan

Геокодирование:  89%|████████▉ | 17842/19990 [1:06:37<34:04,  1.05it/s]

[17842] Геокодируем адрес: Вадима Шефнера ул, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17843/19990 [1:06:38<34:42,  1.03it/s]

[17843] Геокодируем адрес: Дашкевича ул, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17844/19990 [1:06:39<35:07,  1.02it/s]

[17844] Геокодируем адрес: Железнодорожный пр-т, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17845/19990 [1:06:40<36:43,  1.03s/it]

[17845] Геокодируем адрес: муринская дор, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17846/19990 [1:06:41<34:52,  1.02it/s]

[17846] Геокодируем адрес: Маршала Казакова ул 67а, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17847/19990 [1:06:42<37:05,  1.04s/it]

[17847] Геокодируем адрес: бухарестская ул 33к1, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17848/19990 [1:06:43<36:11,  1.01s/it]

[17848] Геокодируем адрес: Плесецкая ул 16стр1, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17849/19990 [1:06:44<34:58,  1.02it/s]

[17849] Геокодируем адрес: Ушинского ул 33к2, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17850/19990 [1:06:45<35:07,  1.02it/s]

[17850] Геокодируем адрес: Байконурская ул 5к1, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17851/19990 [1:06:46<37:14,  1.04s/it]

Автосохранение после 17850 строк...
[17851] Геокодируем адрес: Петровский пр-т, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17852/19990 [1:06:47<36:04,  1.01s/it]

[17852] Геокодируем адрес: Первомайская ул, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17853/19990 [1:06:48<35:44,  1.00s/it]

[17853] Геокодируем адрес: Кронштадт Советская ул 31, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17854/19990 [1:06:49<35:00,  1.02it/s]

[17854] Геокодируем адрес: Ленинский пр-т, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17855/19990 [1:06:51<45:35,  1.28s/it]

[17855] Геокодируем адрес: Белы Куна ул 7к5, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17856/19990 [1:06:52<40:49,  1.15s/it]

[17856] Геокодируем адрес: адмирала лазарева наб, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17857/19990 [1:06:53<38:23,  1.08s/it]

[17857] Геокодируем адрес: 3-я ул, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17858/19990 [1:06:54<37:14,  1.05s/it]

[17858] Геокодируем адрес: Марата ул 29, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17859/19990 [1:06:55<38:46,  1.09s/it]

[17859] Геокодируем адрес: Балтийский б-р 4стр1, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17860/19990 [1:06:56<36:36,  1.03s/it]

[17860] Геокодируем адрес: Маршала Блюхера пр-т 67к2, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17861/19990 [1:06:58<47:03,  1.33s/it]

[17861] Геокодируем адрес: Туристская ул 22, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17862/19990 [1:06:59<44:43,  1.26s/it]

[17862] Геокодируем адрес: Витебский пр-т 33к1, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17863/19990 [1:07:00<41:28,  1.17s/it]

[17863] Геокодируем адрес: Выборгское ш 5к1И, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17864/19990 [1:07:01<37:33,  1.06s/it]

[17864] Геокодируем адрес: Подвойского ул, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17865/19990 [1:07:02<37:44,  1.07s/it]

[17865] Геокодируем адрес: Космонавтов пр-т 29к6, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17866/19990 [1:07:03<37:17,  1.05s/it]

[17866] Геокодируем адрес: Белградская ул 22к1, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17867/19990 [1:07:04<36:55,  1.04s/it]

[17867] Геокодируем адрес: nan

Геокодирование:  89%|████████▉ | 17868/19990 [1:07:05<35:43,  1.01s/it]

[17868] Геокодируем адрес: бухарестская ул 31к5, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17869/19990 [1:07:06<36:38,  1.04s/it]

[17869] Геокодируем адрес: Железноводская ул 66, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17870/19990 [1:07:07<35:30,  1.00s/it]

[17870] Геокодируем адрес: Шаумяна пр-т 8, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17871/19990 [1:07:08<40:36,  1.15s/it]

[17871] Геокодируем адрес: 1-й Верхний пер, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17872/19990 [1:07:09<36:38,  1.04s/it]

[17872] Геокодируем адрес: Лени Голикова ул 90, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17873/19990 [1:07:10<36:23,  1.03s/it]

[17873] Геокодируем адрес: Белорусская ул 14/22, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17874/19990 [1:07:11<36:23,  1.03s/it]

[17874] Геокодируем адрес: Невский пр-т 20, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17875/19990 [1:07:14<52:07,  1.48s/it]

[17875] Геокодируем адрес: Угольная ул 14, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17876/19990 [1:07:14<44:59,  1.28s/it]

[17876] Геокодируем адрес: Маршала Жукова пр-т 54к1литераА, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17877/19990 [1:07:15<39:29,  1.12s/it]

[17877] Геокодируем адрес: Новоколомяжский пр-т 4к3, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17878/19990 [1:07:16<40:38,  1.15s/it]

[17878] Геокодируем адрес: Парковая ул 16к6, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17879/19990 [1:07:17<39:38,  1.13s/it]

[17879] Геокодируем адрес: Комендантский пр-т 39к1, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17880/19990 [1:07:18<36:01,  1.02s/it]

[17880] Геокодируем адрес: Парковая ул 16к6, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17881/19990 [1:07:19<39:14,  1.12s/it]

Автосохранение после 17880 строк...
[17881] Геокодируем адрес: Энергетиков пр-т 28к7, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17882/19990 [1:07:20<34:37,  1.01it/s]

[17882] Геокодируем адрес: nan

Геокодирование:  89%|████████▉ | 17883/19990 [1:07:21<33:57,  1.03it/s]

[17883] Геокодируем адрес: Большая Пороховская ул 54к4, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17884/19990 [1:07:22<35:03,  1.00it/s]

[17884] Геокодируем адрес: nan

Геокодирование:  89%|████████▉ | 17885/19990 [1:07:23<34:32,  1.02it/s]

[17885] Геокодируем адрес: Шушары Вишерская ул 22, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17886/19990 [1:07:24<37:23,  1.07s/it]

[17886] Геокодируем адрес: Суворовский пр-т 62, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17887/19990 [1:07:25<37:40,  1.07s/it]

[17887] Геокодируем адрес: Димитрова ул 3к1, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17888/19990 [1:07:26<35:34,  1.02s/it]

[17888] Геокодируем адрес: Ушаковская наб 9к1, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17889/19990 [1:07:27<33:46,  1.04it/s]

[17889] Геокодируем адрес: бухарестская ул 23к1, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17890/19990 [1:07:28<35:29,  1.01s/it]

[17890] Геокодируем адрес: Маршала Захарова ул 58, Санкт-Петербург

Геокодирование:  89%|████████▉ | 17891/19990 [1:07:29<35:58,  1.03s/it]

[17891] Геокодируем адрес: бухарестская ул 72к1, Санкт-Петербург

Геокодирование:  90%|████████▉ | 17892/19990 [1:07:30<34:12,  1.02it/s]

[17892] Геокодируем адрес: Новаторов б-р 51, Санкт-Петербург

Геокодирование:  90%|████████▉ | 17893/19990 [1:07:32<37:43,  1.08s/it]

[17893] Геокодируем адрес: Турку ул 11к1, Санкт-Петербург

Геокодирование:  90%|████████▉ | 17894/19990 [1:07:32<34:05,  1.02it/s]

[17894] Геокодируем адрес: Союза Печатников ул 8, Санкт-Петербург

Геокодирование:  90%|████████▉ | 17895/19990 [1:07:33<33:59,  1.03it/s]

[17895] Геокодируем адрес: Малодетскосельский пр-т 27а, Санкт-Петербург

Геокодирование:  90%|████████▉ | 17896/19990 [1:07:34<36:34,  1.05s/it]

[17896] Геокодируем адрес: Шушары Школьная ул 28, Санкт-Петербург

Геокодирование:  90%|████████▉ | 17897/19990 [1:07:35<34:22,  1.01it/s]

[17897] Геокодируем адрес: Маршака пр-т 28к1, Санкт-Петербург

Геокодирование:  90%|████████▉ | 17898/19990 [1:07:36<35:12,  1.01s/it]

[17898] Геокодируем адрес: Орджоникидзе ул 37к1, Санкт-Петербург

Геокодирование:  90%|████████▉ | 17899/19990 [1:07:37<34:06,  1.02it/s]

[17899] Геокодируем адрес: Лени Голикова ул, Санкт-Петербург

Геокодирование:  90%|████████▉ | 17900/19990 [1:07:38<33:13,  1.05it/s]

[17900] Геокодируем адрес: nan

Геокодирование:  90%|████████▉ | 17901/19990 [1:07:39<33:15,  1.05it/s]

[17901] Геокодируем адрес: Шушары Школьная ул 26, Санкт-Петербург

Геокодирование:  90%|████████▉ | 17902/19990 [1:07:40<36:26,  1.05s/it]

[17902] Геокодируем адрес: Арцеуловская ал 23к1, Санкт-Петербург

Геокодирование:  90%|████████▉ | 17903/19990 [1:07:41<34:09,  1.02it/s]

[17903] Геокодируем адрес: Морская ул, Санкт-Петербург

Геокодирование:  90%|████████▉ | 17904/19990 [1:07:42<34:00,  1.02it/s]

[17904] Геокодируем адрес: Парголово Михаила Дудина ул 25к2, Санкт-Петербург

Геокодирование:  90%|████████▉ | 17905/19990 [1:07:43<36:08,  1.04s/it]

[17905] Геокодируем адрес: Димитрова ул 7к1, Санкт-Петербург

Геокодирование:  90%|████████▉ | 17906/19990 [1:07:45<36:56,  1.06s/it]

[17906] Геокодируем адрес: Марата ул 75, Санкт-Петербург

Геокодирование:  90%|████████▉ | 17907/19990 [1:07:46<36:34,  1.05s/it]

[17907] Геокодируем адрес: Полоцкая ул, Санкт-Петербург

Геокодирование:  90%|████████▉ | 17908/19990 [1:07:46<33:14,  1.04it/s]

[17908] Геокодируем адрес: Штурманская ул 34, Санкт-Петербург

Геокодирование:  90%|████████▉ | 17909/19990 [1:07:47<33:13,  1.04it/s]

[17909] Геокодируем адрес: Стойкости ул 20, Санкт-Петербург

Геокодирование:  90%|████████▉ | 17910/19990 [1:07:48<34:10,  1.01it/s]

[17910] Геокодируем адрес: Тельмана ул 40, Санкт-Петербург

Геокодирование:  90%|████████▉ | 17911/19990 [1:07:50<37:03,  1.07s/it]

Автосохранение после 17910 строк...
[17911] Геокодируем адрес: Стойкости ул 12, Санкт-Петербург

Геокодирование:  90%|████████▉ | 17912/19990 [1:07:50<33:05,  1.05it/s]

[17912] Геокодируем адрес: nan

Геокодирование:  90%|████████▉ | 17913/19990 [1:07:51<32:45,  1.06it/s]

[17913] Геокодируем адрес: Плесецкая ул 20к1, Санкт-Петербург

Геокодирование:  90%|████████▉ | 17914/19990 [1:07:52<35:40,  1.03s/it]

[17914] Геокодируем адрес: Комендантский пр-т 66к1, Санкт-Петербург

Геокодирование:  90%|████████▉ | 17915/19990 [1:07:53<33:55,  1.02it/s]

[17915] Геокодируем адрес: nan

Геокодирование:  90%|████████▉ | 17916/19990 [1:07:54<33:00,  1.05it/s]

[17916] Геокодируем адрес: Ветеранов пр-т 149к2, Санкт-Петербург

Геокодирование:  90%|████████▉ | 17917/19990 [1:07:55<34:54,  1.01s/it]

[17917] Геокодируем адрес: Александровской Фермы пр-т 13, Санкт-Петербург

Геокодирование:  90%|████████▉ | 17918/19990 [1:07:56<36:38,  1.06s/it]

[17918] Геокодируем адрес: nan

Геокодирование:  90%|████████▉ | 17919/19990 [1:07:57<32:31,  1.06it/s]

[17919] Геокодируем адрес: Морской пр-т 15, Санкт-Петербург

Геокодирование:  90%|████████▉ | 17920/19990 [1:07:58<36:40,  1.06s/it]

[17920] Геокодируем адрес: Перекопская ул 3, Санкт-Петербург

Геокодирование:  90%|████████▉ | 17921/19990 [1:07:59<33:41,  1.02it/s]

[17921] Геокодируем адрес: Петербургское ш 5, Санкт-Петербург

Геокодирование:  90%|████████▉ | 17922/19990 [1:08:00<35:34,  1.03s/it]

[17922] Геокодируем адрес: nan

Геокодирование:  90%|████████▉ | 17923/19990 [1:08:01<32:43,  1.05it/s]

[17923] Геокодируем адрес: Шелгунова ул 27, Санкт-Петербург

Геокодирование:  90%|████████▉ | 17924/19990 [1:08:02<34:27,  1.00s/it]

[17924] Геокодируем адрес: Шелгунова ул 27, Санкт-Петербург

Геокодирование:  90%|████████▉ | 17925/19990 [1:08:03<34:59,  1.02s/it]

[17925] Геокодируем адрес: nan

Геокодирование:  90%|████████▉ | 17926/19990 [1:08:04<32:52,  1.05it/s]

[17926] Геокодируем адрес: Таврическая ул 5, Санкт-Петербург

Геокодирование:  90%|████████▉ | 17927/19990 [1:08:05<35:05,  1.02s/it]

[17927] Геокодируем адрес: Лидии Зверевой ул 5к1, Санкт-Петербург

Геокодирование:  90%|████████▉ | 17928/19990 [1:08:06<34:18,  1.00it/s]

[17928] Геокодируем адрес: nan

Геокодирование:  90%|████████▉ | 17929/19990 [1:08:07<33:17,  1.03it/s]

[17929] Геокодируем адрес: реки Фонтанки наб 103, Санкт-Петербург

Геокодирование:  90%|████████▉ | 17930/19990 [1:08:08<36:00,  1.05s/it]

[17930] Геокодируем адрес: Шелгунова ул 27, Санкт-Петербург

Геокодирование:  90%|████████▉ | 17931/19990 [1:08:09<35:25,  1.03s/it]

[17931] Геокодируем адрес: Парголово Меркурьева ул, Санкт-Петербург

Геокодирование:  90%|████████▉ | 17932/19990 [1:08:10<32:48,  1.05it/s]

[17932] Геокодируем адрес: nan

Геокодирование:  90%|████████▉ | 17933/19990 [1:08:11<32:52,  1.04it/s]

[17933] Геокодируем адрес: Малая Балканская ул 12к1, Санкт-Петербург

Геокодирование:  90%|████████▉ | 17934/19990 [1:08:12<36:35,  1.07s/it]

[17934] Геокодируем адрес: Константина Заслонова ул 32-34, Санкт-Петербург

Геокодирование:  90%|████████▉ | 17935/19990 [1:08:13<35:16,  1.03s/it]

[17935] Геокодируем адрес: Черняховского ул 16к5, Санкт-Петербург

Геокодирование:  90%|████████▉ | 17936/19990 [1:08:14<33:42,  1.02it/s]

[17936] Геокодируем адрес: nan

Геокодирование:  90%|████████▉ | 17937/19990 [1:08:15<32:39,  1.05it/s]

[17937] Геокодируем адрес: Жуковского ул 57, Санкт-Петербург

Геокодирование:  90%|████████▉ | 17938/19990 [1:08:16<35:26,  1.04s/it]

[17938] Геокодируем адрес: Большой Васильевского острова пр-д 74, Санкт-Петербург

Геокодирование:  90%|████████▉ | 17939/19990 [1:08:19<49:34,  1.45s/it]

[17939] Геокодируем адрес: Энгельса пр-т 28к2, Санкт-Петербург

Геокодирование:  90%|████████▉ | 17940/19990 [1:08:20<41:38,  1.22s/it]

[17940] Геокодируем адрес: остров Декабристов, Санкт-Петербург

Геокодирование:  90%|████████▉ | 17941/19990 [1:08:21<40:10,  1.18s/it]

Автосохранение после 17940 строк...
[17941] Геокодируем адрес: Омская ул 14, Санкт-Петербург

Геокодирование:  90%|████████▉ | 17942/19990 [1:08:22<37:59,  1.11s/it]

[17942] Геокодируем адрес: Дыбенко ул, Санкт-Петербург

Геокодирование:  90%|████████▉ | 17943/19990 [1:08:22<35:43,  1.05s/it]

[17943] Геокодируем адрес: Парголово, Санкт-Петербург

Геокодирование:  90%|████████▉ | 17944/19990 [1:08:23<35:17,  1.03s/it]

[17944] Геокодируем адрес: Зайцева ул, Санкт-Петербург

Геокодирование:  90%|████████▉ | 17945/19990 [1:08:24<35:10,  1.03s/it]

[17945] Геокодируем адрес: Стачек пр-т, Санкт-Петербург

Геокодирование:  90%|████████▉ | 17946/19990 [1:08:26<36:34,  1.07s/it]

[17946] Геокодируем адрес: 2-й Предпортовый пр-д, Санкт-Петербург

Геокодирование:  90%|████████▉ | 17947/19990 [1:08:27<34:26,  1.01s/it]

[17947] Геокодируем адрес: Александровское ш, Санкт-Петербург

Геокодирование:  90%|████████▉ | 17948/19990 [1:08:27<33:31,  1.02it/s]

[17948] Геокодируем адрес: Токарева ул 6, Санкт-Петербург

Геокодирование:  90%|████████▉ | 17949/19990 [1:08:29<34:48,  1.02s/it]

[17949] Геокодируем адрес: Долгоозерная ул, Санкт-Петербург

Геокодирование:  90%|████████▉ | 17950/19990 [1:08:29<33:41,  1.01it/s]

[17950] Геокодируем адрес: Кронштадтская пл, Санкт-Петербург

Геокодирование:  90%|████████▉ | 17951/19990 [1:08:30<33:57,  1.00it/s]

[17951] Геокодируем адрес: Павловск Грушевая ул, Санкт-Петербург

Геокодирование:  90%|████████▉ | 17952/19990 [1:08:32<34:13,  1.01s/it]

[17952] Геокодируем адрес: nan

Геокодирование:  90%|████████▉ | 17953/19990 [1:08:32<33:22,  1.02it/s]

[17953] Геокодируем адрес: Благодатная ул 34, Санкт-Петербург

Геокодирование:  90%|████████▉ | 17954/19990 [1:08:34<35:48,  1.06s/it]

[17954] Геокодируем адрес: Русановская ул, Санкт-Петербург

Геокодирование:  90%|████████▉ | 17955/19990 [1:08:34<33:09,  1.02it/s]

[17955] Геокодируем адрес: nan

Геокодирование:  90%|████████▉ | 17956/19990 [1:08:36<33:47,  1.00it/s]

[17956] Геокодируем адрес: nan

Геокодирование:  90%|████████▉ | 17957/19990 [1:08:36<33:43,  1.00it/s]

[17957] Геокодируем адрес: 13-я линия ВО, Санкт-Петербург

RateLimiter caught an error, retrying (0/2 tries). Called with (*('13-я линия ВО, Санкт-Петербург',), **{}).
Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connection.py", line 516, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1374, in getresponse
    response.begin()
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1278, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1134, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 367, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=13-%D1%8F+%D0%BB%D0%B8%D0%BD%D0%B8%D1%8F+%D0%92%D0%9E%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 482, in _request
    resp = self.session.get(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\requests\adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=13-%D1%8F+%D0%BB%D0%B8%D0%BD%D0%B8%D1%8F+%D0%92%D0%9E%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\extra\rate_limiter.py", line 136, in _retries_gen
    yield i  # Run the function.
    ^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\extra\rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\geocoders\nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\geocoders\base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 472, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\nir3-pcLNBEA5-py3.11\Lib\site-packages\geopy\adapters.py", line 494, in _request
    raise GeocoderUnavailable(message)
geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=13-%D1%8F+%D0%BB%D0%B8%D0%BD%D0%B8%D1%8F+%D0%92%D0%9E%2C+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))
Геокодирование:  90%|████████▉ | 17958/19990 [1:08:47<2:13:48,  3.95s/it]

[17958] Геокодируем адрес: реки Каменки наб 7к2, Санкт-Петербург

Геокодирование:  90%|████████▉ | 17959/19990 [1:08:48<1:41:10,  2.99s/it]

[17959] Геокодируем адрес: nan

Геокодирование:  90%|████████▉ | 17960/19990 [1:08:49<1:19:33,  2.35s/it]

[17960] Геокодируем адрес: Туристская ул 24/42, Санкт-Петербург

Геокодирование:  90%|████████▉ | 17961/19990 [1:08:50<1:07:47,  2.00s/it]

[17961] Геокодируем адрес: nan

Геокодирование:  90%|████████▉ | 17962/19990 [1:08:51<55:36,  1.65s/it]

[17962] Геокодируем адрес: Большая Конюшенная ул, Санкт-Петербург

Геокодирование:  90%|████████▉ | 17963/19990 [1:08:52<49:08,  1.45s/it]

[17963] Геокодируем адрес: Гончарная ул, Санкт-Петербург

Геокодирование:  90%|████████▉ | 17964/19990 [1:08:53<44:22,  1.31s/it]

[17964] Геокодируем адрес: Художников пр-т 33к1литЖ, Санкт-Петербург

Геокодирование:  90%|████████▉ | 17965/19990 [1:08:54<40:42,  1.21s/it]

[17965] Геокодируем адрес: Отечественная ул 7, Санкт-Петербург

Геокодирование:  90%|████████▉ | 17966/19990 [1:08:55<39:34,  1.17s/it]

[17966] Геокодируем адрес: nan

Геокодирование:  90%|████████▉ | 17967/19990 [1:08:56<37:12,  1.10s/it]

[17967] Геокодируем адрес: Стачек пр-т 105к2, Санкт-Петербург

Геокодирование:  90%|████████▉ | 17968/19990 [1:08:57<36:49,  1.09s/it]

[17968] Геокодируем адрес: nan

Геокодирование:  90%|████████▉ | 17969/19990 [1:08:58<35:01,  1.04s/it]

[17969] Геокодируем адрес: nan

Геокодирование:  90%|████████▉ | 17970/19990 [1:08:59<34:59,  1.04s/it]

[17970] Геокодируем адрес: nan

Геокодирование:  90%|████████▉ | 17971/19990 [1:09:00<35:58,  1.07s/it]

Автосохранение после 17970 строк...
[17971] Геокодируем адрес: nan

Геокодирование:  90%|████████▉ | 17972/19990 [1:09:01<33:38,  1.00s/it]

[17972] Геокодируем адрес: nan

Геокодирование:  90%|████████▉ | 17973/19990 [1:09:02<34:00,  1.01s/it]

[17973] Геокодируем адрес: Стачек пр-т 105к1Д, Санкт-Петербург

Геокодирование:  90%|████████▉ | 17974/19990 [1:09:03<33:03,  1.02it/s]

[17974] Геокодируем адрес: Вавиловых ул 4к2, Санкт-Петербург

Геокодирование:  90%|████████▉ | 17975/19990 [1:09:04<34:41,  1.03s/it]

[17975] Геокодируем адрес: Дальневосточный пр-т, Санкт-Петербург

Геокодирование:  90%|████████▉ | 17976/19990 [1:09:05<35:32,  1.06s/it]

[17976] Геокодируем адрес: Греческий пр-т, Санкт-Петербург

Геокодирование:  90%|████████▉ | 17977/19990 [1:09:06<34:59,  1.04s/it]

[17977] Геокодируем адрес: nan

Геокодирование:  90%|████████▉ | 17978/19990 [1:09:07<32:50,  1.02it/s]

[17978] Геокодируем адрес: 6-я Советская ул 10, Санкт-Петербург

Геокодирование:  90%|████████▉ | 17979/19990 [1:09:09<46:25,  1.38s/it]

[17979] Геокодируем адрес: nan

Геокодирование:  90%|████████▉ | 17980/19990 [1:09:10<38:35,  1.15s/it]

[17980] Геокодируем адрес: Обуховской Обороны ул 33к2, Санкт-Петербург

Геокодирование:  90%|████████▉ | 17981/19990 [1:09:11<37:54,  1.13s/it]

[17981] Геокодируем адрес: Победы ул, Санкт-Петербург

Геокодирование:  90%|████████▉ | 17982/19990 [1:09:12<38:54,  1.16s/it]

[17982] Геокодируем адрес: Стойкости ул 29/1, Санкт-Петербург

Геокодирование:  90%|████████▉ | 17983/19990 [1:09:13<36:47,  1.10s/it]

[17983] Геокодируем адрес: Шелгунова ул 6к1, Санкт-Петербург

Геокодирование:  90%|████████▉ | 17984/19990 [1:09:14<33:59,  1.02s/it]

[17984] Геокодируем адрес: Южное ш 64, Санкт-Петербург

Геокодирование:  90%|████████▉ | 17985/19990 [1:09:15<34:35,  1.04s/it]

[17985] Геокодируем адрес: Солдата Корзуна ул 7, Санкт-Петербург

Геокодирование:  90%|████████▉ | 17986/19990 [1:09:16<33:16,  1.00it/s]

[17986] Геокодируем адрес: Ириновский пр-т 29к1, Санкт-Петербург

Геокодирование:  90%|████████▉ | 17987/19990 [1:09:17<33:36,  1.01s/it]

[17987] Геокодируем адрес: nan

Геокодирование:  90%|████████▉ | 17988/19990 [1:09:18<32:19,  1.03it/s]

[17988] Геокодируем адрес: Лени Голикова ул 20, Санкт-Петербург

Геокодирование:  90%|████████▉ | 17989/19990 [1:09:19<34:08,  1.02s/it]

[17989] Геокодируем адрес: nan

Геокодирование:  90%|████████▉ | 17990/19990 [1:09:20<32:21,  1.03it/s]

[17990] Геокодируем адрес: Средний ВО пр-т 7, Санкт-Петербург

Геокодирование:  90%|█████████ | 17991/19990 [1:09:21<35:49,  1.08s/it]

[17991] Геокодируем адрес: Ломоносова ул 14, Санкт-Петербург

Геокодирование:  90%|█████████ | 17992/19990 [1:09:22<37:01,  1.11s/it]

[17992] Геокодируем адрес: Пулковское ш 99, Санкт-Петербург

Геокодирование:  90%|█████████ | 17993/19990 [1:09:23<34:34,  1.04s/it]

[17993] Геокодируем адрес: Бухарестская ул 148к1Б, Санкт-Петербург

Геокодирование:  90%|█████████ | 17994/19990 [1:09:24<31:07,  1.07it/s]

[17994] Геокодируем адрес: Гудиловская ул, Санкт-Петербург

Геокодирование:  90%|█████████ | 17995/19990 [1:09:25<32:15,  1.03it/s]

[17995] Геокодируем адрес: тверская ул 39, Санкт-Петербург

Геокодирование:  90%|█████████ | 17996/19990 [1:09:26<33:19,  1.00s/it]

[17996] Геокодируем адрес: Художников пр-т 18к1, Санкт-Петербург

Геокодирование:  90%|█████████ | 17997/19990 [1:09:27<34:25,  1.04s/it]

[17997] Геокодируем адрес: Муринская дор 57, Санкт-Петербург

Геокодирование:  90%|█████████ | 17998/19990 [1:09:28<33:03,  1.00it/s]

[17998] Геокодируем адрес: Севастопольская ул 34, Санкт-Петербург

Геокодирование:  90%|█████████ | 17999/19990 [1:09:29<33:07,  1.00it/s]

[17999] Геокодируем адрес: nan

Геокодирование:  90%|█████████ | 18000/19990 [1:09:30<32:09,  1.03it/s]

[18000] Геокодируем адрес: Светлановский пр-т 61к2, Санкт-Петербург

Геокодирование:  90%|█████████ | 18001/19990 [1:09:31<34:43,  1.05s/it]

Автосохранение после 18000 строк...
[18001] Геокодируем адрес: Тверская ул 3/1, Санкт-Петербург

Геокодирование:  90%|█████████ | 18002/19990 [1:09:32<33:28,  1.01s/it]

[18002] Геокодируем адрес: Ветеранов пр-т 181, Санкт-Петербург

Геокодирование:  90%|█████████ | 18003/19990 [1:09:33<35:12,  1.06s/it]

[18003] Геокодируем адрес: Парголово Федора Абрамова ул 16к1, Санкт-Петербург

Геокодирование:  90%|█████████ | 18004/19990 [1:09:34<31:40,  1.04it/s]

[18004] Геокодируем адрес: nan

Геокодирование:  90%|█████████ | 18005/19990 [1:09:35<31:28,  1.05it/s]

[18005] Геокодируем адрес: Просвещения пр-т 43, Санкт-Петербург

Геокодирование:  90%|█████████ | 18006/19990 [1:09:36<35:02,  1.06s/it]

[18006] Геокодируем адрес: nan

Геокодирование:  90%|█████████ | 18007/19990 [1:09:37<31:10,  1.06it/s]

[18007] Геокодируем адрес: Южное ш 56, Санкт-Петербург

Геокодирование:  90%|█████████ | 18008/19990 [1:09:38<33:16,  1.01s/it]

[18008] Геокодируем адрес: Бабушкина, Санкт-Петербург

Геокодирование:  90%|█████████ | 18009/19990 [1:09:39<32:28,  1.02it/s]

[18009] Геокодируем адрес: Советский пр-т 39к1, Санкт-Петербург

Геокодирование:  90%|█████████ | 18010/19990 [1:09:40<33:06,  1.00s/it]

[18010] Геокодируем адрес: nan

Геокодирование:  90%|█████████ | 18011/19990 [1:09:42<41:42,  1.26s/it]

[18011] Геокодируем адрес: Богатырский пр-т 51к1, Санкт-Петербург

Геокодирование:  90%|█████████ | 18012/19990 [1:09:43<42:45,  1.30s/it]

[18012] Геокодируем адрес: Богатырский пр-т 51к1, Санкт-Петербург

Геокодирование:  90%|█████████ | 18013/19990 [1:09:44<37:24,  1.14s/it]

[18013] Геокодируем адрес: Гражданский пр-т 18, Санкт-Петербург

Геокодирование:  90%|█████████ | 18014/19990 [1:09:45<38:37,  1.17s/it]

[18014] Геокодируем адрес: Богатырский пр-т 51к1, Санкт-Петербург

Геокодирование:  90%|█████████ | 18015/19990 [1:09:46<35:26,  1.08s/it]

[18015] Геокодируем адрес: Зенитчиков ул, Санкт-Петербург

Геокодирование:  90%|█████████ | 18016/19990 [1:09:47<32:30,  1.01it/s]

[18016] Геокодируем адрес: Кронштадтская ул, Санкт-Петербург

Геокодирование:  90%|█████████ | 18017/19990 [1:09:48<32:46,  1.00it/s]

[18017] Геокодируем адрес: Чекистов ул 38, Санкт-Петербург

Геокодирование:  90%|█████████ | 18018/19990 [1:09:49<34:06,  1.04s/it]

[18018] Геокодируем адрес: nan

Геокодирование:  90%|█████████ | 18019/19990 [1:09:50<33:01,  1.01s/it]

[18019] Геокодируем адрес: Рябовское ш 57, Санкт-Петербург

Геокодирование:  90%|█████████ | 18020/19990 [1:09:52<44:03,  1.34s/it]

[18020] Геокодируем адрес: Тверская ул 23-25, Санкт-Петербург

Геокодирование:  90%|█████████ | 18021/19990 [1:09:53<40:38,  1.24s/it]

[18021] Геокодируем адрес: nan

Геокодирование:  90%|█████████ | 18022/19990 [1:09:54<36:01,  1.10s/it]

[18022] Геокодируем адрес: Кондратьевский пр-т 64к9, Санкт-Петербург

Геокодирование:  90%|█████████ | 18023/19990 [1:09:55<35:55,  1.10s/it]

[18023] Геокодируем адрес: Софьи Ковалевской ул 11к5, Санкт-Петербург

Геокодирование:  90%|█████████ | 18024/19990 [1:09:56<37:54,  1.16s/it]

[18024] Геокодируем адрес: Таврическая ул 5, Санкт-Петербург

Геокодирование:  90%|█████████ | 18025/19990 [1:09:57<33:32,  1.02s/it]

[18025] Геокодируем адрес: nan

Геокодирование:  90%|█████████ | 18026/19990 [1:09:58<32:34,  1.00it/s]

[18026] Геокодируем адрес: nan

Геокодирование:  90%|█████████ | 18027/19990 [1:09:59<32:55,  1.01s/it]

[18027] Геокодируем адрес: Одесская ул 2, Санкт-Петербург

Геокодирование:  90%|█████████ | 18028/19990 [1:10:00<34:39,  1.06s/it]

[18028] Геокодируем адрес: Шушары Вишерская ул 16, Санкт-Петербург

Геокодирование:  90%|█████████ | 18029/19990 [1:10:01<33:00,  1.01s/it]

[18029] Геокодируем адрес: Юнтолово, Санкт-Петербург

Геокодирование:  90%|█████████ | 18030/19990 [1:10:02<31:43,  1.03it/s]

[18030] Геокодируем адрес: nan

Геокодирование:  90%|█████████ | 18031/19990 [1:10:03<33:16,  1.02s/it]

Автосохранение после 18030 строк...
[18031] Геокодируем адрес: Солунская ул, Санкт-Петербург

Геокодирование:  90%|█████████ | 18032/19990 [1:10:04<31:55,  1.02it/s]

[18032] Геокодируем адрес: Шлиссельбургский пр-т, Санкт-Петербург

Геокодирование:  90%|█████████ | 18033/19990 [1:10:05<34:03,  1.04s/it]

[18033] Геокодируем адрес: Полевая Сабировская ул 47к1, Санкт-Петербург

Геокодирование:  90%|█████████ | 18034/19990 [1:10:06<32:17,  1.01it/s]

[18034] Геокодируем адрес: Богатырский пр-т 51к1, Санкт-Петербург

Геокодирование:  90%|█████████ | 18035/19990 [1:10:07<33:17,  1.02s/it]

[18035] Геокодируем адрес: Ропшинское ш 3к9, Санкт-Петербург

Геокодирование:  90%|█████████ | 18036/19990 [1:10:08<33:07,  1.02s/it]

[18036] Геокодируем адрес: Ропшинское ш 3к8, Санкт-Петербург

Геокодирование:  90%|█████████ | 18037/19990 [1:10:09<32:18,  1.01it/s]

[18037] Геокодируем адрес: Масляный канал, Санкт-Петербург

Геокодирование:  90%|█████████ | 18038/19990 [1:10:10<31:40,  1.03it/s]

[18038] Геокодируем адрес: Петергоф Ропшинское ш 3к8, Санкт-Петербург

Геокодирование:  90%|█████████ | 18039/19990 [1:10:11<32:31,  1.00s/it]

[18039] Геокодируем адрес: Сестрорецк Приморское ш 336, Санкт-Петербург

Геокодирование:  90%|█████████ | 18040/19990 [1:10:13<43:45,  1.35s/it]

[18040] Геокодируем адрес: Бабушкина ул 89к2, Санкт-Петербург

Геокодирование:  90%|█████████ | 18041/19990 [1:10:14<39:10,  1.21s/it]

[18041] Геокодируем адрес: Обуховской Обороны пр-т 287к1, Санкт-Петербург

Геокодирование:  90%|█████████ | 18042/19990 [1:10:15<38:26,  1.18s/it]

[18042] Геокодируем адрес: Дальневосточный пр-т, Санкт-Петербург

Геокодирование:  90%|█████████ | 18043/19990 [1:10:16<37:40,  1.16s/it]

[18043] Геокодируем адрес: СУздальский пр-т 11, Санкт-Петербург

Геокодирование:  90%|█████████ | 18044/19990 [1:10:17<35:56,  1.11s/it]

[18044] Геокодируем адрес: Жукова ул 23, Санкт-Петербург

Геокодирование:  90%|█████████ | 18045/19990 [1:10:18<35:02,  1.08s/it]

[18045] Геокодируем адрес: Маршала Жукова пр-т, Санкт-Петербург

Геокодирование:  90%|█████████ | 18046/19990 [1:10:19<33:45,  1.04s/it]

[18046] Геокодируем адрес: Красносельское ш, Санкт-Петербург

Геокодирование:  90%|█████████ | 18047/19990 [1:10:20<31:17,  1.04it/s]

[18047] Геокодируем адрес: Курьерский пр-д, Санкт-Петербург

Геокодирование:  90%|█████████ | 18048/19990 [1:10:21<34:19,  1.06s/it]

[18048] Геокодируем адрес: Комендантский пр-т, Санкт-Петербург

Геокодирование:  90%|█████████ | 18049/19990 [1:10:23<36:06,  1.12s/it]

[18049] Геокодируем адрес: Большой пр-т 62, Санкт-Петербург

Геокодирование:  90%|█████████ | 18050/19990 [1:10:24<37:00,  1.14s/it]

[18050] Геокодируем адрес: Дибуновская ул, Санкт-Петербург

Геокодирование:  90%|█████████ | 18051/19990 [1:10:25<32:31,  1.01s/it]

[18051] Геокодируем адрес: реки Мойкина наб, Санкт-Петербург

Геокодирование:  90%|█████████ | 18052/19990 [1:10:26<32:49,  1.02s/it]

[18052] Геокодируем адрес: Лиговский пр-т 114г, Санкт-Петербург

Геокодирование:  90%|█████████ | 18053/19990 [1:10:27<33:26,  1.04s/it]

[18053] Геокодируем адрес: Синопская наб 32/35, Санкт-Петербург

Геокодирование:  90%|█████████ | 18054/19990 [1:10:28<31:59,  1.01it/s]

[18054] Геокодируем адрес: Синопская наб 32/35, Санкт-Петербург

Геокодирование:  90%|█████████ | 18055/19990 [1:10:29<32:10,  1.00it/s]

[18055] Геокодируем адрес: Конная ул 20/6, Санкт-Петербург

Геокодирование:  90%|█████████ | 18056/19990 [1:10:30<32:40,  1.01s/it]

[18056] Геокодируем адрес: Фурштатская ул 7-9, Санкт-Петербург

Геокодирование:  90%|█████████ | 18057/19990 [1:10:31<32:40,  1.01s/it]

[18057] Геокодируем адрес: Зины Портновой ул 25к1, Санкт-Петербург

Геокодирование:  90%|█████████ | 18058/19990 [1:10:32<31:44,  1.01it/s]

[18058] Геокодируем адрес: Турку ул, Санкт-Петербург

Геокодирование:  90%|█████████ | 18059/19990 [1:10:33<31:46,  1.01it/s]

[18059] Геокодируем адрес: Пражская ул 12к2, Санкт-Петербург

Геокодирование:  90%|█████████ | 18060/19990 [1:10:34<31:43,  1.01it/s]

[18060] Геокодируем адрес: Пулковская ул 10к2, Санкт-Петербург

Геокодирование:  90%|█████████ | 18061/19990 [1:10:35<33:31,  1.04s/it]

Автосохранение после 18060 строк...
[18061] Геокодируем адрес: Среднерогатская ул 20, Санкт-Петербург

Геокодирование:  90%|█████████ | 18062/19990 [1:10:36<31:10,  1.03it/s]

[18062] Геокодируем адрес: Альпийский пер 13к1, Санкт-Петербург

Геокодирование:  90%|█████████ | 18063/19990 [1:10:37<32:38,  1.02s/it]

[18063] Геокодируем адрес: Альпийский пер 13к1, Санкт-Петербург

Геокодирование:  90%|█████████ | 18064/19990 [1:10:38<31:37,  1.02it/s]

[18064] Геокодируем адрес: Шаврова ул, Санкт-Петербург

Геокодирование:  90%|█████████ | 18065/19990 [1:10:39<31:34,  1.02it/s]

[18065] Геокодируем адрес: Петергоф Ропшинское пр-т 3к9, Санкт-Петербург

Геокодирование:  90%|█████████ | 18066/19990 [1:10:40<33:06,  1.03s/it]

[18066] Геокодируем адрес: Петергоф Ропшинское пр-т 3к8, Санкт-Петербург

Геокодирование:  90%|█████████ | 18067/19990 [1:10:41<31:44,  1.01it/s]

[18067] Геокодируем адрес: Петергоф Ропшинское пр-т 3к8, Санкт-Петербург

Геокодирование:  90%|█████████ | 18068/19990 [1:10:42<31:57,  1.00it/s]

[18068] Геокодируем адрес: Петергоф Ропшинское пр-т 3к8, Санкт-Петербург

Геокодирование:  90%|█████████ | 18069/19990 [1:10:43<33:23,  1.04s/it]

[18069] Геокодируем адрес: Петергоф Ропшинское пр-т 3к8, Санкт-Петербург

Геокодирование:  90%|█████████ | 18070/19990 [1:10:44<32:52,  1.03s/it]

[18070] Геокодируем адрес: Петергоф Ропшинское пр-т 3к8, Санкт-Петербург

Геокодирование:  90%|█████████ | 18071/19990 [1:10:45<32:00,  1.00s/it]

[18071] Геокодируем адрес: Петергоф Ропшинское пр-т 3к8, Санкт-Петербург

Геокодирование:  90%|█████████ | 18072/19990 [1:10:46<31:56,  1.00it/s]

[18072] Геокодируем адрес: реки Карповки наб 22, Санкт-Петербург

Геокодирование:  90%|█████████ | 18073/19990 [1:10:47<31:40,  1.01it/s]

[18073] Геокодируем адрес: Пионерстроя ул 27, Санкт-Петербург

Геокодирование:  90%|█████████ | 18074/19990 [1:10:48<31:01,  1.03it/s]

[18074] Геокодируем адрес: Ветеранов пр-т 122, Санкт-Петербург

Геокодирование:  90%|█████████ | 18075/19990 [1:10:49<34:08,  1.07s/it]

[18075] Геокодируем адрес: Культуры пр-т 29к4, Санкт-Петербург

Геокодирование:  90%|█████████ | 18076/19990 [1:10:50<31:17,  1.02it/s]

[18076] Геокодируем адрес: Парголово Заречная ул 17, Санкт-Петербург

Геокодирование:  90%|█████████ | 18077/19990 [1:10:51<31:29,  1.01it/s]

[18077] Геокодируем адрес: Красное Село, Санкт-Петербург

Геокодирование:  90%|█████████ | 18078/19990 [1:10:52<30:04,  1.06it/s]

[18078] Геокодируем адрес: Красное Село, Санкт-Петербург

Геокодирование:  90%|█████████ | 18079/19990 [1:10:53<30:29,  1.04it/s]

[18079] Геокодируем адрес: Военная ул, Санкт-Петербург

Геокодирование:  90%|█████████ | 18080/19990 [1:10:54<31:12,  1.02it/s]

[18080] Геокодируем адрес: nan

Геокодирование:  90%|█████████ | 18081/19990 [1:10:55<31:02,  1.03it/s]

[18081] Геокодируем адрес: Ропшинское ш, Санкт-Петербург

Геокодирование:  90%|█████████ | 18082/19990 [1:10:56<31:38,  1.00it/s]

[18082] Геокодируем адрес: Пролетарская ул 77, Санкт-Петербург

Геокодирование:  90%|█████████ | 18083/19990 [1:10:57<34:05,  1.07s/it]

[18083] Геокодируем адрес: Будапештская ул 98к3, Санкт-Петербург

Геокодирование:  90%|█████████ | 18084/19990 [1:10:58<32:56,  1.04s/it]

[18084] Геокодируем адрес: nan

Геокодирование:  90%|█████████ | 18085/19990 [1:10:59<30:25,  1.04it/s]

[18085] Геокодируем адрес: nan

Геокодирование:  90%|█████████ | 18086/19990 [1:11:00<30:58,  1.02it/s]

[18086] Геокодируем адрес: nan

Геокодирование:  90%|█████████ | 18087/19990 [1:11:01<30:53,  1.03it/s]

[18087] Геокодируем адрес: Пятилеток ул 14, Санкт-Петербург

Геокодирование:  90%|█████████ | 18088/19990 [1:11:02<33:51,  1.07s/it]

[18088] Геокодируем адрес: nan

Геокодирование:  90%|█████████ | 18089/19990 [1:11:03<30:50,  1.03it/s]

[18089] Геокодируем адрес: nan

Геокодирование:  90%|█████████ | 18090/19990 [1:11:04<31:09,  1.02it/s]

[18090] Геокодируем адрес: Шушары, Санкт-Петербург

Геокодирование:  91%|█████████ | 18091/19990 [1:11:05<32:34,  1.03s/it]

Автосохранение после 18090 строк...
[18091] Геокодируем адрес: Шушары Ростовская ул 14к1, Санкт-Петербург

Геокодирование:  91%|█████████ | 18092/19990 [1:11:06<36:18,  1.15s/it]

[18092] Геокодируем адрес: Товарищеский пр-т 2к1, Санкт-Петербург

Геокодирование:  91%|█████████ | 18093/19990 [1:11:07<32:17,  1.02s/it]

[18093] Геокодируем адрес: ПО 106, Санкт-Петербург

Геокодирование:  91%|█████████ | 18094/19990 [1:11:08<33:53,  1.07s/it]

[18094] Геокодируем адрес: Софийская ул 23к2, Санкт-Петербург

Геокодирование:  91%|█████████ | 18095/19990 [1:11:09<31:25,  1.01it/s]

[18095] Геокодируем адрес: Ветеранов пр-т 108к1, Санкт-Петербург

Геокодирование:  91%|█████████ | 18096/19990 [1:11:10<31:11,  1.01it/s]

[18096] Геокодируем адрес: Стачек пр-т 17, Санкт-Петербург

Геокодирование:  91%|█████████ | 18097/19990 [1:11:11<33:29,  1.06s/it]

[18097] Геокодируем адрес: Таврический сад, Санкт-Петербург

Геокодирование:  91%|█████████ | 18098/19990 [1:11:12<31:09,  1.01it/s]

[18098] Геокодируем адрес: Ушаковская наб 5, Санкт-Петербург

Геокодирование:  91%|█████████ | 18099/19990 [1:11:13<30:23,  1.04it/s]

[18099] Геокодируем адрес: Роменская ул 5, Санкт-Петербург

Геокодирование:  91%|█████████ | 18100/19990 [1:11:14<31:34,  1.00s/it]

[18100] Геокодируем адрес: Ропшинское ш 3к7, Санкт-Петербург

Геокодирование:  91%|█████████ | 18101/19990 [1:11:15<31:42,  1.01s/it]

[18101] Геокодируем адрес: Партизана Германа ул 20, Санкт-Петербург

Геокодирование:  91%|█████████ | 18102/19990 [1:11:16<31:59,  1.02s/it]

[18102] Геокодируем адрес: Воронцовский сквер, Санкт-Петербург

Геокодирование:  91%|█████████ | 18103/19990 [1:11:17<29:51,  1.05it/s]

[18103] Геокодируем адрес: Юрия Гагарина пр-т 63к3, Санкт-Петербург

Геокодирование:  91%|█████████ | 18104/19990 [1:11:18<31:24,  1.00it/s]

[18104] Геокодируем адрес: Гатчинская ул, Санкт-Петербург

Геокодирование:  91%|█████████ | 18105/19990 [1:11:19<31:01,  1.01it/s]

[18105] Геокодируем адрес: Петровский пр-т 24к3, Санкт-Петербург

Геокодирование:  91%|█████████ | 18106/19990 [1:11:20<31:37,  1.01s/it]

[18106] Геокодируем адрес: Каменноостровский пр-т 26-28, Санкт-Петербург

Геокодирование:  91%|█████████ | 18107/19990 [1:11:21<33:23,  1.06s/it]

[18107] Геокодируем адрес: Революции ш 84/3, Санкт-Петербург

Геокодирование:  91%|█████████ | 18108/19990 [1:11:22<32:48,  1.05s/it]

[18108] Геокодируем адрес: Большая Монетная ул, Санкт-Петербург

Геокодирование:  91%|█████████ | 18109/19990 [1:11:23<29:40,  1.06it/s]

[18109] Геокодируем адрес: nan

Геокодирование:  91%|█████████ | 18110/19990 [1:11:24<29:41,  1.06it/s]

[18110] Геокодируем адрес: Партизана Германа ул, Санкт-Петербург

Геокодирование:  91%|█████████ | 18111/19990 [1:11:25<31:02,  1.01it/s]

[18111] Геокодируем адрес: nan

Геокодирование:  91%|█████████ | 18112/19990 [1:11:26<30:39,  1.02it/s]

[18112] Геокодируем адрес: nan

Геокодирование:  91%|█████████ | 18113/19990 [1:11:27<30:27,  1.03it/s]

[18113] Геокодируем адрес: nan

Геокодирование:  91%|█████████ | 18114/19990 [1:11:28<30:41,  1.02it/s]

[18114] Геокодируем адрес: Петергоф Ропшинское ш 3к7, Санкт-Петербург

Геокодирование:  91%|█████████ | 18115/19990 [1:11:29<32:14,  1.03s/it]

[18115] Геокодируем адрес: nan

Геокодирование:  91%|█████████ | 18116/19990 [1:11:30<30:24,  1.03it/s]

[18116] Геокодируем адрес: Южное ш 47к3, Санкт-Петербург

Геокодирование:  91%|█████████ | 18117/19990 [1:11:31<31:04,  1.00it/s]

[18117] Геокодируем адрес: Вербная ул 17к1, Санкт-Петербург

Геокодирование:  91%|█████████ | 18118/19990 [1:11:32<31:47,  1.02s/it]

[18118] Геокодируем адрес: Красное Село Стрельнинское ш, Санкт-Петербург

Геокодирование:  91%|█████████ | 18119/19990 [1:11:33<32:20,  1.04s/it]

[18119] Геокодируем адрес: Коллонтай ул 4к1, Санкт-Петербург

Геокодирование:  91%|█████████ | 18120/19990 [1:11:34<32:41,  1.05s/it]

[18120] Геокодируем адрес: Стасовой ул 2, Санкт-Петербург

Геокодирование:  91%|█████████ | 18121/19990 [1:11:35<33:03,  1.06s/it]

Автосохранение после 18120 строк...
[18121] Геокодируем адрес: Суздальский пр-т, Санкт-Петербург

Геокодирование:  91%|█████████ | 18122/19990 [1:11:36<32:05,  1.03s/it]

[18122] Геокодируем адрес: nan

Геокодирование:  91%|█████████ | 18123/19990 [1:11:37<29:25,  1.06it/s]

[18123] Геокодируем адрес: Старорусская ул 3, Санкт-Петербург

Геокодирование:  91%|█████████ | 18124/19990 [1:11:38<30:24,  1.02it/s]

[18124] Геокодируем адрес: Шушары Окуловская ул 4, Санкт-Петербург

Геокодирование:  91%|█████████ | 18125/19990 [1:11:39<30:24,  1.02it/s]

[18125] Геокодируем адрес: Авиаторов сквер, Санкт-Петербург

Геокодирование:  91%|█████████ | 18126/19990 [1:11:40<30:14,  1.03it/s]

[18126] Геокодируем адрес: Шушары Окуловская ул 4, Санкт-Петербург

Геокодирование:  91%|█████████ | 18127/19990 [1:11:41<32:32,  1.05s/it]

[18127] Геокодируем адрес: Петергоф Ропшинское ш 3к8, Санкт-Петербург

Геокодирование:  91%|█████████ | 18128/19990 [1:11:42<30:50,  1.01it/s]

[18128] Геокодируем адрес: Ветеранов пр-т 56, Санкт-Петербург

Геокодирование:  91%|█████████ | 18129/19990 [1:11:43<33:00,  1.06s/it]

[18129] Геокодируем адрес: Петергоф Ропшинское ш 3к8, Санкт-Петербург

Геокодирование:  91%|█████████ | 18130/19990 [1:11:44<30:35,  1.01it/s]

[18130] Геокодируем адрес: Красногвардейская пл 4, Санкт-Петербург

Геокодирование:  91%|█████████ | 18131/19990 [1:11:45<30:15,  1.02it/s]

[18131] Геокодируем адрес: Маршака пр-т 14к2, Санкт-Петербург

Геокодирование:  91%|█████████ | 18132/19990 [1:11:46<30:29,  1.02it/s]

[18132] Геокодируем адрес: Меншиковский пр-т 19, Санкт-Петербург

Геокодирование:  91%|█████████ | 18133/19990 [1:11:47<31:36,  1.02s/it]

[18133] Геокодируем адрес: Партизана Германа ул 20, Санкт-Петербург

Геокодирование:  91%|█████████ | 18134/19990 [1:11:48<30:28,  1.02it/s]

[18134] Геокодируем адрес: Авиаторов сквер, Санкт-Петербург

Геокодирование:  91%|█████████ | 18135/19990 [1:11:49<29:52,  1.03it/s]

[18135] Геокодируем адрес: nan

Геокодирование:  91%|█████████ | 18136/19990 [1:11:50<29:51,  1.03it/s]

[18136] Геокодируем адрес: nan

Геокодирование:  91%|█████████ | 18137/19990 [1:11:51<29:51,  1.03it/s]

[18137] Геокодируем адрес: Будапештская ул 108к2, Санкт-Петербург

Геокодирование:  91%|█████████ | 18138/19990 [1:11:52<30:55,  1.00s/it]

[18138] Геокодируем адрес: Александра Невского ул 9Г, Санкт-Петербург

Геокодирование:  91%|█████████ | 18139/19990 [1:11:53<31:49,  1.03s/it]

[18139] Геокодируем адрес: nan

Геокодирование:  91%|█████████ | 18140/19990 [1:11:54<29:47,  1.03it/s]

[18140] Геокодируем адрес: nan

Геокодирование:  91%|█████████ | 18141/19990 [1:11:55<29:56,  1.03it/s]

[18141] Геокодируем адрес: nan

Геокодирование:  91%|█████████ | 18142/19990 [1:11:56<30:19,  1.02it/s]

[18142] Геокодируем адрес: Подвойского ул 24к2, Санкт-Петербург

Геокодирование:  91%|█████████ | 18143/19990 [1:11:57<30:59,  1.01s/it]

[18143] Геокодируем адрес: Обводного канала наб 118к3, Санкт-Петербург

Геокодирование:  91%|█████████ | 18144/19990 [1:11:58<31:20,  1.02s/it]

[18144] Геокодируем адрес: nan

Геокодирование:  91%|█████████ | 18145/19990 [1:11:59<30:32,  1.01it/s]

[18145] Геокодируем адрес: nan

Геокодирование:  91%|█████████ | 18146/19990 [1:12:00<30:31,  1.01it/s]

[18146] Геокодируем адрес: Петергоф Ропшинское ш 3к8, Санкт-Петербург

Геокодирование:  91%|█████████ | 18147/19990 [1:12:01<31:25,  1.02s/it]

[18147] Геокодируем адрес: Петергоф Ропшинское ш 3к8, Санкт-Петербург

Геокодирование:  91%|█████████ | 18148/19990 [1:12:02<31:49,  1.04s/it]

[18148] Геокодируем адрес: Петергоф Ропшинское ш 3к8, Санкт-Петербург

Геокодирование:  91%|█████████ | 18149/19990 [1:12:03<31:22,  1.02s/it]

[18149] Геокодируем адрес: Петергоф Ропшинское ш 3к8, Санкт-Петербург

Геокодирование:  91%|█████████ | 18150/19990 [1:12:04<30:49,  1.00s/it]

[18150] Геокодируем адрес: Сестрорецк Володарского ул 24, Санкт-Петербург

Геокодирование:  91%|█████████ | 18151/19990 [1:12:05<31:49,  1.04s/it]

Автосохранение после 18150 строк...
[18151] Геокодируем адрес: Петергоф Ропшинское ш 3к8, Санкт-Петербург

Геокодирование:  91%|█████████ | 18152/19990 [1:12:06<30:19,  1.01it/s]

[18152] Геокодируем адрес: nan

Геокодирование:  91%|█████████ | 18153/19990 [1:12:07<29:16,  1.05it/s]

[18153] Геокодируем адрес: Полевая Сабировская ул 47к1, Санкт-Петербург

Геокодирование:  91%|█████████ | 18154/19990 [1:12:08<30:27,  1.00it/s]

[18154] Геокодируем адрес: nan

Геокодирование:  91%|█████████ | 18155/19990 [1:12:09<29:47,  1.03it/s]

[18155] Геокодируем адрес: Полевая Сабировская ул 47к1, Санкт-Петербург

Геокодирование:  91%|█████████ | 18156/19990 [1:12:10<30:14,  1.01it/s]

[18156] Геокодируем адрес: Большая Зеленина ул 28, Санкт-Петербург

Геокодирование:  91%|█████████ | 18157/19990 [1:12:11<31:08,  1.02s/it]

[18157] Геокодируем адрес: Полевая Сабировская ул 47к1, Санкт-Петербург

Геокодирование:  91%|█████████ | 18158/19990 [1:12:12<30:22,  1.01it/s]

[18158] Геокодируем адрес: Стачек пр-т, Санкт-Петербург

Геокодирование:  91%|█████████ | 18159/19990 [1:12:13<30:54,  1.01s/it]

[18159] Геокодируем адрес: Автовская ул 28, Санкт-Петербург

Геокодирование:  91%|█████████ | 18160/19990 [1:12:14<30:45,  1.01s/it]

[18160] Геокодируем адрес: nan

Геокодирование:  91%|█████████ | 18161/19990 [1:12:15<29:42,  1.03it/s]

[18161] Геокодируем адрес: Петро-Славянка Софийская, Санкт-Петербург

Геокодирование:  91%|█████████ | 18162/19990 [1:12:16<30:50,  1.01s/it]

[18162] Геокодируем адрес: Павловск Грушевая ул, Санкт-Петербург

Геокодирование:  91%|█████████ | 18163/19990 [1:12:17<29:46,  1.02it/s]

[18163] Геокодируем адрес: nan

Геокодирование:  91%|█████████ | 18164/19990 [1:12:18<29:39,  1.03it/s]

[18164] Геокодируем адрес: Ленинский пр-т 129к4, Санкт-Петербург

Геокодирование:  91%|█████████ | 18165/19990 [1:12:19<30:46,  1.01s/it]

[18165] Геокодируем адрес: nan

Геокодирование:  91%|█████████ | 18166/19990 [1:12:20<30:23,  1.00it/s]

[18166] Геокодируем адрес: Поварской пер 9, Санкт-Петербург

Геокодирование:  91%|█████████ | 18167/19990 [1:12:21<31:18,  1.03s/it]

[18167] Геокодируем адрес: Маяковского ул, Санкт-Петербург

Геокодирование:  91%|█████████ | 18168/19990 [1:12:22<31:05,  1.02s/it]

[18168] Геокодируем адрес: Комендантский пр-т 61, Санкт-Петербург

Геокодирование:  91%|█████████ | 18169/19990 [1:12:23<31:11,  1.03s/it]

[18169] Геокодируем адрес: Исполкомская ул 16, Санкт-Петербург

Геокодирование:  91%|█████████ | 18170/19990 [1:12:24<29:55,  1.01it/s]

[18170] Геокодируем адрес: Европы пл, Санкт-Петербург

Геокодирование:  91%|█████████ | 18171/19990 [1:12:25<29:09,  1.04it/s]

[18171] Геокодируем адрес: Павловск Грушевая ул, Санкт-Петербург

Геокодирование:  91%|█████████ | 18172/19990 [1:12:26<30:19,  1.00s/it]

[18172] Геокодируем адрес: Шушары Витебский пр-т, Санкт-Петербург

Геокодирование:  91%|█████████ | 18173/19990 [1:12:27<30:26,  1.01s/it]

[18173] Геокодируем адрес: nan

Геокодирование:  91%|█████████ | 18174/19990 [1:12:28<29:27,  1.03it/s]

[18174] Геокодируем адрес: Союза Печатников ул 8, Санкт-Петербург

Геокодирование:  91%|█████████ | 18175/19990 [1:12:29<30:58,  1.02s/it]

[18175] Геокодируем адрес: Павловск Грушевая ул, Санкт-Петербург

Геокодирование:  91%|█████████ | 18176/19990 [1:12:30<29:53,  1.01it/s]

[18176] Геокодируем адрес: Большая Зеленина ул 2, Санкт-Петербург

Геокодирование:  91%|█████████ | 18177/19990 [1:12:31<30:30,  1.01s/it]

[18177] Геокодируем адрес: Союза Печатников ул 8, Санкт-Петербург

Геокодирование:  91%|█████████ | 18178/19990 [1:12:32<30:05,  1.00it/s]

[18178] Геокодируем адрес: Подъездной пер 4, Санкт-Петербург

Геокодирование:  91%|█████████ | 18179/19990 [1:12:33<29:47,  1.01it/s]

[18179] Геокодируем адрес: nan

Геокодирование:  91%|█████████ | 18180/19990 [1:12:34<29:25,  1.02it/s]

[18180] Геокодируем адрес: Лиговский пр-т 117, Санкт-Петербург

Геокодирование:  91%|█████████ | 18181/19990 [1:12:35<34:12,  1.13s/it]

Автосохранение после 18180 строк...
[18181] Геокодируем адрес: Елецкая ул, Санкт-Петербург

Геокодирование:  91%|█████████ | 18182/19990 [1:12:36<29:32,  1.02it/s]

[18182] Геокодируем адрес: Пушкин Красной Звезды ул 17/9, Санкт-Петербург

Геокодирование:  91%|█████████ | 18183/19990 [1:12:37<33:20,  1.11s/it]

[18183] Геокодируем адрес: Камчатская ул, Санкт-Петербург

Геокодирование:  91%|█████████ | 18184/19990 [1:12:38<28:47,  1.05it/s]

[18184] Геокодируем адрес: Репищева ул, Санкт-Петербург

Геокодирование:  91%|█████████ | 18185/19990 [1:12:39<29:18,  1.03it/s]

[18185] Геокодируем адрес: Пушкин Красносельское ш, Санкт-Петербург

Геокодирование:  91%|█████████ | 18186/19990 [1:12:40<29:30,  1.02it/s]

[18186] Геокодируем адрес: Энгельса пр-т, Санкт-Петербург

Геокодирование:  91%|█████████ | 18187/19990 [1:12:41<32:07,  1.07s/it]

[18187] Геокодируем адрес: Муринская дор, Санкт-Петербург

Геокодирование:  91%|█████████ | 18188/19990 [1:12:42<28:56,  1.04it/s]

[18188] Геокодируем адрес: nan

Геокодирование:  91%|█████████ | 18189/19990 [1:12:43<29:04,  1.03it/s]

[18189] Геокодируем адрес: Хармса ул, Санкт-Петербург

Геокодирование:  91%|█████████ | 18190/19990 [1:12:44<29:30,  1.02it/s]

[18190] Геокодируем адрес: Пулковское ш, Санкт-Петербург

Геокодирование:  91%|█████████ | 18191/19990 [1:12:45<30:14,  1.01s/it]

[18191] Геокодируем адрес: 1-я Конная лахта ул, Санкт-Петербург

Геокодирование:  91%|█████████ | 18192/19990 [1:12:46<33:22,  1.11s/it]

[18192] Геокодируем адрес: Красносельское ш, Санкт-Петербург

Геокодирование:  91%|█████████ | 18193/19990 [1:12:48<38:52,  1.30s/it]

[18193] Геокодируем адрес: nan

Геокодирование:  91%|█████████ | 18194/19990 [1:12:49<35:38,  1.19s/it]

[18194] Геокодируем адрес: Лисий Нос Приморское ш, Санкт-Петербург

Геокодирование:  91%|█████████ | 18195/19990 [1:12:50<34:51,  1.17s/it]

[18195] Геокодируем адрес: nan

Геокодирование:  91%|█████████ | 18196/19990 [1:12:51<32:41,  1.09s/it]

[18196] Геокодируем адрес: nan

Геокодирование:  91%|█████████ | 18197/19990 [1:12:52<31:33,  1.06s/it]

[18197] Геокодируем адрес: 1-й Предпортовый пр-д, Санкт-Петербург

Геокодирование:  91%|█████████ | 18198/19990 [1:12:53<31:40,  1.06s/it]

[18198] Геокодируем адрес: Невский пр-т 39Б, Санкт-Петербург

Геокодирование:  91%|█████████ | 18199/19990 [1:12:54<32:27,  1.09s/it]

[18199] Геокодируем адрес: nan

Геокодирование:  91%|█████████ | 18200/19990 [1:12:55<29:39,  1.01it/s]

[18200] Геокодируем адрес: Малый пр-т 89, Санкт-Петербург

Геокодирование:  91%|█████████ | 18201/19990 [1:12:56<32:44,  1.10s/it]

[18201] Геокодируем адрес: Домостроительная ул, Санкт-Петербург

Геокодирование:  91%|█████████ | 18202/19990 [1:12:57<29:02,  1.03it/s]

[18202] Геокодируем адрес: Ленинский пр-т 77, Санкт-Петербург

Геокодирование:  91%|█████████ | 18203/19990 [1:12:59<41:14,  1.38s/it]

[18203] Геокодируем адрес: Земледельческая ул, Санкт-Петербург

Геокодирование:  91%|█████████ | 18204/19990 [1:13:00<34:48,  1.17s/it]

[18204] Геокодируем адрес: nan

Геокодирование:  91%|█████████ | 18205/19990 [1:13:01<33:13,  1.12s/it]

[18205] Геокодируем адрес: nan

Геокодирование:  91%|█████████ | 18206/19990 [1:13:02<32:02,  1.08s/it]

[18206] Геокодируем адрес: Муринская дор, Санкт-Петербург

Геокодирование:  91%|█████████ | 18207/19990 [1:13:03<31:43,  1.07s/it]

[18207] Геокодируем адрес: Заречная ул, Санкт-Петербург

Геокодирование:  91%|█████████ | 18208/19990 [1:13:04<32:20,  1.09s/it]

[18208] Геокодируем адрес: nan

Геокодирование:  91%|█████████ | 18209/19990 [1:13:05<29:51,  1.01s/it]

[18209] Геокодируем адрес: Жуковского ул 2, Санкт-Петербург

Геокодирование:  91%|█████████ | 18210/19990 [1:13:06<31:36,  1.07s/it]

[18210] Геокодируем адрес: Шушары Школьная ул, Санкт-Петербург

Геокодирование:  91%|█████████ | 18211/19990 [1:13:07<30:38,  1.03s/it]

Автосохранение после 18210 строк...
[18211] Геокодируем адрес: Кронштадтская ул, Санкт-Петербург

Геокодирование:  91%|█████████ | 18212/19990 [1:13:08<29:10,  1.02it/s]

[18212] Геокодируем адрес: Энгельса пр-т, Санкт-Петербург

Геокодирование:  91%|█████████ | 18213/19990 [1:13:09<30:35,  1.03s/it]

[18213] Геокодируем адрес: Савушкина ул 20, Санкт-Петербург

Геокодирование:  91%|█████████ | 18214/19990 [1:13:10<30:08,  1.02s/it]

[18214] Геокодируем адрес: nan

Геокодирование:  91%|█████████ | 18215/19990 [1:13:11<28:34,  1.03it/s]

[18215] Геокодируем адрес: Северный пр-д, Санкт-Петербург

Геокодирование:  91%|█████████ | 18216/19990 [1:13:12<30:12,  1.02s/it]

[18216] Геокодируем адрес: Краснопутиловская ул, Санкт-Петербург

Геокодирование:  91%|█████████ | 18217/19990 [1:13:13<28:43,  1.03it/s]

[18217] Геокодируем адрес: Просвещения пр-т 32к2, Санкт-Петербург

Геокодирование:  91%|█████████ | 18218/19990 [1:13:14<30:01,  1.02s/it]

[18218] Геокодируем адрес: Красное Село Ленина пр-т, Санкт-Петербург

Геокодирование:  91%|█████████ | 18219/19990 [1:13:15<31:42,  1.07s/it]

[18219] Геокодируем адрес: Серебряков пер 9, Санкт-Петербург

Геокодирование:  91%|█████████ | 18220/19990 [1:13:16<28:13,  1.05it/s]

[18220] Геокодируем адрес: Подвойского ул 20к1, Санкт-Петербург

Геокодирование:  91%|█████████ | 18221/19990 [1:13:17<29:01,  1.02it/s]

[18221] Геокодируем адрес: Реки Фонтанки наб 29/66, Санкт-Петербург

Геокодирование:  91%|█████████ | 18222/19990 [1:13:18<29:16,  1.01it/s]

[18222] Геокодируем адрес: Школьная ул 6, Санкт-Петербург

Геокодирование:  91%|█████████ | 18223/19990 [1:13:19<31:42,  1.08s/it]

[18223] Геокодируем адрес: Добролюбова пр-т, Санкт-Петербург

Геокодирование:  91%|█████████ | 18224/19990 [1:13:20<28:49,  1.02it/s]

[18224] Геокодируем адрес: Лабораторная ул, Санкт-Петербург

Геокодирование:  91%|█████████ | 18225/19990 [1:13:21<28:13,  1.04it/s]

[18225] Геокодируем адрес: Верхняя ул, Санкт-Петербург

Геокодирование:  91%|█████████ | 18226/19990 [1:13:22<28:43,  1.02it/s]

[18226] Геокодируем адрес: Металлистов пр-т 61к2, Санкт-Петербург

Геокодирование:  91%|█████████ | 18227/19990 [1:13:23<28:52,  1.02it/s]

[18227] Геокодируем адрес: Горское ш, Санкт-Петербург

Геокодирование:  91%|█████████ | 18228/19990 [1:13:24<28:49,  1.02it/s]

[18228] Геокодируем адрес: Обуховской Обороны пр-т 227к2, Санкт-Петербург

Геокодирование:  91%|█████████ | 18229/19990 [1:13:25<29:13,  1.00it/s]

[18229] Геокодируем адрес: Полевая ул, Санкт-Петербург

Геокодирование:  91%|█████████ | 18230/19990 [1:13:26<30:16,  1.03s/it]

[18230] Геокодируем адрес: северный пр-д, Санкт-Петербург

Геокодирование:  91%|█████████ | 18231/19990 [1:13:27<30:15,  1.03s/it]

[18231] Геокодируем адрес: ефремовский пр-д, Санкт-Петербург

Геокодирование:  91%|█████████ | 18232/19990 [1:13:28<29:25,  1.00s/it]

[18232] Геокодируем адрес: центральный пр-д, Санкт-Петербург

Геокодирование:  91%|█████████ | 18233/19990 [1:13:29<29:37,  1.01s/it]

[18233] Геокодируем адрес: Петрозаводское ш, Санкт-Петербург

Геокодирование:  91%|█████████ | 18234/19990 [1:13:30<28:17,  1.03it/s]

[18234] Геокодируем адрес: центральный пр-д, Санкт-Петербург

Геокодирование:  91%|█████████ | 18235/19990 [1:13:31<29:34,  1.01s/it]

[18235] Геокодируем адрес: славянский пр-д, Санкт-Петербург

Геокодирование:  91%|█████████ | 18236/19990 [1:13:32<28:47,  1.02it/s]

[18236] Геокодируем адрес: Морской пехоты ул, Санкт-Петербург

Геокодирование:  91%|█████████ | 18237/19990 [1:13:33<28:37,  1.02it/s]

[18237] Геокодируем адрес: Академика Байкова ул, Санкт-Петербург

Геокодирование:  91%|█████████ | 18238/19990 [1:13:34<29:10,  1.00it/s]

[18238] Геокодируем адрес: Академика Байкова ул 11к3, Санкт-Петербург

Геокодирование:  91%|█████████ | 18239/19990 [1:13:35<29:35,  1.01s/it]

[18239] Геокодируем адрес: nan

Геокодирование:  91%|█████████ | 18240/19990 [1:13:36<28:15,  1.03it/s]

[18240] Геокодируем адрес: Чернышевского пр-т 17, Санкт-Петербург

Геокодирование:  91%|█████████▏| 18241/19990 [1:13:38<33:31,  1.15s/it]

Автосохранение после 18240 строк...
[18241] Геокодируем адрес: Металлострой Садовая ул 6, Санкт-Петербург

Геокодирование:  91%|█████████▏| 18242/19990 [1:13:38<29:05,  1.00it/s]

[18242] Геокодируем адрес: Стеклянная ул 33, Санкт-Петербург

Геокодирование:  91%|█████████▏| 18243/19990 [1:13:39<29:09,  1.00s/it]

[18243] Геокодируем адрес: Одоевского ул, Санкт-Петербург

Геокодирование:  91%|█████████▏| 18244/19990 [1:13:40<28:53,  1.01it/s]

[18244] Геокодируем адрес: Николая Рубцова ул 5, Санкт-Петербург

Геокодирование:  91%|█████████▏| 18245/19990 [1:13:41<30:09,  1.04s/it]

[18245] Геокодируем адрес: nan

Геокодирование:  91%|█████████▏| 18246/19990 [1:13:42<28:11,  1.03it/s]

[18246] Геокодируем адрес: Краснопутиловская ул 101, Санкт-Петербург

Геокодирование:  91%|█████████▏| 18247/19990 [1:13:43<28:57,  1.00it/s]

[18247] Геокодируем адрес: Колпино Красных Партизан ул, Санкт-Петербург

Геокодирование:  91%|█████████▏| 18248/19990 [1:13:44<28:47,  1.01it/s]

[18248] Геокодируем адрес: Тихорецкий пр-т 13, Санкт-Петербург

Геокодирование:  91%|█████████▏| 18249/19990 [1:13:45<30:15,  1.04s/it]

[18249] Геокодируем адрес: 1-й Предпортовый пр-д, Санкт-Петербург

Геокодирование:  91%|█████████▏| 18250/19990 [1:13:46<28:45,  1.01it/s]

[18250] Геокодируем адрес: Лиговский пр-т 93, Санкт-Петербург

Геокодирование:  91%|█████████▏| 18251/19990 [1:13:47<29:41,  1.02s/it]

[18251] Геокодируем адрес: Большевиков пр-т 9к1, Санкт-Петербург

Геокодирование:  91%|█████████▏| 18252/19990 [1:13:48<28:21,  1.02it/s]

[18252] Геокодируем адрес: nan

Геокодирование:  91%|█████████▏| 18253/19990 [1:13:49<28:11,  1.03it/s]

[18253] Геокодируем адрес: Краснопутиловская ул 101, Санкт-Петербург

Геокодирование:  91%|█████████▏| 18254/19990 [1:13:50<28:35,  1.01it/s]

[18254] Геокодируем адрес: Шушары, Санкт-Петербург

Геокодирование:  91%|█████████▏| 18255/19990 [1:13:51<29:05,  1.01s/it]

[18255] Геокодируем адрес: 1, Санкт-Петербург

Геокодирование:  91%|█████████▏| 18256/19990 [1:13:52<29:44,  1.03s/it]

[18256] Геокодируем адрес: nan

Геокодирование:  91%|█████████▏| 18257/19990 [1:13:53<28:02,  1.03it/s]

[18257] Геокодируем адрес: nan

Геокодирование:  91%|█████████▏| 18258/19990 [1:13:54<28:15,  1.02it/s]

[18258] Геокодируем адрес: Колпино, Санкт-Петербург

Геокодирование:  91%|█████████▏| 18259/19990 [1:13:55<28:51,  1.00s/it]

[18259] Геокодируем адрес: Талалихина ул 5/15, Санкт-Петербург

Геокодирование:  91%|█████████▏| 18260/19990 [1:13:56<30:05,  1.04s/it]

[18260] Геокодируем адрес: nan

Геокодирование:  91%|█████████▏| 18261/19990 [1:13:57<28:09,  1.02it/s]

[18261] Геокодируем адрес: Народного Ополчения пр-т 145, Санкт-Петербург

Геокодирование:  91%|█████████▏| 18262/19990 [1:13:58<29:58,  1.04s/it]

[18262] Геокодируем адрес: Песочный Лесная ул, Санкт-Петербург

Геокодирование:  91%|█████████▏| 18263/19990 [1:14:00<37:09,  1.29s/it]

[18263] Геокодируем адрес: nan

Геокодирование:  91%|█████████▏| 18264/19990 [1:14:01<33:58,  1.18s/it]

[18264] Геокодируем адрес: Лидии Зверевой ул 3.2, Санкт-Петербург

Геокодирование:  91%|█████████▏| 18265/19990 [1:14:02<32:50,  1.14s/it]

[18265] Геокодируем адрес: Белорусская ул 8, Санкт-Петербург

Геокодирование:  91%|█████████▏| 18266/19990 [1:14:03<32:00,  1.11s/it]

[18266] Геокодируем адрес: Греческий пр-т 23, Санкт-Петербург

Геокодирование:  91%|█████████▏| 18267/19990 [1:14:04<31:48,  1.11s/it]

[18267] Геокодируем адрес: Бадаева ул 11, Санкт-Петербург

Геокодирование:  91%|█████████▏| 18268/19990 [1:14:05<30:19,  1.06s/it]

[18268] Геокодируем адрес: Бадаева ул 11, Санкт-Петербург

Геокодирование:  91%|█████████▏| 18269/19990 [1:14:06<29:32,  1.03s/it]

[18269] Геокодируем адрес: Ивана Зубкова ул, Санкт-Петербург

Геокодирование:  91%|█████████▏| 18270/19990 [1:14:07<28:55,  1.01s/it]

[18270] Геокодируем адрес: Школьная ул 114к2, Санкт-Петербург

Геокодирование:  91%|█████████▏| 18271/19990 [1:14:09<32:33,  1.14s/it]

Автосохранение после 18270 строк...
[18271] Геокодируем адрес: центральный пр-д, Санкт-Петербург

Геокодирование:  91%|█████████▏| 18272/19990 [1:14:09<29:09,  1.02s/it]

[18272] Геокодируем адрес: Будапештская ул 106к2, Санкт-Петербург

Геокодирование:  91%|█████████▏| 18273/19990 [1:14:10<28:11,  1.02it/s]

[18273] Геокодируем адрес: nan

Геокодирование:  91%|█████████▏| 18274/19990 [1:14:11<27:41,  1.03it/s]

[18274] Геокодируем адрес: 7-я Советская ул 4, Санкт-Петербург

Геокодирование:  91%|█████████▏| 18275/19990 [1:14:12<30:00,  1.05s/it]

[18275] Геокодируем адрес: nan

Геокодирование:  91%|█████████▏| 18276/19990 [1:14:13<27:29,  1.04it/s]

[18276] Геокодируем адрес: 10-я Советская ул 9, Санкт-Петербург

Геокодирование:  91%|█████████▏| 18277/19990 [1:14:14<30:09,  1.06s/it]

[18277] Геокодируем адрес: Космонавтов пр-т 82, Санкт-Петербург

Геокодирование:  91%|█████████▏| 18278/19990 [1:14:16<30:37,  1.07s/it]

[18278] Геокодируем адрес: Фурштатская ул 42, Санкт-Петербург

Геокодирование:  91%|█████████▏| 18279/19990 [1:14:16<27:19,  1.04it/s]

[18279] Геокодируем адрес: nan

Геокодирование:  91%|█████████▏| 18280/19990 [1:14:17<26:55,  1.06it/s]

[18280] Геокодируем адрес: Большеохтинский пр-т 11к1, Санкт-Петербург

Геокодирование:  91%|█████████▏| 18281/19990 [1:14:18<28:33,  1.00s/it]

[18281] Геокодируем адрес: nan

Геокодирование:  91%|█████████▏| 18282/19990 [1:14:19<27:26,  1.04it/s]

[18282] Геокодируем адрес: 17-я линия ВО 20, Санкт-Петербург

Геокодирование:  91%|█████████▏| 18283/19990 [1:14:20<29:25,  1.03s/it]

[18283] Геокодируем адрес: Кронштадт Советская ул 31, Санкт-Петербург

Геокодирование:  91%|█████████▏| 18284/19990 [1:14:21<28:29,  1.00s/it]

[18284] Геокодируем адрес: Варшавская ул 37к1, Санкт-Петербург

Геокодирование:  91%|█████████▏| 18285/19990 [1:14:22<27:48,  1.02it/s]

[18285] Геокодируем адрес: Пушкин Петербургское ш 9, Санкт-Петербург

Геокодирование:  91%|█████████▏| 18286/19990 [1:14:23<29:47,  1.05s/it]

[18286] Геокодируем адрес: Варфоломеевская ул 15, Санкт-Петербург

Геокодирование:  91%|█████████▏| 18287/19990 [1:14:24<27:36,  1.03it/s]

[18287] Геокодируем адрес: Лиговский пр-т 271, Санкт-Петербург

Геокодирование:  91%|█████████▏| 18288/19990 [1:14:25<29:48,  1.05s/it]

[18288] Геокодируем адрес: Оптиков ул 52к1, Санкт-Петербург

Геокодирование:  91%|█████████▏| 18289/19990 [1:14:26<27:16,  1.04it/s]

[18289] Геокодируем адрес: Савушкина ул, Санкт-Петербург

Геокодирование:  91%|█████████▏| 18290/19990 [1:14:27<27:35,  1.03it/s]

[18290] Геокодируем адрес: Шушары Вишерская ул 2, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18291/19990 [1:14:28<28:14,  1.00it/s]

[18291] Геокодируем адрес: Лиговский пр-т 71, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18292/19990 [1:14:29<29:26,  1.04s/it]

[18292] Геокодируем адрес: Софьи Ковалевской ул 11к3, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18293/19990 [1:14:30<27:42,  1.02it/s]

[18293] Геокодируем адрес: Карпинского ул 34к6, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18294/19990 [1:14:31<27:54,  1.01it/s]

[18294] Геокодируем адрес: 21-я линия ВО 16, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18295/19990 [1:14:32<29:48,  1.06s/it]

[18295] Геокодируем адрес: Таврическая ул 45, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18296/19990 [1:14:33<27:26,  1.03it/s]

[18296] Геокодируем адрес: Народного ополчения пр-т 143, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18297/19990 [1:14:34<29:37,  1.05s/it]

[18297] Геокодируем адрес: Захарьевская ул 1, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18298/19990 [1:14:35<27:04,  1.04it/s]

[18298] Геокодируем адрес: 2-я линия ВО, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18299/19990 [1:14:38<39:47,  1.41s/it]

[18299] Геокодируем адрес: Стачек пр-т 59к2, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18300/19990 [1:14:38<33:08,  1.18s/it]

[18300] Геокодируем адрес: nan

Геокодирование:  92%|█████████▏| 18301/19990 [1:14:39<32:31,  1.16s/it]

Автосохранение после 18300 строк...
[18301] Геокодируем адрес: Энгельса пр-т, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18302/19990 [1:14:40<31:10,  1.11s/it]

[18302] Геокодируем адрес: Рентгена ул, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18303/19990 [1:14:41<29:12,  1.04s/it]

[18303] Геокодируем адрес: Малая Бухарестская ул 10к2, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18304/19990 [1:14:42<29:14,  1.04s/it]

[18304] Геокодируем адрес: 17-я линия ВО 20, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18305/19990 [1:14:44<30:11,  1.08s/it]

[18305] Геокодируем адрес: Белградская ул 46, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18306/19990 [1:14:44<28:13,  1.01s/it]

[18306] Геокодируем адрес: Королева пр-т 64к1, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18307/19990 [1:14:45<28:09,  1.00s/it]

[18307] Геокодируем адрес: nan

Геокодирование:  92%|█████████▏| 18308/19990 [1:14:46<27:53,  1.01it/s]

[18308] Геокодируем адрес: Большой пр-т 74, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18309/19990 [1:14:48<31:39,  1.13s/it]

[18309] Геокодируем адрес: Шушары Вишерская ул 2стр1, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18310/19990 [1:14:48<27:25,  1.02it/s]

[18310] Геокодируем адрес: nan

Геокодирование:  92%|█████████▏| 18311/19990 [1:14:49<27:08,  1.03it/s]

[18311] Геокодируем адрес: Карпинского ул 34к6, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18312/19990 [1:14:50<28:11,  1.01s/it]

[18312] Геокодируем адрес: nan

Геокодирование:  92%|█████████▏| 18313/19990 [1:14:51<27:18,  1.02it/s]

[18313] Геокодируем адрес: Кубинская ул 30, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18314/19990 [1:14:52<28:04,  1.01s/it]

[18314] Геокодируем адрес: Колпино Ижорского Батальона ул 7, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18315/19990 [1:14:54<28:45,  1.03s/it]

[18315] Геокодируем адрес: Шушары Школьная ул 15стр1, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18316/19990 [1:14:54<27:29,  1.01it/s]

[18316] Геокодируем адрес: Днепропетровская ул 63Б, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18317/19990 [1:14:56<28:29,  1.02s/it]

[18317] Геокодируем адрес: Советский пр-т 43к1, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18318/19990 [1:14:57<28:42,  1.03s/it]

[18318] Геокодируем адрес: Большая Посадская ул 10, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18319/19990 [1:14:57<27:37,  1.01it/s]

[18319] Геокодируем адрес: nan

Геокодирование:  92%|█████████▏| 18320/19990 [1:14:58<26:51,  1.04it/s]

[18320] Геокодируем адрес: имени 30-летия Октября сад, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18321/19990 [1:14:59<27:44,  1.00it/s]

[18321] Геокодируем адрес: Лиговский пр-т 3/9, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18322/19990 [1:15:01<29:14,  1.05s/it]

[18322] Геокодируем адрес: Чекистов ул 44, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18323/19990 [1:15:01<27:33,  1.01it/s]

[18323] Геокодируем адрес: nan

Геокодирование:  92%|█████████▏| 18324/19990 [1:15:02<26:51,  1.03it/s]

[18324] Геокодируем адрес: nan

Геокодирование:  92%|█████████▏| 18325/19990 [1:15:03<26:58,  1.03it/s]

[18325] Геокодируем адрес: Комендантский пр-т, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18326/19990 [1:15:04<27:50,  1.00s/it]

[18326] Геокодируем адрес: nan

Геокодирование:  92%|█████████▏| 18327/19990 [1:15:05<27:12,  1.02it/s]

[18327] Геокодируем адрес: nan

Геокодирование:  92%|█████████▏| 18328/19990 [1:15:06<27:24,  1.01it/s]

[18328] Геокодируем адрес: Маршала Тухачевского ул 5к1, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18329/19990 [1:15:08<28:56,  1.05s/it]

[18329] Геокодируем адрес: nan

Геокодирование:  92%|█████████▏| 18330/19990 [1:15:08<27:02,  1.02it/s]

[18330] Геокодируем адрес: Обуховской Обороны пр-т 217, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18331/19990 [1:15:10<30:17,  1.10s/it]

Автосохранение после 18330 строк...
[18331] Геокодируем адрес: nan

Геокодирование:  92%|█████████▏| 18332/19990 [1:15:10<26:29,  1.04it/s]

[18332] Геокодируем адрес: nan

Геокодирование:  92%|█████████▏| 18333/19990 [1:15:11<26:42,  1.03it/s]

[18333] Геокодируем адрес: nan

Геокодирование:  92%|█████████▏| 18334/19990 [1:15:12<26:58,  1.02it/s]

[18334] Геокодируем адрес: Варшавская ул 19к3Б, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18335/19990 [1:15:13<27:32,  1.00it/s]

[18335] Геокодируем адрес: Яхтенная ул 28, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18336/19990 [1:15:14<28:10,  1.02s/it]

[18336] Геокодируем адрес: nan

Геокодирование:  92%|█████████▏| 18337/19990 [1:15:15<26:52,  1.02it/s]

[18337] Геокодируем адрес: Мытнинская ул 31, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18338/19990 [1:15:16<27:41,  1.01s/it]

[18338] Геокодируем адрес: nan

Геокодирование:  92%|█████████▏| 18339/19990 [1:15:17<27:07,  1.01it/s]

[18339] Геокодируем адрес: Суздальский пр-т 97, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18340/19990 [1:15:19<28:59,  1.05s/it]

[18340] Геокодируем адрес: Савушкина ул 111, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18341/19990 [1:15:20<27:56,  1.02s/it]

[18341] Геокодируем адрес: nan

Геокодирование:  92%|█████████▏| 18342/19990 [1:15:20<26:38,  1.03it/s]

[18342] Геокодируем адрес: nan

Геокодирование:  92%|█████████▏| 18343/19990 [1:15:21<26:41,  1.03it/s]

[18343] Геокодируем адрес: Суворовский пр-т 62, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18344/19990 [1:15:23<28:29,  1.04s/it]

[18344] Геокодируем адрес: Кудровский пр-д, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18345/19990 [1:15:23<27:07,  1.01it/s]

[18345] Геокодируем адрес: Софийская ул, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18346/19990 [1:15:24<26:56,  1.02it/s]

[18346] Геокодируем адрес: Невский пр-т 95, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18347/19990 [1:15:26<29:02,  1.06s/it]

[18347] Геокодируем адрес: Просвещения пр-т, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18348/19990 [1:15:26<27:03,  1.01it/s]

[18348] Геокодируем адрес: Домостроительная ул, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18349/19990 [1:15:27<26:46,  1.02it/s]

[18349] Геокодируем адрес: nan

Геокодирование:  92%|█████████▏| 18350/19990 [1:15:28<26:31,  1.03it/s]

[18350] Геокодируем адрес: nan

Геокодирование:  92%|█████████▏| 18351/19990 [1:15:29<26:57,  1.01it/s]

[18351] Геокодируем адрес: Петродворец Ораниенбаумское ш 2М, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18352/19990 [1:15:31<28:05,  1.03s/it]

[18352] Геокодируем адрес: Петродворец Ораниенбаумское ш 2М, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18353/19990 [1:15:32<28:04,  1.03s/it]

[18353] Геокодируем адрес: Петродворец Ораниенбаумское ш 2М, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18354/19990 [1:15:33<28:03,  1.03s/it]

[18354] Геокодируем адрес: Тихорецкий пр-т 26, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18355/19990 [1:15:34<27:44,  1.02s/it]

[18355] Геокодируем адрес: Тихорецкий пр-т 26, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18356/19990 [1:15:35<27:08,  1.00it/s]

[18356] Геокодируем адрес: Стрельна Санкт-Петербургское ш, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18357/19990 [1:15:35<26:02,  1.05it/s]

[18357] Геокодируем адрес: Санкт-Петербургское ш, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18358/19990 [1:15:36<26:35,  1.02it/s]

[18358] Геокодируем адрес: Санкт-Петербургское ш, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18359/19990 [1:15:37<27:16,  1.00s/it]

[18359] Геокодируем адрес: Науки пр-т, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18360/19990 [1:15:39<27:47,  1.02s/it]

[18360] Геокодируем адрес: Шишкина ул 293, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18361/19990 [1:15:40<28:52,  1.06s/it]

Автосохранение после 18360 строк...
[18361] Геокодируем адрес: Заманиловская-Михайловская ул, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18362/19990 [1:15:40<25:55,  1.05it/s]

[18362] Геокодируем адрес: Котельникова ал 2к2, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18363/19990 [1:15:41<26:54,  1.01it/s]

[18363] Геокодируем адрес: Савушкина ул, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18364/19990 [1:15:42<26:15,  1.03it/s]

[18364] Геокодируем адрес: nan

Геокодирование:  92%|█████████▏| 18365/19990 [1:15:43<26:15,  1.03it/s]

[18365] Геокодируем адрес: Савушкина ул 2, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18366/19990 [1:15:45<27:52,  1.03s/it]

[18366] Геокодируем адрес: Королева пр-т, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18367/19990 [1:15:46<27:24,  1.01s/it]

[18367] Геокодируем адрес: nan

Геокодирование:  92%|█████████▏| 18368/19990 [1:15:46<26:09,  1.03it/s]

[18368] Геокодируем адрес: Рябовское ш, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18369/19990 [1:15:47<26:38,  1.01it/s]

[18369] Геокодируем адрес: Морского Десанта ул, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18370/19990 [1:15:48<26:35,  1.02it/s]

[18370] Геокодируем адрес: nan

Геокодирование:  92%|█████████▏| 18371/19990 [1:15:49<26:37,  1.01it/s]

[18371] Геокодируем адрес: nan

Геокодирование:  92%|█████████▏| 18372/19990 [1:15:50<26:43,  1.01it/s]

[18372] Геокодируем адрес: nan

Геокодирование:  92%|█████████▏| 18373/19990 [1:15:51<26:41,  1.01it/s]

[18373] Геокодируем адрес: Курчатова ул 6, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18374/19990 [1:15:53<28:58,  1.08s/it]

[18374] Геокодируем адрес: Ивана Фомина ул 13к1, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18375/19990 [1:15:53<26:57,  1.00s/it]

[18375] Геокодируем адрес: nan

Геокодирование:  92%|█████████▏| 18376/19990 [1:15:54<26:20,  1.02it/s]

[18376] Геокодируем адрес: Дыбенко ул, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18377/19990 [1:15:55<26:59,  1.00s/it]

[18377] Геокодируем адрес: Дыбенко ул, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18378/19990 [1:15:56<26:34,  1.01it/s]

[18378] Геокодируем адрес: Дыбенко ул, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18379/19990 [1:15:57<26:46,  1.00it/s]

[18379] Геокодируем адрес: Дыбенко ул, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18380/19990 [1:15:58<26:37,  1.01it/s]

[18380] Геокодируем адрес: Дыбенко ул, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18381/19990 [1:15:59<26:32,  1.01it/s]

[18381] Геокодируем адрес: Тельмана ул 40, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18382/19990 [1:16:01<27:53,  1.04s/it]

[18382] Геокодируем адрес: nan

Геокодирование:  92%|█████████▏| 18383/19990 [1:16:01<26:03,  1.03it/s]

[18383] Геокодируем адрес: Ольги Берггольц ул 9к1, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18384/19990 [1:16:02<26:52,  1.00s/it]

[18384] Геокодируем адрес: nan

Геокодирование:  92%|█████████▏| 18385/19990 [1:16:03<26:29,  1.01it/s]

[18385] Геокодируем адрес: Артиллерийская ул 12, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18386/19990 [1:16:04<27:07,  1.01s/it]

[18386] Геокодируем адрес: Большая Морская ул 9, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18387/19990 [1:16:05<27:14,  1.02s/it]

[18387] Геокодируем адрес: канала Грибоедова наб, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18388/19990 [1:16:06<26:21,  1.01it/s]

[18388] Геокодируем адрес: 5-я Советская ул 34, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18389/19990 [1:16:08<27:42,  1.04s/it]

[18389] Геокодируем адрес: Ленсоветовский, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18390/19990 [1:16:08<25:57,  1.03it/s]

[18390] Геокодируем адрес: Пушкин Октябрьский б-р 22, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18391/19990 [1:16:10<29:45,  1.12s/it]

Автосохранение после 18390 строк...
[18391] Геокодируем адрес: nan

Геокодирование:  92%|█████████▏| 18392/19990 [1:16:10<25:20,  1.05it/s]

[18392] Геокодируем адрес: nan

Геокодирование:  92%|█████████▏| 18393/19990 [1:16:11<25:47,  1.03it/s]

[18393] Геокодируем адрес: Шушары, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18394/19990 [1:16:12<26:12,  1.01it/s]

[18394] Геокодируем адрес: Славянка, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18395/19990 [1:16:13<26:33,  1.00it/s]

[18395] Геокодируем адрес: Шушары Школьная ул 17, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18396/19990 [1:16:15<26:59,  1.02s/it]

[18396] Геокодируем адрес: Новгородский пр-т 9.2, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18397/19990 [1:16:16<27:54,  1.05s/it]

[18397] Геокодируем адрес: Тамбасова ул 29к2, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18398/19990 [1:16:16<26:12,  1.01it/s]

[18398] Геокодируем адрес: nan

Геокодирование:  92%|█████████▏| 18399/19990 [1:16:17<25:40,  1.03it/s]

[18399] Геокодируем адрес: Будапештская ул 29к1, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18400/19990 [1:16:18<26:32,  1.00s/it]

[18400] Геокодируем адрес: Софийская ул 33к1, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18401/19990 [1:16:20<26:51,  1.01s/it]

[18401] Геокодируем адрес: Купчинская ул 4к2, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18402/19990 [1:16:21<26:26,  1.00it/s]

[18402] Геокодируем адрес: Красуцкого ул 2, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18403/19990 [1:16:22<26:29,  1.00s/it]

[18403] Геокодируем адрес: Петергофское ш 53, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18404/19990 [1:16:23<26:22,  1.00it/s]

[18404] Геокодируем адрес: Тельмана ул 44Ж, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18405/19990 [1:16:24<27:21,  1.04s/it]

[18405] Геокодируем адрес: Сапёрный Дорожная ул, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18406/19990 [1:16:24<25:31,  1.03it/s]

[18406] Геокодируем адрес: Бабушкина ул 84к2, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18407/19990 [1:16:26<26:30,  1.00s/it]

[18407] Геокодируем адрес: Савушкина ул 3, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18408/19990 [1:16:27<26:37,  1.01s/it]

[18408] Геокодируем адрес: Торжковская ул, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18409/19990 [1:16:27<25:42,  1.03it/s]

[18409] Геокодируем адрес: Савушкина ул, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18410/19990 [1:16:28<25:52,  1.02it/s]

[18410] Геокодируем адрес: Чёрной речки наб 53к2, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18411/19990 [1:16:29<26:13,  1.00it/s]

[18411] Геокодируем адрес: nan

Геокодирование:  92%|█████████▏| 18412/19990 [1:16:30<25:52,  1.02it/s]

[18412] Геокодируем адрес: Путиловская наб, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18413/19990 [1:16:31<26:16,  1.00it/s]

[18413] Геокодируем адрес: nan

Геокодирование:  92%|█████████▏| 18414/19990 [1:16:32<25:56,  1.01it/s]

[18414] Геокодируем адрес: Гончарная ул, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18415/19990 [1:16:33<26:14,  1.00it/s]

[18415] Геокодируем адрес: Кулибина пл, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18416/19990 [1:16:34<26:08,  1.00it/s]

[18416] Геокодируем адрес: Блокадников сквер, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18417/19990 [1:16:35<26:14,  1.00s/it]

[18417] Геокодируем адрес: nan

Геокодирование:  92%|█████████▏| 18418/19990 [1:16:36<26:05,  1.00it/s]

[18418] Геокодируем адрес: Брянцева ул, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18419/19990 [1:16:37<26:10,  1.00it/s]

[18419] Геокодируем адрес: Брянцева ул, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18420/19990 [1:16:38<26:33,  1.02s/it]

[18420] Геокодируем адрес: Кондратьевский пр-т, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18421/19990 [1:16:40<27:48,  1.06s/it]

Автосохранение после 18420 строк...
[18421] Геокодируем адрес: Большая Морская ул 11, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18422/19990 [1:16:41<26:08,  1.00s/it]

[18422] Геокодируем адрес: Партизана Германа ул, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18423/19990 [1:16:41<25:47,  1.01it/s]

[18423] Геокодируем адрес: Кирочная ул, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18424/19990 [1:16:42<25:41,  1.02it/s]

[18424] Геокодируем адрес: Планерная ул, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18425/19990 [1:16:43<25:43,  1.01it/s]

[18425] Геокодируем адрес: Измайловский б-р, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18426/19990 [1:16:45<26:29,  1.02s/it]

[18426] Геокодируем адрес: Муринская дор, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18427/19990 [1:16:45<25:40,  1.01it/s]

[18427] Геокодируем адрес: Крыленко ул, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18428/19990 [1:16:46<25:59,  1.00it/s]

[18428] Геокодируем адрес: Стачек пр-т, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18429/19990 [1:16:48<26:58,  1.04s/it]

[18429] Геокодируем адрес: Стойкости ул 14, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18430/19990 [1:16:49<33:36,  1.29s/it]

[18430] Геокодируем адрес: Шушары, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18431/19990 [1:16:50<31:03,  1.20s/it]

[18431] Геокодируем адрес: Шушары Московское ш, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18432/19990 [1:16:51<29:31,  1.14s/it]

[18432] Геокодируем адрес: 2-й Предпортовый пр-д, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18433/19990 [1:16:53<28:46,  1.11s/it]

[18433] Геокодируем адрес: 2-й Предпортовый пр-д, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18434/19990 [1:16:53<27:47,  1.07s/it]

[18434] Геокодируем адрес: Марата ул 35, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18435/19990 [1:16:55<27:52,  1.08s/it]

[18435] Геокодируем адрес: Новостроек ул, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18436/19990 [1:16:55<26:11,  1.01s/it]

[18436] Геокодируем адрес: Бассейная ул, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18437/19990 [1:16:56<26:13,  1.01s/it]

[18437] Геокодируем адрес: парнас, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18438/19990 [1:16:57<26:06,  1.01s/it]

[18438] Геокодируем адрес: nan

Геокодирование:  92%|█████████▏| 18439/19990 [1:16:58<25:47,  1.00it/s]

[18439] Геокодируем адрес: Народного Ополчения пр-т 193, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18440/19990 [1:17:00<28:12,  1.09s/it]

[18440] Геокодируем адрес: Феодосийская ул, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18441/19990 [1:17:00<25:05,  1.03it/s]

[18441] Геокодируем адрес: Гангутская ул, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18442/19990 [1:17:01<25:21,  1.02it/s]

[18442] Геокодируем адрес: Торфяная дор 17к2, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18443/19990 [1:17:02<25:41,  1.00it/s]

[18443] Геокодируем адрес: Искровский пр-т 29, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18444/19990 [1:17:04<27:23,  1.06s/it]

[18444] Геокодируем адрес: 6-я Жерновская ул 9к1, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18445/19990 [1:17:04<25:25,  1.01it/s]

[18445] Геокодируем адрес: Сергея Тюленина пер 4/23, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18446/19990 [1:17:06<26:22,  1.02s/it]

[18446] Геокодируем адрес: Есенина ул 1к1, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18447/19990 [1:17:07<26:09,  1.02s/it]

[18447] Геокодируем адрес: nan

Геокодирование:  92%|█████████▏| 18448/19990 [1:17:07<24:32,  1.05it/s]

[18448] Геокодируем адрес: Тихорецкий пр-т 13, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18449/19990 [1:17:09<26:50,  1.05s/it]

[18449] Геокодируем адрес: Торжковская ул 3, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18450/19990 [1:17:09<24:55,  1.03it/s]

[18450] Геокодируем адрес: Новоизмайловский пр-т, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18451/19990 [1:17:11<26:33,  1.04s/it]

Автосохранение после 18450 строк...
[18451] Геокодируем адрес: Малая Бухарестская ул, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18452/19990 [1:17:11<24:25,  1.05it/s]

[18452] Геокодируем адрес: Дворцовый пр-д, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18453/19990 [1:17:12<25:11,  1.02it/s]

[18453] Геокодируем адрес: Солидарности пр-т, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18454/19990 [1:17:13<25:27,  1.01it/s]

[18454] Геокодируем адрес: Тимуровская ул, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18455/19990 [1:17:14<25:04,  1.02it/s]

[18455] Геокодируем адрес: Грибалевой ул, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18456/19990 [1:17:15<25:13,  1.01it/s]

[18456] Геокодируем адрес: Торжковская ул 1А, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18457/19990 [1:17:16<25:45,  1.01s/it]

[18457] Геокодируем адрес: Большой пр-т, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18458/19990 [1:17:18<27:10,  1.06s/it]

[18458] Геокодируем адрес: Ушинского ул, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18459/19990 [1:17:18<24:55,  1.02it/s]

[18459] Геокодируем адрес: Просвещения пр-т, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18460/19990 [1:17:20<25:35,  1.00s/it]

[18460] Геокодируем адрес: Среднияй пр-т 83с2, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18461/19990 [1:17:20<24:28,  1.04it/s]

[18461] Геокодируем адрес: Просвещения пр-т, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18462/19990 [1:17:22<25:42,  1.01s/it]

[18462] Геокодируем адрес: Королева пр-т 29а, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18463/19990 [1:17:23<26:19,  1.03s/it]

[18463] Геокодируем адрес: Ушинского ул, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18464/19990 [1:17:23<24:49,  1.02it/s]

[18464] Геокодируем адрес: nan

Геокодирование:  92%|█████████▏| 18465/19990 [1:17:24<24:45,  1.03it/s]

[18465] Геокодируем адрес: nan

Геокодирование:  92%|█████████▏| 18466/19990 [1:17:25<24:50,  1.02it/s]

[18466] Геокодируем адрес: Большая Разночинная ул 23, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18467/19990 [1:17:26<25:24,  1.00s/it]

[18467] Геокодируем адрес: nan

Геокодирование:  92%|█████████▏| 18468/19990 [1:17:27<25:03,  1.01it/s]

[18468] Геокодируем адрес: nan

Геокодирование:  92%|█████████▏| 18469/19990 [1:17:28<25:07,  1.01it/s]

[18469] Геокодируем адрес: nan

Геокодирование:  92%|█████████▏| 18470/19990 [1:17:29<25:11,  1.01it/s]

[18470] Геокодируем адрес: Симонова ул, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18471/19990 [1:17:30<25:35,  1.01s/it]

[18471] Геокодируем адрес: Лесной пр-т 59к2, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18472/19990 [1:17:32<25:48,  1.02s/it]

[18472] Геокодируем адрес: Литовская ул, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18473/19990 [1:17:32<25:09,  1.01it/s]

[18473] Геокодируем адрес: Брянцева ул, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18474/19990 [1:17:33<25:23,  1.00s/it]

[18474] Геокодируем адрес: Петергоф Ропшинское ш 3к7, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18475/19990 [1:17:35<25:47,  1.02s/it]

[18475] Геокодируем адрес: Косинова ул 14к2, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18476/19990 [1:17:35<25:13,  1.00it/s]

[18476] Геокодируем адрес: Зои Космодемьянской ул 15, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18477/19990 [1:17:37<25:58,  1.03s/it]

[18477] Геокодируем адрес: Луначарского пр-т 94к1Б, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18478/19990 [1:17:37<24:16,  1.04it/s]

[18478] Геокодируем адрес: Стачек пр-т 105, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18479/19990 [1:17:39<26:33,  1.05s/it]

[18479] Геокодируем адрес: Новоколомяжский пр-т 13, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18480/19990 [1:17:41<33:50,  1.34s/it]

[18480] Геокодируем адрес: nan

Геокодирование:  92%|█████████▏| 18481/19990 [1:17:42<30:19,  1.21s/it]

Автосохранение после 18480 строк...
[18481] Геокодируем адрес: Ленинский пр-т 150к2, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18482/19990 [1:17:43<28:17,  1.13s/it]

[18482] Геокодируем адрес: Академика Крылова ул 3, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18483/19990 [1:17:44<28:26,  1.13s/it]

[18483] Геокодируем адрес: Тельмана ул 42к2, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18484/19990 [1:17:45<26:32,  1.06s/it]

[18484] Геокодируем адрес: 2-я Советская ул 15, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18485/19990 [1:17:46<26:55,  1.07s/it]

[18485] Геокодируем адрес: Невский пр-т 128Г, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18486/19990 [1:17:47<25:52,  1.03s/it]

[18486] Геокодируем адрес: 9-я Советская ул 22, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18487/19990 [1:17:48<26:12,  1.05s/it]

[18487] Геокодируем адрес: Загородный пр-т 21-23, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18488/19990 [1:17:49<25:57,  1.04s/it]

[18488] Геокодируем адрес: Загородный пр-т 21-23, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18489/19990 [1:17:50<25:32,  1.02s/it]

[18489] Геокодируем адрес: Лиговский пр-т 47, Санкт-Петербург

Геокодирование:  92%|█████████▏| 18490/19990 [1:17:51<25:01,  1.00s/it]

[18490] Геокодируем адрес: nan

Геокодирование:  93%|█████████▎| 18491/19990 [1:17:51<23:33,  1.06it/s]

[18491] Геокодируем адрес: Авиаконструкторов пр-т 4к1, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18492/19990 [1:17:53<25:15,  1.01s/it]

[18492] Геокодируем адрес: Подвойского ул 40к1, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18493/19990 [1:17:53<24:21,  1.02it/s]

[18493] Геокодируем адрес: Шушары Первомайская ул 22, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18494/19990 [1:17:55<24:48,  1.01it/s]

[18494] Геокодируем адрес: Бестужевская ул 30, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18495/19990 [1:17:55<24:34,  1.01it/s]

[18495] Геокодируем адрес: Краснодонская ул 21, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18496/19990 [1:17:56<24:28,  1.02it/s]

[18496] Геокодируем адрес: Кораблестроителей ул 19к2, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18497/19990 [1:17:58<24:55,  1.00s/it]

[18497] Геокодируем адрес: Петергоф Ропшинское ш 3к7, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18498/19990 [1:17:59<25:01,  1.01s/it]

[18498] Геокодируем адрес: Петергоф Ропшинское ш 3к8, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18499/19990 [1:18:00<24:56,  1.00s/it]

[18499] Геокодируем адрес: Петергоф Ропшинское ш 3к8, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18500/19990 [1:18:01<24:52,  1.00s/it]

[18500] Геокодируем адрес: Петергоф Ропшинское ш 3к7, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18501/19990 [1:18:02<24:59,  1.01s/it]

[18501] Геокодируем адрес: 1-й Предпортовый пр-д, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18502/19990 [1:18:02<24:29,  1.01it/s]

[18502] Геокодируем адрес: Шушары Школьная ул, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18503/19990 [1:18:03<24:11,  1.02it/s]

[18503] Геокодируем адрес: Шуваловский пр-т, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18504/19990 [1:18:05<24:53,  1.01s/it]

[18504] Геокодируем адрес: nan

Геокодирование:  93%|█████████▎| 18505/19990 [1:18:05<24:14,  1.02it/s]

[18505] Геокодируем адрес: Заневский пр-т, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18506/19990 [1:18:06<24:56,  1.01s/it]

[18506] Геокодируем адрес: Пушкин Ахматовская ул 19А, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18507/19990 [1:18:08<25:32,  1.03s/it]

[18507] Геокодируем адрес: Шаумяна пр-т, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18508/19990 [1:18:09<24:37,  1.00it/s]

[18508] Геокодируем адрес: Металлистов пр-т, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18509/19990 [1:18:10<25:01,  1.01s/it]

[18509] Геокодируем адрес: Львовская ул 9, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18510/19990 [1:18:11<25:05,  1.02s/it]

[18510] Геокодируем адрес: Медиков пр-т 10к5, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18511/19990 [1:18:12<25:03,  1.02s/it]

Автосохранение после 18510 строк...
[18511] Геокодируем адрес: Ветеранов пр-т 63, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18512/19990 [1:18:13<25:49,  1.05s/it]

[18512] Геокодируем адрес: Петергоф Чичеринская ул 7к1, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18513/19990 [1:18:14<23:52,  1.03it/s]

[18513] Геокодируем адрес: Окраинная ул 9литЕ, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18514/19990 [1:18:14<23:13,  1.06it/s]

[18514] Геокодируем адрес: nan

Геокодирование:  93%|█████████▎| 18515/19990 [1:18:15<23:46,  1.03it/s]

[18515] Геокодируем адрес: Полевая Сабировская ул 47к1, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18516/19990 [1:18:16<24:27,  1.00it/s]

[18516] Геокодируем адрес: Колпино Павловская ул 94литА, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18517/19990 [1:18:17<23:52,  1.03it/s]

[18517] Геокодируем адрес: 5-й Предпортовый пр-д, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18518/19990 [1:18:18<24:41,  1.01s/it]

[18518] Геокодируем адрес: Средний В. О. пр-т, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18519/19990 [1:18:20<25:41,  1.05s/it]

[18519] Геокодируем адрес: nan

Геокодирование:  93%|█████████▎| 18520/19990 [1:18:20<23:50,  1.03it/s]

[18520] Геокодируем адрес: Таллинская ул 24, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18521/19990 [1:18:21<24:19,  1.01it/s]

[18521] Геокодируем адрес: Рязанский пер, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18522/19990 [1:18:22<24:24,  1.00it/s]

[18522] Геокодируем адрес: nan

Геокодирование:  93%|█████████▎| 18523/19990 [1:18:23<24:01,  1.02it/s]

[18523] Геокодируем адрес: nan

Геокодирование:  93%|█████████▎| 18524/19990 [1:18:24<24:06,  1.01it/s]

[18524] Геокодируем адрес: nan

Геокодирование:  93%|█████████▎| 18525/19990 [1:18:25<24:20,  1.00it/s]

[18525] Геокодируем адрес: Маршала Жукова пр-т 34к1, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18526/19990 [1:18:27<26:17,  1.08s/it]

[18526] Геокодируем адрес: Варшавская ул 46, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18527/19990 [1:18:27<23:55,  1.02it/s]

[18527] Геокодируем адрес: Пилотов ул 13, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18528/19990 [1:18:29<24:37,  1.01s/it]

[18528] Геокодируем адрес: Ленинский пр-т, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18529/19990 [1:18:30<24:45,  1.02s/it]

[18529] Геокодируем адрес: Пилотов ул 13, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18530/19990 [1:18:31<24:21,  1.00s/it]

[18530] Геокодируем адрес: Наличная ул 21, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18531/19990 [1:18:31<23:58,  1.01it/s]

[18531] Геокодируем адрес: Кржижановского ул, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18532/19990 [1:18:32<23:44,  1.02it/s]

[18532] Геокодируем адрес: Костюшко ул, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18533/19990 [1:18:33<23:52,  1.02it/s]

[18533] Геокодируем адрес: Индустриальный пр-т, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18534/19990 [1:18:35<24:47,  1.02s/it]

[18534] Геокодируем адрес: Индустриальный пр-т, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18535/19990 [1:18:36<24:28,  1.01s/it]

[18535] Геокодируем адрес: Шушары, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18536/19990 [1:18:36<23:45,  1.02it/s]

[18536] Геокодируем адрес: Кржижановского ул, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18537/19990 [1:18:37<23:55,  1.01it/s]

[18537] Геокодируем адрес: Кораблестроителей ул, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18538/19990 [1:18:38<23:54,  1.01it/s]

[18538] Геокодируем адрес: Непокоренных пр-т, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18539/19990 [1:18:39<24:24,  1.01s/it]

[18539] Геокодируем адрес: Кондратьевский пр-т 62к6, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18540/19990 [1:18:40<24:08,  1.00it/s]

[18540] Геокодируем адрес: Волковский пр-д 2, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18541/19990 [1:18:42<26:23,  1.09s/it]

Автосохранение после 18540 строк...
[18541] Геокодируем адрес: Пулковское ш, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18542/19990 [1:18:42<23:36,  1.02it/s]

[18542] Геокодируем адрес: Евгения Шварца ал 12к1, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18543/19990 [1:18:44<23:50,  1.01it/s]

[18543] Геокодируем адрес: Варшавская ул 23 к.2, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18544/19990 [1:18:45<23:58,  1.00it/s]

[18544] Геокодируем адрес: nan

Геокодирование:  93%|█████████▎| 18545/19990 [1:18:45<23:13,  1.04it/s]

[18545] Геокодируем адрес: Косыгина пр-т 30к2, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18546/19990 [1:18:46<23:54,  1.01it/s]

[18546] Геокодируем адрес: верхняя ул, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18547/19990 [1:18:47<24:00,  1.00it/s]

[18547] Геокодируем адрес: Металлострой Садовая ул 2к3, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18548/19990 [1:18:49<24:12,  1.01s/it]

[18548] Геокодируем адрес: Гатчинское ш 4к3, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18549/19990 [1:18:49<24:02,  1.00s/it]

[18549] Геокодируем адрес: Кантемировская ул, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18550/19990 [1:18:50<23:39,  1.01it/s]

[18550] Геокодируем адрес: Туристская ул, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18551/19990 [1:18:51<23:49,  1.01it/s]

[18551] Геокодируем адрес: Сестрорецк Приморское ш 350, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18552/19990 [1:18:53<25:47,  1.08s/it]

[18552] Геокодируем адрес: Косыгина пр-т 30к2, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18553/19990 [1:18:53<23:25,  1.02it/s]

[18553] Геокодируем адрес: Краснопутиловская ул 98, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18554/19990 [1:18:54<23:31,  1.02it/s]

[18554] Геокодируем адрес: Евгения Шварца ал 12к1, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18555/19990 [1:18:55<23:49,  1.00it/s]

[18555] Геокодируем адрес: nan

Геокодирование:  93%|█████████▎| 18556/19990 [1:18:56<23:14,  1.03it/s]

[18556] Геокодируем адрес: Ломоносов Ораниенбаум пр-т, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18557/19990 [1:18:58<24:15,  1.02s/it]

[18557] Геокодируем адрес: Южное ш 53к4, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18558/19990 [1:18:58<23:42,  1.01it/s]

[18558] Геокодируем адрес: Красное Село Ленина пр-т, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18559/19990 [1:19:00<25:35,  1.07s/it]

[18559] Геокодируем адрес: Луначарского пр-т 110литА, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18560/19990 [1:19:00<22:37,  1.05it/s]

[18560] Геокодируем адрес: Мебельная ул, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18561/19990 [1:19:01<23:24,  1.02it/s]

[18561] Геокодируем адрес: Тореза пр-т 13, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18562/19990 [1:19:03<24:47,  1.04s/it]

[18562] Геокодируем адрес: Большой пр-т 99, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18563/19990 [1:19:05<33:10,  1.39s/it]

[18563] Геокодируем адрес: Тореза пр-т 17, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18564/19990 [1:19:06<28:44,  1.21s/it]

[18564] Геокодируем адрес: nan

Геокодирование:  93%|█████████▎| 18565/19990 [1:19:06<25:57,  1.09s/it]

[18565] Геокодируем адрес: Петергоф Суворовская ул 7к5, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18566/19990 [1:19:09<32:54,  1.39s/it]

[18566] Геокодируем адрес: Художников пр-т 30к1, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18567/19990 [1:19:10<30:58,  1.31s/it]

[18567] Геокодируем адрес: nan

Геокодирование:  93%|█████████▎| 18568/19990 [1:19:10<27:18,  1.15s/it]

[18568] Геокодируем адрес: Лиговский пр-т 89/20, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18569/19990 [1:19:12<28:15,  1.19s/it]

[18569] Геокодируем адрес: Предпортовый пр-д 1, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18570/19990 [1:19:13<25:53,  1.09s/it]

[18570] Геокодируем адрес: nan

Геокодирование:  93%|█████████▎| 18571/19990 [1:19:14<25:15,  1.07s/it]

Автосохранение после 18570 строк...
[18571] Геокодируем адрес: Предпортовый пр-д 1, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18572/19990 [1:19:15<24:34,  1.04s/it]

[18572] Геокодируем адрес: Металлистов пр-т 21.2-3, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18573/19990 [1:19:16<25:05,  1.06s/it]

[18573] Геокодируем адрес: Новаторов б-р, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18574/19990 [1:19:17<24:03,  1.02s/it]

[18574] Геокодируем адрес: Пилотов ул 14.1, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18575/19990 [1:19:18<23:31,  1.00it/s]

[18575] Геокодируем адрес: Новгородский пр-т, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18576/19990 [1:19:19<23:27,  1.00it/s]

[18576] Геокодируем адрес: nan

Геокодирование:  93%|█████████▎| 18577/19990 [1:19:19<22:45,  1.03it/s]

[18577] Геокодируем адрес: nan

Геокодирование:  93%|█████████▎| 18578/19990 [1:19:20<23:02,  1.02it/s]

[18578] Геокодируем адрес: nan

Геокодирование:  93%|█████████▎| 18579/19990 [1:19:21<23:16,  1.01it/s]

[18579] Геокодируем адрес: Предпортовый пр-д 1, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18580/19990 [1:19:23<24:06,  1.03s/it]

[18580] Геокодируем адрес: nan

Геокодирование:  93%|█████████▎| 18581/19990 [1:19:23<23:01,  1.02it/s]

[18581] Геокодируем адрес: 2-й Предпортовый пр-д 6, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18582/19990 [1:19:25<23:39,  1.01s/it]

[18582] Геокодируем адрес: Руднева ул 13к1, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18583/19990 [1:19:26<23:58,  1.02s/it]

[18583] Геокодируем адрес: Коллонтай ул 27, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18584/19990 [1:19:27<23:40,  1.01s/it]

[18584] Геокодируем адрес: Пискаревский пр-т 52, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18585/19990 [1:19:28<24:17,  1.04s/it]

[18585] Геокодируем адрес: Одоевского ул 8, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18586/19990 [1:19:29<22:59,  1.02it/s]

[18586] Геокодируем адрес: Новоизмайловский пр-т 13к2Б, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18587/19990 [1:19:29<22:23,  1.04it/s]

[18587] Геокодируем адрес: Новоизмайловский пр-т 17, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18588/19990 [1:19:31<24:04,  1.03s/it]

[18588] Геокодируем адрес: 1-й Предпортовый пр-д 14, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18589/19990 [1:19:32<23:27,  1.00s/it]

[18589] Геокодируем адрес: nan

Геокодирование:  93%|█████████▎| 18590/19990 [1:19:32<22:41,  1.03it/s]

[18590] Геокодируем адрес: nan

Геокодирование:  93%|█████████▎| 18591/19990 [1:19:33<22:47,  1.02it/s]

[18591] Геокодируем адрес: nan

Геокодирование:  93%|█████████▎| 18592/19990 [1:19:34<22:53,  1.02it/s]

[18592] Геокодируем адрес: nan

Геокодирование:  93%|█████████▎| 18593/19990 [1:19:35<23:05,  1.01it/s]

[18593] Геокодируем адрес: nan

Геокодирование:  93%|█████████▎| 18594/19990 [1:19:36<23:08,  1.01it/s]

[18594] Геокодируем адрес: nan

Геокодирование:  93%|█████████▎| 18595/19990 [1:19:37<22:59,  1.01it/s]

[18595] Геокодируем адрес: nan

Геокодирование:  93%|█████████▎| 18596/19990 [1:19:38<23:06,  1.01it/s]

[18596] Геокодируем адрес: nan

Геокодирование:  93%|█████████▎| 18597/19990 [1:19:39<23:14,  1.00s/it]

[18597] Геокодируем адрес: nan

Геокодирование:  93%|█████████▎| 18598/19990 [1:19:40<23:07,  1.00it/s]

[18598] Геокодируем адрес: nan

Геокодирование:  93%|█████████▎| 18599/19990 [1:19:41<23:12,  1.00s/it]

[18599] Геокодируем адрес: Окуловская ул 4, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18600/19990 [1:19:42<23:21,  1.01s/it]

[18600] Геокодируем адрес: nan

Геокодирование:  93%|█████████▎| 18601/19990 [1:19:44<24:03,  1.04s/it]

Автосохранение после 18600 строк...
[18601] Геокодируем адрес: Некрасова ул 23, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18602/19990 [1:19:45<24:40,  1.07s/it]

[18602] Геокодируем адрес: nan

Геокодирование:  93%|█████████▎| 18603/19990 [1:19:45<22:20,  1.03it/s]

[18603] Геокодируем адрес: nan

Геокодирование:  93%|█████████▎| 18604/19990 [1:19:46<22:31,  1.03it/s]

[18604] Геокодируем адрес: Большой Сампсониевский пр-т 96, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18605/19990 [1:19:48<25:23,  1.10s/it]

[18605] Геокодируем адрес: Союза Печатников ул 8, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18606/19990 [1:19:49<22:50,  1.01it/s]

[18606] Геокодируем адрес: nan

Геокодирование:  93%|█████████▎| 18607/19990 [1:19:49<21:59,  1.05it/s]

[18607] Геокодируем адрес: Союза Печатников ул 8, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18608/19990 [1:19:51<22:51,  1.01it/s]

[18608] Геокодируем адрес: Культуры пр-т 11, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18609/19990 [1:19:52<24:08,  1.05s/it]

[18609] Геокодируем адрес: nan

Геокодирование:  93%|█████████▎| 18610/19990 [1:19:52<21:59,  1.05it/s]

[18610] Геокодируем адрес: Большой Сампсониевский пр-т, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18611/19990 [1:19:54<23:35,  1.03s/it]

[18611] Геокодируем адрес: Трудящихся б-р 13, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18612/19990 [1:19:55<23:36,  1.03s/it]

[18612] Геокодируем адрес: Оборонная ул, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18613/19990 [1:19:55<21:58,  1.04it/s]

[18613] Геокодируем адрес: nan

Геокодирование:  93%|█████████▎| 18614/19990 [1:19:56<22:11,  1.03it/s]

[18614] Геокодируем адрес: nan

Геокодирование:  93%|█████████▎| 18615/19990 [1:19:57<22:18,  1.03it/s]

[18615] Геокодируем адрес: Коломяжский пр-т, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18616/19990 [1:19:59<23:02,  1.01s/it]

[18616] Геокодируем адрес: Металлострой Северный пр-д, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18617/19990 [1:19:59<22:53,  1.00s/it]

[18617] Геокодируем адрес: Петергоф, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18618/19990 [1:20:00<22:41,  1.01it/s]

[18618] Геокодируем адрес: Муринская дор, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18619/19990 [1:20:02<29:44,  1.30s/it]

[18619] Геокодируем адрес: Кузнецовская ул, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18620/19990 [1:20:03<27:31,  1.21s/it]

[18620] Геокодируем адрес: Колпино, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18621/19990 [1:20:04<25:57,  1.14s/it]

[18621] Геокодируем адрес: Колпино, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18622/19990 [1:20:05<25:02,  1.10s/it]

[18622] Геокодируем адрес: nan

Геокодирование:  93%|█████████▎| 18623/19990 [1:20:06<24:18,  1.07s/it]

[18623] Геокодируем адрес: nan

Геокодирование:  93%|█████████▎| 18624/19990 [1:20:07<23:44,  1.04s/it]

[18624] Геокодируем адрес: Металлистов пр-т, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18625/19990 [1:20:09<24:03,  1.06s/it]

[18625] Геокодируем адрес: Панфилова ул 29, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18626/19990 [1:20:09<23:26,  1.03s/it]

[18626] Геокодируем адрес: Индустриальный пр-т 20к1, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18627/19990 [1:20:11<23:16,  1.02s/it]

[18627] Геокодируем адрес: nan

Геокодирование:  93%|█████████▎| 18628/19990 [1:20:11<22:34,  1.01it/s]

[18628] Геокодируем адрес: Красное Село Гатчинское ш 12/1, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18629/19990 [1:20:14<32:21,  1.43s/it]

[18629] Геокодируем адрес: Петергоф Ропшинское ш 1А, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18630/19990 [1:20:15<27:39,  1.22s/it]

[18630] Геокодируем адрес: nan

Геокодирование:  93%|█████████▎| 18631/19990 [1:20:16<26:07,  1.15s/it]

Автосохранение после 18630 строк...
[18631] Геокодируем адрес: Ропшинское ш 4, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18632/19990 [1:20:17<24:23,  1.08s/it]

[18632] Геокодируем адрес: nan

Геокодирование:  93%|█████████▎| 18633/19990 [1:20:17<23:38,  1.04s/it]

[18633] Геокодируем адрес: Рябовское ш, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18634/19990 [1:20:18<23:19,  1.03s/it]

[18634] Геокодируем адрес: nan

Геокодирование:  93%|█████████▎| 18635/19990 [1:20:19<22:55,  1.02s/it]

[18635] Геокодируем адрес: Прибрежная ул, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18636/19990 [1:20:20<23:02,  1.02s/it]

[18636] Геокодируем адрес: Ветеранов пр-т 150-158, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18637/19990 [1:20:22<24:22,  1.08s/it]

[18637] Геокодируем адрес: Белоостровская ул 31, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18638/19990 [1:20:22<22:17,  1.01it/s]

[18638] Геокодируем адрес: Софийская ул 37к1, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18639/19990 [1:20:24<22:52,  1.02s/it]

[18639] Геокодируем адрес: Литейный пр-т 16, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18640/19990 [1:20:25<23:35,  1.05s/it]

[18640] Геокодируем адрес: Ропшинское ш 3к7, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18641/19990 [1:20:26<22:00,  1.02it/s]

[18641] Геокодируем адрес: Просвещения пр-т 80к4, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18642/19990 [1:20:26<22:07,  1.02it/s]

[18642] Геокодируем адрес: nan

Геокодирование:  93%|█████████▎| 18643/19990 [1:20:27<21:52,  1.03it/s]

[18643] Геокодируем адрес: Большевиков пр-т 26к1Б, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18644/19990 [1:20:29<22:22,  1.00it/s]

[18644] Геокодируем адрес: Печатников сад, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18645/19990 [1:20:29<22:18,  1.01it/s]

[18645] Геокодируем адрес: Энергетиков пр-т 9к1, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18646/19990 [1:20:31<22:47,  1.02s/it]

[18646] Геокодируем адрес: Шушары Валдайская ул 11, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18647/19990 [1:20:32<22:33,  1.01s/it]

[18647] Геокодируем адрес: Сестрорецк Советский пр-т 1, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18648/19990 [1:20:33<23:19,  1.04s/it]

[18648] Геокодируем адрес: 6-я Жерновская ул 9к1, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18649/19990 [1:20:33<21:39,  1.03it/s]

[18649] Геокодируем адрес: nan

Геокодирование:  93%|█████████▎| 18650/19990 [1:20:34<21:47,  1.03it/s]

[18650] Геокодируем адрес: nan

Геокодирование:  93%|█████████▎| 18651/19990 [1:20:35<21:51,  1.02it/s]

[18651] Геокодируем адрес: Металлострой дор, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18652/19990 [1:20:36<22:10,  1.01it/s]

[18652] Геокодируем адрес: Маршала Захарова ул 16к1, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18653/19990 [1:20:38<23:14,  1.04s/it]

[18653] Геокодируем адрес: Маршала Казакова ул, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18654/19990 [1:20:39<22:26,  1.01s/it]

[18654] Геокодируем адрес: Брянцева ул, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18655/19990 [1:20:39<21:54,  1.02it/s]

[18655] Геокодируем адрес: Белы Куна ул 6, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18656/19990 [1:20:41<23:11,  1.04s/it]

[18656] Геокодируем адрес: Крыленко ул 43к1, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18657/19990 [1:20:42<22:00,  1.01it/s]

[18657] Геокодируем адрес: Кораблестроителей ул 19к1, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18658/19990 [1:20:43<22:10,  1.00it/s]

[18658] Геокодируем адрес: Варшавская ул 37, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18659/19990 [1:20:44<22:11,  1.00s/it]

[18659] Геокодируем адрес: Серебряков пер 9, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18660/19990 [1:20:45<22:00,  1.01it/s]

[18660] Геокодируем адрес: Баррикадная ул 5, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18661/19990 [1:20:46<22:51,  1.03s/it]

Автосохранение после 18660 строк...
[18661] Геокодируем адрес: Петергоф Ропшинское ш 3к7, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18662/19990 [1:20:47<21:56,  1.01it/s]

[18662] Геокодируем адрес: Петергоф Ропшинское ш 3к8, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18663/19990 [1:20:48<21:56,  1.01it/s]

[18663] Геокодируем адрес: Петергоф Ропшинское ш 3к8, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18664/19990 [1:20:49<21:51,  1.01it/s]

[18664] Геокодируем адрес: Петергоф Ропшинское ш 3к8, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18665/19990 [1:20:50<22:03,  1.00it/s]

[18665] Геокодируем адрес: Замшина ул 54, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18666/19990 [1:20:51<21:43,  1.02it/s]

[18666] Геокодируем адрес: Северный пр-т 83, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18667/19990 [1:20:52<24:29,  1.11s/it]

[18667] Геокодируем адрес: Народная ул 70, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18668/19990 [1:20:53<21:58,  1.00it/s]

[18668] Геокодируем адрес: nan

Геокодирование:  93%|█████████▎| 18669/19990 [1:20:54<21:03,  1.05it/s]

[18669] Геокодируем адрес: Шостаковича ул 5к1, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18670/19990 [1:20:55<22:04,  1.00s/it]

[18670] Геокодируем адрес: Большая Московская ул 6, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18671/19990 [1:20:56<21:59,  1.00s/it]

[18671] Геокодируем адрес: Суворовский пр-т 62, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18672/19990 [1:20:57<22:45,  1.04s/it]

[18672] Геокодируем адрес: Кораблестроителей ул 19к2, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18673/19990 [1:20:58<21:14,  1.03it/s]

[18673] Геокодируем адрес: Университетская наб, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18674/19990 [1:20:59<21:13,  1.03it/s]

[18674] Геокодируем адрес: Комендантский пр-т, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18675/19990 [1:21:00<22:04,  1.01s/it]

[18675] Геокодируем адрес: Шуваловский пр-т, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18676/19990 [1:21:01<21:34,  1.01it/s]

[18676] Геокодируем адрес: Космонавтов пр-т, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18677/19990 [1:21:02<22:24,  1.02s/it]

[18677] Геокодируем адрес: дорога на Турухтанные Острова дор, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18678/19990 [1:21:03<22:08,  1.01s/it]

[18678] Геокодируем адрес: Ленсовета ул, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18679/19990 [1:21:04<21:11,  1.03it/s]

[18679] Геокодируем адрес: Малоохтинский пр-т, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18680/19990 [1:21:05<21:55,  1.00s/it]

[18680] Геокодируем адрес: Московский пр-т, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18681/19990 [1:21:06<22:10,  1.02s/it]

[18681] Геокодируем адрес: nan

Геокодирование:  93%|█████████▎| 18682/19990 [1:21:06<21:02,  1.04it/s]

[18682] Геокодируем адрес: реки Мойки наб, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18683/19990 [1:21:08<21:40,  1.00it/s]

[18683] Геокодируем адрес: Энгельса пр-т 147к2, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18684/19990 [1:21:09<21:47,  1.00s/it]

[18684] Геокодируем адрес: Гаккелевская ул, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18685/19990 [1:21:10<21:23,  1.02it/s]

[18685] Геокодируем адрес: Космонавтов пр-т, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18686/19990 [1:21:11<22:15,  1.02s/it]

[18686] Геокодируем адрес: Бадаева ул, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18687/19990 [1:21:12<21:18,  1.02it/s]

[18687] Геокодируем адрес: Шуваловский пр-т, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18688/19990 [1:21:13<21:56,  1.01s/it]

[18688] Геокодируем адрес: Бабушкина ул 52, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18689/19990 [1:21:14<22:10,  1.02s/it]

[18689] Геокодируем адрес: Бабушкина ул 52, Санкт-Петербург

Геокодирование:  93%|█████████▎| 18690/19990 [1:21:15<22:00,  1.02s/it]

[18690] Геокодируем адрес: Будапештская ул 38к3, Санкт-Петербург

Геокодирование:  94%|█████████▎| 18691/19990 [1:21:16<22:08,  1.02s/it]

Автосохранение после 18690 строк...
[18691] Геокодируем адрес: Приморское ш, Санкт-Петербург

Геокодирование:  94%|█████████▎| 18692/19990 [1:21:17<20:59,  1.03it/s]

[18692] Геокодируем адрес: Приморское ш, Санкт-Петербург

Геокодирование:  94%|█████████▎| 18693/19990 [1:21:18<21:11,  1.02it/s]

[18693] Геокодируем адрес: Приморское ш, Санкт-Петербург

Геокодирование:  94%|█████████▎| 18694/19990 [1:21:20<27:47,  1.29s/it]

[18694] Геокодируем адрес: Седова ул, Санкт-Петербург

Геокодирование:  94%|█████████▎| 18695/19990 [1:21:21<26:00,  1.21s/it]

[18695] Геокодируем адрес: Приморское ш, Санкт-Петербург

Геокодирование:  94%|█████████▎| 18696/19990 [1:21:22<24:42,  1.15s/it]

[18696] Геокодируем адрес: nan

Геокодирование:  94%|█████████▎| 18697/19990 [1:21:22<23:17,  1.08s/it]

[18697] Геокодируем адрес: Ропшинское ш 3к8, Санкт-Петербург

Геокодирование:  94%|█████████▎| 18698/19990 [1:21:24<23:27,  1.09s/it]

[18698] Геокодируем адрес: Брянцева ул, Санкт-Петербург

Геокодирование:  94%|█████████▎| 18699/19990 [1:21:25<22:19,  1.04s/it]

[18699] Геокодируем адрес: Пулковское ш 9к1, Санкт-Петербург

Геокодирование:  94%|█████████▎| 18700/19990 [1:21:26<22:18,  1.04s/it]

[18700] Геокодируем адрес: Будапештская ул 23к4, Санкт-Петербург

Геокодирование:  94%|█████████▎| 18701/19990 [1:21:27<21:55,  1.02s/it]

[18701] Геокодируем адрес: Рябовское ш, Санкт-Петербург

Геокодирование:  94%|█████████▎| 18702/19990 [1:21:28<21:40,  1.01s/it]

[18702] Геокодируем адрес: Поварской пер, Санкт-Петербург

Геокодирование:  94%|█████████▎| 18703/19990 [1:21:28<21:33,  1.00s/it]

[18703] Геокодируем адрес: Ушинского ул, Санкт-Петербург

Геокодирование:  94%|█████████▎| 18704/19990 [1:21:30<21:38,  1.01s/it]

[18704] Геокодируем адрес: Матисова канала наб, Санкт-Петербург

Геокодирование:  94%|█████████▎| 18705/19990 [1:21:31<21:29,  1.00s/it]

[18705] Геокодируем адрес: nan

Геокодирование:  94%|█████████▎| 18706/19990 [1:21:31<21:14,  1.01it/s]

[18706] Геокодируем адрес: Большая Подьяческая ул 14, Санкт-Петербург

Геокодирование:  94%|█████████▎| 18707/19990 [1:21:33<21:56,  1.03s/it]

[18707] Геокодируем адрес: Варваринская ул, Санкт-Петербург

Геокодирование:  94%|█████████▎| 18708/19990 [1:21:34<21:16,  1.00it/s]

[18708] Геокодируем адрес: Эрлеровский б-р 10, Санкт-Петербург

Геокодирование:  94%|█████████▎| 18709/19990 [1:21:35<22:30,  1.05s/it]

[18709] Геокодируем адрес: Сварицкая ул, Санкт-Петербург

Геокодирование:  94%|█████████▎| 18710/19990 [1:21:35<20:35,  1.04it/s]

[18710] Геокодируем адрес: Марата ул 50, Санкт-Петербург

Геокодирование:  94%|█████████▎| 18711/19990 [1:21:37<22:22,  1.05s/it]

[18711] Геокодируем адрес: Морская наб 15, Санкт-Петербург

Геокодирование:  94%|█████████▎| 18712/19990 [1:21:38<21:37,  1.02s/it]

[18712] Геокодируем адрес: Заневский пр-т 67к3, Санкт-Петербург

Геокодирование:  94%|█████████▎| 18713/19990 [1:21:39<20:53,  1.02it/s]

[18713] Геокодируем адрес: nan

Геокодирование:  94%|█████████▎| 18714/19990 [1:21:39<20:36,  1.03it/s]

[18714] Геокодируем адрес: Вишерская ул, Санкт-Петербург

Геокодирование:  94%|█████████▎| 18715/19990 [1:21:40<20:50,  1.02it/s]

[18715] Геокодируем адрес: Ботаническая ул 18, Санкт-Петербург

Геокодирование:  94%|█████████▎| 18716/19990 [1:21:42<21:17,  1.00s/it]

[18716] Геокодируем адрес: Ботаническая ул 18, Санкт-Петербург

Геокодирование:  94%|█████████▎| 18717/19990 [1:21:43<21:21,  1.01s/it]

[18717] Геокодируем адрес: Московский пр-т 136к2а, Санкт-Петербург

Геокодирование:  94%|█████████▎| 18718/19990 [1:21:43<20:42,  1.02it/s]

[18718] Геокодируем адрес: Шушары Школьная ул, Санкт-Петербург

Геокодирование:  94%|█████████▎| 18719/19990 [1:21:44<21:00,  1.01it/s]

[18719] Геокодируем адрес: Народная ул 40, Санкт-Петербург

Геокодирование:  94%|█████████▎| 18720/19990 [1:21:46<21:33,  1.02s/it]

[18720] Геокодируем адрес: Каменноостровский пр-т 42Б, Санкт-Петербург

Геокодирование:  94%|█████████▎| 18721/19990 [1:21:47<22:34,  1.07s/it]

Автосохранение после 18720 строк...
[18721] Геокодируем адрес: Светлановский пр-т 38к2, Санкт-Петербург

Геокодирование:  94%|█████████▎| 18722/19990 [1:21:48<20:40,  1.02it/s]

[18722] Геокодируем адрес: Просвещения пр-т 51, Санкт-Петербург

Геокодирование:  94%|█████████▎| 18723/19990 [1:21:49<21:50,  1.03s/it]

[18723] Геокодируем адрес: Ропшинское ш 3к8, Санкт-Петербург

Геокодирование:  94%|█████████▎| 18724/19990 [1:21:50<20:36,  1.02it/s]

[18724] Геокодируем адрес: Маршала Захарова ул 33к1, Санкт-Петербург

Геокодирование:  94%|█████████▎| 18725/19990 [1:21:51<21:40,  1.03s/it]

[18725] Геокодируем адрес: 2-й Предпортовый пр-д, Санкт-Петербург

Геокодирование:  94%|█████████▎| 18726/19990 [1:21:52<20:35,  1.02it/s]

[18726] Геокодируем адрес: Школьная ул, Санкт-Петербург

Геокодирование:  94%|█████████▎| 18727/19990 [1:21:53<22:05,  1.05s/it]

[18727] Геокодируем адрес: Ропшинское ш 3к8, Санкт-Петербург

Геокодирование:  94%|█████████▎| 18728/19990 [1:21:54<20:24,  1.03it/s]

[18728] Геокодируем адрес: Октябрьская наб 24-26, Санкт-Петербург

Геокодирование:  94%|█████████▎| 18729/19990 [1:21:55<21:30,  1.02s/it]

[18729] Геокодируем адрес: Лени Голикова ул, Санкт-Петербург

Геокодирование:  94%|█████████▎| 18730/19990 [1:21:56<20:16,  1.04it/s]

[18730] Геокодируем адрес: nan

Геокодирование:  94%|█████████▎| 18731/19990 [1:21:56<20:15,  1.04it/s]

[18731] Геокодируем адрес: 5-я линия ВО 46, Санкт-Петербург

Геокодирование:  94%|█████████▎| 18732/19990 [1:21:59<29:05,  1.39s/it]

[18732] Геокодируем адрес: терр. Марьино 48, Санкт-Петербург

Геокодирование:  94%|█████████▎| 18733/19990 [1:22:00<24:43,  1.18s/it]

[18733] Геокодируем адрес: Кропоткина ул, Санкт-Петербург

Геокодирование:  94%|█████████▎| 18734/19990 [1:22:00<22:58,  1.10s/it]

[18734] Геокодируем адрес: nan

Геокодирование:  94%|█████████▎| 18735/19990 [1:22:01<22:18,  1.07s/it]

[18735] Геокодируем адрес: Жукова ул, Санкт-Петербург

Геокодирование:  94%|█████████▎| 18736/19990 [1:22:03<22:11,  1.06s/it]

[18736] Геокодируем адрес: Наставников пр-т 29к1, Санкт-Петербург

Геокодирование:  94%|█████████▎| 18737/19990 [1:22:04<22:08,  1.06s/it]

[18737] Геокодируем адрес: nan

Геокодирование:  94%|█████████▎| 18738/19990 [1:22:04<21:00,  1.01s/it]

[18738] Геокодируем адрес: Восстания ул 14, Санкт-Петербург

Геокодирование:  94%|█████████▎| 18739/19990 [1:22:06<21:35,  1.04s/it]

[18739] Геокодируем адрес: Малые Гаванцы сквер, Санкт-Петербург

Геокодирование:  94%|█████████▎| 18740/19990 [1:22:06<20:53,  1.00s/it]

[18740] Геокодируем адрес: nan

Геокодирование:  94%|█████████▍| 18741/19990 [1:22:07<20:38,  1.01it/s]

[18741] Геокодируем адрес: Петергоф Ропшинское ш 3к7, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18742/19990 [1:22:09<21:30,  1.03s/it]

[18742] Геокодируем адрес: Зеленогорск Курортная ул 31, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18743/19990 [1:22:10<21:23,  1.03s/it]

[18743] Геокодируем адрес: Морская ул, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18744/19990 [1:22:10<20:32,  1.01it/s]

[18744] Геокодируем адрес: Лермонтовский пр-т, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18745/19990 [1:22:12<20:48,  1.00s/it]

[18745] Геокодируем адрес: nan

Геокодирование:  94%|█████████▍| 18746/19990 [1:22:12<20:20,  1.02it/s]

[18746] Геокодируем адрес: Среднерогатская ул 13, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18747/19990 [1:22:14<21:02,  1.02s/it]

[18747] Геокодируем адрес: Павловское ш, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18748/19990 [1:22:14<20:28,  1.01it/s]

[18748] Геокодируем адрес: Петергоф Ропшинское ш 3к7, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18749/19990 [1:22:16<20:56,  1.01s/it]

[18749] Геокодируем адрес: Косыгина пр-т 30к2, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18750/19990 [1:22:16<20:31,  1.01it/s]

[18750] Геокодируем адрес: nan

Геокодирование:  94%|█████████▍| 18751/19990 [1:22:18<21:10,  1.03s/it]

Автосохранение после 18750 строк...
[18751] Геокодируем адрес: Парголово Железнодорожная ул 11к2, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18752/19990 [1:22:19<20:36,  1.00it/s]

[18752] Геокодируем адрес: Светлановский пр-т 99к1, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18753/19990 [1:22:19<20:13,  1.02it/s]

[18753] Геокодируем адрес: Верности ул 46к2, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18754/19990 [1:22:20<20:23,  1.01it/s]

[18754] Геокодируем адрес: nan

Геокодирование:  94%|█████████▍| 18755/19990 [1:22:21<20:11,  1.02it/s]

[18755] Геокодируем адрес: Ушаковская наб 7к2, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18756/19990 [1:22:23<20:45,  1.01s/it]

[18756] Геокодируем адрес: Московский пр-т 97, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18757/19990 [1:22:24<21:37,  1.05s/it]

[18757] Геокодируем адрес: nan

Геокодирование:  94%|█████████▍| 18758/19990 [1:22:24<19:56,  1.03it/s]

[18758] Геокодируем адрес: Брянцева ул 8, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18759/19990 [1:22:26<20:26,  1.00it/s]

[18759] Геокодируем адрес: Бухарестская ул, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18760/19990 [1:22:27<20:33,  1.00s/it]

[18760] Геокодируем адрес: Кирочная ул 12, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18761/19990 [1:22:28<20:37,  1.01s/it]

[18761] Геокодируем адрес: Новаторов б-р 78, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18762/19990 [1:22:30<27:32,  1.35s/it]

[18762] Геокодируем адрес: Авиационная ул 40а, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18763/19990 [1:22:31<24:55,  1.22s/it]

[18763] Геокодируем адрес: Караваевская ул 2к1, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18764/19990 [1:22:32<23:05,  1.13s/it]

[18764] Геокодируем адрес: nan

Геокодирование:  94%|█████████▍| 18765/19990 [1:22:32<21:47,  1.07s/it]

[18765] Геокодируем адрес: Дачный пр-т, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18766/19990 [1:22:34<21:59,  1.08s/it]

[18766] Геокодируем адрес: Кондратьевский пр-т, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18767/19990 [1:22:35<21:16,  1.04s/it]

[18767] Геокодируем адрес: Славы пр-т 7к1, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18768/19990 [1:22:36<21:19,  1.05s/it]

[18768] Геокодируем адрес: nan

Геокодирование:  94%|█████████▍| 18769/19990 [1:22:36<20:19,  1.00it/s]

[18769] Геокодируем адрес: nan

Геокодирование:  94%|█████████▍| 18770/19990 [1:22:37<20:19,  1.00it/s]

[18770] Геокодируем адрес: Бабушкина ул 8к2, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18771/19990 [1:22:39<21:06,  1.04s/it]

[18771] Геокодируем адрес: Старо-Петергофский пр-т, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18772/19990 [1:22:40<20:32,  1.01s/it]

[18772] Геокодируем адрес: Красного Курсанта ул 10б, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18773/19990 [1:22:41<20:31,  1.01s/it]

[18773] Геокодируем адрес: Кингисеппское ш 51, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18774/19990 [1:22:42<20:16,  1.00s/it]

[18774] Геокодируем адрес: Тучков пер, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18775/19990 [1:22:42<19:50,  1.02it/s]

[18775] Геокодируем адрес: nan

Геокодирование:  94%|█████████▍| 18776/19990 [1:22:43<19:57,  1.01it/s]

[18776] Геокодируем адрес: nan

Геокодирование:  94%|█████████▍| 18777/19990 [1:22:44<19:59,  1.01it/s]

[18777] Геокодируем адрес: Кустодиева ул 10к2, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18778/19990 [1:22:45<20:09,  1.00it/s]

[18778] Геокодируем адрес: nan

Геокодирование:  94%|█████████▍| 18779/19990 [1:22:46<20:06,  1.00it/s]

[18779] Геокодируем адрес: Кузнечный пер 14б, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18780/19990 [1:22:48<20:47,  1.03s/it]

[18780] Геокодируем адрес: nan

Геокодирование:  94%|█████████▍| 18781/19990 [1:22:49<20:45,  1.03s/it]

Автосохранение после 18780 строк...
[18781] Геокодируем адрес: Ткачей ул 4, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18782/19990 [1:22:50<20:05,  1.00it/s]

[18782] Геокодируем адрес: Рябовское ш, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18783/19990 [1:22:50<19:48,  1.02it/s]

[18783] Геокодируем адрес: Ольги Берггольц ул, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18784/19990 [1:22:52<20:11,  1.00s/it]

[18784] Геокодируем адрес: Беговая ул, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18785/19990 [1:22:52<19:50,  1.01it/s]

[18785] Геокодируем адрес: Космонавтов пр-т 29к6, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18786/19990 [1:22:54<20:16,  1.01s/it]

[18786] Геокодируем адрес: Карла Маркса ул, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18787/19990 [1:22:55<20:35,  1.03s/it]

[18787] Геокодируем адрес: nan

Геокодирование:  94%|█████████▍| 18788/19990 [1:22:55<19:33,  1.02it/s]

[18788] Геокодируем адрес: Рябовское ш, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18789/19990 [1:22:56<19:40,  1.02it/s]

[18789] Геокодируем адрес: Рентгена ул 23, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18790/19990 [1:22:57<20:02,  1.00s/it]

[18790] Геокодируем адрес: Вавиловых ул 7к1, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18791/19990 [1:22:58<19:57,  1.00it/s]

[18791] Геокодируем адрес: Тележный пер 3, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18792/19990 [1:22:59<19:57,  1.00it/s]

[18792] Геокодируем адрес: Энгельса пр-т 96, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18793/19990 [1:23:01<21:12,  1.06s/it]

[18793] Геокодируем адрес: Кингисеппское ш 8, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18794/19990 [1:23:01<19:33,  1.02it/s]

[18794] Геокодируем адрес: Будапештская ул 5к3, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18795/19990 [1:23:03<19:42,  1.01it/s]

[18795] Геокодируем адрес: Рябовское ш, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18796/19990 [1:23:03<19:26,  1.02it/s]

[18796] Геокодируем адрес: Рябовское ш, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18797/19990 [1:23:04<19:36,  1.01it/s]

[18797] Геокодируем адрес: Маршала Тухачевского ул 39Б, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18798/19990 [1:23:06<20:28,  1.03s/it]

[18798] Геокодируем адрес: Нахимова ул, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18799/19990 [1:23:06<19:33,  1.02it/s]

[18799] Геокодируем адрес: Красных Зорь б-р, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18800/19990 [1:23:08<20:12,  1.02s/it]

[18800] Геокодируем адрес: Конная ул, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18801/19990 [1:23:08<19:23,  1.02it/s]

[18801] Геокодируем адрес: Королева пр-т, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18802/19990 [1:23:10<20:11,  1.02s/it]

[18802] Геокодируем адрес: Парашютная ул, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18803/19990 [1:23:10<19:24,  1.02it/s]

[18803] Геокодируем адрес: Конная ул, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18804/19990 [1:23:11<19:29,  1.01it/s]

[18804] Геокодируем адрес: Металлистов пр-т, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18805/19990 [1:23:12<19:43,  1.00it/s]

[18805] Геокодируем адрес: Большой пр-т 55А, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18806/19990 [1:23:14<21:07,  1.07s/it]

[18806] Геокодируем адрес: Типанова ул 23стр1, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18807/19990 [1:23:15<19:24,  1.02it/s]

[18807] Геокодируем адрес: Кронверкский пр-т 33, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18808/19990 [1:23:16<20:10,  1.02s/it]

[18808] Геокодируем адрес: Гатчинская ул 2/54, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18809/19990 [1:23:17<19:18,  1.02it/s]

[18809] Геокодируем адрес: Таврическая ул 19, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18810/19990 [1:23:18<19:39,  1.00it/s]

[18810] Геокодируем адрес: Кронштадт Кронштадтское ш, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18811/19990 [1:23:19<20:08,  1.03s/it]

Автосохранение после 18810 строк...
[18811] Геокодируем адрес: Коммуны ул, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18812/19990 [1:23:19<19:01,  1.03it/s]

[18812] Геокодируем адрес: Коммуны ул, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18813/19990 [1:23:20<19:20,  1.01it/s]

[18813] Геокодируем адрес: Пулковское ш, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18814/19990 [1:23:22<19:30,  1.01it/s]

[18814] Геокодируем адрес: Выборгское ш, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18815/19990 [1:23:23<19:45,  1.01s/it]

[18815] Геокодируем адрес: nan

Геокодирование:  94%|█████████▍| 18816/19990 [1:23:23<18:59,  1.03it/s]

[18816] Геокодируем адрес: nan

Геокодирование:  94%|█████████▍| 18817/19990 [1:23:24<19:08,  1.02it/s]

[18817] Геокодируем адрес: Тележный наб 3, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18818/19990 [1:23:25<19:35,  1.00s/it]

[18818] Геокодируем адрес: Конная ул 5к3, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18819/19990 [1:23:27<19:43,  1.01s/it]

[18819] Геокодируем адрес: Бронницкая ул 31г, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18820/19990 [1:23:28<19:39,  1.01s/it]

[18820] Геокодируем адрес: nan

Геокодирование:  94%|█████████▍| 18821/19990 [1:23:28<19:03,  1.02it/s]

[18821] Геокодируем адрес: Марата ул, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18822/19990 [1:23:30<19:33,  1.01s/it]

[18822] Геокодируем адрес: nan

Геокодирование:  94%|█████████▍| 18823/19990 [1:23:30<19:06,  1.02it/s]

[18823] Геокодируем адрес: nan

Геокодирование:  94%|█████████▍| 18824/19990 [1:23:31<19:15,  1.01it/s]

[18824] Геокодируем адрес: nan

Геокодирование:  94%|█████████▍| 18825/19990 [1:23:32<19:26,  1.00s/it]

[18825] Геокодируем адрес: nan

Геокодирование:  94%|█████████▍| 18826/19990 [1:23:33<19:14,  1.01it/s]

[18826] Геокодируем адрес: nan

Геокодирование:  94%|█████████▍| 18827/19990 [1:23:34<19:14,  1.01it/s]

[18827] Геокодируем адрес: Симонова ул, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18828/19990 [1:23:35<19:25,  1.00s/it]

[18828] Геокодируем адрес: Софийская ул, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18829/19990 [1:23:36<19:27,  1.01s/it]

[18829] Геокодируем адрес: nan

Геокодирование:  94%|█████████▍| 18830/19990 [1:23:37<19:13,  1.01it/s]

[18830] Геокодируем адрес: Александра Матросова ул, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18831/19990 [1:23:39<19:53,  1.03s/it]

[18831] Геокодируем адрес: Крузенштерна ул, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18832/19990 [1:23:39<19:20,  1.00s/it]

[18832] Геокодируем адрес: Манчестерская ул, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18833/19990 [1:23:40<19:10,  1.01it/s]

[18833] Геокодируем адрес: Бронницкая ул, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18834/19990 [1:23:41<19:12,  1.00it/s]

[18834] Геокодируем адрес: nan

Геокодирование:  94%|█████████▍| 18835/19990 [1:23:42<19:05,  1.01it/s]

[18835] Геокодируем адрес: Апрельская ул, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18836/19990 [1:23:43<19:16,  1.00s/it]

[18836] Геокодируем адрес: Шуваловский пр-т, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18837/19990 [1:23:45<19:26,  1.01s/it]

[18837] Геокодируем адрес: Конторская ул, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18838/19990 [1:23:45<19:08,  1.00it/s]

[18838] Геокодируем адрес: Верхняя ул, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18839/19990 [1:23:46<19:11,  1.00s/it]

[18839] Геокодируем адрес: Красное Село Кингисеппское ш 8, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18840/19990 [1:23:48<21:02,  1.10s/it]

[18840] Геокодируем адрес: Малая Балканская ул 46, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18841/19990 [1:23:49<19:34,  1.02s/it]

Автосохранение после 18840 строк...
[18841] Геокодируем адрес: Оружейника Фёдорова ул 9, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18842/19990 [1:23:50<18:45,  1.02it/s]

[18842] Геокодируем адрес: Боровая ул 21, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18843/19990 [1:23:51<18:45,  1.02it/s]

[18843] Геокодируем адрес: Сестрорецкая ул 3, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18844/19990 [1:23:51<18:42,  1.02it/s]

[18844] Геокодируем адрес: Ленсовета ул 88, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18845/19990 [1:23:53<18:59,  1.00it/s]

[18845] Геокодируем адрес: Тележный пер 3, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18846/19990 [1:23:53<18:45,  1.02it/s]

[18846] Геокодируем адрес: Конная ул 5/3, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18847/19990 [1:23:54<18:48,  1.01it/s]

[18847] Геокодируем адрес: nan

Геокодирование:  94%|█████████▍| 18848/19990 [1:23:55<18:39,  1.02it/s]

[18848] Геокодируем адрес: Бадаева ул 1к1, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18849/19990 [1:23:57<19:08,  1.01s/it]

[18849] Геокодируем адрес: Колпино, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18850/19990 [1:23:57<18:52,  1.01it/s]

[18850] Геокодируем адрес: Композиторов ул 17к1, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18851/19990 [1:23:59<19:09,  1.01s/it]

[18851] Геокодируем адрес: Парголово, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18852/19990 [1:23:59<18:44,  1.01it/s]

[18852] Геокодируем адрес: Гангутская ул, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18853/19990 [1:24:00<18:56,  1.00it/s]

[18853] Геокодируем адрес: Ковенский пер, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18854/19990 [1:24:01<18:46,  1.01it/s]

[18854] Геокодируем адрес: nan

Геокодирование:  94%|█████████▍| 18855/19990 [1:24:03<24:23,  1.29s/it]

[18855] Геокодируем адрес: nan

Геокодирование:  94%|█████████▍| 18856/19990 [1:24:04<22:41,  1.20s/it]

[18856] Геокодируем адрес: Авиаконструкторов пр-т, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18857/19990 [1:24:06<22:19,  1.18s/it]

[18857] Геокодируем адрес: Парфеновская ул, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18858/19990 [1:24:06<20:37,  1.09s/it]

[18858] Геокодируем адрес: Бестужевская ул, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18859/19990 [1:24:07<20:15,  1.08s/it]

[18859] Геокодируем адрес: Инструментальная ул 2, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18860/19990 [1:24:09<20:14,  1.07s/it]

[18860] Геокодируем адрес: Пушкин Ленинградская ул 36, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18861/19990 [1:24:10<20:16,  1.08s/it]

[18861] Геокодируем адрес: Кронштадт Форт Константин, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18862/19990 [1:24:10<18:52,  1.00s/it]

[18862] Геокодируем адрес: nan

Геокодирование:  94%|█████████▍| 18863/19990 [1:24:11<18:36,  1.01it/s]

[18863] Геокодируем адрес: Елизарова пр-т 11, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18864/19990 [1:24:13<19:44,  1.05s/it]

[18864] Геокодируем адрес: nan

Геокодирование:  94%|█████████▍| 18865/19990 [1:24:13<18:19,  1.02it/s]

[18865] Геокодируем адрес: Малоохтинский пр-т 98, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18866/19990 [1:24:15<19:10,  1.02s/it]

[18866] Геокодируем адрес: nan

Геокодирование:  94%|█████████▍| 18867/19990 [1:24:15<18:18,  1.02it/s]

[18867] Геокодируем адрес: Турку ул 2к4, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18868/19990 [1:24:17<18:46,  1.00s/it]

[18868] Геокодируем адрес: Чернышевского пр-т 5, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18869/19990 [1:24:19<25:07,  1.34s/it]

[18869] Геокодируем адрес: nan

Геокодирование:  94%|█████████▍| 18870/19990 [1:24:19<22:06,  1.18s/it]

[18870] Геокодируем адрес: Пискаревский пр-т, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18871/19990 [1:24:22<28:06,  1.51s/it]

Автосохранение после 18870 строк...
[18871] Геокодируем адрес: Шушары Первомайская ул 5к1, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18872/19990 [1:24:23<24:14,  1.30s/it]

[18872] Геокодируем адрес: Шушары Первомайская ул 5к1, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18873/19990 [1:24:24<22:25,  1.20s/it]

[18873] Геокодируем адрес: Марата ул 14, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18874/19990 [1:24:25<21:56,  1.18s/it]

[18874] Геокодируем адрес: nan

Геокодирование:  94%|█████████▍| 18875/19990 [1:24:25<19:50,  1.07s/it]

[18875] Геокодируем адрес: Королёва ул 32к2, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18876/19990 [1:24:27<20:09,  1.09s/it]

[18876] Геокодируем адрес: Космонавтов пр-т 104, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18877/19990 [1:24:28<20:37,  1.11s/it]

[18877] Геокодируем адрес: Генерала Симоняка ул 15, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18878/19990 [1:24:28<18:36,  1.00s/it]

[18878] Геокодируем адрес: Шушары Школьная ул 17, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18879/19990 [1:24:30<19:04,  1.03s/it]

[18879] Геокодируем адрес: Авиаконструкторов пр-т 11к2, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18880/19990 [1:24:31<18:31,  1.00s/it]

[18880] Геокодируем адрес: Канонерская ул 22, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18881/19990 [1:24:31<18:22,  1.01it/s]

[18881] Геокодируем адрес: Оборонный мост, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18882/19990 [1:24:32<18:07,  1.02it/s]

[18882] Геокодируем адрес: nan

Геокодирование:  94%|█████████▍| 18883/19990 [1:24:33<18:09,  1.02it/s]

[18883] Геокодируем адрес: Парфеновская ул, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18884/19990 [1:24:34<18:19,  1.01it/s]

[18884] Геокодируем адрес: nan

Геокодирование:  94%|█████████▍| 18885/19990 [1:24:35<18:17,  1.01it/s]

[18885] Геокодируем адрес: Ленская ул 8к1, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18886/19990 [1:24:37<18:38,  1.01s/it]

[18886] Геокодируем адрес: Стойкости ул 30к1, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18887/19990 [1:24:38<18:31,  1.01s/it]

[18887] Геокодируем адрес: Красное Село Кингисеппское ш 8, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18888/19990 [1:24:39<20:22,  1.11s/it]

[18888] Геокодируем адрес: Канонерский пр-д 11к4, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18889/19990 [1:24:40<17:49,  1.03it/s]

[18889] Геокодируем адрес: Коммуны ул 26, Санкт-Петербург

Геокодирование:  94%|█████████▍| 18890/19990 [1:24:41<18:33,  1.01s/it]

[18890] Геокодируем адрес: Конная ул 5/3В, Санкт-Петербург

Геокодирование:  95%|█████████▍| 18891/19990 [1:24:42<18:11,  1.01it/s]

[18891] Геокодируем адрес: nan

Геокодирование:  95%|█████████▍| 18892/19990 [1:24:42<17:30,  1.04it/s]

[18892] Геокодируем адрес: Придорожная ал 17, Санкт-Петербург

Геокодирование:  95%|█████████▍| 18893/19990 [1:24:43<18:04,  1.01it/s]

[18893] Геокодируем адрес: Ветеранов пр-т 181, Санкт-Петербург

Геокодирование:  95%|█████████▍| 18894/19990 [1:24:45<19:52,  1.09s/it]

[18894] Геокодируем адрес: nan

Геокодирование:  95%|█████████▍| 18895/19990 [1:24:45<17:32,  1.04it/s]

[18895] Геокодируем адрес: Примакова ул 24, Санкт-Петербург

Геокодирование:  95%|█████████▍| 18896/19990 [1:24:47<17:57,  1.02it/s]

[18896] Геокодируем адрес: Крузенштерна пр-т, Санкт-Петербург

Геокодирование:  95%|█████████▍| 18897/19990 [1:24:48<18:04,  1.01it/s]

[18897] Геокодируем адрес: Подводника Кузьмина ул 27, Санкт-Петербург

Геокодирование:  95%|█████████▍| 18898/19990 [1:24:49<18:01,  1.01it/s]

[18898] Геокодируем адрес: nan

Геокодирование:  95%|█████████▍| 18899/19990 [1:24:49<17:48,  1.02it/s]

[18899] Геокодируем адрес: Камская ул, Санкт-Петербург

Геокодирование:  95%|█████████▍| 18900/19990 [1:24:50<17:57,  1.01it/s]

[18900] Геокодируем адрес: Белы Куна ул 7к5, Санкт-Петербург

Геокодирование:  95%|█████████▍| 18901/19990 [1:24:52<19:25,  1.07s/it]

Автосохранение после 18900 строк...
[18901] Геокодируем адрес: nan

Геокодирование:  95%|█████████▍| 18902/19990 [1:24:52<17:23,  1.04it/s]

[18902] Геокодируем адрес: Капитана Грищенко ул, Санкт-Петербург

Геокодирование:  95%|█████████▍| 18903/19990 [1:24:54<17:59,  1.01it/s]

[18903] Геокодируем адрес: Обуховской Обороны пр-т 70к3, Санкт-Петербург

Геокодирование:  95%|█████████▍| 18904/19990 [1:24:56<23:37,  1.31s/it]

[18904] Геокодируем адрес: Варшавская ул 108, Санкт-Петербург

Геокодирование:  95%|█████████▍| 18905/19990 [1:24:57<21:47,  1.20s/it]

[18905] Геокодируем адрес: Большая Зеленина ул 21, Санкт-Петербург

Геокодирование:  95%|█████████▍| 18906/19990 [1:24:58<20:40,  1.14s/it]

[18906] Геокодируем адрес: Приморский пр-т 137к1, Санкт-Петербург

Геокодирование:  95%|█████████▍| 18907/19990 [1:24:58<19:43,  1.09s/it]

[18907] Геокодируем адрес: Полевая Сабировская ул, Санкт-Петербург

Геокодирование:  95%|█████████▍| 18908/19990 [1:24:59<19:09,  1.06s/it]

[18908] Геокодируем адрес: Юрия Гагарина пр-т 28к4, Санкт-Петербург

Геокодирование:  95%|█████████▍| 18909/19990 [1:25:01<19:10,  1.06s/it]

[18909] Геокодируем адрес: Глинки ул 2, Санкт-Петербург

Геокодирование:  95%|█████████▍| 18910/19990 [1:25:02<19:03,  1.06s/it]

[18910] Геокодируем адрес: Бабушкина ул 70, Санкт-Петербург

Геокодирование:  95%|█████████▍| 18911/19990 [1:25:03<18:47,  1.05s/it]

[18911] Геокодируем адрес: Обуховской обороны пр-т 107, Санкт-Петербург

Геокодирование:  95%|█████████▍| 18912/19990 [1:25:05<24:12,  1.35s/it]

[18912] Геокодируем адрес: Обуховской Обороны пр-т 143, Санкт-Петербург

Геокодирование:  95%|█████████▍| 18913/19990 [1:25:06<23:07,  1.29s/it]

[18913] Геокодируем адрес: nan

Геокодирование:  95%|█████████▍| 18914/19990 [1:25:06<19:34,  1.09s/it]

[18914] Геокодируем адрес: nan

Геокодирование:  95%|█████████▍| 18915/19990 [1:25:07<19:00,  1.06s/it]

[18915] Геокодируем адрес: Пушкинская ул 3, Санкт-Петербург

Геокодирование:  95%|█████████▍| 18916/19990 [1:25:09<19:38,  1.10s/it]

[18916] Геокодируем адрес: Колпино Трудящихся б-р 8, Санкт-Петербург

Геокодирование:  95%|█████████▍| 18917/19990 [1:25:10<19:15,  1.08s/it]

[18917] Геокодируем адрес: Чарушинская ул 22к1, Санкт-Петербург

Геокодирование:  95%|█████████▍| 18918/19990 [1:25:10<17:50,  1.00it/s]

[18918] Геокодируем адрес: Восстания ул 41, Санкт-Петербург

Геокодирование:  95%|█████████▍| 18919/19990 [1:25:12<18:20,  1.03s/it]

[18919] Геокодируем адрес: Лиговский пр-т, Санкт-Петербург

Геокодирование:  95%|█████████▍| 18920/19990 [1:25:13<18:20,  1.03s/it]

[18920] Геокодируем адрес: nan

Геокодирование:  95%|█████████▍| 18921/19990 [1:25:13<17:26,  1.02it/s]

[18921] Геокодируем адрес: Казанская ул 12, Санкт-Петербург

Геокодирование:  95%|█████████▍| 18922/19990 [1:25:15<18:03,  1.01s/it]

[18922] Геокодируем адрес: nan

Геокодирование:  95%|█████████▍| 18923/19990 [1:25:15<17:25,  1.02it/s]

[18923] Геокодируем адрес: nan

Геокодирование:  95%|█████████▍| 18924/19990 [1:25:16<17:34,  1.01it/s]

[18924] Геокодируем адрес: Петергоф Ропшинское ш 3к8, Санкт-Петербург

Геокодирование:  95%|█████████▍| 18925/19990 [1:25:18<17:55,  1.01s/it]

[18925] Геокодируем адрес: Петергоф Ропшинское ш 3к8, Санкт-Петербург

Геокодирование:  95%|█████████▍| 18926/19990 [1:25:19<18:12,  1.03s/it]

[18926] Геокодируем адрес: Фёдора Абрамова ул 8, Санкт-Петербург

Геокодирование:  95%|█████████▍| 18927/19990 [1:25:20<18:28,  1.04s/it]

[18927] Геокодируем адрес: Петергоф Ропшинское ш 3к8, Санкт-Петербург

Геокодирование:  95%|█████████▍| 18928/19990 [1:25:21<17:34,  1.01it/s]

[18928] Геокодируем адрес: Суздальский пр-т 1к1, Санкт-Петербург

Геокодирование:  95%|█████████▍| 18929/19990 [1:25:22<17:56,  1.01s/it]

[18929] Геокодируем адрес: nan

Геокодирование:  95%|█████████▍| 18930/19990 [1:25:22<17:02,  1.04it/s]

[18930] Геокодируем адрес: nan

Геокодирование:  95%|█████████▍| 18931/19990 [1:25:24<17:54,  1.01s/it]

Автосохранение после 18930 строк...
[18931] Геокодируем адрес: Обуховской обороны пр-т 35Б, Санкт-Петербург

Геокодирование:  95%|█████████▍| 18932/19990 [1:25:25<17:56,  1.02s/it]

[18932] Геокодируем адрес: Обуховской Обороны пр-т 35б, Санкт-Петербург

Геокодирование:  95%|█████████▍| 18933/19990 [1:25:26<18:06,  1.03s/it]

[18933] Геокодируем адрес: Воронежская ул 98, Санкт-Петербург

Геокодирование:  95%|█████████▍| 18934/19990 [1:25:27<17:21,  1.01it/s]

[18934] Геокодируем адрес: Овсянниковский сад, Санкт-Петербург

Геокодирование:  95%|█████████▍| 18935/19990 [1:25:27<16:54,  1.04it/s]

[18935] Геокодируем адрес: nan

Геокодирование:  95%|█████████▍| 18936/19990 [1:25:28<17:02,  1.03it/s]

[18936] Геокодируем адрес: 2-я Советская ул 14к4, Санкт-Петербург

Геокодирование:  95%|█████████▍| 18937/19990 [1:25:30<17:46,  1.01s/it]

[18937] Геокодируем адрес: Конная ул 11/4, Санкт-Петербург

Геокодирование:  95%|█████████▍| 18938/19990 [1:25:30<17:21,  1.01it/s]

[18938] Геокодируем адрес: Невский пр-т 166в, Санкт-Петербург

Геокодирование:  95%|█████████▍| 18939/19990 [1:25:31<17:16,  1.01it/s]

[18939] Геокодируем адрес: Конная ул 15Б, Санкт-Петербург

Геокодирование:  95%|█████████▍| 18940/19990 [1:25:33<17:43,  1.01s/it]

[18940] Геокодируем адрес: nan

Геокодирование:  95%|█████████▍| 18941/19990 [1:25:33<17:03,  1.03it/s]

[18941] Геокодируем адрес: nan

Геокодирование:  95%|█████████▍| 18942/19990 [1:25:34<17:15,  1.01it/s]

[18942] Геокодируем адрес: nan

Геокодирование:  95%|█████████▍| 18943/19990 [1:25:35<17:15,  1.01it/s]

[18943] Геокодируем адрес: nan

Геокодирование:  95%|█████████▍| 18944/19990 [1:25:36<17:14,  1.01it/s]

[18944] Геокодируем адрес: Конная ул 13, Санкт-Петербург

Геокодирование:  95%|█████████▍| 18945/19990 [1:25:38<17:51,  1.03s/it]

[18945] Геокодируем адрес: Университетская наб, Санкт-Петербург

Геокодирование:  95%|█████████▍| 18946/19990 [1:25:38<17:17,  1.01it/s]

[18946] Геокодируем адрес: Кронверкский пр-т, Санкт-Петербург

Геокодирование:  95%|█████████▍| 18947/19990 [1:25:39<17:27,  1.00s/it]

[18947] Геокодируем адрес: nan

Геокодирование:  95%|█████████▍| 18948/19990 [1:25:40<17:08,  1.01it/s]

[18948] Геокодируем адрес: nan

Геокодирование:  95%|█████████▍| 18949/19990 [1:25:41<17:14,  1.01it/s]

[18949] Геокодируем адрес: nan

Геокодирование:  95%|█████████▍| 18950/19990 [1:25:42<17:12,  1.01it/s]

[18950] Геокодируем адрес: nan

Геокодирование:  95%|█████████▍| 18951/19990 [1:25:43<17:12,  1.01it/s]

[18951] Геокодируем адрес: Евгения Шварца ул, Санкт-Петербург

Геокодирование:  95%|█████████▍| 18952/19990 [1:25:45<17:38,  1.02s/it]

[18952] Геокодируем адрес: nan

Геокодирование:  95%|█████████▍| 18953/19990 [1:25:45<17:07,  1.01it/s]

[18953] Геокодируем адрес: Пискаревский пр-т 38/1, Санкт-Петербург

Геокодирование:  95%|█████████▍| 18954/19990 [1:25:47<18:04,  1.05s/it]

[18954] Геокодируем адрес: Чкаловский пр-т, Санкт-Петербург

Геокодирование:  95%|█████████▍| 18955/19990 [1:25:48<17:17,  1.00s/it]

[18955] Геокодируем адрес: Большой пр-т, Санкт-Петербург

Геокодирование:  95%|█████████▍| 18956/19990 [1:25:49<18:11,  1.06s/it]

[18956] Геокодируем адрес: Косая линия ВО, Санкт-Петербург

Геокодирование:  95%|█████████▍| 18957/19990 [1:25:49<16:49,  1.02it/s]

[18957] Геокодируем адрес: Валерия Гаврилина ул 3к1, Санкт-Петербург

Геокодирование:  95%|█████████▍| 18958/19990 [1:25:51<17:14,  1.00s/it]

[18958] Геокодируем адрес: Блохина ул 4, Санкт-Петербург

Геокодирование:  95%|█████████▍| 18959/19990 [1:25:51<16:55,  1.02it/s]

[18959] Геокодируем адрес: Бухарестская ул 112, Санкт-Петербург

Геокодирование:  95%|█████████▍| 18960/19990 [1:25:53<17:14,  1.00s/it]

[18960] Геокодируем адрес: Свохозный пер 4, Санкт-Петербург

Геокодирование:  95%|█████████▍| 18961/19990 [1:25:54<17:17,  1.01s/it]

Автосохранение после 18960 строк...
[18961] Геокодируем адрес: nan

Геокодирование:  95%|█████████▍| 18962/19990 [1:25:54<16:36,  1.03it/s]

[18962] Геокодируем адрес: Краснопутиловская ул 59, Санкт-Петербург

Геокодирование:  95%|█████████▍| 18963/19990 [1:25:56<17:05,  1.00it/s]

[18963] Геокодируем адрес: реки Фонтанки наб 17, Санкт-Петербург

Геокодирование:  95%|█████████▍| 18964/19990 [1:25:58<22:15,  1.30s/it]

[18964] Геокодируем адрес: 12-я линия ВО 17Б, Санкт-Петербург

Геокодирование:  95%|█████████▍| 18965/19990 [1:25:59<22:34,  1.32s/it]

[18965] Геокодируем адрес: Ординарная ул, Санкт-Петербург

Геокодирование:  95%|█████████▍| 18966/19990 [1:25:59<18:47,  1.10s/it]

[18966] Геокодируем адрес: nan

Геокодирование:  95%|█████████▍| 18967/19990 [1:26:00<18:14,  1.07s/it]

[18967] Геокодируем адрес: Софьи Ковалевской ул, Санкт-Петербург

Геокодирование:  95%|█████████▍| 18968/19990 [1:26:01<18:02,  1.06s/it]

[18968] Геокодируем адрес: Трудящихся б-р, Санкт-Петербург

Геокодирование:  95%|█████████▍| 18969/19990 [1:26:03<18:09,  1.07s/it]

[18969] Геокодируем адрес: Лесная ул, Санкт-Петербург

Геокодирование:  95%|█████████▍| 18970/19990 [1:26:04<18:13,  1.07s/it]

[18970] Геокодируем адрес: Богатырский пр-т, Санкт-Петербург

Геокодирование:  95%|█████████▍| 18971/19990 [1:26:05<17:18,  1.02s/it]

[18971] Геокодируем адрес: Пионерская ул, Санкт-Петербург

Геокодирование:  95%|█████████▍| 18972/19990 [1:26:06<17:08,  1.01s/it]

[18972] Геокодируем адрес: Оптиков ул, Санкт-Петербург

Геокодирование:  95%|█████████▍| 18973/19990 [1:26:06<16:45,  1.01it/s]

[18973] Геокодируем адрес: nan

Геокодирование:  95%|█████████▍| 18974/19990 [1:26:07<16:51,  1.00it/s]

[18974] Геокодируем адрес: Пулковское ш, Санкт-Петербург

Геокодирование:  95%|█████████▍| 18975/19990 [1:26:08<16:49,  1.01it/s]

[18975] Геокодируем адрес: Будапештская ул, Санкт-Петербург

Геокодирование:  95%|█████████▍| 18976/19990 [1:26:09<16:46,  1.01it/s]

[18976] Геокодируем адрес: Октябрьская наб, Санкт-Петербург

Геокодирование:  95%|█████████▍| 18977/19990 [1:26:10<16:52,  1.00it/s]

[18977] Геокодируем адрес: Пушкин Гатчинское ш, Санкт-Петербург

Геокодирование:  95%|█████████▍| 18978/19990 [1:26:11<16:52,  1.00s/it]

[18978] Геокодируем адрес: nan

Геокодирование:  95%|█████████▍| 18979/19990 [1:26:12<16:49,  1.00it/s]

[18979] Геокодируем адрес: Ветеранов пр-т 143к1, Санкт-Петербург

Геокодирование:  95%|█████████▍| 18980/19990 [1:26:14<17:01,  1.01s/it]

[18980] Геокодируем адрес: Гривцова пер 24, Санкт-Петербург

Геокодирование:  95%|█████████▍| 18981/19990 [1:26:15<17:08,  1.02s/it]

[18981] Геокодируем адрес: Придорожная ал, Санкт-Петербург

Геокодирование:  95%|█████████▍| 18982/19990 [1:26:15<16:37,  1.01it/s]

[18982] Геокодируем адрес: Гривцова пер 24, Санкт-Петербург

Геокодирование:  95%|█████████▍| 18983/19990 [1:26:17<16:53,  1.01s/it]

[18983] Геокодируем адрес: 6-я линия ВО, Санкт-Петербург

Геокодирование:  95%|█████████▍| 18984/19990 [1:26:18<19:21,  1.16s/it]

[18984] Геокодируем адрес: Подвойского ул, Санкт-Петербург

Геокодирование:  95%|█████████▍| 18985/19990 [1:26:19<16:38,  1.01it/s]

[18985] Геокодируем адрес: 6-я линия ВО 21, Санкт-Петербург

Геокодирование:  95%|█████████▍| 18986/19990 [1:26:20<17:40,  1.06s/it]

[18986] Геокодируем адрес: 5-я линия ВО 30В, Санкт-Петербург

Геокодирование:  95%|█████████▍| 18987/19990 [1:26:21<18:26,  1.10s/it]

[18987] Геокодируем адрес: 8-я линия ВО 3, Санкт-Петербург

Геокодирование:  95%|█████████▍| 18988/19990 [1:26:22<16:37,  1.00it/s]

[18988] Геокодируем адрес: 6-я линия ВО 17, Санкт-Петербург

Геокодирование:  95%|█████████▍| 18989/19990 [1:26:23<16:38,  1.00it/s]

[18989] Геокодируем адрес: Петергоф Ботаническая ул 18к3, Санкт-Петербург

Геокодирование:  95%|█████████▍| 18990/19990 [1:26:24<16:11,  1.03it/s]

[18990] Геокодируем адрес: Рыбацкая ул, Санкт-Петербург

Геокодирование:  95%|█████████▌| 18991/19990 [1:26:25<16:51,  1.01s/it]

Автосохранение после 18990 строк...
[18991] Геокодируем адрес: Введенская ул 4, Санкт-Петербург

Геокодирование:  95%|█████████▌| 18992/19990 [1:26:26<16:18,  1.02it/s]

[18992] Геокодируем адрес: 4-я Красноармейская ул, Санкт-Петербург

Геокодирование:  95%|█████████▌| 18993/19990 [1:26:27<16:12,  1.02it/s]

[18993] Геокодируем адрес: Скобелевский пр-т 18, Санкт-Петербург

Геокодирование:  95%|█████████▌| 18994/19990 [1:26:28<17:05,  1.03s/it]

[18994] Геокодируем адрес: Большой пр-т 41к2, Санкт-Петербург

Геокодирование:  95%|█████████▌| 18995/19990 [1:26:29<16:34,  1.00it/s]

[18995] Геокодируем адрес: Союза Печатников ул 8, Санкт-Петербург

Геокодирование:  95%|█████████▌| 18996/19990 [1:26:30<16:21,  1.01it/s]

[18996] Геокодируем адрес: Краснопутиловская ул 100, Санкт-Петербург

Геокодирование:  95%|█████████▌| 18997/19990 [1:26:31<16:08,  1.03it/s]

[18997] Геокодируем адрес: Коллонтай ул 24к2, Санкт-Петербург

Геокодирование:  95%|█████████▌| 18998/19990 [1:26:32<16:36,  1.00s/it]

[18998] Геокодируем адрес: Ветеранов пр-т 143к1, Санкт-Петербург

Геокодирование:  95%|█████████▌| 18999/19990 [1:26:33<16:18,  1.01it/s]

[18999] Геокодируем адрес: Петергоф Ольгинское ш 41, Санкт-Петербург

Геокодирование:  95%|█████████▌| 19000/19990 [1:26:34<16:43,  1.01s/it]

[19000] Геокодируем адрес: Композиторов ул, Санкт-Петербург

Геокодирование:  95%|█████████▌| 19001/19990 [1:26:35<16:05,  1.02it/s]

[19001] Геокодируем адрес: Большой пр-т 88, Санкт-Петербург

Геокодирование:  95%|█████████▌| 19002/19990 [1:26:36<18:25,  1.12s/it]

[19002] Геокодируем адрес: Искровский пр-т, Санкт-Петербург

Геокодирование:  95%|█████████▌| 19003/19990 [1:26:37<16:12,  1.01it/s]

[19003] Геокодируем адрес: Введенская ул 6, Санкт-Петербург

Геокодирование:  95%|█████████▌| 19004/19990 [1:26:38<16:02,  1.02it/s]

[19004] Геокодируем адрес: nan

Геокодирование:  95%|█████████▌| 19005/19990 [1:26:39<15:52,  1.03it/s]

[19005] Геокодируем адрес: nan

Геокодирование:  95%|█████████▌| 19006/19990 [1:26:40<16:03,  1.02it/s]

[19006] Геокодируем адрес: Ленсовета ул, Санкт-Петербург

Геокодирование:  95%|█████████▌| 19007/19990 [1:26:41<16:13,  1.01it/s]

[19007] Геокодируем адрес: Благодатная ул 31, Санкт-Петербург

Геокодирование:  95%|█████████▌| 19008/19990 [1:26:42<16:33,  1.01s/it]

[19008] Геокодируем адрес: Шостаковича ул 1/9, Санкт-Петербург

Геокодирование:  95%|█████████▌| 19009/19990 [1:26:43<16:51,  1.03s/it]

[19009] Геокодируем адрес: Ветеранов пр-т 143к1, Санкт-Петербург

Геокодирование:  95%|█████████▌| 19010/19990 [1:26:44<16:13,  1.01it/s]

[19010] Геокодируем адрес: Тельмана ул 44, Санкт-Петербург

Геокодирование:  95%|█████████▌| 19011/19990 [1:26:45<17:01,  1.04s/it]

[19011] Геокодируем адрес: nan

Геокодирование:  95%|█████████▌| 19012/19990 [1:26:46<15:43,  1.04it/s]

[19012] Геокодируем адрес: Кокколевская ул 9с1, Санкт-Петербург

Геокодирование:  95%|█████████▌| 19013/19990 [1:26:47<16:06,  1.01it/s]

[19013] Геокодируем адрес: nan

Геокодирование:  95%|█████████▌| 19014/19990 [1:26:48<15:59,  1.02it/s]

[19014] Геокодируем адрес: Ударников пр-т 28/32, Санкт-Петербург

Геокодирование:  95%|█████████▌| 19015/19990 [1:26:49<16:57,  1.04s/it]

[19015] Геокодируем адрес: Кокколевская ул 9с1, Санкт-Петербург

Геокодирование:  95%|█████████▌| 19016/19990 [1:26:50<16:00,  1.01it/s]

[19016] Геокодируем адрес: Биржевой пер, Санкт-Петербург

Геокодирование:  95%|█████████▌| 19017/19990 [1:26:51<15:53,  1.02it/s]

[19017] Геокодируем адрес: nan

Геокодирование:  95%|█████████▌| 19018/19990 [1:26:52<15:52,  1.02it/s]

[19018] Геокодируем адрес: Среднерогатская ул 13, Санкт-Петербург

Геокодирование:  95%|█████████▌| 19019/19990 [1:26:53<16:28,  1.02s/it]

[19019] Геокодируем адрес: nan

Геокодирование:  95%|█████████▌| 19020/19990 [1:26:54<15:52,  1.02it/s]

[19020] Геокодируем адрес: Антокольский пер, Санкт-Петербург

Геокодирование:  95%|█████████▌| 19021/19990 [1:26:55<16:43,  1.04s/it]

Автосохранение после 19020 строк...
[19021] Геокодируем адрес: Будапештская ул, Санкт-Петербург

Геокодирование:  95%|█████████▌| 19022/19990 [1:26:56<15:50,  1.02it/s]

[19022] Геокодируем адрес: Будапештская ул, Санкт-Петербург

Геокодирование:  95%|█████████▌| 19023/19990 [1:26:57<15:56,  1.01it/s]

[19023] Геокодируем адрес: Косая линия ВО, Санкт-Петербург

Геокодирование:  95%|█████████▌| 19024/19990 [1:26:58<16:01,  1.00it/s]

[19024] Геокодируем адрес: Тепловозная ул 52, Санкт-Петербург

Геокодирование:  95%|█████████▌| 19025/19990 [1:26:59<16:08,  1.00s/it]

[19025] Геокодируем адрес: Шелгунова ул, Санкт-Петербург

Геокодирование:  95%|█████████▌| 19026/19990 [1:27:00<15:58,  1.01it/s]

[19026] Геокодируем адрес: Тверская ул 18, Санкт-Петербург

Геокодирование:  95%|█████████▌| 19027/19990 [1:27:01<16:15,  1.01s/it]

[19027] Геокодируем адрес: Тверская ул 18, Санкт-Петербург

Геокодирование:  95%|█████████▌| 19028/19990 [1:27:02<16:15,  1.01s/it]

[19028] Геокодируем адрес: Московский пр-т, Санкт-Петербург

Геокодирование:  95%|█████████▌| 19029/19990 [1:27:03<16:09,  1.01s/it]

[19029] Геокодируем адрес: 6-я линия ВО, Санкт-Петербург

Геокодирование:  95%|█████████▌| 19030/19990 [1:27:04<18:17,  1.14s/it]

[19030] Геокодируем адрес: Витебский пр-т, Санкт-Петербург

Геокодирование:  95%|█████████▌| 19031/19990 [1:27:05<15:49,  1.01it/s]

[19031] Геокодируем адрес: Александра Матросова ул 3стр1, Санкт-Петербург

Геокодирование:  95%|█████████▌| 19032/19990 [1:27:06<15:51,  1.01it/s]

[19032] Геокодируем адрес: nan

Геокодирование:  95%|█████████▌| 19033/19990 [1:27:07<15:46,  1.01it/s]

[19033] Геокодируем адрес: Солдатский пер, Санкт-Петербург

Геокодирование:  95%|█████████▌| 19034/19990 [1:27:08<15:47,  1.01it/s]

[19034] Геокодируем адрес: nan

Геокодирование:  95%|█████████▌| 19035/19990 [1:27:09<15:42,  1.01it/s]

[19035] Геокодируем адрес: Кожевенная линия ВО, Санкт-Петербург

Геокодирование:  95%|█████████▌| 19036/19990 [1:27:10<15:58,  1.01s/it]

[19036] Геокодируем адрес: nan

Геокодирование:  95%|█████████▌| 19037/19990 [1:27:11<15:40,  1.01it/s]

[19037] Геокодируем адрес: Косая линия ВО, Санкт-Петербург

Геокодирование:  95%|█████████▌| 19038/19990 [1:27:12<16:07,  1.02s/it]

[19038] Геокодируем адрес: Косая линия ВО, Санкт-Петербург

Геокодирование:  95%|█████████▌| 19039/19990 [1:27:13<15:47,  1.00it/s]

[19039] Геокодируем адрес: Посадская ул 4, Санкт-Петербург

Геокодирование:  95%|█████████▌| 19040/19990 [1:27:14<15:55,  1.01s/it]

[19040] Геокодируем адрес: Дунайский пр-т 34, Санкт-Петербург

Геокодирование:  95%|█████████▌| 19041/19990 [1:27:15<16:50,  1.07s/it]

[19041] Геокодируем адрес: nan

Геокодирование:  95%|█████████▌| 19042/19990 [1:27:16<15:17,  1.03it/s]

[19042] Геокодируем адрес: Хлопина ул, Санкт-Петербург

Геокодирование:  95%|█████████▌| 19043/19990 [1:27:17<15:30,  1.02it/s]

[19043] Геокодируем адрес: Богатырский пр-т, Санкт-Петербург

Геокодирование:  95%|█████████▌| 19044/19990 [1:27:18<16:03,  1.02s/it]

[19044] Геокодируем адрес: Демьяна Бедного ул, Санкт-Петербург

Геокодирование:  95%|█████████▌| 19045/19990 [1:27:19<15:37,  1.01it/s]

[19045] Геокодируем адрес: Маршала Захарова ул 9, Санкт-Петербург

Геокодирование:  95%|█████████▌| 19046/19990 [1:27:20<16:19,  1.04s/it]

[19046] Геокодируем адрес: nan

Геокодирование:  95%|█████████▌| 19047/19990 [1:27:21<15:12,  1.03it/s]

[19047] Геокодируем адрес: Оптиков ул, Санкт-Петербург

Геокодирование:  95%|█████████▌| 19048/19990 [1:27:22<15:27,  1.02it/s]

[19048] Геокодируем адрес: Сердобольская ул 5, Санкт-Петербург

Геокодирование:  95%|█████████▌| 19049/19990 [1:27:23<15:34,  1.01it/s]

[19049] Геокодируем адрес: Новоладожская ул, Санкт-Петербург

Геокодирование:  95%|█████████▌| 19050/19990 [1:27:24<15:33,  1.01it/s]

[19050] Геокодируем адрес: Витебский пр-т 31к1, Санкт-Петербург

Геокодирование:  95%|█████████▌| 19051/19990 [1:27:25<16:51,  1.08s/it]

Автосохранение после 19050 строк...
[19051] Геокодируем адрес: Волковский пр-т 144, Санкт-Петербург

Геокодирование:  95%|█████████▌| 19052/19990 [1:27:26<15:59,  1.02s/it]

[19052] Геокодируем адрес: Художников пр-т 31к1, Санкт-Петербург

Геокодирование:  95%|█████████▌| 19053/19990 [1:27:27<15:27,  1.01it/s]

[19053] Геокодируем адрес: Медиков пр-т 10к5, Санкт-Петербург

Геокодирование:  95%|█████████▌| 19054/19990 [1:27:28<15:10,  1.03it/s]

[19054] Геокодируем адрес: Правды ул 22, Санкт-Петербург

Геокодирование:  95%|█████████▌| 19055/19990 [1:27:29<16:01,  1.03s/it]

[19055] Геокодируем адрес: Полевая Сабировская ул Полевая Сабировская, Санкт-Петербург

Геокодирование:  95%|█████████▌| 19056/19990 [1:27:30<15:10,  1.03it/s]

[19056] Геокодируем адрес: Комендантский пр-т 13к1, Санкт-Петербург

Геокодирование:  95%|█████████▌| 19057/19990 [1:27:31<15:34,  1.00s/it]

[19057] Геокодируем адрес: Богатырский пр-т 9, Санкт-Петербург

Геокодирование:  95%|█████████▌| 19058/19990 [1:27:32<15:58,  1.03s/it]

[19058] Геокодируем адрес: Крыленко ул 45, Санкт-Петербург

Геокодирование:  95%|█████████▌| 19059/19990 [1:27:33<15:20,  1.01it/s]

[19059] Геокодируем адрес: Александра Матросова ул 1с1, Санкт-Петербург

Геокодирование:  95%|█████████▌| 19060/19990 [1:27:34<15:36,  1.01s/it]

[19060] Геокодируем адрес: Спортивная ул, Санкт-Петербург

Геокодирование:  95%|█████████▌| 19061/19990 [1:27:35<15:13,  1.02it/s]

[19061] Геокодируем адрес: nan

Геокодирование:  95%|█████████▌| 19062/19990 [1:27:36<14:52,  1.04it/s]

[19062] Геокодируем адрес: Пионерская ул, Санкт-Петербург

Геокодирование:  95%|█████████▌| 19063/19990 [1:27:37<15:40,  1.01s/it]

[19063] Геокодируем адрес: nan

Геокодирование:  95%|█████████▌| 19064/19990 [1:27:38<14:59,  1.03it/s]

[19064] Геокодируем адрес: Александровской Фермы ул 3к2, Санкт-Петербург

Геокодирование:  95%|█████████▌| 19065/19990 [1:27:39<15:48,  1.03s/it]

[19065] Геокодируем адрес: наличная ул 37к4, Санкт-Петербург

Геокодирование:  95%|█████████▌| 19066/19990 [1:27:40<15:09,  1.02it/s]

[19066] Геокодируем адрес: Маяковского ул 52, Санкт-Петербург

Геокодирование:  95%|█████████▌| 19067/19990 [1:27:41<16:30,  1.07s/it]

[19067] Геокодируем адрес: Шостаковича ул 5к1, Санкт-Петербург

Геокодирование:  95%|█████████▌| 19068/19990 [1:27:42<15:17,  1.00it/s]

[19068] Геокодируем адрес: Евгения Шварца ал 12стр11, Санкт-Петербург

Геокодирование:  95%|█████████▌| 19069/19990 [1:27:43<14:35,  1.05it/s]

[19069] Геокодируем адрес: Александра Матросова ул 1с1, Санкт-Петербург

Геокодирование:  95%|█████████▌| 19070/19990 [1:27:44<15:39,  1.02s/it]

[19070] Геокодируем адрес: Ворошилова ул 25к1, Санкт-Петербург

Геокодирование:  95%|█████████▌| 19071/19990 [1:27:45<15:25,  1.01s/it]

[19071] Геокодируем адрес: Маршала Блюхера пр-т 51к1, Санкт-Петербург

Геокодирование:  95%|█████████▌| 19072/19990 [1:27:46<15:32,  1.02s/it]

[19072] Геокодируем адрес: Косая линия ВО 24/25, Санкт-Петербург

Геокодирование:  95%|█████████▌| 19073/19990 [1:27:47<15:39,  1.02s/it]

[19073] Геокодируем адрес: Александра Матросова ул 1с1, Санкт-Петербург

Геокодирование:  95%|█████████▌| 19074/19990 [1:27:48<15:20,  1.01s/it]

[19074] Геокодируем адрес: Рощинская ул 11, Санкт-Петербург

Геокодирование:  95%|█████████▌| 19075/19990 [1:27:49<14:52,  1.03it/s]

[19075] Геокодируем адрес: Подвойского ул 20к1, Санкт-Петербург

Геокодирование:  95%|█████████▌| 19076/19990 [1:27:50<14:58,  1.02it/s]

[19076] Геокодируем адрес: Московский пр-т 199, Санкт-Петербург

Геокодирование:  95%|█████████▌| 19077/19990 [1:27:51<15:41,  1.03s/it]

[19077] Геокодируем адрес: Вокзальная ул 15кв1, Санкт-Петербург

Геокодирование:  95%|█████████▌| 19078/19990 [1:27:52<14:52,  1.02it/s]

[19078] Геокодируем адрес: Петровский остров, Санкт-Петербург

Геокодирование:  95%|█████████▌| 19079/19990 [1:27:53<14:33,  1.04it/s]

[19079] Геокодируем адрес: Колпино, Санкт-Петербург

Геокодирование:  95%|█████████▌| 19080/19990 [1:27:54<14:49,  1.02it/s]

[19080] Геокодируем адрес: Грибалевой ул 7к1, Санкт-Петербург

Геокодирование:  95%|█████████▌| 19081/19990 [1:27:55<16:00,  1.06s/it]

Автосохранение после 19080 строк...
[19081] Геокодируем адрес: Бабушкина ул 96, Санкт-Петербург

Геокодирование:  95%|█████████▌| 19082/19990 [1:27:56<15:06,  1.00it/s]

[19082] Геокодируем адрес: Большая Зеленина ул 10, Санкт-Петербург

Геокодирование:  95%|█████████▌| 19083/19990 [1:27:57<15:00,  1.01it/s]

[19083] Геокодируем адрес: г.Павловск, Санкт-Петербург

Геокодирование:  95%|█████████▌| 19084/19990 [1:27:58<15:02,  1.00it/s]

[19084] Геокодируем адрес: Кирпичный пер, Санкт-Петербург

Геокодирование:  95%|█████████▌| 19085/19990 [1:27:59<14:37,  1.03it/s]

[19085] Геокодируем адрес: Кирпичный пер, Санкт-Петербург

Геокодирование:  95%|█████████▌| 19086/19990 [1:28:00<14:45,  1.02it/s]

[19086] Геокодируем адрес: Петергоф Санкт-Петербургский пр-т, Санкт-Петербург

Геокодирование:  95%|█████████▌| 19087/19990 [1:28:01<15:07,  1.01s/it]

[19087] Геокодируем адрес: Олеко Дундича ул, Санкт-Петербург

Геокодирование:  95%|█████████▌| 19088/19990 [1:28:02<14:55,  1.01it/s]

[19088] Геокодируем адрес: nan

Геокодирование:  95%|█████████▌| 19089/19990 [1:28:03<14:42,  1.02it/s]

[19089] Геокодируем адрес: nan

Геокодирование:  95%|█████████▌| 19090/19990 [1:28:04<14:47,  1.01it/s]

[19090] Геокодируем адрес: nan

Геокодирование:  96%|█████████▌| 19091/19990 [1:28:05<14:50,  1.01it/s]

[19091] Геокодируем адрес: Прибрежная ул, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19092/19990 [1:28:06<15:00,  1.00s/it]

[19092] Геокодируем адрес: Обуховской Обороны пр-т 251, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19093/19990 [1:28:07<15:58,  1.07s/it]

[19093] Геокодируем адрес: Большой Сампсониевский пр-т, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19094/19990 [1:28:09<19:46,  1.32s/it]

[19094] Геокодируем адрес: Косая линия ВО 24/25, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19095/19990 [1:28:10<18:27,  1.24s/it]

[19095] Геокодируем адрес: Косая линия ВО, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19096/19990 [1:28:11<16:17,  1.09s/it]

[19096] Геокодируем адрес: Кожевенная линия ВО, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19097/19990 [1:28:12<15:56,  1.07s/it]

[19097] Геокодируем адрес: Маяковского ул 36-38, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19098/19990 [1:28:13<17:22,  1.17s/it]

[19098] Геокодируем адрес: Тореза пр-т 102к4, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19099/19990 [1:28:14<15:01,  1.01s/it]

[19099] Геокодируем адрес: Шушары Пушкинская ул 50, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19100/19990 [1:28:15<15:08,  1.02s/it]

[19100] Геокодируем адрес: тер Ленсоветовский 31, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19101/19990 [1:28:16<15:17,  1.03s/it]

[19101] Геокодируем адрес: Суздальское ш 30к2, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19102/19990 [1:28:18<19:25,  1.31s/it]

[19102] Геокодируем адрес: реки Фонтанки наб 201, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19103/19990 [1:28:19<18:06,  1.23s/it]

[19103] Геокодируем адрес: Суздальское ш 30к2, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19104/19990 [1:28:20<16:40,  1.13s/it]

[19104] Геокодируем адрес: nan

Геокодирование:  96%|█████████▌| 19105/19990 [1:28:21<15:49,  1.07s/it]

[19105] Геокодируем адрес: nan

Геокодирование:  96%|█████████▌| 19106/19990 [1:28:22<15:33,  1.06s/it]

[19106] Геокодируем адрес: Суздальский пр-т 73, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19107/19990 [1:28:23<16:15,  1.10s/it]

[19107] Геокодируем адрес: Ильюшина ул, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19108/19990 [1:28:24<14:48,  1.01s/it]

[19108] Геокодируем адрес: Ильюшина ул, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19109/19990 [1:28:25<14:52,  1.01s/it]

[19109] Геокодируем адрес: 1-я линия ВО, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19110/19990 [1:28:27<21:32,  1.47s/it]

[19110] Геокодируем адрес: Октябрьская наб 38к3, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19111/19990 [1:28:28<18:32,  1.27s/it]

Автосохранение после 19110 строк...
[19111] Геокодируем адрес: Народного Ополчения пр-т 67, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19112/19990 [1:28:29<17:26,  1.19s/it]

[19112] Геокодируем адрес: Малый пр-т 6Б, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19113/19990 [1:28:30<16:56,  1.16s/it]

[19113] Геокодируем адрес: nan

Геокодирование:  96%|█████████▌| 19114/19990 [1:28:31<15:03,  1.03s/it]

[19114] Геокодируем адрес: Богатырский пр-т, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19115/19990 [1:28:32<15:04,  1.03s/it]

[19115] Геокодируем адрес: Путиловская наб, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19116/19990 [1:28:33<14:38,  1.01s/it]

[19116] Геокодируем адрес: Малый пр-т, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19117/19990 [1:28:35<19:23,  1.33s/it]

[19117] Геокодируем адрес: Планерная ул, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19118/19990 [1:28:36<17:36,  1.21s/it]

[19118] Геокодируем адрес: Мебельная ул, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19119/19990 [1:28:37<16:33,  1.14s/it]

[19119] Геокодируем адрес: Шушарская дор, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19120/19990 [1:28:38<15:58,  1.10s/it]

[19120] Геокодируем адрес: Земский пер, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19121/19990 [1:28:39<15:28,  1.07s/it]

[19121] Геокодируем адрес: nan

Геокодирование:  96%|█████████▌| 19122/19990 [1:28:40<15:03,  1.04s/it]

[19122] Геокодируем адрес: nan

Геокодирование:  96%|█████████▌| 19123/19990 [1:28:41<14:50,  1.03s/it]

[19123] Геокодируем адрес: nan

Геокодирование:  96%|█████████▌| 19124/19990 [1:28:42<14:45,  1.02s/it]

[19124] Геокодируем адрес: Обводного Канала наб, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19125/19990 [1:28:43<14:47,  1.03s/it]

[19125] Геокодируем адрес: Артиллерийская ул, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19126/19990 [1:28:44<14:35,  1.01s/it]

[19126] Геокодируем адрес: Ропшинское ш, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19127/19990 [1:28:45<14:36,  1.02s/it]

[19127] Геокодируем адрес: Павловск, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19128/19990 [1:28:46<14:25,  1.00s/it]

[19128] Геокодируем адрес: Комендантский пр-т, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19129/19990 [1:28:47<14:41,  1.02s/it]

[19129] Геокодируем адрес: Новочеркасский пр-т, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19130/19990 [1:28:48<14:20,  1.00s/it]

[19130] Геокодируем адрес: Биржевой пер, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19131/19990 [1:28:49<14:17,  1.00it/s]

[19131] Геокодируем адрес: Старорусский пр-т, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19132/19990 [1:28:50<14:42,  1.03s/it]

[19132] Геокодируем адрес: Тучков пер 11/5, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19133/19990 [1:28:51<14:21,  1.01s/it]

[19133] Геокодируем адрес: Биржевой, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19134/19990 [1:28:52<14:06,  1.01it/s]

[19134] Геокодируем адрес: Ленинский пр-т 130/6, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19135/19990 [1:28:53<15:40,  1.10s/it]

[19135] Геокодируем адрес: Дальневосточный пр-т, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19136/19990 [1:28:54<14:11,  1.00it/s]

[19136] Геокодируем адрес: Федюнинского ул, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19137/19990 [1:28:55<13:43,  1.04it/s]

[19137] Геокодируем адрес: Рябовское ш, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19138/19990 [1:28:56<13:50,  1.03it/s]

[19138] Геокодируем адрес: Старорогатская ул 13/1, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19139/19990 [1:28:57<13:45,  1.03it/s]

[19139] Геокодируем адрес: Парашютная ул 61к4, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19140/19990 [1:28:58<14:11,  1.00s/it]

[19140] Геокодируем адрес: Новостроек ул 11, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19141/19990 [1:29:00<19:01,  1.34s/it]

Автосохранение после 19140 строк...
[19141] Геокодируем адрес: Взлетная ул 13, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19142/19990 [1:29:01<16:56,  1.20s/it]

[19142] Геокодируем адрес: Школьная ул, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19143/19990 [1:29:02<17:13,  1.22s/it]

[19143] Геокодируем адрес: Руднева ул, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19144/19990 [1:29:03<15:02,  1.07s/it]

[19144] Геокодируем адрес: nan

Геокодирование:  96%|█████████▌| 19145/19990 [1:29:04<14:31,  1.03s/it]

[19145] Геокодируем адрес: Авиаконструкторов пр-т 4к1, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19146/19990 [1:29:05<14:57,  1.06s/it]

[19146] Геокодируем адрес: Костюшко ул 72, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19147/19990 [1:29:06<14:38,  1.04s/it]

[19147] Геокодируем адрес: Костюшко ул 13, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19148/19990 [1:29:07<14:15,  1.02s/it]

[19148] Геокодируем адрес: Дачный пр-т, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19149/19990 [1:29:08<14:24,  1.03s/it]

[19149] Геокодируем адрес: Левашовский пр-т, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19150/19990 [1:29:09<13:56,  1.00it/s]

[19150] Геокодируем адрес: Школьная ул, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19151/19990 [1:29:10<15:08,  1.08s/it]

[19151] Геокодируем адрес: Энгельса пр-т 94к2, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19152/19990 [1:29:11<13:47,  1.01it/s]

[19152] Геокодируем адрес: Школьная ул, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19153/19990 [1:29:12<14:33,  1.04s/it]

[19153] Геокодируем адрес: Балтийский б-р, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19154/19990 [1:29:13<13:50,  1.01it/s]

[19154] Геокодируем адрес: Советский пр-т, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19155/19990 [1:29:14<14:05,  1.01s/it]

[19155] Геокодируем адрес: Парголовский пер, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19156/19990 [1:29:15<13:09,  1.06it/s]

[19156] Геокодируем адрес: Латышских Стрелков ул, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19157/19990 [1:29:16<13:33,  1.02it/s]

[19157] Геокодируем адрес: канала Грибоедова наб, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19158/19990 [1:29:17<13:33,  1.02it/s]

[19158] Геокодируем адрес: проспект Энгельса 120Д, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19159/19990 [1:29:18<13:59,  1.01s/it]

[19159] Геокодируем адрес: Новочеркасский пр-т, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19160/19990 [1:29:19<13:39,  1.01it/s]

[19160] Геокодируем адрес: Беговая ул, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19161/19990 [1:29:20<13:34,  1.02it/s]

[19161] Геокодируем адрес: Шушары Окуловская ул, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19162/19990 [1:29:21<13:47,  1.00it/s]

[19162] Геокодируем адрес: Костюшко ул 11, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19163/19990 [1:29:22<14:03,  1.02s/it]

[19163] Геокодируем адрес: Костюшко ул, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19164/19990 [1:29:23<13:29,  1.02it/s]

[19164] Геокодируем адрес: Энгельса пр-т 94к1, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19165/19990 [1:29:24<13:47,  1.00s/it]

[19165] Геокодируем адрес: Костюшко ул 15, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19166/19990 [1:29:25<13:48,  1.01s/it]

[19166] Геокодируем адрес: Лиговский пр-т 91, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19167/19990 [1:29:26<14:04,  1.03s/it]

[19167] Геокодируем адрес: Варшавская ул 73, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19168/19990 [1:29:27<13:27,  1.02it/s]

[19168] Геокодируем адрес: Энгельса пр-т, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19169/19990 [1:29:28<14:02,  1.03s/it]

[19169] Геокодируем адрес: nan

Геокодирование:  96%|█████████▌| 19170/19990 [1:29:29<13:10,  1.04it/s]

[19170] Геокодируем адрес: Костюшко ул 84, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19171/19990 [1:29:30<14:17,  1.05s/it]

Автосохранение после 19170 строк...
[19171] Геокодируем адрес: Октябрьская наб, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19172/19990 [1:29:31<13:12,  1.03it/s]

[19172] Геокодируем адрес: Пушкин Белозёрки пер 9, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19173/19990 [1:29:32<13:44,  1.01s/it]

[19173] Геокодируем адрес: Костюшко ул 30, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19174/19990 [1:29:33<13:51,  1.02s/it]

[19174] Геокодируем адрес: nan

Геокодирование:  96%|█████████▌| 19175/19990 [1:29:34<13:10,  1.03it/s]

[19175] Геокодируем адрес: Костюшко ул 22, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19176/19990 [1:29:35<13:46,  1.02s/it]

[19176] Геокодируем адрес: Чайковского ул 81, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19177/19990 [1:29:36<13:57,  1.03s/it]

[19177] Геокодируем адрес: 2-я Советская ул 12, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19178/19990 [1:29:37<13:50,  1.02s/it]

[19178] Геокодируем адрес: Маршала Блюхера пр-т, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19179/19990 [1:29:38<13:38,  1.01s/it]

[19179] Геокодируем адрес: 2-я Советская ул 25/2, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19180/19990 [1:29:39<13:23,  1.01it/s]

[19180] Геокодируем адрес: Двадцать Пятого Октября пр-т, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19181/19990 [1:29:40<13:42,  1.02s/it]

[19181] Геокодируем адрес: Королева пр-т, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19182/19990 [1:29:41<13:15,  1.02it/s]

[19182] Геокодируем адрес: Энгельса пр-т 124к1, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19183/19990 [1:29:42<13:11,  1.02it/s]

[19183] Геокодируем адрес: nan

Геокодирование:  96%|█████████▌| 19184/19990 [1:29:43<12:48,  1.05it/s]

[19184] Геокодируем адрес: Пулковское ш, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19185/19990 [1:29:44<13:14,  1.01it/s]

[19185] Геокодируем адрес: Петербургское ш, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19186/19990 [1:29:45<13:13,  1.01it/s]

[19186] Геокодируем адрес: Софийская ул, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19187/19990 [1:29:46<13:12,  1.01it/s]

[19187] Геокодируем адрес: Костюшко ул 15, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19188/19990 [1:29:47<13:31,  1.01s/it]

[19188] Геокодируем адрес: Петербургское ш, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19189/19990 [1:29:48<13:12,  1.01it/s]

[19189] Геокодируем адрес: Александровской Фермы пр-т 4, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19190/19990 [1:29:49<14:07,  1.06s/it]

[19190] Геокодируем адрес: Боровая ул 11-13, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19191/19990 [1:29:50<13:08,  1.01it/s]

[19191] Геокодируем адрес: 5-я Советская ул 11-13, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19192/19990 [1:29:51<13:15,  1.00it/s]

[19192] Геокодируем адрес: Семёнова-Тян-Шанского сквер, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19193/19990 [1:29:52<13:00,  1.02it/s]

[19193] Геокодируем адрес: Лёни Голикова ул 23к9, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19194/19990 [1:29:53<13:06,  1.01it/s]

[19194] Геокодируем адрес: nan

Геокодирование:  96%|█████████▌| 19195/19990 [1:29:54<13:02,  1.02it/s]

[19195] Геокодируем адрес: 5-я Советская ул 11-13, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19196/19990 [1:29:55<13:34,  1.03s/it]

[19196] Геокодируем адрес: nan

Геокодирование:  96%|█████████▌| 19197/19990 [1:29:56<12:52,  1.03it/s]

[19197] Геокодируем адрес: Обуховской Обороны пр-т 225, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19198/19990 [1:29:57<13:50,  1.05s/it]

[19198] Геокодируем адрес: Большая Пороховская ул 54к2, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19199/19990 [1:29:58<12:55,  1.02it/s]

[19199] Геокодируем адрес: nan

Геокодирование:  96%|█████████▌| 19200/19990 [1:29:59<12:47,  1.03it/s]

[19200] Геокодируем адрес: Шлиссельбургский пр-т, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19201/19990 [1:30:00<13:55,  1.06s/it]

Автосохранение после 19200 строк...
[19201] Геокодируем адрес: Некрасова ул 25, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19202/19990 [1:30:01<13:40,  1.04s/it]

[19202] Геокодируем адрес: Шушары Окуловская ул 4, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19203/19990 [1:30:02<12:54,  1.02it/s]

[19203] Геокодируем адрес: Петергоф Ропшинское ш 3к8, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19204/19990 [1:30:03<12:50,  1.02it/s]

[19204] Геокодируем адрес: Ленинский пр-т 134, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19205/19990 [1:30:04<13:58,  1.07s/it]

[19205] Геокодируем адрес: Нахимова ул 11 кв129, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19206/19990 [1:30:05<12:42,  1.03it/s]

[19206] Геокодируем адрес: Будапештская ул 69к2, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19207/19990 [1:30:06<12:30,  1.04it/s]

[19207] Геокодируем адрес: nan

Геокодирование:  96%|█████████▌| 19208/19990 [1:30:07<12:34,  1.04it/s]

[19208] Геокодируем адрес: Савушкина ул 143к2, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19209/19990 [1:30:08<13:00,  1.00it/s]

[19209] Геокодируем адрес: Школьная ул 128, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19210/19990 [1:30:09<14:19,  1.10s/it]

[19210] Геокодируем адрес: Фарфоровская ул 24, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19211/19990 [1:30:10<12:31,  1.04it/s]

[19211] Геокодируем адрес: Барочная ул, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19212/19990 [1:30:11<12:51,  1.01it/s]

[19212] Геокодируем адрес: Энгельса пр-т 130к1, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19213/19990 [1:30:12<12:51,  1.01it/s]

[19213] Геокодируем адрес: Барочная ул 8, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19214/19990 [1:30:13<12:41,  1.02it/s]

[19214] Геокодируем адрес: Левашовский пр-т 13, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19215/19990 [1:30:14<13:31,  1.05s/it]

[19215] Геокодируем адрес: Просвещения пр-т 53к2, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19216/19990 [1:30:15<12:30,  1.03it/s]

[19216] Геокодируем адрес: Кронштадт Зосимова ул 4, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19217/19990 [1:30:16<12:49,  1.00it/s]

[19217] Геокодируем адрес: Дмитровский пер 8, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19218/19990 [1:30:17<12:46,  1.01it/s]

[19218] Геокодируем адрес: Басков пер 22, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19219/19990 [1:30:18<12:56,  1.01s/it]

[19219] Геокодируем адрес: Среднеохтинский пр-т 25/19, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19220/19990 [1:30:20<17:15,  1.34s/it]

[19220] Геокодируем адрес: Малый Петроградской стороны пр-т, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19221/19990 [1:30:21<15:31,  1.21s/it]

[19221] Геокодируем адрес: Хрустальная ул, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19222/19990 [1:30:22<14:11,  1.11s/it]

[19222] Геокодируем адрес: Невский пр-т 175, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19223/19990 [1:30:23<14:21,  1.12s/it]

[19223] Геокодируем адрес: Трудящихся б-р 17, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19224/19990 [1:30:24<13:32,  1.06s/it]

[19224] Геокодируем адрес: Путиловская наб, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19225/19990 [1:30:25<12:58,  1.02s/it]

[19225] Геокодируем адрес: Вяеслава Шишкова ул, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19226/19990 [1:30:26<12:40,  1.00it/s]

[19226] Геокодируем адрес: nan

Геокодирование:  96%|█████████▌| 19227/19990 [1:30:27<12:50,  1.01s/it]

[19227] Геокодируем адрес: Малая митрофаньевская ул 10к4, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19228/19990 [1:30:28<12:56,  1.02s/it]

[19228] Геокодируем адрес: Крупской ул 24к2, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19229/19990 [1:30:29<13:10,  1.04s/it]

[19229] Геокодируем адрес: Тамбасова ул 29к2, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19230/19990 [1:30:30<12:58,  1.02s/it]

[19230] Геокодируем адрес: Ланское ш 12к1, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19231/19990 [1:30:31<13:15,  1.05s/it]

Автосохранение после 19230 строк...
[19231] Геокодируем адрес: Ланское ш 12к1, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19232/19990 [1:30:32<12:28,  1.01it/s]

[19232] Геокодируем адрес: nan

Геокодирование:  96%|█████████▌| 19233/19990 [1:30:33<12:19,  1.02it/s]

[19233] Геокодируем адрес: реки Карповки наб 20, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19234/19990 [1:30:34<12:42,  1.01s/it]

[19234] Геокодируем адрес: nan

Геокодирование:  96%|█████████▌| 19235/19990 [1:30:35<12:13,  1.03it/s]

[19235] Геокодируем адрес: Стойкости ул 18к2, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19236/19990 [1:30:36<12:28,  1.01it/s]

[19236] Геокодируем адрес: Канонерский парк, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19237/19990 [1:30:37<12:33,  1.00s/it]

[19237] Геокодируем адрес: Варшавская ул 108, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19238/19990 [1:30:38<12:39,  1.01s/it]

[19238] Геокодируем адрес: Обуховской Обороны пр-т, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19239/19990 [1:30:39<12:58,  1.04s/it]

[19239] Геокодируем адрес: Энгельса пр-т, Санкт-Петербург

Геокодирование:  96%|█████████▌| 19240/19990 [1:30:40<12:41,  1.01s/it]

[19240] Геокодируем адрес: Планерная ул 67к1, Санкт-Петербург

Геокодирование:  96%|█████████▋| 19241/19990 [1:30:41<12:20,  1.01it/s]

[19241] Геокодируем адрес: Октябрьский б-р 3, Санкт-Петербург

Геокодирование:  96%|█████████▋| 19242/19990 [1:30:42<13:38,  1.09s/it]

[19242] Геокодируем адрес: Курортная ул 31е, Санкт-Петербург

Геокодирование:  96%|█████████▋| 19243/19990 [1:30:43<12:21,  1.01it/s]

[19243] Геокодируем адрес: Зеленогорск Курортная ул 31, Санкт-Петербург

Геокодирование:  96%|█████████▋| 19244/19990 [1:30:44<12:12,  1.02it/s]

[19244] Геокодируем адрес: nan

Геокодирование:  96%|█████████▋| 19245/19990 [1:30:45<11:49,  1.05it/s]

[19245] Геокодируем адрес: Зеленогорск Курортная ул 31, Санкт-Петербург

Геокодирование:  96%|█████████▋| 19246/19990 [1:30:46<12:22,  1.00it/s]

[19246] Геокодируем адрес: nan

Геокодирование:  96%|█████████▋| 19247/19990 [1:30:47<11:52,  1.04it/s]

[19247] Геокодируем адрес: nan

Геокодирование:  96%|█████████▋| 19248/19990 [1:30:48<12:04,  1.02it/s]

[19248] Геокодируем адрес: nan

Геокодирование:  96%|█████████▋| 19249/19990 [1:30:49<12:06,  1.02it/s]

[19249] Геокодируем адрес: Новоизмайловский пр-т 26к3, Санкт-Петербург

Геокодирование:  96%|█████████▋| 19250/19990 [1:30:50<12:23,  1.01s/it]

[19250] Геокодируем адрес: Парголово Первого Мая ул 83, Санкт-Петербург

Геокодирование:  96%|█████████▋| 19251/19990 [1:30:51<12:43,  1.03s/it]

[19251] Геокодируем адрес: Шаврова ул 25к1, Санкт-Петербург

Геокодирование:  96%|█████████▋| 19252/19990 [1:30:52<12:22,  1.01s/it]

[19252] Геокодируем адрес: Московский пр-т 161, Санкт-Петербург

Геокодирование:  96%|█████████▋| 19253/19990 [1:30:53<13:35,  1.11s/it]

[19253] Геокодируем адрес: Виленский пер 6, Санкт-Петербург

Геокодирование:  96%|█████████▋| 19254/19990 [1:30:54<11:54,  1.03it/s]

[19254] Геокодируем адрес: Московский пр-т 163, Санкт-Петербург

Геокодирование:  96%|█████████▋| 19255/19990 [1:30:56<16:28,  1.34s/it]

[19255] Геокодируем адрес: Шаврова ул 25к1, Санкт-Петербург

Геокодирование:  96%|█████████▋| 19256/19990 [1:30:57<14:24,  1.18s/it]

[19256] Геокодируем адрес: Парголово, Санкт-Петербург

Геокодирование:  96%|█████████▋| 19257/19990 [1:30:58<13:32,  1.11s/it]

[19257] Геокодируем адрес: Королёва пр-т 9, Санкт-Петербург

Геокодирование:  96%|█████████▋| 19258/19990 [1:30:59<14:07,  1.16s/it]

[19258] Геокодируем адрес: nan

Геокодирование:  96%|█████████▋| 19259/19990 [1:31:00<12:26,  1.02s/it]

[19259] Геокодируем адрес: nan

Геокодирование:  96%|█████████▋| 19260/19990 [1:31:01<12:21,  1.02s/it]

[19260] Геокодируем адрес: Обуховской Обороны пр-т 99Е, Санкт-Петербург

Геокодирование:  96%|█████████▋| 19261/19990 [1:31:02<13:27,  1.11s/it]

Автосохранение после 19260 строк...
[19261] Геокодируем адрес: Пушкин Пушкинская ул 8, Санкт-Петербург

Геокодирование:  96%|█████████▋| 19262/19990 [1:31:03<12:31,  1.03s/it]

[19262] Геокодируем адрес: Ольги Берггольц ул, Санкт-Петербург

Геокодирование:  96%|█████████▋| 19263/19990 [1:31:04<11:53,  1.02it/s]

[19263] Геокодируем адрес: Большевиков пр-т 9к1, Санкт-Петербург

Геокодирование:  96%|█████████▋| 19264/19990 [1:31:05<11:58,  1.01it/s]

[19264] Геокодируем адрес: Ольги Берггольц ул 5к2Б, Санкт-Петербург

Геокодирование:  96%|█████████▋| 19265/19990 [1:31:06<12:01,  1.00it/s]

[19265] Геокодируем адрес: Политехническая ул 30к2, Санкт-Петербург

Геокодирование:  96%|█████████▋| 19266/19990 [1:31:07<12:02,  1.00it/s]

[19266] Геокодируем адрес: Большая Пороховская ул 48, Санкт-Петербург

Геокодирование:  96%|█████████▋| 19267/19990 [1:31:08<12:02,  1.00it/s]

[19267] Геокодируем адрес: Павловск, Санкт-Петербург

Геокодирование:  96%|█████████▋| 19268/19990 [1:31:09<11:57,  1.01it/s]

[19268] Геокодируем адрес: Шаврова ул 26, Санкт-Петербург

Геокодирование:  96%|█████████▋| 19269/19990 [1:31:10<12:27,  1.04s/it]

[19269] Геокодируем адрес: Елизарова пр-т 8к2Е, Санкт-Петербург

Геокодирование:  96%|█████████▋| 19270/19990 [1:31:11<11:34,  1.04it/s]

[19270] Геокодируем адрес: Казанская ул 15, Санкт-Петербург

Геокодирование:  96%|█████████▋| 19271/19990 [1:31:12<12:15,  1.02s/it]

[19271] Геокодируем адрес: Художников пр-т 26к4, Санкт-Петербург

Геокодирование:  96%|█████████▋| 19272/19990 [1:31:13<11:50,  1.01it/s]

[19272] Геокодируем адрес: Варшавская ул 108, Санкт-Петербург

Геокодирование:  96%|█████████▋| 19273/19990 [1:31:14<12:10,  1.02s/it]

[19273] Геокодируем адрес: Карпинского ул 34к5, Санкт-Петербург

Геокодирование:  96%|█████████▋| 19274/19990 [1:31:15<11:53,  1.00it/s]

[19274] Геокодируем адрес: Коломяжский пр-т 32, Санкт-Петербург

Геокодирование:  96%|█████████▋| 19275/19990 [1:31:17<15:44,  1.32s/it]

[19275] Геокодируем адрес: Саблинская ул, Санкт-Петербург

Геокодирование:  96%|█████████▋| 19276/19990 [1:31:18<14:04,  1.18s/it]

[19276] Геокодируем адрес: Лёни Голикова ул 23к3, Санкт-Петербург

Геокодирование:  96%|█████████▋| 19277/19990 [1:31:19<13:30,  1.14s/it]

[19277] Геокодируем адрес: Коломяжский пр-т 32, Санкт-Петербург

Геокодирование:  96%|█████████▋| 19278/19990 [1:31:20<13:24,  1.13s/it]

[19278] Геокодируем адрес: nan

Геокодирование:  96%|█████████▋| 19279/19990 [1:31:21<12:20,  1.04s/it]

[19279] Геокодируем адрес: Южная Роща сквер, Санкт-Петербург

Геокодирование:  96%|█████████▋| 19280/19990 [1:31:22<12:48,  1.08s/it]

[19280] Геокодируем адрес: nan

Геокодирование:  96%|█████████▋| 19281/19990 [1:31:23<11:53,  1.01s/it]

[19281] Геокодируем адрес: Южная Роща сквер, Санкт-Петербург

Геокодирование:  96%|█████████▋| 19282/19990 [1:31:24<12:19,  1.04s/it]

[19282] Геокодируем адрес: Южная Роща сквер, Санкт-Петербург

Геокодирование:  96%|█████████▋| 19283/19990 [1:31:25<12:07,  1.03s/it]

[19283] Геокодируем адрес: Автовская ул 48, Санкт-Петербург

Геокодирование:  96%|█████████▋| 19284/19990 [1:31:26<11:40,  1.01it/s]

[19284] Геокодируем адрес: Савушкина ул 3, Санкт-Петербург

Геокодирование:  96%|█████████▋| 19285/19990 [1:31:27<11:57,  1.02s/it]

[19285] Геокодируем адрес: Рыбацкий пр-т 18к2, Санкт-Петербург

Геокодирование:  96%|█████████▋| 19286/19990 [1:31:28<11:43,  1.00it/s]

[19286] Геокодируем адрес: nan

Геокодирование:  96%|█████████▋| 19287/19990 [1:31:29<11:26,  1.02it/s]

[19287] Геокодируем адрес: Коломяжский пр-т 32, Санкт-Петербург

Геокодирование:  96%|█████████▋| 19288/19990 [1:31:30<11:59,  1.03s/it]

[19288] Геокодируем адрес: Комендантский пр-т 13к1, Санкт-Петербург

Геокодирование:  96%|█████████▋| 19289/19990 [1:31:31<11:55,  1.02s/it]

[19289] Геокодируем адрес: Комендантский пр-т 55к1, Санкт-Петербург

Геокодирование:  96%|█████████▋| 19290/19990 [1:31:32<11:35,  1.01it/s]

[19290] Геокодируем адрес: Марата ул 77, Санкт-Петербург

Геокодирование:  97%|█████████▋| 19291/19990 [1:31:33<12:38,  1.08s/it]

Автосохранение после 19290 строк...
[19291] Геокодируем адрес: Металлострой Плановая ул 24, Санкт-Петербург

Геокодирование:  97%|█████████▋| 19292/19990 [1:31:34<11:29,  1.01it/s]

[19292] Геокодируем адрес: Комендантский пр-т 13к1, Санкт-Петербург

Геокодирование:  97%|█████████▋| 19293/19990 [1:31:35<11:31,  1.01it/s]

[19293] Геокодируем адрес: Кавалергардская ул 20, Санкт-Петербург

Геокодирование:  97%|█████████▋| 19294/19990 [1:31:36<11:12,  1.03it/s]

[19294] Геокодируем адрес: Комендантский пр-т 13к1, Санкт-Петербург

Геокодирование:  97%|█████████▋| 19295/19990 [1:31:37<11:39,  1.01s/it]

[19295] Геокодируем адрес: Адмирала Трибуца ул, Санкт-Петербург

Геокодирование:  97%|█████████▋| 19296/19990 [1:31:38<11:11,  1.03it/s]

[19296] Геокодируем адрес: Шевченко ул 24к2, Санкт-Петербург

Геокодирование:  97%|█████████▋| 19297/19990 [1:31:39<11:55,  1.03s/it]

[19297] Геокодируем адрес: Генерала Хазова ул 24, Санкт-Петербург

Геокодирование:  97%|█████████▋| 19298/19990 [1:31:40<11:28,  1.01it/s]

[19298] Геокодируем адрес: Ветеранов пр-т 3к3, Санкт-Петербург

Геокодирование:  97%|█████████▋| 19299/19990 [1:31:41<11:44,  1.02s/it]

[19299] Геокодируем адрес: Ленинский пр-т 56, Санкт-Петербург

Геокодирование:  97%|█████████▋| 19300/19990 [1:31:42<12:21,  1.07s/it]

[19300] Геокодируем адрес: Петропавловская ул 8, Санкт-Петербург

Геокодирование:  97%|█████████▋| 19301/19990 [1:31:43<10:52,  1.06it/s]

[19301] Геокодируем адрес: nan

Геокодирование:  97%|█████████▋| 19302/19990 [1:31:44<10:53,  1.05it/s]

[19302] Геокодируем адрес: Вавиловых ул 15к1, Санкт-Петербург

Геокодирование:  97%|█████████▋| 19303/19990 [1:31:45<11:15,  1.02it/s]

[19303] Геокодируем адрес: nan

Геокодирование:  97%|█████████▋| 19304/19990 [1:31:46<11:03,  1.03it/s]

[19304] Геокодируем адрес: Железнодорожная ул 44, Санкт-Петербург

Геокодирование:  97%|█████████▋| 19305/19990 [1:31:47<11:56,  1.05s/it]

[19305] Геокодируем адрес: nan

Геокодирование:  97%|█████████▋| 19306/19990 [1:31:48<11:01,  1.03it/s]

[19306] Геокодируем адрес: Народного Ополчения пр-т 97, Санкт-Петербург

Геокодирование:  97%|█████████▋| 19307/19990 [1:31:49<12:07,  1.07s/it]

[19307] Геокодируем адрес: терр. Красные Зори, Санкт-Петербург

Геокодирование:  97%|█████████▋| 19308/19990 [1:31:51<14:49,  1.30s/it]

[19308] Геокодируем адрес: Металлургов ул 13, Санкт-Петербург

Геокодирование:  97%|█████████▋| 19309/19990 [1:31:52<14:03,  1.24s/it]

[19309] Геокодируем адрес: nan

Геокодирование:  97%|█████████▋| 19310/19990 [1:31:53<12:38,  1.12s/it]

[19310] Геокодируем адрес: Пороховые, Санкт-Петербург

Геокодирование:  97%|█████████▋| 19311/19990 [1:31:54<12:22,  1.09s/it]

[19311] Геокодируем адрес: Марата ул 77, Санкт-Петербург

Геокодирование:  97%|█████████▋| 19312/19990 [1:31:55<12:18,  1.09s/it]

[19312] Геокодируем адрес: Южное ш, Санкт-Петербург

Геокодирование:  97%|█████████▋| 19313/19990 [1:31:56<11:38,  1.03s/it]

[19313] Геокодируем адрес: nan

Геокодирование:  97%|█████████▋| 19314/19990 [1:31:57<11:27,  1.02s/it]

[19314] Геокодируем адрес: nan

Геокодирование:  97%|█████████▋| 19315/19990 [1:31:58<11:25,  1.02s/it]

[19315] Геокодируем адрес: nan

Геокодирование:  97%|█████████▋| 19316/19990 [1:31:59<11:20,  1.01s/it]

[19316] Геокодируем адрес: Новаторов б-р 84, Санкт-Петербург

Геокодирование:  97%|█████████▋| 19317/19990 [1:32:00<12:00,  1.07s/it]

[19317] Геокодируем адрес: Петергоф Ропшинское ш 3к8, Санкт-Петербург

Геокодирование:  97%|█████████▋| 19318/19990 [1:32:01<11:15,  1.01s/it]

[19318] Геокодируем адрес: nan

Геокодирование:  97%|█████████▋| 19319/19990 [1:32:02<10:57,  1.02it/s]

[19319] Геокодируем адрес: Бурцева ул 20, Санкт-Петербург

Геокодирование:  97%|█████████▋| 19320/19990 [1:32:03<11:25,  1.02s/it]

[19320] Геокодируем адрес: Шушары, Санкт-Петербург

Геокодирование:  97%|█████████▋| 19321/19990 [1:32:04<11:28,  1.03s/it]

Автосохранение после 19320 строк...
[19321] Геокодируем адрес: nan

Геокодирование:  97%|█████████▋| 19322/19990 [1:32:05<10:51,  1.03it/s]

[19322] Геокодируем адрес: Шушары Пушкинская ул 10, Санкт-Петербург

Геокодирование:  97%|█████████▋| 19323/19990 [1:32:06<11:15,  1.01s/it]

[19323] Геокодируем адрес: Просвещения пр-т 23, Санкт-Петербург

Геокодирование:  97%|█████████▋| 19324/19990 [1:32:07<11:32,  1.04s/it]

[19324] Геокодируем адрес: nan

Геокодирование:  97%|█████████▋| 19325/19990 [1:32:08<10:41,  1.04it/s]

[19325] Геокодируем адрес: nan

Геокодирование:  97%|█████████▋| 19326/19990 [1:32:09<10:47,  1.03it/s]

[19326] Геокодируем адрес: Стачек пр-т 101к1, Санкт-Петербург

Геокодирование:  97%|█████████▋| 19327/19990 [1:32:10<10:59,  1.00it/s]

[19327] Геокодируем адрес: Лиственная ул 18к1, Санкт-Петербург

Геокодирование:  97%|█████████▋| 19328/19990 [1:32:11<11:04,  1.00s/it]

[19328] Геокодируем адрес: Беринга ул 24к1, Санкт-Петербург

Геокодирование:  97%|█████████▋| 19329/19990 [1:32:12<11:03,  1.00s/it]

[19329] Геокодируем адрес: Дыбенко ул 12к1Ж, Санкт-Петербург

Геокодирование:  97%|█████████▋| 19330/19990 [1:32:13<10:41,  1.03it/s]

[19330] Геокодируем адрес: nan

Геокодирование:  97%|█████████▋| 19331/19990 [1:32:14<10:54,  1.01it/s]

[19331] Геокодируем адрес: nan

Геокодирование:  97%|█████████▋| 19332/19990 [1:32:15<10:52,  1.01it/s]

[19332] Геокодируем адрес: nan

Геокодирование:  97%|█████████▋| 19333/19990 [1:32:16<10:51,  1.01it/s]

[19333] Геокодируем адрес: Реки Фонтанки наб 29/66, Санкт-Петербург

Геокодирование:  97%|█████████▋| 19334/19990 [1:32:17<11:08,  1.02s/it]

[19334] Геокодируем адрес: nan

Геокодирование:  97%|█████████▋| 19335/19990 [1:32:18<10:49,  1.01it/s]

[19335] Геокодируем адрес: Светлановский пр-т 95, Санкт-Петербург

Геокодирование:  97%|█████████▋| 19336/19990 [1:32:19<11:32,  1.06s/it]

[19336] Геокодируем адрес: Шушары Старорусский пр-т 13к1, Санкт-Петербург

Геокодирование:  97%|█████████▋| 19337/19990 [1:32:20<10:53,  1.00s/it]

[19337] Геокодируем адрес: nan

Геокодирование:  97%|█████████▋| 19338/19990 [1:32:21<10:37,  1.02it/s]

[19338] Геокодируем адрес: Школьная ул 15к1, Санкт-Петербург

Геокодирование:  97%|█████████▋| 19339/19990 [1:32:22<11:59,  1.11s/it]

[19339] Геокодируем адрес: Подводника Кузьмина ул 16, Санкт-Петербург

Геокодирование:  97%|█████████▋| 19340/19990 [1:32:23<10:37,  1.02it/s]

[19340] Геокодируем адрес: Большевиков пр-т 53к1, Санкт-Петербург

Геокодирование:  97%|█████████▋| 19341/19990 [1:32:24<10:27,  1.03it/s]

[19341] Геокодируем адрес: Большевиков пр-т 53к1, Санкт-Петербург

Геокодирование:  97%|█████████▋| 19342/19990 [1:32:25<10:33,  1.02it/s]

[19342] Геокодируем адрес: Конная ул 5/3, Санкт-Петербург

Геокодирование:  97%|█████████▋| 19343/19990 [1:32:26<10:42,  1.01it/s]

[19343] Геокодируем адрес: Корнеева ул 6, Санкт-Петербург

Геокодирование:  97%|█████████▋| 19344/19990 [1:32:27<10:42,  1.01it/s]

[19344] Геокодируем адрес: Искровский пр-т, Санкт-Петербург

Геокодирование:  97%|█████████▋| 19345/19990 [1:32:28<10:46,  1.00s/it]

[19345] Геокодируем адрес: Искровский пр-т, Санкт-Петербург

Геокодирование:  97%|█████████▋| 19346/19990 [1:32:29<10:51,  1.01s/it]

[19346] Геокодируем адрес: nan

Геокодирование:  97%|█████████▋| 19381/19990 [1:32:30<00:33, 18.44it/s]

Автосохранение после 19350 строк...
Автосохранение после 19380 строк...

Геокодирование:  97%|█████████▋| 19441/19990 [1:32:31<00:09, 57.15it/s]

Автосохранение после 19410 строк...
Автосохранение после 19440 строк...

Геокодирование:  98%|█████████▊| 19501/19990 [1:32:31<00:05, 93.41it/s]

Автосохранение после 19470 строк...
Автосохранение после 19500 строк...

Геокодирование:  98%|█████████▊| 19561/19990 [1:32:31<00:03, 125.19it/s]

Автосохранение после 19530 строк...
Автосохранение после 19560 строк...

Геокодирование:  98%|█████████▊| 19621/19990 [1:32:32<00:02, 147.39it/s]

Автосохранение после 19590 строк...
Автосохранение после 19620 строк...

Геокодирование:  98%|█████████▊| 19681/19990 [1:32:32<00:01, 166.65it/s]

Автосохранение после 19650 строк...
Автосохранение после 19680 строк...

Геокодирование:  99%|█████████▉| 19741/19990 [1:32:32<00:01, 173.52it/s]

Автосохранение после 19710 строк...
Автосохранение после 19740 строк...

Геокодирование:  99%|█████████▉| 19801/19990 [1:32:33<00:01, 173.55it/s]

Автосохранение после 19770 строк...
Автосохранение после 19800 строк...

Геокодирование:  99%|█████████▉| 19861/19990 [1:32:33<00:00, 179.82it/s]

Автосохранение после 19830 строк...
Автосохранение после 19860 строк...

Геокодирование: 100%|█████████▉| 19921/19990 [1:32:33<00:00, 180.12it/s]

Автосохранение после 19890 строк...
Автосохранение после 19920 строк...

Геокодирование: 100%|██████████| 19990/19990 [1:32:34<00:00,  3.60it/s]

Автосохранение после 19950 строк...
Автосохранение после 19980 строк...

Геокодирование завершено, результат сохранён.

In [14]:
# df1 = pd.DataFrame({
#     'address': [
#         'Russia, Saint-Peterburg, Nevskiy st.',
#         'Шотмана ул 4, г. Санкт-Петерубрг, Россия',
#                 'Шотмана ул 4, Санкт-Петербург',
#                 ' Санкт-Петербург, Россия, Санкт-Петербург, Шотмана ул 4'
#     ]
# })

# Инициализация геокодера
geolocator = Nominatim(user_agent="my_geocoder")

# RateLimiter, чтобы избежать блокировки за слишком частые запросы
geocode = RateLimiter(geolocator.geocode, min_delay_seconds=1)
df1 = df.head(20)
# Геокодируем
df1['location'] = df1['loc_for_geocoding'].apply(geocode)
df1['latitude'] = df1['location'].apply(lambda loc: loc.latitude if loc else None)
df1['longitude'] = df1['location'].apply(lambda loc: loc.longitude if loc else None)

print(df1[['loc_for_geocoding', 'latitude', 'longitude']])

                         loc_for_geocoding   latitude  longitude
0      Новаторов б-р 26к2, Санкт-Петербург        NaN        NaN
1       Колпинское ш 28к1, Санкт-Петербург  59.734334  30.469621
2   6-я Жерновская ул 9к1, Санкт-Петербург  59.963965  30.493054
3            Красное Село, Санкт-Петербург  59.733767  30.086246
4          Ольминского ул, Санкт-Петербург  59.898659  30.422142
5             Школьная ул, Санкт-Петербург  59.988245  30.290681
6      Ветеранов пр-т 114, Санкт-Петербург        NaN        NaN
7    Непокоренных пр-т 74, Санкт-Петербург        NaN        NaN
8        Ивановская ул 36, Санкт-Петербург  59.871835  30.434741
9     Маршала Жукова пр-т, Санкт-Петербург  59.825633  30.189795
10        Шотмана ул 12к3, Санкт-Петербург  59.899859  30.475575
11           Шотмана ул 4, Санкт-Петербург  59.900923  30.474623
12   Гаккелевская ул 27к2, Санкт-Петербург  60.003187  30.258668
13     Добровольцев ул 18, Санкт-Петербург  59.839364  30.170209
14     Гвардейская ул 8к2, Санкт-Петербург  59.735194  30.086000
15     Добровольцев ул 26, Санкт-Петербург  59.836929  30.166434
16         Взлетная ул 13, Санкт-Петербург  59.812071  30.286644
17        Искровский пр-т, Санкт-Петербург  59.909552  30.463269
18                Южное ш, Санкт-Петербург  59.866770  30.425933
19       Энергетиков пр-т, Санкт-Петербург  59.930742  30.435045

C:\Users\User\AppData\Local\Temp\ipykernel_8620\3087141660.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['location'] = df1['loc_for_geocoding'].apply(geocode)
C:\Users\User\AppData\Local\Temp\ipykernel_8620\3087141660.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['latitude'] = df1['location'].apply(lambda loc: loc.latitude if loc else None)
C:\Users\User\AppData\Local\Temp\ipykernel_8620\3087141660.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['longitude'] = df1['location'].apply(lambda loc: loc.longitude if loc else None)