In [2]:
import geopandas as gpd
from shapely.geometry import Point, MultiPolygon
from shapely.geometry import Point
import geopandas as gpd
import pandas as pd
from shapely import wkt

In [3]:
df_nspb = pd.read_csv(r'c:\Users\User\Documents\NIR3\files\ПОС_сообщения_geocoded_2.csv', sep=';')
df_nspb = df_nspb.drop_duplicates(subset=['text'])
df_nspb = df_nspb.dropna(subset=['longitude'])
df_nspb = df_nspb.dropna(subset=['text'])
df_nspb['geometry'] = df_nspb.apply(lambda row: Point(row['longitude'], row['latitude']), axis=1)
df_nspb

,Unnamed: 0,date,text,label_cat,loc_dist,loc_for_geocoding,source,source_cf,latitude,longitude,geometry
1,20.0,2022-02-23,Страшно ездить во дворе. Ещё пару дней и можно...,Дороги,Пушкинский,"Колпинское ш 28к1, Санкт-Петербург",ПОС,1.0,59.734334,30.469621,POINT (30.4696209 59.7343341)
2,21.0,2022-02-23,В этом году ни разу не проводилась Уборка терр...,Дороги,Красногвардейский,"6-я Жерновская ул 9к1, Санкт-Петербург",ПОС,1.0,59.963965,30.493054,POINT (30.4930543 59.9639645)
3,22.0,2022-02-23,"Не числятся проезды вдоль дома, нет посылки. З...",Транспорт,Красносельский,"Красное Село, Санкт-Петербург",ПОС,1.0,59.733767,30.086246,POINT (30.0862455 59.7337668)
4,23.0,2022-02-23,"Здравствуйте, дороги скользкие, невозможно дой...",Дороги,Невский,"Ольминского ул, Санкт-Петербург",ПОС,1.0,59.896931,30.418408,POINT (30.4184078 59.8969306)
5,24.0,2022-02-23,Не убраны снег и лёд между двумя зданиями парк...,Дороги,Приморский,"Школьная ул, Санкт-Петербург",ПОС,1.0,59.988425,30.292290,POINT (30.2922899 59.9884246)
...,...,...,...,...,...,...,...,...,...,...,...
19342,69385.0,2022-06-20,87 квартира делает ремонт. Вывозят мусор. От н...,ЖКХ,Центральный,"Конная ул 5/3, Санкт-Петербург",ПОС,1.0,59.928570,30.375114,POINT (30.3751142 59.9285702)
19343,69388.0,2022-06-20,Добрый день. В мае неожиданно узнал о якобы на...,ЖКХ,Кировский,"Корнеева ул 6, Санкт-Петербург",ПОС,1.0,59.885316,30.270127,POINT (30.2701272 59.8853161)
19344,69396.0,2022-06-20,Объявления на знаках прошу очистить,Транспорт,Невский,"Искровский пр-т, Санкт-Петербург",ПОС,1.0,59.909552,30.463269,POINT (30.4632685 59.9095518)
19345,69397.0,2022-06-20,Объявления на мачте,Транспорт,Невский,"Искровский пр-т, Санкт-Петербург",ПОС,1.0,59.909552,30.463269,POINT (30.4632685 59.9095518)
19346,69405.0,2022-06-20,Весь внутридворовый проезд от ул. Софьи Ковале...,Благоустройство,Калининский,NaN,ПОС,1.0,46.314475,11.048029,POINT (11.0480288 46.3144754)

In [5]:

# df_nspb['geometry'] = df_nspb['geometry'].apply(wkt.loads)
gdf_points_NSPB = gpd.GeoDataFrame(df_nspb, geometry='geometry', crs="EPSG:4326")

In [6]:
gdf = gpd.read_file(r'c:\Users\User\Documents\NIR3\files\MO.geojson', encoding='cp1251')
gdf["NAME"] = gdf["NAME"].apply(lambda val: val.replace("округ", "").strip())

In [7]:
gdf_joined = gpd.sjoin(
    gdf_points_NSPB,
    gdf[['geometry', 'NAME']],
    how='left',
    predicate='within'
)

In [8]:
gdf_joined

,Unnamed: 0,date,text,label_cat,loc_dist,loc_for_geocoding,source,source_cf,latitude,longitude,geometry,index_right,NAME
1,20.0,2022-02-23,Страшно ездить во дворе. Ещё пару дней и можно...,Дороги,Пушкинский,"Колпинское ш 28к1, Санкт-Петербург",ПОС,1.0,59.734334,30.469621,POINT (30.46962 59.73433),23.0,Шушары
2,21.0,2022-02-23,В этом году ни разу не проводилась Уборка терр...,Дороги,Красногвардейский,"6-я Жерновская ул 9к1, Санкт-Петербург",ПОС,1.0,59.963965,30.493054,POINT (30.49305 59.96396),102.0,Ржевка
3,22.0,2022-02-23,"Не числятся проезды вдоль дома, нет посылки. З...",Транспорт,Красносельский,"Красное Село, Санкт-Петербург",ПОС,1.0,59.733767,30.086246,POINT (30.08625 59.73377),17.0,Красное Село
4,23.0,2022-02-23,"Здравствуйте, дороги скользкие, невозможно дой...",Дороги,Невский,"Ольминского ул, Санкт-Петербург",ПОС,1.0,59.896931,30.418408,POINT (30.41841 59.89693),43.0,Невская застава
5,24.0,2022-02-23,Не убраны снег и лёд между двумя зданиями парк...,Дороги,Приморский,"Школьная ул, Санкт-Петербург",ПОС,1.0,59.988425,30.292290,POINT (30.29229 59.98842),56.0,Чёрная речка
...,...,...,...,...,...,...,...,...,...,...,...,...,...
19342,69385.0,2022-06-20,87 квартира делает ремонт. Вывозят мусор. От н...,ЖКХ,Центральный,"Конная ул 5/3, Санкт-Петербург",ПОС,1.0,59.928570,30.375114,POINT (30.37511 59.92857),29.0,Смольнинское
19343,69388.0,2022-06-20,Добрый день. В мае неожиданно узнал о якобы на...,ЖКХ,Кировский,"Корнеева ул 6, Санкт-Петербург",ПОС,1.0,59.885316,30.270127,POINT (30.27013 59.88532),47.0,Нарвский
19344,69396.0,2022-06-20,Объявления на знаках прошу очистить,Транспорт,Невский,"Искровский пр-т, Санкт-Петербург",ПОС,1.0,59.909552,30.463269,POINT (30.46327 59.90955),96.0,Невский
19345,69397.0,2022-06-20,Объявления на мачте,Транспорт,Невский,"Искровский пр-т, Санкт-Петербург",ПОС,1.0,59.909552,30.463269,POINT (30.46327 59.90955),96.0,Невский
19346,69405.0,2022-06-20,Весь внутридворовый проезд от ул. Софьи Ковале...,Благоустройство,Калининский,NaN,ПОС,1.0,46.314475,11.048029,POINT (11.04803 46.31448),NaN,NaN

In [9]:
gdf_joined.rename(columns={'NAME':'loc_mo'})

,Unnamed: 0,date,text,label_cat,loc_dist,loc_for_geocoding,source,source_cf,latitude,longitude,geometry,index_right,loc_mo
1,20.0,2022-02-23,Страшно ездить во дворе. Ещё пару дней и можно...,Дороги,Пушкинский,"Колпинское ш 28к1, Санкт-Петербург",ПОС,1.0,59.734334,30.469621,POINT (30.46962 59.73433),23.0,Шушары
2,21.0,2022-02-23,В этом году ни разу не проводилась Уборка терр...,Дороги,Красногвардейский,"6-я Жерновская ул 9к1, Санкт-Петербург",ПОС,1.0,59.963965,30.493054,POINT (30.49305 59.96396),102.0,Ржевка
3,22.0,2022-02-23,"Не числятся проезды вдоль дома, нет посылки. З...",Транспорт,Красносельский,"Красное Село, Санкт-Петербург",ПОС,1.0,59.733767,30.086246,POINT (30.08625 59.73377),17.0,Красное Село
4,23.0,2022-02-23,"Здравствуйте, дороги скользкие, невозможно дой...",Дороги,Невский,"Ольминского ул, Санкт-Петербург",ПОС,1.0,59.896931,30.418408,POINT (30.41841 59.89693),43.0,Невская застава
5,24.0,2022-02-23,Не убраны снег и лёд между двумя зданиями парк...,Дороги,Приморский,"Школьная ул, Санкт-Петербург",ПОС,1.0,59.988425,30.292290,POINT (30.29229 59.98842),56.0,Чёрная речка
...,...,...,...,...,...,...,...,...,...,...,...,...,...
19342,69385.0,2022-06-20,87 квартира делает ремонт. Вывозят мусор. От н...,ЖКХ,Центральный,"Конная ул 5/3, Санкт-Петербург",ПОС,1.0,59.928570,30.375114,POINT (30.37511 59.92857),29.0,Смольнинское
19343,69388.0,2022-06-20,Добрый день. В мае неожиданно узнал о якобы на...,ЖКХ,Кировский,"Корнеева ул 6, Санкт-Петербург",ПОС,1.0,59.885316,30.270127,POINT (30.27013 59.88532),47.0,Нарвский
19344,69396.0,2022-06-20,Объявления на знаках прошу очистить,Транспорт,Невский,"Искровский пр-т, Санкт-Петербург",ПОС,1.0,59.909552,30.463269,POINT (30.46327 59.90955),96.0,Невский
19345,69397.0,2022-06-20,Объявления на мачте,Транспорт,Невский,"Искровский пр-т, Санкт-Петербург",ПОС,1.0,59.909552,30.463269,POINT (30.46327 59.90955),96.0,Невский
19346,69405.0,2022-06-20,Весь внутридворовый проезд от ул. Софьи Ковале...,Благоустройство,Калининский,NaN,ПОС,1.0,46.314475,11.048029,POINT (11.04803 46.31448),NaN,NaN

In [10]:
gdf_joined.to_csv(r'c:\Users\User\Documents\NIR3\files\ПОС_сообщения_geocoded_2.csv', sep=';')